### ISSUE TITLE
XElement.Should().Match()

### ISSUE THREAD

**Issue by dennisdoomen** [fluentassertions/fluentassertions#1]
Because there are a lot more things to test than just both attributes and elements. 
Currently I use something like this: 

`XElement.As<XNode>().Should().Match<XElement>(x => x.Name == "foo")`

**Comment by leomicheloni** [comment]
Hi, 
 Is this still open? I would like to give it a try. Thanks!

**Comment by dennisdoomen** [comment]
Sure, I welcome PRs.

**Comment by dennisdoomen** [comment]
@leomicheloni do you still intent to pick this up?

**Comment by leomicheloni** [comment]
Hi @dennisdoomen , my apologies I had a really busy end of year. If nobody else is going to pick this up I can try to do that this month, just let me know if you are in a hurry about this issue or you can wait a little more. Thanks a lot!

**Comment by dennisdoomen** [comment]
No hurries.

**Comment by leomicheloni** [comment]
Hi, when I try to run the uni tests there are 86 failing, what I'm doing wrong? Thanks!

**Comment by dennisdoomen** [comment]
Which branch?

**Comment by dennisdoomen** [comment]
Just tried it on Rider 2017.3 and Visual Studio 2017 on my work machine and all runs fine. Can you share a stackdump/exception trace?

**Comment by krajek** [comment]
Regarding 86 failing tests, probably they were the same that I fixed in #726. I got the same number of failing tests in my non-English environment.

**Comment by leomicheloni** [comment]
I updated to the version that contains your changes and still have 86 failling test

**Comment by krajek** [comment]
Could you please attach a list of them, failure messages, or complete log?

**Comment by leomicheloni** [comment]
Sure thing
[testresults.txt](https://github.com/fluentassertions/fluentassertions/files/1628734/testresults.txt)

**Comment by krajek** [comment]
They are exactly the tests that failed for me. I had double checked that InvariantCulture is properly used everywhere now.

The thing that makes me think you are using some different source that HEAD is that in your first failing assert there is:
`Expected exception message to match the equivalent of 
[13/01/2018 21:33:16 Informational] [xUnit.net 00:00:03.1042436]       "Expected value to not approximate*3,14* +/-*0,001*, but it was <null>."`

whereas in the source can there is 
`.WithMessage("Expected value to not approximate*3.14* +/-*0.001*, but it was <null>.");`
Notice, that your assert message contains `3.14`, the source code has `3.14`.

Any idea how this could happen?

**Comment by leomicheloni** [comment]
Yeap, you're right, now all test pass, my bad. Thanks!

**Comment by leomicheloni** [comment]
Ok, I'been peeking around the code and this issue, I think I don't totally undestand the requirement, is there any chance to provide a more detailed scenario so I can understand what to do. I'm really sorry but I really don't got it.
Thanks!

**Comment by dennisdoomen** [comment]
Basically we want to have an assertion named `Match` that takes a predicate on an `XElement`. And when that predicate returns `false`, it should throw a failure message. We have something similar on `ObjectAssertions`

**Comment by dennisdoomen** [comment]
Anything you need to get this one going?

**Comment by dennisdoomen** [comment]
@leomicheloni  you're still working on this?

**Comment by leomicheloni** [comment]
Hi, I'm apologize, I really wasn't able to implement the feature, it's just too complex for me :( .

**Comment by vanashimko** [comment]
Is this still relevant? I tried
```csharp
new XElement("test").Should().Match(x => x.HasAttributes);
```
and it failed as expected. 

Given that this issue has number "1", maybe it was lost and should be closed now?

**Comment by dennisdoomen** [comment]
You're right. It's old.
