### ISSUE TITLE
Assertion that asynchronous operation completes within time span

### ISSUE THREAD

**Issue by lg2de** [fluentassertions/fluentassertions#1001]
Testing asynchronous operations is currently available like this:
```cs
this.myServer.Invoking(s => s.OpenAsync).Should().NotThrow();
```

I'm missing the option just check, that the operation will complete (and not throw) within specific time range. Therefore a new assertion could be created:
```cs
this.myServer.Invoking(s => s.OpenAsync).Should().Complete(TimeSpan.FromMilliseconds(100));
```

Such an idea I already mentioned in #990.

While thinking about the implementation I found a different approach.
Why to I need the indirection using "Invoking"? Why not asserting the Task directly:
```cs
this.myServer.OpenAsync().Should().Complete(TimeSpan.FromMilliseconds(100));
```

**Comment by bitbonk** [comment]
I have come across this problem too. Sometimes those asynchronous operations that are being tested may never complete or may take an unusual long time to complete. As a result, the whole test run takes forever to complete. 

Sometimes I just want a test to fail if the asynchronous operation does not complete within a given amount of time. In most cases actually *is* something wrong if a task takes forever to complete.

**Comment by bitbonk** [comment]
One more thing: What should happen to those tasks that did not complete in case the assertions failed? Is here a problem if tasks stay alive after the test is done? If there is a `CancellationToken`, can FA take care of cancelling those tasks?

**Comment by lg2de** [comment]
So, @bitbonk, you prefer following the Invoking pattern?
Thinking about again, the timing may be more exact than working on the Task directly.
But, the approach without `Invoking` would be shorter.

Regarding the `CancellationToken` I do not see an option for FA.
But using e.g. xUnit the testing framework can take care, isn't it?

**Comment by dennisdoomen** [comment]
> If there is a CancellationToken, can FA take care of cancelling those tasks?

The `CompleteWithin` could take the cancellation token as a parameter, but it won't be very intuitive.

**Comment by lg2de** [comment]
@dennisdoomen, which approach you prefer? Based on Invoking or directly on the Task?

**Comment by dennisdoomen** [comment]
Both ;-)

**Comment by lg2de** [comment]
> Both ;-)

äähhmmm, oooh...
I'll try to do my best.

**Comment by ArndtMichael** [comment]
I would prefer handling with the Task directly because:
The assertion is related to exactly that task and not that one Invoking returns. It's more clear what happens.

**Comment by lg2de** [comment]
Hi @dennisdoomen and @jnyrup, you remember my attempt to contribute this extension?

Today we have simlar extension with the Invoking feature. Fine, so far.
In my team will still have a private extension for the assertion directly on `Task`. I would like to discuss again with you, whether and how to get this in the official FA.

We like the very short version I mentioned initially:
```cs
this.myServer.OpenAsync().Should().CompleteWithin(100.MilliSeconds());
```

You did not want to introduce this because it is an overlay of the `ObjectAssertions`.
With this approach some methods will be unavailable. Lets have a look in detail:

|Methods|Comment|
|---|---|
|(Not)Be|How to assert equality of tasks?|
|(Not)BeEquivalentTo|How to assert similarity of tasks?|
|HaveFlag|Tasks are not enums.|
|(Not)BeNull|Using asynchronous programming you should never have `null` Tasks. This should be checked implicitly.|
|(Not)BeSameAs|Why should I ever expect that two Tasks are the same instance?|
|(Not)BeOfType/BeAssignableTo|Using asynchronous programming you should only use `Task` and `Task<T>`, isn't it?|
|Match|This could be a useful method which we could add.|

So, I can identify only a single method which can be used used reasonable on Tasks in the current API. This one can be added to be compatible.
Additionally I would be possible to inherit from `ObjectAssertions` or `ReferenceTypeAssertions`.

Further you mentioned the timing may be inaccurate because the task is already running when check timer is started.
For me this is not an issue. This extension is intended as timeout for a single operation without creating `CancellationTokenSource` every time. It should just ensure that e.g. complex tests (mainly integration tests) will fail early with clear information on blocking step.

What do you think today? Additional questions to discuss?

**Comment by dennisdoomen** [comment]
If I recall correctly, the main problem was the discussion around `Task` vs `Func<Task>`, right?

**Comment by lg2de** [comment]
`Func<Task>` is already implemented. 
In addition I would like to have `Task`.

**Comment by jnyrup** [comment]
The timing accuracy is a minor problem of assertion directly on `Task`.
A bigger problem with asserting directly on `Task` is that not every assertion available on `Func<Task>` makes sense for `Task`.
E.g. `NotThrow()` as `myTask` may throw before we get a change to `await` it.
```c#
myTask.Should().NotThrow();
```

While we could leave the exception testing assertions out of the API for `Task`, that would (in my opinion) give a fragmented API where most assertions are available on `Task` but some only on `Func<Task>`.
I don't doubt that the people commenting in this thread are experienced enough to know when to use which type of assertion, but I think it would make it harder for newcomers.

**Comment by dennisdoomen** [comment]
_If_ we support it, we would have to do it in a consistent way. So every assertion that you can run on a `Func<Task>` should also become available on `Task`.

**Comment by bitbonk** [comment]
To be honest I don't really see a problem, if the assertions available on `Task` differ from the ones available on `Func<Task>`.  It is not that a novice user would be able to use assertions that do not work. It is just that some are just not available. Novice users are still guided 100% by intellisense.

More importantly: Similar things already exists in the synchronous equivalent. There I also can't just do `SutMethod.Should().NotThrow<Exception>()`. I have to wrap it into an `Action`: `new Action(_ => SutMethod()).Should().NotThrow<Exception>()`. 

If we would do the same thing for tasks (having to wrap it into a `Func<Task>`) it would seem pretty consistent to me.

**Comment by lg2de** [comment]
I think, discussion is completed so far.
