### ISSUE TITLE
Tests are language dependent

### ISSUE THREAD

**Issue by lg2de** [fluentassertions/fluentassertions#1003]
I wondered why some tests fail while your build seams to complete successfully.

I found, that some tests are language dependend, e.g. `When_asserting_collections_not_to_be_equal_but_expected_collection_is_null_it_should_throw`:
```cs
act.Should().Throw<ArgumentNullException>().WithMessage(
    "Cannot compare collection with <null>.*Parameter name: unexpected");
```

The test verifies the text from exception, but the ArgumentNullException generates text depending on user/windows settings. On my (german) system the text is "Parametername" instead of "Parameter name".

I see three options:
1. remove (always) language dependend part of verified message ("Cannot compare collection with <null>.*: unexpected")
2. run all tests explicitely with english locale (either in build.ps1 or [better] within the test)
3. introduce and use UseCultureAttribute from [xUnit samples](https://github.com/xunit/samples.xunit/blob/master/UseCulture/UseCultureAttribute.cs)

What do you think?
For me, option 3 would be the best.

**Comment by dennisdoomen** [comment]
I would go for option 2. I would always code in English. In the Netherlands, it's quite common to work with non-Dutch developers. 

Regardless, this issue is not related to Fluent Assertions.

**Comment by lg2de** [comment]
Hi @dennisdoomen, I think this is a misunderstandig: I was talking about the Unit Tests of FluentAssertions. So, it is related to FA.
I'm coding in English, but other things are fine in German. So, I would like to have configured my Windows to German. But THAN "your" Fluent Assertions Unit Tests will fail.

I think, this should be fixed. The tests should NOT be related to the language selected for the OS they are running on!
