### ISSUE TITLE
double.Should().BeApproximately

### ISSUE THREAD

**Issue by candychiu** [fluentassertions/fluentassertions#101]
Hi,

Would you point me to how the approximate functions are exposed in the new version?

Thanks.

**Comment by ravensorb** [comment]
It looks like this doesn't work with Nullable Expressions?

This is not working
```
double? d = 1.01234;

d.Should().BeApproximately(1.01, 1.0);   <-- compile error
```

**Comment by brarui** [comment]
you should use the 'm' to give decimal values.
worked for me.

d.Should().BeApproximately(1.01m, 0.01m);
