### ISSUE TITLE
BeEquivalentTo on double collections

### ISSUE THREAD

**Issue by Brondahl** [fluentassertions/fluentassertions#1010]
```c#
new List<double> { 0.02 }.Should().BeEquivalentTo(0   );
new List<double> { 0    }.Should().BeEquivalentTo(0.02);
new List<double> { 0.02 }.Should().BeEquivalentTo(0.00);
new List<double> { 0.00 }.Should().BeEquivalentTo(0.02);
```
The first line passes, all the others fail.

I can see an argument for ".BeEquivalentTo()" isn't, in general, meaningful on collections of doubles/floats, in the same way that ".Be()" or ".BeEqualTo()" isn't.
But it should at least be self-consistent, shouldn't it?

### Versions
FA v5.6.0
.Net Fmwk 4.6.1
C# 7.3

**Comment by dennisdoomen** [comment]
You're right. Although I can't think of a way how the first line could pass.

**Comment by jnyrup** [comment]
The problem happens in `IsSameOrEqualTo` where both the subject `0.02` and the expectation `0` are boxed as objects.
```
var convertedActual = Convert.ChangeType(actual, expected.GetType());
```

As the conversion is driven by the type of the expectation (`int`), `actual` (`0.02`) is converted from a boxed double to a boxed `int` with value `0`.

**Comment by dennisdoomen** [comment]
Of course it is ;-)

I see two options:
1. Do a two-way comparison. I.o.w., first convert the subject to the expectation and compare then. If they are not the same, do the reverse and try again
2. Only convert to a "more relaxed" type. So we convert an `int` to `float` and a `float` to a `double`, but not the other way around

**Comment by dennisdoomen** [comment]
Any opinions?

**Comment by jnyrup** [comment]
Is the `Convert.ChangeType` part supposed to be used for anything but comparing numeric types?
If I remove it, only `When_numvercalues_convertible_it_should_treat_them_as_equivalent`.

From https://www.sevecek.com/EnglishPages/Lists/Posts/Post.aspx?ID=62 it seems we could use `(dynamic)actual == (dynamic)expected` to compare the numbers. 
More information is found in the bottom of https://ericlippert.com/2009/03/03/representation-and-identity/
The good thing is that is puts the burden on casting the two objects on the runtime.
The (maybe) less good thing is that this puts a dependency on `Microsoft.CSharp` (already included in net45, net47, netcoreapp20)

A workaround, which seems to work, is to convert `convertedActual` back to `actual.GetType()` and compare it to `actual` to see if there was any loss of precision.

**Comment by jnyrup** [comment]
The mentioned workaround 
 https://github.com/jnyrup/fluentassertions/commit/001923f09783f23fbad01abb0904691063f3f53a

**Comment by Brondahl** [comment]
Whoop! Thanks guys :)
What version will this be released in; and what's the likely ETA on that release?

**Comment by jnyrup** [comment]
This will be part of 5.10.0.
We're striving to release it this month.
