### ISSUE TITLE
Shorter syntax for exception assertions

### ISSUE THREAD

**Issue by ejball** [fluentassertions/fluentassertions#1015]
I'd like to be able to perform [exception assertions](https://fluentassertions.com/documentation/#exceptions) in a single statement, without using the `subject.Invoking(...)` pattern (e.g. for calling static methods), and without having to create an `Action` variable first.

I propose a static class with `Invoking`, `Awaiting`, and `Enumerating` methods for this purpose, e.g.:

```csharp
public static class FluentAction
{
    public static Action Invoking(Action action) => action;
    public static Func<T> Invoking<T>(Func<T> func) => func;
    public static Func<Task> Awaiting(Func<Task> action) => action;
    public static Func<Task<T>> Awaiting<T>(Func<Task<T>> func) => func;
    public static Action Enumerating(Func<IEnumerable> enumerable) => enumerable.Enumerating();
    public static Action Enumerating<T>(Func<IEnumerable<T>> enumerable) => enumerable.Enumerating();
}
```

Used like so:

```csharp
FluentAction.Invoking(() => MyClass.Create(null)).Should().Throw<ArgumentNullException();
```

Or even:

```csharp
using static FluentAssertions.FluentAction;

...

Invoking(() => MyClass.Create(null)).Should().Throw<ArgumentNullException();
```

**Comment by dennisdoomen** [comment]
That's the first time I see a useful example of the new `using static` [directive[(https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-static).

**Comment by jnyrup** [comment]
I like it, a lot prettier than the equivalent inline version:
```c#
((Func<T>)(() => MyClass.Create(null))).Should().Throw<ArgumentNullException();
```

Related to #872

**Comment by jnyrup** [comment]
Contributed in #1017 
Will be available in next release.
