### ISSUE TITLE
Add `async`-support for `WithMessage()`

### ISSUE THREAD

**Issue by mu88** [fluentassertions/fluentassertions#1052]
### Description
It would be great to use `WithMessage()` on `ThrowAsync<>()`.

### Complete minimal example reproducing the issue
```csharp
// Arrange
Func<Task> act = () => throw new InvalidOperationException("Hello World");

// Act & Assert
await act().Should().ThrowAsync<InvalidOperationException>().WithMessage("HelloWorld");
```

### Actual behavior:
Compile-time error. If have to await/block the Task to use `WithMessage()` (e. g. `await act().Should().ThrowAsync<InvalidOperationException>().Result.WithMessage("HelloWorld");`).

### Versions
5.6.0

**Comment by jnyrup** [comment]
Currently you need to `await` the `ThrowAsync` before calling `WithMessage`.
```c#
(await act().Should().ThrowAsync<InvalidOperationException>()).WithMessage("HelloWorld");
```
note the extra parentheses.

To avoid those parentheses you could create an extension method like this
```c#
public static async Task<ExceptionAssertions<TException>> WithMessage<TException>(
    this Task<ExceptionAssertions<TException>> task,
    string expectedWildcardPattern,
    string because = "",
    params object[] becauseArgs)
    where TException : Exception
{
    return (await task).WithMessage(expectedWildcardPattern, because, becauseArgs);
}
```

and then call
```c#
await act().Should().ThrowAsync<InvalidOperationException>().WithMessage("HelloWorld");
```

**Comment by mu88** [comment]
Works like a charm! Is it okay for you if I provide this extension method as a PR?

**Comment by dennisdoomen** [comment]
Absolutely!

**Comment by jnyrup** [comment]
Contributed in #1055
