### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#1081]
Go to https://fluentassertions.com/introduction
Click on "Documentation" in the sidebar
Boom, page not found.

Go to https://fluentassertions.com/basicassertions/
click on "Detecting Test Frameworks"
Boom, page not found.

**Comment by dennisdoomen** [comment]
There's something with extra backslashes. When I run this locally, it's fine. Already fixed two of them.

**Comment by jnyrup** [comment]
We still have broken links:

https://fluentassertions.com/
    click "read more" (https://fluentassertions.com/documentation/)

Maybe we should stick to https://fluentassertions.com/documentation/ to avoid too many broken links around the web?
E.g. Links to documentation in https://www.continuousimprover.com/2018/02/fluent-assertions-50-best-unit-test.html are broken and a quick [search](https://www.google.com/search?q=site%3Astackoverflow.com+%22fluentassertions.com%2Fdocumentation%22&oq=site%3Astackoverflow.com+%22fluentassertions.com%2Fdocumentation%22&aqs=chrome..69i57j69i58.6657j0j7&sourceid=chrome&ie=UTF-8) gave 80 results on StackOverflow that are probably broken.

https://fluentassertions.com/basicassertions/
    click "Detecting Test Frameworks" doesn't work.

**Comment by dennisdoomen** [comment]
![image](https://user-images.githubusercontent.com/572734/59552480-d0537c80-8f87-11e9-901e-e866c7f4f36b.png)
