### ISSUE TITLE
String .BeEquivalentTo() is case-sensitive on linux

### ISSUE THREAD

**Issue by nvborisenko** [fluentassertions/fluentassertions#1096]
It seems that `BeEquivalentTo()` doesn't ignore case when comparing strings on **Linux** environment.

```csharp
"SomeString".Should().BeEquivalentTo("somestring");
```

Expected: verification passes.

It works as expected on **Windows**, but throws `but "SomeString" differs near "Som" (index 0)` exception on **Linux**.

On the same environment string assertion from NUnit framework works as expected.
```csharp
StringAssert.AreEqualIgnoringCase("SomeString", "somestring");
```

Info:
- FluentAssertions v5.7.0
- .netcoreapp 2.1

**Comment by jnyrup** [comment]
[`StringAssertions.BeEquivalentTo`](https://github.com/fluentassertions/fluentassertions/blob/master/Src/FluentAssertions/Primitives/StringAssertions.cs#L96) uses `StringComparison.CurrentCultureIgnoreCase` which as far as I known queries the OS to determine the culture.

See e.g. https://github.com/dotnet/corefx/issues/17052

What Culture does .net core gets for you on your linux machine?
```c#
System.Globalization.CultureInfo.CurrentCulture.Name
```c#

**Comment by dennisdoomen** [comment]
That's weird indeed.

**Comment by dennisdoomen** [comment]
> you may check the values of the environment variables LC_MESSAGES and LC_ALL in your system.

and

> You may look at https://github.com/dotnet/coreclr/blob/master/src/corefx/System.Globalization.Native/locale.cpp#L123 for how we get the default user locale. in short, we call ICU function uloc_getDefault() to get the default locale.

So if that returns `en_US_POSIX`, it explains the weird behavior. It has nothing to do with Fluent Assertions, but some special behavior of .NET Core on this specific Linux locale.

**Comment by nvborisenko** [comment]
Will provide details about environment in 1 week.

**Comment by nvborisenko** [comment]
CurrentCulture: `en-US-POSIX`
LC_MESSAGES: `there is no env variable`
LC_ALL: `C.UTF-8`

I execute tests on Amazon Cloud Code Build (I guess OS is Ubuntu).

**Comment by eNeRGy164** [comment]
> So if that returns `en_US_POSIX`, it explains the weird behavior. It has nothing to do with Fluent Assertions, but some special behavior of .NET Core on this specific Linux locale.

You could switch to `StringComparison.OrdinalIgnoreCase` explicitly for comparisons? This would prevent fallback to OS specific comparison?

It is tricky, I discovered for example the `string.Equals` uses `Ordinal` (case sensitive, culture insensitive). But `string.StartsWith` and `string.Endswith` are using `CurrentCulture` by default.

**Comment by dennisdoomen** [comment]
> You could switch to StringComparison.OrdinalIgnoreCase explicitly for comparisons

You mean in FA?

**Comment by eNeRGy164** [comment]
> > You could switch to StringComparison.OrdinalIgnoreCase explicitly for comparisons
> 
> You mean in FA?

Yeah, I find it strange that about half of the StringAssertions use Ordinal, and half use CurrentCulture. It is probably a breaking change. But having code be asserted differently depending on your machine is also not expected I guess.

**Comment by kimsey0** [comment]
This also happens in other environments. For example, the `Should_pass_when_contains_equivalent_of(actual: "aa", equivalentSubstring: "A")` test fails when run on a machine with the `da-DK` (Danish) locale in both .NET Core 2, .NET Core 3, and .NET Framework 4. The behavior can be seen by running this in a REPL:

``` cs
Thread.CurrentThread.CurrentCulture = new CultureInfo("da-DK");
Debug.Assert("aa".IndexOf("A", StringComparison.CurrentCultureIgnoreCase) >= 0);
```

I think it would make sense for Fluent Assertions to use ordinal comparisons by default. (If not, `Should_pass_when_contains_equivalent_of` and other culture-sensitive unit tests should set the culture.)

**Comment by dennisdoomen** [comment]
> It is probably a breaking change.

I think it'll be fine.

**Comment by kimsey0** [comment]
I'll be happy to create a pull request that changes these methods to use ordinal comparison.

However, normally I'd also add some regression tests, but that seems less than simple. The tests would need to set `Thread.CurrentThread.CurrentCulture`/`CultureInfo.CurrentCulture`, and I'm not sure of the exact effects of affecting the _ambient context_ like that when running the tests in parallel.

The problem has been discussed at https://github.com/xunit/xunit/issues/1605. The test project used to test Xunit does include a `[CulturedTheory]` attribute, but it's not shipped with Xunit, and it's quite a bit of code, so I'm not sure I'd want to just copy-paste it into Fluent Assertions:
- https://github.com/xunit/xunit/blob/master/test/test.utility/CultureAwareTesting/CulturedTheoryAttribute.cs
- https://github.com/xunit/xunit/blob/master/test/test.utility/CultureAwareTesting/CulturedTheoryAttributeDiscoverer.cs
- https://github.com/xunit/xunit/blob/master/test/test.utility/CultureAwareTesting/CulturedXunitTheoryTestCase.cs
- https://github.com/xunit/xunit/blob/master/test/test.utility/CultureAwareTesting/CulturedXunitTheoryTestCaseRunner.cs

How would you handle this? Just not test this change?

**Comment by jnyrup** [comment]
I wouldn't mind including the extra xunit code.
It could maybe combine it with `[CollectionDefinition]` to disable parallelization for those tests mingling with the `CurrentCulture`, see an example in [`AssertionOptionSpecs.cs`](https://github.com/fluentassertions/fluentassertions/blob/master/Tests/Shared.Specs/AssertionOptionSpecs.cs#L29)
