### ISSUE TITLE
Confusing failure message in Should().BeAssignableTo(...)

### ISSUE THREAD

**Issue by Tyrrrz** [fluentassertions/fluentassertions#1103]
### Description

When `Should().BeAssignableTo(...)` fails, it leaves a confusing message.

### Complete minimal example reproducing the issue

```csharp
((object) null).Should().BeAssignableTo(typeof(string));
```

### Expected behavior:

`Expected an object assignable to System.String, but found <null> instead.`

### Actual behavior:

`Expected type not to be System.String, but found <null>.`

### Versions

* Which version of Fluent Assertions are you using?

5.7.0

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.

.NET 4.6

### Additional Information

![image](https://user-images.githubusercontent.com/1935960/61993371-a8b9fe80-b073-11e9-8060-803dbc685883.png)

**Comment by Tyrrrz** [comment]
Thank you ❤️

**Comment by jnyrup** [comment]
Just a heads up: 5.8.0 has been released with the fix for this.
