### ISSUE TITLE
Unused TestFrameworks

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#1108]
In e039dae1 `Src/FluentAssertions.Dotnet/Execution/TestFrameworkProvider.cs` was deleted, which was the only file that referenced `NUnitPclTestFramework` and `MSTestFrameworkRT`.
The cross-compiled `TestFrameworkProvider` does not reference any of those two classes.

Is that an error or should the two classes just be deleted?

**Comment by dennisdoomen** [comment]
I think they are leftovers from 4.x.
