### ISSUE TITLE
Different output on Action within AssertionScope

### ISSUE THREAD

**Issue by dariusz-wozniak** [fluentassertions/fluentassertions#1128]
Running the following code:

```csharp
[Test]
public void Bug()
{
    Action act = () =>
    {
        (2 + 2).Should().Be(5);
        (2 + 2).Should().Be(5);
    };

    using (new AssertionScope())
    {
        act();
    }
}
```

...yields different results on Debug and Release.

Debug output:

```
Expected (2 + 2) to be 5, but found 4.
Expected (2 + 2) to be 5, but found 4.
```

Release output:

```
Expected (2 + 2) to be 5, but found 4.
Expected value to be 5, but found 4.
```

Release output seems to do not recognize the last assertion. In case of _n_ number of assertions (i.e. `(2 + 2).Should().Be(5)`), always only the last one is shown improperly.

E.g. for 5 assertions:

```
Expected (2 + 2) to be 5, but found 4.
Expected (2 + 2) to be 5, but found 4.
Expected (2 + 2) to be 5, but found 4.
Expected (2 + 2) to be 5, but found 4.
Expected value to be 5, but found 4.
```

### Versions

* FluentAssertions 5.9.0
* .NET Core 2.2

**Comment by dennisdoomen** [comment]
Including the name of the subject in the output requires a debug build, but it in a release mode it should consistently fall back on `value`

**Comment by jnyrup** [comment]
I'm quite sure the experienced behavior is similar to #1125 
See my diagnosis here https://github.com/fluentassertions/fluentassertions/issues/1125#issuecomment-533776096

**Comment by jnyrup** [comment]
I'll close this for now, if anyone comes it with an idea for an improvement, feel to open a new issue.
