### ISSUE TITLE
API approval tests

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#1133]
### Description

In order to help not breaking semantic versioning, we should include API approval tests to verify that any changes to the public API of each targeting framework are explicitly verified.

FakeItEasy does this quite neatly using [PublicApiGenerator](https://github.com/JakeGinnivan/ApiApprover).
See https://github.com/FakeItEasy/FakeItEasy/tree/master/tests/FakeItEasy.Tests.Approval

**Comment by dennisdoomen** [comment]
We use the same approach in our project and it works quite well.
