### ISSUE TITLE
How to test dependencies when exceptions are thrown

### ISSUE THREAD

**Issue by davidkeaveny** [fluentassertions/fluentassertions#1135]
Hi,

I am using FluentAssertions 5.9.0 to test a .NET Core 2.2 library that I am working on. In that library, I have a class which decorates another class which is doing some SQL operations; if the decorator detects that an unhandled SQL exception bubbles up from the inner class, and that exception is related to a deadlock, it does an automatic retry of the failed operations and writes to the logger (e.g. number of retries, retry interval).

It's easy enough to have FluentAssertions verify that when a deadlock exception is thrown, it gets caught by my SUT and retried, using an action:

```
var handler = Substitute.For<IHandler>();
handler.Handle().Throws(new NastyDeadlockException());

var logger = Substitute.For<ILogger>();

var sut = new DeadlockHandler(Logger, Handler);
Action operation = () => sut.Handle();
operation.Should().Throw<NastyDeadlockException>();
```

But what I want to be able to do is verify whether the SUT has written to the logger, in addition to having rethrown the exception (or even, in the event that a retry completed successfully, that no exception was rethrown and the logger was still written to).

Do you have any suggestions as to how to use the fluent syntax to include assertions on my dependencies, in addition to the `Should().Throw` or `Should().NotThrow` assertions?

**Comment by dennisdoomen** [comment]
Why don't you use NSubstitute's specific assertions for that?

**Comment by danielmpetrov** [comment]
Verification is something mocking libraries provide, maybe you should look into that.

I'm not familiar with NSubstitute, but after a quick Google search, I believe this might be of interest to you - https://nsubstitute.github.io/help/received-calls/

Your problem seems out of scope for Fluent Assertions, good luck.

**Comment by jnyrup** [comment]
Closing as this seems to be answered.
If not, feel free to re-open.
