### ISSUE TITLE
Collections containing nulls do not compare equivalent

### ISSUE THREAD

**Issue by bacar** [fluentassertions/fluentassertions#1139]
# Description

Collections containing nulls do not always appear to compare equivalent.

### Complete minimal example reproducing the issue

```csharp
{
    var actual = new int?[] { null, 1 };
    actual.Should().BeEquivalentTo(new int?[] { 1, null }); // passes
    actual.Should().BeEquivalentTo(new int?[] { null, 1 }); // passes
}
{
    var actual = new int?[] { 1, null };
    actual.Should().BeEquivalentTo(new int?[] { 1, null }); // passes
    actual.Should().BeEquivalentTo(new int?[] { null, 1 }); // passes
}
{
    var actual = new object[] { null, 1 };
    actual.Should().BeEquivalentTo(new object[] { 1, null }); // passes
    actual.Should().BeEquivalentTo(new object[] { null, 1 }); // passes
}
{
    var actual = new object[] { 1, null };
    actual.Should().BeEquivalentTo(new object[] { 1, null }); // passes
    actual.Should().BeEquivalentTo(new object[] { null, 1 }); // FAILS
}
```

### Expected behavior:

I expect all 8 of the very similar assertions to succeed. Should I?

### Actual behavior:

8th assertion fails with: `Expected item[0] to be <null>, but found 1.`

### Versions

* Which version of Fluent Assertions are you using? - *5.9.0*
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0. - *.Net Framework 4.7.2*

**Comment by bacar** [comment]
I note that the first four assertions (which take `int?[]`) resolve to `BeEquivalentTo<TExpectation>(      IEnumerable<TExpectation> expectation, string because = "", params object[] becauseArgs)`, whilst the latter four resolve to `BeEquivalentTo(params object[] expectations)`.

However, I observe very similar problematic behaviour with:

```csharp
{
    var actual = new List<object[]> { new object[] { null }, new object[] { 1 }, };
    actual.Should().BeEquivalentTo(new List<object[]> { new object[] { null }, new object[] { 1 } }); // passes
    actual.Should().BeEquivalentTo(new List<object[]> { new object[] { 1 }, new object[] { null } }); // passes
}
{
    var actual = new List<object[]> { new object[] { 1 }, new object[] { null }, };
    actual.Should().BeEquivalentTo(new List<object[]> { new object[] { 1 }, new object[] { null }, }); // passes
    actual.Should().BeEquivalentTo(new List<object[]> { new object[] { null }, new object[] { 1 }, }); // FAILS
}
```


...which all resolve to the first overload.

**Comment by jnyrup** [comment]
Sounds related to #1036

**Comment by bacar** [comment]
Potentially. Perhaps I have a mistaken understanding of how types that are `object` at compile time should be compared.
