### ISSUE TITLE
Chaining assertions without needing to use .And()

### ISSUE THREAD

**Issue by CaseyPlummer** [fluentassertions/fluentassertions#1146]
This is an idea/suggestion.

The current API requires the use of .And():
`testValue.Should().BeInRange(1, 20).And.NotBe(13);`

Not sure if it possible. but wouldn't it be more terse like this?:
`testValue.Should().BeInRange(1, 20).NotBe(13);`

**Comment by jnyrup** [comment]
In any case I would prefer the first one as it reads closer to regular prose.

From a technical point of view most assertions return an `AndConstraint` that only has an `And` property for chained assertions. 
Some other assertions return an `AndWhichConstraint` that also has a `Which` property that can be used for chained assertion on verified assertions.

```c#
list.Should().ContainSingle()
    .Which.Should().Be(42);
```

When returning an `AndWhichConstraint` we need to be able to distinguish between `And` and `Which` to know whether the upcoming assertion is to be performed on the same object or inner object.

Using `And` disregarding of the type of returned `Constraint` keeps a uniform API.
