### ISSUE TITLE
Explicit subject name

### ISSUE THREAD

**Issue by CaseyPlummer** [fluentassertions/fluentassertions#1147]
This is an idea/suggestion.

Could a method be added to explicitly provide the subject name under test? For situations where the debug symbols might not be available or performance is a concern.

`testValue.Should().BeInRange(1, 20).WithName(nameof(testValue));`

**Comment by dennisdoomen** [comment]
This does not work technically since assertions like `BeInRange` don't allow any successive code to be executed. You _can_ however wrap you assertion in a `using AssertionScope("some name")` block
