### ISSUE TITLE
BeEquivalentTo Excluding can't recursive child by same regulation

### ISSUE THREAD

**Issue by t628x7600** [fluentassertions/fluentassertions#1153]
### Description
Hi! I have a problem with BeEquivalentTo. I use Excluding it can't  work to my expectation.
Excluding can't  recursive sub property with same regulation
E.g.
//csharp
```
public class MyClass
{
	public int Id { get; set; }
	public string describe { get; set;}
	public MyClass parent;
}

//Act 
var act = new MyClass
{
	Id = 1,
	describe = "Hello",
	parent = new MyClass
	{
		Id = 2,
		describe = "hay"
	}
}

var expect = new MyClass
{
	Id = 3,
	describe = "Hello",
	parent = new MyClass
	{
		Id = 4,
		describe = "hay"
	}
}
// Assert
act .Should().BeEquivalentTo(expect , cfg => cfg.Excluding(src => src.id));
```

### Expected behavior:
Expected behavior be pass

I know can use
```
act.Should().BeEquivalentTo(expect, cfg => cfg.Excluding(src => src.id)
	.Excluding(src => src.parent.id));
```

I can do it
but it not my expected solution 
```
var act = new MyClass
{
	Id = 1,
	describe = "Hello",
	parent = new MyClass
	{
		Id = 2,
		describe = "hay"
		parent = new MyClass
		{
			Id = 3,
			describe = "John"
		}
	}
}

var expect = new MyClass
{
	Id = 4,
	describe = "Hello",
	parent = new MyClass
	{
		Id = 5,
		describe = "hay"
		parent = new MyClass
		{
			Id = 6,
			describe = "John"
		}
	}
}
act.Should().BeEquivalentTo(expect, cfg => cfg.Excluding(src => src.id)
	.Excluding(src => src.parent.id)
	.Excluding(src => src.parent.parent.id));
```
### Versions

* Which version of Fluent Assertions are you using? 5.6.0
* Which .NET runtime and version are you targeting? E.g. NET Core 2.2

**Comment by dennisdoomen** [comment]
The `Excluding` option always assumes the root as the start of the property path. So it does exactly as it is designed to. If you want to always exclude the `Id` property of `MyClass`, you can do something like `cfg.Excluding(ctx => ctx.SelectedMemberPath.EndsWidth("Id"))`

**Comment by IAmTomaton** [comment]
Why can't I call SelectedMemberPath? I have the latest version of the library.
