### ISSUE TITLE
Order by multiple properties sequentially

### ISSUE THREAD

**Issue by d1mnewz** [fluentassertions/fluentassertions#1160]
This is an idea / feature request:

It makes sense to enable sequential ordering. 
My use-case is that I want to verify that a collection was sorted first by a Name, then by Id. 

Is there any way of doing that using assertions such as `BeInAscendingOrder` and not by using predefined expected collection? 
My expectation was to have something like `results.Should().BeInAscendingOrder(x => x.Name).And.BeInAscendingOrder(x => x.Id);`

**Comment by dennisdoomen** [comment]
Chaining won't work, but there _is_ an overload that takes an `IComparer<T>`.

**Comment by rvplauborg** [comment]
I guess this issue should be closed after the merge of 1416? :)

**Comment by dennisdoomen** [comment]
You are right. Thanks for the reminder.
