### ISSUE TITLE
Xml code doc is outdated

### ISSUE THREAD

**Issue by mitikov** [fluentassertions/fluentassertions#1162]
https://github.com/fluentassertions/fluentassertions/blob/0a37562a3eebc9a3269a8f5965259cdc170306c8/Src/FluentAssertions/Primitives/StringAssertions.cs#L79

**Comment by mitikov** [comment]
StackOverflow mentions that as well: https://stackoverflow.com/questions/9877644/can-fluent-assertions-use-a-string-insensitive-comparison-for-ienumerablestring

**Comment by dennisdoomen** [comment]
How is it outdated?

**Comment by mitikov** [comment]
Sorry, my mistake.

**Comment by mitikov** [comment]
The phrase `exactly same as` took all attention, and comment next line (the exception of the casing) was missed.
