### ISSUE TITLE
DateTime Should().BeLessThan(...).After(b) not check After

### ISSUE THREAD

**Issue by SvetlanaNesterova** [fluentassertions/fluentassertions#1165]
Hello!

It seems strange for me that DateTimeAssertions works in this way:

```c#
[Test]
public void Test_before_and_after()
{
    var a = new DateTime(2019, 01, 01, 12, 0, 0, DateTimeKind.Utc);
    var b = new DateTime(2019, 01, 01, 12, 30, 0, DateTimeKind.Utc);
    a.Should().BeLessThan(1.Hours()).Before(b);
    a.Should().BeLessThan(1.Hours()).After(b);
}
```
These methods check that difference is less than value, and it is true when difference is negative. But is not correct to say that `a` is less than an hour **after** `b` when `a - b == -30.Minutes()`
 
I think there should be assertion that difference (`TimeSpan actual`) should be not negative in methods `DateTimeRangeAssertions.Before` and `DateTimeRangeAssertions.After`.

https://github.com/fluentassertions/fluentassertions/blob/0a37562a3eebc9a3269a8f5965259cdc170306c8/Src/FluentAssertions/Primitives/DateTimeRangeAssertions.cs#L75-L80

https://github.com/fluentassertions/fluentassertions/blob/0a37562a3eebc9a3269a8f5965259cdc170306c8/Src/FluentAssertions/Primitives/DateTimeRangeAssertions.cs#L116-L121

**Comment by dennisdoomen** [comment]
>  But is not correct to say that a is less than an hour after b when a - b == -30.Minutes()

I don't get it. Are you saying that the assertion API is not grammatically correct?

**Comment by SvetlanaNesterova** [comment]
A = 12:00
B = 12:30
I want to know: is A less than 1 hour after B?
I think correct answer is "No", because A is before B, not after.
I expected it is equivalent to statement `A in interval (B; B + 1 hour)`. And I was surprised when I changed "Before" on "After" in my test and it didn't fail.

If you think current behaviour is correct, I will close the issue.

**Comment by jonathann92** [comment]
Hey guys I'm running into this issue as well. I agree with @SvetlanaNesterova that it should fail the test in his original case. Do you know if this is being worked on?

**Comment by dennisdoomen** [comment]
We kind of missed it. I've just flagged it as a bug to give it more attention.

**Comment by jnyrup** [comment]
@jonathann92 To our knowledge no one is working on this issue, but we're open to contributions.

**Comment by jonathann92** [comment]
@jnyrup Hi I started working on this request. I noticed that in the solution, when declaring variables, there isn't a lot of `var str`. Would you rather declare variables using `string str` or is there no preference?

**Comment by jonathann92** [comment]
@jnyrup @dennisdoomen 

I've created a PR for this request. Can you take a look whenever you guys get a chance? 

#1313

**Comment by dennisdoomen** [comment]
> Hi I started working on this request. I noticed that in the solution, when declaring variables, there isn't a lot of `var str`. Would you rather declare variables using `string str` or is there no preference?

We follow https://csharpcodingguidelines.com//maintainability-guidelines/#AV1520
