### ISSUE TITLE
Equivalency of multidimensional arrays with zero size width

### ISSUE THREAD

**Issue by quinmars** [fluentassertions/fluentassertions#1167]
Following code throws an exception (`System.IndexOutOfRangeException : Index was outside the bounds of the array.`):

```csharp
[Fact]
public void Test()
{
    Array a = new long[1,0] { { } };
    Array b = new long[1,0] { { } };

    a
        .Should().BeEquivalentTo(b);
}
```

I'd expect `a` to be equivalent to `b`.

I'm using version 5.9.0 of FluentAssertions.

**Comment by dennisdoomen** [comment]
Defintiely a bug.

**Comment by quinmars** [comment]
Thank you!
