### ISSUE TITLE
Add Should().All() feature

### ISSUE THREAD

**Issue by Brondahl** [fluentassertions/fluentassertions#1179]
I very often want to make an assertion about every member of a collection.
You can use `.Should().OnlyContain()` but I'd like to be able to use your lovely library of helper assertions.

e.g. I'd like to be able to write:
`myStrings.Should().All().StartWith("Hello");`

It feels like it ought to be relatively achievable?
Roughly speaking .All() would need to return an object that looked the same as a `.Should()` of the Collection contents but which passes all of its implementations down to an inner `.Should()` against each of the elements.

First Question: Would you be happy with this functionality existing?

Second Question: Is this something that you'd be likely to implement any time soon?
If not, would you accept a PR for it? And do you think such a change would be tractable to an experienced .NET programmer who's never looked inside your codebase before?

**Comment by Brondahl** [comment]
Some other viable-but-a-bit-dissappointing solutoins exist here:

https://stackoverflow.com/questions/18899755/how-to-assert-all-items-in-a-collection-using-fluent-assertions

The `.Select()` and `.ForEach()` forms even give access to the assertion helpers. But I think the above proposal is much more inline with the "Fluent" goal of this library, is a LOT more discoverable, and would be much more pleasant all-round.

**Comment by Brondahl** [comment]
@dennisdoomen 
Is that agreement that the proposed solution is more elegant than the linked workarounds? Or an indication tha I should stick to those other options?

Does it constitute "Yes, if a PR was raised for this then we'd accept it?" (You appear to be the primary contributor :) )

(I've raised PRs in the past for other OpenSource projects that were rejected because the maintainers didn't like the idea of the feature I'd added, so I don't want to do the work before the feature is approved!)

**Comment by jnyrup** [comment]
A *few* times we have had to decline PRs or change our minds after encouraging a PR.
Sometimes designing the API just requires the feedback loop from implementing it and get a feeling of it.
That risk is greatly reduced if you can propose a function signature of the assertion and an example of how to use it.

We recently had [`SatisfyRespectively`](https://github.com/fluentassertions/fluentassertions/pull/1043) which states that N elements should match N assertions.
Your assertion wants to assert that N elements should match a single assertion

So how about
```c#
public AndConstraint<TAssertions> AllSatisfy(Action<T> elementInspector)
```

```c#
myStrings.Should().AllSatisfy(e => e.StartWith("Hello"));
```

One difference compared to that PR, is that is should implemented in 
`SelfReferencingCollectionAssertions` instead of `GenericCollectionAssertions`, see #1188

**Comment by dennisdoomen** [comment]
I really like @Brondahl 's proposal. Having this `All()` makes it very fluent and can indeed work as expected. But let's not make it an extension method to prevent conflicts with LINQ's `All` extension method.

**Comment by Brondahl** [comment]
:D

Cool, it sounds you're collectively on board with the broad concept :)

I'll have a play around with a few signatures to see what I can get to work, without treading on Linq's toes.
If the `.AllSatisfy()` signature is the only one that works, then that would have to do, but I'd prefer to be able to avoid adding the extra lamda in.

I'll come back to you when I've got a fully formed signature I like the feel of.

**Comment by Brondahl** [comment]
Having looked into the codeabse around this, I'm pretty sure that I can achieve my initial signature:

`myStrings.Should().All().StartWith("Hello");`

Much like `.Should()`, `.All()` would return a different type depending on the type of the `Subject`, achieved by typed overloads of the `.All()` method.
`.All()` will technically be a set of static extension methods on `SelfReferencingCollectionAssertions<T,TAssertions>`, with varying overloads based on T, matching the `.Should()` overloads in `AssertionExtensions.cs`.
(Plus also an extension method on `NonGenericCollectionAssertions`, exposing the generalised ObjectAssertions

Note that these won't conflict with Linq's `.All()`, since `IEnumerable` and doesn't implement `SelfReferencingCollectionAssertions` and viceversa, thus at most one `.All()` method can be accessible for a given object.

Return Types will, regrettably, have to be done per-SubjectType, due to Type Requirements. We won't be duplicating the *logic* of the per-SubjectType checks. But I suspect we'll be duplicating the signatures; which is a shame.
We should be able to make the implementations of the additional copies of the signatures pretty terse though:
* Call a helper method to loop over the collection and collate errors.
* Pass into that helper method, a call to the "real" test.

I can see 2 options specifically how we achieve that for, say, XDocAssertions:

Either:
* make all the methods on the relevant `XDocAssertions` objects virtual, and then have a subclass `XDocAssertionsOnAll` which overrides the base methods, does the looping and error-collation, before calling `base.Method()`
* or **(preferred)**: introduce `IXDocAssertions`, an interface containing all the public methods on `XDocAssertions`. Mark `XDocAssertions : IXDocAssertions`. Create a 2nd class `XDocAssertionsOnAll`, which also implements the interface, and which delegates the actual testing logic to an instance of `XDocAssertions`. Then have the relevant `.Should()` and `.All()` methods return the interface, not the concrete Type.

An advantage of the 2nd option is that all of the intellisense documentation can be stored on the interface, so we won't have to duplicate it (and hence keep it in sync!) on both the classes.

**Comment by Brondahl** [comment]
@dennisdoomen if you could take a read through that and let me know that you're happy with the proposed design. Then I'll go ahead and implement a PR. If not we can figure out an alternative design (or Syntax).

**Comment by dennisdoomen** [comment]
I can't oversee the type-specific constraints you're facing, but would the use of extension methods help here? E.g. an `All` extension method that extends `XDocAssertions`

**Comment by Brondahl** [comment]
No, the issue is that we have a `SelfReferencingCollectionAssertions<XDoc, SelfReferencingCollectionAssertions>` object, and we need to get an `XDocAssertions` object out of it. (Or something that looks like it).

As programmers we know that `XDoc` maps to `XDocAssertions`, but the code doesn't. And if we were to define a mapper from Type => AssertionType, then it would have to return a base assertion type (if that exists? I don't think that RefTypeAssertions and ValueTypeAssertions shared a common base?) so even if the object *WAS* actually an `XDocAssertions` object, we wouldn't know that ... we'd only know that it was a `ReferenceTypeAssertions` object, so we'd immediately lose all the 
benefits of doing this.

This is the same problem that `.Should()` has, and the only solution is for different extension methods to return different types ... which is what I arrived at in the design above. :)

It's not as nice as I'd hoped, but I don't think it's **too** bad.

**Comment by dennisdoomen** [comment]
Maybe you can do a spike so we can look at the consequences and implementation details. I have a hard time understanding the details, but I have the feeling it's going to be a pretty significant change.

**Comment by Brondahl** [comment]
👍

**Comment by nbarbettini** [comment]
On occasion I run into test code where having `.AllSatisfy(x => ...)` would be really helpful. Right now `collection.ForEach(x => x.Should()...)` is doing the job.

**Comment by dennisdoomen** [comment]
@Brondahl looking at it again. I think I understand you now. But unless I'm still misunderstanding you, we'll need to duplicate _every_ non-collection assertion to make an _all_ version out of it, right?

**Comment by Brondahl** [comment]
Heya, Sorry that this got dropped. In a bout of Open Source enthusiasm I
picked up another OS feature PR at the same time, which would have been
more concretely useful for my current project and was a little more
tractable, and then we moved house and all my free-time went away!
Based on my memory and the notes above (i.e. *not* on having re-reviewed
the code)...

Yes, we'd need to duplicate each assertion. Specifically, we'd need to
duplicate:

   - the declaration of a `<Something>Assertion` Type
   - the .Should() signature, to give access to that new Type

But we *wouldn't* need to duplicate the *logic* of the assertions, though.

What's your take on that as a design?
I'm still happy to do a demo implementation for one particular type, so
that you can see concretely what I have in mind?
Might actually have some time to do it in, now, too!

**Comment by dennisdoomen** [comment]
No worries. Life of an open-source developers is unpredictable at best.

I don't think we should go in that direction. It will create quite a maintenance burden for the future. Maybe a `Should().AllSatisfy` is a better alternative.

**Comment by mdentremont** [comment]
I like the `AllSatisfy` concept, I actually thought that's what either `Satisfy` or `SatisfyRespectively` would do from a high view and was disappointed when they didn't 😛
