### ISSUE TITLE
Question: Test naming convention

### ISSUE THREAD

**Issue by lg2de** [fluentassertions/fluentassertions#1182]
Whenever I add a new test to FA I find it very difficult to name it correctly. The nomenclature you use is very complex from my point of view.

Have you ever thought about using the style that I perceive to be predominantly used?
`[UnitOfWork_StateUnderTest_ExpectedBehavior]`

[Here](https://stackoverflow.com/a/1594049/3621055) is one source for this recommendation.

**Comment by dennisdoomen** [comment]
Yes, I'm fully aware of what Roy Osherove has proposed years ago. But I've never agreed with that. I want my tests to be functionally named. Consider reading https://www.continuousimprover.com/2016/11/the-three-mental-modes-of-working-with.html

**Comment by lg2de** [comment]
Ok, I understand your intention.
Here is one example, why I dislike your current structure:
![image](https://user-images.githubusercontent.com/44983012/69903697-511efd00-139d-11ea-92a2-2fd48a09b84a.png)

Anyway, in future (like past) I'll try to adopt the test name from existing tests.

**Comment by dennisdoomen** [comment]
That's a wrong example IMO. See point 2 of https://www.continuousimprover.com/2015/11/12-tips-to-write-unit-tests-that-dont.html
