### ISSUE TITLE
Should.be() fails when comparing object and true

### ISSUE THREAD

**Issue by GeeWee** [fluentassertions/fluentassertions#1183]
# Description
If I have an `object` and I use `Should().Be()` to compare it to a boolean, it will always pass, if passed in `true`, but fail correctly when passed in `false`.

See the example below:

```csharp
            // For unrelated reasons I have an object as a number
            object myNumber = 10;
            // This should not work, they're not identical, but it passes
            myNumber.Should().Be(true);
            // The opposite arrangement fails properly
            ((object)true).Should().Be(myNumber);
            // Comparing the number to false, fails properly as well
            myNumber.Should().Be(false);
```

### Versions

FluentAssertions 5.9.0 targeting .NET Core 3.0

**Comment by jnyrup** [comment]
Thanks for raising awareness about this issue.
It essentially boils down to the same issue as #1010.
When comparing `(object)10` and `true` it currently tries to converts `10` to a `bool` using `Convert.ChangeType` which returns a `true`.
And `true` equals `true`.

**Comment by GeeWee** [comment]
Thanks for the quick response! I couldn't find the previous issue while searching :)
