### ISSUE TITLE
Build process does not include icon

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#1186]
### Description

https://github.com/fluentassertions/fluentassertions/pull/1156 changed from `<PackageIconUrl>` to `<PackageIcon>`.
I'm using [Nuget Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) to verify that the icon is properly read, but it isn't.

### Complete minimal example reproducing the issue

Download [5.9.0 artifact](https://www.nuget.org/api/v2/package/FluentAssertions/5.9.0) and open in Nuget Package Explorer
It shows the icon and the `.nuspec` contains
`<iconUrl>https://raw.githubusercontent.com/fluentassertions/fluentassertions/master/Src/FluentAssertions.png</iconUrl>`

Download the [artifact](https://ci.appveyor.com/api/buildjobs/v8agm3x84qye2pr0/artifacts/Artifacts%2FFluentAssertions.5.9.1-pullrequest1156-0027.nupkg) produced from #1156 
It does not show an icon and the `.nuspec` does not contain any `icon` entry.

When building master locally, the `.nuspec` contains
`<icon>FluentAssertions.png</icon>`

### Additional Information

I suspect the AppVeyor build server has an too old version of some component.

**Comment by jnyrup** [comment]
@dennisdoomen which build image is AppVeyor using?

This should be resolved before publishing next minor version.

**Comment by dennisdoomen** [comment]
![image](https://user-images.githubusercontent.com/572734/69087616-120cb580-0a47-11ea-8fa3-58391c0ed348.png)

**Comment by jnyrup** [comment]
Fixed in #1195
