### ISSUE TITLE
Bug in obj1.Should().BeEquivalentTo(obj2) with nested objects

### ISSUE THREAD

**Issue by missym-pt** [fluentassertions/fluentassertions#1187]
**Before you file a bug, have you:**

* Tried upgrading to newest version of Fluent Assertions, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/fluentassertions/fluentassertions/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Read the [documentation](https://fluentassertions.com/documentation/)?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/questions/tagged/fluent-assertions?mixed=1).

### Description

Bug in obj1.Should().BeEquivalentTo(obj2) with nested objects
Was using latest package, already tried downgrading to check if it was a version issue but didn't solve.
In the example,  var copyFromExpectedResult was created only for debbuging/testing purposes on the bug.

Thank you

### Complete minimal example reproducing the issue

        [Test]
        public async Task Execute_ValidResponseWithNestedWidgets_DataAndChildDataAreMapped()
        {
            _identifiersResponse = new GetIdentifiersResponse()
            {
                Identifiers = new List<DimensionIdentifier>
                {
                    new DimensionIdentifier{Id = 1, CName = "Bad_Jurisdiction"},
                    new DimensionIdentifier{Id = 2, CName = "Good_ClientType"},
                    new DimensionIdentifier {Id = 227, CName = "Mock"}
                }
            };

            GetLayoutDetailsResultV2 result = await InitCommand(_dashResponse).Execute(_request, new RequestContext());

            GetLayoutDetailsResultV2 expectedResult = new GetLayoutDetailsResultV2()
            {
                Id = 1,
                CName = "SomeLayoutCName",
                DisplayName = "Audience for tests DataAndChildDataAreMapped",
                BrandId = 4,
                Widget =
                    new WidgetDataV2
                    {
                        Id = 11,
                        TypeId = 11,
                        TypeName = "typeName11",
                        TypeCName = "typeCName11",
                        Properties = new[]
                        {
                            new WidgetPropertyDataV2
                            {
                                Name = "SomePropertyName",
                                Value = "SomePropertyValue",
                                TypeId = 42
                            }
                        },
                        Widgets = new List<WidgetDataV2>()
                        {
                            new WidgetDataV2
                            {
                                Id = 111,
                                TypeId = 111,
                                TypeName = "typeName111",
                                TypeCName = "typeCName111",
                                Properties = new[]
                                {
                                    new WidgetPropertyDataV2
                                    {
                                        Name = "SomePropertyName",
                                        Value = "SomePropertyValue",
                                        TypeId = 42
                                    }
                                },
                                Widgets =new List<WidgetDataV2>()
                            },
                            new WidgetDataV2
                            {
                                Id = 112,
                                TypeId = 112,
                                TypeName = "typeName112",
                                TypeCName = "typeCName112",
                                Properties = new[]
                                {
                                    new WidgetPropertyDataV2
                                    {
                                        Name = "SomePropertyName",
                                        Value = "SomePropertyValue",
                                        TypeId = 42
                                    }
                                },
                                Widgets = new List<WidgetDataV2>()
                                {
                                    new WidgetDataV2
                                    {
                                        Id = 1121,
                                        TypeId = 1121,
                                        TypeName = "typeName1121",
                                        TypeCName = "typeCName1121",
                                        Properties = new[]
                                        {
                                            new WidgetPropertyDataV2
                                            {
                                                Name = "SomePropertyName",
                                                Value = "SomePropertyValue",
                                                TypeId = 42
                                            },
                                            new WidgetPropertyDataV2
                                            {
                                                Name = "SomePropertyName",
                                                Value = "SomePropertyValue",
                                                TypeId = 42
                                            },
                                            new WidgetPropertyDataV2
                                            {
                                                Name = "SomePropertyName",
                                                Value = "SomePropertyValue",
                                                TypeId = 42
                                            },
                                            new WidgetPropertyDataV2
                                            {
                                                Name = "SomePropertyName",
                                                Value = "SomePropertyValue",
                                                TypeId = 42
                                            }
                                        }
                                    }
                                }
                            },
                            new WidgetDataV2
                            {
                                Id = 113,
                                TypeId = 113,
                                TypeName = "typeName113",
                                TypeCName = "typeCName113",
                                Properties = new[]
                                {
                                    new WidgetPropertyDataV2
                                    {
                                        Name = "SomePropertyName",
                                        Value = "SomePropertyValue",
                                        TypeId = 47
                                    }
                                },
                                Widgets =new List<WidgetDataV2>()

                            }
                        }
                    }
            };

             GetLayoutDetailsResultV2 copyFromExpectedResult = new GetLayoutDetailsResultV2()
            {
                Id = 1,
                CName = "SomeLayoutCName",
                DisplayName = "Audience for tests DataAndChildDataAreMapped",
                BrandId = 4,
                Widget =
                    new WidgetDataV2
                    {
                        Id = 11,
                        TypeId = 11,
                        TypeName = "typeName11",
                        TypeCName = "typeCName11",
                        Properties = new[]
                        {
                            new WidgetPropertyDataV2
                            {
                                Name = "SomePropertyName",
                                Value = "SomePropertyValue",
                                TypeId = 42
                            }
                        },
                        Widgets = new List<WidgetDataV2>()
                        {
                            new WidgetDataV2
                            {
                                Id = 111,
                                TypeId = 111,
                                TypeName = "typeName111",
                                TypeCName = "typeCName111",
                                Properties = new[]
                                {
                                    new WidgetPropertyDataV2
                                    {
                                        Name = "SomePropertyName",
                                        Value = "SomePropertyValue",
                                        TypeId = 42
                                    }
                                },
                                Widgets =new List<WidgetDataV2>()
                            },
                            new WidgetDataV2
                            {
                                Id = 112,
                                TypeId = 112,
                                TypeName = "typeName112",
                                TypeCName = "typeCName112",
                                Properties = new[]
                                {
                                    new WidgetPropertyDataV2
                                    {
                                        Name = "SomePropertyName",
                                        Value = "SomePropertyValue",
                                        TypeId = 42
                                    }
                                },
                                Widgets = new List<WidgetDataV2>()
                                {
                                    new WidgetDataV2
                                    {
                                        Id = 1121,
                                        TypeId = 1121,
                                        TypeName = "typeName1121",
                                        TypeCName = "typeCName1121",
                                        Properties = new[]
                                        {
                                            new WidgetPropertyDataV2
                                            {
                                                Name = "SomePropertyName",
                                                Value = "SomePropertyValue",
                                                TypeId = 42
                                            },
                                            new WidgetPropertyDataV2
                                            {
                                                Name = "SomePropertyName",
                                                Value = "SomePropertyValue",
                                                TypeId = 42
                                            },
                                            new WidgetPropertyDataV2
                                            {
                                                Name = "SomePropertyName",
                                                Value = "SomePropertyValue",
                                                TypeId = 42
                                            },
                                            new WidgetPropertyDataV2
                                            {
                                                Name = "SomePropertyName",
                                                Value = "SomePropertyValue",
                                                TypeId = 42
                                            }
                                        }
                                    }
                                }
                            },
                            new WidgetDataV2
                            {
                                Id = 113,
                                TypeId = 113,
                                TypeName = "typeName113",
                                TypeCName = "typeCName113",
                                Properties = new[]
                                {
                                    new WidgetPropertyDataV2
                                    {
                                        Name = "SomePropertyName",
                                        Value = "SomePropertyValue",
                                        TypeId = 47
                                    }
                                },
                                Widgets =new List<WidgetDataV2>()

                            }
                        }
                    }
            };

             result.Should().BeEquivalentTo(expectedResult); //HERE FAILS ALL OTHERS PASS//

             //FAILURES
             //Expected member Widget.Widgets[1].Id to be 112, but found 113.
             //Expected member Widget.Widgets[1].TypeId to be 112, but found 113.
             //Expected member Widget.Widgets[1].TypeName to be 
             //"typeName112", but 
             //"typeName113" differs near "3" (index 10).
             //Expected member Widget.Widgets[1].TypeCName to be 
             //"typeCName112", but 
             //"typeCName113" differs near "3" (index 11).
             //Expected member Widget.Widgets[1].Properties[0].TypeId to be 42, but found 47.
             //Expected member Widget.Widgets[1].Widgets to be a collection with 1 item(s), but found an empty collection.

             copyFromExpectedResult.Should().BeEquivalentTo(expectedResult);
            

            result.Widget.Widgets[1].Id.Should().Be(expectedResult.Widget.Widgets[1].Id);

            Assert.AreEqual(result.BrandId, 4);
            Assert.AreEqual(result.CName, "SomeLayoutCName");
            Assert.AreEqual(result.Id, 1);
            Assert.AreEqual(result.Widget.Id, 11);
            Assert.AreEqual(result.Widget.TypeId, 11);
            Assert.AreEqual(result.Widget.TypeName, "typeName11");
            Assert.AreEqual(result.Widget.TypeCName, "typeCName11");
            Assert.AreEqual(result.Widget.Properties.First().Name, "SomePropertyName");
            Assert.AreEqual(result.Widget.Properties.First().TypeId, 42);
            Assert.AreEqual(result.Widget.Properties.First().Value, "SomePropertyValue");
            Assert.AreEqual(result.Widget.Widgets.ToArray()[0].Id, 111);
            Assert.AreEqual(result.Widget.Widgets.ToArray()[0].TypeId, 111);
            Assert.AreEqual(result.Widget.Widgets.ToArray()[0].TypeName, "typeName111");
            Assert.AreEqual(result.Widget.Widgets.ToArray()[0].TypeCName, "typeCName111");
            Assert.AreEqual(result.Widget.Widgets.ToArray()[1].Id, expectedResult.Widget.Widgets[1].Id);
            Assert.AreEqual(result.Widget.Widgets.ToArray()[1].TypeId, 112);
            Assert.AreEqual(result.Widget.Widgets.ToArray()[1].TypeName, "typeName112");
            Assert.AreEqual(result.Widget.Widgets.ToArray()[1].TypeCName, "typeCName112");

        }

### Expected behavior:

 result.Should().BeEquivalentTo(expectedResult); should pass

### Actual behavior:

 result.Should().BeEquivalentTo(expectedResult);  fails

             //FAILURES
             //Expected member Widget.Widgets[1].Id to be 112, but found 113.
             //Expected member Widget.Widgets[1].TypeId to be 112, but found 113.
             //Expected member Widget.Widgets[1].TypeName to be 
             //"typeName112", but 
             //"typeName113" differs near "3" (index 10).
             //Expected member Widget.Widgets[1].TypeCName to be 
             //"typeCName112", but 
             //"typeCName113" differs near "3" (index 11).
             //Expected member Widget.Widgets[1].Properties[0].TypeId to be 42, but found 47.
             //Expected member Widget.Widgets[1].Widgets to be a collection with 1 item(s), but found an empty collection.

### Versions
Fluent Assertions 5.9
.NET runtime Core 2.2.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jnyrup** [comment]
Please a *complete* and *minimal* example.
* *complete* means I can copy the example in a fresh test project and run it.
* *minimal* means it has been stripped from any irrelevant code.

**Comment by jnyrup** [comment]
Closing for now, feel free to re-open if you have a *complete* and *minimal* example.
Stackoverflow has some helpful [guidance](https://stackoverflow.com/help/minimal-reproducible-example) on the topic

**Comment by kevin-se** [comment]
Just ran in to this and found a simple repro scenario.  The number of entries in [0] and [1] need to be different, and the BeEquivilentTo assertion needs to fail for the item at [0]

`using System;
using System.Collections.Generic;
using FluentAssertions;
using NUnit.Framework;

namespace FluentAssertionsBug
{
    [TestFixture]
    public class TestFixture
    {
        [Test]
        public void NoBug()
        {
            // Assertions return correct failures (3 failures) 
            var id = Guid.NewGuid();

            var correctResult = new ThingWithProperties()
            {
                Properties = new Dictionary<string, object>
                {
                    {"ID", id},
                    {"Property", "Value"},
                }
            };

            var incorrectResult = new ThingWithProperties()
            {
                Properties = new Dictionary<string, object>
                {
                    {"Property", "Value"},
                }
            };

            var result = new object[]
            {
                new object[] { correctResult },
                new object[] { correctResult, correctResult },
            };

            var expected = new object[]
            {
                new object[] { correctResult },
                new object[] { incorrectResult, incorrectResult },
            };

            result.Should().BeEquivalentTo(expected);

        }

        [Test]
        public void BugRepro()
        {
            // Assertions fail  result[0][0] is compared to bug[0][0] and bug[0][1] rather then results[0][0] -> bug[0][0] results[0][1] -> result[0][1]
            // this only occurs when result[0][0] : bug[0][0] throws a failure.
            var id = Guid.NewGuid();

            var correctResult = new ThingWithProperties()
            {
                Properties = new Dictionary<string, object>
                {
                    {"ID", id},
                    {"Property", "Value"},
                }
            };

            var incorrectResult = new ThingWithProperties()
            {
                Properties = new Dictionary<string, object>
                {
                    {"Property", "Value"},
                }
            };

            var result = new object[]
            {
                new object[] { correctResult },
                new object[] { correctResult, correctResult },
            };

            var bug = new object[]
            {
                new object[] { incorrectResult },
                new object[] { incorrectResult, incorrectResult },
            };


            result.Should().BeEquivalentTo(bug);

        }
    }

    public class ThingWithProperties
    {
        public IDictionary<string, object> Properties { get; set; }
    }
}

**Comment by jnyrup** [comment]
@kevin-se I tried running your tests and I don't think there is a bug.

The error message I get is (note: I'm testing in the development branch) 

```
Expected item[0][0].Properties to be a dictionary with 1 item(s), but has additional key(s) {"ID"}
Expected item[1] to be a collection with 2 item(s), but {FluentAssertions.Specs.ThingWithProperties
   {
	  Properties = {[ID, ca7a0f74-035d-4830-922e-07a469984e41], [Property, Value]}
   }}"
"contains 1 item(s) less than"
"{FluentAssertions.Specs.ThingWithProperties
   {
	  Properties = {[Property, Value]}
   }, FluentAssertions.Specs.ThingWithProperties
   {
	  Properties = {[Property, Value]}
   }}.

With configuration:
- Use declared types and members
- Compare enums by value
- Include all non-private properties
- Include all non-private fields
- Match member by name (or throw)
- Be strict about the order of items in byte arrays
- Without automatic conversion.
```

`BeEquivalentTo` per default uses non-strict ordering when comparing the elements. 
That is `[1, 2]` is considered *equivalent* to `[2, 1]` as they contain the same elements.

What might make error message confusing is that neither of `bug[0]` or `bug[1]` matched any of `result[]`.

When formatting the error message it will only include a single non-match.
So what the error message says in condensed form is that neither of `bug[0]` or `bug[1]` matched `result[0]`.

A fully verbose error message would be something like
```
Tried to match bug[] against result[] regardless of the order of their items.
bug[0] neither matched result[0] nor result[1]
bug[1] neither matched result[0] nor result[1]
```

But as you might imagine this doesn't scale very well as the collections grow larger.
```
Tried to match bug[] against result[] regardless of the order of their items.
bug[0] neither matched result[0], …, nor result[N]
⋮
bug[N] neither matched result[0], …, nor result[N]
```

> // this only occurs when result[0][0] : bug[0][0] throws a failure.

When `bug[0]` matches `result[0]` the equivalency will only have to compare `bug[1]` against `result[1]` the formatter can be more specific about which elements didn't match.

> // Assertions fail  result[0][0] is compared to bug[0][0] and bug[0][1] rather then results[0][0] -> bug[0][0] results[0][1] -> result[0][1]

If you'd rather like to compare `bug[]` and `result[]` in order, you can use `WithStrictOrdering()`

```c#
result.Should().BeEquivalentTo(bug, opt => opt.WithStrictOrdering());
```

that gives the following error message
```
Expected item[0][0].Properties to be a dictionary with 1 item(s), but has additional key(s) {"ID"}
    Expected item[1][0].Properties to be a dictionary with 1 item(s), but has additional key(s) {"ID"}
    Expected item[1][1].Properties to be a dictionary with 1 item(s), but has additional key(s) {"ID"}
```
