### ISSUE TITLE
StringCollectionAssertions missing SatisfyRespectively GenericCollectionAssertions

### ISSUE THREAD

**Issue by robhol** [fluentassertions/fluentassertions#1188]
### Description

GenericCollectionAssertions has SatisfyRespectively, which is not present in the more specialized StringCollectionAssertions - I would expect more specialized Assertions classes to add, but not remove functionality.

Seems like it could've happened elsewhere, but I don't have the time to track down any other instances.

### Complete minimal example reproducing the issue

```csharp
new object[] { }.Should().SatisfyRespectively(x => { }); //Should() is GenericCollectionAssertions
new string[] { }.Should().SatisfyRespectively(...) // does not exist, Should() is StringCollectionAssertions
```

### Versions

* Which version of Fluent Assertions are you using?
5.9.0

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
.NET Core 2.2

**Comment by jnyrup** [comment]
Seems we can just move `SatisfyRespectively` from `GenericCollectionAssertions<T>` to its base class `SelfReferencingCollectionAssertions<T, TAssertions>`.


Doing so should not be a [breaking change](https://docs.microsoft.com/en-us/dotnet/core/compatibility/#members)
> ✔️ Moving a member into a class higher in the hierarchy than the type from which it was removed
