### ISSUE TITLE
DateTimeOffsetValueFormatter fails with empty DateTime

### ISSUE THREAD

**Issue by gius** [fluentassertions/fluentassertions#120]
DateTimeOffsetValueFormatter in FluentAssertions.Core\Formatting fails with default DateTime value (1.1.0001 12:00 AM) when the computer is in timezone with "+XX hours".

To be precise, ArgumentOutOfrangeException ("The UTC time represented when the offset is applied must be between year 0 and 10,000.") is thrown on line 41:

```
dateTime = (DateTime) value;
```

This can be reproduced with the following type cast when current computer timezone is set to +1 and more:

```
(DateTimeOffset)new DateTime();
```

The reason seems to be pretty clear - DateTimeOffset first converts the DateTime to UTC and thus it has to subtract hours according to the current timezone. This causes the result to be less than DateTimeOffset.MinValue.

I am sorry for not providing pull request fixing this problem but I don't know FluentAssertions architecture enough to be sure that simple usage of DateTime instead of DateTimeOffset wouldn't cause any other problems.

**Comment by Robelind** [comment]
Any progress on this issue? It's quite annoying.

**Comment by vossad01** [comment]
@Robelind What version are you running?

As this issue has been closed a while, if you are still encountering the issue in v3.3.0, would you please create a new Issue, ideally with steps to recreate your specific issue?
