### ISSUE TITLE
BeEquivalentTo fails when comparing two JsonElement's

### ISSUE THREAD

**Issue by annas-abuhassan** [fluentassertions/fluentassertions#1212]
Test is failing when comparing two Json Elements using ShouldBeEquivalentTo. I'm sure that this Assertion 

```csharp
[Fact]
public void Test()
{
        // Arrange & Act
        var element1 = JsonDocument.Parse("{}").RootElement;
        var element2 = JsonDocument.Parse("{}").RootElement;

        // Assert
        element1.Should().BeEquivalentTo(element2);
}
```

### Expected behavior:

I would expect this to pass

### Actual behavior:

This actually fails

### Versions
XUnit v2.4.1
FluentAssertions v5.9.0
.NET Core 3.0

**Comment by jnyrup** [comment]
Analysis:
[`JsonElement`](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonElement.cs) is a `struct` that does *not* override `Object.Equals(object)`.
That is, it keeps the default generated `ValueType.Equals(object)` which compares instances memberwise using *their* `Equals(object)`.

`JsonElement` has a field `_parent`, which points to its parent `JsonDocument`.
`JsonDocument` also does not override `Object.Equals(object)`, so instances are compared by reference.

As the `_parent` fields of `element1` and `element2` points to two different `JsonDocument`s in memory, `element1` does not equal `element2`.

This behavior can be seen with
```c#
element1.Equals(element2); // false
```

Workaround:
If you use `ComparingByMembers()` Fluent Assertions will compare object structurally (think memberwise), but per default only for public members.
So it will now exclude `_parent`.
```c#
element1.Should().BeEquivalentTo(element2, opt => opt.ComparingByMembers<JsonElement>());
```

**Comment by annas-abuhassan** [comment]
Hi @jnyrup,

Thank you for the prompt reply. 
So I cannot compare JsonElements **values**, only the **structure** of the object - is that correct?

**Comment by jnyrup** [comment]
Structural comparison here means comparing the values of the members of the objects.

**Comment by stewie1570** [comment]
Is there a workaround for when comparing objects that contain `JsonElement`s?

**Comment by jnyrup** [comment]
@stewie1570 The workaround described above works as well for objects containing `JsonElement`s.

```cs
public void TestMethod1()
{
    // Arrange & Act
    var element1 = new { Json = JsonDocument.Parse("{}").RootElement };
    var element2 = new { Json = JsonDocument.Parse("{}").RootElement };

    // Assert
    element1.Should().BeEquivalentTo(element2, opt => opt
        /*.ComparingByMembers<JsonElement>()*/);
}
```

**Comment by dennisdoomen** [comment]
And we also have `FluentAssertions.Json`

**Comment by jnyrup** [comment]
@dennisdoomen `JsonElement` is from `System.Text.Json` not `Newtonsoft.Json`.

**Comment by jevonkendon** [comment]
For now I've created a custom FluentAssertion rule, which just compares their string representations:
```
    public class JsonDocumentRule : IAssertionRule
    {
        public bool AssertEquality(IEquivalencyValidationContext context)
        {
            if (!(context.Subject is JsonDocument subjectValue) ||
                !(context.Expectation is JsonDocument expectationValue))
            {
                // rule not applicable
                return false;
            }

            var lhs = ToJsonString(subjectValue);
            var rhs = ToJsonString(expectationValue);

            Execute.Assertion
                .BecauseOf(context.Because, context.BecauseArgs)
                .ForCondition(lhs == rhs)
                .FailWith("Expected {context:string} to be {0}{reason}, but found {1}",
                    context.Subject, context.Expectation);

            // equality assertion handled
            return true;
        }

        private static string ToJsonString(JsonDocument document)
        {
            using var stream = new MemoryStream();
            Utf8JsonWriter writer = new Utf8JsonWriter(stream, new JsonWriterOptions {Indented = true});
            document.WriteTo(writer);
            writer.Flush();
            return Encoding.UTF8.GetString(stream.ToArray());
        }
    }
```
and then
```
actual.Should().BeEquivalentTo(expected, options => options.Using(new JsonDocumentRule()));
```

**Comment by bhaeussermann** [comment]
> Analysis:
>  ...
> 
> Workaround: If you use `ComparingByMembers()` Fluent Assertions will compare object structurally (think memberwise), but per default only for public members. So it will now exclude `_parent`.
> 
> ```cs
> element1.Should().BeEquivalentTo(element2, opt => opt.ComparingByMembers<JsonElement>());
> ```

This is useless (worse — it's misleading) as it does practically nothing. The following assertion will pass:

```
var expected = JsonDocument.Parse(@"{""name"": ""John""}").RootElement;
var actual = JsonDocument.Parse(@"{""x"": 4, ""y"": 10}").RootElement;
actual.Should().BeEquivalentTo(expected, opt => opt.ComparingByMembers<JsonElement>());
```

The `JsonDocumentRule` implementation provided above isn't very useful either, as it requires the ordering of the properties in both objects to be the same, which shouldn't be required for two objects to be equal.

Isn't there a way to assert that two JSON objects are structurally equivalent other than having to rely on `Newtonsoft.Json`?

**Comment by bhaeussermann** [comment]
> Analysis:
>  ...
> 
> Workaround: If you use `ComparingByMembers()` Fluent Assertions will compare object structurally (think memberwise), but per default only for public members. So it will now exclude `_parent`.
> 
> ```cs
> element1.Should().BeEquivalentTo(element2, opt => opt.ComparingByMembers<JsonElement>());
> ```

This is useless (worse — it's misleading) as it does practically nothing. The following assertion will pass:

```
var expected = JsonDocument.Parse(@"{""name"": ""John""}").RootElement;
var actual = JsonDocument.Parse(@"{""x"": 4, ""y"": 10}").RootElement;
actual.Should().BeEquivalentTo(expected, opt => opt.ComparingByMembers<JsonElement>());
```

The `JsonDocumentRule` implementation provided above isn't very useful either, as it requires the ordering of the properties in both objects to be the same, which shouldn't be required for two objects to be equal.

Isn't there a way to assert that two JSON objects are structurally equivalent other than having to rely on `Newtonsoft.Json`?
