### ISSUE TITLE
Add support for JsonElement with ValueKind == JsonValueKind.String <-> String comparisons

### ISSUE THREAD

**Issue by ardove** [fluentassertions/fluentassertions#1225]
### Description
This isn't a bug, just more of a feature request. I recently ran into this when converting from Newtonsoft.Json to System.Text.Json in .NET Core 3.1.

As it turns out, there is a minor difference between the values returned from (de)serializing an object in the two libraries, so I needed to add the following equivalency step to simplify the comparison across multiple invocations. 

In any case, we know that the ToString invocation on a JsonElement where the JsonValueKind == JsonValueKind.String is going to match the value of a String's ToString method, but FluentAssertions doesn't include a way to compare the string values of an object given the ToString implementation (hence my little workaround). 

```c#
public class JsonElementStringComparisonEquivalencyStep : IEquivalencyStep {
    public bool CanHandle(IEquivalencyValidationContext context, IEquivalencyAssertionOptions config)
    {
        return context.Subject is JsonElement jsonElement && jsonElement.ValueKind == JsonValueKind.String;
    }

    public bool Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config)
    {
        // we expect the Handle method to be called AFTER CanHandle, but just being defensive
        if (!(context.Subject is JsonElement jsonElement) || jsonElement.ValueKind != JsonValueKind.String)
        {
            return false;
        }

        context.Subject.ToString().Should().BeEquivalentTo(context.Expectation.ToString(), context.Because, context.BecauseArgs);
        return true;
    }
}
```

I think it'd be awesome if you guys supported a "ToString" comparison option for any object, specifically meaningful in cases like this, but also cases where the ToString implementation has been overriden. 

This really only presents itself when you use a Dictionary<string, Object>.

Here's a test method:
```c#
[TestMethod]
public void Test()
{
    var expected = new Dictionary<string, object>
    {
        { "foo", "bar" }
    };

    var expectedJson = JsonSerializer.Serialize(expected);
    var actual = JsonSerializer.Deserialize<Dictionary<string, object>>(expectedJson);

    actual.Should().BeEquivalentTo(expected);
}
```

I'd expect that to pass, but instead, it fails with:
`Expected pair[foo] to be System.String, but found System.Text.Json.JsonElement.`
 

### Versions

* FluentAssertions 5.10.0
* .Net Core 3.1

**Comment by dennisdoomen** [comment]
What if you use `WithAutoConversion`?

**Comment by ardove** [comment]
@dennisdoomen, I assume you mean, update the assertion from 
```
actual.Should().BeEquivalentTo(expected);
```
to
```
actual.Should().BeEquivalentTo(expected, options => options.WithAutoConversion());
```

If so, that test still fails with the following error message
```
Expected pair[foo] to be System.String, but found System.Text.Json.JsonElement.
```

**Comment by dennisdoomen** [comment]
OK. I was there was a built-in conversion from `string` to `JsonElement`. 

You could create an `IEquivalencyStep` that will do exactly what you want and pass it to the `Using` method of the options provided by `BeEquivalentTo`

**Comment by ardove** [comment]
Right, that’s what I did above.

I was hoping you guys could add something that would be supported in a similar fashion as the “WithAutoConversion” option. 

I could take a stab at submitting a pull request if you think that’s something you’d like to support long term.  It’d be some like “CompareUsingToStringValue”.

**Comment by dennisdoomen** [comment]
Honestly, I believe it's such a niche requirement, that I don't see a lot of value. I think it would only give us more obfuscated behavior.

**Comment by ardove** [comment]
Fair enough. Closing this. We'll maintain it in our solutions for now.
