### ISSUE TITLE
Preparation 6.0 

### ISSUE THREAD

**Issue by dennisdoomen** [fluentassertions/fluentassertions#1228]
* [x] Keep only .NET Core 2.1, .NET Core 3.0, .NET 4.7, .NET Standard 2.0 and 2.1
* [x] Remove older test frameworks
* [x] Make everything under `Common` that is supposed to be used internally `internal`
* [x] Remove `IAssertionRule`
* [x] Make `CallerIdentifier.logger` a property
* [x] Make `SelfReferenceEquivalencyAssertionOptions.orderingRules` a property
* [x] Remove `#if NETCOREAPP1_1` from all specs
* [x] Check that all `#if`s are necessary in both core and specs projects
* [x] Remove ncrunch files
* [x] Remove references to Gallio and MbUnit
* [x] Restructure `Equivalency` folder
* [x] Revise `params object[]` overloads for ambiguity (e.g. `BequivalentTo`)
* [x] Update `FluentAssertions.Json`

**Comment by lg2de** [comment]
> * Let `[Not]HaveCount*` return the `Subject`

Is there a separate issue therefore?
I checked the current implementation and found that all these assertions returns an `AndConstraint`, so the subject is available, isnt't it?
What do you expected when writing "return the subject"?

**Comment by dennisdoomen** [comment]
> Is there a separate issue therefore?

@jnyrup I think it's yours, right?

**Comment by jnyrup** [comment]
Yes, I'm trying to remember what I meant.

**Comment by jnyrup** [comment]
I really can't remember :(
I had a brief note lying aorund, but that is gone.
