### ISSUE TITLE
Be() and BeSameAs() are doing the same thing

### ISSUE THREAD

**Issue by raschmitt** [fluentassertions/fluentassertions#1237]
### Description

Both methods Be() and BeSameAs() are failing when testing equivalent objects in diferent instances.

As far as I can understand by the documentation only BeSameAs() should compare if two objects refer to the same object in memory, but acctualy both functions are doing so.

[Documentation:](https://fluentassertions.com/basicassertions/)

```
To assert that two objects are equal (through their implementation of Object.Equals), use

string otherObject = "whatever";
theObject.Should().Be(otherObject, "because they have the same values");
theObject.Should().NotBe(otherObject);

If you want to make sure two objects are not just functionally equal but refer to the exact same object in memory, use the following two methods.

theObject = otherObject;
theObject.Should().BeSameAs(otherObject);
theObject.Should().NotBeSameAs(otherObject);
```

### Complete minimal example reproducing the issue

```c#
public class ProductRequestModel
{
    public string Name { get; set; }
    public bool Active { get; set; }
}

[Fact]
public void Should_Be()
{
	var product1 = new ProductRequestModel
	{
		Active = true,
		Name = "Produto",
	};

	var product2 = new ProductRequestModel
	{
		Active = true,
		Name = "Produto",
	};

	product1.Should().Be(product2);
}

[Fact]
public void Should_BeSameAS()
{
	var product1 = new ProductRequestModel
	{
		Active = true,
		Name = "Produto",
	};

	var product2 = new ProductRequestModel
	{
		Active = true,
		Name = "Produto",
	};

	product1.Should().BeSameAs(product2);
}
```

### Expected behavior:

Shoud_Be(), should pass.
Shoud_BeSameAs(), should fail.

### Actual behavior:

Shoud_Be(), fails
Shoud_BeSameAs(), fails

### Versions

* Which version of Fluent Assertions are you using? **v5.9.0**
* Which .NET runtime and version are you targeting? **.Net Core 2.2**

### Additional Information

My error message for Should_Be() is as follows:

```
  Message: 
    Expected product1 to be 
    
    HBSIS.MapaCompetencia.Tests.Integration.ProductRequestModel
    {
       Active = True
       Name = "Produto"
    }, but found 
    
    HBSIS.MapaCompetencia.Tests.Integration.ProductRequestModel
    {
       Active = True
       Name = "Produto"
    }.
```

The interesting part is that Be(), works as expected when comparing anonymous objects.

**Comment by jnyrup** [comment]
Please provide a *complete* example as required from the issue template.
We don't have a `ProductRequestModel`, so we can't reason or run your code.

**Comment by raschmitt** [comment]
> Please provide a _complete_ example as required from the issue template.
> We don't have a `ProductRequestModel`, so we can't reason or run your code.

Just updated my example as requested

**Comment by jnyrup** [comment]
`Be` uses `object.Equals()` to compare whether your two *identical* instances `ProductRequestModel` are to be considered *equal*.
As you haven't overridden `object.Equals()` on `ProductRequestModel` your objects are compared for *reference equality*, which is why you experience identical behavior as `BeSameAs`.

To compare the two objects memberwise, you can use [`BeEquivalentTo`](https://fluentassertions.com/objectgraphs/). 
```c#
product1.Should().BeEquivalentTo(product2);
```

**Comment by raschmitt** [comment]
I had already solved my problem with BeEquivalentTo(), still thanks for your reply.

I just don't get the necessity of having two methods that in practical terms are doing the same thing, or am I missing something here?

**Comment by raschmitt** [comment]
Another thing that I can't understand is, why Be() works for comparing two _non-identical_ instances of anonymous type objects?

```
        [Fact]
        public void Should_Be()
        {
            var product1 = new
            {
                Active = true,
                Name = "Produto",
            };

            var product2 = new
            {
                Active = true,
                Name = "Produto",
            };

            product1.Should().Be(product2);
        }
```

**Comment by raschmitt** [comment]
> Another thing that I can't understand is, why Be() works for comparing two _non-identical_ instances of anonymous type objects?
> 
> For instance, this code works just fine:
> 
> ```cs
>         [Fact]
>         public void Should_Be()
>         {
>             var product1 = new
>             {
>                 Active = true,
>                 Name = "Produto",
>             };
> 
>             var product2 = new
>             {
>                 Active = true,
>                 Name = "Produto",
>             };
> 
>             product1.Should().Be(product2);
>         }
> ```

Just to complement my own question.

I did some further research and discovered that apparently this happens due to C# own design of Object.Equals(). As stated [here](https://stackoverflow.com/a/12124463/11234800), it seems that the method in question gets overridden by anonymous types, "so that two instances of the same anonymous type are equal if and only if all their properties are equal".

**Comment by dennisdoomen** [comment]
> I did some further research and discovered that apparently this happens due to C# own design of Object.Equals(). As stated [here](https://stackoverflow.com/a/12124463/11234800), it seems that the method in question gets overridden by anonymous types, "so that two instances of the same anonymous type are equal if and only if all their properties are equal".

Yep. That's why we have two methods. Sometimes people override `Equals` on a subset of the properties, so just using `Be` might not what you want. Just like you sometimes use `Equals`, `==` or `ReferenceEquals` for reasons.

I'm closing this issue since FA does exactly how it is documented and designed.
