### ISSUE TITLE
NotHaveCount throws on null

### ISSUE THREAD

**Issue by Crashdummyy** [fluentassertions/fluentassertions#1241]
### Description

Hello, 
I don't  know if this is on purpose but if I check against a specific Count on an Array the Assertion fails if the Array is null.
Asserting Array.Should().NotHaveCount(1) should succeed if the Array is null in my opinion

### Complete minimal example reproducing the issue

```csharp
public class Thingy
{
    public ArrayThingy[] ArrayThinges { get; set; }
}

public class ArrayThingy
{
    public int Id { get; set; }
}
...
...
// Arrange
var data = new Thingy
                  {
                       ArrayThingies = null
                  };

// Assert
data.ArrayThingies.Should().NotHaveCount(1)
```

### Expected behavior:

This test should pass as the Array is null and therefore does not hold exactly one item

### Actual behavior:

```csharp
Expected data.ArrayThinges to not contain 1 item(s), but found <null>.
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Collections.SelfReferencingCollectionAssertions`2.NotHaveCount(Int32 unexpected, String because, Object[] becauseArgs)
```

### Versions

```csharp
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.2.0" />
    <PackageReference Include="FluentAssertions" Version="5.10.0" />
    <PackageReference Include="Moq" Version="4.13.1" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
    <PackageReference Include="coverlet.collector" Version="1.0.1" />
  </ItemGroup>
```

**Comment by dennisdoomen** [comment]
Thanks for reporting this. But to be frank, my first reaction is to disagree. I would be very much surprised if it would behave like you're suggesting. Plus, I wonder why the count should not be `1` specifically.

**Comment by Crashdummyy** [comment]
Im just doing some mapping.
The ArrayThingy is only filled under some circumstances.
Afterwards I calculate some values in a specific way if the Array length is exactly one.

**Comment by krajek** [comment]
I also, just as @dennisdoomen think that current behavior is sensible. 

Additionally, if you treat your tests as examples then for the particular example you could just assert that collection is null.

Other way to approach your problem is to write custom extension method that asserts exactly what you expect, maybe even using your domain language for better readability.

**Comment by Crashdummyy** [comment]
I thought about and I guess you're both right.
I wanted to treat notHaveCount as "Everything except" but thats not the case as 'null' does not exist at all.
Well I don't care that much about it as null sucks so bad that my Code will (almost) never produce it
