### ISSUE TITLE
Should().Be() is claiming that objects aren't equal even though they should be equal

### ISSUE THREAD

**Issue by nadvolod** [fluentassertions/fluentassertions#1242]
### Description
When running my test I'm getting the following error
```
  Message: 
    Expected SauceOptions.BrowserName to be chrome, but found chrome.
  Stack Trace: 
    LateBoundTestFramework.Throw(String message)
    TestFrameworkProvider.Throw(String message)
    DefaultAssertionStrategy.HandleFailure(String message)
    AssertionScope.FailWith(Func`1 failReasonFunc)
    AssertionScope.FailWith(Func`1 failReasonFunc)
    AssertionScope.FailWith(String message, Object[] args)
    ObjectAssertions.Be(Object expected, String because, Object[] becauseArgs)
    SauceOptionsTests.UsesLatestChromeWindowsVersionsByDefault() line 29
```

[Description of the issue]

### Complete minimal example reproducing the issue

```csharp
[TestMethod]
public void UsesLatestChromeWindowsVersionsByDefault()
{
    SauceOptions = new SauceOptions();
    SauceOptions.BrowserName.Should().Be(Browser.Chrome);
}

public class SauceOptions
{
    private Browser _browserName = Browser.Chrome;
    public Browser BrowserName 
    { 
        get
        {
            return _browserName;
        }
    }
}
```

### Expected behavior:

For the test to pass and assert true

### Actual behavior:
Failure with message
```
  Message: 
    Expected SauceOptions.BrowserName to be chrome, but found chrome.
  Stack Trace: 
    LateBoundTestFramework.Throw(String message)
    TestFrameworkProvider.Throw(String message)
    DefaultAssertionStrategy.HandleFailure(String message)
    AssertionScope.FailWith(Func`1 failReasonFunc)
    AssertionScope.FailWith(Func`1 failReasonFunc)
    AssertionScope.FailWith(String message, Object[] args)
    ObjectAssertions.Be(Object expected, String because, Object[] becauseArgs)
    SauceOptionsTests.UsesLatestChromeWindowsVersionsByDefault() line 29
```

### Versions

* Which version of Fluent Assertions are you using?
5.9.0
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.1.
.NET Core 3.0

**Comment by jnyrup** [comment]
I don't have your `Browser` class available, so I'll have to guess.
`Be` uses the possibly overridden `object.Equals` of the `Browser` class to compare objects.
In general if `a.Equals(b)` returns `true`, `a.Should().Be(a)` should pass.

What is the output if you write of this?
```c#
SauceOptions.BrowserName.Equals(Browser.Chrome)
```

**Comment by nadvolod** [comment]
Sorry, here's Browser.cs
```csharp
    public class Browser
    {
        private Browser(string browserName)
        {
            Value = browserName;
        }

        private string Value { get; set; }

        public static Browser Chrome => new Browser("chrome");
```
Here's the output 
```
SauceOptions.BrowserName.Equals(Browser.Chrome)
false
```

**Comment by jnyrup** [comment]
### Issue

* `Be` uses `object.Equals` to compare `SauceOptions.BrowserName` and `Browser.Chrome`.
* Since `Browser` does not override `object.Equals`, two instances of `Browser` are compared by reference equality, i.e. they are *only* equal if they are the exact same object in memory.
* `Browser.Chrome` uses `=>`, so it returns a *new* instance of `Browser` each time called.
* Therefore `SauceOptions.BrowserName` and `Browser.Chrome` are not equal since they are two different instances of `Browser`.

### How to fix it
If possible I would make `Browser` immutable and let the `Chrome` property return the *same* instance every time invoked.

```c#
public sealed class Browser
{
    private Browser(string browserName)
    {
        Value = browserName;
    }

    private string Value { get; }

    public static Browser Chrome { get; } = new Browser("chrome");

    public override string ToString()
    {
        return Value;
    }
}
```

Another way is to override `object.Equals` on `Browser`:

```c#
public class Browser
{
    private Browser(string browserName)
    {
        Value = browserName;
    }

    private string Value { get; set; }

    public static Browser Chrome => new Browser("chrome");

    public override string ToString()
    {
        return Value;
    }

    public override bool Equals(object obj)
    {
        return obj is Browser other
            && Value.Equals(other.Value);
    }

    public override int GetHashCode()
    {
        return Value.GetHashCode();
    }
}
```

**Comment by dennisdoomen** [comment]
I do wonder if we can do something to make the distinction clearer if the `IValueFormatters` for the actual and expectation yield the same output

**Comment by nadvolod** [comment]
Excellent solution @jnyrup ! It worked. You're the best. Really appreciate you 🙏
