### ISSUE TITLE
string.NotMatch() and Match() don't fail consistently with nulls

### ISSUE THREAD

**Issue by tomaustin700** [fluentassertions/fluentassertions#1243]
### Description

If you attempt to do NotMatch(null) on a string it will fail when the string is not null

### Complete minimal example reproducing the issue

```csharp
// Arrange
string testString = "fdgkdfgkjdfg";

// Assert
testString.Should().NotMatch(null);
```

### Expected behavior:

Test should pass as string is not null

### Actual behavior:

Test fails

### Versions

FluentAssertions 5.10.0
net core 3.1

**Comment by dennisdoomen** [comment]
`NotMatch` is supposed to take a wildcard pattern. It's a required parameter, so if you pass `null` as the argument, it is expected to throw you an exception.

**Comment by tomaustin700** [comment]
Hi @dennisdoomen, thanks for getting back to me. That makes sense but it isn't consistent with how `Match` works though as this throws no exception:
```csharp
string testString = null;
testString.Should().Match(null);
```

**Comment by dennisdoomen** [comment]
Hmm, that's a problem indeed. We'll need to make them consistently fail.
