### ISSUE TITLE
Add NotBeNullNorEmpty

### ISSUE THREAD

**Issue by NN---** [fluentassertions/fluentassertions#1245]
### Description

I suggest to add `NotBeNullNorEmpty` which makes assertion clear.

### Complete minimal example reproducing the issue

```csharp
// Arrange

// Act
string result = GetString();

// Assert
result.Should().NotBeNullNorEmpty();
```

### Versions

* Which version of Fluent Assertions are you using? 5.0
* Which .NET runtime and version are you targeting? .NET Core 3.1

**Comment by dennisdoomen** [comment]
How is that different from `NotBeNullOrEmpty`?

**Comment by jnyrup** [comment]
The difference seems to be grammatically?

* "not be null *or* empty" is strictly speaking `!null || empty`, while
* "not be null *nor* empty" is the *correct* way to express `!(null || empty)`.

**Comment by dennisdoomen** [comment]
See also https://english.stackexchange.com/questions/82842/cannot-be-null-or-empty-vs-cannot-be-null-nor-empty

It seems to be common to combine `nor` with `neither` and not use it in a stand-alone fashion. I vote for keeping the existing API in place.

**Comment by dennisdoomen** [comment]
Or an even better explanation: https://english.stackexchange.com/a/208835

**Comment by NN---** [comment]
>But it does not make sense to check a char for null or emptiness -- it can never be either.

Correct, the example was not good.
I changed to `string`

**Comment by NN---** [comment]
>It seems to be common to combine nor with neither and not use it in a stand-alone fashion. I vote for keeping the existing API in place.

My suggestion is to add another method.
Removing the existing one will break compilation.

**Comment by dennisdoomen** [comment]
That would make it every more confusing.

**Comment by jnyrup** [comment]
I also vote for keeping the API as it is.
