### ISSUE TITLE
5.10.0: Exception with { } from json content failed string.Format

### ISSUE THREAD

**Issue by shuodong** [fluentassertions/fluentassertions#1255]
### Description

```c#
public void TestCurly()
{
	List<string> expected = new List<string>();
	expected.Add("item1");

	try
	{
		expected.Should().BeEmpty();
	}
	catch (Exception e)
	{
		string s = string.Format(e.Message);
	}
}
```

### Expected behavior:

Exception thrown by `expected.Should().BeEmpty();` should have `{{ }}`

### Actual behavior:

Exception thrown by `expected.Should().BeEmpty();` only have `{ }` which cause `string.Format` to throw

### Versions

* Which version of Fluent Assertions are you using?
5.10.0
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.1.
.net 4.5

### Additional Information
I expect this is a known issue which should be fixed already by https://github.com/fluentassertions/fluentassertions/pull/582

**Comment by dennisdoomen** [comment]
I've just tried the following on `master`:

```csharp
        [Fact]
        public void When_scenario_it_should_behavior()
        {
            // Arrange
            List<string> expected = new List<string>();
            expected.Add("item1");

            expected.Should().BeEmpty();
```

And it gave me:

`Expected expected to be empty, but found {"item1"}.`

**Comment by shuodong** [comment]
Thanks for trying the repro. according to the note from https://github.com/fluentassertions/fluentassertions/pull/582
this issue should be fixed and we should get {{"item1" }} instead. 

This is a pretty annoying problem as we write exception from fluent to our log and {"item1"} would throw. I've worked around this problem for now by replacing { with {{ in our system. Would love to see a native solution. Thanks!

**Comment by dennisdoomen** [comment]
Ah, you mean that the exception message we return cannot be passed to `string.Format`? If so, it's not intended to do that. You would need to escape the message before you process it further yourself. 

In short, this is not a bug in FA.

**Comment by shuodong** [comment]
Thinking more about that, that makes sense to fix on our side. Thanks for the reponse!
