### ISSUE TITLE
PropertyInfoSelectorAssertions.NotBeWritable?

### ISSUE THREAD

**Issue by Crono1981** [fluentassertions/fluentassertions#1256]
Hi,

I just found out about `PropertyInfoSelector` type and its corresponding `PropertyInfoSelectorAssertions` type. I see that there's a `BeWritable` assertion method included, but oddly enough, there's no `NotBeWritable` counterpart.

Is there a reason why? I'd like to know before I implement my own `NotBeWritable` extension method. :)

Thank you!

**Comment by dennisdoomen** [comment]
There is... see https://github.com/fluentassertions/fluentassertions/blob/87ccb0d55f5a29a05693fb857d332d9a2f69edd0/Src/FluentAssertions/Types/PropertyInfoAssertions.cs#L120

**Comment by Crono1981** [comment]
@dennisdoomen Thanks but that's `PropertyInfoAssertions`. I'm asking about `PropertyInfoSelectorAssertions`. ;)

**Comment by Crono1981** [comment]
https://github.com/fluentassertions/fluentassertions/blob/87ccb0d55f5a29a05693fb857d332d9a2f69edd0/Src/FluentAssertions/Types/PropertyInfoSelectorAssertions.cs

**Comment by dennisdoomen** [comment]
I see. Well, we would welcome a PR ;-)

**Comment by dramurai** [comment]
I could take a shot at this, unless I should interpret @jnyrup 👍 as sign that he is willing to do it.

**Comment by jnyrup** [comment]
@damirarh You're very welcome to take a shot at this. 
My 👍 was just an agreement to Dennis's comment about us welcoming PRs.
