### ISSUE TITLE
FluentAssertions seemingly confuses between two lines

### ISSUE THREAD

**Issue by ArXen42** [fluentassertions/fluentassertions#1259]
### Description

I have encountered extremely weird behavior of FluentAssertions. Currently can't isolate it from my project (which is 1 day old though), so including screenshots.

### Expected behavior:

Expect FluentAssertions to not freak out :)

### Actual behavior:

1. This is correct behavior (with commented line):
![good](https://user-images.githubusercontent.com/10744285/75099711-cb929e00-55d5-11ea-911a-f7edd9d59da0.png)
2. This is incorrect behaviour (uncommented line):
![bad](https://user-images.githubusercontent.com/10744285/75099716-d5b49c80-55d5-11ea-8f35-83432bb19ec0.png)
It fails on the first line but shows message template from second.
3. And here FluentAssertions context feature disables completely if I add one line of code between them:
![wat](https://user-images.githubusercontent.com/10744285/75099720-eebd4d80-55d5-11ea-8fda-e9a7a520325f.png)

I will continue tests and try to isolate issue but perhaps it is somehow related to multithreading problems.

### Versions

Environment is Linux x64, JetBrains Rider, .NET CoreApp 3.1, Fluent Assertions 5.10.2

**Comment by ArXen42** [comment]
Oops, I was building in Release mode. Guess that was source of a problem (some code reflection features probably broken because of optimizations).

If testing in Release mode is not supported then I'm extremely sorry for bothering you and the issue can be closed.

**Comment by jnyrup** [comment]
The assertions themselves should work in release mode. (If not that sounds like a bug somewhere)
Only line numbers in failure messages are not reliable in release mode.

**Comment by dennisdoomen** [comment]
Correct. In release mode, the compiler does some weird tricks to make your code more efficient. Especially reordering of lines and in-lining methods is notorious and kills our ability to traverse stack frames.
