### ISSUE TITLE
Should().AllBeEquivalentTo does not work on List<String>

### ISSUE THREAD

**Issue by michaelveloz** [fluentassertions/fluentassertions#1263]
Should().AllBeEquivalentTo works for Lists of various types, but appears not to work for `List<String>`, in version 5.10.2

This is very easy to reproduce. In a new Net Framekwork 4.7.2 app, add these two lines of code to any event handler:

```c#
new List<int> { 1, 2, 3 }.Should().AllBeEquivalentTo(new List<int> { 1, 2, 3 });
new List<String> { "a", "b", "c" }.Should().AllBeEquivalentTo(new List<String> { "foo", "bar" });
```
The first line generates no errors, the second line generates `'StringCollectionAssertions' does not contain a definition for 'AllBeEquivalentTo' and no accessible extension method 'AllBeEquivalentTo' accepting a first argument of type 'StringCollectionAssertions' could be found (are you missing a using directive or an assembly reference?)`

It seems like I must be missing something very obvious, but the documentation does not say that there are special requirements for `List<String>`

I see that in the case of `List<int>` `GenericCollectionAssertions` is providing the assertion, but the error for `List<string>` implies that the reference is trying to be resolved against `StringCollectionAssertions` - is this a separate module?

**Comment by jnyrup** [comment]
Collections of `string`s are handled by [`StringCollectionAssertions`](https://github.com/fluentassertions/fluentassertions/blob/develop/Src/FluentAssertions/Collections/StringCollectionAssertions.cs) which does not have an `AllBeEquivalentTo`.
Other generic collections such as e.g. `List<int>` are handled by [`GenericCollectionAssertions<T>`](https://github.com/fluentassertions/fluentassertions/blob/develop/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs) which does have an `AllBeEquivalentTo`.

But we are welcoming PR to add the same support for `StringCollectionAssertions`.

Be aware that `AllBeEquivalentTo` is intended to verify that every element in the subject is equivalent to a *single* expected element.

```c#
new List<int> { 1, 1, 1 }.Should().AllBeEquivalentTo(1);
```

**Comment by dennisdoomen** [comment]
Yeah, I'm pretty sure @michaelveloz actually meant to just use `BeEquivalentTo`.

**Comment by rynkevich** [comment]
I think that string collections should also support this functionality, so I've provided a PR to add it. @jnyrup, @dennisdoomen I would be glad if you take a look at it.

**Comment by dennisdoomen** [comment]
There's some confusion here. 
* There's a `BeEquivalentTo` for other types, which does a deep structural comparison between two 
collections in ignores the order for most types. 
* There's a `AllBeEquivalentTo` for other types, which does a deep structural comparison between a collection and a single object. 
* There's a `BeEquivalentTo` available to string _collections,_ that will assert that two collections contain the same strings in any order and that is case-sensitive. 
* There's a `BeEquivalentTo` available to strings, which will ensure two strings are the same except for their casing.

So if the intention of this issue (and the PR created by @rynkevich) is to allow developers to ensure that all strings in a collection match a single string in a case-sensitive way, I would call that method `AllBe`. E.g. `collectionOfStrings.Should().AllBe("a single string")`

**Comment by rynkevich** [comment]
Yes, there is definitely something wrong with naming.

I agree that `AllBe()` sounds more clear and is more suitable for the methods I provided in PR. It also looks like case-insensitive comparison with `AllBeEquivalentTo()` would be useful.

However, there's a problem with `BeEquivalentTo()` for string collection and strings. If by saying "the string is _equivalent_ to another string" we mean that they are the same except for their casing, then saying "the string collection is _equivalent_ to another string collection" implies that for each string in one collection there is an _equivalent_ string in another one and these equivalency pairs do not intersect. Isn't it? Right now it works in a different way, which leads to some confusion.

**Comment by dennisdoomen** [comment]
I agree that the terminology can be a bit confusing sometimes, however since you're comparing a _collection_ of strings, the current behavior of `BeEquivalentTo` on `StringCollectionAssertions` is consistent with other collections. 

Regardless, I stay with my original proposal. What's being asked in this issue should be named `AllBe`

**Comment by rynkevich** [comment]
@dennisdoomen, I've pushed changes where this method is renamed to `AllBe`.

**Comment by dennisdoomen** [comment]
Solved by providing the `AllBe` method for string collections.
