### ISSUE TITLE
Subject in exception has truncated curly brackets

### ISSUE THREAD

**Issue by hallipr** [fluentassertions/fluentassertions#1279]
### Description

In string validation, when the subject or expectation string contain more than 3 concurrent curly braces, 2 are removed in the exception message.

### Complete minimal example reproducing the issue

```csharp
var expected = "{{{{test}}}}";
var actual = "{{{{test2}}}}";

actual.Should().Be(expected);
```

### Expected behavior:

exception thrown with message:
> Expected string to be "{{{{test}}}}" with a length of 12, but "{{{{test2}}}}" has a length of 13, differs near "2}}" (index 8).

### Actual behavior:

exception thrown with message:
> Expected string to be "{{test}}" with a length of 12, but "{{test2}}" has a length of 13, differs near "2}}" (index 8).

### Versions

I've seen this in versions 5.6 and 5.10.3
.NET Core 3.1.1

### Additional Information

This affects json serialization tests:

``` csharp
	var expected = "{\"a\":{\"b\":{\"c\":{\"d\":\"e\"}}}}";
	var actual = "{\"a\":{\"b\":{\"c\":{\"d\":\"e\"}}";
	
	actual.Should().Be(expected);
```
> Expected string to be "{"a":{"b":{"c":{"d":"e"}}" with a length of 27, but "{"a":{"b":{"c":{"d":"e"}}" has a length of 25, differs near "}" (index 24)...

**Comment by jnyrup** [comment]
This was probably fixed in `develop` with #1234.

The failure message in the `develop` branch
```
Expected actual to be 
    "{{{{test}}}}" with a length of 12, but 
    "{{{{test2}}}}" has a length of 13, differs near "2}}" (index 8).
```

**Comment by hallipr** [comment]
Looks like.  Sorry, I should have searched closed issues too.

**Comment by dennisdoomen** [comment]
> I should have searched closed issues too.

No worries. I happens to me all the time on other OSS projects.
