### ISSUE TITLE
Open up `OccurenceConstraint` for usage in custom assertion extensions

### ISSUE THREAD

**Issue by brooknovak** [fluentassertions/fluentassertions#1281]
The `OccurrenceConstraint.Assert()` method is internal - so people who write their own extensions cannot use this very handy constraint (and therefore create their own - creating inconsistency of how to deal with assertion occurences).

Understand why this is internal - so the actual usage hides this when defining an assertion for the test.
However why not add a new overload in the `Execute` assertion fluent API to accept a `OccurrenceConstraint`. i.e. as an alternative to `ForCondition(...)`:

```c#
Execute.Assertion
    .BecauseOf(because, becauseArgs)
    .ForConstraint(constraint)
    .FailWith("Expected {0}{reason} but found {1}",
              constraint, Subject.Count());
```

Note there would be a formatter for the occurrence constraint to render the expected amount / "mode" (since these are also internal - and should continue to be)

**Comment by rynkevich** [comment]
After some research I can offer a few solutions for this feature. I'll list and describe them below.
@brooknovak @dennisdoomen @jnyrup It would be great if you could look through and give some comments on this. 

---
A) **Literally what @brooknovak asked**

**Overview**: `ForConstraint` method is added specifically for `OccurrenceConstraint`. A new formatter for `OccurrenceConstraint` is also registered.

**Pros**:
- The simplest solution.

**Cons**: 
- Constraint, probably, is not something that should have a global formatter. It just needs a particular formatter in this particular case.
- With this API user must specify some information twice (expected and actual values in both `ForConstraint` and `FailWith`).
- It's not the best solution from the extension interface perspective: 
a) If more "assertable" constraints will appear, either `ForConstraint` will have to be rewritten or more overloads added.
b) The need to add a new formatter for new "assertable" constraint is not explicit.

**Possible implementation**
```
// AssertionScope.cs

public AssertionScope ForConstraint(OccurrenceConstraint constraint, int actual)
{
    succeeded = constraint.Assert(actual);

    return this;
}

...

// OccurrenceConstraintFormatter.cs

public class OccurrenceConstraintFormatter : IValueFormatter
{
    public bool CanHandle(object value) => value is OccurrenceConstraint;

    public string Format(object value, FormattingContext context, FormatChild formatChild)
    {
        var occurrenceConstraint = (OccurrenceConstraint)value;

        return $"{occurrenceConstraint.Mode} {occurrenceConstraint.ExpectedCount.Times()}";
    }
}

...

// Formatter.cs

private static readonly List<IValueFormatter> DefaultFormatters = new List<IValueFormatter>
{
    ...
    new OccurrenceConstraintFormatter()
}
```

**Usage**
```
Execute.Assertion
    .BecauseOf(because, becauseArgs)
    .ForConstraint(constraint, Subject.Count())
    .FailWith("Expected {0}{reason} but found {1}",
        constraint, Subject.Count());
```
---
B) **Generalized solution**

**Overview**: `ForConstraint` is added for `AssertableConstraint`, which is an abstract base class for constraints with `Assert` method. Probably, interface would be more suitable here, but it won't allow keeping it `internal`. A new formatter for `AssertableConstraint` is registered, which invokes formatting logic, defined inside the constraint implementation.

**Pros**:
- Agile, scalable solution.
- The need for formatting logic implementation is obvious. 

**Cons**:
- The most complicated.
- A little bit more reflection than it should be.
- Global formatter for constraints is still required.
- Duplicate specification of expected and actual values is still required.
- Makes less sense if more "assertable" constraints will not ever appear.

**Possible implementation**
```
// AssertableConstraint.cs

public abstract class AssertableConstraint<T>
{
    internal abstract bool Assert(T actual);

    internal abstract string Format(); // or a better name
}

...

// OccurrenceConstraint.cs

public abstract class OccurrenceConstraint : AssertableConstraint<int>
{
    ...

    internal override string Format() => $"{Mode} {ExpectedCount.Times()}";
}

...

// AssertionScope.cs

public AssertionScope ForConstraint<T>(AssertableConstraint<T> constraint, T actual)
{
    succeeded = constraint.Assert(actual);

    return this;
}

...

// AssertableConstraintFormatter.cs

public class AssertableConstraintFormatter : IValueFormatter
{
    public bool CanHandle(object value) => IsInstanceOfGenericType(typeof(AssertableConstraint<>), value);

    public string Format(object value, FormattingContext context, FormatChild formatChild)
    {
        var constraint = (OccurrenceConstraint)value;

        return constraint.Format();
    }

    private static bool IsInstanceOfGenericType(Type genericType, object instance)
    {
        Type type = instance.GetType();

        while (type != null)
        {
            if (type.IsGenericType && type.GetGenericTypeDefinition() == genericType)
            {
                return true;
            }

            type = type.BaseType;
        }

        return false;
    }
}

...

// Formatter.cs

private static readonly List<IValueFormatter> DefaultFormatters = new List<IValueFormatter>
{
    ...
    new AssertableConstraintFormatter()
}
```

**Usage**
```
Execute.Assertion
    .BecauseOf(because, becauseArgs)
    .ForConstraint(constraint, Subject.Count())
    .FailWith("Expected {0}{reason} but found {1}",
        constraint, Subject.Count());
```
---
C) **Generalized solution with placeholders for formatting**

**Overview**: The same as B), but API is changed to use special placeholders `FailWith` message argument so there is no need for formatters.

**Pros**:
- Scalable, the most agile solution.
- The need for formatting logic implementation is obvious.
- API does not have redundancies.
- No global formatters for constraints. 

**Cons**:
- Not as simple as A).
- A little bit more reflection than it should be.
- Existence of special placeholders is not obvious for a library user.

**Possible implementation**
```
// AssertableConstraint.cs

public abstract class AssertableConstraint<T>
{
    internal abstract bool Assert(T actual);

    internal abstract void RegisterReportables(AssertionScope scope);
}

...

// OccurrenceConstraint.cs

public abstract class OccurrenceConstraint : AssertableConstraint<int>
{
    ...

    internal override void RegisterReportables(AssertionScope scope)
    {
        scope.AddReportable("occurrenceMode", Mode);
        scope.AddReportable("expectedOccurrenceCount", ExpectedCount.Times());
    }
}

...

// AssertionScope.cs

public AssertionScope ForConstraint<T>(AssertableConstraint<T> constraint, T actual)
{
    succeeded = constraint.Assert(actual);
    constraint.RegisterReportables(this);

    return this;
}
```

**Usage**
```
Execute.Assertion
    .BecauseOf(because, becauseArgs)
    .ForConstraint(constraint, Subject.Count())
    .FailWith("Expected {occurrenceMode} {expectedOccurrenceCount} {reason} but found {1}");
```
---

**Comment by dennisdoomen** [comment]
Very impressive and well-thought-out set of proposals. I'm in doubt between B or C. B is a bit more explicit, but C is doing what we kind of already doing with `{reason`}`.

**Comment by brooknovak** [comment]
@rynkevich loving your input on this topic.
I really like that you have not only proposed some options, but weighed up some actual pros and cons of each. It really is a great way to start solving this. Let's pull together and iterate on your proposals.

As @rynkevich has so neatly laid out for us, they way I see it we are trying to achieve the following design goals for fluent assertion constraints library (which may partly align with the overall libraries goals):

1. **Re-usability**: the core issue for this ticket. Right not we cannot re-use the existing set of constraints for custom assertions.

2. **Extensibility** (open/closed principles in SOLID): we should consider the possibility to allow for developers to extend the framework with custom constraints (implementations and the accompanying fluent api extensions). These custom constrains could be used for any assertion that supports constraints.

3. **Intuitive human readable API for the usage** - since this is a BDD fluent API: one of the killer reasons that makes this library so awesome is out tests read like natural human language.

4. **Discoverable feature-set** when extending: it should be easy for a fluent-assertions adopter to discover features to tap into from the public api (not just the docs).

5. **Easy for developers understand**:  it should be easy for a fluent-assertions adopter to figure out how to hook into the constraint library for their custom assertions by the design of the interfaces.

Goal 2 is at risk of increasing scope, but worth a mention since we are focusing on "constraints" concept as a whole.

I think all 3 options proposed address goals 1) and 3). 
Option A doesn't address goal 2) and also has issues with goals 4) and 5).

With B) and C), they increase extensibility (2), so yes it will scale to support other possible "constraints". However going down this path adds a risk of over-engineering the solution which could incur some costs: if we support "constraints" generically, rather than just Occurrence:
-  Increases library complexity: it's harder for the design to account for all sorts of possible implementations of a constraint. But it still might be worth paying this cost.
- Dilutes the concept: going generic also starts making me think "what even is a constraint?" and "what is are the differences between a vanilla assertion and a constrains?". If occurrence contains are generalised up to support any type of contraint: how does a developer choose between what is now considered to be a constraint vs a vanilla assertion. Another way to put it: what are the rules for a developers to use ForConstraint vs ForCondition? 
  - What will help guide us on this design would be to provide some examples of generic contraints that are not occurrence related.
  - This relates to @dennisdoomen's point: we start to conflate vanilla assertions with "reason" formatting and "constraints".

Personally I struggled to get up to speed with the hidden formatting rules and how they connect with the `BecauseOf()` etc.. methods. If we add more to the mix, it may just confuse people even more. If we were going to add one, then I would try simplify it to "{constraint}". Because every custom implementation that hides "reportable"'s isn't really hiding the implementation detail: rather its a leaky abstraction of formatting where the developers need to be aware of the underlying implementation of the passed in constraint being used in order to know how to format it. So the abstraction of formatting would not be as effective.

I don't have solutions to offer, but my vote at this point is:
- unless we get a clear understanding of what is a constraint - generally speaking: stick with just Occurrence constraints.
  - If we keep the scope narrow, rather than `ForConstraint(..)` we could have `ForOccurences(...)` 
- use `"{constraint}"` for formatted assertions failures. Or maybe "{constraintResult}", or "{occurrences}" or some other natural language

**Comment by dennisdoomen** [comment]
Thank you for your extensive write-up @brooknovak. I love you're five design principles. With your permission, I'd like to use them for future reference. And I think you're right. We should try to avoid making the internal assertion API too generic and extensible. So let's stay away from making the constraints abstract and stick to a specific API for occurrence-based constraints. I also think it's fine to introduce another well-named placeholder as long as make sure we document it on the `FailWith` method.

**Comment by brooknovak** [comment]
Go for it @dennisdoomen - use whatever you like. I love this library, it's really helped shape the way I approach testing!

**Comment by eNeRGy164** [comment]
> ... I love you're five design principles. With your permission, I'd like to use them for future reference...

While reading @brooknovak's excellent post, I thought that FA should have some ADR's. It would be good to know the thoughts behind the design, specially when you want to contribute or extend FA.

**Comment by dennisdoomen** [comment]
> I thought that FA should have some ADR's. It would be good to know the thoughts behind the design, specially when you want to contribute or extend FA.

That's not a bad idea at all. Or at least some design principles such as these and how to deal with `null` arguments and such.

**Comment by rynkevich** [comment]
@brooknovak, thanks for your great feedback and for well-formed and precise set of design principles you have formulated.
I also think that generalized solution for this issue looks more like over-engineering than something that solves a real problem. The best option is, as always, something in between - I like the changes you voted for and I'll prepare a PR shortly.

**Comment by rynkevich** [comment]
I'll quote @jnyrup's comment so it is visible here:
> It would be nice having a test that adds a custom `OccurrenceConstraint` to exemplify the purpose of `ForConstraint` for library consumer.
@brooknovak could you provide us with such?

**Comment by brooknovak** [comment]
This is a cut-down version of what I already have in one of my assertion libraries .. (where currently I have to write my own `OccurrenceConstraint` whic hwas essentially a copy-n-paste from this github repo :) - ive modified the `FailWith(...)` with the proposed "{constraint}" formatter.

```
public class LogEventsAssertions : ReferenceTypeAssertions<IEnumerable<LogEvent>, LogEventsAssertions>
{
  ...
        public LogEventsAssertions Occuring(
            OccurrenceConstraint constraint,
            string because = "",
            params object[] becauseArgs)
        {
            Execute.Assertion
                .BecauseOf(because, becauseArgs)
                .ForConstraint(constraint, Subject.Count())
                .FailWith("Expected {context:logs} {constraint}{reason}");
            return this;
        }

  ...
}
```

**Comment by phillip-haydon** [comment]
Shouldn't all assertions be open?

It appears I cannot add a custom assertion for string length. There's only 1 option which is for a fixed length, but I need to ensure a length is not exceeded.

If I check against `thing.Length.Should()...` then you end up with useless messages which aren't helpful. 

> Expected name.Length to be less or equal to 128, but found 131.

And there's no documentation to explain if this is possible to implement.

**Comment by jnyrup** [comment]
@phillip-haydon Your problem sounds unrelated to this issue?
Or I might just be unsure what you're asking about.

For asserting on string length, you can use
```cs
"foo".Should().HaveLength(3);
```

If this doesn't answer your question and it's not related to `OccurenceConstraint`, please open a new issue.

**Comment by phillip-haydon** [comment]
I just included it here because it appears that Fluent Assertions is very closed, difficult to extend, unable to extend for string comparisons. 

As is my example, you cannot extend to check string length for anything other than fixed length. (or the documentation lacks the information to explain how)

I tried to open a new issue but got a giant wall of text which is off putting.

**Comment by jnyrup** [comment]
@phillip-haydon Please take the time to read the giant wall of text, it's there for a reason.
* Right 4 other participants of this thread are receiving notifications.
* As maintainers we think it fair that an issue-opener spends some time making a good issue, before _we_ spend time reading, asking follow-up question and investigate an issue. We also value our time.

Your question/issue might very well relevant, but I would prefer I you open up a new issue, that makes it _much_ easier for us to navigate the reported issues.
Thanks.
