### ISSUE TITLE
BooleanAssertions.NotBe

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#1285]
### Description

`BooleanAssertions` is missing an `NotBe(boolean unexpected)` assertion.

### Complete minimal example reproducing the issue

One should be able to write

```csharp
// Act
bool foo = Foo();
bool bar = Bar();

// Assert
foo.Should().NotBe(bar);
```

**Comment by eNeRGy164** [comment]
I'd like to pick this one up, seems good as a first time contribution.

**Comment by jnyrup** [comment]
@eNeRGy164 You're very welcome.
It should be fairly straight forward, but let us know if you encounter any problems or have questions.

**Comment by eNeRGy164** [comment]
Does this also imply adding `NotBeTrue` and `NotBeFalse`?

**Comment by jnyrup** [comment]
My immediate thought is that `BeFalse` and `BeTrue` cover those cases fine.
