### ISSUE TITLE
Inconsistent naming for StartWithEquivalent and EndWithEquivalent

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#1286]
### Description

These two assertions does *not* end in `Of`
```
StartWithEquivalent
EndWithEquivalent
```
as all other `Equivalent` assertions on `StringAssertions` do.
```
NotStartWithEquivalentOf
NotEndWithEquivalentOf
MatchEquivalentOf
NotMatchEquivalentOf
ContainEquivalentOf
NotContainEquivalentOf
```

### Task

* Rename the two functions
* Update the docs
* Add a line to in the breaking changes section of the release notes.

**Comment by eNeRGy164** [comment]
Now I'm started, I take this one up as well :)

**Comment by eNeRGy164** [comment]
Interesting that `releases.md` mentions PR numbers, which I don't know before making the PR. ;)

**Comment by jnyrup** [comment]
If I feel lucky I try to guess what the PR number would be.
Most times I submit the PR, change `releases.md` and rebase the changes.

**Comment by eNeRGy164** [comment]
It would be good to add to CONTIBUTING.md / PR template
* Adding release notes
* Apply API changes if applicable (and how)
