### ISSUE TITLE
global.json specifies too specific version

### ISSUE THREAD

**Issue by eNeRGy164** [fluentassertions/fluentassertions#1291]
### Description

Visual Studio 2019 fails to load solution with current `global.json` and newer .NET Core SDK patch version.

### Complete minimal example reproducing the issue

My current installed SDKs:

    ❯ dotnet --list-sdks
    2.1.403 [C:\Program Files\dotnet\sdk]
    2.1.602 [C:\Program Files\dotnet\sdk]
    2.1.700 [C:\Program Files\dotnet\sdk]
    2.1.801 [C:\Program Files\dotnet\sdk]
    2.1.802 [C:\Program Files\dotnet\sdk]
    2.2.202 [C:\Program Files\dotnet\sdk]
    2.2.300 [C:\Program Files\dotnet\sdk]
    2.2.401 [C:\Program Files\dotnet\sdk]
    2.2.402 [C:\Program Files\dotnet\sdk]
    3.1.200 [C:\Program Files\dotnet\sdk]

global.json

    {
        "sdk": {
            "version": "3.1.100"
        }
    }

### Expected behavior:

Visual Studio 2019 can load solution.

### Actual behavior:

Visual Studio 2019 can't load solution.

    The project file cannot be opened by the project system, because it is missing some critical imports or the referenced SDK cannot be found.

    Detailed Information:
    Unable to locate the .NET Core SDK. Check that it is installed and that the version specified in global.json (if any) matches the installed version.

### Versions

Microsoft Visual Studio Enterprise 2019 `16.5.1`

### Additional Information

When changing global.json version to `3.1` it works as expected. (`3.1.200` as well of course, but that would also prevent a lot of people of opening the solution)

**Comment by jnyrup** [comment]
The reasons where specifying an exact version is for `build.p1`.

https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#matching-rules
> * If a *global.json* file is found and it specifies an SDK version:
>   * If no `rollFoward` value is set, it uses `latestPatch` as the default `rollForward` policy. Otherwise, check each value and their behavior in the rollForward section.

[`latestPatch`](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#rollforward)
> Uses the latest installed patch level that matches the requested major, minor, and feature band with a patch level and that is greater or equal than the specified value.
If not found, fails.
In our case `3.1.1nn`, where `nn >= 00`

If we add `"rollForward": latestFeature` it should allow
`3.1.znn` where `z >= 1`.

**Comment by eNeRGy164** [comment]
I can confirm this works
