### ISSUE TITLE
New Task .Should() extensions

### ISSUE THREAD

**Issue by michal-ciechan** [fluentassertions/fluentassertions#1305]
Wondering if it is worth adding the following 2 extension methods for `Task`/`Task<T>` to not need `Func<Task> act = ....` each time I want to assert the method call with throw an exception.

```csharp
    public static class FluentAssertionExtensions
    {
        public static NonGenericAsyncFunctionAssertions Should(this Task task)
        {
            Func<Task> act = () => task;

            return act.Should();
        }

        public static GenericAsyncFunctionAssertions<T> Should<T>(this Task<T> task)
        {
            Func<Task<T>> act = () => task;

            return act.Should();
        }
    }
```

I have been copying this code from project to project and sounds generic enough to be moved.

Probably would be best to create a `TaskAssertions` / `GenericTaskAssertions` which either inherit from or delegate to the corresponding `[Non]GenericAsyncFunctionsAssertions` on the `ThrowsAsync` etc.

If it is something you guys may be interested in adding let me know, I can create a PR.

This allows me to

```csharp
[Fact]
public async Task Test()
{
    await _sut.AsyncMethod().Should().ThrowAsync<InvalidOperationException>();
}
```
Rather than

```csharp
[Fact]
public async Task Test()
{
    Func<Task> act = () => _sut.AsyncMethod();

    await act.Should().ThrowAsync<InvalidOperationException>();
}
```

**Comment by michal-ciechan** [comment]
Also worth considering `ValueTask` /`ValueTask<T>` pair. Delegate to ValueTask.AsTask(), and then continue as normal `Task`

**Comment by jnyrup** [comment]
The current stand is not to include those assertions.
See e.g. #1001, #1011, #1013 and https://fluentassertions.slack.com/archives/C039Y2H7U/p1581329945017800

But you can write it *almost* as concise as your desired example by using `FluentActions`.
```c#
using static FluentAssertions.FluentActions;

await Awaiting(() => _sut.AsyncMethod()).Should().ThrowAsync<InvalidOperationException>();
```
