### ISSUE TITLE
AssertionExtensions.Awaiting Task method is ambiguous with ValueTask

### ISSUE THREAD

**Issue by odyth** [fluentassertions/fluentassertions#1316]
With .net core and c# 8 how are you supposed to use the AssertionExtensions.Awaiting methods? The following code worked before ValueTask was added, but now will give the following compile time error
>The call is ambiguous between the following methods or properties: 'AssertionExtensions.Awaiting<T>(T, Func<T, Task>)' and 'AssertionExtensions.Awaiting<T>(T, Func<T, ValueTask>)'

```
[Test]
public async Task TestFoo()
{
    var foo = new Foo();

    foo.Awaiting(async f => await f.BarAsync()).Should().NotThrow(); //<--compiler error
}

public class Foo
{
    public Task BarAsync() => Task.FromResult(0);
}
```

**Comment by dennisdoomen** [comment]
Which version of FA are you using and which platform are you targeting?

**Comment by dennisdoomen** [comment]
If you change the code to 

```csharp
            Func<Foo, Task> p = async f => await f.BarAsync();
            foo.Awaiting(p).Should().NotThrow(); //<--compiler error
```

It compiles properly. So it looks like it is a compiler limitation. 

Did you recently move from one version of FA to another?

**Comment by jnyrup** [comment]
When removing `async` + `await` it works

```c#
foo.Awaiting(f => f.BarAsync()).Should().NotThrow();
```

**Comment by jnyrup** [comment]
Here's a minimal example
```c#
// Func<ValueTask> a = () => Task.Delay(0); // <-- does not compile as expected
Func<ValueTask> b = async () => await Task.Delay(0); // ambiguous
Func<Task> c = () => Task.Delay(0); // compiles as expected
```

This seems to be a known limitation in C#'s overload resolution.
I believe the tracking issue is https://github.com/dotnet/csharplang/issues/98 

Not much we can do about it, except guiding people to remove the `async` + `await`.

**Comment by odyth** [comment]
thanks

**Comment by markusschaber** [comment]
The example here still advises async + await:
https://fluentassertions.com/exceptions/

`Alternatively, you can use the Awaiting method like this:

Func<Task> act = () => asyncObject.Awaiting(async x => await x.ThrowAsync<ArgumentException>());
act.Should().Throw<ArgumentException>();
`

**Comment by dennisdoomen** [comment]
Or use `ThrowAsync`

**Comment by CraigRice** [comment]
Some related information:

I had a similar issue when having to force LangVersion 6 on an old project (to use c# 6), the Should() assertion extensions wouldn't compile with "The call is ambiguous between the following methods or properties: 'DataRowAssertionExtensions.Should<TDataRow>(TDataRow)' and 'DataSetAssertionExtensions.Should<TDataSet>(TDataSet)'".

The workaround is changing "using FluentAssertions;" to "using static FluentAssertions.AssertionExtensions;"
