### ISSUE TITLE
Using FluentAssertions in VB.Net

### ISSUE THREAD

**Issue by ZipZamZappem** [fluentassertions/fluentassertions#1319]
Why does this work In C#:
  Object dt = New DateTime(1992, 11, 22, 10, 13, 29);
  dt.Should().BeOfType<DateTime>();

and this fails in VB:
  Dim dt As Object = New DateTime(1992, 11, 22, 10, 13, 29)
  dt.Should().BeOfType(Of DateTime)()
with the Exception 'Public member 'Should' on type 'Date' not found.' ?

**Comment by jnyrup** [comment]
This seems to be a limitation of VB, that you cannot invoke extension methods on `object`.

https://stackoverflow.com/questions/3227888/vb-net-impossible-to-use-extension-method-on-system-object-instance

I haven't programmed in VB before, but this compiles and works.
```vb
Imports FluentAssertions.Primitives

Module Program
    Public Function Should(ByVal obj As Object) As ObjectAssertions
        Return New ObjectAssertions(obj)
    End Function

    Sub Main()
        Dim dt As Object = New DateTime(1992, 11, 22, 10, 13, 29)
        Should(dt).BeOfType(Of DateTime)()
    End Sub
End Module
```

Hope that answers your question and solves your problem.
