### ISSUE TITLE
Feature request: SatisfyRespectively for GenericDictionaryAssertions

### ISSUE THREAD

**Issue by AroglDarthu** [fluentassertions/fluentassertions#1326]
Please consider adding `SatisfyRespectively` to `GenericDictionaryAssertion`.
Now, as a workaround, we use:
`dictionary.AsEnumerable().Should().SatisfyRespectively(...)`

**Comment by jnyrup** [comment]
@AroglDarthu Thanks for raising interest in this.

In the upcoming 6.0 this comes for free, as `GenericDictionaryAssertions` now inherits from `SelfReferencingCollectionAssertions`.

In the develop branch this example compiles and works
```cs
var dict = new Dictionary<string, int>
{
    ["foo"] = 42,
    ["bar"] = 1337
};

dict.Should().SatisfyRespectively(
    e => e.Key.Should().Be("foo"),
    e => e.Value.Should().Be(1337)
);
```
