### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Daniel15** [fluentassertions/fluentassertions#1327]
I wasn't sure of the best way of contacting the authors of this library, so I just wanted to leave a note and thank you so much for working on it! I just discovered it yesterday and really like it. Keep up the great work.

**Comment by dennisdoomen** [comment]
Thank you for those kind words. And keep spreading the love. If you keep having these feelings and you're looking for a way to vent them, consider one of the options on https://fluentassertions.com/ to support us.
