### ISSUE TITLE
ShouldBeEquivalentTo uses overriden Equals instead of comparing the properties

### ISSUE THREAD

**Issue by kkcosmo** [fluentassertions/fluentassertions#1328]
### Description

I see a different behavior between the 4.9 version of
`ShouldBeEquivalentTo`
and the current 
`Should().BeEquivalentTo`

The `BeEquivalentTo `seems to use the overriden Equals method of an object to determine the equality instead of comparing the properties

IMO this is also described here for a much earlier version: https://stackoverflow.com/questions/14238064/fluentassertions-shouldbeequivalentto-method-still-invokes-object-equals

### Complete minimal example reproducing the issue

```csharp
        public class Foo
        {
            public override bool Equals(object other)
            {
                return Equals(other as Foo);
            }
            public bool Equals(Foo other)
            {
                return other != null && other.GetType() == GetType() && other.Id == Id;
            }
            public string Id { get; set; }
            public int Bar { get; set; }
        }

// Act
            var a1 = new Foo { Id = "a", Bar = 0 };
            var a2 = new Foo { Id = "a", Bar = 10 };

// Assert
            Equals(a1, a2).Should().BeTrue();
            a1.Equals(a2).Should().BeTrue();
            a1.Should().Be(a2);

            //a1.ShouldBeEquivalentTo(a2); // fails as expected in version 4.19.4
            a1.Should().BeEquivalentTo(a2);       //should fail, but does not
```

### Expected behavior:

I expect that the BeEquivalentTo behaves the same way as the former ShouldBeEquivalentTo

### Actual behavior:

BeEquivalentTo takes a shortcut by using
public override bool Equals(object other)

### Versions

* Which version of Fluent Assertions are you using?
5.10.3
* Which .NET runtime and version are you targeting?
.NET Core 3.1.

**Comment by dennisdoomen** [comment]
This is by design and the main reason we bumped the major version in 2018. Please read [this blog](https://www.continuousimprover.com/2018/02/fluent-assertions-50-best-unit-test.html) post to understand the differences.
