### ISSUE TITLE
Variables with "Should" in the name leads to truncated stack traces

### ISSUE THREAD

**Issue by GeeWee** [fluentassertions/fluentassertions#1330]
**Before you file a bug, have you:**

### Description
If you have a variable with "Should" in the name, the stack trace will be truncated if an assertion fails.

### Complete minimal example reproducing the issue

Running this isolated in a test will reproduce the issue:
```csharp
var thisShouldActuallyBeTrue = false;
thisShouldActuallyBeTrue.Should().BeTrue();
```
and will result in a stack trace that starts like this:

```
Error Message:
   Expected thi to be true, but found False.
```

While the following example will work fine.
```csharp
var this_shouldActuallyBeABlankString = "butIt'sNot";
this_shouldActuallyBeABlankString.Should().Be("");
```
Leading to a correct stack trace. So the error only happens if there is "Should", in the name, but e.g. "should" 

I would expect both versions to lead to a stack trace with the full name of the variable. I don't know the fluentassertion codebase, but I'm assuming there's a Regex matching on a `Should` somewhere, and accidentally truncates the variable name.

### Versions

* Which version of Fluent Assertions are you using?. **I have tested this with 5.10.0 and 5.10.3**
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.1. **We are targeting .NET Core 3.1**

**Comment by dennisdoomen** [comment]
So if everything is working it _should_ (pun intended) tell you this:

`Expected thisShouldActuallyBeTrue to be true` 

Is this really something you care about?

**Comment by jnyrup** [comment]
@GeeWee Thanks for reporting this.

The problematic code is `CallerIdentifier.ExtractVariableNameFrom(StackFrame frame)`
https://github.com/fluentassertions/fluentassertions/blob/64eb84b212374c2279cb4a7ec4f23e8beb392644/Src/FluentAssertions/CallerIdentifier.cs#L88

As it tries to extract the variable name from a stack trace without proper parsing but with textual extraction we could probably always make examples to trick it. 
See https://github.com/fluentassertions/fluentassertions/issues/871#issuecomment-407867286 for an example.
But we could certainly do better, at least for simpler cases.

```
fooShould.Should()
ShouldBar.Should()
foo.
    Should()
foo
    .Should()
```

**Comment by GeeWee** [comment]
Hah, yeah that's what it should tell me. In regards to caring - is it a big problem? Not particulary, but apparently I often call variables something with `Should` so it has stumped me a couple of times
