### ISSUE TITLE
Should().Be(default) fails for a nullable int

### ISSUE THREAD

**Issue by space-alien** [fluentassertions/fluentassertions#1342]
```csharp
int? subject = null;
subject.Should().Be(default);
```

This throws:
`FluentAssertions.Execution.AssertionFailedException: Expected subject to be 0, but found <null>.`

But the test should have passed, because `default(int?)` is `null`, not `0`.

I ran into this when testing a generic class with a mix of value and reference types, where I wanted to test for `default`.

### Versions
FluentAssertions 5.10.3
.NET Core 3.1

**Comment by eNeRGy164** [comment]
You could use the pre C# 7.1 syntax: `subject.Should().Be(default(int?));`

**Comment by dennisdoomen** [comment]
Yeah, @eNeRGy164 is right. The `Be` comes from the `NumericAssertions` from which `NullableNumericAssertions` inherits from. Normally you would not compare an `int?` with `null` directly. Instead, you would use one of the available assertions like `BeNull` or `HaveValue`.

Nothing we can do here.
