### ISSUE TITLE
Fluent Assertion Should().Be() returns false positive

### ISSUE THREAD

**Issue by NamrataKankaria** [fluentassertions/fluentassertions#1347]
When i use try and catch block and under my try block when I use fluent assertions. My test gets passed even though it should fail.

Sample code -
```cs
[Test]
public void TestingFuent()
{
    try
    {
        "HI".Should().Be("as");
    }
    catch (Exception ex)
    { }
}
```
-- The above code could will go to catch block. But Test will be shown as PASSED

**Comment by eNeRGy164** [comment]
If you want the test to fail on an exception I see 3 options:
1. Remove the `try {} catch {}`, leaving only the assertion.
2. Add `throw;` inside the catch block.
3. throw a specific exception you want inside the catch block.

But as it is a unit test, why would you want to catch the exception from the assertion? This is how most people use unit tests.
The assertion exception is specifically tailored to give you information why a test has failed.

**Comment by NamrataKankaria** [comment]
> If you want the test to fail on an exception I see 3 options:
> 
> 1. Remove the `try {} catch {}`, leaving only the assertion.
> 2. Add `throw;` inside the catch block.
> 3. throw a specific exception you want inside the catch block.
> 
> But as it is a unit test, why would you want to catch the exception from the assertion? This is how most people use unit tests.
> The assertion exception is specifically tailored to give you information why a test has failed.

Thanks. Yes one way would be to remove try and catch block.
I dont want to catch exception from assertions. But I need it incase of other scenarios. 
For eg- Trying to click on a link. And the link name is incorrect. So in that case I want try catch block in order to tackle those cases.

My test is something like this-
Step1- Clicking on link
Step 2- Using Fluent Assertion to assert link title.
I need try/catch block for Step1.

**Comment by eNeRGy164** [comment]
Maybe it can be structured like this:

```csharp
[Test]
public void TestingFuent()
{
    var value = string.Empty;
    try
    {
        // Click link cod, other logic
        value = "HI";
    }
    catch (Exception ex)
    { 
        // Handle error from clicking link
    }

    value.Should().Be("as");
}
```

**Comment by NamrataKankaria** [comment]
> Maybe it can be structured like this:
> 
> ```cs
> [Test]
> public void TestingFuent()
> {
>     var value = string.Empty;
>     try
>     {
>         // Click link code, other logic
>         value = "HI";
>     }
>     catch (Exception ex)
>     { 
>         // Handle error from clicking link
>     }
> 
>     value.Should().Be("as");
> }
> ```

This is perfect. Thank you so much :)

**Comment by eNeRGy164** [comment]
No problem.
I think it is more appropriate to ask these kinds of questions at [StackOverflow](https://stackoverflow.com/questions/tagged/fluent-assertions).

**Comment by NamrataKankaria** [comment]
What do you think of this?

try
{
	ClickLink();


	using (new AssertionScope())
	{
	  LinkTitle.Should().Be("This");

        };

        catch (AssertionException a)
        {
            Assert.Fail(a.Message);
        }

       catch(Exception ex) 
       {
            
       }

}

**Comment by NamrataKankaria** [comment]
> No problem.
> I think it is more appropriate to ask these kinds of questions at [StackOverflow](https://stackoverflow.com/questions/tagged/fluent-assertions).

Yes you are right. I saw some someone having the same issue in Github and felt right to ask here :)

**Comment by eNeRGy164** [comment]
I would simplofy it like this:
```csharp
try
{
    ClickLink();

    LinkTitle.Should().Be("This");
}
catch (Exception ex) when (!(ex is AssertionException))
{
}
```

**Comment by NamrataKankaria** [comment]
> I would simplify it like this:
> 
> ```cs
> try
> {
>     ClickLink();
> 
>     LinkTitle.Should().Be("This");
> }
> catch (Exception ex) when (!(ex is AssertionException))
> {
> }
> ```

This is really better :)

**Comment by dennisdoomen** [comment]
Since this question is a merely a general programming question and not related to the functioning of FluentAssertions, we've closed this one.
