### ISSUE TITLE
Allow to inherit from SelectedMemberInfo in user libraries

### ISSUE THREAD

**Issue by MaxShoshin** [fluentassertions/fluentassertions#1350]
Now it is not possible to create class in user library inherited from `SelectedMemberInfo` as it contains internal abstract members. 

It can be usefull when implement completely different mechanism in `IMemberMatchingRule` (for example compare values between levels, etc.)

This fix can be used as a hotfix for #535 on user side.

I can create PR, but it will affect public api of the library so I would like to discuss it first.

I would like to change:
```cs
public abstract class SelectedMemberInfo
{
.....
        internal abstract CSharpAccessModifier GetGetAccessModifier();

        internal abstract CSharpAccessModifier GetSetAccessModifier();
```

to: 
```cs
public abstract class SelectedMemberInfo
{ 
....
        public abstract CSharpAccessModifier GetGetAccessModifier();

        public abstract CSharpAccessModifier GetSetAccessModifier();
```

**Comment by jnyrup** [comment]
merged in #1349
