### ISSUE TITLE
BeEquivalentTo succeeds with polymorph hierarchies where it should not

### ISSUE THREAD

**Issue by ModernRonin** [fluentassertions/fluentassertions#1351]
### Description
See code example

### Complete minimal example reproducing the issue
```csharp
class Zoo
{
	public ICollection<Animal> Animals { get; set; }= new List<Animal>();
}
abstract class Animal
{

}

class Dog : Animal
{
	public int Size { get; set; }
}

class Cat : Animal
{

}

[Test]
public void Repro()
{
	var lhs = new Zoo
	{
		Animals = new List<Animal>
		{
			new Cat(),
			new Dog() {Size = 11}, // note the different property
			new Cat(),
		}
	};
	var rhs = new Zoo
	{
		Animals = new List<Animal>
		{
			new Cat(),
			new Dog() {Size = 13}, // note the different property
			new Cat(),
		}
	};
	
	lhs.Should().BeEquivalentTo(rhs); // this passes despite the difference in the Size properties
}
```

### Expected behavior:

`lhs.Should().BeEquivalentTo(rhs)` should fail

### Actual behavior:

`lhs.Should().BeEquivalentTo(rhs)`  passes

### Versions

* Which version of Fluent Assertions are you using?
5.10.3
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.1.
netcoreapp3.1

**Comment by jnyrup** [comment]
Thanks for the complete example.

Per default Fluent Assertions compares members by their compile time types.
So the items of `Animals` are compared by the members of `Animal`, not taking into account whether it's a `Cat` or a `Dog`.

To compare objects by their runtime type, you can use
```cs
lhs.Should().BeEquivalentTo(rhs, ctx => ctx.RespectingRuntimeTypes());
```

**Comment by ModernRonin** [comment]
thanks a lot, this works indeed!
