### ISSUE TITLE
Feature request: Should be with predicate?

### ISSUE THREAD

**Issue by weitzhandler** [fluentassertions/fluentassertions#1355]
**Before you file a bug, have you:**

### Description
I often come across functions that don't exist, for instance `"A".Should().BeUpperCase()`, and I was wondering if it would make sense to have an overload that takes a `Predicate<T>` that determines the expectancy.

### Complete minimal example reproducing the issue

```csharp
// Arrange
string input = "MyString";

// Act
string actual = input.ToUpperInvariant();
```

### Desired behavior:

```csharp
// Arrange
string input = "MyString";

// Act
string actual = input.ToUpperInvariant();

// Assert
actual.Should().Be(actual => actual.All(ch => char.IsUpper(ch)));
```

**Comment by jnyrup** [comment]
`Match` is the assertion you're looking for.
```cs
actual.Should().Match(actual => actual.All(ch => char.IsUpper(ch)));
```

**Comment by weitzhandler** [comment]
Hi @jnyrup and thanks for your reponse,

For some reason, this only works properly with collections. With single items, the compiler doesn't seem to be inferring the type, for example, if I want to verify a `HttpResponseMessage` for its `IsSuccessStatusCode` property and other properties.

This won't work:

```c#
dummyResponse
                .Should().Match(response => response.IsSuccessStatusCode);
```

While this might:

```c#
dummyResponse
                .Should().Match((HttpResponseMessage r) => r.IsSuccessStatusCode);
```

But having to explicitly specify the type in the lambda is somewhat tedious and cumbersome.

**Comment by jnyrup** [comment]
What happening is:
`ReferenceTypeAssertions<TSubject>` has two overloads of `Match`

```cs
Match(Expression<Func<TSubject, bool>> predicate)
Match<T>(Expression<Func<T, bool>> predicate
```

`HttpResponseMessage.Should()` resolves to `ObjectAssertions` which inherits from `ReferenceTypeAssertions<object>`.

So now that we've lost the type, it's first `Match` overload is
```cs
Match(Expression<Func<object, bool>> predicate)
```

For other typed `XXXAssertions` inheriting from `ReferenceTypeAssertions<TSubject>` this works quite well.
E.g.
```cs
"".Should().Match(e => e.Length == 0);
```

**Comment by weitzhandler** [comment]
Basically I'm looking for a way to walk through an object and assert its properties (multiple verifications for each property) in a single line, does this feature exist?

**Comment by jnyrup** [comment]
Without an example it's hard to provide guidance in what would be the most idiomatic way.

If you want to assert on only a subset of the properties, you can use anonymous objects. 
```cs
class A
{
    B Some { get; set; }
    C Other { get; set; }
}

class B
{
    int Foo { get; set; }
    string Note { get; set; }
}

class C
{
    int Bar { get; set; }
    string Note { get; set; }
}
```

```cs
var subject = new A
{
    Some = new B
    {
        Foo = 1,
        Note = "something, something",
    },
    Other = new C
    {
        Bar = 2,
        OtherNote = "darkside"
    }
};

var expectation = new
{
    Some = new
    {
        Foo = 1
    },
    Other = new
    {
        Bar = 2
    }
};

// this will ignore `A.Some.Note` and `A.Other.OtherNote` as they are not present in `expectation`.
subject.Should().BeEquivalentTo(expectation);
```

If you want to perform different assertions on elements in a collection, you can use `SatisfyRespectively`
See https://fluentassertions.com/collections/ for an example.

**Comment by weitzhandler** [comment]
> ```cs
> var expectation = new
> {
>     Some = new
>     {
>         Foo = 1
>     },
>     Other = new
>     {
>         Bar = 2
>     }
> };
> 
> // this will ignore `A.Some.Note` and `A.Other.OtherNote` as they are not present in `expectation`.
> ```

First of all Jonas, thanks for your nice comprehensive example. This comment is the missing bit I was unaware of. I didn't know you can use anonymous types for verification, and I also thought it'll fail if the properties do not match.
That is a perfect solution.
Thank you for your time and patience explaining all that.
