### ISSUE TITLE
Feature request: lower/upper case assertions

### ISSUE THREAD

**Issue by weitzhandler** [fluentassertions/fluentassertions#1356]
### Description

Please introduce lowercase and uppercase assertions for strings or chars, for example:

```c#
// Arrange
var input = "A";

// Act
var actual = input.ToUpper();

// Assert
actual.Should().BeUpper();
actual.Should().NotBeLower();
```

**Comment by weitzhandler** [comment]
@dennisdoomen Would you accept a PR?

**Comment by jnyrup** [comment]
How about adding `case` to the name?
```cs
actual.Should().BeUppercase();
```

Do you think we should have all four combinations?
```
BeUpper
NotBeUpper
BeLower
NotBeLower
```

or would the two affirmative assertions suffice?
```
BeUpper
BeLower
```

**Comment by dennisdoomen** [comment]
> @dennisdoomen Would you accept a PR?

Absolutely. But please take into account @jnyrup's suggestions.

**Comment by weitzhandler** [comment]
> How about adding `case` to the name?

I was sticking to [`char.IsUpper`](https://docs.microsoft.com/en-us/dotnet/api/system.char.isupper).

> Do you think we should have all four combinations?

Of course. And I'd say start with adding extensions for chars, then add for string tunneling down to the char ones.

**Comment by eNeRGy164** [comment]
I guess the `ToXxxInvariant` versions are not needed here as the culture is not relevant I think?

**Comment by weitzhandler** [comment]
Or having an overload that supports `BeUpper(CultureInfo)`, which can then be used with `CultureInfo.InvariantCulture`.

**Comment by jnyrup** [comment]
Culture invariance is still relevant to behave identically on a Turkey Test no matter the current culture on the testing machine.

**Comment by weitzhandler** [comment]
> Culture invariance is still relevant to behave identically on a Turkey Test no matter the current culture on the testing machine.

That's a good point. What do you suggest the actual implementation to be then?

---

What are we implying with `"".Should().BeUpper()`?
