### ISSUE TITLE
Misleading exception message: "FluentAssertions was configured to use mstest but the required test framework assembly could not be found"

### ISSUE THREAD

**Issue by fcastells** [fluentassertions/fluentassertions#1359]
### Description

Configuring a not supported test framework in app config (eg "mstest" instead of "mstestv2") through `FluentAssertions.TestFramework` key throws a misleading exception message, which says:

> "FluentAssertions was configured to use mstest but the required test framework assembly could not be found"

When it should say something like

```csharp
string.Format("FluentAssertions was configured to use {0} but this test framework is not supported. Use one of the supported frameworks:  {1}",  frameworkName, string.Join(", ", Frameworks.Keys));
```

### Complete minimal example reproducing the issue

Add the following to app.config:

```xml
 <add key="FluentAssertions.TestFramework" value="mstest" />
```

Add a failing test:

```csharp
true.Should().BeFalse();
```

### Expected behavior:

Message saying that the configured test framework is not supported and list the supported ones

### Actual behavior:

Message saying that the test framework assembly could not be found (which leads to reviwing if the assembly is there, etc).

### Versions

.net 462
FluentAssertions version 5.10.3

**Comment by jnyrup** [comment]
Thanks for reporting this, the error message could indeed be improved.

The error message is though correct in that the necessary assembly for mstest could not be found.
If you've been digging into the code in the `develop` branch (aka. 6.0), we've removed support for "mstest" there, while 5.10 is based on `master` and has support for "mstest".
https://github.com/fluentassertions/fluentassertions/blob/master/Src/FluentAssertions/Execution/TestFrameworkProvider.cs

How do you think about this error message?
```cs
var message = string.Format("FluentAssertions was configured to use {0} but the required test framework assembly "{1}" could not be found. Please use one of the supported frameworks: {2}",  frameworkName, framework.AssemblyName, string.Join(", ", Frameworks.Keys));
```

@dennisdoomen 
Right now we silently ignore if a config value is specified but not present among the supported frameworks and use the `FallbackTestFramework `.

How about we change that to an exception, with a message like:
```cs
var message = string.Format("FluentAssertions was configured to use {0} but the requested test framework is not supported. Please use one of the supported frameworks: {2}",  frameworkName, framework.AssemblyName, string.Join(", ", Frameworks.Keys));
```

**Comment by fcastells** [comment]
Ah, I see. Yes, I looked at the develop branch, my bad. Your proposed solution covers nicely both scenarios.

**Comment by dennisdoomen** [comment]
> How about we change that to an exception, with a message like:

Sounds like a nice improvement.
