### ISSUE TITLE
Flaky test: When_task_is_checking_synchronization_context_on_UI_thread_it_should_succeed

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#1372]
When running https://ci.appveyor.com/project/dennisdoomen/fluentassertions/builds/34562293 for #1371 
`When_task_is_checking_synchronization_context_on_UI_thread_it_should_succeed` failed.
I suspect it is because it uses a `RealClock` together with the timing sensitive `CompleteWithin`.
Can the intention of the test be implementation with a timing *insensitive* assertion?

**Comment by dennisdoomen** [comment]
I guess it is to be expected to fail sometimes. Delaying for 1 second _and_ running an assertion might take a little bit more than 1 second.

**Comment by lg2de** [comment]
Please mind the sibling test without "UI".

**Comment by facundo91** [comment]
I run into the same issue. What about closing the gap temporary by adding a summary letting know future builders that it might be alright to fail from time to time?
https://github.com/fluentassertions/fluentassertions/blob/e2fd717e3366505e35cef081a4c65ba9f67909d4/Tests/FluentAssertions.Specs/Specialized/TaskAssertionSpecs.cs#L105

**Comment by dennisdoomen** [comment]
Isn't this fixed now?

**Comment by jnyrup** [comment]
Yes, #1566 should hopefully have solved this issue.
