### ISSUE TITLE
Wrong variable name in assertion failure message

### ISSUE THREAD

**Issue by martinCentric** [fluentassertions/fluentassertions#1373]
### Description

FA puts the wrong variable name in the assertion failure message.

### Complete minimal example reproducing the issue

```csharp
// Arrange/act
var registrationCodes = new[] { "blah", "blah" };
var registrationCode = registrationCodes[0];

// Assert
var numberOfOccurences = registrationCodes.Count(c => c == registrationCode);
numberOfOccurences.Should().Be(1, because: $"registration codes should be unique"); // this assertion fails, producing the error message
registrationCode.Length.Should().Be(registrationCodes[0].Length, because: "all generated registration codes should have the same length");
```

### Expected behavior:

I expect FA to produce the following message:

> Expected **numberOfOccurences** to be 1 because registration codes should be unique, but found 2.

Or alternatively:

> Expected value to be 1 because registration codes should be unique, but found 2.

### Actual behavior:

FA produces the following message:

> Expected **registrationCode.Length** to be 1 because registration codes should be unique, but found 2.

### Versions

* Fluent Assertions: 5.10.3
* .NET: .NET Core 3.1.

**Comment by jnyrup** [comment]
When I run your example I get the expected message:
```
Expected numberOfOccurences to be 1 because registration codes should be unique, but found 2.
```

Please double check your example in a completely fresh solution to be sure nothing else is interfering.

**Comment by martinCentric** [comment]
I tried that, and found out the issue only occurs in the release version. So that's probably why you get the expected message.

In case you can't reproduce in release configuration, here's my solution:

[ReproduceFluentAssertionsIssue1373.zip](https://github.com/fluentassertions/fluentassertions/files/5057974/ReproduceFluentAssertionsIssue1373.zip)

**Comment by martinCentric** [comment]
Oops. Didn't mean to close...

**Comment by jnyrup** [comment]
Subject identification does not work reliably in release mode, you would need to build your unit test project in debug mode.

https://fluentassertions.com/introduction#subject-identification
> Since it needs the debug symbols for that, this will require you to compile the unit tests in debug mode, even on your build servers.

**Comment by martinCentric** [comment]
OK. I'll close this issue then.
Thanks for the info.
