### ISSUE TITLE
BeOfType() does not exist for nullable DateTime

### ISSUE THREAD

**Issue by ebewley** [fluentassertions/fluentassertions#1385]
### Description

Documentation says that `BeOfType()` is available for all types, but I am getting an error when I try to use it for a nullable DateTime variable.

### Complete minimal example reproducing the issue

```csharp
using System;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace MyTests.ModelTests
{
    [TestClass]
    public class ModelTest
    {
        [TestMethod]
        public void ModelTest
        {
            DateTime? value = DateTime.Now;
            int x = 3;

            x.Should().BeOfType(Type.GetType("int"));  // everything is fine
            value.Should().BeOfType(Type.GetType("DateTime?"));  // error
        }
    }
}
```

### Expected behavior:

Expect no errors.

### Actual behavior:

Code-time error
```
'NullableDateTimeAssertions' does not contain a definition for 'BeOfType' and no accessible extension method 'BeOfType' accepting a first argument of type 'NullableDateTimeAssertions' could be found ...
```

### Versions

* Which version of Fluent Assertions are you using?  **5.10.3**
* Which .NET runtime and version are you targeting?  **.NET Core 2.1**

### Additional Information

None

**Comment by jnyrup** [comment]
The documentation is simply incorrect in that `BeOfType` is available for *all* types.

The following assertion classes do not inherit from `ReferenceTypeAssertions` where `BeOfType` is defined.
```
BooleanAssertions
DateTimeAssertions
DateTimeOffsetAssertions
GuidAssertions
NullableBooleanAssertions
NullableDateTimeAssertions
NullableDateTimeOffsetAssertions
NullableGuidAssertions
NullableNumericAssertions<T>
NullableSimpleTimeSpanAssertions
NumericAssertions<T>
SimpleTimeSpanAssertions

MethodInfoSelectorAssertions
PropertyInfoSelectorAssertions
TypeSelectorAssertions
ExecutionTimeAssertions
TaskCompletionSourceAssertions
```

Note that the majority of non-inheriting assertion classes operates on primitive data types.
`ReferenceTypeAssertions` provides 14 assertion methods and most of them are not applicable to primitives.

My question is now, why would you want to know the type of an `DateTime?`.
Maybe the example is to simplistic for me to see the case, but a variable of type `DateTime?` naturally has type  `DateTime?`.

If your case is to verify the design of a data structure you could go meta and use the reflection based part of the Fluent Assertions API.

```cs
public class MyClass
{
    public DateTime? MyProperty { get; set; }
}

[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestMethod1()
    {
        typeof(MyClass).Should().HaveProperty<DateTime?>(nameof(MyClass.MyProperty));
    }
}
```

**Comment by ebewley** [comment]
My apologies for such a simple example, but security is extremely important where I am, and the minimum necessary illustration seemed sufficient.  Our data comes to us in different forms from external sources, so the actual tests are not so simple.  Also, we have multiple people working on different pieces, so comparing actual implementations against expected implementations is vital.  

For example, one dev may develop the class, another may develop the tests.  The issue may be related to using the incorrect type, or it may be related to an ambiguity in a user story/task.  Regardless, the issue needs to be addressed.

To reduce the likelihood of errors in tests, I often generate blocks of test code via scripts from metadata, table structures, etc.  It would be nice, if such basic assertions were available on all types, if only to simplify the code-gen scripts, but now that I know the documentation is incorrect on that point, I can code around it.  Thanks for explaining.

**Comment by jnyrup** [comment]
A workaround for you could be to cast `value` to `object` to get access to `BeOfType`.

Be aware that `BeOfType` assert on the exact *runtime* type.
```cs
DateTime? value = DateTime.Now;
value.As<object>().Should().BeOfType<DateTime?>();
```
fails with
```
Expected type to be System.Nullable`1[[System.DateTime, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], but found System.DateTime.
```

`BeAssignableTo` might be more useful here.
```
DateTime? value = DateTime.Now;
value.As<object>().Should().BeAssignableTo<DateTime?>();
```

**Comment by ebewley** [comment]
Thanks.  That's helpful.  I appreciate you taking the time to respond so quickly.
