### ISSUE TITLE
Use Case: How to check equivalence of 2 Option<T> instances (Optional library usage)

### ISSUE THREAD

**Issue by SuperJMN** [fluentassertions/fluentassertions#1387]
### Summary 

I'm using [**Optional**](https://github.com/nlkl/Optional), a library to allow C# work with a common abstraction of functional programming called "maybe", that is represented by its `Option<T>` type

### The problem
I can't test correctly whether 2 `Option<T>` instances are equivalent or not.
I'm not getting the desired results.

**The question is:**
How do I tell Fluent Assertions to check the equivalence correctly using the Option<T> type?

### Complete minimal example reproducing the issue
```cs
[Fact]
void TestOptional()
{
	var a = new[] { 1, 2, 3 }.Some();
	var b = new[] { 1, 3, 3 }.Some();
	
	a.Should().BeEquivalentTo(b);
}
```

[![Snapshot][1]][1]
As you see, this isn't what one expects. 

### Expected behavior:

The 2 instances should be equivalent.

### Actual behavior:

Test says the 2 instances aren't equivalent.

### Versions

* Which version of Fluent Assertions are you using? 5.10.3
* Which .NET runtime and version are you targeting? .NET Core 3.1

  [1]: https://i.stack.imgur.com/TUQ6X.png

**Comment by dennisdoomen** [comment]
Do you know if `Some` overrides `Equals`? If not, FA will compare its properties.

**Comment by jnyrup** [comment]
It does override Equals. 
This was answered in https://stackoverflow.com/a/63922414
