### ISSUE TITLE
ComparingByValue/Members for open generics

### ISSUE THREAD

**Issue by Cherepoc** [fluentassertions/fluentassertions#1392]
Hi, Is there any way I can setup a generic class/struct to be compared by value/members? I have a small type in F# that I decorate with a [<Struct>] attribute. I want it to be compared by membres though, because one of the member can be non-comparable, depending on the generic argument. How can I setup this type to be compared by members without listing any possible generic arguments? ComparingByMembers method does not seem to accept open generics.

**Comment by jnyrup** [comment]
Duplicate of #1023, #1387 and #1388
Implemented in #1389
Will be released with 6.0 (No current ETA)
