### ISSUE TITLE
How to use EquivalentTo inside custom IEquivalencyStep with parent EquivalencyAssertionOptions

### ISSUE THREAD

**Issue by MaxShoshin** [fluentassertions/fluentassertions#1393]
### Description

I'm try to implement custom equivalency step.

I'm try to use `BeEquivalentTo` method inside my custom step. I would like to pass equivalency settings specified in tests. 

I.e. when I write following test:
```csharp
value.Should().BeEquivalentTo(
    expectet, 
    opts => opts
        .Using(new CustomEquivalencyStep())
        .ComparingEnumsByName());
```
An inside my custom step I would like to CompareEnumsByName when I call `BeEquivalentTo`

Some part of my CustomEquivalencyStep:
```csharp
public bool Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config)
{
   ....
    context.Subject
                    .Should()
                    .BeEquivalentTo(
                        context.Expectation,
                        opts => GetSomehowOptionsFrom(config)); // ????
   ....
}
```

My question is how I can create `EquivalencyAssertionOptions<T>` with defaults from `config` parameter?

`EquivalencyAssertionOptions<T>` has internal constructor for this. Can we make it public? Or may be we have workaround for my case?

Thank you!

### Versions

* 5.9.0

**Comment by dennisdoomen** [comment]
Unfortunately that constructor is `internal`. We would not mind a PR to make it public.

**Comment by MaxShoshin** [comment]
Could you review #1397 ?
