### ISSUE TITLE
Add missing extensions for ThrowAsync

### ISSUE THREAD

**Issue by fbrosseau** [fluentassertions/fluentassertions#1400]
Hello, thanks for the great project!

This is identical to #1052 - Add `async`-support for `WithMessage()`
Which added an extension on the Task<..Assertion> itself for WithMessage

Can I submit a PR for the other 3 ExceptionAssertion methods, so that parentheses around the whole await expression are not required?

Namely,
-WithInnerException
-WithInnerExceptionExactly
-Where

**Comment by dennisdoomen** [comment]
By all means, go ahead.
