### ISSUE TITLE
Add a way to transform assertions to predicates

### ISSUE THREAD

**Issue by Fed03** [fluentassertions/fluentassertions#1402]
First and foremost, thank you for the awesome library!

I've a little request. Often, I wold like to use the fluentassertions powers in places where they could make sense.
The first example that comes to my mind is:
```C#
var collectionOfComplexTypes = ...;
collectionOfComplexTypes.Should().OnlyContain(x => x.DateProperty.Should().BeCloseTo(Datetime.Now))
```
Now, `OnlyContain` accepts a predicate but the assertions return void. The naive solution would be to wrap the assertion in a try/catch block and return the bool accordingly. A more natural way could be something like this
```C#
var collectionOfComplexTypes = ...;
collectionOfComplexTypes.Should().OnlyContain(x => x.DateProperty.Should().BeCloseTo(Datetime.Now).ToPredicate())
```
The second example where something like this could prove useful is when using argument matchers of the mock framework of your choice. Often the match is done with predicates, and being able to use the superpowers of fluentassertions could be a game changer

**Comment by dennisdoomen** [comment]
For some reason, I don't get what you are trying to say here. `OnlyContain` accepts a predicate that returns a `bool`, and I guess that `CloseTo` returns exactly that, right?

**Comment by Fed03** [comment]
> For some reason, I don't get what you are trying to say here. `OnlyContain` accepts a predicate that returns a `bool`, and I guess that `CloseTo` returns exactly that, right?

Sorry, it seems that `Should().Be` remained in my keyboard.... I edited the original post

**Comment by dennisdoomen** [comment]
Ah, now I understand. The only way to make that work is to have some static method that takes an `Action<T>` and wraps the invocation in an `AssertionScope` so you intercept the assertions before FA throws an exception. Something like this:

`AssertionHelper. ToPredicate(() => sub.DateProperty.Should().BeCloseTo(Datetime.Now));`

```csharp
public static bool ToPredicate(Action act)
{
  using (var scope = new AssertionScope())
  {
    act();
    return scope.Discard().Any();
  }
}
```

**Comment by jnyrup** [comment]
For the case with `OnlyContain` you could also use `AllBeEquivalentTo`

```cs
class ComplexType
{
    public int Value { get; set; }

    public DateTime DateProperty { get; set; }
}

[TestMethod]
public void MyTestMethod()
{
    var now = DateTime.Now;

    var complexTypes = new[]
    {
        new ComplexType { Value = 1, DateProperty = now.AddMilliseconds(10) },
        new ComplexType { Value = 2, DateProperty = now.AddMilliseconds(11) }
    };

    var expected = new
    {
        DateProperty = now
    };

    complexTypes.Should().AllBeEquivalentTo(expected, opt => opt
        .Using<DateTime>(ctx => ctx.Subject.Should().BeCloseTo(ctx.Expectation, TimeSpan.FromMilliseconds(20)))
        .WhenTypeIs<DateTime>());
}
```

**Comment by Fed03** [comment]
The `OnlyContain` is just an example. I'm looking for a way to transform any assertion to a predicate and, maybe, printing the output when false. I think the solution proposed by @dennisdoomen is a good start.
Moreover, It could make the entire fluentassertion framework more powerful, making possible to use all the assertions inside the ones that take predicates

**Comment by dennisdoomen** [comment]
To be honest, I don't really like that syntax myself, but that's more a limitation of the C# language. I'm in doubt whether this should become part of the library itself though.

**Comment by Fed03** [comment]
The `SatisfyRespectively` collection assertion accepts actions where you can use assertions. How is this made possible? In the same way you proposed before?

**Comment by dennisdoomen** [comment]
It acts on a collection. In other words, it's an extension method named `Should` that actions on an `IEnumerable<T>` or something like that. But internally it is doing exactly as I suggested `AssertionHelper.ToPredicate` should work.

**Comment by Fed03** [comment]
Many thanks @dennisdoomen! Maybe methods acting on collections should have an overload that wraps actions with the `AssertionHelper.ToPredicate`
 technique like `SatisfyRespectively` does. What do you think?

**Comment by dennisdoomen** [comment]
Sure, but that's quite some work. Unless somebody contributes that, I don't think it'll get a lot of priority right now.
