### ISSUE TITLE
Improve messages for numeric assertions to show the difference of the comparison

### ISSUE THREAD

**Issue by augustoproiete** [fluentassertions/fluentassertions#1412]
I'd like to discuss a possible improvement to the error messages on numeric assertions (_which I'm happy to take a stab and send a PR once a design is agreed_):

Given a test similar to this:

```csharp
var expectedResult = 832168464;
var actualResult = 832168447;

actualResult.Should().Be(expectedResult);
```

The error message currently would be:

```
Expected actualResult to be 832168464, but found 832168447.
```

This is great, but given we're comparing numbers, it would be more useful if the error message included the difference, instead of the developer having to calculate it separately from the error message. e.g.

```
Expected actualResult to be 832168464, but found 832168447. Difference: -17
```

The difference when comparing numeric values is usually a good clue when trying to understand why the test failed, and displaying it as part of the error message makes the experience better.

---

Is there a desire to have something like that implemented?

**Comment by dennisdoomen** [comment]
Sure, but it'll have to be done on all numeric assertions.

**Comment by augustoproiete** [comment]
My initial thinking is to make `NumericAssertions<T>` and `NullableNumericAssertions<T>` classes abstract and create individual concrete classes for each numeric primitive supported today (inheriting from `NA<T>` and `NNA<T>` respectively) so that we can perform a statically typed comparison without having to compile expressions or use reflection.

- `NumericAssertions<T>`
  - `ByteAssertions : NumericAssertions<byte>`
  - `DecimalAssertions : NumericAssertions<decimal>`
  - `DoubleAssertions : NumericAssertions<double>`
  - `FloatAssertions : NumericAssertions<float>`
  - `IntAssertions : NumericAssertions<int>`
  - `LongAssertions : NumericAssertions<long>`
  - `SByteAssertions : NumericAssertions<sbyte>`
  - `ShortAssertions : NumericAssertions<short>`
  - `UIntAssertions : NumericAssertions<int>`
  - `ULongAssertions : NumericAssertions<ulong>`
  - `UShortAssertions : NumericAssertions<ushot>`

- `NullableNumericAssertions<T>`
  - `NullableByteAssertions : NullableNumericAssertions<byte>`
  - `NullableDecimalAssertions : NullableNumericAssertions<decimal>`
  - `NullableDoubleAssertions : NullableNumericAssertions<double>`
  - `NullableFloatAssertions : NullableNumericAssertions<float>`
  - `NullableIntAssertions : NullableNumericAssertions<int>`
  - `NullableLongAssertions : NullableNumericAssertions<long>`
  - `NullableSByteAssertions : NullableNumericAssertions<sbyte>`
  - `NullableShortAssertions : NullableNumericAssertions<short>`
  - `NullableUIntAssertions : NullableNumericAssertions<int>`
  - `NullableULongAssertions : NullableNumericAssertions<ulong>`
  - `NullableUShortAssertions : NullableNumericAssertions<ushot>`

It's a little bit of work, but given we have a known and finite number of primitive types to target, I think would offer the best performance and not introduce any magic.

Thoughts?

**Comment by dennisdoomen** [comment]
I would suggest to spike it to see if you can make it work without too much new complexity.

**Comment by augustoproiete** [comment]
Great. You can assign this issue to men. I'll give it a go over the weekend.

**Comment by iliashkolyar** [comment]
@augustoproiete, you made some significant progress in your PR.
Do you mind if I pick up where you left off in order to add this helpful enhancement?

**Comment by augustoproiete** [comment]
@iliashkolyar Sure, go for it! 🚀

**Comment by iliashkolyar** [comment]
@augustoproiete thanks!
@dennisdoomen , would like me to open a new PR for this or should I continue in the original PR?

**Comment by dennisdoomen** [comment]
Since you'll be using a separate branch, you'll have to create a new PR anyway.
