### ISSUE TITLE
FluentActions.Invoking vs FluentActions.Awaiting

### ISSUE THREAD

**Issue by rizi** [fluentassertions/fluentassertions#1420]
Can someone tell me whats the difference between this two methods?
On the documentation page (https://fluentassertions.com/exceptions/) both are shown, but I can't find the difference.

I'm also not sure, do I have to await Invoking or Awaiting it seems that it's also working without the await.

Btw. I'm using MSTest v2.

```cs
[TestMethod]
public async Task TestMethod2()
{
   await FluentActions.Invoking(() => _testClass.TestMethodAsync()).Should().ThrowExactlyAsync<NotImplementedException>();
}
```

```cs
[TestMethod]
public async Task TestMethod3()
{
	await FluentActions.Awaiting(() => _testClass.TestMethodAsync()).Should().ThrowExactlyAsync<NotImplementedException>();
}
```

Br

**Comment by jnyrup** [comment]
> Can someone tell me whats the difference between this two methods?

`Invoking` is intended for synchronous methods while `Awaiting` is for asynchronous ones.
For a method return a `Task<T>` they can both be used, but I added `Awaiting` as well in #1051 for consistency.

> I'm also not sure, do I have to await Invoking or Awaiting it seems that it's also working without the await.

You do not need to `await` `Awaiting` (it returns a `Func` so it cannot be awaited), but you do need to `await` `ThrowExactlyAsync`, otherwise the test method could finish before `ThrowExactlyAsync` has finished.

**Comment by rizi** [comment]
> > Can someone tell me whats the difference between this two methods?
> 
> `Invoking` is intended for synchronous methods while `Awaiting` is for asynchronous ones.
> For a method return a `Task<T>` they can both be used, but I added `Awaiting` as well in #1051 for consistency.
> 
> > I'm also not sure, do I have to await Invoking or Awaiting it seems that it's also working without the await.
> 
> You do not need to `await` `Awaiting` (it returns a `Func` so it cannot be awaited), but you do need to `await` `ThrowExactlyAsync`, otherwise the test method could finish before `ThrowExactlyAsync` has finished.

Thx for the clarification (that makes sense) 

br.
