### ISSUE TITLE
Community namespace

### ISSUE THREAD

**Issue by Miista** [fluentassertions/fluentassertions#1430]
Is there a specific sub-namespace to use for community packages?

**Comment by dennisdoomen** [comment]
Not really, unless you want to join the [fluentassertions](https://github.com/fluentassertions) organization.

**Comment by Miista** [comment]
What would the benefit be for me? Aside from allowing me to publish a community package?

**Comment by dennisdoomen** [comment]
It would show up on Nuget under the `fluentassertions` organization. We don't really have any specific rules or guidelines for that.

**Comment by Miista** [comment]
Sorry for leaving you hanging.

I don't see a reason not to join the `fluentassertions` organization.
How would I go about joining it?

That said, the namespace I had in mind for the package seems to have been taken already.

**Comment by dennisdoomen** [comment]
What package name did you have in mind?

**Comment by Miista** [comment]
`FluentAssertions.Optional` was the package name I had in mind.

**Comment by dennisdoomen** [comment]
And the existing one on NuGet is not yours I presume?

**Comment by Miista** [comment]
That is correct.

**Comment by dennisdoomen** [comment]
Then you have no choice to come up with something new ;-)
