### ISSUE TITLE
Unexpected behavior with IEnumerable and exceptions

### ISSUE THREAD

**Issue by mu88** [fluentassertions/fluentassertions#1431]
### Description

When calling `.Should().Throw()` on a method that uses LINQ and returns an `IEnumerable`, the enumeration won't get executed. This can hide exceptions that occur within a LINQ statement.

### Complete minimal example reproducing the issue

The following code needs MSTest. It is a rather simple example of some code I have in front of me, but hopefully, the problem gets clear: I have to call `.ToList()` to actually execute the enumeration and get the expected error.

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using FluentAssertions;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace UnitTestProject1
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void ThisShouldThrow()
        {
            var testee = new Example();

            testee.Invoking(x => x.DoSomething()).Should().Throw<InvalidOperationException>();
        }

        [TestMethod]
        public void ThisThrows()
        {
            var testee = new Example();

            testee.Invoking(x => x.DoSomething().ToList()).Should().Throw<InvalidOperationException>();
        }
    }

    public class Example
    {
        public IEnumerable<int> DoSomething()
        {
            var range = Enumerable.Range(0, 10);

            return range.Select(Twice);
        }

        private int Twice(int arg)
        {
            if (arg == 5)
            {
                throw new InvalidOperationException();
            }

            return 2 * arg;
        }
    }
}
```

### Expected behavior:

I would expect that all exception handling methods (e. g. `Throw()`, `NotThrow()`, etc.) actually enumerate the underlying collection (e. g. by calling `.ToList()`). Otherwise this could lead to False Negatives.

### Actual behavior:

The enumeration has to be done manually. If it gets forgotten, exceptions will be swallowed.

### Versions

* Which version of Fluent Assertions are you using? 5.10.3
* Which .NET runtime and version are you targeting? .NET Framework 4.8

**Comment by jnyrup** [comment]
To force enumeration you can use `Enumerating()`

```cs
// Arrange
var testee = new Example();

// Act
Func<IEnumerable<int>> act = testee.DoSomething();

// Assert
act.Enumerating().Should().Throw<InvalidOperationException>();
```

We don't currently have an overload of `Enumerating`, that allows you to write
```
testee.Enumerating(x => x.DoSomething()).Should().Throw<InvalidOperationException>();
```

but we're open for a PR adding
```cs
public static Action Enumerating<T, TResult>(this T subject, Func<T, IEnumerable<TResult>> enumerable)
```

**Comment by mu88** [comment]
So from your perspective, enumerating should not be part of `Throw()`? This feels a bit strange... maybe you can give me an explanation why `ThisShouldThrow()` (see my example) behaves correctly from your point? Or can you please give me an example when it is beneficial that I have to do the enumeration on my own?

**Comment by jnyrup** [comment]
Yes, from our perspective `Throw` should not try to enumerate an `IEnumerable`.
`ThisShouldThrow` works as "expected" as `DoSomething` returns an `IEnumerable` and `IEnumerables` are lazure per nature.
That's how `GenerateAMillionNumbers().First()` does not need to enumerate all one million numbers, but can stop once it has generated the first number.

Here's a case where you don't want Fluent Assertions to force enumeration of an `IEnumerable`.

```cs
public class MyClass
{
    public IEnumerable<int> GetInfiniteNumbers(bool fail)
    {
        if (fail)
            throw new ArgumentException("you told me to fail", nameof(fail));

        return GetInfiniteNumbers();
    }

    private IEnumerable<int> GetInfiniteNumbers()
    {
        int i = 0;
        while (true)
        {
            yield return i++;
        }
    }
}

[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestValidationPart_Failure()
    {
        // Arrange
        var subject = new MyClass();

        // Act
        Func<IEnumerable<int>> act = () => subject.GetInfiniteNumbers(fail: true);

        // Assert
        act.Should().Throw<ArgumentException>();
    }

    [TestMethod]
    public void TestValidationPart_Success()
    {
        // Arrange
        var subject = new MyClass();

        // Act
        Func<IEnumerable<int>> act = () => subject.GetInfiniteNumbers(fail: false);

        // Assert
        act.Should().NotThrow<ArgumentException>();
    }
}
```

**Comment by mu88** [comment]
Thanks for your explanation! That's perfectly fine for me - I like your clear API philosophy 🙂

If it's okay for you, you can assign this issue to me and I go for this PR.

**Comment by jnyrup** [comment]
@mu88 You've got it.
