### ISSUE TITLE
Request: Implement BeCloseTo for decimal/double/float

### ISSUE THREAD

**Issue by bart-degreed** [fluentassertions/fluentassertions#1439]
It works for natural numbers like int/short/long and DateTime/DateTimeOffset, but it is not provided for decimal/double/float types.

```c#
DateTimeOffset releasedAt = DateTime.UtcNow;
decimal lengthInSeconds = 123M;

// ...

trackInDatabase.ReleasedAt.Should().BeCloseTo(releasedAt);
trackInDatabase.LengthInSeconds.Should().BeCloseTo(lengthInSeconds); // compile error: BeCloseTo is not available for decimal
```

The reason I'm asking is due to roundtrip to database, a bit of precision is lost. I've written the next extension to fill the gap:

```c#
public static class ObjectAssertionsExtensions
{
    public static void BeCloseTo(this NumericAssertions<decimal> source, decimal expected, string because = "",
        params object[] becauseArgs)
    {
        var value = (decimal) source.Subject;
        value.Should().Match(x => Math.Abs(x - expected) < 0.00000000001M, because, becauseArgs);
    }
}
```

When considering to add this, please also consider to add for their nullable counterparts: decimal?, double? and float?.

### Versions

* Which version of Fluent Assertions are you using? v5.10.3
* Which .NET runtime and version are you targeting? .NET Core 3.1.

**Comment by jnyrup** [comment]
For `NumericAssertions<T>` where `T` is one of {`double`, `float`, `decimal`}  you can use `BeApproximately`.
![image](https://user-images.githubusercontent.com/919634/100338831-62fba600-2fd9-11eb-90c6-59fc3f70e2de.png)

Does that answer your question?

**Comment by bart-degreed** [comment]
Yes, that's exactly what I was looking for. Thanks!
