### ISSUE TITLE
.HaveFlag() fails for HttpStatusCode 4xx

### ISSUE THREAD

**Issue by DaGrisa** [fluentassertions/fluentassertions#1441]
### Description

Check of `HttpStatusCode` with `.HaveFlag()` fails for all 4xx status codes when comparing to `HttpStatusCode.BadRequest` (=400).

### Complete minimal example reproducing the issue

```csharp
[Test]
public async Task FluentAssertionBug_HaveFlag()
{
    // Arrange
    var badRequest = HttpStatusCode.BadRequest;
    var methodNotAllowed = HttpStatusCode.MethodNotAllowed;

    // Assert
    using (new AssertionScope())
    {
        methodNotAllowed.Should().HaveFlag(badRequest, "equals with .HaveFlag(...)");
        methodNotAllowed.Should().Be(badRequest, "equals with .Be(...)");
    }
}
```

### Expected behavior:

First assertion should also fail, like the second one using `.Be(...)`.

### Actual behavior:

Only second assertion fails using `.Be(...)`.

### Versions

5.10.3 on .NET Core 3.1

**Comment by dennisdoomen** [comment]
Why should it fail? Because `HttpStatusCode` is not a Flags enum?

**Comment by jnyrup** [comment]
This is due to how `Enum.HasFlag` works.

`x.HasFlag(y)` can be implemented as
```cs
(x & y) == y
```

```
MethodNotAllowed = 405 = 0b110010101
BadRequest       = 400 = 0b110010000


  0b110010101 405
& 0b110010000 400
  -----------
= 0b110010000 400
```

**Comment by jnyrup** [comment]
From the documentation of [`HasFlag`](https://docs.microsoft.com/en-us/dotnet/api/system.enum.hasflag?view=net-5.0#remarks)
> The `HasFlag` method is designed to be used with enumeration types that are marked with the `FlagsAttribute` attribute and can be used to determine whether multiple bit fields are set. For enumeration types that are not marked with the `FlagsAttribute` attribute, call either the `Equals` method or the `CompareTo` method.

`Be` and `HaveFlag` are working as expected.

* Use `HaveFlag` for enums that are decorated with `Flags` or behaves as flags.
* Use `Be` to assert equality.
