### ISSUE TITLE
BeEquivalentTo with Excluding does not work for structs

### ISSUE THREAD

**Issue by skymindapps** [fluentassertions/fluentassertions#1444]
### Description

When using Should().BeEquivalentTo with options.Excluding on a struct it does not seem to exclude.
The exact same code executed on a class works as expected.

### Complete minimal example reproducing the issue

```csharp
class Foo
{
    public int A;
    public int B;
}
struct Bar
{
    public int A;
    public int B;
}

// This succeeds
Foo fooExpected = new Foo { A = 1, B = 2 };
Foo fooActual = new Foo { A = 1, B = 3 };
fooActual.Should().BeEquivalentTo(fooExpected, options => options.Excluding(x => x.B));

// This fails
Bar barExpected = new Bar { A = 1, B = 2 };
Bar barActual = new Bar { A = 1, B = 3 };
barActual.Should().BeEquivalentTo(barExpected, options => options.Excluding(x => x.B));
```

### Expected behavior:

I would expect the assertion on barActual to succeed, since I am specifically excluding the field that has a different value (B).

### Actual behavior:

The assertion of barActual fails with the following message, indicating that is does in fact NOT exclude the field B:
```
  Message: 
    Expected barActual to be 
    
    Tests.Bar
    {
       A = 1
       B = 2
    }, but found 
    
    Tests.Bar
    {
       A = 1
       B = 3
    }.
    
    With configuration:
    - Use declared types and members
    - Compare enums by value
    - Exclude member root.B
    - Match member by name (or throw)
    - Without automatic conversion.
    - Be strict about the order of items in byte arrays
    
  Stack Trace: 
    XUnit2TestFramework.Throw(String message)
    TestFrameworkProvider.Throw(String message)
    CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
    EquivalencyValidator.AssertEquality(EquivalencyValidationContext context)
    ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs)
    Tests.TestFooAndBar() line 75
```
### Versions

Reproduced on .NET Core 3.1 with Fluent Assertions v5.10.3

**Comment by dennisdoomen** [comment]
The reason for this is that a `struct` is a value type and that by default, FA will rely on the default implementation of `Equals` of a `struct`, which does a member-wide comparison outside control of FA.

**Comment by skymindapps** [comment]
Thank you for the reference.

Changing the Bar/struct assertion to the following (adding the ComparingByMemners) makes it work:
```
barActual.Should().BeEquivalentTo(barExpected, options => options.Excluding(x => x.B).ComparingByMembers<Bar>());
```
