### ISSUE TITLE
.NET 5 support

### ISSUE THREAD

**Issue by ezekiell** [fluentassertions/fluentassertions#1445]
### Description

It would be great to add .NET 5 support! :-)

**Comment by jnyrup** [comment]
The current stable version of Fluent Assertions has plenty of target frameworks that .NET 5 should be able to consume.
In the upcoming Fluent Assertions 6.0.0, we plan to add .NET Core 3 support.

Before we just add yet another target, I'm curious what in .NET 5 you're missing?

**Comment by ezekiell** [comment]
Sorry my mistake I tried to add nuget into .NET 5 test project and it didn't work so I thought it's not supported. I was able to add it today.. Problem on my site. Thanks, closing.. Btw great package ;-)

**Comment by dennisdoomen** [comment]
No worries. Happy to hear that.
