### ISSUE TITLE
Variable name is incorrect inside AssertionScope on fail

### ISSUE THREAD

**Issue by shatulsky** [fluentassertions/fluentassertions#1447]
### Description

I have a few big `AssertionScope` with loops to compare different DTO without mappings. When executing tests on release mode - variable names on the fail assertion exception message are incorrect.

### Complete minimal example reproducing the issue

I cant provide a whole code example, but here is an example that can help to get the problem

E.g.

```csharp
using (new AssertionScope())
{
	// Verify request fields
	requestFromDatabase.CampaignId.Should().Be(usedCampaign.CampaignId);
	requestFromDatabase.CorrelationToken.Should().Be(requestToCreate.CorrelationToken);
	requestFromDatabase.InsertDT.UtcDateTime.Should().BeCloseTo(createResponse.CreationTime, 1.Minutes());
	string author = ServiceProvider.Get<IConfiguration>().GetSectionValue("CreatedById");
	requestFromDatabase.InsertBy.Should().Be(author);
	requestFromDatabase.RequestStatusId.Should().NotBeNullOrEmpty();

	// Verify request address fields
	IEnumerable<RequestAddressDatabaseModel> requestAddress = ServiceProvider
		.Get<RequestAddressDatabaseController>()
		.GetRequestAddressByRequestId(requestId);
	foreach (RequestAddressDatabaseModel databaseAddressModel in requestAddress)
	{
		AddressApiModel addressToCreate =
			requestToCreate.Addresses.First(
				a => a.CorrelationToken == databaseAddressModel.CorrelationToken);

		string timeZoneId = GetTimeZoneDatabaseId(addressToCreate.TimeZone);
		databaseAddressModel.TimeZone.Should().Be(timeZoneId);
		databaseAddressModel.InsertBy.Should().Be(author);
```

### Expected behavior:
The error message is:
Expected databaseAddressModel.**TimeZone** to be
"US/Eastern", but
"us/eastern" differs near "us/" (index 0).

### Actual behavior:
The error message is:
Expected databaseAddressModel.**InsertBy** to be
"US/Eastern", but
"us/eastern" differs near "us/" (index 0).

The problem represents only in Release compile mode. In debug compile mode it works as expected.

### Versions

* Which version of Fluent Assertions are you using? - 5.10.3
* Which .NET runtime and version are you targeting? net core 3.1

**Comment by jnyrup** [comment]
Subject Identification is not reliable in release mode.
For the upcoming 6.0.0 release we've tried to increase the accuracy.

> The way this works is that Fluent Assertions will try to traverse the current stack trace to find the line and column numbers as well as the full path to the source file. Since it needs the debug symbols for that, this will require you to compile the unit tests in debug mode, even on your build servers. Also, since only .NET Standard 2.0 and the full .NET Framework support getting direct access to the current stack trace, subject identification only works for the platforms targeting those frameworks.

https://fluentassertions.com/introduction#subject-identification
