### ISSUE TITLE
Detailed message for graph comparison of C# 9 records

### ISSUE THREAD

**Issue by Cherepoc** [fluentassertions/fluentassertions#1451]
Hi!
When used with regular classes, comparing two different objects yields a message detailing what exactly is different, like in my case:
```
Expected member WorkingHoursJson to be <null>, but found 
"[{"dayOfWeek": "friday", "latestTime": 120, "earliestTime": 60}]"
```
When I make that class a record, those details are lost, and both objects are just dumped into message:
`Expected createdBusiness to be BusinessDto { Id = 1, Name = Halvorson - Orn, CreatedAt = 12.09.2020 13:47:54, UpdatedAt = 12.09.2020 13:47:54, EnableA...`
...and so on. Is there a way to get detailed messages for records?
Thanks!

EDIT: found ComparingByMembers option, this solves the problem. But I think it would be better to compare records by members by default.

**Comment by dennisdoomen** [comment]
A `record` in C# 9 has value semantics and FA honors that, just like it treats `struct`s. So I think the current behavior is correct.

**Comment by Cherepoc** [comment]
I think tuples are meant to be value-like too, but they are still compared by properties. Can there at least be an option to manually override this behaviour and set all records to be compared by properties?
Thanks!

**Comment by rizi** [comment]
> > I think tuples are meant to be value-like too, but they are still compared by properties.
> 
> Tuples is a value type as far as FA is concerned, but tuples have a (generated) implementation of `Equals` that compares the properties.
> 
> > Can there at least be an option to manually override this behaviour and set all records to be compared by properties?
> 
> You can always use `ComparingByMembers<T>()`

Is there a way to make ComparingByMembers default for C# records, if so how can this be done? --> do it manually for each assert when a record is involved is not the best way ;)

**Comment by Cherepoc** [comment]
> but tuples have a (generated) implementation of `Equals` that compares the properties

That is correct, but:
- Records have the same generated equality checks
- When comparing object graphs the equality behavior for tuples is overriden to use structural equality instead of generated equality implementation. It is explicitly mentioned in the docs.

I've made a fiddle to better demonstrate the differences between value and structural equality, tuples and records, here it is:
https://dotnetfiddle.net/k609MZ

**Comment by rizi** [comment]
@dennisdoomen: The following change will work, I just tried it with the latest code from GitHub:

Extend HasValueSemantics(this ...) method in https://github.com/fluentassertions/fluentassertions/blob/c882c22c20622e1e7741945197a919356fc38f66/Src/FluentAssertions/Common/TypeExtensions.cs to take records into account like so:

```
public static bool HasValueSemantics(this.....)
{
          return 
                   type.OverridesEquals()
                   && !type.IsAnonymousType() 
                   && !type.IsTuple() 
                   && !IsKeyValuePair(type)
                   && !type.IsRecord();
}

private static bool IsRecord(this Type type)
{
            Type iEquatableMemberInfo = type.GetInterface("IEquatable`1");

            return
                ((TypeInfo)type).DeclaredProperties.FirstOrDefault(property => property.Name == "EqualityContract")?.GetMethod?.GetCustomAttribute(typeof(CompilerGeneratedAttribute)) != null
                && type.GetMethod("<Clone>$") != null
                && iEquatableMemberInfo?.GetGenericArguments().Single() == type;
 }
```

It also does not break any existing tests, so I think it should be safe to do it.

What do you think?

**Comment by dennisdoomen** [comment]
The problem is that I don't think we should treat records differently from structs.

**Comment by rizi** [comment]
> The problem is that I don't think we should treat records differently from structs.

But how does it make sense to compare Collections within records by reference,  this will more or less never be what you want to assert, so BeEquivalent will most of the time throw an exception, except you use ComparingByMembers.

Do you have a use case where comparing collections by reference makes sense?

Br

**Comment by Cherepoc** [comment]
Judging by the project I work in, records are used differently then structs. They are either used as local helpers (and are not compared in tests), or as Dtos, and that's one of the reasons why they were created, as far as I know. We just replace old dto classes with records now, because of non-destructable mutations. Many of those dto classes are serialized to json and have collections, and are checked in tests for equality.
Structs are used in our project primarily to represent some special for of data - DateTime, coordinates, etc. It makes sense to compare them by values, because they might have a very special way to compare the data and we can't know that just by looking at the properties. But that is not the case with records, they are quite the same as tuples in that regard. They are structs too, yet they are not regarded as such for assertions. What makes records different?
Anyway, that is just a perspective of a person with experience of using records in just one project. I don't pretend to be right here.
Thanks!

**Comment by jtleaming** [comment]
I have a similar experience with testing records. I started using records to create immutable entities in my code, and doing this broke previous tests where I needed to exclude particular properties (code generated guids). I agree these shouldn't be treated the same as structs, as they are conceptually different from structs.

**Comment by christophpre** [comment]
I think most aspects of this problem have already been discussed, but I wanted to add my 2 cents. We have the same problem with FluentAssertions and migrating Dtos from classes to records in two new projects. Using BeEquivalent with the current semantics breaks many of our tests. Therefore, I also think that records should not be treated the same as structs in this regard.

**Comment by baratgabor** [comment]
I also ran into a related problem, which was compounded by how the failure message seemed to 'treat the objects as strings'. I think this can be particularly confusing for people new to FA, who happen to use the new record types in their projects.

I literally thought that FA tries to compare the string representations of the two objects.

Here is my question on SO:
https://stackoverflow.com/questions/66007426/fluentassertions-should-beequivalentto-fails-in-trivial-case-when-types-are

**Comment by InspiringCode** [comment]
Meanwhile you can use this workaround to use ComparingByMembers for ALL record types:
```CSharp
        static TestBase() {
            AssertionOptions.EquivalencySteps.Insert<RecordEquivalencyStep>();
        }

        private class RecordEquivalencyStep : IEquivalencyStep {
            private readonly StructuralEqualityEquivalencyStep _structuralStep = new StructuralEqualityEquivalencyStep();

            public bool CanHandle(IEquivalencyValidationContext context, IEquivalencyAssertionOptions config) => 
                context.Expectation != null &&
                IsRecord(context.RuntimeType) && 
                _structuralStep.CanHandle(context, config);

            public bool Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config)
                => _structuralStep.Handle(context, parent, config);

            private static bool IsRecord(Type type) =>
                type.GetMethod("<Clone>$") != null &&
                type.GetTypeInfo()
                    .DeclaredProperties
                    .FirstOrDefault(p => p.Name == "EqualityContract")?
                    .GetMethod?
                    .GetCustomAttribute(typeof(CompilerGeneratedAttribute)) != null;
        }
```

**Comment by 304NotModified** [comment]
@InspiringCode thanks for the work around!

Unfortunately, after this I get sometimes a " Collection was modified; enumeration operation may not execute." exception :'(

Any idea why?

```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.

at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
at FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(IEquivalencyValidationContext context)
at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context)
at FluentAssertions.Equivalency.StructuralEqualityEquivalencyStep.Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config)
at FluentAssertions.Equivalency.EquivalencyValidator.RunStepsUntilEquivalencyIsProven(IEquivalencyValidationContext context)
at FluentAssertions.Equivalency.EquivalencyValidator.AssertEqualityUsing(IEquivalencyValidationContext context)
at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context)
at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs)
at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, String because, Object[] becauseArgs)
```

**Comment by dennisdoomen** [comment]
> Unfortunately, after this I get sometimes a " Collection was modified; enumeration operation may not execute." exception :'(

That's because test frameworks are lazy-loaded. So somewhere inside the intricacies of `BeEquivalentTo`, you're modifying the global settings. It's probably better to use some of the global initialization techniques that xUnit offers or use the workaround that [was proposed earlier](https://github.com/fluentassertions/fluentassertions/issues/1451#issuecomment-784386165).
