### ISSUE TITLE
Idea for new collection assertion

### ISSUE THREAD

**Issue by vanya-lebedev** [fluentassertions/fluentassertions#1480]
Hello, fluentassertions community, 

I would like to propose a new overload of the BeEquivalentTo method for collection assertions. Here's an example:

```C#
plannedOrders.Should().BeEquivalentTo(
    order => order.Type == OrderType.Purchase && order.Quantity == 5 && order.Date == tomorrow,
    order => order.Type == OrderType.Transfer && order.SourceLocation == distributionCenter && order.Quantity == 3 && order.Date == today,
    order => order.Type == OrderType.Transfer && order.SourceLocation == factory && order.Quantity == 5 && order.Date == today.AddDays(10)
);

```
Basically, the API should be similar to the existing collection.Should().BeEquivalentTo() API but instead of providing a collection of elements as input we would instead provide a collection of predicates that elements of the collection must match. Assertion should pass if it is possible to have a 1-1 mapping between elements of the collection and the predicates.

The proposed API is useful in scenarios when the collection has elements with many properties but only few of these are insteresting in the scope of a given test scenario.

Could you please let me know if there is interest in the community in this feature? I would be happy to contribute.

Best regards,
Vanya

**Comment by jnyrup** [comment]
Hi Vanya.

This sounds like the existing `SatisfyRespectively` method.

Here is the example from our [documentation](https://fluentassertions.com/collections/).

```cs
var collection = new []
{
    new { Id = 1, Name = "John", Attributes = new string[] { } },
    new { Id = 2, Name = "Jane", Attributes = new string[] {"attr"} }
};
collection.Should().SatisfyRespectively(
    first =>
    {
        first.Id.Should().Be(1);
        first.Name.Should().StartWith("J");
        first.Attributes.Should().NotBeNull();
    },
    second =>
    {
        second.Id.Should().Be(2);
        second.Name.Should().EndWith("e");
        second.Attributes.Should().NotBeEmpty();
    });
```

A difference between `SatisfyRespectively` and what I understand from your proposal, it that `SatisfyRespectively` requires the subject and list of predicates to be in the same order, while `BeEquivalentTo` per default allows unordered 1:1 equivalency mappings.

You mention the desire for the proposed extension of `BeEquivalentTo` is because your element type has many properties, but only a small subset is relevant for the test.
Another way you might archive what you're seeking might be to use anonymous objects, as the expectation type decides what properties to compare.

```cs
var expected = new[]
{
    new { Type = OrderType.Purchase, Quantity = 5, Date = tomorrow },
    new { Type = OrderType.Transfer, SourceLocation = distributionCenter, Quantity = 3, Date = today },
    new { Type = Transfer, SourceLocation = factory, Quantity == 5, Date = today.AddDays(10) }
};

plannedOrders.Should().BeEquivalentTo(expected);
```

**Comment by vanya-lebedev** [comment]
Thanks a lot for the quick reply, Jonas! 

The option with SatisfyRespectively has a couple of downsides: 
- Comparison is sensitive to the order of elements in the collection
- It is also significantly more verbose than the proposed option. 

The option with anonymous types covers a lot of use cases. A couple of downsides with it: 
- If the type of the objects in the collection is refactored (e.g. property name is changed) then tests need to be changed manually. 
- If one of the conditions in the predicate is more complex than equality then it cannot be used.

**Comment by jnyrup** [comment]
I can only agree on your analysis.

I'm not sure if `BeEquivalentTo` is the best method to overload, as I would say that an item is not equivalent to a predicate, but matches or satisfies it.
This is just my immediate gut feeling, which isn't necessarily right, but just that I'm not (yet) convinced. Sometimes a proposed API just needs a bit of time to sink in.
On the other hand we already have `Contain(Expression<Func<T, bool>> predicate)`.

The verbosity of `SatisfyRespectively` is to provide more detailed failure messages.
An example from the tests:
```cs
public void When_asserting_collection_does_not_satisfy_any_inspector_it_should_throw()
{
    // Arrange
    var customers = new[]
    {
        new CustomerWithItems { Age = 21, Items = new[] { 1, 2 } },
        new CustomerWithItems { Age = 22, Items = new[] { 3 } }
    };

    // Act
    Action act = () => customers.Should().SatisfyRespectively(
        new Action<CustomerWithItems>[]
        {
            customer =>
            {
                customer.Age.Should().BeLessThan(21);
                customer.Items.Should().SatisfyRespectively(
                    item => item.Should().Be(2),
                    item => item.Should().Be(1));
            },
            customer =>
            {
                customer.Age.Should().BeLessThan(22);
                customer.Items.Should().SatisfyRespectively(item => item.Should().Be(2));
            }
        }, "because we want to test {0}", "nested assertions");

    // Assert
    act.Should().Throw<XunitException>().WithMessage(
@"Expected customers to satisfy all inspectors because we want to test nested assertions, but some inspectors are not satisfied:
*At index 0:
*Expected customer.Age to be less than 21, but found 21
*Expected customer.Items to satisfy all inspectors, but some inspectors are not satisfied:
*At index 0:
*Expected item to be 2, but found 1
*At index 1:
*Expected item to be 1, but found 2
*At index 1:
*Expected customer.Age to be less than 22, but found 22
*Expected customer.Items to satisfy all inspectors, but some inspectors are not satisfied:
*At index 0:
*Expected item to be 2, but found 3"
);
}
```

**Comment by vanya-lebedev** [comment]
- Regarding the naming of the method to expose the proposed API - we can try different options. E.g. Should().OnlyContain() could be an alternative?
- Regarding providing nice looking failure messages. In our project we actually have implemented parsing of predicate expression trees and managed to cover majority of the mainline cases. Here's an example of a failure message that our custom implementation provides:

```
Expected result:
Quantity: 123, RequestedIssueTime: 04 Feb 2021, RequiredIssueTime: 04 Feb 2021, PlannedIssueTime: 04 Feb 2021
    
Actual result:
Quantity: 1, RequestedIssueTime: 04 Feb 2021, RequiredIssueTime: 04 Feb 2021, PlannedIssueTime: 04 Feb 2021

```

**Comment by dennisdoomen** [comment]
Honestly I don't see too much value in this API. It feels too niche to be worth the significant development costs I see for this.

**Comment by vanya-lebedev** [comment]
Oh, well. You're the owner of the project, Dennis :) your decision. For development costs, as I mentioned, I would be happy to develop the solution. But I realize that design and code reviews is a burden that would fall on the community...

**Comment by dennisdoomen** [comment]
@jnyrup what's your take on this?

**Comment by jnyrup** [comment]
If we forget about equivalency, it _might_ be able to fit in nicely next to 
`Contain(Expression<Func<T, bool>> predicate)`

`OnlyContain(IEnumerable<Expression<Func<T, bool>>> predicates)`
`ContainExactly(IEnumerable<Expression<Func<T, bool>>> predicates)`

I think it could be as "simple" as
```
if predicates.Count != Subject.Count
	fail

foreach permutation in permutation(predicates)
{
	success = zip(permutation, Subject).All((predicate, item) => predicate(item));

	if (success)
		return // we found a match
}

fail // we didn't find match
```

It has a terrible computational complexity of N!*N, but I guess people would use this assertion with a rather low N.

(Otherwise there's probably someone out there who can recall their CS curriculum)

**Comment by dennisdoomen** [comment]
Indeed. In that case, if @vanya-lebedev is up to it, having an overload to `SelfReferencingCollectionAssertions.Contains` may work.

**Comment by vanya-lebedev** [comment]
Perfect! Thanks a lot for your support!

**Comment by vanya-lebedev** [comment]
I have created a pull request with the suggested implementation. Looking forward to your comments. 
https://github.com/fluentassertions/fluentassertions/pull/1500
