### ISSUE TITLE
Rebuild documentation pages

### ISSUE THREAD

**Issue by GeeWee** [fluentassertions/fluentassertions#1484]
### Description

When debugging a FluentAssertions issue (#1323) and a PR for the documentation update that solves it (#1334), I realized that the documentation update hasn't made it into the main fluentassertions.com website.

The page I am talking about is the tips page ([Github develop branch link](https://github.com/fluentassertions/fluentassertions/blob/develop/docs/_pages/tips.md), [Github master branch link](https://github.com/fluentassertions/fluentassertions/blob/master/docs/_pages/tips.md), [FluentAssertions main page link](https://fluentassertions.com/tips/)

It seems like the changes have only made their way into the develop branch, which is not reflected on the website.

Is there a chance we can rebuild the documentation, or pull this change into master so that the new docs can be seen on the website?

**Comment by dennisdoomen** [comment]
We would have to cherry-pick that change into the `master` branch. If you're in a hurry, you could provide us with a PR to do that. We'll take care of upmerging those changes to `develop`.

**Comment by GeeWee** [comment]
Is there a cadence in which develop is released to master, or is that just when 6.0 drops?

I'm not in a hurry seeing as I already found the documentation, I was mostly just worried that the change had gotten "lost" somewhere and would never make it to live :)

**Comment by dennisdoomen** [comment]
No, usually we don't have a `develop` branch, unless we're introducing lots of breaking changes. So we can't promise anything about 6.0.

**Comment by GeeWee** [comment]
Fair enough - let's just consider the issue closed and hope not too many people stumble upon it. Thanks for your time !

**Comment by dennisdoomen** [comment]
Thank you for reaching out to us.
