### ISSUE TITLE
`AllBeEquivalentTo` works on enums but not on strings

### ISSUE THREAD

**Issue by kbilsted** [fluentassertions/fluentassertions#1487]
### Description

`AllBeEquivalentTo` works on enums but not on strings. This is very inconvenient

### Complete minimal example reproducing the issue

E.g. testing the `State` property of a collection of objects all have the same enum value I can write

```cs
someCollection.Select(x => x.State)
    .Should()
    .AllBeEquivalentTo(StateEnum.Inactive);
```

Changing field `State` from `StateEnum` to `string` I had to rewrite my asserts to

```cs
someCollection.Select(x => x.State)
    .Distinct()  
    .Should()
    .BeEquivalentTo("Inactive");
```

which is less elegant than using `AllBeEquivalentTo`

### Expected behavior:

be able to use `AllBeEquivalentTo` with strings

### Actual behavior:

compiler error

### Versions

* Which version of Fluent Assertions are you using?
5.10.3

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.1.
core 3.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jnyrup** [comment]
With 6.0.0-alpha1 you can use
```cs
someCollection.Select(x => x.State)
    .Should()
    .AllBe("Inactive")
```

If you need case-insensitive comparison it would be
```
someCollection.Select(x => x.State)
    .Should()
    .AllBe("Inactive", opt => opt
        .Using<string>(ctx => ctx.Subject.Should().BeEquivalentTo(ctx.Expectation))
        .WhenTypeIs<string>());
```
See #1263 for the discussion about this new overload and why it's not named `AllBeEquivalenTo`.


With 5.10.3 you can use an anonymous object to only take the `State` property into consideration.
```cs
var expected = new
{
    State = "Inactive"
};

someCollection.Should()
    .AllBeEquivalentTo(expected);
```

**Comment by kbilsted** [comment]
thanks

**Comment by lonix1** [comment]
@jnyrup I also need `AllBe()`, but am reluctant to use an alpha version.

Does v6 have breaking changes?

**Comment by jnyrup** [comment]
@Ionix1 Yes, v6 has breaking changes.
We have just released beta2, so the amount of changes from now should be very minimal.

Here are some of the changes we expect to be most visible.
https://github.com/fluentassertions/fluentassertions/blob/release-6.0/docs/_pages/upgradingtov6.md

Here is a complete list of changes since v5.
https://github.com/fluentassertions/fluentassertions/blob/release-6.0/docs/_pages/releases.md

**Comment by lonix1** [comment]
Wow that is very organized, congratulations!

I see that v6 has been in the works for over a year - when do you expect the final will be released?

**Comment by dennisdoomen** [comment]
> I see that v6 has been in the works for over a year - when do you expect the final will be released?

Very soon. I'm trying to fix the last bugs and have already prepared a blog post.
