### ISSUE TITLE
Unexpected behaviour of NotBeNullOrEmpty with nullable reference

### ISSUE THREAD

**Issue by anton-makarevich** [fluentassertions/fluentassertions#1491]
### Description

BeNullOrEmpty doesn't fail test when object is null 

### Complete minimal example reproducing the issue

```csharp
    class TestClass
    {
        public string? NullString { get; }
    }

    public class UnitTest1
    {
        [Fact]
        public void ThisTestShouldFail()
        {
            TestClass sut = null;

            sut?.NullString.Should().NotBeNullOrEmpty();
        }
    }
```

### Expected behavior:

sut?.NullString is null as sut is null so test should fail

### Actual behavior:

test passes

### Versions

* net5.0, C#8+ with null reference types on, FA 5.10.3 (nuget)

### Additional Information

Not sure if this is a bug, but at least it's not what I would expect

**Comment by jnyrup** [comment]
The unexpected outcome is because you're using `?.`. 
The invocation is short-circuited before it gets to `BeNullOrEmpty`. 

To get the expected behavior, you can use `(sut?.Null String).Should().BeNullOrEmpty()`

**Comment by anton-makarevich** [comment]
yep, this works. still it's a bit weird to me as in a real life example I dont now if my ?.something is null or not, that's a test task to determine that. Of course I can always add a null check on an object itself, but this extra assertion shouldn't be necessary I think. So it's error prone for people who don't know implementation details. My assumption was it should behave like 
```csharp
Assert.False(string.IsNullOrEmpty(sut?.NullString))
```
 which works perfectly in this situation

**Comment by anton-makarevich** [comment]
ok, this works so closing the issue. thanks!
