### ISSUE TITLE
SelfReferencingCollectionAssertions.OnlyContain fails when collection is empty

### ISSUE THREAD

**Issue by Overlong** [fluentassertions/fluentassertions#1492]
### Description

SelfReferencingCollectionAssertions.OnlyContain fails when asserting that an empty collection should contain only items matching a predicate, even though the asserted statement is [vacuously true](https://en.wikipedia.org/wiki/Vacuous_truth).

### Complete minimal example reproducing the issue

```csharp
// Arrange
var actual = new int[0];

// Assert
actual.All(item => true).Should().BeTrue();
actual.Should().OnlyContain(item => true);
```

### Expected behavior:

Both assertions to pass.

### Actual behavior:

The first assertion passes, but the second fails with message
  > Expected actual to contain only items matching True, but the collection is empty.

### Versions

* Fluent Assertions: 5.10.3
* .NET runtime: .NET Core 3.1

### Comments

This issue is similar in nature to [my previous issue](https://github.com/fluentassertions/fluentassertions/issues/1410) (whose resolution I'm grateful for). I would think that the behavior of OnlyContain is also by design but that it might be more intuitive for the assertion to always pass on empty collections.

The perhaps counterintuitive behavior of OnlyContain on an empty collection has been [mentioned before](https://github.com/fluentassertions/fluentassertions/pull/633#issuecomment-326802060) (although only in passing).

**Comment by dennisdoomen** [comment]
I'm not convinced yet. If I would use `OnlyContain` because I expect the collection to contain only items matching that specific predicate. I would definitely not expect the collection to be empty. In retrospect, I also think what we did in that [previous issue](https://github.com/fluentassertions/fluentassertions/issues/1410) is a mistake. The goal is not to make the API of FA consistent to the underlying .NET framework methods. The goal is to make things explicit and intention revealing.

**Comment by jnyrup** [comment]
> Outside of mathematics, statements which can be characterized informally as vacuously true can be misleading. Such statements make reasonable assertions about qualified objects which do not actually exist. 

https://en.wikipedia.org/wiki/Vacuous_truth

**Comment by dennisdoomen** [comment]
I read it, but it does not help in this debate. The question is what the majority of people expect to happen.

**Comment by jnyrup** [comment]
The quote was to support your point of view - that even though it may be strictly true it can be misleading.

**Comment by Overlong** [comment]
> I'm not convinced yet. If I would use `OnlyContain` because I expect the collection to contain only items matching that specific predicate. I would definitely not expect the collection to be empty.

A nitpicky but perhaps pertinent remark is that `ContainOnly` seems like a better name for the behavior I seek; to me, `OnlyContain` (but not `ContainOnly`) might indeed suggest that the collection actually contains something.

> In retrospect, I also think what we did in that [previous issue](https://github.com/fluentassertions/fluentassertions/issues/1410) is a mistake. The goal is not to make the API of FA consistent to the underlying .NET framework methods. The goal is to make things explicit and intention revealing.

That is a good point. There might be some value in said consistency, however, insofar as FA users may expect the assertions to be readily expressible in terms of .NET-framework methods (but I can of course only speak for myself). In the case of `StringAssertions.StartWith`, the translation in terms of `String.StartsWith` is immediate, but the case with `OnlyContain` in terms of `All` is not as straightforward.

A weak argument in favor of changing the behavior of `OnlyContain` is that the current behavior would still be available (in an explicit and intention-revealing fashion no less):
```csharp
actual.Should().NotBeEmpty().And.OnlyContain(predicate);
```

This advantage of the proposed behavior is probably mostly a coincidence caused by the fact that assertions can be chained with `And` but not with `Or` though; the proposed behavior would otherwise have been available (in an explicit and intention-revealing way) in terms of the current behavior as
```csharp
actual.Should().BeEmpty().Or.OnlyContain(predicate);
```

In any case, a possible workaround is to use the following extension method (which as far as I can tell has the proposed behavior):
```csharp
public static AndConstraint<TAssertions> ContainOnly<T, TAssertions>(
    this SelfReferencingCollectionAssertions<T, TAssertions> assertions,
    Expression<Func<T, bool>> predicate,
    string because = "",
    params object[] becauseArgs)
    where TAssertions : SelfReferencingCollectionAssertions<T, TAssertions>
{
    // TODO: Validate arguments

    if (!assertions.Subject.Any())
        return new AndConstraint<TAssertions>((TAssertions)assertions);

    return assertions.OnlyContain(predicate, because, becauseArgs);
}
```

**Comment by jnyrup** [comment]
> A weak argument in favor of changing the behavior of OnlyContain is that the current behavior would still be available (in an explicit and intention-revealing fashion no less):
> ```cs
> actual.Should().NotBeEmpty().And.OnlyContain(predicate);
> ```

I agree in the weakness, if the majority would expect `OnlyContain` to fail on an empty collection, then needing to use
`actual.Should().NotBeEmpty().And.OnlyContain(predicate)` moves the burden from the minority to the majority.

I think those who seek an empty collection to pass, should copy your ~20 line extension method.

**Comment by eNeRGy164** [comment]
You could compare it to `String.IsNullOrEmpty`, that would give something like `OnlyContainAndNotEmpty(predicate)`
But in that case I think `.NotBeEmpty().And.OnlyContain(predicate);` is just as good, if not better.

**Comment by dennisdoomen** [comment]
@Overlong So me and @jnyrup discussed the pros and cons. And even though we value the effort you put into making your arguments sound, we sometimes need to weigh those pros and cons against the greater audience of the library. In this case, we decided to keep the behavior as is. I hope you can understand that. 

But next time, please don't hesitate to propose improvements. It keeps us sharp ;-)
