### ISSUE TITLE
Should().Be() Throws exception using dynamic types

### ISSUE THREAD

**Issue by SteveLaycock** [fluentassertions/fluentassertions#1493]
### Description

`Should().Be()` throws an exception when the types being tested are dynamic.

```cs
[TestMethod]
public void ExceptionWithDynamic()
{
    dynamic myDynamic1 = 1;
    dynamic myDynamic2 = 1;
    myDynamic1.Should().Be(myDynamic2);
}
```

Gives the exception
```
ExceptionWithDynamic
   Source: UnitTest1.cs line 2206
   Duration: 329 ms

  Message: 
    Test method VBALibrary.ExceptionWithDynamicDemo.ExceptionWithDynamic threw exception: 
    Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'int' does not contain a definition for 'Should'
  Stack Trace: 
    CallSite.Target(Closure , CallSite , Object )
    UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
    ExceptionWithDynamicDemo.ExceptionWithDynamic() line 2210

```
If I replace the dynamic with int all is fine.

```cs
public class ExceptionWithDynamicDemo
{
    [TestMethod]
    public void ExceptionWithDynamic()
    {
        int myDynamic1 = 1;
        int myDynamic2 = 1;
        myDynamic1.Should().Be(myDynamic2);
    }
}
```

**Comment by jnyrup** [comment]
Have you had a look at #234 and #473?

**Comment by SteveLaycock** [comment]
I guess I've been spoiled by the Rubberduck repository which pops up related posts when you enter the title for an issue.

My other thoughts would be that as dynamic appears to be problematical there should be some kind of discussion of the issues on the help pages.

If I were authoring the code, I'd be trying to forwarn people of the issues with a specific message rather than relying on an exception message.

**Comment by jnyrup** [comment]
I agree that a note in the documentation would be nice, we're open for PR's ;)

We're not relying on any exceptions (as I see it), it's how C# handles extension methods on dynamic types.

See this minimal example that not use Fluent Assertions, but behaves similar to your example.
```cs
[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestMethod1()
    {
        dynamic obj = 1;
        obj.Should();
    }
}

public static class Extensions
{
    public static object Should(this object o)
    {
        throw new System.Exception("this is never hit");
    }
}
```
![image](https://user-images.githubusercontent.com/919634/107508562-84643b00-6ba1-11eb-9256-a52073c20489.png)

**Comment by jnyrup** [comment]
The best you can probably do is to cast your dynamic object to `object` before calling `Should()`.

```cs
dynamic obj = 1;
((int)obj).Should();
```
