### ISSUE TITLE
ArgumentNullException when asserting on a delegate that was obtained by compiling an expression

### ISSUE THREAD

**Issue by m-ringler** [fluentassertions/fluentassertions#1512]
### Description

When asserting on a compiled expression an `ArgumentNullException` is thrown in [`FailIfSubjectIsAsyncVoid`](https://github.com/fluentassertions/fluentassertions/blob/4787885aca5dcda3715a047d7fd6f53f022698c4/Src/FluentAssertions/Specialized/DelegateAssertions.cs#L266)

### Complete minimal example reproducing the issue

```csharp
[TestMethod]
public void CompiledLambdaShouldNotThrow()
{
    Expression<Action> expr = () => DoNothing();
    Action action = expr.Compile();
    action.Should().NotThrow();
}

private static void DoNothing()
{
}
```

### Expected behavior:

Test passes

### Actual behavior:

Test fails with:
~~~
Message: 
    Test method TestClass.CompiledLambdaShouldNotThrow threw exception: 
    System.ArgumentNullException: Value cannot be null.
    Parameter name: source
  Stack Trace: 
    Enumerable.OfType[TResult](IEnumerable source)
    DelegateAssertions`1.FailIfSubjectIsAsyncVoid() line 268
    DelegateAssertions`1.NotThrow(String because, Object[] becauseArgs) line 103
    TestClass.CompiledLambdaShouldNotThrow() line 321
~~~
### Versions

* Which version of Fluent Assertions are you using?
5.10.3

* Which .NET runtime and version are you targeting?
.NET framework 4.6.2

**Comment by dennisdoomen** [comment]
It's no longer reproducible on the 6.0 development branch, so I propose to close it.

**Comment by m-ringler** [comment]
I can confirm that it is fixed in FluentAssertions.6.0.0-alpha0001

**Comment by m-ringler** [comment]
Workaround: 
~~~
Action action1 = () => action.Invoke();
action1.Should().NotThrow();
~~~
