### ISSUE TITLE
Provide Copyright information in LICENSE file

### ISSUE THREAD

**Issue by romans-uteam** [fluentassertions/fluentassertions#1513]
https://github.com/fluentassertions/fluentassertions/blob/abecbdeb60533e73227a2f1e0936167ff4e4f688/LICENSE#L179

Hello, I've been looking through the licensing information for this repo and noticed, that there is missing Copyrights claims in LICENSE file. 
Could you please add this information, please? Thank you.

**Comment by dennisdoomen** [comment]
Thank you for pointing that out. Added the missing info.

**Comment by jnyrup** [comment]
I don't think that part should be changed.

See e.g.
https://github.com/nodatime/nodatime/blob/master/LICENSE.txt
https://github.com/serilog/serilog/blob/dev/LICENSE
https://github.com/apple/swift/blob/main/LICENSE.txt

https://github.com/kubernetes/kubernetes/blob/master/LICENSE
They even reverted a similar change: https://github.com/kubernetes/kubernetes/commit/d30db1f9a915aa95402e1190461469a1889d92be#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

> Thanks for looking, but unfortunately, that's not how it works-- our lawyers have assured us that those fields are ONLY to be filled in in the boilerplate section at the top of each file, and that the license itself is to remain untouched.
https://github.com/kubernetes/kubernetes/pull/883#issuecomment-52092355

> IIRC the Google lawyers say that we shouldn't modify the LICENSE file itself but instead just do that substitution when applying to individual files (...)
https://github.com/kubernetes/kubernetes-template-project/issues/3#issuecomment-262098623

**Comment by romans-uteam** [comment]
Hey, thanks for the fast reply, 
I think you are right and the APPENDIX should be applied only on specific files (this is a kind of instruction, which is not really part of the license statements).

But in this case, can you point who can be considered as 'Licenser' for this project?

**Comment by dennisdoomen** [comment]
> I don't think that part should be changed.

There was something in the back of my mind saying it should not directly commit to `develop` without a review from @jnyrup .... I guess it was my conscious 🤦‍♂️

**Comment by jnyrup** [comment]
@dennisdoomen You have my blessing to revert the change directly to `develop` :godmode: 

@romans-uteam I see your point, but I'm no lawyer and my Google skills aren't strong enough. Do you happen to know a lawyer with knowledge about OSS licensing?
