### ISSUE TITLE
Add overloads for constraints without optional arguments

### ISSUE THREAD

**Issue by zetroot** [fluentassertions/fluentassertions#1528]
### Description

F# (at least in version 5.0) has difficulties consuming C#-defined functions with "optional" arguments with default value. So writing assertions in F# is not so clean as in C#:

### Example
Excellent C# assertion looks like:
```csharp
// Arrange
var x  = 0;

// Act
++x;

// Assert
x.Should().Be(1);
```
But in F# you should write:
```fsharp
// Arrange
let mutable x = 0

// Act
x <- x+1

// Assert
x.Should().Be(1, "because you need to specify \"because argument\"");
```

### What i would like to have

Just overloads for constraints. Something like this:

```csharp
public AndConstraint<NumericAssertions<T>> Be(T expected) => this.Be(expected, "");
```

### Versions

* Which version of Fluent Assertions are you using?
5.10.3
* Which .NET runtime and version are you targeting?
.NET 5.0

### Additional Information

I would like to handle this by myself, if nobody minds.

**Comment by jnyrup** [comment]
I have no experience with F#, but maybe @ursenzler has a trick?

I can't imagine we would want to add the overload you're proposing as this would at least double the size of the API surface.

**Comment by zetroot** [comment]
@jnyrup oh, i have not thought of the API surface size. If there will be no trick found - i'll implement own extensions, not to impact public API. Thanks a lot for your time!

**Comment by dennisdoomen** [comment]
I agree with @jnyrup here. We actually removed all those extra overloads because C# supports optional parameters.

**Comment by ursenzler** [comment]
I wrote some wrapper functions to make using FluentAssertions easier from F#. You can find them here: https://gist.github.com/ursenzler/293b9f23affe7543f8dac288f6fc199b

This works also great in cases when you need to add special configuration.

**Comment by zetroot** [comment]
@ursenzler very nice! Thank you!
Thanks a lot, guys! I just wanted to be helpful for such great project

**Comment by lg2de** [comment]
@dennisdoomen and @jnyrup, what do think about the rule [CA1026: Default parameters should not be used](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1026?view=vs-2019)?

**Comment by dennisdoomen** [comment]
It depends. If a library is designed to be used by multiple .NET languages, you should not rely on default parameters. But FluentAssertions was originally designed for C#. And the idea of duplicating all APIs with an extra overload does not appeal to me.

**Comment by jnyrup** [comment]
Several answers to question depending on the perspective.

From a cross-language perspective it makes sense.
From within C# it is broken in every async method taking an optional `CancellationToken`.
And I fully agree with Dennis about is doesn't sound appealing tripling the API surface augmenting every `Foo()` with `Foo(string because)` and `Foo(string because, object[] becauseArgs)`.

If I we're writing F# I would head over to the F# repo and open/vote on an issue allowing this (I have no idea if technically possible)

**Comment by ursenzler** [comment]
F# does not support overloading of functions because of function currying. Only method overloads are possible. But no default values. 

When using FluentAssertions from F#, I think it is best to use some wrapper functions. That also an easy way to define some custom configuration.

**Comment by cmeeren** [comment]
For reference: https://github.com/fsharp/fslang-suggestions/issues/1267
