### ISSUE TITLE
Should().NotBeNullOrWhiteSpace() ?

### ISSUE THREAD

**Issue by GiganteX** [fluentassertions/fluentassertions#1545]
Hi!

The Strings page at https://fluentassertions.com/strings says there's a method :
`theString.Should().NotBeNullOrWhiteSpace();`

...but I am getting :
'ObjectAssertions' does not contain a definition for 'NotBeNullOrWhiteSpace' ...

Oh wait, I am doing this:
`Result.Should().NotBeNull().And.Should().NotBeNullOrWhiteSpace();`

That doesn't work, but this does:

`Result.Should().NotBeNullOrWhiteSpace();`

Why is there a difference there?

**Comment by dennisdoomen** [comment]
What's the type of `Result`? `object`?

**Comment by dennisdoomen** [comment]
Hahaha. Didn't even notice that. But I'm pretty sure `Result` is of type `object` in the example.

**Comment by dennisdoomen** [comment]
Agreed. But giving that error about `ObjectAssertions`, I get the feeling he/she wasn't copying the right example. 

But let's wait until @GiganteX answers him/herself.

**Comment by GiganteX** [comment]
> You have a `Should()` to much in
> `Result.Should().NotBeNull().And.Should().NotBeNullOrWhiteSpace();`
> It should just be
> `Result.Should().NotBeNull().And.NotBeNullOrWhiteSpace();`.

Aah I see, that makes sense then! Thanks!

**Comment by GiganteX** [comment]
> Agreed. But giving that error about `ObjectAssertions`, I get the feeling he/she wasn't copying the right example.
> 
> But let's wait until @GiganteX answers him/herself.

It's a string yes, like this:

![image](https://user-images.githubusercontent.com/15637533/117544478-e8bc5c80-b021-11eb-9372-6ffbd31a22ca.png)

But when I remove the extra Should() it works nicely!

**Comment by jnyrup** [comment]
The misleading/confusing error message with `ObjectAssertions` is because `And` return an `AndConstraint` and then `Should` resolved to `Should(this object)` that returns an `ObjectAssertions` which, as the messages points out, does not contain any `NotBeNullOrWhiteSpace` method.
