### ISSUE TITLE
GuidAssertions.Be(string) throws FormatException for invalid input

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#1553]
### Description

When providing a string not convertible to a `Guid` `GuidAssertions.Be(string)` throws a `FormatException`.

We have two options:
1) Keep the overload taking a `string` and validate it using `Guid.TryParse`
2) Delete the overload and let users pass in a typed `Guid`.

I vote for the second.

### Complete minimal example reproducing the issue

```cs
Guid.NewGuid().Should().Be("");
```

### Expected behavior:

We should not throw a `FormatException`.

### Actual behavior:

We throw a `FormatException`.

### Versions

* Fluent Assertions 5.10.3

**Comment by dennisdoomen** [comment]
I think it makes sense to have an overload that takes a `string`. It should just throw a proper exception.

**Comment by eNeRGy164** [comment]
I can do this one.
