### ISSUE TITLE
Support Is() paradim to return predicate evaluations instead of throwing assertion exceptions

### ISSUE THREAD

**Issue by roryprimrose** [fluentassertions/fluentassertions#158]
There are several circumstances where I want to use the fluent assertions power of object/value evaluation in order to return a predicate evaluation rather than to throw an assertion exception. The classic example is that I want to assert whether a stub was called with a particular `DateTimeOffset` value that is close to a particular value. `Should()` is great for asserting an output, but something like an `Is()` for returning a boolean result will be useful for other types of testing assertions.

For example:

```cs
subscriptions.Received()
    .CreateAsync(
        Arg.Is<SubscriptionCreateRequest>(
            x =>
                x.TrialEnd.Value.IsWithin(
                    TimeSpan.FromSeconds(2),
                    trialExpires)));
```

To get this to work, I have to use hacky extension methods like:

```cs
public static bool IsWithin(this DateTimeOffset source, TimeSpan allowedTime, DateTimeOffset comparedTo)
{
    if (source > comparedTo)
    {
        var greaterTime = source.Subtract(comparedTo);

        return greaterTime <= allowedTime;
    }

    var lesserTime = comparedTo.Subtract(source);

    return lesserTime <= allowedTime;
}
```

It would be really sweet if I could use FluentAssertions in this mix.

```cs
subscriptions.Received()
    .CreateAsync(
        Arg.Is<SubscriptionCreateRequest>(
            x =>
                x.TrialEnd.Value.Is().CloseTo(trialExpires)));
```

**Comment by princeo911** [comment]
> ```cs
> public bool MatchesAssertion(Action assertion)
> {
>   using (var scope = new AssertionScope())
>   {
>      assertion();
>      return scope.Discard().Any();
>   }
> }
> ```

Cant this be made into a extension method like should() or is there an equivalent I have missed? 

It would be nice if I didnt have to recreate this method for every test project I have.

**Comment by raschmitt** [comment]
Totally agree with @princeo911 this should be a standard extension.

As of syntax, I think `MatchesAssertions` (in plural) is just fine.

**Comment by dennisdoomen** [comment]
An extension method on what?

**Comment by raschmitt** [comment]
My bad, not an extension method, but a public available method. 

So we can use it out of the box as you proposed like this:

```csharp
subscriptions.Received()
    .CreateAsync(
        Arg.Is<SubscriptionCreateRequest>(
            x => MatchesAssertions(() =>
                x.TrialEnd.Value.Is().CloseTo(trialExpires))));
````

**Comment by dennisdoomen** [comment]
Maybe as a static method on `AssertionScope`

**Comment by mpodonyi** [comment]
What was the result of this ticket?
