### ISSUE TITLE
Should().BeApproximately() with custom IEqualityComparer

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [fluentassertions/fluentassertions#1584]
### Description

I am comparing 3D vectors which, due to float precision, might end up a little bit different from what I expect. Therefore I would like to use a custom IEqualityComparer in `myVector.Should().BeApproximately( expectedVector, myComparer );`

I saw there was a PR #1284 which added this behaviour. Unfortunately it has been removed since.

Then being possible:

```csharp
a.Should().BeEquivalentTo( b, opt => opt.Using( CustomComparer) );
```

is not working anymore.

Did I miss something? Is there another way to do it?

Cheers,
Georg

### Versions

* Version 5.10.3 with .NET 5.0

**Comment by dennisdoomen** [comment]
Yes, but that's only available in 6.0 alpha 2.

**Comment by georg-eckert-zeiss** [comment]
Still great to hear that : )

**Comment by dennisdoomen** [comment]
Does that mean we can close the issue?
