### ISSUE TITLE
ClearExpectation after Given<> always returns false

### ISSUE THREAD

**Issue by eNeRGy164** [fluentassertions/fluentassertions#1596]
### Description

`ClearExpectation()` returns `false` after a successful `Given<>`.

### Complete minimal example reproducing the issue

```csharp
bool success = Execute.Assertion
    .Given(() => new object())
    .ForCondition(subject => true)
    .FailWith("but collection is <null>.")
    .Then
    .ClearExpectation();

success.Should().BeTrue();
```

### Expected behavior:

Should return `true`.

### Actual behavior:

Returns `false`

Having another `Given(() => {}).ForCondition()` chain after `ClearExpectation` will return `true` again.

### Versions

* 6.0 beta (source)
* Any

**Comment by eNeRGy164** [comment]
I'm investigating this and finding all kinds of methods that are not completely following the continuation logic as expected.

Expect incoming unit tests on `AssertionScope`, `ContinuedAssertionScope` and `GivenSelector` 😅

**Comment by dennisdoomen** [comment]
Then I'll need to dive into this when I have time again.
