### ISSUE TITLE
Event monitor breaks when monitoring events generacted by Xamarin.CommunityToolkit's ObservableObject

### ISSUE THREAD

**Issue by AdamBarnettUK** [fluentassertions/fluentassertions#1612]
### Description

I've been using event monitoring in many of my projects to verify the PropertyChanged event is being correctly invoked. I recently started work on a Xamarin Forms project and have been using some implementations from the Xamarin Community Toolkit. In particular, the ObservableObject implementation seems to cause some issues with the event monitoring. Honestly not sure where the fault lies, but the ObservableObject seems to work with everything else and the fault is only present when using the event monitoring provided with FluentAssertions. If you guys decide the fault lies with the XCT, I'll bounce this over to their issue board. 

### Complete minimal example reproducing the issue

[WeakEventMonitoringTest.zip](https://github.com/fluentassertions/fluentassertions/files/6669897/WeakEventMonitoringTest.zip)

As this relies on an XCT nuget package, I've written a short sample and attached it to this issue. The snippets of code that cause this issue are quoted below (the sample I've provided has more tests showing working examples). 

```csharp
public class RaisePropertyChangedWeakReference : ObservableObject
{
    public int MyProperty { get; }
    public void RaisePropertyChangedEvent()
    {
        OnPropertyChanged(nameof(MyProperty));
    }
}

public class TestClass
{
    [Test]
    public void WeaklyRaisePropertyChangedWithMonitor()
    {
        RaisePropertyChangedWeakReference testObject = new();
        using (var monitor = testObject.Monitor())
        {
            testObject.RaisePropertyChangedEvent();
        }
    }
}
```

Note that ObservableObject is the class provided by the Xamarin Community Toolkit. 

### Expected behavior:

The event monitor correctly registers an event has been raised, and this could be verified using the appropriate check. 

### Actual behavior:

The following exception is thrown:
Message: 
    Xamarin.CommunityToolkit.Exceptions.InvalidHandleEventException : Parameter count mismatch. If invoking an `event Action` use `HandleEvent(string eventName)` or if invoking an `event Action<T>` use `HandleEvent(object eventArgs, string eventName)`instead.
      ----> System.Reflection.TargetParameterCountException : Parameter count mismatch.

  Stack Trace: 
    EventManagerService.HandleEvent(String& eventName, Object& sender, Object& eventArgs, Dictionary`2& eventHandlers)
    DelegateWeakEventManager.RaiseEvent(Object sender, Object eventArgs, String eventName)
    ObservableObject.OnPropertyChanged(String propertyName)
    RaisePropertyChangedWeakReference.RaisePropertyChangedEvent() line 15
    WeakEventSample.WeaklyRaisePropertyChangedWithMonitor() line 78
    --TargetParameterCountException
    DynamicMethod.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    EventManagerService.HandleEvent(String& eventName, Object& sender, Object& eventArgs, Dictionary`2& eventHandlers)

### Versions

Fluent Assertions version: 5.10.3
.NET Runtime: .NET Core 3.1
Xamarin.CommunityToolkit: 1.1.0

### Additional Information

The first difference that came to mind is that the ObservableObject is implemented using a DelegateWeakEventManager (hence the naming I've used in the sample). My first suspicion was that this might be causing the issue, although the event should be exposed in the normal manner. Apologies if this issue actually lies with the CommunityToolkit implementation and I've raised the issue in the wrong place.

**Comment by dennisdoomen** [comment]
It's because FA assumes you implement `INotifyPropertyChanged`, which defines `event PropertyChangingEventHandler PropertyChanging;`

**Comment by AdamBarnettUK** [comment]
Is this related to issues about not picking up inherited events? ObservableObject implements INotifyPropertyChanged, but is that not visible to the EventMonitor?

**Comment by dennisdoomen** [comment]
On second thought, I think it does implement it correctly. But I don't see any FluentAssertions code in the stack trace, so it looks like something fails inside the `ObservableObject`.

**Comment by AdamBarnettUK** [comment]
Yeah... my suspicion was that some part of the event monitoring registered a callback that ended up being bundled into this exception. I'm a bit busy for the next couple of hours, but I'll try to get an issue raised against XCT so they can look into this, and I'll link it back to this issue.

Not sure what your policy is on leaving this open till we get a response from them? Possibly you'd prefer to close this and, if I have more info that suggests it's an FA issue, open a new issue?

**Comment by dennisdoomen** [comment]
We can leave it open for a while.

**Comment by dennisdoomen** [comment]
Any update on this?

**Comment by AdamBarnettUK** [comment]
Sorry, no. This issue was raised https://github.com/xamarin/XamarinCommunityToolkit/issues/1411 but I guess it's not been a priority. Happy to close this off, as it doesn't look like it will be addressed and there is a workaround for it using a non-event monitor method.
