### ISSUE TITLE
Improve Stack Trace for InnerException of TargetInvocationExceptions

### ISSUE THREAD

**Issue by FabianNitsche** [fluentassertions/fluentassertions#1613]
During equivalency steps, methods are called by reflection e.g.
```csharp
try
{
    HandleMethod.MakeGenericMethod(typeOfEnumeration).Invoke(null, new[] { validator, subjectAsArray, comparands.Expectation });
}
catch (TargetInvocationException e)
{
    throw e.Unwrap();
}
```

The Unwrap extension method gets the inner exception from the TargetInvocationException. However, the throw in the catch kills the original stack trace which lead to some confusion when trying to understand the problem.

Since FluentAssertions 6.0.0 is dropping support for Framework <= 4.5 it could now use [ExceptionDispatchInfo](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.exceptiondispatchinfo?view=netframework-4.5) to keep the original stack trace.

The Unwrap extension method then would change to
```csharp
public static ExceptionDispatchInfo Unwrap(this TargetInvocationException exception)
{
    Exception result = exception;
    while (result is TargetInvocationException)
    {
        result = result.InnerException;
    }

    return ExceptionDispatchInfo.Capture(result);
}
```

And the site of the invocation would change to
```csharp
catch (TargetInvocationException e)
{
    e.Unwrap().Throw();
}
```

If you are interested in this improvement, I can provide a pull request draft.

**Comment by dennisdoomen** [comment]
Do you have an example of what the stack trace looks like before and after the change? I don't quite grasp what problem you are solving.

**Comment by FabianNitsche** [comment]
You can just run this example [DotNetFiddle](https://dotnetfiddle.net/ku7PXV)

The stack trace of the current implementation points to the position where the unwrapped exception is rethrown. Which is a little confusing, since the NotImplementedException happens in the property getter.

The stack trace of the implementation using ExceptionDispatchInfo is pointing to the right method that threw the exception in the first place.

**Comment by dennisdoomen** [comment]
Very nice. If you're up to it, we would be more than happy to welcome that PR

**Comment by FabianNitsche** [comment]
I will look into it. I think it should be a non-breaking change.
