### ISSUE TITLE
Assertion of type (BeOfType<>) after And fails

### ISSUE THREAD

**Issue by rneeft** [fluentassertions/fluentassertions#1617]
### Description

Assertion of type after `And` fails

### Complete minimal example reproducing the issue

```csharp
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;

namespace FluentAssertions
{
    [TestClass]
    public class FluentAssertionTest
    {
        private Exception exception = new ArgumentNullException();

        [TestMethod]
        public void This_should_work_but_it_does_not()
        {
            // TestMethod fails: Expected type to be System.ArgumentNullException, 
            // but found FluentAssertions.Primitives.ObjectAssertions.
            exception.Should().NotBeNull().And.Should().BeOfType<ArgumentNullException>();
        }

        [TestMethod]
        public void This_works()
        {
            exception.Should().NotBeNull();
            exception.Should().BeOfType<ArgumentNullException>();
        }
    }
}

```

### Expected behavior:

Both test method to work

### Actual behavior:

Test method with `And` (This_should_work_but_it_does_not) is not working

### Versions

FluentAssertions version: 5.10.3 (and 6.0.0-beta0001)
.NET Core 3.1

**Comment by jnyrup** [comment]
Your two examples are not identical.
The first one does not assert that `exception` is of type `ArgumentNullException`.
Due to the extra `Should()` after `And`, it asserts that the `ObjectAssertions` returned from `And` is of type `ArgumentNullException`.

```cs
exception.Should().NotBeNull().And.BeOfType<ArgumentNullException>();
```

`BeOfType` already checks for null, so it can also be shortened to
```cs
exception.Should().BeOfType<ArgumentNullException>();
```

**Comment by dennisdoomen** [comment]
Indeed. Maybe we should build in a safeguard that if you call any `Should` method on one of the built-in assertion classes, it throws a clear exception.
