### ISSUE TITLE
BeEquivalentTo and different property names

### ISSUE THREAD

**Issue by Ergamon** [fluentassertions/fluentassertions#1626]
Hope this is also the right place for questions?

I found some old threads about this topic and wanted to check if there is meanwhile some solution to this scenario.

Basically I am writing a lot of tests for some mapping code. Of course most of the time it is just a copy from one property of the other with the same name. Therefore BeEquivalentTo fits perfect.

Let´s take the simple scenario from the documentation, I want to copy an Order to an OrderDto. Let´s assume they have the same properties but the Order has an OrderName and the OrderDto just a Name.

How do I tell FluentAssertions this?

So far I ended with

dto.Should().BeEquivalentTo(order, options => options.Exclude(d =>d. Name));

dto.Name.Should().Be(order.OrderName);

But that feels not really nice. As I have to write every property twice. (I dont want to use ExcludeMissingMembers, the whole point of these tests is to quickly show missing mappings when the objects change in the future)

**Comment by dennisdoomen** [comment]
I think what you mean is a duplicate of #535. I want that as well, but have not found a nice API.

**Comment by Ergamon** [comment]
Ok, thx for your quick reply. This is basically the thread Google took me to. I thought perhaps I missed sth as it originates 2017.

Is there at least any way to achieve this even in an ugly version? I have not found any working sample to handle this at all.

**Comment by dennisdoomen** [comment]
No, not right now unfortunately.

**Comment by Ergamon** [comment]
At least I dont have to look further ;)
