### ISSUE TITLE
BeEquivalentTo ComparingByMembers still calls object.Equals

### ISSUE THREAD

**Issue by Ergamon** [fluentassertions/fluentassertions#1628]
### Description

BeEquivalentTo calls object.Equals, but according to documentation  ComparingByMembers changes this behavior.

### Complete minimal example reproducing the issue

E.g.

```csharp
  public class Target
  {
    public string Value1 { get; set; }
  }

  public record Source(string Value1, string Value2);

  var source = new Source("value1", "value2");
  var target = new Target()
  {
    Value1 = source.Value1,
  };

  target.Should().BeEquivalentTo(source, options => options.ComparingByMembers<Target>());
```

### Expected behavior:

The test passes.

### Actual behavior:

Test fails cause BeEquivalentTo still calls Equals on the record,

### Versions

* Which version of Fluent Assertions are you using? 5.10.3
* Which .NET runtime and version are you targeting?  .NET 5.0.

**Comment by dennisdoomen** [comment]
It's the `source` that is used as the expectation, and which will drive the comparison. So in this case, it's expecting the target to be record. And since records override `Equals`, it'll try to compare the `source` with `target` using the source's `Equals` implementation. The `ComparingByMembers` statement doesn't do anything, since `Target` is not used in the expectation. 

In v6 (currently in beta), we've [changed the behavior](https://github.com/fluentassertions/fluentassertions/blob/release-6.0/docs/_pages/objectgraphs.md#value-types) of records so that they are compared by their members.

**Comment by Ergamon** [comment]
The problem I have is that I cannot change the target/source. I made the example with my problem.

The logic I have is that I want to verify that every property in target is mapped, but not every property in source must be mapped.

Usually I have a DTO to export my data from my entities. As I consider my mapping test also as some kind of safety net for future changes, I want my tests to fail, if someone extends the DTO and for whatever reason the data is not copied from the source.

On the other hand I dont care if someone extends the entity.

This behavior is exactly the way FluentAssertions BeEquivalentTo works unless the source overwrites Equals.

So from what you are saying I can achieve what I want with swapping source and target.

In the end this works, but feels a little unethical to me ;)

I mean normally I write my tests like this:

// Given
var source = GetSource();
var mapper = GetMapper();

// When
var result = mapper.Map<Target>(source);

// Then
result.Should().BeEquivalentTo(source);

So I call a method and verify the result.

While technically probably the same, it feels a little strange for me to write
source.Should().BeEquivalentTo(result);

If you know what I mean.

**Comment by dennisdoomen** [comment]
Yes, I've run into that specific situation once as well. But as a design principle, we valued the ability to assert that certain properties of the subject-under-test have certain values, and ignore the rest. Maybe you can use something like API validation tests to cover that extra scenario. There's a [Roslyn analyze](https://github.com/dotnet/roslyn-analyzers/blob/ab7019ee000e20e0b822f6fca7d64eef4e09995d/src/PublicApiAnalyzers/PublicApiAnalyzers.Help.md) for that, and in the Fluent Assertions code-base we use [Verify](https://github.com/VerifyTests/Verify/) to ensure we don't introduce breaking changes accidentally.
