### ISSUE TITLE
[Feature Request] Throw overload that takes an argument

### ISSUE THREAD

**Issue by lonix1** [fluentassertions/fluentassertions#1629]
### Background

I can assert that an action throws, using a generic parameter:
````cs
action.Should().Throw<SomeException>();
````

### Feature Request

Please consider adding an overload that takes an instance as well:
````cs
action.Should().Throw(expectedType);
````

This would be very useful when I don't know the type at compile time.

Right now we need to use an ugly workaround:
````cs
try {
  action();
}
catch (Exception e) {
  e.Should().BeOfType(expectedType);
}
````

### Versions

* Which version of Fluent Assertions are you using? 5.10.3
* Which .NET runtime and version are you targeting? 5.0.301

**Comment by dennisdoomen** [comment]
What about using `Should().Throw<Exception>().Which.Should().BeOfType(expectedType);

**Comment by lonix1** [comment]
Outstanding. Didn't know about that one. Thank you!
