### ISSUE TITLE
Non-generic overload for WithInnerExceptionExactly

### ISSUE THREAD

**Issue by lonix1** [fluentassertions/fluentassertions#1632]
## Background

I can do this:
````cs
action.Should().Throw<TargetInvocationException>()
  .WithInnerExceptionExactly<TException>()         // <--- known at compile time
  .Where(x => x.Message == message)
  .And.ParamName.Should().Be(paramName);
````

## Problem

The above assumes I know `TException` at compile time. But what if I don't?

I can rewrite it using [a trick](https://github.com/fluentassertions/fluentassertions/issues/1629#issuecomment-886243261) I learnt from @dennisdoomen, like this:
````cs
action.Should().Throw<TargetInvocationException>()
  .WithInnerException<Exception>().Which.Should().BeOfType(expectedType)
  //.Where(x => x.Message == message)
  //.And.ParamName.Should().Be(paramName);
````

But then I can't chain `.Where` etc.

## Feature Request

I read the [exception docs](https://fluentassertions.com/exceptions/) but couldn't find a workaround.

Please consider adding an overload that take an instance:
````cs
.WithInnerExceptionExactly(expectedType)
````

## Versions

* Which version of Fluent Assertions are you using? 5.10.3
* Which .NET runtime and version are you targeting? 5.0.301

**Comment by dennisdoomen** [comment]
Sure. If anybody is willing to contribute this, we would welcome it.
