### ISSUE TITLE
BeEquivalentTo and Excluding does not work with auto generated protobuf classes.

### ISSUE THREAD

**Issue by bernarden** [fluentassertions/fluentassertions#1633]
### Description
We generate our c# schema classes using protobuf files. For some reason BeEquivalentTo and Excluding are not working as expected with these generated classes, since version 5 of FluentAssertions when ShouldBeEquivalentTo() became Should().BeEquivalentTo().

### Complete minimal example reproducing the issue
TestProject.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net50</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.17.3" />
    <PackageReference Include="Grpc.Tools" Version="2.38.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="5.10.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.1.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="**/*.proto" />
  </ItemGroup>
</Project>
```

Batch.proto
```proto
syntax = "proto3";
package TestProject;
option csharp_namespace = "TestProject";

message Batch {
    string Id = 1;
    string Value = 2;
}
```

UnitTest.cs
```csharp
using FluentAssertions;
using Xunit;

namespace TestProject
{
    public class UnitTest
    {
        [Fact]
        public void Test()
        {
            var batch1 = new Batch()
            {
                Id = "SomeId",
                Value = "Value1"
            };

            var batch2 = batch1.Clone();

            // Works
            batch1.Should().BeEquivalentTo(batch2);

            batch2.Value = "Value2";

            // Does not work
            batch1.Should().BeEquivalentTo(batch2, o => o
                .Excluding(x => x.Value)
                // I then tried the following options to potentially ignore auto generated fields but it did not work either.
                .Excluding(x => ((Google.Protobuf.IMessage) x).Descriptor)
                .Excluding(x => x.SelectedMemberPath.EndsWith("id_"))
                .Excluding(x => x.SelectedMemberPath.EndsWith("value_"))
                .ExcludingProperties()
                .ExcludingFields());

            // Used to work in v4
            // batch1.ShouldBeEquivalentTo(batch2, o => o.Excluding(x => x.Value));
        }
    }
}
```

### Expected behavior:
The test should pass when using the following command:
`batch1.Should().BeEquivalentTo(batch2, o => o.Excluding(x => x.Value)`

### Actual behavior:
Xunit.Sdk.XunitException
Expected batch1 to be { "Id": "SomeId", "Value": "Value2" }, but found { "Id": "SomeId", "Value": "Value1" }.

With configuration:
- Use declared types and members
- Compare enums by value
- Exclude member root.Value
- Exclude member root.Descriptor
- Exclude member when x.SelectedMemberPath.EndsWith("id_")
- Exclude member when x.SelectedMemberPath.EndsWith("value_")
- Match member by name (or throw)
- Without automatic conversion.
- Be strict about the order of items in byte arrays

   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context)
   at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs)
   at TestProject.UnitTest.Test() in C:\Dev\TestProject\TestProject\UnitTest1.cs:line 25

### Versions
* Which version of Fluent Assertions are you using? 5.10.3
* Which .NET runtime and version are you targeting? .NET Core 3.1 and .NET 5.

**Comment by dennisdoomen** [comment]
I suspect it's caused by `Batch` being either a `struct` or a class that overrides `Equals`. In that case, FA will honor the value semantics of that type. This was a big change in v5. You can read more about that [here](https://fluentassertions.com/objectgraphs/#value-types) or the [rationale behind that](https://www.continuousimprover.com/2018/02/fluent-assertions-50-best-unit-test.html#redefining-equivalency).

**Comment by bernarden** [comment]
You are right. Batch class is overriding Equals method. I had to add .ComparingByMembers\<Batch\>() to resolve my issue. Thank you so much for your help! 👍

**Comment by dennisdoomen** [comment]
No problem. That's why we're here ;-)
