### ISSUE TITLE
Ambiguous invocation when using BeEquivalentTo with Excluding with <6.0

### ISSUE THREAD

**Issue by valentasm1** [fluentassertions/fluentassertions#1645]
This code brings compiler exception "ambiguous invocation" when using 6.0.0 version, but works with lower versions.

```cs
private class Test1
{
    public string Name { get; set; }
}

private class Test2
{
    public string Name { get; set; }
}

[Fact]
public async Task Test_Case()
{
    var test1 = new Test1();
    var test2 = new Test2();

    //Work around
    //Expression<Func<IMemberInfo, bool>> expression = info => info.Name == "Level.Level.Text";
    //test1.Should().BeEquivalentTo(test2, opts => opts.Excluding(expression));

    test1.Should().BeEquivalentTo(test2,
        opts => opts.Excluding(ctx => ctx.SelectedMemberPath == "Level.Level.Text"));
}
```

**Comment by ajeckmans** [comment]
SelectedMemberPath  was renamed to Path.
So `
    test1.Should().BeEquivalentTo(test2,
        opts => opts.Excluding(ctx => ctx.Path == "Level.Level.Text"));` should work. 

The docs unfortunately do not reflect this yet.

**Comment by jnyrup** [comment]
In #1379 we changed the name of `IMemberInfo.SelectedMemberPath` to `IMemberInfo.Name`.

That's probably the reason why your compiler gives an exception about "ambiguous invocation".
My compiler (VS 2019 16.10.4) just selects the `Test2.Name` property.

To help your compiler disambiguate `ctx.Name`, you can use
```
test1.Should().BeEquivalentTo(test2,
    opts => opts.Excluding((IMemberInfo ctx) => ctx.Name == "Level.Level.Text"));
```

**Comment by jnyrup** [comment]
whoops, you're right - it was renamed to `Path` not `Name`.

**Comment by busches** [comment]
@ajeckmans thanks for that quick fix.

**Comment by ajeckmans** [comment]
@dennisdoomen There is also the issue of the docs all mentioning the "old" way and not the new. Is there a guideline on how to write the documentation?
