### ISSUE TITLE
ObjectAssertions does not contain a definition for 'NotContain' error after updating to luent Assertions 6.0.0

### ISSUE THREAD

**Issue by ms6073** [fluentassertions/fluentassertions#1650]
After upgrading from 5.10.3 to 6.0.0 , I immediately see numerous _ObjectAssertions does not contain a definition for__ errors for the Contain, NotBeEmpty. and NotContain CollectionAssertions. 

### Complete minimal example reproducing the issue
SimpleUnitTests.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.9.4" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.3" />
    <PackageReference Include="coverlet.collector" Version="3.0.2" />
  </ItemGroup>
</Project>
```

SimpleUnitTest.cs
```
namespace SimpleUnitTests
{
    [TestClass]
    public class SimpleUnitTest
    {
        [TestMethod]
        public void DebugShouldBeEmpty()
        {
            IEnumerable actual = new[] { 1, 2, 5, 8 };
            actual.Should().BeEmpty();
        }

        [TestMethod]
        public void DebugShouldContain()
        {
            IEnumerable actualList = new[] { "12345", "abcdef", "1aw2gh5f" };
            actualList.Should().Contain(new[] { "12345" });
        }

        [TestMethod]
        public void DebugShouldNotContain()
        {
            IEnumerable actualList = new[] { "12345", "abcdef", "1aw2gh5f" };
            actualList.Should().NotContain(new[] { "7890" });
        }
    }
```
### Expected behavior: 
The tests should be able to be executed and complete

### Actual behavior:
The tests cannot be run due to the prevalence of CS1061 errors.

Example:
CS1061	'ObjectAssertions' does not contain a definition for 'BeEmpty' and no accessible extension method 'BeEmpty' accepting a first argument of type 'ObjectAssertions' could be found (are you missing a using directive or an assembly reference?)

### Versions
• Which version of Fluent Assertions are you using?  Fluent Assertions v6.0.0
• Which .NET runtime and version are you targeting? .NET 5

**Comment by ms6073** [comment]
Additionally, as soon as I run Install-Package FluentAssertions -Version 5.10.3 from the Package Manager Console, the errors are removed, and tests can be executed normally.

**Comment by lg2de** [comment]
With V6 the support of non-generic IEnumerable has been removed. 

https://fluentassertions.com/upgradingtov6#collections

**Comment by ms6073** [comment]
Well I I thought I had perused the release notes for v6 pretty thoroughly, but obviously not. Thank you for the follow-up.
