### ISSUE TITLE
Migration guide to v6 is missing  breaking change Throw/ThrowAsync

### ISSUE THREAD

**Issue by myshon** [fluentassertions/fluentassertions#1652]
I'm upgrading FluentAssertions to v6 (good job!). In the previous version v5, I had a lot of tests like that 

```csharp
Func<Task> action = async () => await repository.CreateFile();
action .Should().Throw<FileAlreadyExists>();
```

However, after the upgrade I encountered builds errors, these tests need to be fixed 

```csharp
Func<Task> action = async () => await repository.CreateFile();
await action .Should().Throw<FileAlreadyExists>();
```

Of course, it's pretty easy to change. I only wonder, why this breaking change it's not mentioned in the migration guide https://fluentassertions.com/upgradingtov6 
It applies also to ThrowExactly, NotThrow etc.

**Comment by jnyrup** [comment]
Hi Szymon
Thanks for the kind words, we're also really glad to have it out.

Regarding your question, I think we simply forgot as we only started the migration guide later in the development process of v6.
Dennis did though mention it in his [blog post](https://www.continuousimprover.com/2021/08/fluent-assertions-v6.html) about v6.

But I agree that the migration guide should also mention the removal of blocking `Throw` for async delegates.

**Comment by dennisdoomen** [comment]
Added a small section on this to the migration guide.
