### ISSUE TITLE
Should().Throw does not catch the expected exception

### ISSUE THREAD

**Issue by laleluk** [fluentassertions/fluentassertions#1653]
Hey,

I upgraded the .NET Framework to 4.8 (previous 4.7.1) and the Nuget to v6.0.0 (previous v5.10.2), but now I'm encountering some strange behavior in one of my UnitTests:

```
[TestMethod]
public void Calculate_Null_Throws()
{
    //given
    byte[] array = null;

    //when
    array.Invoking(foo => foo.Calculate())
         .Should().Throw<ArgumentNullException>(); // then
}
```

The ArgumentNullException will be thrown like expected, but the '.Should()Throw<ArgumentNullException>()' does not catch the exception. This UnitTest already worked with version 5.10.2 (with the .NET Framework 4.7.1).

### Exception Message:

```
Test method FluentAssertionsTests.FluentAssertionsTest.SubArray_Null_Throws threw exception: 
System.ArgumentNullException: Value cannot be null.
Parameter name: subject
    at FluentAssertions.AssertionExtensions.Invoking[T,TResult](T subject, Func`2 action)
```

### Versions

.NET Framework 4.8
FluentAssertions 6.0.0

### Additional Information

Created a short solution to test the behavior:
[FluentAssertionsTests.zip](https://github.com/fluentassertions/fluentassertions/files/7014103/FluentAssertionsTests.zip)

Keep up your great work!

**Comment by dennisdoomen** [comment]
You're calling `Invoking` on a `null`, so that should never worked in the first place. In 6.0, we added some additional assertions to make sure these mistakes are not made again.

**Comment by eNeRGy164** [comment]
I think what you want to do is:

```csharp
[TestMethod]
public void Calculate_Null_Throws()
{
    //given
    byte[] array = null;

    //when
    Action act = () => array.Calculate();

    act.Should().Throw<ArgumentNullException>(); // then
}
```

**Comment by laleluk** [comment]
hmm ... I still wonder why the catch does not work, due to the fact that the null check from Invoke() is throwing an ArgumentNullException and not the .NET Framework.

Anyway, I'm currently testing your code and I guess this should be not part of a UnitTest.
So I go with the solution from @eNeRGy164. 
Thank you guys!

**Comment by dennisdoomen** [comment]
> hmm ... I still wonder why the catch does not work, due to the fact that the null check from Invoke() is throwing an ArgumentNullException and not the .NET Framework.

Because `Invoking` doesn't do much other than build a `Func` that will invoke your code and pass it to `Should().Throw`. But in v6, before we build that func, we first assert you didn't pass `null`.

**Comment by laleluk** [comment]
I see! Sorry I missed that. 
Thanks for the explanation!
