### ISSUE TITLE
InvalidOperationException when asserting equivalent with default instance of ImmutableArray<T>

### ISSUE THREAD

**Issue by Tragedian** [fluentassertions/fluentassertions#1655]
### Description

When comparing an `ImmutableArray<T>` against its default value using `Should().BeEquivalentTo(...)` an exception is thrown by the attempt to examine the array as a collection.

### Complete minimal example reproducing the issue

The following shows how to produce the error:

```csharp
default(ImmutableArray<string>).Should().BeEquivalentTo(default(ImmutableArray<string>));
```

Comparing empty arrays does not cause the issue:

```csharp
ImmutableArray<string>.Empty.Should().BeEquivalentTo(ImmutableArray<string>.Empty);
```

### Expected behavior:

I expect the comparison to succeed without an exception. In the case that a non-default array is compared against a default array, I expect an exception to be thrown highlighting the difference between expected and actual values.

### Actual behavior:

The following exception is thrown:
```
Message: 
  System.InvalidOperationException : This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.

Stack Trace: 
  ImmutableArray`1.ThrowInvalidOperationIfNotInitialized()
  ICollection<T>.get_Count()
  EnumerableHelpers.ToArray[T](IEnumerable`1 source)
  GenericEnumerableEquivalencyStep.HandleImpl[T](EnumerableEquivalencyValidator validator, Object[] subject, IEnumerable`1 expectation)
  --- End of stack trace from previous location ---
  GenericEnumerableEquivalencyStep.Handle(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator nestedValidator)
  EquivalencyValidator.RunStepsUntilEquivalencyIsProven(Comparands comparands, IEquivalencyValidationContext context)
  EquivalencyValidator.RecursivelyAssertEquality(Comparands comparands, IEquivalencyValidationContext context)
  EquivalencyValidator.AssertEquality(Comparands comparands, EquivalencyValidationContext context)
  StringCollectionAssertions`2.BeEquivalentTo(IEnumerable`1 expectation, Func`2 config, String because, Object[] becauseArgs)
  StringCollectionAssertions`2.BeEquivalentTo(IEnumerable`1 expectation, String because, Object[] becauseArgs)
```

### Versions

Fluent Assertions version: 6.0.0
.NET Target version: net5.0

**Comment by eNeRGy164** [comment]
The message is quite clear?

> This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array

you are now doing

```csharp
null.Should().BeEquivalentTo(null);
```

**Comment by dennisdoomen** [comment]
So an `ImmutableArray` implements `ICollection<T>`, but throws on `Count`. Sounds like a violation of the Liskov Substitution Principle... Regardless, I agree we need to support it.

**Comment by Tragedian** [comment]
`ImmutableArray<T>` has a very unpleasant implementation of its `default` state. I'd love to understand the reasoning behind why the default value doesn't have empty-collection behaviours.

The expectation seems to be that consumers should check the `ImmutableArray<T>.IsDefault` or `IsDefaultOrEmpty` properties before operating on an instance.

**Comment by Tragedian** [comment]
> _removed wrong assumption_
> 
> Ok, looking further on your stack trace it seems the code tries to do a `Count()` on the array, so it should have a special case where it's not `null` but also not `initialized`.

`ImmutableArray<T>` is a value-type; it cannot be `null`. It implements its own `default` value handling which includes throwing an exception if you invoke any collection operations on a default value.

**Comment by eNeRGy164** [comment]
I was looking into this, but it looks like adding code that checks for `ImmutableArray` would also add a dependency FluentAssertions for .NET 4.7 and .NET Standard 2.0 and 2.1

Would that be acceptable?

**Comment by dennisdoomen** [comment]
No, we should not do that. But maybe we should be smart enough to handle "default" instances of types in general

**Comment by eNeRGy164** [comment]
Checking if the object is a `ValueType` and has a property `IsDefault` would be possible, and I think the first check should not add too much performance cost

**Comment by dennisdoomen** [comment]
And maybe replace that object with an empty collection or something like that.

**Comment by eNeRGy164** [comment]
In `EnumerableEquivalencyStep.cs` I tried the replace
```csharp
internal static object[] ToArray(object value)
{
    return value is not null ? ((IEnumerable)value).Cast<object>().ToArray() : null;
}
```

As `Subject` boxes the valuetype, it's hard to do a comparison (without also having a reference to `ImmutableArray<T>`) as al comparers will compare the value a an object, not the actual valuetype.

I tried with dynamic, which works in the debugger:

```csharp
internal static object[] ToArray(object value)
{
    return value is not null && !IsDefaultImmutableArray(value) ? ((IEnumerable)value).Cast<object>().ToArray() : null;
}

private static bool IsDefaultImmutableArray(object value)
{
    Type type = value.GetType();
    if (!type.IsValueType)
    {
        return false;
    }

    var boxedValueType = (dynamic)value;

    return type.GetMember("IsDefault").Length > 0 && boxedValueType["IsDefault"] == true;
}
```

But the net47 project doesn't want to compile this with the message
> CS0656	Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'	FluentAssertions (net47)

Which I can't seem to solve

**Comment by dennisdoomen** [comment]
What about catching the exception and doing something smart?

**Comment by eNeRGy164** [comment]
This does the trick:

```csharp
internal static object[] ToArray(object value)
{
    if (value is null)
    {
        return null;
    }

    try
    {
        return ((IEnumerable)value).Cast<object>().ToArray();
    }
    catch (InvalidOperationException)
    {
        // This is probably a default ImmutableArray<T>
        return new object[0];
    }
}
```

**Comment by Tragedian** [comment]
Would it be worth looking at the type before catching the exception? I can see enumerators throwing `InvalidOperationException` for other reasons than being a default `ImutableArray<T>`.

```
catch (InvalidOperationException) when (value.GetType().Name.StartsWith("ImutableArray`"))
{
    // This is probably a default ImmutableArray<T>
    return Array.Empty<object>();
}
```

**Comment by eNeRGy164** [comment]
Yeah, was already thinking about that, toke it in.

**Comment by dennisdoomen** [comment]
> catch (InvalidOperationException) when (value.GetType().Name.StartsWith("ImutableArray`"))

Hmm, on second thought, maybe we should just bite the bullet and accept taking a dependency on the `System.Collections.Immutable` package.

**Comment by dennisdoomen** [comment]
True, but in this case, it's kind of basic functionality.

**Comment by eNeRGy164** [comment]
I have a new approach in this branch: https://github.com/eNeRGy164/fluentassertions/pull/1/files

Please take a look at it if this is more the way to go.

**Comment by dennisdoomen** [comment]
Oh nice. Wondering what @jnyrup thinks of this.

**Comment by eNeRGy164** [comment]
I'm also very interested in @jnyrup's thought on this.

**Comment by jnyrup** [comment]
Sorry for the silence, needed to chew on the aspects of this.

I'm a little hesitant in adding `System.Collections.Immutable` as a dependency - see e.g #1470.
_If_ we do, we should probably depend on 1.5.0 due to its more versatile target frameworks.
But I'm quite satisfied with how few dependencies we have with 6.0.

I'm also wondering if we by https://github.com/eNeRGy164/fluentassertions/pull/1/files try to fix a problem that doesn't exist in _practice_.

I'm really fine with the minimal approach in #1668 to account for `ImmutableArray<T>` breaking Liskov Substitution Principle.

**Comment by dennisdoomen** [comment]
If @eNeRGy164 promises he tests the NuGet package against every supported target version I'm quite okay with it.

**Comment by jnyrup** [comment]
I have not worked with `ImmutableArray<T>` before, but reading a bit up on it, it seems the non-initialized state is a non-desired technical limitation and even https://github.com/dotnet/runtime/issues/34096 suggest to prefer `ImmutableArray<T>.Empty` over `new ImmutableArray<T>()`.

I might not see the full picture, but what issues do we solve versus the complexity (dependency+code) we add?
E.g. in #1141 we deemed "validating all the ways to iterate an enumerable" too specific to fit in FA.

**Comment by dennisdoomen** [comment]
I see increasing usage of `ImmutableArray<T>` as a way to replace returning `IEnumerable<T>` to emphasize an object returns something that should not be touched. So I do see the need for this.

**Comment by Tragedian** [comment]
Default values of `ImmutableArray<T>` are absolutely an undesired state, something I wouldn't want to see if my code under ideal circumstances. The problem is that the current failure mode in FA doesn't help highlight where the bad value is in the system. I have a significant graph to make comparisons of, so not knowing the faulty branch is problematic.

Whether that means there needs to be a small tweak to overcome its Liskov Substitution violation, or a dedicated comparer to account for default value comparisons (i.e. that `new ImmutableArray<T>()` is not equivalent to `ImmutableArray<T>.Empty`) I couldn't say.

**Comment by eNeRGy164** [comment]
So, in which direction do we want to take this?

a) a "hack" so at least there is no exception thrown when using `ImmutableArray<T>`
b) make `ImmutableArray<T>` a first class citizen in FA which can have its own assertions/handling

**Comment by dennisdoomen** [comment]
Let's remain on a conservative path and accept the hack for now.
