### ISSUE TITLE
ObjectAssertions.Be no longer uses IComparable<T> and does not use IEquatable<T>

### ISSUE THREAD

**Issue by kwbauer** [fluentassertions/fluentassertions#1675]
### Description

Version 6.0.0 introduced an undocumented breaking change from version 5.10.3.  In older versions, `actual.Should().Be(expected)` would pass when actual and expected were of the same type and that type implemented `IComparable<T>` and the `CompareTo` implementation returned 0. Tests that relied on this now fail in versions 6.0.0 and 6.1.0.

Interestingly, NUnit's `Assert.AreEqual` fails to pass in this situation as well but it does pass if the class implements `IEquatable<T>` and the Equals implementation returns true.

Neither the older or newer versions of FluentAssertions will pass `Should().Be()` for the `IEquatable<T>` scenario.

### Complete minimal example reproducing the issue

```cs
using FluentAssertions;
using NUnit.Framework;

namespace FluentAssertionBug
{
    public class ClassToBeComparedWithIComparable : IComparable<ClassToBeComparedWithIComparable>
    {
        public string Id { get; set; }
        public int Value { get; set; }

        public int CompareTo(ClassToBeComparedWithIComparable other)
        {
            var c = string.Compare(Id, other.Id, StringComparison.Ordinal);


            return c != 0 ? c : Value.CompareTo(other.Value);
        }
    }

    public class ClassToBeComparedWithIEquatable : IEquatable<ClassToBeComparedWithIEquatable>
    {
        public string Id { get; set; }
        public int Value { get; set; }

        public bool Equals(ClassToBeComparedWithIEquatable other)
        {
            if (other == null)
                return false;

            return Id.Equals(other.Id) && Value.Equals(other.Value);
        }
    }

    [TestFixture]
    public class Tests
    {
        [Test]
        public void GivenTwoIComparablesThatHaveIdenticalValues_ShouldBe_ShouldPass_WillFailInNewerVersions()
        {
            var value1 = new ClassToBeComparedWithIComparable { Id = "One", Value = 1 };
            var value2 = new ClassToBeComparedWithIComparable { Id = "One", Value = 1 };

            value1.Should().Be(value2);
        }

        [Test]
        public void GivenTwoIEquatablesThatHaveIdenticalValues_Equals_ShouldPass()
        {
            var value1 = new ClassToBeComparedWithIEquatable { Id = "One", Value = 1 };
            var value2 = new ClassToBeComparedWithIEquatable { Id = "One", Value = 1 };

            if (value1.Equals(value2))
                Assert.Pass();

            Assert.Fail();
        }

        [Test]
        public void GivenTwoIEquatablesThatHaveIdenticalValues_AssertAreEqual_ShouldPass()
        {
            var value1 = new ClassToBeComparedWithIEquatable { Id = "One", Value = 1 };
            var value2 = new ClassToBeComparedWithIEquatable { Id = "One", Value = 1 };

            Assert.AreEqual(value2, value1);
        }
    }
}
```

### Expected behavior:

I expect the breaking change for the `IComparable<T>` scenario to be documented.
I expect `Should().Be()` to honor the `IEquatable<T>` implementation when determining if 2 objects are equal.

### Actual behavior:

Neither the 6.0.0 nor the 6.1.0 documentation mention that Should().Be() no longer honors the `IComparable<T>` implementation when determining equality.

`Should().Be()` does not honor the `IEquatable<T>` implementation when determining equality.

### Versions

* I upgraded from FluentAssertion 5.10.3 to 6.1.0. (I also tried using 6.0.0 to determine when the break first occurred.)
* I am using .Net Core 3.1
* I am using NUnit 3.13.2 as my testing suite.

**Comment by dennisdoomen** [comment]
Thanks for reporting this. Are you sure you're not mixing up versions? Because v5 _only_ relied on `object.Equals`, and v6 now uses `EqualityComparer<T>.Default.Equals`, which _does_ support `IEquatable<T>`.

**Comment by kwbauer** [comment]
I am not mixing up versions. Here is a zip of the solution with 3 different unit test projects. One each using versions 5.10.3, 6.0.0, and 6.1.0 of FluentAssertions. All 3 unit test projects reference the same code file containing the tests. This clearly illustrates that FluentAssertions do not honor implementations of IEquatable in versions 5.10.3, 6.0.0, nor 6.1.0.
[FluentAssertionBug.zip](https://github.com/fluentassertions/fluentassertions/files/7078002/FluentAssertionBug.zip)

**Comment by kwbauer** [comment]
I was able to confirm that the IEquatable<T>.Equals(T other) implementation is not directly used. It is only used if object.Equals(object other) is overriden to call the IEquatable implementation. While a good thing to do, this is not required and it means that your code is not directly utilizing the IEquatable interface.

I suspect that this code is not doing what the author intended as it is not entering the if-block to use the default EqualityComparer<T> (which would directly use the IEquatable implementation).

https://github.com/fluentassertions/fluentassertions/blob/1848385eec9a4558ff2ec114396015733d09ac48/Src/FluentAssertions/Common/ObjectExtensions.cs#L17-L23

**Comment by kwbauer** [comment]
I added these lines before https://github.com/fluentassertions/fluentassertions/blob/1848385eec9a4558ff2ec114396015733d09ac48/Tests/FluentAssertions.Specs/Primitives/ObjectAssertionSpecs.cs#L19-L21. When the overriden Equal(object) uses ReferenceEquals (the default implementation), the test fails. When it calls through to the IEquatable implementation, it succeeds.

        ```
public class ClassImplementsIEquatable : IEquatable<ClassImplementsIEquatable>
        {
            public string Id { get; set; }

            public int Value { get; set; }

            public bool Equals(ClassImplementsIEquatable other)
            {
                if (other == null)
                {
                    return false;
                }

                return Id.Equals(other.Id, StringComparison.Ordinal) && Value.Equals(other.Value);
            }

            public override bool Equals(object other)
            {
                return ReferenceEquals(this, other);

                //if (other is ClassImplementsIEquatable typed)
                //{
                //    return Equals(typed);
                //}

                //return false;
            }

            public override int GetHashCode()
            {
                int hash = 17;

                hash *= 23;
                hash += Id.GetHashCode();

                hash *= 23;
                hash += Value.GetHashCode();

                return hash;
            }
        }

        [Fact]
        public void When_two_equal_IEquatable_object_are_expected_to_be_equal_it_should_not_fail()
        {
            // Arrange
            var someObject = new ClassImplementsIEquatable { Id = "One", Value = 1 };
            var equalObject = new ClassImplementsIEquatable { Id = "One", Value = 1 };

            // Act / Assert
            someObject.Should().Be(equalObject);
        }
```

**Comment by kwbauer** [comment]
After more digging, that if-statement fails because TSubject for the ObjectAssertions is System.Object while ObjectExtensions.GetComparer<TSubject> expects it to be the type of the object passed to Should(this object objectValue).

https://github.com/fluentassertions/fluentassertions/blob/1848385eec9a4558ff2ec114396015733d09ac48/Src/FluentAssertions/Primitives/ObjectAssertions.cs#L12

https://github.com/fluentassertions/fluentassertions/blob/1848385eec9a4558ff2ec114396015733d09ac48/Src/FluentAssertions/AssertionExtensions.cs#L280-L283

**Comment by dennisdoomen** [comment]
> This clearly illustrates that FluentAssertions do not honor implementations of IEquatable in versions 5.10.3, 6.0.0, nor 6.1.0.

So even v5 doesn't honor `IEquatable`, right? Because that's what I was expecting.

**Comment by dennisdoomen** [comment]
Alright. Did some digging myself. We're both right, but that's not going to help you. The most simple version of `Be` acts on instances of `object`, which causes `ObjectExtensions.GetComparer` to use `EqualityComparer<object>.Default.Equals`, which falls back to `object.Equals`. This is not something we can improve without restoring to some ugly reflection. However, IMO, it's not a bug, but merely a potential performance improvement. In fact, even [CA1067](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1067) tells you override `Equals` in a consistent way with `IEquatable`.

**Comment by jnyrup** [comment]
The _main_ benefit of `Equals(T)` over `Equals(object)` is avoiding boxing value types.
As `Should().Be(object)` already boxes the any value type, the remaining performance is avoiding a type check, which should be negligible.
I have a hard time imagining that we should take inconsistent implementations of `Equals(T)` and `Equals(object)` into account.

The change in using `Equals` over `CompareTo` for `IComparable<T>` changed in #1177 but it seems we missed to mentioning it any where.
You can use `BeRankedEquallyTo` to compare the objects using `CompareTo`.

**Comment by jnyrup** [comment]
For vNext it [seems](https://github.com/jnyrup/fluentassertions/tree/GenericIComparableAssertions) we can make `ComparableAssertions` take an `T : IComparable<T>` instead of an `IComparable<T>` which would let us use `EqualityComparer<T>.Default.Equals(T, T)` instead of `object.Equals(object)` for `[Not]Be`.
