### ISSUE TITLE
Update from 5.10.3 to 6.1.0 brings a compiler error for Should().Throw<>()

### ISSUE THREAD

**Issue by epicbugs** [fluentassertions/fluentassertions#1676]
### Description

When I update FluentAssertions from version 5.10.3 to version 6.0.0/6.1.0 on .NET Core 3.1 test project then I get compiler error:

`Error	CS1061	'NonGenericAsyncFunctionAssertions' does not contain a definition for 'Throw' and no accessible extension method 'Throw' accepting a first argument of type 'NonGenericAsyncFunctionAssertions' could be found (are you missing a using directive or an assembly reference?)`

### Complete minimal example reproducing the issue

```csharp
// Arrange
Exception ex = new ArgumentOutOfRangeException();

// Act
Func<Task> action = async () => await Task.FromException(ex);
            
// Assert
action.Should().Throw<ArgumentOutOfRangeException>();
```

### Expected behavior:

Unit test should compile and run successfully.

### Actual behavior:

Compiler error CS1061

### Versions

* Which version of Fluent Assertions are you using? 6.1.0
* Which .NET runtime and version are you targeting? .NET Core 3.1

**Comment by dennisdoomen** [comment]
That's a breaking change that was documented in the [release notes](https://www.continuousimprover.com/2021/08/fluent-assertions-v6.html), the [blog post](https://www.continuousimprover.com/2021/08/fluent-assertions-v6.html) and the [upgrade guide](https://fluentassertions.com/upgradingtov6#asserting-exceptions-asynchronously).

**Comment by epicbugs** [comment]
Should have realized 🤦‍♂️
Thanks for the quick reply!

**Comment by dennisdoomen** [comment]
No worries.
