### ISSUE TITLE
[Feature] - Count XDocument nodes

### ISSUE THREAD

**Issue by ITaluone** [fluentassertions/fluentassertions#1681]
**Before you file a bug, have you:**

* Tried upgrading to newest version of Fluent Assertions, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/fluentassertions/fluentassertions/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Read the [documentation](https://fluentassertions.com/introduction/)?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/questions/tagged/fluent-assertions?mixed=1).

### Description

It would be great if you can count occurrences of XML nodes. 
Reason is: According to the openTRANS standard various nodes **have to** be available exactly once.

### Complete minimal example reproducing the issue

None, because the method does not exist :)

### Expected behavior:

Intellisense shows something like: 

- `xDoc.Should().HaveElement("element").**Single()**`
or
- `xDoc.Should().HaveElement("element").**And.HaveCount(3)**`

### Versions

* Which version of Fluent Assertions are you using? 6.1.0
* Which .NET runtime and version are you targeting? .NET Core 3.1

**Comment by ABergBN** [comment]
Which variants would you prefer? I've started implementing: 
`document.Should().HaveElement("child").Which.Should().BeSingle();`
and/or 
`document.Should().HaveElement("child").Which.Should().HaveCount(5);`

**Comment by lg2de** [comment]
`HaveElement` sounds to me like "single" at all.
How about `document.Should().HaveElements("child")...`?

**Comment by dennisdoomen** [comment]
Good point. `HaveElement` will be satisfied if the `XDocument` has one _or more_ elements with that name. So we probably need either a `HaveSingleElement` or ensure that chaining `Which` after `HaveElement` throws if there's more than one element with that name.

**Comment by ITaluone** [comment]
> Which variants would you prefer? I've started implementing:
> `document.Should().HaveElement("child").Which.Should().BeSingle();`
> and/or
> `document.Should().HaveElement("child").Which.Should().HaveCount(5);`

That sounds cool already :)

> HaveElement sounds to me like "single" at all.

Yepp true, but: 
> HaveElement will be satisfied if the XDocument has one or **_more_** elements

That "more" is the thing..
