### ISSUE TITLE
Should().MatchRegex() should allow specifying RegexOptions

### ISSUE THREAD

**Issue by drauch** [fluentassertions/fluentassertions#1682]
`Should().MatchRegex()` should allow specifying `RegexOptions` so I can set `RegexOptions.Singleline`.

Best regards,
D.R.

**Comment by jnyrup** [comment]
Have you seen that v6.0 supports taking a `Regex` instance instead of a pattern?

```cs
"subject".Should().MatchRegex(new Regex("pattern", RegexOptions.Singleline));
```

**Comment by drauch** [comment]
Uh nice, no I haven't seen it, we're still using 5.x, I will initiate updating the library at our side. Thanks!

Best regards,
D.R.
