### ISSUE TITLE
Remove Async postfix from assertions of asynchronous operations

### ISSUE THREAD

**Issue by lg2de** [fluentassertions/fluentassertions#1685]
As discussed in #1490 I propose to remove the `Async` postfix of assertions like `CompleteWithinAsync` to be more fluent.

It could not be completed for v6 and should be planned/discussed for v7 in future.

To detect breaking tests while migration from v5 to v7 I propose adding an analyzer which is creating compiler error in case an asynchronous assertion is not awaited.

**Comment by mikkelbu** [comment]
Do I read this issue correctly that you will remove the Async postfix introduced in version 6 ?

I was considering supplying a PR to Polly to bump their usage of FluentAssertions from 5.10.3 to the latest version - see e.g. App-vNext/Polly#913 for the issue. But it seems like one should wait on v7 to avoid adding `Async` in several hundred places and then later removing them again.

**Comment by dennisdoomen** [comment]
> I don't use fluentassertions myself but from nuget it seems that there are major releases every 2-3 years, is this still the expectation for version 7?

Yes, because we try to have as little breaking changes as possible. And nothing is planned right now.

**Comment by mikkelbu** [comment]
Thanks for the swift answer @dennisdoomen 👍

**Comment by lg2de** [comment]
@dennisdoomen , @jnyrup , now, I would like to start the discussion whether removing the postfix as described.

**Comment by dennisdoomen** [comment]
So if I understand the rationale, I can see one advantage and one disadvantage. The advantage is that it removes the `Async` postfix and makes the API a bit more fluent. But the disadvantage is that people need to remember to `await` the invocation. Right?

**Comment by lg2de** [comment]
Yes, correct. 
But, this is true for the current version (with suffix), too. I remember some issues/discussions wondering the behavior while `await` was absent. 

As stated before, I think we can (I would like to) create an analyzer if such is not already existing.

**Comment by dennisdoomen** [comment]
Me and @jnyrup had some backchannel discussions today and we agreed that we want to keep the `Async` prefix. We don't think the additional problems this will cause where people forget to `await` the invocation is worth a slightly more fluent API. 

I know you take this topic seriously, and we value your opinions a lot, but this is our final decision. I hope you respect that decision.
