### ISSUE TITLE
Breaking change in ContainInOrder when type object is involved

### ISSUE THREAD

**Issue by luiscantero** [fluentassertions/fluentassertions#1694]
In a project, we had code like this:
```cs
var collection = new List<object> { 1, 2, 5, 8 };

collection.Should().NotBeEmpty()
    .And.HaveCount(4)
    .And.ContainInOrder(new int[] { 2, 5 })
    .And.ContainItemsAssignableTo<int>();
```

Using 5.10.3 this worked fine. After upgrading to 6.1.0, we got the following error:
```
FluentAssertions.Execution.AssertionFailedException: 'Expected collection {1, 2, 5, 8} to contain items {{2, 5}} in order, but {2, 5} (index 0) did not appear (in the right order).'
```

I found no documentation or issue related to this problem. To fix it I had to change the expected collection to `new object[] { 2, 5 }`

Environment:
.NET Core 3.1, VS2019, Windows.

**Comment by jnyrup** [comment]
This is probably a side-effect of removing support for non-generic collections.
[Release notes ]https://github.com/fluentassertions/fluentassertions/blob/master/docs/_pages/releases.md#600, but it's "covered" under 
> Removed support for non-generic collections, see the Migration Guide for more details - #1529.

The compiler now matches the entire `int[]` as a single element of type `object` in `List<object>`.

**Comment by luiscantero** [comment]
The linked [Migration guide](https://github.com/fluentassertions/fluentassertions/blob/master/upgradingtov6#collections) (on the releases page) results in 404 for me.

**Comment by dennisdoomen** [comment]
https://fluentassertions.com/upgradingtov6

**Comment by dennisdoomen** [comment]
Is this still a real bug or just a misunderstanding?

**Comment by jnyrup** [comment]
There is no bug, to sum up:
V6 removed the support for non-generic collections.
In most cases this will show up as compile-time errors, but when using `object` the code might still compile, which turns it into an undesirable runtime error.
If we in v7 further reduce the usage of `params` we can probably improve by turning this into a compile time error.
