### ISSUE TITLE
CallerIdentification can't seem to handle `new[]{}`

### ISSUE THREAD

**Issue by mdentremont** [fluentassertions/fluentassertions#1695]
I noticed that the subject in our assertion output often had "root[..]", which seemed odd so whipped up a quick test case to validate my concerns. The following test fails (output is included), but using `new List<int> { 1, 2, 3}` instead of `new[]` works just fine.

I was on master SHA: b5b5ceb445035e5c461eec03dfa1a0c72049db5a

```c#
[Fact]
public void When_the_caller_is_bob()
{
    // Arrange
    var foo = new Foo();

    // Act
    Action act = () => foo.GetFoo(new[] { 1, 2, 3 }.Sum() + "")
        .Should()
        .BeNull();

    // Assert
    act.Should().Throw<XunitException>()
        .WithMessage("Expected foo.GetFoo(new[]{1,2,3}.Sum()+\"\") to be <null>*");
}
```

Output:
```
Expected exception message to match the equivalent of "Expected foo.GetFoo(new[]{1,2,3}.Sum()+"") to be <null>*", but "Expected object to be <null>, but found FluentAssertions.Specs.Execution.Foo
{
    Bar = "bar", 
    Field = "bar"
}." does not.
```

I can probably work on this in the future, but it might be a little as things are busy at the moment 👍.

**Comment by dennisdoomen** [comment]
Thanks for reporting this issue. Do you run your unit tests in debug mode? Because in a release build, caller identification doesn't work very well because of compiler optimizations.

**Comment by mdentremont** [comment]
@dennisdoomen Thanks for the quick response! 

I do run my tests in debug mode. Did you see my unit test? That test reproduces the issue (I ran it in your VS solution to confirm), and I also changed the `new[]{}` to `new List<int>{}` to confirm that List is handled properly but array isn't.

**Comment by dennisdoomen** [comment]
Ah, now I get it. So it's limitation of the current algorithm indeed. Sorry for misreading.

**Comment by jnyrup** [comment]
Dug a little into this.

`AddNonEmptySymbolParsingStrategy` is too greedy in stripping out whitespaces. 
It outputs `new List` as `newList`.
So `CallerIdentifier.UsesNewKeyword` fails to see that `newList` is actually `new List`.

`UsesNewKeyword` also cannot recognize the new target types `new() { 1 }`

```cs
public class Foo
{
    public object GetFoo(IEnumerable<int> _) => new();

    public object GetBar(List<int> _) => new();
}

[Fact]
public void Array_initializers_are_formatted_correctly()
{
    // Arrange
    var foo = new Foo();

    // Act
    Action act = () => foo.GetFoo(new[] { 1 })
        .Should()
        .BeNull();

    // Assert
    act.Should().Throw<XunitException>()
        .WithMessage("Expected foo.GetFoo(new[] { 1 }) to be <null>*");
}

[Fact]
public void List_initializers_are_formatted_correctly()
{
    // Arrange
    var foo = new Foo();

    // Act
    Action act = () => foo.GetFoo(new List<int> { 1 })
        .Should()
        .BeNull();

    // Assert
    act.Should().Throw<XunitException>()
        .WithMessage("Expected foo.GetFoo(new List<int> { 1 }) to be <null>*");
}

[Fact]
public void Target_type_initializers_are_formatted_correctly()
{
    // Arrange
    var foo = new Foo();

    // Act
    Action act = () => foo.GetBar(new() { 1 })
        .Should()
        .BeNull();

    // Assert
    act.Should().Throw<XunitException>()
        .WithMessage("Expected foo.GetBar(new() { 1 }) to be <null>*");
}
```

**Comment by dennisdoomen** [comment]
Imagine this:

`new[] { "one", "two", "three" }.Should().ContainInOrder(new[] { "three", "one" })`

What would you expect?

`Expected collection { "one", "two", "three" } to contain { "three", "one" } in order`?

or

`Expected new[] { "one", "two", "three" } { "one", "two", "three" } to contain { "three", "one" } in order`?

Because the current code favors the first.
