### ISSUE TITLE
Contain fails to find enum value in 6.1.0

### ISSUE THREAD

**Issue by luiscantero** [fluentassertions/fluentassertions#1697]
I'm unsure if this is a bug in FluentAssertions, and I went through the migration notes regarding Enums. I'm reporting it just in case. Note that the original code that lead to this issue is not as obvious as this one (e.g. the convertion to ushort) - this is just a simple repro.

With 5.10.3, the following code executed without problems:
```cs
var dict = new Dictionary<string, object>
{
    ["/EventId"] = "SomeId",
    ["/Severity"] = (ushort)Severity.High,
};

dict.Should().Contain(new Dictionary<string, object>
{
    ["/EventId"] = "SomeId",
    ["/Severity"] = Severity.High,
});
```

After upgrading to 6.1.0, we get this exception:
`FluentAssertions.Execution.AssertionFailedException: 'Expected dict to contain value Severity.High {value: 1} at key "/Severity", but found 1us.'`

To solve the issue, the following works:
```cs
dict.Should().Contain(new Dictionary<string, object>
{
    ["/EventId"] = "SomeId",
    ["/Severity"] = (int)Severity.High,
});
```

Environment:
.NET Core 3.1, VS2019, Windows.

**Comment by jnyrup** [comment]
This is by design and part of
https://github.com/fluentassertions/fluentassertions/blob/master/docs/_pages/releases.md#600
> Major overhaul on how enums are handled, see the [Migration Guide](https://fluentassertions.com/upgradingtov6#enums) for more details - [#1479](https://github.com/fluentassertions/fluentassertions/pull/1479).

Consider this case, which passed in 5.10.3

```cs
enum Severity
{
    Low,
    Medium,
    High
}

enum Color
{
    Red,
    Green,
    Blue
}

[TestMethod]
public void Lollostein()
{
    var subject = new Dictionary<string, object>
    {
        ["/EventId"] = "SomeId",
        ["/Severity"] = Severity.High,
    };

    var expected = new Dictionary<string, object>
    {
        ["/EventId"] = "SomeId",
        ["/Severity"] = Color.Blue,
    };

    subject.Should().Contain(expected);
}
```

To retain the old behavior your workaround seems fine to me, as it's more explicit in that you want to compare the underlying values.

**Comment by luiscantero** [comment]
Thanks for the info, pls feel free to close this issue.
