### ISSUE TITLE
Misleading error message: Expected items to be empty, but found {empty}.

### ISSUE THREAD

**Issue by dswisher** [fluentassertions/fluentassertions#1718]
### Description

Using `Should().BeEmpty()` on a non-materialized `IEnumerable` produces the misleading (or at least odd/unhelpful) error message:

`Expected items to be empty, but found {empty}.`

### Complete minimal example reproducing the issue

```csharp
[Fact]
public void BeEmptyTest()
{
    var stack = new Stack<long>();
    stack.Push(10);

    var items = GetIds(stack, 20);

    items.Should().BeEmpty();
}


private IEnumerable<long> GetIds(Stack<long> stack, long current)
{
    while (stack.Any() && (stack.Peek() < current))
    {
        var val = stack.Pop();

        yield return val;
    }
}
```

### Expected behavior:

I expected an error message similar to the following: `Expected items to be empty, but found {10L}.`

### Actual behavior:

The actual error message is: `Expected items to be empty, but found {empty}.`

### Versions

This is using FluentAssertions 6.1.0, on .NET Core 3.1.

### Additional Information

Materializing the enumerable (`GetIds(stack, 20).ToList()`) produces the expected message:

`Expected items to be empty, but found {10L}.`

**Comment by jnyrup** [comment]
Thanks for reporting this.
We seem to be inconsistent in whether we materialize `Subject` in `GenericCollectionAssertions.cs`.

For at least `BeEmpty` and `NotBeEmpty` we wanted to avoid enumerate the entire enumerable.
See e.g. #1691 about not counting the number of elements in an infinite sequence.

I'm not sure if we can fix this for the general case.

Here `HaveCount(1)` consumes `stack`, so `NotBeEmpty` fails.
```cs
[Fact]
public void CountAndNotBeEmpty()
{
    var stack = new Stack<long>();
    stack.Push(10);

    var items = GetIds(stack);

    items.Should().HaveCount(1)
        .And.NotBeEmpty();
}
```

This also reveals more realistic examples, that produces false negatives.

```cs
[Fact]
public void Contain()
{
    var stack = new Stack<long>();
    stack.Push(10);

    var items = GetIds(stack);

    items.Should().Contain(e => e == 10)
        .Which.Should().Be(10);
}

[Fact]
public void Satisfy()
{
    var stack = new Stack<long>();
    stack.Push(10);

    var items = GetIds(stack);

    items.Should().Satisfy(e => e == 10);
}

[Fact]
public void SatisfyRespectively()
{
    var stack = new Stack<long>();
    stack.Push(10);

    var items = GetIds(stack);

    items.Should().SatisfyRespectively(e => e.Should().Be(10));
}

[Fact]
public void Predecessor()
{
    var stack = new Stack<long>();
    stack.Push(10);

    var items = GetIds(stack);

    items.Should().HaveElementPreceding(10, 20);
}

[Fact]
public void Succeeding()
{
    var stack = new Stack<long>();
    stack.Push(10);

    var items = GetIds(stack);

    items.Should().HaveElementSucceeding(10, 20);
}
```

**Comment by dennisdoomen** [comment]
The problem is not even that the collection in the report isn't materialized yet. The problem is that you can only materialize it once. So there's no sensible way to resolve this properly. As @jnyrup says, if we would try to fully materialize it before we continue our internal assertions, we would run in other problems.
