### ISSUE TITLE
Feature Request: Assert Collection not contains Element. “NotContainEquivalentOf”

### ISSUE THREAD

**Issue by niksanla2** [fluentassertions/fluentassertions#1727]
based on https://github.com/fluentassertions/fluentassertions/issues/584
Now we need method `NotContainEquivalentOf`.

**Comment by iliashkolyar** [comment]
@jnyrup Isn't this method [already exist](https://github.com/fluentassertions/fluentassertions/blob/master/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs#L2131)?

**Comment by jnyrup** [comment]
Thanks @iliashkolyar 

This issue duplicates #1287 which was implemented in #1318 and released with 6.0.0
