### ISSUE TITLE
Modify `HaveCount` report message order: start with items found and expected.

### ISSUE THREAD

**Issue by obiwanjacobi** [fluentassertions/fluentassertions#1735]
Please modify the order of the report for failing a `Should().HaveCount()` on a collection, by starting with the actual number of items found and expected before dumping the object's contents.

**Comment by dennisdoomen** [comment]
Some of the other overloads of `HaveCount` don't include the entire collection, so maybe we should do the same here.

**Comment by iliashkolyar** [comment]
@dennisdoomen This can be closed now.
