### ISSUE TITLE
[Feature] - dynamic assertions

### ISSUE THREAD

**Issue by ITaluone** [fluentassertions/fluentassertions#1738]
**Before you file a bug, have you:**

* Tried upgrading to newest version of Fluent Assertions, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/fluentassertions/fluentassertions/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Read the [documentation](https://fluentassertions.com/introduction/)?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/questions/tagged/fluent-assertions?mixed=1).

### Description
It would be great if asserting `dynamic` types could work. Especially `dynamicObj.Should().BeAssignableTo<MyClass>();` would be perfect (inclusive dealing with a `MyClass`-object afterwards).

### Expected behavior:

```csharp
dynamic obj = MaybeAnAPICallWhichReturnsDynamic();

obj.Should()
    .BeAssignableTo<MyClass>()
    .Which
    ....
```

### Actual behavior:

Test fails with "MyClass does not contain a definition for 'Should'"

### Versions

* Which version of Fluent Assertions are you using? 6.2.0
* Which .NET runtime and version are you targeting?  .NET Core 3.1.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jnyrup** [comment]
C# does not support extension methods for dynamic types.
See e.g. previous issues: #234 #473 #1493

As a workaround you should be able to cast `obj` to `object`.

**Comment by ITaluone** [comment]
Ahh.. thanks for this hint :)

I will check this..

**Comment by kelps** [comment]
Just curious: is it possible to test equivalence to a dynamic object?

I want to create custom assertions that will be defined by a configuration. I intend to create a dynamic object from that configuration and use BeEquivalentTo to validate: 

```csharp
myobject.Should().RepresentData(mydata, myconfig);
```

mydata will be the data I'm comparing to and myconfig the configuration that will be used to create a dynamic object with that data to be used in the equivalence comparison.

This is to test the correctness of some data translations between formats in an app (serialization and specially deserialization of complex structures that don't map directly with the target objects). The data could be in different formats but same target object, so different configurations to map the test.

**Comment by dennisdoomen** [comment]
No, C# doesn't allow adding extension methods to `dynamic` methods.

**Comment by kelps** [comment]
I didn't intend to add the extension to a dynamic. The main object isn't dynamic in my example. I intended to pass a dynamic as parameter to BeEquivalentTo (inside my custom assertion), but the main object is a real reference type, that would be compared to a dynamic, instead of an anonymous. That should be possible...

**Comment by dennisdoomen** [comment]
Yes, you can pass in a `dynamic` object as the expectation. I've just tried that.
