### ISSUE TITLE
Very easy to misuse `ThrowAsync` in a sync test

### ISSUE THREAD

**Issue by lonix1** [fluentassertions/fluentassertions#1746]
### Description
The API for asserting exceptions in async code is VERY easy to misuse. Such tests would pass, but in fact should fail.

The problem is that `action.Should().ThrowAsync<Exception>()` should be awaited, but Roslyn doesn't know that and doesn't warn you. It's very easy to forget to put it in an async test, and to await it.

### Complete minimal example reproducing the issue

This test has a very subtle hard-to-detect bug. It should fail, but will actually pass.

````cs
[Fact]
public void sync_test_that_should_fail_but_will_pass()
{
    Func<Task> action = () => throw new ArgumentNullException("paramName");
    action.Should().ThrowAsync<ArgumentNullException>().WithParameterName("foo");     // "foo" is incorrect
}
````

This test fixes the bug. It should fail, and will fail.

````cs
[Fact]
public async Task async_test_that_should_fail_and_will_fail()
{
    Func<Task> action = () => throw new ArgumentNullException("paramName");
    await action.Should().ThrowAsync<ArgumentNullException>().WithParameterName("foo");
}
````

### Expected behavior:
Don't know! :smile:

Firstly please tell me, are you aware of an analyser (third party maybe?) that checks for this?

If not, there are two options:
- Maybe someone someday will write an analyser that detects this problem. That would be best. It would see that you don't `await` when calling a `ThrowsAsync`. I know nothing about Roslyn so regrettably cannot assist.
- Is it possible to detect this at runtime and log a warning to the console?

### Actual behavior:
Doesn't warn you.

### Versions
* Which version of Fluent Assertions are you using? 6.2.0
* Which .NET runtime and version are you targeting? .NET Core 5

### Additional Information
Maybe there's a different way to handle this problem - if so I'd appreciate the advice!

**Comment by jnyrup** [comment]
If your method is marked as `async` [CS4014](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs4014) detects non-awaited methods.

A post on SO suggested https://github.com/ykoksen/unused-task-warning
I haven't tried it, but I'ld like to hear your experiences.

**Comment by lonix1** [comment]
> If your method is marked as `async` [CS4014](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs4014) detects non-awaited methods.

True, but the problem is when you don't realise, and you write a sync test instead (like in my first example). Then the analyser won't be triggered.

> A post on SO suggested [ykoksen/unused-task-warning](https://github.com/ykoksen/unused-task-warning) I haven't tried it, but I'ld like to hear your experiences.

Thanks - I tried [ykoksen/unused-task-warning](https://github.com/ykoksen/unused-task-warning) as an analyser and it works well! Very clever little library.

Then I tried [semihokur/AsyncFixer](https://github.com/semihokur/AsyncFixer) which has some interesting analysers and that works well too!

I strongly recommend both of these libraries, I've already found lots of places to improve in my code. Thanks for sending me in the right direction.

**Comment by lonix1** [comment]
Amazing how many tests I was able to fix with [ykoksen/unused-task-warning](https://github.com/ykoksen/unused-task-warning).

@dennisdoomen, @jnyrup I realise this is out of scope, but if there is a way to bring attention to this issue in the docs, it would help other users, and that library is the perfect solution. Just a thought. My original assertion (pun intended) that it is a common problem still holds.

Thanks again @jnyrup.

**Comment by dennisdoomen** [comment]
Sounds like a nice section under https://fluentassertions.com/tips/ or my own blog.

**Comment by dennisdoomen** [comment]
Here you go... https://www.continuousimprover.com/2022/01/awaiting-the-awaitable
