### ISSUE TITLE
Dictionary should be able to match against anonymous type

### ISSUE THREAD

**Issue by mariusingjer** [fluentassertions/fluentassertions#1747]
It would be super nice if this was possible (demonstrated with Dapper):

```cs
connection.Execute("CREATE TEMP TABLE foo (bar text, zot text)");
connection.Execute("INSERT INTO foo values ('hello', 'world')");

var result = connection.Query("select * from foo").ToList()[0] as IDictionary<string, object>;
result.Should().BeEquivalentTo(new { bar = "hello", zot = "world" });
```

In other words: a dictionary should be equivalent to an anonymous type if the keys in the dictionary are properties on the anonymous type and the values are equivalent

**Comment by dennisdoomen** [comment]
You can already compare dictionaries like that. Doesn't this work?

**Comment by mariusingjer** [comment]
testing.stuff.Fluent_assertions.Foo:
    Outcome: Failed
    Error Message:
    Expectation has property result.bar that the other object does not have.
Expectation has property result.zot that the other object does not have.

**Comment by dennisdoomen** [comment]
Ah wait, now I understand you. I thought you were declaring an anonymous dictionary. But no, that would be quite hard to implement, and to be honest, quite a niche feature.
