### ISSUE TITLE
Parameterless `ContainSingle()` evaluates `IEnumerable`s twice

### ISSUE THREAD

**Issue by bert2** [fluentassertions/fluentassertions#1752]
### Description

The "parameterless" variant of `ContainSingle()` (without a predicate) evaluates `IEnumerable`s twice. This means any side-effects in the enumerable chain are executed twice which might lead to unexpected behavior.

### Complete minimal example reproducing the issue

https://dotnetfiddle.net/SFGRnc

```csharp
using System.Collections.Generic;
using System.Linq;
using FluentAssertions;

var d = new Dictionary<int, int>();
var xs = new[] { 1 }
    .Select(x => {
        d.Add(x, x); // crashes if executed twice
        return x;
    });

xs.Should().ContainSingle(); // crashes
//xs.Should().ContainSingle(_ => true); // does not crash
```

### Expected behavior:

`xs.Should().ContainSingle();` should not crash.

### Actual behavior:

`xs.Should().ContainSingle();` crashes.

### Versions

* FluentAssertions 6.2.0
* .NET 6.0

### Additional Information

The problem is that `ContainSingle()` uses `Count()` [here](https://github.com/fluentassertions/fluentassertions/blob/42f0f8f001cc8f291ae6d3c6efac1bf0da34100f/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs#L1008) and also `SingleOrDefault()` [here](https://github.com/fluentassertions/fluentassertions/blob/42f0f8f001cc8f291ae6d3c6efac1bf0da34100f/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs#L1016) without materializing the enumerable first.

The variant taking a predicate *does* materialize the enumerable first [here](https://github.com/fluentassertions/fluentassertions/blob/42f0f8f001cc8f291ae6d3c6efac1bf0da34100f/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs#L1058).

**Comment by dennisdoomen** [comment]
Thank you for reporting this. We would most definitely welcome a PR.

**Comment by bert2** [comment]
@dennisdoomen Yep, considered doing a PR but wasn't sure when I'd find the time to. Might be tomorrow or next week. So I wanted to report it at least.

**Comment by dennisdoomen** [comment]
No worries. Thanks for helping out.
