### ISSUE TITLE
Add assertions for net6.0 DateOnly/TimeOnly

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#1754]
### Description
.NET 6 introduced two new interesting time structures, [`DateOnly`](https://docs.microsoft.com/en-us/dotnet/api/system.dateonly) and [`TimeOnly`](https://docs.microsoft.com/en-us/dotnet/api/system.timeonly), see [this PR](https://github.com/dotnet/runtime/pull/50980).

Currently one can workaround the missing APIs in Fluent Assertions by converting `DateOnly` to `DateTime` and `TimeOnly` to `TimeSpan`.
```cs
new DateOnly().ToDateTime(TimeOnly.MinValue).Should();
new TimeOnly().ToTimeSpan().Should();
```

It would be nice if we had native APIs for asserting on `DateOnly` and `TimeOnly`.
I believe most assertions can simply be copied from the `[Nullable]DateTimeAssertions` and `[Nullable]SimpleTimeSpanAssertions`.

**Comment by julealgon** [comment]
@MullerWasHere can you confirm that you are working on this issue?

**Comment by MullerWasHere** [comment]
@julealgon I was working on it previously, haven't progressed much and I'm lacking time. If you want you can open a PR for it.

**Comment by iliashkolyar** [comment]
@jnyrup
Wondering regarding this one.
Shouldn't there be some prerequisite PR that adds `net6.0` support to all relevant projects and builds before being able to add support to these new time structures?

**Comment by jnyrup** [comment]
My initial thought was that adding .NET 6 could be done as part of adding these assertions, as there otherwise is no/little value in adding the extra target framework.

**Comment by iliashkolyar** [comment]
Well, I tried to do so but it wasn't that straightforward.
There are a several compilation flags that check the `TargetFramework` and Include/Remove dependencies accordingly (like `Common/NullConfigurationStore.cs`). These are spread out across multiple project, and the code analyzers are also configured via these flags.
There are several obsolete methods that fail compilation after the addition of the `net6.0` framework such as `BinaryFormatter.Serialize(Stream, object)` and `BinaryFormatter.Deserialize(Stream)` (https://aka.ms/binaryformatter).

I think that these changes are not in scope for this specific feature implementation and should probably be performed by someone with better familiarity with the project.
What do you think?

**Comment by jnyrup** [comment]
Oh, thought it would be more straight forward. 
I'll take a stab at adding .NET 6.

**Comment by jnyrup** [comment]
@iliashkolyar Fluent Assertions now also target net6.0.
