### ISSUE TITLE
Asserting exceptions on methods that return `ValueTask`

### ISSUE THREAD

**Issue by lonix1** [fluentassertions/fluentassertions#1763]
### Description

I've read the docs and searched past issues. I'm strugging to understand how to use the exception assertions for `ValueTask`.

### Complete minimal example reproducing the issue

I'd do this normally:

````cs
Func<Task> act = () => sut.Foo();
await act.Should().ThrowsAsync<InvalidOperationException>();
````

But if `Foo()` returns a `ValueTask` then I can't figure out the correct approach. I've tried all the various combinations in the [docs](www.fluentassertions.com/exceptions/) without success.

### Versions

* Which version of Fluent Assertions are you using? 6
* Which .NET runtime and version are you targeting? .net core 5

### Additional Information

At some point it might be useful to have a section with examples for `ValueTask` on that page I linked above.

**Comment by jnyrup** [comment]
(Currently) you have to convert the `ValueTask` into a regular `Task`.
Here are some ways to do that.

```cs
private class MyClass
{
    public ValueTask Foo() => ValueTask.FromException(new InvalidOperationException());
}

[Fact]
public async Task ValueTask0()
{
    var sut = new MyClass();

    Func<Task> act = () => sut.Foo().AsTask();
    await act.Should().ThrowAsync<InvalidOperationException>();
}

[Fact]
public async Task ValueTask1()
{
    var sut = new MyClass();

    Func<Task> act = async () => await sut.Foo();
    await act.Should().ThrowAsync<InvalidOperationException>();
}

[Fact]
public async Task ValueTask2()
{
    var sut = new MyClass();

    Func<Task> act = sut.Awaiting(e => e.Foo()); // calls ToTask() underneath.
    await act.Should().ThrowAsync<InvalidOperationException>();
}
```

**Comment by lonix1** [comment]
The `.AsTask()` option is the neatest for me, as it looks similar to the rest of my code and so is easier to remember. These examples would be great in the docs page for exceptions. Should I close for now?

Thanks and Happy New Year!

**Comment by dennisdoomen** [comment]
We would welcome a PR on the docs 😋
