### ISSUE TITLE
BeLowerCased() results in failing tests with only lower case characters. 

### ISSUE THREAD

**Issue by MEmanuelsson** [fluentassertions/fluentassertions#1768]
### Description

Just introduced using `BeLowerCased()` into one of our tests where we want to assert that a file path is lower case, but the result is not as expected. The response I get from the failing test is as follows:

```
Expected all characters in carFolderPath to be lower cased, but found "\files\f7f9de7c-90f4-46a3-9ceb-97af53f495e3\carfiles\abc123".
```

Perhaps the back slash is considered an upper case character in some way?

### Complete minimal example reproducing the issue

```cs
// Arrange 
var input = @"\test\with\lower\cased\string";

// Assert
input.Should().BeLowerCased();
```

### Expected behavior:

Test to pass

### Actual behavior:

Test fails

### Versions

Fluentassertions: 6.3.0
.NET 5

**Comment by dennisdoomen** [comment]
> Asserts that all characters in a string are in lower casing.

This is the description of the `BeLowerCased` method. So although you could debate that it could be smart enough to only check the letters in the string, it doesn't do that.

**Comment by MEmanuelsson** [comment]
OK, yes I would argue that characters that have no upper or lower case definition would be excluded from the algorithm or approved, that's at least how I thought it would work. But if that's not the way it works, then that's not the way it works. 

Maybe I'm the first who stumble across this problem but perhaps this can be made clearer in the description of the function, just a thought?

**Comment by dennisdoomen** [comment]
Hmm, I see your point. Wondering what @jnyrup thinks about that.

**Comment by jnyrup** [comment]
I see that we did consider this in https://github.com/fluentassertions/fluentassertions/pull/1357#issuecomment-660664866
The solution is to use `NotBeUpperCased` instead.

We probably should improve some documentation to stress that detail.

**Comment by MEmanuelsson** [comment]
`NotBeUpperCased` does the trick in this case, however not completely clear by the description of the function that this is how it works. 

I thought that anything that for instance had been `ToLower`:ed would also be asserted as ok by BeLowerCased. So for instance, a silly example: 
```
var test = "ABC123".ToLower();
test.Should().BeLowerCased(); // ==> true
```
Thanks for pointing me in the right direction regarding `NotBeUpperCased`

**Comment by dennisdoomen** [comment]
Let's keep it open so we update the documentation.
