### ISSUE TITLE
Proposal to exclude properties on a nested list

### ISSUE THREAD

**Issue by whymatter** [fluentassertions/fluentassertions#1771]
### Description

I propose a new feature to exclude certain properties of an object in a nested list. (see: https://stackoverflow.com/questions/22142576/how-to-use-exclude-in-fluentassertions-for-property-in-collection).

Currently, it is only possible to exclude certain properties of an entity at a specified index or to use string-based property path matching. The first one does not offer the required functionality, the latter one is complicated, lacks IntelliSense, and is not straightforward.

### Example

Given the following objects, I want to exclude the `Text` property from the nested collection.

```C#
// Arrange
var subject = new
{
    Level = new
    {
        Collection = new[]
        {
            new { Number = 1, Text = "Actual" },
            new { Number = 2, Text = "Actual" }
        }
    }
};

var expected = new
{
    Level = new
    {
        Collection = new[]
        {
            new { Number = 1, Text = "Expected" },
            new { Number = 2, Text = "Expected" }
        }
    }
};
```

### Proposals
```c#
const int MATCH_ALL = 0;

// Option 1: By using a magic constant (Excluding would have to detect if MATCH_ALL was used)
Action option1 = () => subject.Should().BeEquivalentTo(expected,
    options => options.Excluding(x => x.Level.Collection[MATCH_ALL].Text));

// Option 2: By using the .Select function on IEnumerable
Action option2 = () => subject.Should().BeEquivalentTo(expected,
    options => options.Excluding(x => x.Level.Collection.Select(l => l.Text)));

// Option 3: By using the Excluding function again
Action option3 = () => subject.Should().BeEquivalentTo(expected,
    options => options.Excluding(x => x.Level.Collection.Excluding(l => l.Text)));
```

I am also interested in implementing this 🙂

**Comment by dennisdoomen** [comment]
Hmm, I see what you are trying to accomplish, but I don't think any of those proposals look very intuitive.

**Comment by whymatter** [comment]
Okay, I tried to use a syntax familiar to some developers. Option 2 should be know to most EF 6 users (including tables to the result). We could also utilize the EF Core Syntax which could then look like this:

```c#
// Option 4: By using .ThenExclude (like .ThenInclude in EF Core)
Action option2 = () => subject.Should().BeEquivalentTo(expected,
    options => options.Excluding(x => x.Level.Collection).ThenExclude(x => x.Number));
```

Is there anything you think about?

(https://stackoverflow.com/questions/40319251/using-ef-core-theninclude-on-junction-tables)

**Comment by dennisdoomen** [comment]
I like that, but I'm wondering if we can make that possible. It means that the `Excluding` needs to track the last part that was excluded. But normally `Excluding` returns the main equivalency options instance.

**Comment by whymatter** [comment]
My idea is to create a decorator type `EquivalencyAssertionOptionsBuilder<TExpectation, TNext>` for the original `EquivalencyAssertionOptions<TExpectation>`. `TNext` points to the generic type of the IEnumerable.
This way `Excluding` still returns an instance of `EquivalencyAssertionOptions<TExpectation>`, so no breaking changes, but because its an `EquivalencyAssertionOptionsBuilder<TExpectation, TNext>` we can continue with the `ThenExcluding` and `TNext`

You can have a look at this commit for my API proposal: https://github.com/whymatter/fluentassertions/commit/67b9c7f93ded1a5bb540382637eb2f1682e40917

**Comment by dennisdoomen** [comment]
But this only works if `Excluding` is the last option of all the options `EquivalencyAssertionOptions` provides.

**Comment by whymatter** [comment]
That is correct, I noticed I can call the copy constructor on `SelfReferenceEquivalencyAssertionOptions` to solve the problem https://github.com/whymatter/fluentassertions/commit/4acdf92a8e1d650c16ed4ec1fe5f682c767cd064.
I will implement the actual ThenExcluding-logic next week to see if this approach works.

**Comment by dennisdoomen** [comment]
Then this will become a breaking change for existing users. What if we make `SelfReferenceEquivalencyAssertionOptions` smart enough to track the last call to `Excluding` and use that when chaining it with `ThenExcluding`?

**Comment by whymatter** [comment]
I need to return an instance from `Excluding` that knows the `T` of the `IEnumerable<T>`. How can I do that by tracking something in `SelfReferenceEquivalencyAssertionOptions`? My idea was to track the path to `IEnumerable<T>` and then chain it with the Selector from `ThenExcluding`.
To understand correctly, the breaking change is that I return a new instance?

**Comment by dennisdoomen** [comment]
> I need to return an instance from `Excluding` that knows the `T` of the `IEnumerable<T>`. How can I do that by tracking something in `SelfReferenceEquivalencyAssertionOptions`? My idea was to track the path to `IEnumerable<T>` and then chain it with the Selector from `ThenExcluding`.

Hmm, you're right. That's not going to fly. Unless you could return an object that derives from `EquivalencyAssertionOptions<TExpectation>` and thereby exposes `ThenExcluding` _and_ the existing members.

> To understand correctly, the breaking change is that I return a new instance?

Yes, just imagine that somebody uses `Excluding` and then any of the other members. If they would upgrade to the version that introduces your suggested change, it would cause a compilation error. That's a breaking change. Those are not allowed until v7.  And that one is not planned at all.

**Comment by whymatter** [comment]
Ah okay, I guess I communicated my idea insufficiently.
> Unless you could return an object that derives from EquivalencyAssertionOptions<TExpectation> and thereby exposes ThenExcluding and the existing members.

Actually, that is what I proposed. `EquivalencyAssertionOptionsBuilder<TExpectation, TCurrent>` derives from `EquivalencyAssertionOptions<TExpectation>` and exposes all existing members.

```c#
public class EquivalencyAssertionOptionsBuilder<TExpectation, TCurrent> : EquivalencyAssertionOptions<TExpectation>
```
`EquivalencyAssertionOptionsBuilder` will expose the `ThenExcluding` function.  I believe that is what you were thinking about?

`EquivalencyAssertionOptions.Excluding` will get an overload that returns the new `EquivalencyAssertionOptionsBuilder`. See here:
```c#
public EquivalencyAssertionOptionsBuilder<TExpectation, TNext> Excluding<TNext>(
    Expression<Func<TExpectation, IEnumerable<TNext>>> expression)
```

**Comment by dennisdoomen** [comment]
Ah, then we're aligned.
