### ISSUE TITLE
ContainEquivalentOf fails unexpectedly

### ISSUE THREAD

**Issue by lonix1** [fluentassertions/fluentassertions#1795]
### Description

I'm trying compare two collections, which should be equivalent. But the test fails.

### Complete minimal example reproducing the issue
````cs
using System.Security.Claims;
using FluentAssertions;
using Xunit;

public class Tests {

  [Fact]
  public void collections_should_be_equivalent() {

    var collection1 = new List<Claim> {
        new Claim("foo", "bar"),
        new Claim("spam", "ham"),
      };

    var collection2 = new List<Claim> {
        new Claim("foo", "bar"),
        new Claim("spam", "ham"),
      };

    collection2.Should().ContainEquivalentOf(collection1);
  }

}
````

I also tried `collection2.Should().ContainEquivalentOf(collection1, o => o.WithTracing());` but that doesn't provide tracing info, and when debugging, it throws `XunitException`.

### Expected behavior:
I expect the test to pass.

### Actual behavior:
The test fails.

> Outcome: Failed
    Error Message:
    Expected collection2 {foo: bar, spam: ham} to contain equivalent of {foo: bar, spam: ham}.

### Versions
* Which version of Fluent Assertions are you using? 6.2.0
* Which .NET runtime and version are you targeting? .NET SDK 6.0.101, but my project targets 5.0.404

### Additional Information
I don't understand why the `WithTracing` option doesn't work - any ideas?

**Comment by dennisdoomen** [comment]
`ContainEquivalentOf` asserts that `collection1` contains any _object_ that is equivalent to the object represented by `collection2`. But `collection1` does not contain another collection. What you may have intended is that both collections are equivalent. For that, you need to use `BeEquivalentTo`. 

`WithTracing` without using a `ITraceWriter` is indeed broken in combination with `ContainEquivalentOf`. I'll create a separate bug for that.

**Comment by lonix1** [comment]
This is very embarrassing, it's not the first time I've stumbled over those methods. :smile: Some of them can get confusing.

Sorry for the false issue report, and thanks for the reply!

**Comment by dennisdoomen** [comment]
No worries. 

Related bug: https://github.com/fluentassertions/fluentassertions/issues/1796
