### ISSUE TITLE
`EnumAssertions.Be()` doesn't identify the subject (but its `NotBe()` counterpart does)

### ISSUE THREAD

**Issue by jasonsparc** [fluentassertions/fluentassertions#1832]
I decided to look at the source code after finding out that my `enum` assertions weren't identifying the subject name when using `Be()`, and yet it is identified correctly when using `NotBe()`.

Apparently, in `EnumAssertions.Be()` (see line 60), `{context:the enum}` was not being used:

https://github.com/fluentassertions/fluentassertions/blob/418a405031b71caf93023ba0d39562525e937f13/Src/FluentAssertions/Primitives/EnumAssertions.cs#L55-L64

This doesn't match the counterpart `NotBe()` (see line 105):

https://github.com/fluentassertions/fluentassertions/blob/418a405031b71caf93023ba0d39562525e937f13/Src/FluentAssertions/Primitives/EnumAssertions.cs#L99-L108

The above are permalinks but the issue currently exists in both the `develop` and `master` branches.

**Comment by jasonsparc** [comment]
Also, I think the failure message for `NotBe()` would be better if instead of "Expected *the enum* not to be …", it was rather "Expected *the enum* to not be …" – I'm not a native English speaker btw, so it could be just me that I find the wording weird, that it might be a typo, so I'm reporting it also just in case.

Actual example output in my tests:

```
Expected state not to be DisposeState.DisposedFully {value: 7} because `HandleDisposeRequest() == false`, but it is.
```

**Comment by dennisdoomen** [comment]
> Also, I think the failure message for `NotBe()` would be better if instead of "Expected _the enum_ not to be …", it was rather "Expected _the enum_ to not be …"

You're right. That's better.

**Comment by jnyrup** [comment]
We have a "not to be" or "to not be" discussion somewhere, but I can't find it right now.

Just for the record, we're using "not to be" most places.
* `not to be`: 77 occurrences
* `to not be`: 19 occurrences

**Comment by dennisdoomen** [comment]
https://github.com/fluentassertions/fluentassertions/issues/1340

We should change that thing into a page on www.fluentassertions.com

**Comment by jnyrup** [comment]
Found it, I was looking for #713 and #620.
