### ISSUE TITLE
Build expression dynamically rather than using enum for sorting

### ISSUE THREAD

**Issue by abatishchev** [fluentassertions/fluentassertions#185]
Hi Dennis,
In `GenericCollectionAssertions` you're using `enum SortDirection { Ascending, Descending }` but rather than this you can build a sorting expression dynamically:

```c#
ParameterExpression param = Expression.Parameter(typeof(T), "x");   // x

Expression property = Expression.Property(param, columnName);       // x.ColumnName

Func<T, object> lambda = Expression.Lambda<Func<T, object>>(        // x => x.ColumnName
            Expression.Convert(property, typeof(object)),
            param)
    .Compile();

Func<IEnumerable<T>, Func<T, object>, IEnumerable<T>> expression = (c, f) => c.OrderBy(f)
// or (c, f) => c.OrderByDescending(f) accordingly

IEnumerable<T> sorted = expression(collection, lambda);
```

(code is from [here](http://www.codeproject.com/Articles/246361/Handle-GridView-OnSorting-using-LINQ))

It isn't strictly related to [the code you have](https://github.com/dennisdoomen/fluentassertions/blob/master/Src/Core/Collections/GenericCollectionAssertions.cs#L69) but just some thoughts on it.

**Comment by d1mnewz** [comment]
I would appreciate if `BeOrderedBy` becomes public so you can pass an expression of how it should be sorted and in which direction.

**Comment by abatishchev** [comment]
The issue appears to be valid [still](https://github.com/fluentassertions/fluentassertions/blob/fdce702f501c24f14c5577802e6182f42de67ab2/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs#L509) ;)

**Comment by jnyrup** [comment]
@abatishchev Could you elaborate a bit on why this would be beneficial?
I haven't dug into this, but it looks like a lot of overhead to add all the `Expression` machinery compared to the current code?
```
IOrderedEnumerable<T> expectation = (direction == SortOrder.Ascending)
    ? unordered.OrderBy(keySelector, comparer)
    : unordered.OrderByDescending(keySelector, comparer);
```

**Comment by dennisdoomen** [comment]
I think the current implementation is fine as it is. There's no bug or performance issue and no need to make the code more complicated.
