### ISSUE TITLE
`AndConstraint` misbehaves

### ISSUE THREAD

**Issue by sebascomeau** [fluentassertions/fluentassertions#1861]
### Description

I'm trying to assert that my `DateTime` variable is not null and the `Kind` property is `DateTimeKind.Utc` by using `AndConstraint` but the it fails saying the kind is `DateTimeKind.Unspecified`. Check my examples below for more details. The first will failed and the second will succeed and only the difference is the `AndConstraint`.

### Complete minimal example reproducing the issue

```csharp
[Fact]
public void DateTimeNullable_Kind_ShouldBeUtc_Failed() {
    // Arrange & Act
    DateTime? dt = new(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc);

    // Assert
    dt.Should().NotBeNull()
        .And.As<DateTime>().Kind.Should().Be(DateTimeKind.Utc);
}

[Fact]
public void DateTimeNullable_Kind_ShouldBeUtc_Succeed() {
    // Arrange & Act
    DateTime? dt = new(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc);

    // Assert
    dt.Should().NotBeNull();
    dt.As<DateTime>().Kind.Should().Be(DateTimeKind.Utc);
}
```

### Expected behavior:

The `DateTimeKind.Utc` sould be asserted as `DateTimeKind.Utc` in both tests.

### Actual behavior:

DateTimeNullable_Kind_ShouldBeUtc_Failed fails

### Versions

* Which version of Fluent Assertions are you using? **6.5.1**
* Which .NET runtime and version are you targeting? **.net 6.0**

**Comment by dennisdoomen** [comment]
That's because `And` returns the `NullableDateTimeAssertions` that contains the `NotBeNull` method, which you then try to cast to `DateTime`. This gives you a `default` date time object, which, obviously, has no kind.

Instead, what you need to do is use

    dt.Should().NotBeNull().And.BeIn(DateTimeKind.Utc);
