### ISSUE TITLE
Asserting on a mac (VS2022 Preview) behaves partially wrong

### ISSUE THREAD

**Issue by IT-VBFK** [fluentassertions/fluentassertions#1874]
### Description

For example: Test `FluentAssertions.Specs.Types.MethodInfoAssertionSpecs.When_subject_is_null_be_async_should_fail()` fails with following error message:

```
Expected exception message to match the equivalent of "Expected method to be async *failure message*, but methodInfo is <null>.", but "Expected method to be async because we want to test the failure message, but member is <null>." does not.
```
(This differs at the "member" part)

It seems that the `{context:member}` is not resolved correctly to the variable name in code.

### Complete minimal example reproducing the issue

On my mac this test above fails already.

### Expected behavior:

The test passes and the variable name is (in this particular case) `memberInfo` instead of `member`.

### Actual behavior:

See error message

### Versions

* Which version of Fluent Assertions are you using? 6.5.1
* Which .NET runtime and version are you targeting?

### Additional Information

Maybe this a problem outside of the scope from fluentassertions, but in case this could be tested/solved I file this "bug" here

**Comment by dennisdoomen** [comment]
Are you building a `debug` build? Because call site identification only works when the unit tests are compiled in debug mode.

**Comment by IT-VBFK** [comment]
Yes, all builds are in debug mode

**Comment by dennisdoomen** [comment]
Hmm, this is something Mac specific. And I don't have a Mac, so unless you're willing to investigate where identity identification fails, there's nothing we can do.

**Comment by IT-VBFK** [comment]
Weird.. This is apparently all about VisualStudio.. if I run `dotnet build` and `dotnet test` at the command line it all works
