### ISSUE TITLE
Add support `System.Text.Json.JsonDocument`

### ISSUE THREAD

**Issue by RobSwDev** [fluentassertions/fluentassertions#1887]
For those who are moving away from Json.Net

**Comment by dennisdoomen** [comment]
No, there's no news. But if anybody is up for it, we would most definitely welcome it.

**Comment by jnyrup** [comment]
Before anyone goes on and implement this, please provide a proposal of what the adding API would look like.

**Comment by WhatzGames** [comment]
Possibly thinking about covering JsonNode as well?

**Comment by lucasteles** [comment]
> Possibly thinking about covering `System.Text.Json.Nodes` as well?

please

**Comment by lucasteles** [comment]
> Before anyone goes on and implement this, please provide a proposal of what the adding API would look like.

Maybe it could be same as `fluentassertions.json`

**Comment by dennisdoomen** [comment]
Should be covered by #2205
