### ISSUE TITLE
Github Repo descrictiption does not include .NET6.0

### ISSUE THREAD

**Issue by IT-VBFK** [fluentassertions/fluentassertions#1910]
**Before you file a bug, have you:**

* Tried upgrading to newest version of Fluent Assertions, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/fluentassertions/fluentassertions/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Read the [documentation](https://fluentassertions.com/introduction)?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/questions/tagged/fluent-assertions?mixed=1).

### Description

The README calls out the compatibility for .NET6.0 as well, so it is a litte "Bug" to not mention this in the repo description..

**Comment by jnyrup** [comment]
Thanks, I've updated the repo description.
