### ISSUE TITLE
BeEquivalentTo with anonymous types

### ISSUE THREAD

**Issue by ltickett** [fluentassertions/fluentassertions#1914]
Is it ok to use `BeEquivalentTo()` with anonymous types?

When we do it, we have to double up our check or we get false positives. e.g. consider the below:

```csharp
[Fact]
public void SomeTest()
{
    var a = new { SomeProp = "hello", AnotherProp = 9 };
    var b = new { SomeProp = "hello" };
    var c = new { AnotherProp = 9 };
    var d = new { SomeProp = "hello", AnotherProp = 9 };

    a.Should().BeEquivalentTo(b);
    a.Should().BeEquivalentTo(c);
    a.Should().BeEquivalentTo(d);
}
```

All 3 assertions would pass?

So we do both:

```csharp
[Fact]
public void SomeTest()
{
    var a = new { SomeProp = "hello", AnotherProp = 9 };
    var b = new { SomeProp = "hello" };
    var c = new { AnotherProp = 9 };
    var d = new { SomeProp = "hello", AnotherProp = 9 };

    a.Should().BeEquivalentTo(b);
    b.Should().BeEquivalentTo(a);
    a.Should().BeEquivalentTo(c);
    c.Should().BeEquivalentTo(a);
    a.Should().BeEquivalentTo(d);
    d.Should().BeEquivalentTo(a);
}
```

Could we introduce a flag or additional matcher that checks both ways around? Or perhaps adds a `actual.CountOfProps == expected.CountOfProps` as this would avoid having to double the comparisons?

**Comment by jnyrup** [comment]
It's _perfectly_ fine to use `BeEquivalentTo` with anonymous types.

`BeEquivalentTo` by design uses the expectation to select what members to compare.

The intention is that you can write

```cs
var subject = new DomainObject // imagine this entity was the output of some code
{
    ImportantProp = "foo"
    AutoGeneratedProp = "bar" // we don't want to include this in the comparison
};

var expected = new
{
    ImportantProp = "foo"
};

subject.Should().BeEquivalentTo(expected);
```

You can write your own extension method to do both equivalency checks.
Rough sketch of how it could look.
```cs
public static class ObjectAssertionsExtensions
{
    public static AndConstraint<ObjectAssertions> BeSymmetricallyEquivalentTo(this ObjectAssertions parent,
        object expectation,
        string because = "",
        params object[] becauseArgs)
    {
        return parent.BeSymmetricallyEquivalentTo(expectation, config => config, because, becauseArgs);
    }

    public static AndConstraint<ObjectAssertions> BeSymmetricallyEquivalentTo(this ObjectAssertions parent,
        object expectation,
        Func<EquivalencyAssertionOptions<object>, EquivalencyAssertionOptions<object>> config,
        string because = "",
        params object[] becauseArgs)
    {
        parent.BeEquivalentTo(expectation, config, because, becauseArgs);
        expectation.Should().BeEquivalentTo(parent.Subject, config, because, becauseArgs);
        return new AndConstraint<ObjectAssertions>(parent);
    }
}
```

**Comment by ltickett** [comment]
Amazing- thank you so much @jnyrup i'm really glad my approach isn't ridiculous!

Would you consider accepting such a contribution if I try to add the check to the project itself?

**Comment by dennisdoomen** [comment]
I feel comparing this from two directions is a bit of a niche feature. So no, I don't think we should add it to the library.

**Comment by jnyrup** [comment]
Agree @dennisdoomen.
I also used `EquivalencyAssertionOptions<object>` in the snippet above, so it could be used on _both_ subject and expectation even if they are of different compile-time type.
Such a workaround does not fit in well in the library.
