### ISSUE TITLE
Add `ForConstraint` to `IAssertionScope`

### ISSUE THREAD

**Issue by ITaluone** [fluentassertions/fluentassertions#1918]
**Before you file a bug, have you:**

* Tried upgrading to newest version of Fluent Assertions, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/fluentassertions/fluentassertions/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Read the [documentation](https://fluentassertions.com/introduction)?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/questions/tagged/fluent-assertions?mixed=1).

### Description

Is there a good reason why `ForConstraint` is not available in an `IAssertionScope`, but only in the `AssertionScope` implementation?
Reason for this change is, that you can not chain an `ForConstraint` after a `Then`, resulting in quite longish sets of `Execute.Assertion...`

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

E.g.

```csharp
Execute.Assertion
    .BecauseOf(because, becauseArgs)
    .WithExpectation($"Some expectation {0}}{{reason}}, ", parameter)
    .ForCondition(somethingShouldBeTrue)
    .FailWith("but cool error.")
    .Then
    .ForConstraint(occurrenceConstraint, actualCount) // this line here
    .FailWith($"Other cool error {{0}}{{reason}}, but found {{1}}.",
        coolParameter, bla);
```

### Expected behavior:

Chaining a `ForConstraint` should also work after `Then`

### Actual behavior:

Does not :)

### Versions

* Which version of Fluent Assertions are you using? 6.6.0

**Comment by jnyrup** [comment]
I can't remember at the top of my head why we didn't also include it on `IAssertionScope` in v6. 
Adding it now is *technically* a breaking change.

**Comment by IT-VBFK** [comment]
Ok, so if we add it at v7 take the following also into consideration: for now you have to include `.WithExpactation()` twice in the statement. First place: as shown in the example and second before the `.ForConstraint()`. The only difference is: the second `.WithExpactation()` includes the reportable for the occurrence `{expectedOccurrence}`.

To handle this, I have two possible solutions:
1) Add a new method e.g. `.WithReportable()` or something like that, where you can pass down the reportable `WithExpectation()` should care of
2) remove the {expectedOccurrence} only at `.FailWith()` _after_ a `.ForConstraint()`

Hope this is clear :)

```csharp

Execute.Assertion
    .BecauseOf(because, becauseArgs)
    .WithExpectation($"Some expectation {0}}{{reason}}, ", parameter)
    .WithReportabe("expectedOccurrence")
    .ForCondition(somethingShouldBeTrue)
    .FailWith("but cool error.")
    .Then
    .ForConstraint(occurrenceConstraint, actualCount) // this line here
    .FailWith($"Other cool error {{0}}{{reason}}, but found {{1}}.",
        coolParameter, bla);

```

**Comment by IT-VBFK** [comment]
While implementing this I changed my mind about the second `.WithExpectation()`, because
- it affects mostly extensions
- you want a different expectation message sometimes

**Comment by dennisdoomen** [comment]
This is also related to #2253
