### ISSUE TITLE
Excluding properties behind an array doesn't work in BeEquivalentTo on collections

### ISSUE THREAD

**Issue by Turnerj** [fluentassertions/fluentassertions#1919]
### Description

A bit of a weird title but basically if I call `myCollection.Should().BeEquivalent(expected, cfg => cfg.Excluding(i => i.SomeArray[0].SomeProperty))`, the property isn't correctly excluded and I get the follow assertion error:

> Expected property root[0].Items[0].Name to be "Foo", but "Bar" differs near "Bar"

### Complete minimal example reproducing the issue

```csharp
var expected = new A[] {
	new A { Items = new List<B> { new B { Name = "Foo" } } }
};

var actual = new A[] {
	new A { Items = new List<B> { new B { Name = "Bar" } } }
};

actual.Should().BeEquivalentTo(
	expected,
	cfg => cfg.Excluding(a => a.Items[0].Name)
);

class A
{
	public string Name { get; set; }
	public List<B> Items { get; set; }
}

class B
{
	public string Name { get; set; }
}
```

### Expected behavior:

The excluding rule to be used and the test to pass.

### Actual behavior:

The excluding rule is ignored and the test fails.

### Versions

* Which version of Fluent Assertions are you using?
v6.6.0

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.1.
.NET 6

### Additional Information

I believe this is a regression between v5.5.3 and v6.6.0 - I haven't (yet) nailed down which version but will update when I have.

**Edit**: The regression starts in v6.0.0. The last v5 has this behaving correctly.

Additionally, this only seems to affect properties behind the array in the excluded check. Properties on the same level as the array work as expected if excluded.

**Comment by IT-VBFK** [comment]
Ahhm... this should be fixed in the next release. See #1782

**Comment by Turnerj** [comment]
Ahhh OK. I did look for existing issues about this but must not have had the right keywords or something.

Looking forward to the next release then!

**Comment by Turnerj** [comment]
I cloned the develop branch and tested this (as that PR you referenced was merged) but it doesn't seem to work:

```csharp
var expected = new A[]
{
    new A { Items = new List<B> { new B { Name = "Foo" } } }
};

var actual = new A[]
{
    new A { Items = new List<B> { new B { Name = "Bar" } } }
};

actual.Should().BeEquivalentTo(
    expected,
    cfg => cfg.For(a => a.Items).Exclude(a => a.Name)
);
```

This is the exception the test threw:
```
Expected property actual[0].Items[0].Name to be "Foo", but "Bar" differs near "Bar" (index 0).

With configuration:
- Use declared types and members
- Compare enums by value
- Compare tuples by their properties
- Compare anonymous types by their properties
- Compare records by their members
- Include non-browsable members
- Include all non-private properties
- Include all non-private fields
- Exclude member Items[]Name
- Match member by name (or throw)
- Be strict about the order of items in byte arrays
- Without automatic conversion.
```

**Comment by Turnerj** [comment]
If I was to have a guess at the problem, one difference between my example and the linked PR is that my base type I run `Should()` on is an array. I don't know the inner workings of Fluent Assertions to know whether that would make a difference but I think it interferes with the member path checks (eg. `actual[0].Items[0].Name` != `Items[0].Name`).

**Comment by ITaluone** [comment]
Hmm.. this have to be a bug then..

**Comment by whymatter** [comment]
My PR was about the `For` and `Excluding` syntax to make an exclusion for all items in an IEnumerable. The initial issue here was about excluding a specific array index. These are two different 'exclusion types'.  

For my understanding, the following should work on the 6.6.0 release
````c#
actual.Should().BeEquivalentTo(
	expected,
	cfg => cfg.Excluding(a => a.Items[0].Name)
);
```

**Comment by ITaluone** [comment]
Hmm... but what if I want to exclude `Name` on every `Item`? IMHO this is what @Turnerj wants to acheive here..

**Comment by Turnerj** [comment]
Technically it is _both_. The code I've inherited uses `Items[0].Name` in the syntax @whymatter mentions but that is broken as of v6.0.0 according to my testing of different Fluent Assertion versions. That said, in this code I've inherited, there is only one item in that array so it really is _all_ items.

I think the underlying issue of why `Items[0].Name` doesn't work is why `For(a => a.Items).Excluding(b => b.Name)` doesn't work - there is something special about the root object being an array.

**Comment by whymatter** [comment]
My point is that even the existing functionality (excluding specific indices) before my PR is not working. Which I think is strange, I guess there are unit tests for this..

**Comment by dennisdoomen** [comment]
I initially thought it worked given we have this [successful test](https://github.com/fluentassertions/fluentassertions/blob/37a241bf21395a8356226b68ca17b28b810207ad/Tests/FluentAssertions.Equivalency.Specs/CollectionSpecs.cs#L528), but that one is not using a collection at the root. Also, I can confirm the behavior is slightly different when the root is a collection.
