### ISSUE TITLE
Throws() method does not work properly

### ISSUE THREAD

**Issue by GualaBanana** [fluentassertions/fluentassertions#1921]
.Invoking() a method that clearly throws fails the .Throw() assertion. I also can't step inside the method being invoked while debugging, assertion exception is just thrown.

My code:
```csharp
public class MyClass
{
    public void Method()
    {
        throw new DirectoryNotFoundException();
    }
}
```

Test method:

```csharp
    [Fact]
    public void TestMethod()
    {
        var sut = new MyClass();

        sut.Invoking(sut => sut.Method()).Should().Throw<FileNotFoundException>();
    }
```

### Expected behavior:

The assertion should not fail.

### Actual behavior:

It fails with the message:
```
Message: 
Expected a <DirectoryNotFoundException> to be thrown, but no exception was thrown.
```

### Versions

* Which version of Fluent Assertions are you using?
- 6.6.0

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.1.
- .NET6

This is the second time this issue reoccurs. First time it happened I lost a lot of time trying to figure out why it doesn't work, although everything is correct until quitted with frustration and lack of any results. It just didn't work no matter what, I also tried to clear NuGet packages, restart VisualStudio, computer.. Nothing helped. I haven't opened that project for a week and when eventually did, it just worked without me touching anything.

**Comment by GualaBanana** [comment]
> Hello! Have you solved your problem?

Yep.

**Comment by MikDal002** [comment]
Could you say how?

**Comment by GualaBanana** [comment]
> Could you say how?

The problem was that I was using it to assert an exception that must be thrown from the method that returns `IEnumerable` and these require another type of assertion - `.Enumerating()`.

From the official documentation on exceptions:
> If the method you are testing returns an IEnumerable or IEnumerable<T> and it uses the yield keyword to construct that collection, just calling the method will not cause the effect you expected because the real work is not done until you actually iterate over that collection. You can use the Enumerating() extension method to force enumerating the collection like this.
```
Func<IEnumerable<char>> func = () => obj.SomeMethodThatUsesYield("blah");
func.Enumerating().Should().Throw<ArgumentException>();
```
> You do have to use the Func<T> type instead of Action<T> then. Or you can do it like this:

```obj.Enumerating(x => x.SomeMethodThatUsesYield("blah")).Should().Throw<ArgumentException>();```

**Comment by MikDal002** [comment]
Thank you, I missed that part of documentation.
