### ISSUE TITLE
The Be() method does not allow a becauseArgsFunc parameter

### ISSUE THREAD

**Issue by brah-mcdude** [fluentassertions/fluentassertions#1940]
### Description
The `Be()` method should allow a `becauseArgsFunc` parameter.  This function callback creates and returns the `becauseArgs `parameter list. This will improve performance of apps that use this method. 

Example: 
In my app, I need to create a large `becauseArgs` parameter list. This is expensive. Especially since I assert in my inner most loop in my app, many times per second. This ends up slowing down my app significantly. I wish I could not evaluate `becauseArgs` unless the assertion fails. So only if the assertion fails, will `Be()` call the `becauseArgsFunc` to get the actual `becauseArgs`.

**Comment by brah-mcdude** [comment]
yes. i actually consulted with one of you (FA team) before about this. i was told that i can do it.

**Comment by dennisdoomen** [comment]
Sure you can, but it wasn't designed for that, so it may have consequences on the performance.

**Comment by brah-mcdude** [comment]
have you done any performance benchmarks? how bad can it be? i just like having assertions sprinkled in my code. how does FA compare with a vanilla if-then-throw construct?
