### ISSUE TITLE
Exceptions in event accessors fail tests when using .Monitor()

### ISSUE THREAD

**Issue by apazureck** [fluentassertions/fluentassertions#1948]
### Description

When an event handler accessor has an explicit implementation, which throws an exception on the setter, `.Monitor()` is failing the test completely.

**What is my motivation?**

I need to test the class behavior without changing the other base event handler accessors behavior. It could cause unwanted side effects. But I do not need to test this event. I just wanted to test PropertyChanged events being raised. Therefore, I would like to have the benefit of having the full class available to write expressions in the assertion.

**Suggestion:**

Make some more configuration options for the Monitor. Like ignoring failing events, or just subscribing to a subset of interfaces with those events, or putting some events on ignore, without changing the generic Type, which is used to assert / monitor.

**Benefit:**

Using the great syntax you introduced in monitor on brown field projects or if you are not able to change the behavior of some event accessors. Therefore, write better and cleaner test code from the beginning.

### Complete minimal example reproducing the issue

```csharp
using System.ComponentModel;
using Xunit;

namespace FluentAssertions.Tests;

class FailingEventHandlerSubscription : INotifyPropertyChanged
{
    private event PropertyChangedEventHandler? InnerPropertyChanged;
    public event PropertyChangedEventHandler? PropertyChanged
    {
        add { throw new System.Exception("This is sadly happening due to anonymous method"); }
        remove { InnerPropertyChanged -= value; }
    }

    private object prop;

    public object Property
    {
        get => prop;
        set
        {
            prop = value;
            this.InnerPropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Property)));
        }
    }
}

public class UnitTest2
{
    [Fact]
    public void TestEventHandler()
    {
        // Arrange
        var cut = new FailingEventHandlerSubscription();

       // will fail, because the exception is thrown, when the EventHandler class is subscribing the event.
        using var monitored = cut.Monitor();

        // Act
        cut.Property = new object();

        // Assert
        // If I just use the INotifyPropertyChanged interface, I cannot write this awesome expression.
        monitored.Should().RaisePropertyChangeFor(m => m.Property);
    }
}
```

### Expected behavior:

FluentAssertions is able to have options in the monitor to ignore failing event handlers.

### Actual behavior:

It throws an exception when .Monitor() is called and I can do nothing about it, event though I do not want to test this specific event.

### Versions

FluentAssertions Version 6.7.0

### Additional Information

I already implemented my custom implementation of the monitor and would offer to contribute my suggestion above to the FluentAssertions project. I just wanted to talk to you first, if you would approve of such an enhancement of the monitor or if you disagree on this feature for some reason.

So let me know if you agree or disagree.

cheers!

**Comment by dennisdoomen** [comment]
I'm not sure how we can fix this. The job of `Monitor` is to subscribe to the events exposes by the SUT, so it can track which events was raised. I don't think we should ignore exceptions while subscribing. If we would, an assertion like `Should().RaisePropertyChangeFor` will throw an exception because the property wasn't raised, even though it never subscribed.

**Comment by lg2de** [comment]
The method `Monitor` could get (optional) options to ignore specific events to be subscribed.

**Comment by apazureck** [comment]
@dennisdoomen I already forked and implemented it. The default behavior won't be changed. I added an optional `.ConfigureMonitor(...)` extension, with which it is possible to suppress the exception either using a configuration object or a fluent api with .IgnoreEventAccessorExceptions().

So a normal call would look like this:

`using IMonitor<ClassToMonitor> monitor = cut.ConfigureMonitor().IgnoreEventAccessorExceptions().Monitor();`

Would you be OK with that?

**Comment by lg2de** [comment]
I recommend to ignore specific events instead of "exception when accessing any event". This looks very specific to your scenario.
The options should be similar to exclusion in `BeEquivalentTo`.

**Comment by apazureck** [comment]
I see your argument. I have no strong opinion about how to resolve this.

What you are suggesting is closer to the rest of the framework, which I think is a good thing to do. I never used the BeEquivalentTo exclusions. I will have a look at them next week and come up with a suggestion.

My approach is more pragmatic to solve the problem, as it will ignore all events which have "broken" event accessors and leave the rest as is. So you do not have to change the test when some more not used event accessors may get broken in the future, too. This is following the SOLID principles (SRP - Only one reason to change). Which I think is also a good thing to consider.

But I am also a fan of having choices, so why not both approaches? I just don't want to do both in one merge request / feature request.

**Comment by dennisdoomen** [comment]
I would change it to:

```
using var monitored = cut.Monitor(opt => opt.IgnoringEventAccessorExceptions());
```
