### ISSUE TITLE
Update documentation for Enums assertions

### ISSUE THREAD

**Issue by carlin-q-scott** [fluentassertions/fluentassertions#1955]
### Description

The [documentation for Enums assertions](https://fluentassertions.com/enums/) doesn't mention the fairly new BeOneOf assertion.

### Versions

Fluent Assertions 6.7.0

**Comment by jnyrup** [comment]
Thanks for spotting and reporting this.
The merged PR will be visible on the website with the next release (no ETA).

**Comment by carlin-q-scott** [comment]
I actually implemented this myself before realizing I just needed to install the latest version 😭
