### ISSUE TITLE
reactive async assertions

### ISSUE THREAD

**Issue by bitbonk** [fluentassertions/fluentassertions#197]
We have a system where components embedded in a runtime mainly communicate with each other through events.
To test these components (or to specifiy its behavior) I'd like to see more assertions that deal with handling a series of events (asynchronously or synchronously). 

Here are some examples:

``` C#
// assert number of events
sut.ShouldRaiseEvent("SomethingHappened").Exacly.Once;
sut.ShouldRaiseEvent("SomethingHappened").AtLeast(5).Times;
sut.ShouldRaiseEvent("SomethingHappened").NotMoreThan(6).Times;

// assert sequence of events
sut.ShouldRaiseEvent("SomethingHappened").FollowedBy("SomethingElseHappened");
sut.ShouldRaiseEvent("SomethingHappened").WithArgs<SomethingEventArgs>(a => a.Foo = "Bar").FollowedBy("SomethingHappened").WithArgs<SomethingEventArgs>(a => a.Foo = "Bar2");
sut.ShouldRaiseEvent("SomethingHappened").AtLeast(5).Times.FollowedBy("SomethingElseHappened");
sut.ShouldRaiseEvent("SomethingHappened").AtLeast(5).Times.FollowedBy("SomethingHappened").WithArgs<SomethingEventArgs>(a => a.Foo = "Bar");

// assert all of the above in an asynchronous fashion (obvoiously you'd often want a timeout here)
await sut.ShouldRaiseEvent("SomethingHappened").Exactly.Once.Within(Timespan.FromSeconds(1));

// but also without a timeout is possible
await sut.ShouldRaiseEvent("SomethingHappened").Exactly.Once.Eventually;
```

**Comment by bitbonk** [comment]
Maybe it is just easier to extend the FA's existing [event monitoring feature](https://github.com/dennisdoomen/fluentassertions/wiki#event-monitoring) and not use reactive extensions?  All that is missing is that I can assert agains a collection of events and to have the async thingy with the timeout...

**Comment by dennisdoomen** [comment]
Yeah, but it's a big feature. I welcome Pull Requests though :smirk:
