### ISSUE TITLE
`BeEquivalentTo()` returns false, if `Equals()` returns false

### ISSUE THREAD

**Issue by MisinformedDNA** [fluentassertions/fluentassertions#1979]
### Description

`BeEquivalentTo` returns false, if `Equals()` returns false, even if all the properties in the object graph are the same.

### Complete minimal example reproducing the issue

```csharp
    public class Tests
    {
        [Fact]
        public void Test()
        {
            var s1 = new EntityBase {  Id = 0 };
            var s2 = new EntityBase {  Id = 0 };
            s1.Should().BeEquivalentTo(s2);
        }
    }

    public class EntityBase
    {
        public int Id { get; set; }

        public override bool Equals(object? obj) => false;
    }
```

### Expected behavior:

Test passes.

### Actual behavior:

Test does not pass. Though the error message shows no differences:

>  Message: 
>     Expected s1 to be EntityBase
>     {
>         Id = 0
>     }, but found EntityBase
>     {
>         Id = 0
>     }.

### Versions

* Which version of Fluent Assertions are you using? 6.7.0
* Which .NET runtime and version are you targeting? .NET 6

### Additional Information

Scenario: 

From [here](https://enterprisecraftsmanship.com/posts/entity-base-class/):

> The Id.Equals(default) line checks for transient entities. Such entities are not yet saved to the database and have the Id set to zero by default. We cannot check identifier equality in such entities, and hence treat two entities as different even if both of them have the Id property set to zero.

```csharp
public class EntityBase
{
    public int Id { get; set; }

    public override bool Equals(object obj)
    {
        if (obj is not Entity other) return false;
        if (ReferenceEquals(this, other)) return true;
        if (GetUnproxiedType(this) != GetUnproxiedType(other)) return false;

        if (Id.Equals(default) || other.Id.Equals(default)) return false;

        return Id.Equals(other.Id);
    }
}
```

**Comment by jnyrup** [comment]
This is [by design](https://fluentassertions.com/objectgraphs/#value-types).
You can use `ComparingByMembers<EntityBase>()` to compare the instances by members instead.

**Comment by MisinformedDNA** [comment]
The documentation says

> The default behavior is to treat every type that overrides Object.Equals as an object that was designed to have value semantics.

I had read this before posting this issue and still got it wrong. To me, value semantics means that it is compared by its member values. Whether I am wrong or you disagree, I think the documentation could be clearer.
