### ISSUE TITLE
Should().BeEquivalentTo() throws "Sequence contains more than one matching element" when comparing  classes that have a field that uses the "new" keyword to hide a field with the same name.

### ISSUE THREAD

**Issue by ERGeorgiev** [fluentassertions/fluentassertions#1982]
I have class `A` that inherits class `ABase`. `ABase` contains field `Id` of type `string`. `A` has its own `Id` string field declared as `new` to hide the `Id` member coming from `ABase`.

Scenario:
Calling `A.Should().BeEquivalentTo(A)`

Expected:
The two fields are compared correctly for equivalency and the proper result is returned.

Actual:
Throws "Sequence contains more than one matching element", thrown on line 144 (return list. SingleOrDefault()) in method `TypeExtensions.FindProperty()` in my decompiled code.

Note:
Does not happen if you compare the same class instance to itself.

**Comment by dennisdoomen** [comment]
Although the comparison should never throw that exception (and is a bug), there's every only going to be a single field, depending on what type the instance is. If it's `A`, then it will compare the field `Id` that is marked as `new`. If the instance points to `ABase`, it'll find the base-property `Id`.
