### ISSUE TITLE
MaxDepth in EquivalencyValidator.

### ISSUE THREAD

**Issue by Wolgo** [fluentassertions/fluentassertions#1993]
https://github.com/fluentassertions/fluentassertions/blob/22b82e738c527e5e83edd80dd6a4794f6049e8d5/Src/FluentAssertions/Equivalency/EquivalencyValidator.cs#L48

MaxDepth is set to 10. 
However, when the current node is at depth 10, it would return false. 
Depth is however 0-based, so depth 9 is already 10 levels, but that is not clear in this line of code.

@dennisdoomen

**Comment by IT-VBFK** [comment]
Is this a trivial fix like `bool shouldRecurse = options.AllowInfiniteRecursion || currentNode.Depth **<=** MaxDepth; `?

**Comment by dennisdoomen** [comment]
See also https://github.com/fluentassertions/fluentassertions/issues/1993
