### ISSUE TITLE
Improve not supported error messages when using `Equals()`

### ISSUE THREAD

**Issue by nycdotnet** [fluentassertions/fluentassertions#1997]
### Description

Running code like the below throws an error `"Calling Equals on Assertion classes is not supported."`

I understand that this by design and is a helpful guard rail to prevent someone from thinking they're using an assertion but actually doing an equality operation and the result being thrown away.  Nice job there.

I think this error message could be improved.  For example, it would be nice in the example below if the exception message also said "Did you mean Be()?".

### Complete minimal example reproducing the issue

```csharp
var x = 1;
var y = 2;
x.Should().Equals(y);  // throws NotSupportedException
```

### Expected behavior:

Expected the exception to point me in the right direction.

### Actual behavior:

I had to search the Internet for the error, found this GitHub site, read the code, realized I was dumb and should have used `Be()`.

### Versions

Latest

### Additional Information

I will put in a PR if you think that supplementing the `Equals()` error messages to point the user in the right direction would be useful.  For many of the assertions, this might be to suggest `Be()` but perhaps there are others which would need to use something else?  I haven't looked yet.  Many thanks for this very useful library.

**Comment by jnyrup** [comment]
> I had to search the Internet for the error, found this GitHub site, read the code, realized I was dumb and should have used `Be()`.

For my understanding of how you received the current error message.
We're you in doubt that `"Calling Equals on Assertion classes is not supported."` referred to Fluent Assertions?

We're all in for improving the message to make it more clear that calling `Equals()` is not what you want.
Do you have a sketch of what a more informative error message would have been?

**Comment by dennisdoomen** [comment]
`You're not supposed to be calling Equals on Fluent Assertion's assertion classes. Did you mean Be() instead?`

**Comment by nycdotnet** [comment]
Yes I think the suggested message here is much clearer.  I have used this library for a while and I think one of the reasons I was getting confused is that I was trying to assert reference equality when most of the time it's value.  If you'd be open to it, I can put in a PR using a similar message to that proposed one.  Thanks.

**Comment by nycdotnet** [comment]
And to answer the other question - I did think the NotSupportedException was from FluentAssertions, however I thought it was referring to something else about the code I was using which was sort of nested object hierarchy stuff.  The error made me think I had to change around how I was referencing it rather than "Don't use Equals and use Be instead".

**Comment by dennisdoomen** [comment]
Ah, maybe we can then make it even shorter:

`Equals is not part of Fluent Assertions. Did you mean Be() or BeSameAs() instead?

**Comment by nycdotnet** [comment]
I like that.  I will work on a PR when I get some time soon.  Many thanks for being open to considering improving this error message.

**Comment by jnyrup** [comment]
Suggestions:
For `ReferenceTypeAssertions` the only suggestion is `BeSameAs` whereas for its derivative:
* `ObjectAssertions` there's both `Be` and `BeSameAs`
* `GenericCollectionAssertions` has `BeSameAs` and `Equal`

Several assertion type like e.g. `TimeOnlyAssertions` only has `Be`.

Some don't have any reasonable method to call, e.g. `TypeSelectorAssertions`.

**Comment by dennisdoomen** [comment]
I guess we can make the message specific for the type.

**Comment by jnyrup** [comment]
> I guess we can make the message specific for the type.

Right, I forgot to add the point, which was that we e.g. want to _add_ overrides of `Equals` to e.g. `ObjectAssertions` and `GenericCollectionAssertions` to properly suggest `Be` and `Equals`.
