### ISSUE TITLE
Move DataSet/DataTable/DataRow assertions to separate library

### ISSUE THREAD

**Issue by ericnewton76** [fluentassertions/fluentassertions#2002]
Should DataSet/DataTable/DataRow assertions get lumped into a separate library?  These are types that are over 20 years old, introduced with NetFramework 1.0 beta 1... and I know this because yes I was porting things from VB6 back then as fast as I could... ;-D

Of note, starting a fresh testing project with nunit 3.12 and fluentassertions 6.7.0, I get reference errors about missing reference to System.Data v4.0.0.  Otherwise FluentAssertions is pretty clean.

- FluentAssertions 6.7.0

* [x] Copy all data-related code to https://github.com/fluentassertions/fluentassertions.datasets
* [x] How can the data project inject additional equivalency steps?
* [x] Delete all data-related code from the main repo
* [x] Move the data-related docs to the read-me of the data repo
* [x] Ensure that the data repo has its own discussions, issues and releases
* [x] Update the breaking changes of the main repo
* [x] Push an alpha version of FA 7.0 and update dependencies in the data set project to make it build again
* [x] Introduce a mechanism for an extension library like `FluentAssertions.DataSets` to register custom equivalency steps
* [x] Review all namespace imports and make sure everything works as expected
* [x] Ensure the build works correctly
* [x] Identify any code analysis issues
* [x] Check package contents
* [x] Update the readme
* [x] Setup branch protection rules

**Comment by jnyrup** [comment]
It's definitely something we talked about for vNext (7.0.0), we just never got around to create an issue for it.

Any good ideas for what name it should have?

The first thing that comes to my mind is `FluentAssertions.System.Data`.

**Comment by ITaluone** [comment]
Do you really inteded to close this? 
I think this was a false positive (PR description: .... resolves #2002)

**Comment by dennisdoomen** [comment]
No, I didn't. Thanks for heads up.
