### ISSUE TITLE
Update error message at `DateTimeAssertions.BeCloseTo()` to include the calculated time range

### ISSUE THREAD

**Issue by ITaluone** [fluentassertions/fluentassertions#2012]
**Before you file a bug, have you:**

* Tried upgrading to newest version of Fluent Assertions, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/fluentassertions/fluentassertions/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Read the [documentation](https://fluentassertions.com/introduction)?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/questions/tagged/fluent-assertions?mixed=1).

### Description

Now the error message looks like this:
`Expected logs.First().ChangedAt to be within 15s from <2022-10-13 06:44:06.8277343>, but found <2022-10-13 06:43:51>.`

But with this line I have to calculate the difference between the two `DateTime`s in case I want to know the exact difference.

### Complete minimal example reproducing the issue

This is not an issue inside FA, but a proposal to state more precisely what the time differnece was.

### Expected behavior:

Something like:
`Expected logs.First().ChangedAt to be within 15s from <2022-10-13 06:44:06.8277343>, but found <2022-10-13 06:43:51>, which is XXXs.`

### Actual behavior:

The calculated difference is not displayed.

### Versions

* Which version of Fluent Assertions are you using? 6.7.0
* Which .NET runtime and version are you targeting? .net6.0 and .net7.0

### Additional Information

-

**Comment by IT-VBFK** [comment]
I could take care of this, if this passes a review 🙃

**Comment by jnyrup** [comment]
Sounds good to me. 
The message should work for both times before and after the expected.

**Comment by IT-VBFK** [comment]
Ok.. cool 👌

anything about the message? Or does the example fit?

**Comment by jnyrup** [comment]
Maybe `but <2022-10-13 06:43:51> is XXXs after`?

I usually approach a task like this by brainstorming and writing down the message in all the variants I can think of and then select the best candidate.

**Comment by IT-VBFK** [comment]
Ah.. makes sense
I will come up with my best fit in the PR :)

**Comment by jnyrup** [comment]
Feel free to post the ideas in here before opening a PR.

**Comment by IT-VBFK** [comment]
Ok

what first came into my mind was:
`but <2022-10-13 06:43:51> is of by XXX(h|m|s|ms|us)` where the XXX is the largest possible integer e.g. instead of 0.123s --> 123ms, 0.5min --> 30s and so on
This would take a slightly bigger calculation, but I think it is worth the effort 🤔

**Comment by IT-VBFK** [comment]
> The message should work for both times before and after the expected.

I will take the absolute values 20s more or less returns 20s instead of 20s and -20s.. 
Was that what you meant?

**Comment by dennisdoomen** [comment]
Why not just rely on the ability of FA to render a `TimeSpan`, which relies on `TimeSpanValueFormatter`?

**Comment by ITaluone** [comment]
If it is ok, when the differnence could be negative, sure.
