### ISSUE TITLE
InnerException information missing in output when using Should().NotThrow()

### ISSUE THREAD

**Issue by rcdailey** [fluentassertions/fluentassertions#2015]
I have a unit test that exercises dependency resolution in Autofac. The test itself is simple:

```cs
// This enumerator ensures that this test case is invoked once per registered concrete type
[TestCaseSource(typeof(ConcreteTypeEnumerator))]
public void Service_should_be_instantiable(Type service)
{
    // This just sets up all the registrations from my app in a reusable way
    using var container = new CompositionRoot().Setup().Container;
    var act = () => container.Resolve(service);
    act.Should().NotThrow();
}
```

Then a specific iteration of this test *fails*, I get the below, truncated output:

```
Did not expect any exception, but found Autofac.Core.DependencyResolutionException with message "An exception was thrown while activating Recyclarr.Command.Helpers.CacheStoragePath."
     at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
```

Now change the above example to this:

```cs
[TestCaseSource(typeof(ConcreteTypeEnumerator))]
public void Service_should_be_instantiable(Type service)
{
    using var container = new CompositionRoot().Setup(RegisterAdditionalServices).Container;
    container.Resolve(service);
}
```

This will throw the same exception, except this time it goes to NUnit3 untouched instead of through FluentAssertions. You now get this output:

```txt
Autofac.Core.DependencyResolutionException : An exception was thrown while activating Recyclarr.Command.Helpers.CacheStoragePath.
Data:
  ActivatorChain: Recyclarr.Command.Helpers.CacheStoragePath
  ----> Autofac.Core.DependencyResolutionException : None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Recyclarr.Command.Helpers.CacheStoragePath' can be invoked with the available services and parameters:
Cannot resolve parameter 'Recyclarr.Command.IServiceCommand serviceCommand' of constructor 'Void .ctor(TrashLib.Startup.IAppPaths, Recyclarr.Command.IServiceCommand)'.
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
```

As you can see, there's more detail in the second case. This additional detail is of particular importance for Autofac, because without it, I can't tell exactly why the resolution failed.

If I stop in the debugger, I see that `DependencyResolutionException.InnerException` seems to have the additional detail. But for some reason that's omitted and/or the exception output is truncated.

Please address the issue by ensuring that InnerException details are printed to the console in this case.

### Versions:

* Which version of Fluent Assertions are you using? `6.7.0`
* Which .NET runtime and version are you targeting? .NET 6

**Comment by dennisdoomen** [comment]
We normally rely on the `ToString` of the exception, but indeed, we should also include the inner exceptions and maybe even [demystify](https://github.com/benaadams/Ben.Demystifier) them all.

**Comment by jnyrup** [comment]
Formatting of exceptions was added in e1c6cd2580b4ca4e78adcbeecc1f51d219f9fbbb and has never used the overloaded [`Exception.ToString()`](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Exception.cs,118) which includes `InnerException` and [`AggregateException.ToString()`](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/AggregateException.cs,362) all `InnerExceptions`.

So we could ensure `InnerException` is included by changing `ExceptionValueFormatter.Format` to
```cs
formattedGraph.AddFragment(((Exception)value).ToString());
```

```cs
public void MyTestMethod()
{
    Action act = () => throw new Exception("OuterExceptionMessage", new InvalidOperationException("InnerExceptionMessage"));

    act.Should().NotThrow();
}
```

Currently:
```
Did not expect any exception, but found System.Exception with message "OuterExceptionMessage"
     at FluentAssertions.Specs.Exceptions.InnerExceptionSpecs.<>c.<MyTestMethod>b__0_0() in C:\dev\fluentassertions\Tests\FluentAssertions.Specs\Exceptions\InnerExceptionSpecs.cs:line 13
     at FluentAssertions.Specialized.ActionAssertions.InvokeSubject() in C:\dev\fluentassertions\Src\FluentAssertions\Specialized\ActionAssertions.cs:line 25
     at FluentAssertions.Specialized.DelegateAssertions`2.InvokeSubjectWithInterception() in C:\dev\fluentassertions\Src\FluentAssertions\Specialized\DelegateAssertions.cs:line 221
.
```

Using `Exception.ToString()`
```
Did not expect any exception, but found System.Exception: OuterExceptionMessage
   ---> System.InvalidOperationException: InnerExceptionMessage
     --- End of inner exception stack trace ---
     at FluentAssertions.Specs.Exceptions.InnerExceptionSpecs.<>c.<MyTestMethod>b__0_0() in C:\dev\fluentassertions\Tests\FluentAssertions.Specs\Exceptions\InnerExceptionSpecs.cs:line 13
     at FluentAssertions.Specialized.ActionAssertions.InvokeSubject() in C:\dev\fluentassertions\Src\FluentAssertions\Specialized\ActionAssertions.cs:line 25
     at FluentAssertions.Specialized.DelegateAssertions`2.InvokeSubjectWithInterception() in C:\dev\fluentassertions\Src\FluentAssertions\Specialized\DelegateAssertions.cs:line 221.
```

**Comment by vmelamed** [comment]
This fix doesn't seem to be released, is it? I am also very interested in seeing more detailed exception information, e.g. we use FluentValidation a lot and usually we wrap `FluentValidation.ValidationException` in `ArgumentException`. When we get one of those unexpected, we want to know what is going on.
On a (somewhat) related note, does FluentAssertions have some general options, settings, knobs, and buttons that would allow you to tweak some of the behaviors (like this one). I could not find anything in the documentation. Thank you!

**Comment by dennisdoomen** [comment]
No, it isn't even fixed yet.
