### ISSUE TITLE
[Feature Request] Graph comparison to handle objects that expose their data through user-defined conversion instead of fields/properties

### ISSUE THREAD

**Issue by Melandel** [fluentassertions/fluentassertions#2016]
### Description

Currently, `Should().BeEquivalentTo()` does not look at private members.

I happen to work in a codebase where most types have been encapsulated in the following fashion:

```cs
record PositiveInteger
{
  readonly int _encapsulated;
  PositiveInteger(int encapsulated)
  {
    if (encapsulated <0)
      throw new ObjectIntegrityException("A PositiveInteger cannot encapsulate a negative number.");

    _encapsulated = encapsulated;
  }

  public static PositiveInteger CreateFromInteger(int i)
  {
    return new PositiveInteger(i);
  }

  // how the data is "publicly exposed": passing a PositiveInteger where an int is expected, works!
  public static implicit operator int(PositiveInteger positiveInteger)
  {
    return positiveInteger._encapsulated;
  }
}
```

As you can see, the `int` version of the data is "exposed" not through a field or property, but through a user-defined conversion.

However, because the graph does not look at any private member, it will find that `PositiveInteger.CreateFromInteger(1)` is in fact equivalent to `PositiveInteger.CreateFromInteger(2)`.

It would be cool to have a way to handle this use case.

**Simple repository for reproduction : [link](https://github.com/Melandel/demo.fluentassertions.userdefinedconversionequivalence)**

On top of my head, an option such as `options => options.IncludePrivateFieldsForObjectsWhose[Namespace/FullName]Matches("regex")` may be a good candidate.

### Versions

* fluentassertions v6.7.0
* dotnet 6

**Comment by dennisdoomen** [comment]
But it's a record, so it should implicitly implement an override of `Equals` that uses that `_encapsulated` field right? So although [by default](https://fluentassertions.com/objectgraphs/#value-types), FA compares record by their properties, you should be able to override that using `ComparingByMembers<PositiveInteger>`.

**Comment by Melandel** [comment]
You are right.

I should probably add a bit of context: our tests are not asserting directly on such `PositiveInteger`, but on data structures whose leaves are `PositiveIntegers` and a lot more types that follow the same user-conversion-based principles

For instance:
```cs
record ServerResponse(
  SomeEncapsulatedId SomeEncapsulatedId,
  PositiveInteger[] Values,
  Dictionary<SomeEnum, NegativeInteger[]> ExtraValuesByType,
  SomeObjectContainingPositiveIntegerProperties ComplexObjectWithPositiveIntegers
);

var serverResponse1 = new ServerResponse(...);
var serverResponse2 = new ServerResponse(...);

serverResponse2.Should().BeEquivalentTo(serverResponse1);
```

Am I understanding correctly if I reformulate by saying that I should add `ComparingByMembers<T>` on all types that follow the same philosophy as `PositiveInteger` ?

**Comment by Melandel** [comment]
I made this repository for reproduction and experimentation in order to help talking on configuration points: https://github.com/Melandel/demo.fluentassertions.userdefinedconversionequivalence

**Comment by Melandel** [comment]
As you can see [here](https://github.com/Melandel/demo.fluentassertions.userdefinedconversionequivalence/blob/master/Tests/FluentAssertionsFactually.cs#L38-L59), using `ComparingByMembers<PositiveInteger>` does not provide the mentioned outcome

**Comment by dennisdoomen** [comment]
I'm sorry, but I meant `ComparingRecordsValue()` and `ComparingByValue<T>`. The default for records is already to compare them by their public properties. But since you don't have any, the two options will tell FA to fall back to the record's implicit value equality. 

But looking at your response, it looks like you want some kind of combination between having value semantics for your records, but still compare collections in the way `BeEquivalenTo` usually does that. That's not possible. And we have no intention to support including `private` fields in the comparison.

**Comment by Melandel** [comment]
I had to ask ^^

Thank you for your time and answer!

I will see with the other options left. Maybe some kind of custom collection such as

```cs
sealed record CollectionComparableByValue<T> : IEnumerable<T>
{
	readonly IEnumerable<T> _encapsulated;
	public CollectionComparableByValue(IEnumerable<T> encapsulated) => _encapsulated = encapsulated?.ToArray();

	public IEnumerator<T> GetEnumerator() => ((IEnumerable<T>)_encapsulated).GetEnumerator();
	IEnumerator IEnumerable.GetEnumerator() => _encapsulated.GetEnumerator();
	public bool Equals(CollectionComparableByValue<T> other) => _encapsulated.SequenceEqual(other ?? new(Array.Empty<T>()));
	public override int GetHashCode()
	{
		return unchecked(this.Aggregate(19, (h, i) => h * 19 + i.GetHashCode()));
	}
}
```

**Comment by Melandel** [comment]
I managed to make it work. Leaving this for future readers: [custom record collections](https://github.com/Melandel/demo.fluentassertions.userdefinedconversionequivalence/blob/define-record-collection-to-make-ComparingRecordsByValue-work-on-collections-as-well/Tests/DataStructures.cs#L49-L80) for native deep equals when using `ComparingRecordsByValue`
