### ISSUE TITLE
How to write multiple sub-clauses on fields after Should().BeAssignableTo()?

### ISSUE THREAD

**Issue by jdx-john** [fluentassertions/fluentassertions#2018]
I want to assert along the lines:
`x is T t  and t.Id==3 and t.Misc == 5`

I tried initially
`x.Should().BeAssignableTo<T>().Which.Id.Should().Be(3).And.Misc.Should().Be(5);`
Obviously that's no good because `And` refers to `x.Id` not `x`. I can of course write two tests
```cs
x.Should().BeAssignableTo<T>().Which.Id.Should().Be(3);
x.Should().BeAssignableTo<T>().Which.Misc.Should().Be(5);
```

But these tests start to get pretty long in real life and logically there is no reason to test the type more than once. Is there a way to write compound assertions neatly? I did realise I _can_ do:

```cs
var t = x.Should().BeAssignableTo<T>().Which;
t.Id.Should().Be(3);
t.Misc.Should().Be(5);
```

But is this the most elegant approach?

**Comment by jnyrup** [comment]
Hi John

In the future please respect this line from the issue template, thanks. 
>  Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/questions/tagged/fluent-assertions?mixed=1).

You can use [`BeEquivalentTo`](https://fluentassertions.com/objectgraphs/) for this.

```
var expected = new
{
    Id = 3,
    Misc = 5
};

x.Should().BeAssignableTo<T>()
  .Which.Should().BeEquivalentTo(expected);
```

**Comment by jdx-john** [comment]
Apologies I'd missed that - and thanks for the answer. SO in future.
