### ISSUE TITLE
ComparableTypeAssertions should have BeOneOf method

### ISSUE THREAD

**Issue by jez9999** [fluentassertions/fluentassertions#2027]
Because `ComparableTypeAssertions` doesn't contain `BeOneOf`, the following code doesn't work:

```
float testFloat = 12f;
var testTuple = (1, 2);

testFloat.Should().BeOneOf(12f, 13f); // Works
testTuple.Should().BeOneOf((1, 2), (1, 3)); // Doesn't work
```

I don't see any technical reason why the latter shouldn't work, so how about adding `BeOneOf` to `ComparableTypeAssertions`?

**Comment by dennisdoomen** [comment]
Indeed. We would welcome a PR.

**Comment by jez9999** [comment]
@dennisdoomen PR submitted.
