### ISSUE TITLE
Add `.BeCloseTo()/.NotBeCloseTo()` to TimeOnlyAssertions and DateOnlyAssertions

### ISSUE THREAD

**Issue by jhartmann123** [fluentassertions/fluentassertions#2029]
### Description

Similar to the `DateTimeAssertions`, the method `BeCloseTo()` should be available for TimeOnly and DateOnly.

E.g.

```csharp
// Arrange
SetTime('10:00:12");
var expected = new TimeOnly(10, 0, 12);

// Act
TimeOnly time = GetTime();

// Assert
result.Should().BeCloseTo(expected, TimeSpan.FromSeconds(1));
```

### Expected behavior:

Validation, if the variable `expected` is `>= 10:00:11` and `<= 10:00:13`

**Comment by jnyrup** [comment]
We [intentionally](https://github.com/fluentassertions/fluentassertions/pull/1844#discussion_r825328246) left them out from `DateOnly` as you cannot measure the time difference between two dates.

But I think it makes sense to add it for `TimeOnly`.
