### ISSUE TITLE
Include extension methods for `OccurrenceConstraint` that reads more fluently

### ISSUE THREAD

**Issue by IT-VBFK** [fluentassertions/fluentassertions#2045]
I was wondering if it would make sense to include an extension method for `Exactly.Times` like this:

```cs
myString.Should().Contain("something", 4.Times()); // Equivalent to Exactly.Times(4)
```

I think it reads a bit better than the existing `Exactly.Times(4)`, but perhaps this has already been considered?

I understand there might be some confusion around `AtLeast`, `AtMost` etc., but that might be fixed like:
```cs
myString.Should().Contain("something", 4.TimesOrMore()); // Equivalent to AtLeast.Times(4) and MoreThan(3)
myString.Should().Contain("something", 4.TimesOrLess()); // Equivalent to AtMost.Times(4) and LessThan(5)
```

There seems to be some redundancy in with `AtLeast`/`MoreThan` and `AtMost`/`LessThan`, but they might be useful in scenarios I've never had.

I know creating such extensions is pretty straightforward:
```cs
public static class FluentOccurrenceConstraintExtensions
{
    public static OccurrenceConstraint Times(this int times)
    {
        return Exactly.Times(times);
    }

    public static OccurrenceConstraint TimesOrLess(this int times)
    {
        return AtLeast.Times(times);
    }

    public static OccurrenceConstraint TimesOrMore(this int times)
    {
        return AtMost.Times(times);
    }
}
```

_Originally posted by @siewers in https://github.com/fluentassertions/fluentassertions/discussions/2001_

**Comment by IT-VBFK** [comment]
Should this be "api-approved"? 🤔

**Comment by IT-VBFK** [comment]
Regarding API: What is missing here? Or what should we change?

**Comment by dennisdoomen** [comment]
Maybe a full list of methods you're proposing to add?

**Comment by IT-VBFK** [comment]
Ok.. I thought the details were already discussed and kind of agreed on in #2001.

If not: here are the three methods I would add

```diff
+ public static class OccurrenceConstraintExtensions
+  {
+      public static FluentAssertions.OccurrenceConstraint Times(this int times) { }
+      public static FluentAssertions.OccurrenceConstraint TimesOrLess(this int times) { }
+      public static FluentAssertions.OccurrenceConstraint TimesOrMore(this int times) { }
+  }
```

**Comment by dennisdoomen** [comment]
Thanks for the clarification. Let's see if @jnyrup also agrees.

**Comment by jnyrup** [comment]
Copying my question from [the discussion](https://github.com/fluentassertions/fluentassertions/discussions/2001#discussioncomment-4188740).

> Do you think `4.TimesExactly()` instead of `4.Times()` is overly verbose compared the complete elimination of ambiguity?

**Comment by dennisdoomen** [comment]
Obviously the first is more explicit than the latter. I have a slight preference for the latter. But if you have a strong preference for the former, then let's do that.

**Comment by IT-VBFK** [comment]
I personally tend to `4.Times()` because it is shorter and I think it is not really ambiguous.

**Comment by jnyrup** [comment]
Then let's go with `TimesExactly()`.

Approved API
```diff
+ public static class OccurrenceConstraintExtensions
+  {
+      public static FluentAssertions.OccurrenceConstraint TimesExactly(this int times) { }
+      public static FluentAssertions.OccurrenceConstraint TimesOrLess(this int times) { }
+      public static FluentAssertions.OccurrenceConstraint TimesOrMore(this int times) { }
+  }
