### ISSUE TITLE
Improve failure message for `StringAssertions.Be`

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#2050]
### Discussed in https://github.com/fluentassertions/fluentassertions/discussions/2048 and https://github.com/fluentassertions/fluentassertions/discussions/1941

<div type='discussions-op-text'>

<sup>Originally posted by **thomOrbelius** November 30, 2022</sup>
Hi.

In my department we have been starting to use FluentAssertions. One of the selling point I had was the improved failure messages. A colleague of mine pointed out that the Xunit failure messages for strings is much more helpful (see example below) than the FluentAssertion equivalent. The example shows a case where we use a string with a newline separator.

Do any one else think that a message more similar to the one Xunit has is more helpful than the current? If so, should we update the message used?

```csharp
using FluentAssertions;
using Xunit;

namespace Sectra.Courier.RisAdapter.Tests.Integrations.SectraRis;

public class FluentComparison {
    private const string string1 = "String with \rnewline";
    private const string string2 = "String with \ra newline";

    [Fact]
    public void FluentAssert() {
        // Fails with:
        // newline" has a length of 20, differs near "new" (index 13).
        string1.Should().Be(string2);
    }

    [Fact]
    public void XUnitAssert() {
        // Fails with:
        // Assert.Equal() Failure
        //                         ↓ (pos 13)
        // Expected: String with \rnewline
        // Actual:   String with \ra newline
        //                         ↑ (pos 13)
        Assert.Equal(string1, string2);
    }
}
```
</div>

**Comment by IT-VBFK** [comment]
I have a first rough attempt to fix this.

Two things I want to check first:
* How should we introduce this change? Because updating this huge amount of string assertions is, let's say on the intellectual side of wrapping all assertions inside nested classes 😉 
* When this change should only affect `.Be()`.. how to achieve this?

**Comment by IT-VBFK** [comment]
You can see in the failure messages, that this would work.

**Comment by dennisdoomen** [comment]
I've considered this a couple of times over the years. But I couldn't figure out what it would look like when a string comparison happens as part of a `BeEquivalenTo` call.

**Comment by IT-VBFK** [comment]
I have implemented this falsely on `StringStartValidator`.. my bad.

But after implementing it also on `StringEqualityValidator` as well (and fixing several failing tests :) ) this is what a failing message at `BeEquivalentTo()` would look like:

```
   Expected string to be equivalent to "abc" because we will test 1 + 2, but actually got:
            ↓ (index 1)
Subject:  "ADC"
Expected: "abc"
            ↑ (index 1).
```

**Comment by dennisdoomen** [comment]
And what if there are multiple string properties that are off? I guess you need to take into account the indenting that usually happens.

**Comment by IT-VBFK** [comment]
> And what if there are multiple string properties that are off?
What do you mean exactly? 
e.g. What happens if one string is shorter?

**Comment by dennisdoomen** [comment]
No, when you're comparing two objects that have multiple string properties that are mismatching. Normally, FA will report the names of the properties and the differences. I was wondering what that would look like with your proposal.

**Comment by IT-VBFK** [comment]
Ah.. got it. Now it looks like following:

For collections:
```
Expected subject[1] to be "one", but actually got:
           ↓ (index 0)
Subject:  "One"
Expected: "one"
           ↑ (index 0).
Expected subject[2] to be "one", but actually got:
           ↓ (index 0)
Subject:  "ONE"
Expected: "one"
           ↑ (index 0).

With configuration:
- Use declared types and members
- Compare enums by value
- Compare tuples by their properties
- Compare anonymous types by their properties
- Compare records by their members
- Include non-browsable members
- Include all non-private properties
- Include all non-private fields
- Match member by name (or throw)
- Be strict about the order of items in byte arrays
- Be strict about the order of collections when IsNullOrEmpty(s.Path)
- Without automatic conversion.
```

For objects (considering you meant this type of assertions: https://fluentassertions.com/objectgraphs)

See this test:
```csharp
[Fact]
public void Test_1234567890()
{
    var subject = new
    {
        stringA = "A",
        stringB = "B"
    };
    var expected = new
    {
        stringA = "B",
        stringB = "C"
    };

    subject.Should().BeEquivalentTo(expected);
}
```

would result in

```
Expected property subject.stringA to be "B", but actually got:
           ↓ (index 0)
Subject:  "A"
Expected: "B"
           ↑ (index 0).
Expected property subject.stringB to be "C", but actually got:
           ↓ (index 0)
Subject:  "B"
Expected: "C"
           ↑ (index 0).

With configuration:
- Use declared types and members
- Compare enums by value
- Compare tuples by their properties
- Compare anonymous types by their properties
- Compare records by their members
- Include non-browsable members
- Match member by name (or throw)
- Be strict about the order of items in byte arrays
- Without automatic conversion.
```
> I guess you need to take into account the indenting that usually happens.

Yes, as I mentioned: this is a rough proposal 😉

**Comment by dennisdoomen** [comment]
Maybe something like this for longer strings? Then the first line will not cause unnecessary noise. Also notice the indention.

```
Expected subject[1] to be the same string, but they differ at index 0:
   ↓ (actual)
  "One"
  "one"
   ↑ (expected).
```

And what happens if there are more differences? Should we stop at the first?
And when the string is very long? To not screw up the layout, I think we should cut off the remainder at something like 80 characters?

**Comment by IT-VBFK** [comment]
What about using a full-flegged diff tool? 

This would take care of:
- Multiple differences
- Whitespace changes
- ...

**Comment by dennisdoomen** [comment]
Such as?

**Comment by dennisdoomen** [comment]
> Like in Approval.Tests: DiffPlex

I've played with this a bit today, but it doesn't seem to help on the text rendering part. Even if you use the `CharacterChunker`, it will just report the characters that were inserted or deleted. IMO, we don't need a full UI diff. We just want something that's readable in the test output.

**Comment by IT-VBFK** [comment]
No problem :) Thanks for checking 

> And what happens if there are more differences? Should we stop at the first?

How would that work? Because if normally if you have a difference between two strings, every following character would match that.

Take this for example:

"This is a test" and 
"This is another test"

If we mention every difference we have to mention "n", "o", "t", "h", "e", "r", " ", "t", "e", "s", "t".

**Comment by dennisdoomen** [comment]
Yeah, that's why I was asking. Maybe you (or anybody else) had a better idea.

**Comment by jnyrup** [comment]
A shower thought:
[Sequence Alignment](https://en.wikipedia.org/wiki/Sequence_alignment) is an area in computer science to find an aligment between two sequences, it could be applied to `subject` and `expected`.

E.g. one such alignment between `"This is a test"` and `"This is another test"` could be:
```
"This is a       test"
"This is another test"
```

[Hirschberg's algorithm](https://en.wikipedia.org/wiki/Hirschberg%27s_algorithm) can be used to compute a maximal global alignment between two sequences.

**Comment by dennisdoomen** [comment]
That would be nice too. But if the lengths are the same and only a single character the arrow approach would be more clearer. Maybe a combination of both.

**Comment by thomOrbelius** [comment]
> Mostly a shower thought, I'm not sure it applies well here.
> 
> [Sequence Alignment](https://en.wikipedia.org/wiki/Sequence_alignment) is an area in computer science to find an aligment between two sequences, it could be applied to `subject` and `expected`.
> 
> E.g. one such alignment between `"This is a test"` and `"This is another test"` could be:
> 
> ```
> "This is a       test"
> "This is another test"
> ```
> 
> [Hirschberg's algorithm](https://en.wikipedia.org/wiki/Hirschberg%27s_algorithm) can be used to compute a maximal global alignment between two sequences.

While I do think that the alignment approach is quite neat. But, if I just look at the result as you showed above, the risk it that I think that there is actually a lot if whitespaces in the first string but the lengths are correct, which could be confusing. The whitespace could of course be replaced by a placeholder symbol (· or *) or indicated on a separate "diff" line, but then the solution is approaching a diff tool again.

I think that the approach with identifying just the first mismatch is good enough. Or rather, I can't think of a simple way to intuitively display both indices of mismatches combined with the alignment without it getting cluttered or confusing.

**Comment by jnyrup** [comment]
> I think that the approach with identifying just the first mismatch is good enough.

I agree that we should probably pursue showing the first mismatch with pointers plus the N leading characters and M trailing characters.

**Comment by IT-VBFK** [comment]
So.. coming back to this issue :)

Just to recap to not implementing rubbish ;-) :

- First mismatch is enough
- https://github.com/fluentassertions/fluentassertions/issues/2050#issuecomment-1356740149 (the example), to reduce noise
- adding `... [n characters before]blabla[m character after]` the difference (I think I can reuse the `GetMismatchSegmentForStringsOfDifferentLengths()` method?)

And a few questions:
- What do you mean with "also notice the indendation" https://github.com/fluentassertions/fluentassertions/issues/2050#issuecomment-1356740149 ? How should the failure message behave?
- > Expected subject[1] to be the same string, but they differ at index 0: 

Should this proposed short solution also apply to `BeEquivalentTo()`?
- At which point should I handle escaping of new lines (now it fails like in the initial question/proposal)?

**Comment by IT-VBFK** [comment]
This change is quite a pain in the ass :D

Have to change almost every test using `StringAssertions.Be` or `StringAssertions.BeEquivalentTo` 🤔

**Comment by dennisdoomen** [comment]
Yes, `BeEquivalenTo` will also be affected by this. Let's take the following test case.

```csharp
var subject = new Root
{
    Text = "Root",
    Level = new Level1 { Text = "Level1", Level = new Level2 { Text = "Leval2" } }
};

var expected = new RootDto
{
    Text = "Roat",
    Level = new Level1Dto { Text = "Lavel1", Level = new Level2Dto { Text = "Level2" } }
};

subject.Should().BeEquivalentTo(expected);
```

This will result in the following error:

```
Expected property subject.Text to be "Roat", but "Root" differs near "ot" (index 2).
Expected property subject.Level.Text to be "Lavel1", but "Level1" differs near "eve" (index 1).
Expected property subject.Level.Level.Text to be "Level2", but "Leval2" differs near "al2" (index 3).
```

I think what we're looking for is something like:

```
Expected subject.Text to be the same string, but they differ at index 2:
     ↓ (actual)
  "Root"
  "Roat"
     ↑ (expected).

Expected subject.Level.Text to be the same string, but they differ at index 1:
    ↓ (actual)
  "Level1"
  "Lavel1"
    ↑ (expected).

Expected subject.Level.Level.Text to be the same string, but they differ at index 1:
      ↓ (actual)
  "Leval1"
  "Level1"
      ↑ (expected).
```

Some considerations:
* Will the arrows render correctly on non-English operation systems?
* Should we only switch to the new layout when either of the strings are larger than a certain length? E.g. the `HumanReadableLength` defined in `StringValidator`. If both strings are shorter, we use the old layout
* I don't like the "to be the same string". Any better suggestions? Maybe "Expected subject.Text to match the expectation, but it differs at index"
* When either of the strings contain a newline, I think we should we split the output, report the line number and only show the the line whether the difference exists
* When either of the strings is too long, let's show the 10 characters in front and after the mismatching character. I'm thinking that a 80 characters should be the limit.

**Comment by dennisdoomen** [comment]
Maybe. Although I'm not that happy with the inheritance hierarchy of the `StringValidator`. It misusing inheritance.

**Comment by IT-VBFK** [comment]
Moving on to interface implementation? Like `IStringValidator`? Or is this also "misusing"? :)

I ask, because I want to learn more about interfaces and the "real" need of them.. and to understand when to use them..

**Comment by dennisdoomen** [comment]
> Moving on to interface implementation? Like `IStringValidator`? Or is this also "misusing"? :)

You can't really misuse interfaces, unless they become too bloated (hence the Interface Seggregation Principle).

> I don't get the point? I am on a non-english OS (and additionally on a Mac instead of windows). And all seems fine

Than my concern wasn't necessary.

> How about all beyond 20 chars with the "arrow layout"

The 8 came from some research on what people can "read" without having to analyze character by character.

> What about if one is extremely short and the other extremely long? Just print the full short string and a token of the long string, but max 20 characters?

Sure. We'll need to look at some examples anyway and then adjust accordingy.

**Comment by IT-VBFK** [comment]
> Moving on to interface implementation? Like IStringValidator

Is this we should aim for?

**Comment by dennisdoomen** [comment]
> Is this we should aim for?

I don't know. Haven't thought of the design yet. FWIW, an interface is not a goal. Just see what needs to be done and design accordingly.

**Comment by IT-VBFK** [comment]
I thought a litte while about the design changes. 

What came to my mind is following:

```csharp

public interface IStringValidator
{
    void Validate();
}

public interface INegateStringValidator
{
    bool Negate{get; set;}
}

public interface IIgnoreCaseStringValidator
{
    bool IgnoreCase{get; set;}
}

public interface IIgnoreNewLineStringValidator
{
    bool IgnoreNewLineDifferences{get; set;}
}

public interface IStringWildcardValidator 
    : IStringValidator, INegateStringValidator, IIgnoreCaseStringValidator, IIgnoreNewLineStringValidator
{
}

public interface IStringEqualityValidator 
    : IStringValidator, INegateStringValidator, IIgnoreCaseStringValidator
{
}

public interface IStringStartValidator 
    : IStringValidator, INegateStringValidator, IIgnoreCaseStringValidator
{
}

public class StringEqualityValidator : IStringEqualityValidator
{
    public void Validate()
    {

    }

    public bool IgnoreCase{get; set;}
    public bool Negate{get; set;}
}

public class StringWildcardMatchingValidator 
    : IStringWildcardValidator
{
    public void Validate()
    {

    }

    public bool Negate{get; set;}
    public bool IgnoreCase{get; set;}
    public bool IgnoreNewLineDifferences{get; set;}

}

public class StringStartValidator : IStringStartValidator
{
    public void Validate()
    {

    }

    public bool Negate{get; set;}
    public bool IgnoreCase{get; set;}

}

```

The reason to split this is such small pieces was my goal to add e.g. the `Negate` property only to implementations where needed. 

What do you think about that? (Please ignore the naming of the interfaces and missing properties/methods for now :), this was just for getting an overview)

**Comment by dennisdoomen** [comment]
Let's just say that I dislike the inheritance tree in the current implementation because it violates the principles of inheritance. For example, the `StringValidator` has all kinds of methods that don't have an implementation at all. By definition, this means a violation of the Liskov Substitution Principiple. If I had time to redesign it, I would use composition over inheritance. So what you are suggesting is the opposite of what I would do. 

So I would recommend to first define a list of all the use cases we need to support (both the positive as the negative ones), then identify what needs to be done per use case, and only _then_ think how you would convert that to an implementation.

**Comment by vbreuss** [comment]
@dennisdoomen @IT-VBFK :
I created a draft for improving the failure message in #2307.

The general idea is, that for short single-line strings (up to 8 characters) the behaviour remains unchanged. For longer strings I would add the message with the arrows, e.g.:
```csharp
var subject = "this is a long text that differs in between";
var expected = "this was too short";
subject.Should().Be(expected, "because we use arrows now");
```
throws with message
```
Expected subject to be the same string because we use arrows now, but they differ at index 5:
        ↓ (actual)
  "this is a long text…"
  "this was too short"
        ↑ (expected)."
```

Whenever the string was truncated at the beginning or end, I would also add ellipsis `…` to the string, so that it is clearer that it is not the whole string.

If the general approach is okay with you, I would add the missing unit tests (e.g. for `BeEquivalentTo`), but I wanted to discuss the overall approach first!

**Comment by dennisdoomen** [comment]
That looks promising. What will it look like with multi-line strings?

**Comment by vbreuss** [comment]
> That looks promising. What will it look like with multi-line strings?

At the moment, I replace `"\n"` with `"\\n"` and `"\r"` with `"\\r"` respectively (and also adjust the position of the arrows accordingly), so that it is always a single line, e.g.
```csharp
"A\r\nB".Should().Be("A\r\nC");
```
would result in
```
Expected string to be the same string, but they differ at index 3:
        ↓ (actual)
  "A\r\nB"
  "A\r\nC"
        ↑ (expected).
```

**Comment by eNeRGy164** [comment]
How would it look for something really multiline like this: <https://github.com/eNeRGy164/PlantUml.Builder/blob/main/tests/PlantUml.Builder.Examples/SequenceDiagramExampleTests.cs#L16>?

**Comment by vbreuss** [comment]
> How would it look for something really multiline like this: https://github.com/eNeRGy164/PlantUml.Builder/blob/main/tests/PlantUml.Builder.Examples/SequenceDiagramExampleTests.cs#L16?

@eNeRGy164: I ran the following test:
```csharp
var subject = """
@startuml
Alice -> Bob : Authentication Request
Bob --> Alice : Authentication Response

Alice -> Bob : Another authentication Request
Alice <-- Bob : Another authentication Response
@enduml
""";
var expected = """
@startuml
Alice -> Bob : Authentication Request
Bob --> Alice : Authentication Response

Bob -> Alice : Another authentication Request
Alice <-- Bob : Another authentication Response
@enduml
""";

subject.Should().Be(expected);
```
and the output would be
```
Expected subject to be the same string, but they differ at index 93:
                    ↓ (actual)
  "…Response\r\n\r\nAlice ->…"
  "…Response\r\n\r\nBob ->…"
                    ↑ (expected).
```

**Comment by vbreuss** [comment]
> Maybe it would help to add the line number when the number of lines is > 1?

Some possible ideas for the example above:
- Add the line information when more than one line exists in the string, e.g.
   ```
   Expected subject to be the same string, but they differ at index 93 (on line 5):
   ```
- or use line and index (within the line) to identify the position of the first difference (and also omitting the line information, when the string is single-line), e.g.
   ```
   Expected subject to be the same string, but they differ on line 5 at index 0:
   ```

**Comment by vbreuss** [comment]
I slightly adapted the implementation in PR #2307, so that when the string consists of multiple lines, the information contains not only the index of the first mismatch, but also the line and column information, e.g. `but they differ on line 5 and column 1 (index 93)`.

**Comment by dennisdoomen** [comment]
Can you add the example again?

**Comment by vbreuss** [comment]
It's the example from [this comment](https://github.com/fluentassertions/fluentassertions/issues/2050#issuecomment-1723337496):
```csharp
var subject = """
@startuml
Alice -> Bob : Authentication Request
Bob --> Alice : Authentication Response

Alice -> Bob : Another authentication Request
Alice <-- Bob : Another authentication Response
@enduml
""";
var expected = """
@startuml
Alice -> Bob : Authentication Request
Bob --> Alice : Authentication Response

Bob -> Alice : Another authentication Request
Alice <-- Bob : Another authentication Response
@enduml
""";

subject.Should().Be(expected);
```
and the output would now be
```
Expected subject to be the same string, but they differ on line 5 and column 1 (index 93):
                    ↓ (actual)
  "…Response\r\n\r\nAlice ->…"
  "…Response\r\n\r\nBob ->…"
                    ↑ (expected).
```
One advantage is, that I could can now find the position quite quickly in e.g. Notepad++
![image](https://github.com/fluentassertions/fluentassertions/assets/3438234/e85c166e-b4df-4dbc-bb83-4c7e6948b55b)

**Comment by ITaluone** [comment]
Hmm.. since we're all developers... Why not use 0-based indexing? 😉

**Comment by vbreuss** [comment]
I also thought about 0-based indexing, but strangely all code-editors I checked agree on 1-based indexing :-)
- Visual Studio
  ![image](https://github.com/fluentassertions/fluentassertions/assets/3438234/4935f134-05da-4ab5-ad41-cd057975bd26)
- JetBrains Rider
  ![image](https://github.com/fluentassertions/fluentassertions/assets/3438234/8e1a0af0-d69f-431f-b790-67e455b22561)
- Visual Studio Code
  ![image](https://github.com/fluentassertions/fluentassertions/assets/3438234/8fe5fe8e-da58-42b7-8555-cd9872737aed)

**Comment by ITaluone** [comment]
I think that's because text editors are for end users

**Comment by dennisdoomen** [comment]
> Failure messages from fluentassertions are for developers same as IDEs. I think, that if I use 0-based index for line and column, most developers would be confused.

I tend to agree with that.

**Comment by jnyrup** [comment]
When I have to compare text strings from the failure output, I also tend to go into an text editor with 1-based columns.

**Comment by dennisdoomen** [comment]
That settles the discussion. We're going to keep the 1-based indexes.
