### ISSUE TITLE
Collection: `Should().AllBeEquivalentTo()` does not ignore case

### ISSUE THREAD

**Issue by konarx** [fluentassertions/fluentassertions#2064]
### Description

When trying to assert a `Collection` of `string` with `Equivalence` (in order to ignore case), these 2 approaches, although they look the same, they differ.  In fact, the `Should().AllSatisfy(x => x.Should().BeEquivalentTo("this"))` **PASSES** while `Should().AllBeEquivalentTo("this")` **FAILS**

### Complete minimal example reproducing the issue

```csharp
[Test]
public void Test_AllBeEquivalent()
{
    List<string> data = new() {"this", "tHis", "This", "THis", "thIS"};

    data.Should().AllSatisfy(x => x.Should().BeEquivalentTo("this")); //PASS

    data.Should().AllBeEquivalentTo("this"); //FAIL
}
```

### Expected behavior:

`data.Should().AllBeEquivalentTo("this")` should **PASS**

### Actual behavior:

`data.Should().AllBeEquivalentTo("this")` **FAIL**

### Versions

* Fluent Assertions 6.8
* .NET 6

**Comment by jnyrup** [comment]
This is much related to #1947.

We're aware of the confusion between `StringAssertions.BeEquivalentTo` which is case-insensitive and the object graph equivalency which uses [string equality](https://github.com/fluentassertions/fluentassertions/blob/develop/Src/FluentAssertions/Equivalency/Steps/StringEqualityEquivalencyStep.cs).

For v7 we'll look into aligning these APIs better.

The current workaround to have `AllBeEquivalentTo` using case-insensitive string comparisons.

```cs
data.Should().AllBeEquivalentTo("this", opt => opt
    .Using<string>(ctx => ctx.Subject.Should().BeEquivalentTo(ctx.Expectation))
    .WhenTypeIs<string>()
);
```

**Comment by dennisdoomen** [comment]
I propose to have two options on `BeEquivalentTo`:
1. `IgnoringCasing()` which uses `CurrentCultureIgnoreCase`
2. 'Using(StringComparison comparison)` to fine-tune the behavior.

In v7, we then replace the `BeEquivalentTo` on `string` with `Be` and an overload of `Be` that takes a `StringComparison `

**Comment by vbreuss** [comment]
With #2413 you can specify these options, e.g.
```csharp
[Fact]
public void Test_AllBeEquivalent()
{
    List<string> data = new() {"this", "tHis", "This", "THis", "thIS"};

    data.Should().AllBeEquivalentTo("this", o => o.IgnoringCase()); //PASS
}
```
