### ISSUE TITLE
Use BeEquivalentTo to check equality on two classes

### ISSUE THREAD

**Issue by mehdihadeli** [fluentassertions/fluentassertions#2066]
**Before you file a bug, have you:**

* Tried upgrading to newest version of Fluent Assertions, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/fluentassertions/fluentassertions/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Read the [documentation](https://fluentassertions.com/introduction)?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/questions/tagged/fluent-assertions?mixed=1).

### Description
Hi,
I have two classes in my test and I want to check their equality with fluentassertion like bellow code, but for comparing my email address (f => f.Email, s => s.Email.Value)  I get this error :

``` cmd
The subject's member name cannot be a nested path
```

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

``` csharp
    [Fact]
    public async Task should_create_new_customer_in_postgres_db()
    {
        var fakeIdentityUser = MockServersFixture.IdentityServiceMock.SetupGetUserByEmail().Response.UserIdentity;

        var command = new CreateCustomer(fakeIdentityUser!.Email);

        var createCustomerResponse = await SharedFixture.SendAsync(command);

        // Assert
        var createdCustomer = await SharedFixture.ExecuteDbContextAsync(async db =>
            await db.Customers.SingleOrDefaultAsync(x => x.Id == createCustomerResponse.CustomerId));

        //https://fluentassertions.com/objectgraphs/
        createdCustomer.Should().BeEquivalentTo(fakeIdentityUser,
            options =>
                options
                    .WithMapping<UserIdentityDto, Customer>(f => f.Email, s => s.Email.Value)
                    .ExcludingMissingMembers()
                    .Excluding(x => x.Id));
    }

public class Customer : Aggregate<CustomerId>
{
    public Guid IdentityId { get; private set; }
    public Email Email { get; private set; } = null!;
    public CustomerName Name { get; private set; } = null!;
    public Address? Address { get; private set; }
    public Nationality? Nationality { get; private set; }
    public BirthDate? BirthDate { get; private set; }
    public PhoneNumber? PhoneNumber { get; private set; }
}

public record UserIdentityDto(Guid Id, string UserName, string Email, string FirstName, string LastName);

public record Email
{
    public string Value { get; private set; }

    public static Email? Null => null;

    private Email()
    {
    }

    public static Email Create(string value)
    {
        return new Email
        {
            Value = Guard.Against.InvalidEmail(value, new DomainException($"Email {value} is invalid."))
        };
    }

    public static implicit operator Email?(string? value) => value is null ? null : Create(value);
    public static implicit operator string?(Email? value) => value?.Value;
}
```

### Expected behavior:
I want to felexibility for comparing my nested value of my Email valueobject with other class email string property

### Actual behavior:

``` cmd
The subject's member name cannot be a nested path
```

### Versions

* Which version of Fluent Assertions are you using?
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.1.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by dennisdoomen** [comment]
`WithMapping` only supports comparing members at the same level, so what you are trying to do will not work. Given the internal design of the engine behind `BeEquivalentTo`, I can't think of a way to make that work without major redesigns. 

As a workaround you can try using the `Using`/`When` construct. See https://fluentassertions.com/objectgraphs/#equivalency-comparison-behavior

**Comment by mehdihadeli** [comment]
@dennisdoomen Thanks, your solution works fine.

**Comment by mehdihadeli** [comment]
@dennisdoomen Can I Extend it myself, do this level of compare? What is the reason for preventing mapping in nested level?

**Comment by dennisdoomen** [comment]
> Given the internal design of the engine behind BeEquivalentTo, I can't think of a way to make that work without major redesigns.

Because it's complicated. The entire recursive algorithm always assumes we're comparing members between the subject and the expectation at the same level. You can try yourself, but it's going to a big job. I'm not sure it's worth it.

**Comment by mehdihadeli** [comment]
Yes, you're right, it doesn't worth, and maybe it is better I do these assertions manually one by one. Also, I can't implement comparing emails between two objects with `Using/When`, I get error.

``` csharp
createdCustomer.Should().BeEquivalentTo(fakeIdentityUser,
    options =>
        options
            .Using<Email>(ctx => ctx.Subject.Value.Should().Be(ctx.Expectation))
            .When(info => info.Path.EndsWith("Email"))
            .ExcludingMissingMembers()
            .Excluding(x => x.Id));
```
