### ISSUE TITLE
CS1003: Syntax error ,',' is ecpected. 

### ISSUE THREAD

**Issue by EdlenJ** [fluentassertions/fluentassertions#2069]
![Aw](https://user-images.githubusercontent.com/113501464/208811755-f9060235-f2d8-4c18-837b-7bf8b97e29e0.PNG)

anyone know or experience this error too?

**Comment by jnyrup** [comment]
Looks like you're using [FluentAssertions for Unity](https://github.com/BoundfoxStudios/fluentassertions-unity).
Please look at their page where to ask questions.

**Comment by EdlenJ** [comment]
Hello,
Yes I'm using the Unity version, how do I fix this? or it is not available
to use now in unity?

thank you for your time.

**Comment by jnyrup** [comment]
From the linked above:

> If you encouter any bugs, which are related to the package and not to FluentAssertions itself, feel free to open an issue.

So please open an issue in their issue tracker instead.

**Comment by EdlenJ** [comment]
Can I ask for the link to the issue tracker?, Im very sorry for the
inconvenience.

**Comment by jnyrup** [comment]
https://github.com/BoundfoxStudios/fluentassertions-unity

**Comment by dennisdoomen** [comment]
@EdlenJ please read the response instead of repeating the question. Jonas' first response should already be clear enough.
