### ISSUE TITLE
Allow checking isMatchingAttributePredicate on BeDecoratedWith method on properties

### ISSUE THREAD

**Issue by jamestoyer** [fluentassertions/fluentassertions#207]
It feels a little strange to me to be allowed to check that certain properties are set on an attribute that is added to a type, but not on a property. For example this is valid

```
typeWithAttribute.Should()
  .BeDecoratedWith<DummyClassAttribute>(a => ((a.Name == "Unexpected") && a.IsEnabled));
```

but this is not

```
propertyWithAttribute.Should()
  .BeDecoratedWith<DummyClassAttribute>(a => ((a.Name == "Unexpected") && a.IsEnabled));
```

Is there a reason for this or has it never come up before?

**Comment by dennisdoomen** [comment]
Hi @jamestoyer. I don't see why it wouldn't work. In fact, [several specs](https://github.com/dennisdoomen/fluentassertions/blob/develop/FluentAssertions.Shared.Specs/PropertyInfoAssertionSpecs.cs) exist to prove that. Are you sure `propertyWithAttribute` is of type `PropertyInfo`?

**Comment by jamestoyer** [comment]
Yeah, it is. I've just validated it with this code that it won't compile with version 3.2.2:

```
var type = typeof(CompletedExecutionQueueItem);
PropertyInfo property = type.GetProperty("WorkflowExecutionId");
property.Should().BeDecoratedWith<JsonPropertyAttribute>(a => a.Required == Required.Always)
```

where `CompletedExecutionQueueItem` is simply this

```
internal class ComposerCompletedExecutionQueueItem
{
    [JsonProperty("executionId", Required = Required.Always)]
    public string WorkflowExecutionId { get; set; }
}
```

The only overload I get for `BeDecoratedWith` is the one that takes `string because = "", params object[] reasonArgs`. I've taken a quick look at the source and it goes to `PropertyInfoAssertions` which doesn't seem to have the same overload as the type equivalent.

**Comment by vossad01** [comment]
Would this work for you?

```
property.Should().BeDecoratedWith<JsonPropertyAttribute>()
    .Which.Required.Should().Be(Required.Always);
```

**Comment by jamestoyer** [comment]
@vossad01 I've just tested this now. It does appear to work as hoped, although I'm not sure I like it as much. I'll go with what you've suggested for now though.

**Comment by dennisdoomen** [comment]
Ah shoot, I completely missed the lambda expression.

**Comment by dennisdoomen** [comment]
This was already implemented by the [refactoring work](https://github.com/dennisdoomen/fluentassertions/commit/585ed8ce4acb4cf2e125eded1aa022d1650beaa9) done as part of 3.5.
