### ISSUE TITLE
BeInDescendingOrder does not work correctly

### ISSUE THREAD

**Issue by deadmann** [fluentassertions/fluentassertions#2073]
### Description

BeInDescendingOrder does not validate the Descending order and throws, but work with Ascending data....
I'm using model data, and filtering out a single property for ordering test...
I trace the code into FluentValidation code, and it seem to be Okay, I expect it to work, but it doesn't

### Complete minimal example reproducing the issue

![image](https://user-images.githubusercontent.com/1919241/209468445-f6419342-c467-4433-b163-ee3095188794.png)

### Expected behavior:

To Pass without failure

### Actual behavior:

throws following error:

```
Xunit.Sdk.XunitException: Expected orderedResultItem {
    Mores.Warehouse.Core.Shared.Response.Zone.GetWarehouseStockQuantityByVariantItemResponse
    {
        Id = {885c6cfa-39a1-4b1c-b0bd-d00669aa3890}, 
        SalableQuantity = 8L, 
        TotalQuantity = 8L, 
        UnsalableQuantity = 0L, 
        WarehouseTitle = "Warehouse 2"
    }, 
    Mores.Warehouse.Core.Shared.Response.Zone.GetWarehouseStockQuantityByVariantItemResponse
    {
        Id = {211ef87e-e535-4b59-a1f3-f9570eee808b}, 
        SalableQuantity = 4L, 
        TotalQuantity = 4L, 
        UnsalableQuantity = 0L, 
        WarehouseTitle = "Warehouse1"
    }
}
 to be ordered "by WarehouseTitle" and result in {
    Mores.Warehouse.Core.Shared.Response.Zone.GetWarehouseStockQuantityByVariantItemResponse
    {
        Id = {211ef87e-e535-4b59-a1f3-f9570eee808b}, 
        SalableQuantity = 4L, 
        TotalQuantity = 4L, 
        UnsalableQuantity = 0L, 
        WarehouseTitle = "Warehouse1"
    }, 
    Mores.Warehouse.Core.Shared.Response.Zone.GetWarehouseStockQuantityByVariantItemResponse
    {
        Id = {885c6cfa-39a1-4b1c-b0bd-d00669aa3890}, 
        SalableQuantity = 8L, 
        TotalQuantity = 8L, 
        UnsalableQuantity = 0L, 
        WarehouseTitle = "Warehouse 2"
    }
}
.
```

### Versions

* Which version of Fluent Assertions are you using?
6.7  &  6.8
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.1.
.NET Core 6.x

**Comment by deadmann** [comment]
I found some extra information, which fixed my test but may be correct or incorrect...

My 1st warehouse name was: `Warehouse1`
My 2nd warehouse name was: `Warehouse 2` with one extra [`space`]

I changed `Warehouse 2` to `Warehouse2` (removing the `space`) and it fixed the issue

PostgreSQL returned DESC in the order you see above, for both data, either `Warehouse 2` or `Warehouse2` returned the same result...
but fluent assertions calculate these types of characters in another order!
so I just suggest that you still review the code.

**Comment by jnyrup** [comment]
It's difficult to help you, when you don't include any code. We cannot execute your screenshot. 

As written in the issue template we expect you to read. 

> Complete means the code snippet can be copied into a unit test method in a fresh C# project and run. Minimal means it is stripped from code not related to reproducing the issue.

See e.g. https://stackoverflow.com/help/minimal-reproducible-example

**Comment by dennisdoomen** [comment]
Fluent Assertions is doing exactly what it should be doing (no pun intended). It relies on `Comparer<TSelector>.Default` and therefor completely delegates the ordering to .NET itself. Just run the below code in [.NET Fiddle](https://dotnetfiddle.net/)

```
using System;
using System.Collections.Generic;
using System.Linq;

public class Program
{
	public static void Main()
	{
		var list = new List<string>() {"Warehouse1", "Warehouse 2"};
		
		foreach (var item in Enumerable.OrderByDescending(list, i => i))
		{
			Console.WriteLine(item);
		}
	}
}
```

**Comment by deadmann** [comment]
> It's difficult to help you, when you don't include any code. We cannot execute your screenshot.
> 
> As written in the issue template we expect you to read.
> 
> > Complete means the code snippet can be copied into a unit test method in a fresh C# project and run. Minimal means it is stripped from code not related to reproducing the issue.
> 
> See e.g. https://stackoverflow.com/help/minimal-reproducible-example

``` C#
        { 
            // Test Order - Based on Test Two Warehouse
            // Act Order
            var requestOrder = new GetWarehouseStockQuantityByVariantRequest
            {
                PageNo = 1,
                PageSize = 10,
                Orders = new Dictionary<string, SortDirection>
                {
                    {"WarehouseTitle", SortDirection.DESC}
                },
                VariantPermanentId = AppsFixture.ProductService.VariantPermanentId6,
                CountUnitPermanentId = AppsFixture.ProductService.CountUnitPermanentId1
            };
            
            var result = await PostAsync<GetWarehouseStockQuantityByVariantResponse>(
                GetUriBy(ScopeId, "getWarehouseStockQuantityByVariant"), 
                requestOrder, 
                token, HttpStatusCode.OK);
            
            // Assert Order
            var orderedResultItem = result
                .Should().NotBeNull()
                .And.BeOfType<GetWarehouseStockQuantityByVariantResponse>()
                .Subject.As<GetWarehouseStockQuantityByVariantResponse>()
                .Items;
            
            result.VariantPermanentId.Should().Be(AppsFixture.ProductService.VariantPermanentId6);
            result.CountUnitPermanentId.Should().Be(AppsFixture.ProductService.CountUnitPermanentId1);
            
            orderedResultItem.Should().HaveCount(2);
            orderedResultItem.Should()
                .BeInDescendingOrder(o => o.WarehouseTitle);
        }
```

This is the code, and the service is delegated to the Service which is delegated to the API which delegates to the repository, which fetches data using Dapper, and performs PostgreSQL ordering... which leads to the hassle and knowing of this issue...

**Comment by jnyrup** [comment]
The new code posted is still not a _complete_ reproducing example as it cannot be run.

Anyways, Dennis already pointed out that we rely on how .NET sorts strings.

I'm on mobile right now, so cannot double check if the default string comparison is culture aware.
