### ISSUE TITLE
Declare what files should be considered as source and documentation

### ISSUE THREAD

**Issue by ITaluone** [fluentassertions/fluentassertions#2098]
### Description

Now I think there is a slight inconsistency of what files are considered as source and documentation changes.

For example: only files inside the `docs` folder considered as `documentation changes` and triggers a spell check, and any other files (e.g. `.github/*`, `CONTRIBUTING.md`, `cSpell.json`,...) are considered as `source change`.

I propose a more detailed way of this consideration.

Source changes:
`.nuke/**/*`
`Build/**/*`
`Src/**/*`
`Tests/**/*`
`build.*`
`CNAME`
`Directory.Build.props`
`FluentAssertion.sln`
`FluentAssertion.sln.DotSettings`
`GitVersion.yml`
`global.json`
`nuget.config`
`Rules.ruleset`
`TestRules.ruleset`

Documentation changes:
`docs/**/*`
`CONTRIBUTING.md`
`cSpell.json`
`LICENSE`
`README.md`

**Comment by jnyrup** [comment]
Would it be easier to define documentation as you proposed (or similar) and everything else as source?

I'm trying to avoid:
* having to maintain this list and 
* pipelines not being run because I missed that I e.g. added a source file not on the list.

**Comment by IT-VBFK** [comment]
If you can live with running the build even when the `build.yml` is changed..

**Comment by dennisdoomen** [comment]
> Would it be easier to define documentation as you proposed (or similar) and everything else as source?
> 
> I'm trying to avoid:
> 
> * having to maintain this list and
> * pipelines not being run because I missed that I e.g. added a source file not on the list.

I agree with @jnyrup here. I don't even care if the build runs too often and I most definitely want to maintain a list.

**Comment by IT-VBFK** [comment]
Cool will do that..



> Can I add that to #2093?

If this is ok, I will add this few lines to this PR?

**Comment by jnyrup** [comment]
> Cool will do that..
> 
> > Can I add that to #2093?
> 
> If this is ok, I will add this few lines to this PR?

No, please.
It's much easier for us to manage and review more PRs that have a narrower focus.
