### ISSUE TITLE
BeOneOf for object comparisons with custom comparer support

### ISSUE THREAD

**Issue by xmarshal** [fluentassertions/fluentassertions#2112]
### Background and motivation

Support for custom comparer to compare objects

### API Proposal

```C#
public class ObjectAssertions<TSubject, TAssertions> : ReferenceTypeAssertions<TSubject, TAssertions>
    where TAssertions : ObjectAssertions<TSubject, TAssertions>
{
    public AndConstraint<TAssertions> BeOneOf<TExpectation>(IEnumerable<TExpectation> validValues, IEqualityComparer<TExpectation> comparer, string because = "", params object[] becauseArgs);
}
```

### API Usage

```C#
var obj = new SomeClass(1);
var expected = new[] { new SomeClass(1), new SomeClass(2), new SomeClass(3) };
obj .Should().BeOneOf(expected, new SomeClassEqualityComparer ());

internal class SomeClass
{
    public SomeClass(int key)
    {
        Key = key;
    }

    public int Key { get; }

    public override string ToString()
    {
        return $"SomeClass({Key})";
    }
}

internal class SomeClassEqualityComparer : IEqualityComparer<SomeClass>
{
    public bool Equals(SomeClass x, SomeClass y)
    {
        if (ReferenceEquals(x, y))
        {
            return true;
        }

        if (ReferenceEquals(x, null))
        {
            return false;
        }

        if (ReferenceEquals(y, null))
        {
            return false;
        }

        if (x.GetType() != y.GetType())
        {
            return false;
        }

        return x.Key == y.Key;
    }

    public int GetHashCode(SomeClass obj)
    {
        return obj.Key;
    }
}
```

**Comment by dennisdoomen** [comment]
If we add this to `BeOneOf`, we _must_ also add this to `Be` and `NotBe` for consistency. Assuming @jnyrup agrees, are you willing to include that in your PR @xmarshal ?

**Comment by jnyrup** [comment]
In the proposed signature `validValues` can have a different type `TExpectation` than the subject `TSubject`.
```cs
    public AndConstraint<TAssertions> BeOneOf<TExpectation>(IEnumerable<TExpectation> validValues, IEqualityComparer<TExpectation> comparer, string because = "", params object[] becauseArgs);
```

With the example usage you provide, re-using `TSubject` for `validValues` should suffice.

```cs
    public AndConstraint<TAssertions> BeOneOf(IEnumerable<TSubject> validValues, IEqualityComparer<TSubject> comparer, string because = "", params object[] becauseArgs);
```

Also only `BeEquivalentTo` in `ObjectAssertions` currently uses `TExpectation`.
Can you clarify if this is unintentional or why we should add `TExpectation`.


For even more consistency, we should also add this to `BeOneOf` and `[Not]Be` for `ComparableTypeAssertions`.

For discoverability, this topic is related to #699.

**Comment by xmarshal** [comment]
> In the proposed signature `validValues` can have a different type `TExpectation` than the subject `TSubject`.

Mostly `obj.Should()` extension method returns non-generic `ObjectAssertions`
So `TSubject` will be `object`
May be we should add  `ObjectAssertions<TSubject> :  ObjectAssertions<TSubject, ObjectAssertions<TSubject>>` instead of `ObjectAssertions :  ObjectAssertions<object, ObjectAssertions>` and the `TSubject` can be used for `IEnumerable<TSubject> validValues`

**Comment by xmarshal** [comment]
> If we add this to `BeOneOf`, we _must_ also add this to `Be` and `NotBe` for consistency. Assuming @jnyrup agrees, are you willing to include that in your PR @xmarshal ?

I will add when we reach an agreement for API

**Comment by dennisdoomen** [comment]
> May be we should add ObjectAssertions<TSubject> :  ObjectAssertions<TSubject, ObjectAssertions<TSubject>> instead of ObjectAssertions :  ObjectAssertions<object, ObjectAssertions> and then TSubject can be used for IEnumerable<TSubject> validValues

That would require a `Should<T>` as well. But due to the way overload resolution works, it will overrule every other `Should` extension method.

**Comment by xmarshal** [comment]
50
> That would require a `Should<T>` as well. But due to the way overload resolution works, it will overrule every other `Should` extension method.

> For even more consistency, we should also add this to `BeOneOf` and `[Not]Be` for `ComparableTypeAssertions`.

So what I should do next?

**Comment by dennisdoomen** [comment]
Nothing. I'm waiting for @jnyrup's opinion.

**Comment by jnyrup** [comment]
An alternative API
```cs
public class ObjectAssertions : ObjectAssertions<object, ObjectAssertions>
{
    public AndConstraint<ObjectAssertions> BeOneOf<TExpectation>(IEnumerable<TExpectation> validValues, IEqualityComparer<TExpectation> comparer, string because = "", params object[] becauseArgs);
}

public class ObjectAssertions<TSubject, TAssertions> : ReferenceTypeAssertions<TSubject, TAssertions>
    where TAssertions : ObjectAssertions<TSubject, TAssertions>
{
    public AndConstraint<TAssertions> BeOneOf(IEnumerable<TSubject> validValues, IEqualityComparer<TSubject> comparer, string because = "", params object[] becauseArgs);
}
```

The difference comes for classes deriving from `ObjectAssertions<TSubject, TAssertions>` e.g. `HttpResponseMessageAssertions`.
The proposed API would allow `HttpResponseMessageAssertions.BeOneOf()` to take input of arbitrary types, while it currently only allows input of `HttpResponseMessage`.

**Comment by xmarshal** [comment]
alternative API added
should I add  `Be` and `NotBe` and what signature You suggest?

**Comment by dennisdoomen** [comment]
> An alternative API

Looks good to me.

**Comment by xmarshal** [comment]
`Be` and `NotBe` with comparer added

**Comment by jnyrup** [comment]
The "alternative API" together with `Be` and `NotBe` is approved 👍

**Comment by xmarshal** [comment]
ok will add test soon

**Comment by Corniel** [comment]
If `TSubject` imlements `IEquatable<TSubject>` I would hope that providing `IEqualityComparer<TSubject>` is optional?

**Comment by jnyrup** [comment]
> If `TSubject` imlements `IEquatable<TSubject>` I would hope that providing `IEqualityComparer<TSubject>` is optional?

If not providing an `IEqualityComparer`, wouldn't the existing `BeOneOf` suffice?
See this example: https://dotnetfiddle.net/N2Rpt6
