### ISSUE TITLE
Explicitly implemented properties on the subject are not found during object graph comparison

### ISSUE THREAD

**Issue by edwardbarford** [fluentassertions/fluentassertions#2146]
```cs
interface IPerson
{
    string Name { get }
}

class Person : IPerson
{
    string IPerson.Name => "Bob";
}

IPerson person = new Person();

person.Should().BeEquivalentTo(new { Name = "Bob" });
```

Expected: Should not throw 
Actual: Throws with message "Expectation has property person.Name that the other object does not have."

**Comment by dennisdoomen** [comment]
That's indeed a bug and a big surprise for me since we have several tests covering explicit interface implementations.

**Comment by jonathonchase** [comment]
```
public interface IFoo
{
    string Bar { get;}
}

public class Foo : IFoo {
    string IFoo.Bar => "Bar";
    public string Bar => "Anon";
}

IFoo foo = new Foo();
var anon = new { Bar = "Anon" };

foo.Should().BeEquivalentTo(anon); // Succeeds, Anon matches Anon
anon.Should().BeEquivalentTo(foo); // Fails, Bar does not match Anon
```

It appears that only the 'expected' operand is being used to determine the type for the purposes of trying to match on the explicitly implemented interface properties. 

As far as I know, the type is only known at compile time for the purposes of determining an explicit interface. You could extract if from a generic type parameter, but the entry point for Object Assertions is `Should(this object actualValue)`. `Should<T>(this T actualValue)` would allow you to get the interface type to know what properties to pull down from the explicit interface, but would likely conflict with the overloads. I suspect this is why only the expected value is being used to determine explicit interface comparisons in the first place.

Trying to check each interface the object implements hits the problem of knowing which one is the correct one to utilize. Given that explicit interface implementations are typically used for resolving naming conflicts between interfaces this is a big problem.

**Comment by dennisdoomen** [comment]
> But would likely conflict with the overloads.

That's indeed _exactly_ why we can't introduce `Should<T>(this T value)`.

**Comment by dennisdoomen** [comment]
So the challenge is that because of the fact we use extension methods and the fact that we can't add an overload of `Should` that is generic, `BeEquivalentTo` doesn't know that the subject-under-test was declared as `IPerson`. The only thing we have is the run-time type `Person`. But since `Person` explicitly implements `IPerson`, technically we shouldn't be able to see `Name` when looking at `Person`. So, the only way to fix this is to include both "normal" properties as well as explicitly implemented properties.

**Comment by dennisdoomen** [comment]
Any opinions on this @jnyrup? Otherwise I'm going to change the logic to include explicitly implemented properties.

**Comment by jnyrup** [comment]
It sounds reasonable to me to include explicitly implemented properties on the subject.
