### ISSUE TITLE
Inconsistent results of comparing anonymous types using BeEquivalentTo()

### ISSUE THREAD

**Issue by yuliapu** [fluentassertions/fluentassertions#2161]
### Description

Using `.Should().BeEquivalentTo()` on anonymous types may provide different results when swapping places of actual and expected values.

### Reproduction Steps

```
var actual = new { A = "1", B = new { B2 = new[] { "one", "two", "three" } } };
var expected = new { A = "1" };

actual.Should().BeEquivalentTo(expected);
expected.Should().BeEquivalentTo(actual);
```

### Expected behavior

Both assertions should either pass or fail.

### Actual behavior

```
var actual = new { A = "1", B = new { B2 = new[] { "one", "two", "three" } } };
var expected = new { A = "1" };

actual.Should().BeEquivalentTo(expected);
expected.Should().BeEquivalentTo(actual);
```
`actual.Should().BeEquivalentTo(expected); `passes, but the second assertion `expected.Should().BeEquivalentTo(actual);` does not.

**Comment by dennisdoomen** [comment]
`BeEquivalenTo` was never designed to have symmetric behavior. It's the expectation that drives the comparison, including what members to include.
