### ISSUE TITLE
`AllSatisfy()` fails on empty collections

### ISSUE THREAD

**Issue by dennisdoomen** [fluentassertions/fluentassertions#2169]
### Discussed in https://github.com/fluentassertions/fluentassertions/discussions/2143

<div type='discussions-op-text'>

<sup>Originally posted by **ArneMancofi** March  8, 2023</sup>
### Description

`new object[0].Should().AllSatisfy(o => { });` fails with 
> Expected collection to contain only items satisfying the inspector, but collection is empty.

This does not implement the documented effect of `AllSatisfy`:
> Asserts that a collection contains only items which meet the criteria provided by the inspector

In particular, any empty collection should always pass this test.

The bug is probably due to two code lines in 

https://github.com/fluentassertions/fluentassertions/blob/c3b9a7072b790dea7ce16b2ddbef933f31f6aa1f/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs#L2929-L2930

### Reproduction Steps

```csharp
// Arrange
var emptyArray = new object[0];
// Act
// Assert
emptyArray.Should().AllSatisfy(o => { });
```

### Expected behavior

The test should pass without throwing an exception.

### Actual behavior

The test fails with exception
> Expected collection to contain only items satisfying the inspector, but collection is empty.

### Regression?

This has probably always been this way.

### Known Workarounds

Code like this would be a workaround:
```csharp
if (collection.Any()) collection.Should().AllSatisfy(...);
```

However, reading the documentation of `.AllSatisfy()`, it should not be necessary.

### Configuration

FluentAssertions 6.9.0
.NET 6.0

### Other information

The [WikiPedia article on universal quantification](https://en.wikipedia.org/wiki/Universal_quantification) states that 
> By convention, the formula ∀x∈∅ P(x) is always true, regardless of the formula P(x)

so it is the documentated behaviour of `.AllSatisfy()` that is conventionally correct, and the implementation that is not.</div>

**Comment by cbersch** [comment]
That is also how LINQ-All behaves
````
new int[0].All(x => x > 0); // yields true
````

**Comment by dennisdoomen** [comment]
What do you think @jnyrup? Something for v7?
