### ISSUE TITLE
SpacesPerIndentionLevel is not respected

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#2197]
### Description

c4e7ca7058e53f3db9b96a7eb17a2757d7cd77f6 exposed the instance property `DefaultValueFormatter.SpacesPerIndentionLevel` to ease the implementation of custom formatters.

bde29a65651343bd2386674d5226ab393153e840 changed `DefaultValueFormatter` to use the static `FormattedObjectGraph.SpacesPerIndentation` instead.

### Reproduction Steps

See the exinsting test `When_defining_a_custom_value_formatter_it_should_respect_the_overrides`.
The `CustomClassValueFormatter` overrides `DefaultValueFormatter.SpacesPerIndentionLevel` to `8`, but in the formatted output the indentation is 4 because `FormattedObjectGraph.SpacesPerIndentation` is unconditionally used.

### Expected behavior

`DefaultValueFormatter.SpacesPerIndentionLevel` should be respected when deriving from `DefaultValueFormatter`.

### Actual behavior

`DefaultValueFormatter.SpacesPerIndentionLevel` is never used.

### Regression?

Not from a consumer perspective since both commits were part of 6.0.0.

### Other information

Consider whether we should remove `DefaultValueFormatter.SpacesPerIndentionLevel` since it has never worked, and I'm not sure why would would want to have different indentation levels depending on the object type.
As I recall I simply exposed that property for maximum flexibility.

We could probably also adjust `SpacesPerIndentionLevel` to default to `FormattedObjectGraph.SpacesPerIndentation` and make it work.

**Comment by jnyrup** [comment]
Also when I change the test to have a property with members, it isn't formatted nicely.
Here the value of `Custom` is indented by `FormattedObjectGraph.SpacesPerIndentation` instead of `DefaultValueFormatter.SpacesPerIndentionLevel`.
To have a custom amount indentation I guess it would require that `FormattedObjectGraph` tracks the amount of indentation in terms of number of spaces instead of number of levels.

```cs
[Fact]
public void When_defining_a_custom_value_formatter_it_should_respect_the_overrides()
{
    // Arrange
    var value = new CustomClass() { Custom = new CustomClass() };
    var formatter = new CustomClassValueFormatter();
    using var _ = new FormatterScope(formatter);

    // Act
    string str = Formatter.ToString(value);

    // Assert
    str.Should().Match(
        "*CustomClass" + Environment.NewLine +
        "{" + Environment.NewLine +
        "        IntProperty = 0" + Environment.NewLine +
        "}*");
}

private class CustomClass
{
    public int IntProperty { get; set; }

    public string StringProperty { get; set; }

    public object Custom { get; set; }
}
```

```
Expected str to match "*CustomClass
{
        IntProperty = 0
}*", but "CustomClass
{
        Custom = 
    CustomClass
    {
            Custom = <null>, 
            IntProperty = 0
    }, 
        IntProperty = 0
}" does not.
```

**Comment by dennisdoomen** [comment]
> Consider whether we should remove `DefaultValueFormatter.SpacesPerIndentionLevel` since it has never worked, and I'm not sure why would would want to have different indentation levels depending on the object type.

I agree. I don't see much value allowing individual formatters to override the number of spaces anyway.

**Comment by jnyrup** [comment]
We will remove this broken feature in v7.
