### ISSUE TITLE
ExcludingNestedObjects option does not behave as expected

### ISSUE THREAD

**Issue by andrewslavin** [fluentassertions/fluentassertions#2210]
### Description

`ExcludingNestedObjects` option does not behave as expected.

### Reproduction Steps

```csharp
class Parent
{
    public int Id { get; set; }
    public Child Child { get; set; }
}

class Child
{
    public int Id { get; set; }
}

var p1 = new Parent { Id = 0, Child = new Child { Id = 1 } };
var p2 = new Parent { Id = 0, Child = new Child { Id = 2 } };

p1.Should().BeEquivalentTo(p2, o => o.ExcludingNestedObjects());
```

### Expected behavior

Assertion passes, because help text for `ExcludingNestedObjects` says `Causes the structural equality check to exclude nested collections and complex types`, and `Child` is a complex type.

### Actual behavior

Assertion fails with the message
```
Expected property p1.Child to be Child
{
    Id = 2
}, but found Child
{
    Id = 1
}
```

**Comment by dennisdoomen** [comment]
This is by design. What you're saying with `ExcludingNestedObjects` is that FA should _not_ traverse the properties of the object returned by the `Child` property and instead fall back on a basic `Equals` call. Since the default implementation of `Equals` on a class is doing a reference equality, it fails.

**Comment by andrewslavin** [comment]
Thanks @dennisdoomen, that makes sense. Two suggestions then:
1. Improve `ExcludingNestedObjects` help text to better explain how exactly complex properties will be compared.
2. Add a new option, that will allow to exclude complex properties completely, not just from structural check.

**Comment by dennisdoomen** [comment]
> Add a new option, that will allow to exclude complex properties completely, not just from structural equality check.

What do you mean with that?

**Comment by andrewslavin** [comment]
I was going to reply

> Add something like `ExcludeComplexProperties`, which will completely ignore complex properties when comparing expected and actual, like I can completely ignore one property now using `Excluding`.

But then I read help text for `Excluding` and it says `Excludes the specified (nested) member from the structural equality check`. So it doesn't exclude the member completely, it only switches it from structural check to basic `Equals` call? Then I do not understand why in my test
```csharp
p1.Should().BeEquivalentTo(p2, o => o.ExcludingNestedObjects());
```
fails, but
```csharp
p1.Should().BeEquivalentTo(p2, o => o.Excluding(p => p.Child));
```
succeeds.

**Comment by dennisdoomen** [comment]
`Excluding` completely excludes the property or field. `ExcludingNestedObjects` doesn't exclude the property or field, but doesn't do a recursive comparison on the properties of fields of the object returned by that property.

**Comment by andrewslavin** [comment]
> `Excluding` completely excludes the property or field. `ExcludingNestedObjects` doesn't do a recursive comparison.

Yes that's what I got in my tests. I think documentation needs some improvement because descriptions for both options talk about "structural" equality only:

- `ExcludingNestedObjects`: Causes the structural equality check to exclude nested collections and complex types.
- `Excluding`: Excludes the specified (nested) member from the structural equality check.

Description for `Excluding` should not say "structural", and description for `ExcludingNestedObjects` should explain better what "structural equality" means. I do not think people pay attention to the word "structural" and presume that properties will be just excluded from equality check. That's what I presumed.

**Comment by dennisdoomen** [comment]
> Yes that's what I got in my tests. I think documentation needs some improvement because descriptions for both options talk about "structural" equality only:

I did that in #2211 

> Description for `Excluding` should not say "structural", and description for `ExcludingNestedObjects` should explain better what "structural equality" means. I do not think people pay attention to the word "structural" and presume that properties will be just excluded from equality check. That's what I presumed.

We have _extensive_ documentation on this structural comparison [here](https://fluentassertions.com/objectgraphs/). Although I do agree that the documentation and the code uses different terminology. That's something for v7 to fix.

**Comment by dennisdoomen** [comment]
> On a separate note, would it be feasible to add smth like `ExcludeComplexTypes`, which will completely exclude all complex properties and fields?

That would be an entirely new feature. Please raise a separate feature request for that.
