### ISSUE TITLE
obj.Should().NotBeNull() loses type info

### ISSUE THREAD

**Issue by ITaluone** [fluentassertions/fluentassertions#2212]
### Description

Is it by design or actually a wanted behavior that if I assert on a strongly typed object with `.NotBeNull()` the complete type information is lost, if I continue the assertion with `.And`.

For me this seems a litte odd if I have already a strongly typed object.

### Reproduction Steps

```csharp
// Arrange
MyDto subject = HowIGetMyDto();

// Act / Assert
subject.Should().NotBeNull().And.ADtoProperty.Should.Be("this"); 

```

### Expected behavior

Because I have a strongly typed object already, I could continue the assertion without workarounds of `.BeAssignableTo<MyDto>`, which seems a litte redundant to me.

### Actual behavior

My IDE complains about "Cannot resolve symbol ADtoProperty", because `ADtoProperty` is not available on `object`

### Regression?

No

### Known Workarounds

Make use of `.BeAssignableTo<MyDto>.Subject`

### Configuration

FA 6.11.0
Net6.0

**Comment by IT-VBFK** [comment]
As in here: 
https://github.com/fluentassertions/fluentassertions/blob/672bd5699e54d7cb574228334b367f2f8a0fef1f/Src/FluentAssertions/AssertionExtensions.cs#LL946C1-L949C6

This is shorter but still a "redundant" cast

**Comment by ITaluone** [comment]
Ok I see :)
