### ISSUE TITLE
[API Proposal]: Add support for exposing accessing custom attributes for equivalency config and IEquivalencyStep

### ISSUE THREAD

**Issue by brooknovak** [fluentassertions/fluentassertions#2233]
### Background and motivation

I want to compare everything in an object EXCEPT if there is an attribute present.
Specifically im comparing very complex serialized XML structures - and I want to exclude properties declare with `XmlIgnoreAttribute`. But there is just no way to work around this AFAIK.

### API Proposal

The `IMemberInfo` abstraction hides the ability to do advanced inspections based on the declared member's attributes.
Likewise the `INode` in `IEquivalencyStep` abstracts away this info.
We could expose this info to these abstractions.

### API Usage

```C#
 actual.Should().BeEquivalentTo(expected, cfg => cfb.Excluding((IMemberInfo mi) => mi.HasAttribute<XmlIgnoreAttribute>()))
 ```

### Alternative Designs

A higher abstraction on the equivalency configuration `.ExcludingAttribute<XmlIgnoreAttribute>()`
But id rather solve this at a lower level to allow for more complex equivalency check logic to be combined with other things

### Risks

unsure ...

**Comment by brooknovak** [comment]
Actually duh .. you can access this info:
`.Excluding((IMemberInfo mi) => mi.DeclaringType.GetMember(mi.Name).Any(mi => mi.HasAttribute<IgnoreAttribute>()))`
Wasn't obvious! but does the job

**Comment by dennisdoomen** [comment]
And you can wrap that in a nice custom extension method on top of `IEquivalencyOptions`
