### ISSUE TITLE
NUnit.Framework.Internal.Commands.TestMethodCommand.Execute - Setting ResultState to Success when HasExpectedResult is false

### ISSUE THREAD

**Issue by gakibbie** [fluentassertions/fluentassertions#2244]
### Description

//ACT
var act = async () => await objUnderTest.Handle(context.Object, request);
//ASSERT
act.Should().ThrowAsync<Exception>().Where(e => e.Message.Contains("asdf"));

given the message does not contain "asdf" the result is still success.

My AssertException is firing correctly with:
Expected exception where e.Message.Contains("asdf"), but the condition was not met by:"
""
"{System.Exception: could not find activity design  .<..remainder removed for brevity>

At this point in the stack I am dropped into the NUnit.Framework.Internal.Commands.TestMethodCommand.Execute method where my Result it then set with: context.CurrentResult.SetResult(ResultState.Success);

Using:
//ACT
var act = () => objUnderTest.Handle(context.Object, request).Result;

//ASSERT
act.Should().Throw<Exception>().WithMessage("asdf");

Behaves as expected with the resulting message of:
Message: 
    Expected exception message to match the equivalent of "asdf", but "could not find activity design" does not.

        
        

### Reproduction Steps

```csharp
// Arrange
string input = "MyString";

// Act
char result = input[0];

// Assert
result.Should().Be('M');
```

### Expected behavior

A response of:
Message: 
    Expected exception message to match the equivalent of "asdf", but "could not find activity design" does not.

### Actual behavior

Test Passes

### Regression?

Didn't test

### Known Workarounds

Doesn't work:
//ACT
var act = async () => await objUnderTest.Handle(context.Object, request);
//ASSERT
act.Should().ThrowAsync<Exception>().Where(e => e.Message.Contains("asdf"));

Works:
//ACT
var act = () => objUnderTest.Handle(context.Object, request).Result;

//ASSERT
act.Should().Throw<Exception>().WithMessage("asdf");

### Configuration

<PackageReference Include="FluentAssertions" Version="6.11.0" />
.net v6

**Comment by jnyrup** [comment]
You need to await `ThrowAsync`

**Comment by dennisdoomen** [comment]
You also might want to use [a Roslyn analyzer](https://www.continuousimprover.com/2022/01/awaiting-the-awaitable.html) to help detect those cases.
