### ISSUE TITLE
Assertion failure text includes excessive source code

### ISSUE THREAD

**Issue by InteXX** [fluentassertions/fluentassertions#2248]
### Description

I'm running a rather long and verbose test; bear with me please. I've placed its code—and the response—below for easier reading.

The problem is that when an assertion fails, the remainder of the code starting at the point of the assertion is dumped into the failure output. Given the complexity of the test, this results in a very difficult-to-interpret response.

Is this by design, a bug or merely a misconfiguration on my part?

### Reproduction Steps

```vb
  1.  <Fact>
  2.  Public Async Function Adding_Donor_Should_Also_Create_Recipient() As Task
  3.    Dim oMaryJonesGetByEmailResult As Result(Of MemberResponse)
  4.    Dim oJimSmithGetByEmailResult As Result(Of MemberResponse)
  5.    Dim oJohnDoeGetByEmailResult As Result(Of MemberResponse)
  6.    Dim oMaryJonesAddDonorResult As Result
  7.    Dim oJohnDoeAddDonorResult As Result
  8.    Dim oMaryJonesCreateResult As Result
  9.    Dim oJimSmithCreateResult As Result
 10.    Dim oJohnDoeCreateResult As Result
 11.    Dim oBloodTypeQueryResult As Result(Of BloodTypeResponse)
 12.    Dim oZipCodeQueryResult As Result(Of ZipCodeResponse)
 13.    Dim oCityQueryResult As Result(Of CityResponse)
 14.    Dim oBloodTypeQuery As GetBloodTypeByTypeQuery
 15.    Dim oZipCodeQuery As GetZipCodeByCodeQuery
 16.    Dim oCityQuery As GetCityByNameQuery
 17.    Dim oMaryJonesGetByEmail As GetMemberByEmailQuery
 18.    Dim oJimSmithGetByEmail As GetMemberByEmailQuery
 19.    Dim oJohnDoeGetByEmail As GetMemberByEmailQuery
 20.    Dim oMaryJonesAddDonor As UpdateMemberAddDonorCommand
 21.    Dim oJohnDoeAddDonor As UpdateMemberAddDonorCommand
 22.    Dim oMaryJonesCreate As CreateMemberCommand
 23.    Dim oJimSmithCreate As CreateMemberCommand
 24.    Dim oJohnDoeCreate As CreateMemberCommand
 25.    Dim sMaryJonesEmail As String
 26.    Dim sJimSmithEmail As String
 27.    Dim sJohnDoeEmail As String
 28.    Dim oMediator As IMediator
 29.    Dim oLocation As Location
 30.
 31.    oMediator = Me.DbFixture.Scope.Resolve(Of IMediator)
 32.    oLocation = New Location(0, 0)
 33.
 34.    '
 35.    ' Init email addresses
 36.    '
 37.    sMaryJonesEmail = $"{NameOf(oMaryJonesCreate).Replace("Create", "").Substring(1).ToLower}@domain.com"
 38.    sJimSmithEmail = $"{NameOf(oJimSmithCreate).Replace("Create", "").Substring(1).ToLower}@domain.com"
 39.    sJohnDoeEmail = $"{NameOf(oJohnDoeCreate).Replace("Create", "").Substring(1).ToLower}@domain.com"
 40.
 41.    '
 42.    ' Get supporting entity data
 43.    '
 44.    oZipCodeQuery = GetZipCodeByCodeQuery.Create("10014")
 45.    oZipCodeQueryResult = Await oMediator.Send(oZipCodeQuery)
 46.    oBloodTypeQuery = GetBloodTypeByTypeQuery.Create(BloodTypes.APositive)
 47.    oBloodTypeQueryResult = Await oMediator.Send(oBloodTypeQuery)
 48.    oCityQuery = GetCityByNameQuery.Create(oZipCodeQueryResult.Value.Cities.First.Name)
 49.    oCityQueryResult = Await oMediator.Send(oCityQuery)
 50.
 51.    '
 52.    ' Create members
 53.    '
 54.    oMaryJonesCreate = CreateMemberCommand.Create("Mary", "Jones", sMaryJonesEmail, oLocation, oBloodTypeQueryResult.Value, oZipCodeQueryResult.Value, oCityQueryResult.Value)
 55.    oJimSmithCreate = CreateMemberCommand.Create("Jim", "Smith", sJimSmithEmail, oLocation, oBloodTypeQueryResult.Value, oZipCodeQueryResult.Value, oCityQueryResult.Value)
 56.    oJohnDoeCreate = CreateMemberCommand.Create("John", "Doe", sJohnDoeEmail, oLocation, oBloodTypeQueryResult.Value, oZipCodeQueryResult.Value, oCityQueryResult.Value)
 57.
 58.    oMaryJonesCreateResult = Await oMediator.Send(oMaryJonesCreate)
 59.    oJimSmithCreateResult = Await oMediator.Send(oJimSmithCreate)
 60.    oJohnDoeCreateResult = Await oMediator.Send(oJohnDoeCreate)
 61.
 62.    '
 63.    ' Assert members created
 64.    '
 65.    oMaryJonesCreateResult.IsSuccess.Should.BeTrue()
 66.    oJimSmithCreateResult.IsSuccess.Should.BeTrue()
 67.    oJohnDoeCreateResult.IsSuccess.Should.BeTrue()
 68.
 69.    '
 70.    ' Get members
 71.    '
 72.    oMaryJonesGetByEmail = GetMemberByEmailQuery.Create(sMaryJonesEmail)
 73.    oJimSmithGetByEmail = GetMemberByEmailQuery.Create(sJimSmithEmail)
 74.    oJohnDoeGetByEmail = GetMemberByEmailQuery.Create(sJohnDoeEmail)
 75.
 76.    oMaryJonesGetByEmailResult = Await oMediator.Send(oMaryJonesGetByEmail)
 77.    oJimSmithGetByEmailResult = Await oMediator.Send(oJimSmithGetByEmail)
 78.    oJohnDoeGetByEmailResult = Await oMediator.Send(oJohnDoeGetByEmail)
 79.
 80.    '
 81.    ' Assert members retrieved
 82.    '
 83.    oMaryJonesGetByEmailResult.IsSuccess.Should.BeTrue()
 84.    oJimSmithGetByEmailResult.IsSuccess.Should.BeTrue()
 85.    oJohnDoeGetByEmailResult.IsSuccess.Should.BeTrue()
 86.
 87.    '
 88.    ' Add donors
 89.    '
 90.    oMaryJonesAddDonor = UpdateMemberAddDonorCommand.Create(oMaryJonesGetByEmailResult.Value, oJimSmithGetByEmailResult.Value)
 91.    oJohnDoeAddDonor = UpdateMemberAddDonorCommand.Create(oJohnDoeGetByEmailResult.Value, oMaryJonesGetByEmailResult.Value)
 92.
 93.    oMaryJonesAddDonorResult = Await oMediator.Send(oMaryJonesAddDonor)
 94.    oJohnDoeAddDonorResult = Await oMediator.Send(oJohnDoeAddDonor)
 95.
 96.    '
 97.    ' Assert donors added
 98.    '
 99.    oMaryJonesAddDonorResult.IsSuccess.Should.BeTrue()
100.    oJohnDoeAddDonorResult.IsSuccess.Should.BeTrue()
101.
102.    '
103.    ' Refresh donors
104.    '
105.    oMaryJonesGetByEmailResult = Await oMediator.Send(oMaryJonesGetByEmail)
106.    oJimSmithGetByEmailResult = Await oMediator.Send(oJimSmithGetByEmail)
107.    oJohnDoeGetByEmailResult = Await oMediator.Send(oJohnDoeGetByEmail)
108.
109.    '
110.    ' Assert links
111.    '
112.    oJimSmithGetByEmailResult.Value.Recipients.Any(Function(Recipient) Recipient.Email = oMaryJonesGetByEmailResult.Value.Email).Should.BeTrue()
113.    oMaryJonesGetByEmailResult.Value.Recipients.Any(Function(Recipient) Recipient.Email = oJohnDoeGetByEmailResult.Value.Email).Should.BeTrue()
114.  End Function
```

### Expected behavior

> Tests.MemberTests.Adding_Donor_Should_Also_Create_Recipient
>   Source: MemberTests.vb line 57
>   Duration: 7.9 min
>
>  Message: 
>Expected oMaryJonesCreateResult.IsSuccess.Should.BeTrue() but found False.
>
>  Stack Trace: 
>XUnit2TestFramework.Throw(String message)
>TestFrameworkProvider.Throw(String message)
>DefaultAssertionStrategy.HandleFailure(String message)
>AssertionScope.FailWith(Func`1 failReasonFunc)
>AssertionScope.FailWith(Func`1 failReasonFunc)
>AssertionScope.FailWith(String message, Object[] args)
>BooleanAssertions`1.BeTrue(String because, Object[] becauseArgs)
>MemberTests.Adding_Donor_Should_Also_Create_Recipient() line 141
>--- End of stack trace from previous location ---

### Actual behavior

The entirety of the source code starting at the point of assertion failure (in this case line 65 above) is included in the output.

>  Tests.MemberTests.Adding_Donor_Should_Also_Create_Recipient
>    Source: MemberTests.vb line 57
>    Duration: 7.9 min
>
>    Message: 
>  Expected oMaryJonesCreateResult.IsSuccess.Should.BeTrue()oJimSmithCreateResult.IsSuccess.Should.BeTrue()oJohnDoeCreateResult.IsSuccess.Should.BeTrue()'' Get members'oMaryJonesGetByEmail = GetMemberByEmailQuery.Create(sMaryJonesEmail)oJimSmithGetByEmail = GetMemberByEmailQuery.Create(sJimSmithEmail)oJohnDoeGetByEmail = GetMemberByEmailQuery.Create(sJohnDoeEmail)oMaryJonesGetByEmailResult = Await oMediator.Send(oMaryJonesGetByEmail)oJimSmithGetByEmailResult = Await oMediator.Send(oJimSmithGetByEmail)oJohnDoeGetByEmailResult = Await oMediator.Send(oJohnDoeGetByEmail)oMaryJonesGetByEmailResult.IsSuccess.Should.BeTrue()oJimSmithGetByEmailResult.IsSuccess.Should.BeTrue()oJohnDoeGetByEmailResult.IsSuccess.Should.BeTrue()'' Add donors'oMaryJonesAddDonor = UpdateMemberAddDonorCommand.Create(oMaryJonesGetByEmailResult.Value, oJimSmithGetByEmailResult.Value)oJohnDoeAddDonor = UpdateMemberAddDonorCommand.Create(oJohnDoeGetByEmailResult.Value, oMaryJonesGetByEmailResult.Value)oMaryJonesAddDonorResult = Await oMediator.Send(oMaryJonesAddDonor)oJohnDoeAddDonorResult = Await oMediator.Send(oJohnDoeAddDonor)oMaryJonesAddDonorResult.IsSuccess.Should.BeTrue()oJohnDoeAddDonorResult.IsSuccess.Should.BeTrue()'' Refresh donors'oMaryJonesGetByEmailResult = Await oMediator.Send(oMaryJonesGetByEmail)oJimSmithGetByEmailResult = Await oMediator.Send(oJimSmithGetByEmail)oJohnDoeGetByEmailResult = Await oMediator.Send(oJohnDoeGetByEmail)'' Assert links'oJimSmithGetByEmailResult.Value.Recipients.Any(Function(Recipient) Recipient.Email = oMaryJonesGetByEmailResult.Value.Email).Should.BeTrue()oMaryJonesGetByEmailResult.Value.Recipients.Any(Function(Recipient) Recipient.Email = oJohnDoeGetByEmailResult.Value.Email).Should.BeTrue()End Function<Fact>Public Async Function Can_Get_Member_By_Code() As TaskDim oGetMemberByCodeResult As Result(Of MemberResponse)Dim oBloodTypeQueryResult As Result(Of BloodTypeResponse)Dim oZipCodeQueryResult As Result(Of ZipCodeResponse)Dim oCreateMemberResult As ResultDim oCityQueryResult As Result(Of CityResponse)Dim oGetMemberByCode As GetMemberByCodeQueryDim oBloodTypeQuery As GetBloodTypeByTypeQueryDim oZipCodeQuery As GetZipCodeByCodeQueryDim oCreateMember As CreateMemberCommandDim oCityQuery As GetCityByNameQueryDim oMediator As IMediatorDim oLocation As Location' ArrangeoMediator = Me.DbFixture.Scope.Resolve(Of IMediator)oLocation = New Location(0, 0)oZipCodeQuery = GetZipCodeByCodeQuery.Create("10014")oZipCodeQueryResult = Await oMediator.Send(oZipCodeQuery)oBloodTypeQuery = GetBloodTypeByTypeQuery.Create(Domain.Enums.BloodTypes.APositive)oBloodTypeQueryResult = Await oMediator.Send(oBloodTypeQuery)oCityQuery = GetCityByNameQuery.Create(oZipCodeQueryResult.Value.Cities.First.Name)oCityQueryResult = Await oMediator.Send(oCityQuery)' ActoCreateMember = CreateMemberCommand.Create("John", "Doe", "alias@domain.com", oLocation, oBloodTypeQueryResult.Value, oZipCodeQueryResult.Value, oCityQueryResult.Value)oCreateMemberResult = Await oMediator.Send(oCreateMember)oGetMemberByCode = GetMemberByCodeQuery.Create(oCreateMember.Code)oGetMemberByCodeResult = Await oMediator.Send(oGetMemberByCode)' AssertoGetMemberByCode.Should.NotBeNull()oCreateMemberResult.IsSuccess.Should.BeTrue()oGetMemberByCodeResult.IsSuccess.Should.BeTrue()oGetMemberByCodeResult.Value.Code.Should.Be(oCreateMember.Code)End FunctionEnd Class to be true, but found False.
>
>    Stack Trace: 
>  XUnit2TestFramework.Throw(String message)
>  TestFrameworkProvider.Throw(String message)
>  DefaultAssertionStrategy.HandleFailure(String message)
>  AssertionScope.FailWith(Func`1 failReasonFunc)
>  AssertionScope.FailWith(Func`1 failReasonFunc)
>  AssertionScope.FailWith(String message, Object[] args)
>  BooleanAssertions`1.BeTrue(String because, Object[] becauseArgs)
>  MemberTests.Adding_Donor_Should_Also_Create_Recipient() line 141
>  --- End of stack trace from previous location ---

### Regression?

This has been occurring for some time (years), but it's finally pushed me to the edge. Thus I'm raising this issue.

### Configuration

.NET 7
v6.11.0
VS 2022

### Other information

I tried doing something akin to this:
```vb
Using oScope As New AssertionScope
  oScope.FormattingOptions.MaxLines = 3

  oJimSmithGetByEmailResult.Value.Recipients.Any(Function(Recipient) Recipient.Email = oMaryJonesGetByEmailResult.Value.Email).Should.BeTrue()
  oMaryJonesGetByEmailResult.Value.Recipients.Any(Function(Recipient) Recipient.Email = oJohnDoeGetByEmailResult.Value.Email).Should.BeTrue()
End Using
```
But it had no effect.

**Comment by jnyrup** [comment]
I suspect `CallerIdentifier` is at it again - it hasn't been tested on VB code.

As a quick workaround try using the `AssertionScope(string context)`.
That should short-circuit FA from using `CallerIdentifier`.

I'd like to see if there is a clean+simple improvement we can make to `CallerIdentifier`, but given it's nature it might fall into the known-defect bucket.
As I haven't written any VB code myself (and don't plan to starting) I'd need some more help from your side.
Can you provide a minimal and self-contained VB test that I can copy/paste and debug?

**Comment by InteXX** [comment]
> Can you provide a minimal and self-contained VB test

Certainly, here you go:

```
  <Fact>
  Public Sub VbTest()
    Dim oFruits As List(Of String)
    Dim sOrange As String
    Dim sApple As String

    sOrange = "Orange"
    sApple = "Apple"

    oFruits = New List(Of String) From {sOrange, sApple}

    Using oScope As New AssertionScope("Test")
      oFruits.Count.Should.Be(2)
      oFruits.First.Should.Be(sOrange)
      oFruits.Last.Should.Be(sApple)
      oFruits.Should.Contain("Mango")
    End Using

    '
    ' All manner of source code goes here
    '
    ' Lorem ipsum dolor sit amet, consectetur adipiscing
    ' elit, sed do eiusmod tempor incididunt ut labore
    ' et dolore magna aliqua. Ut enim ad minim veniam,
    ' quis nostrud exercitation ullamco laboris nisi ut
    ' aliquip ex ea commodo consequat. Duis aute irure
    ' dolor in reprehenderit in voluptate velit esse
    ' cillum dolore eu fugiat nulla pariatur. Excepteur
    ' sint occaecat cupidatat non proident, sunt in
    ' culpa qui officia deserunt mollit anim id est
    ' laborum.
    '
  End Sub
```
That works. Use `""` instead of `"Test"` and we've got a repro.

I'd hoped to avoid the boilerplate by doing something like this in my setup/teardown fixture:
```
Public Class Fixture
  Implements IDisposable

  Public Sub New()
    Me.AssertionScope = New AssertionScope("Test")
  End Sub

  Public Sub Dispose() Implements IDisposable.Dispose
    Me.AssertionScope.Dispose()
  End Sub

  Public AssertionScope As AssertionScope
End Class
```
But alas it was not to be. Apparently the call must be local.

**Comment by jnyrup** [comment]
Thanks for the example, I can confirm it reproduces the bug.

Our textual code parser `CallerStatementBuilder` assumes that:
* a statement ends with a `;`
* a call to `Should` looks like `.Should(`

Both are at most valid for C#, but not for F# or VB.

**Comment by InteXX** [comment]
Thanks for the quick reply.

Is it a bug worth fixing?

**Comment by jnyrup** [comment]
The parser will never be bug-free with it's current approach.

My first thought was to simply break out of `CallerIdentifier` if the file ends with `.vb` or `.fs`.

**Comment by InteXX** [comment]
That works for me... (at least)

What does `CallerIdentifier` do?

**Comment by dennisdoomen** [comment]
> My first thought was to simply break out of `CallerIdentifier` if the file ends with `.vb` or `.fs`.

Yes, I agree. We have no plans to support VB.NET.

> What does `CallerIdentifier` do?

It parses the C# code that invokes Fluent Assertions so it can display the variable name on which `Should` is called. See https://fluentassertions.com/introduction#subject-identification

**Comment by InteXX** [comment]
@dennisdoomen 

Ah, gotcha.

Well... here's what I've done as a workaround, based on @jnyrup's suggestion:
```
  <Fact>
  Public Sub SomeTest()
    ' Arrange

    ' Act

    ' Assert
    Using oScope As New AssertionScope("Test")
    End Using
  End Sub
```
I dropped that as a double-click-to-paste template into my VS Toolbox pane and it works just fine. I can live with that if you've got better things to do than worry with this whole thing (and I suspect you do).

**Comment by InteXX** [comment]
I've realized that I mistakenly included sensitive information in posting this issue, information that I'd like to not be revealed.

Are you able to delete it entirely?

**Comment by jnyrup** [comment]
@InteXX I've edited all your posts and removed the history of all code and stack traces.
Is that sufficient?
If possible I'd like to keep the rest of this thread, since this was a prime example of how communication on OSS projects should be.

**Comment by InteXX** [comment]
That's perfect, thank you very much 🙂

**Comment by jnyrup** [comment]
FYI, I've merged a PR that improves the caller identification for VB. 
I also noticed that if you `Should()` instead of the shorthand `Should`, the current version of FA Should work as expected.

**Comment by InteXX** [comment]
It looks official!

**Comment by InteXX** [comment]
Thank you very much 🙂
