### ISSUE TITLE
x.Should().ContainEquivalentOf(x) returns false

### ISSUE THREAD

**Issue by ERGeorgiev** [fluentassertions/fluentassertions#2260]
### Description

Testing if an enumerable contains the equivalent of itself does not pass.

### Reproduction Steps

```csharp
var test = new List<string>() { "test" };
test.Should().ContainEquivalentOf(test);
```

### Expected behavior

It should pass.

### Actual behavior

It does not pass.

**Comment by ERGeorgiev** [comment]
Ah I see. From the wording of that method, I understood that it would check if an array contains the elements of another array. Thank you for the clarification.

**Comment by jnyrup** [comment]
If you have suggestions on how to improve documentation, we welcome PRs 😉
