### ISSUE TITLE
NotThrowAfter doesn't work with AssertionScope

### ISSUE THREAD

**Issue by xzxzxc** [fluentassertions/fluentassertions#2265]
### Description

An `AssertionScope` throws an exception if there is at least one assertion failure in an `action` passed to the `NotThrowAfter` or `NotThrowAfterAsync` method, even if the `action` stoped throwing in time.

### Reproduction Steps

```csharp
using var scope = new AssertionScope();
var start = DateTime.Now;

var action = () =>
{
  if (DateTime.Now - start < TimeSpan.FromSeconds(1))
    1.Should().Be(0);
};

action.Should().NotThrowAfter(5.Seconds(), 500.Milliseconds());
```

### Expected behavior

No exceptions.

### Actual behavior

The next exception is thrown.

```
Xunit.Sdk.XunitException
Expected value to be 0, but found 1 (difference of 1).

   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
   at FluentAssertions.Execution.AssertionScope.Dispose()
   at Clean.UnitTest1.Test() in /User/UnitTest1.cs:line 22
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

### Configuration

NET 7, FluentAssertions 6.11.0

**Comment by dennisdoomen** [comment]
I think you're misunderstanding the purpose of the `AssertionScope`. It only exists so you can execute multiple calls to `Should` so that all failures are thrown as one exception as soon as the scope goes out of "scope".

**Comment by xzxzxc** [comment]
@dennisdoomen, in my real test, I have multiple `Should` calls, one of which uses `NotThrowAfter`. The problem is that `AssertionScope` "breaks" the `NotThrowAfter` check (the test fails when it should not). I tried to create the simplest example of the bug, so it includes only one `Should` call.

**Comment by dennisdoomen** [comment]
I get your problem. But because the `AssertionScope` will collect the results of any assertion that happened within the `using` block, at the end of the test, when the scope gets _disposed_, it will report them back. And `1.Should().Be(0)` _did_ raise an assertion exception.

So although I agree, the behavior might not be 100% obvious, it _is_ according to the design. There's nothing we can fix here.

**Comment by xzxzxc** [comment]
That's sad, but thank you for the clarification! I'll stop using the `AssertionScope` then.

**Comment by dennisdoomen** [comment]
I wonder why you are using the `AssertionScope` in the first place.

**Comment by xzxzxc** [comment]
I have a test where I'm sending a message to the application through Rabbit and waiting for changes in the DB. And I'm checking multiple tables, with a separate assertion (`.Should()`) for each. The first check uses `NotThrowAfter` to wait for the message to be processed.  
It would be nice to aggregate all assertions, but it's not crucial.

**Comment by dennisdoomen** [comment]
In that case, I would not use FA _inside_ the condition you're passing into `NotThrowAfter` and instead, throw a normal exception. This API was intended to call some production code that would throw. Then you can still use an `AssertionScope`.
