### ISSUE TITLE
[Feature]: Extract the object graph comparison engine to a separate package

### ISSUE THREAD

**Issue by ycherkes** [fluentassertions/fluentassertions#2268]
### Background and motivation

1. Sometimes with Moq or NSubstitute I need the following call verification logic:

`someServiceMock.Verify(s => s.DoSomething(It.Is<object>(o => ObjectComparer.Equals(o, expected))));`

I understand and prefer the way with callbacks, as it gives more detailed error messages: 

```
//Arrange
object actual = null;
someServiceMock.Setup(s => s.DoSomething(It.IsAny<object>()))
               .Callback<object>(o => actual = o);

// Act ...

// Assert
expected.Should().BeEquivalentTo(actual);
```
But sometimes it looks overcomplicated. 
So It would be perfect to have the comparison logic available without assertion.

2. Sometimes the fluent assertion approach or library is not approved by the dev team, but the developer who is familiar with fluent assertions would be able to use the comparison feature without referencing the fluent assertion package with a lot of unnecessary extension methods.

PS. I know about the [Compare-Net-Objects](https://github.com/GregFinzer/Compare-Net-Objects) and [ObjectComparer](https://github.com/ValeraT1982/ObjectsComparer) libraries.

### Could you help with a pull-request?

No

**Comment by dennisdoomen** [comment]
If you're devs are not allowed to use Fluent Assertions (which is weird by itself), then I don't understand what you are asking.

**Comment by ycherkes** [comment]
I know it's weird but it's a fact when the team decides to use the only built-in to test framework assertions. And the team doesn't want to mix the approaches.

**Comment by ycherkes** [comment]
> If you're devs are not allowed to use Fluent Assertions (which is weird by itself), then I don't understand what you are asking.

I can be wrong, the fluent assertions library has the following tightly coupled functionality:
1. A set of fluent extensions methods
2. Object comparison engine
3. Test-engine integration code which throws compatible with specific test engine exceptions.

I would like to have the second one as a separate reusable unit.

**Comment by dennisdoomen** [comment]
> I know it's weird but it's a fact when the team decides to use only built-in to test framework assertions. And the team doesn't want to mix the approaches.

If you work in a team with such dogmatic believes, you should consider finding a new job. You're literally stealing from your employer if one refuses to use great tools. And I'm not talking about Fluent Assertions only. 

> I would like to have the second one as a separate reusable unit.

2 and 3 are just there to make 1 better. So this is not something I see any value in. I recommend you check out other examples or fork our code base.

**Comment by jnyrup** [comment]
> Test-engine integration code which throws compatible with specific test engine exceptions.

Just to be clear, upon test failure we detect which testing framework you're using and throw the appropriate exception.
This is done _without_ having a dependency on the testing framework.
You can see the dependencies on [nuget.org](https://www.nuget.org/packages/FluentAssertions/6.11.0#dependencies-body-tab)
