### ISSUE TITLE
[Feature]: Print the execution time for `ExecutionTime`, and co.

### ISSUE THREAD

**Issue by maxnatamo** [fluentassertions/fluentassertions#2282]
### Background and motivation

`ExecutionTime`, `CompleteWithinAsync`, etc. only print the expected execution time, like so:

```
Error Message:
[DBG]    Expected act to complete within 100ms.
```

Would it not be more informative to also include how long the actual execution took, instead of only printing the expected time? Like so:

```
Error Message:
[DBG]    Expected act to complete within 100ms. Took 145ms
```

### Could you help with a pull-request?

Yes

**Comment by jnyrup** [comment]
The problem here is how to handle functions that never terminate or are just very slow to complete.
E.g. if we want to test that `act` completes within 1s, how long should we want until we bail out once we pass 1s of execution time?

Have a look at the implementation of [`CompleteWithinAsync`](https://github.com/fluentassertions/fluentassertions/blob/22ac70fd7501f7426aae2ad768fb38dec4e41faa/Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs#L44) and [`ExecutionTime`](https://github.com/fluentassertions/fluentassertions/blob/develop/Src/FluentAssertions/Specialized/ExecutionTime.cs)

**Comment by maxnatamo** [comment]
Could it not be defaulted to some value, like 10 seconds, but also be changed by the end-user by options, similar to [BeEquivalentTo](https://fluentassertions.com/data/#typed-dataset-datatable-datarow-objects)? For example:

```cs
// Defaults to 10s or some other arbitrary value, or maybe not expire at all
await act.Should().CompleteWithinAsync(300.Milliseconds());

// Custom timeout value
await act.Should().CompleteWithinAsync(300.Milliseconds(), options => options.Timeout = 10.Seconds());
```

I wouldn't know whether this is the best - or even a good - approach to this. But, it seems strange to have such a simple exception, when everything else in FluentAssertions is so descriptive.

**Comment by ITaluone** [comment]
> // Defaults to 10s or some other arbitrary value, or maybe not expire at all
> await act.Should().CompleteWithinAsync(300.Milliseconds());

IMO there is no real difference in waiting 301 milliseconds vs 10 seconds if a task does not finish.

The only difference is that test duration increases a lot.
Let's construct a exaggerated example: Say you have 10,000 tests and they all take the user defined timeout of 10s.. then the whole tests will take 100,000s which is about 28 hours vs. about 50 minutes (with the example above).

**Comment by maxnatamo** [comment]
You're right, it would make some strange results, if the task didn't finish. But, at the same time, if an infinite task was executed outside of FluentAssertion's statements, it would have the same effect. Whether it's handled by an end-user or FA isn't important, when the result would be the same.

**Comment by ITaluone** [comment]
True as well :)
This behavior would occur also if it takes longer than the user defined timeout, which can alos lead into unwanted results.

Another issue: why 10 seconds? This sounds like a magic number to me. (And every other value also will)

**Comment by maxnatamo** [comment]
It is a magic number; I chose it completely arbitrarily.

**Comment by dennisdoomen** [comment]
> The problem here is how to handle functions that never terminate or are just very slow to complete.
> E.g. if we want to test that `act` completes within 1s, how long should we want until we bail out once we pass 1s of execution time?

The point @jnyrup made remains. I'd also add that you should design your code so that you can fake time instead of having very slow tests like you're suggesting. Also, xUnit will kill your tests after a certain timeout anyway. 

So I vote _no_ to this proposal.

**Comment by jnyrup** [comment]
I also vote no to change the existing methods.

But I'm curious to know a bit more about your case, maybe we can learn a new perspective.

**Comment by jnyrup** [comment]
I'll close it then. 
Thanks for sharing your thoughts. 
We appreciate the feedback.

**Comment by dennisdoomen** [comment]
> I'll close it then.
> Thanks for sharing your thoughts.
> We appreciate the feedback.

I second that.
