### ISSUE TITLE
[Feature]: Option to throw on additional members in source object with FluentAssertions which are not compared, i.e. assert all properties are in both objects?

### ISSUE THREAD

**Issue by rklec** [fluentassertions/fluentassertions#2289]
### Background and motivation

**Background of the library:** Basically I want to compare an object with FluentAssertions `BeEquivalentTo`. Now, FluentAssertions [Object graph comparison](https://fluentassertions.com/objectgraphs/) works in a way that is usually good for unit testing: If your source object has _additional_ properties, it does not throw.
In other words: If there are less properties in the target object of the comparison, FluentAssertions will not complain and throw, after all the assertion itself works and all properties you want are in there. The [library author has also explained this in this video](https://www.youtube.com/live/WybRJ_LKGb4?feature=shared&t=810).

**Background of what I want:** Now I don't want this, because this integration test, should also catch superfluous properties. Or better: It should catch properties, where I have not yet "written an assertion", i.e. written a target property that I want it to have been compared too. I know this is not test-driven development (TDD)style, but come on, the thing is I have a large object with many sub-properties/objects to compare and I just want to make sure, I have catched and compared/tested all. After all, the test already stands, this is just my last step to "be sure".

### Alternative Concerns

**Question:** So what I actually want for FluentAssertions is that if my target object has a missing property in the source object, it should error/throw.

Here is a **MWE**:
```csharp
public class CompareClassTest
{
    public class ClassA
    {
        public int Property1 { get; set; }

        public string Property2 { get; set; }
    }

    public class ClassB
    {
        public int Property1 { get; set; }

        public string Property2 { get; set; }

        public bool Property3 { get; set; }
    }

    [Test]
    public void TestEquivalence()
    {
        var objA = new ClassB
        {
            Property1 = 1,
            Property2 = "Test",
            Property3 = true
        };

        var objB = new ClassA { Property1 = 1, Property2 = "Test" };

        objA.Should().BeEquivalentTo(objB

        //,
        //x => x.ThrowingOnMissingMembers() // -> failed

        //,
        //options => options
        //    .IncludingAllDeclaredProperties()
        //    .IncludingNestedObjects()
        //    .IncludingAllRuntimeProperties() // -> failed
        );
    }
}
```

As you can see above, I have tried some options already. None work.

I also tried asking the AI. As I used JetBrains AI Assistant I have to copy that over and [here is the full AI conversation](https://gist.github.com/rklec/277133fe8b3f5bdcce6340953c8000a9).
It first recommend me wrong methods like `ComparingByMembers`. It got a good MWE and I later understood that it was the wrong order around (above is the one which really shows my use case).

Now in the end it got repetitive and said a thing like this would be the only solution:

```csharp
var responseGetProperties = typeof(ResponseGet).GetProperties().Select(p => p.Name);
var viewModelProperties = typeof(viewModel).GetProperties().Select(p => p.Name);

responseGetProperties.Should().BeEquivalentTo(viewModelProperties);
```

But really? As FluentAssertions is already iterating properties I would find it unnecessary to do and implement that again? I would love a simple `option` for that that the AI or me may have missed?

**Edit:** Actually for runtime type comparison it should be this:
```csharp
var responseGetProperties = responseGet.GetType().GetProperties().Select(p => p.Name);
var viewModelProperties = viewModel.GetType().GetProperties().Select(p => p.Name);
responseGetProperties.Should().BeEquivalentTo(viewModelProperties);     
```

However, that also only does a shallow-comparsion and does not go into deep/nested properties.

### Could you help with a pull-request?

No

---

This came from [a Stackoverflow question](https://stackoverflow.com/questions/77025806/throw-on-additional-members-in-source-object-with-fluentassertions-which-are-not) and as I find it a missing feature, I wanted to suggest it here.

**Comment by dennisdoomen** [comment]
Maybe a stupid thought, but what if you would swap the subject and expectation?

**Comment by rklec** [comment]
Oh yeah of course, that seems to work: https://dotnetfiddle.net/ynvbTp ([cross-posted on Stackoverflow](https://stackoverflow.com/a/77178197/15488899), if that is okay).
