### ISSUE TITLE
Allow extension libraries to alter options before the first assertion

### ISSUE THREAD

**Issue by dennisdoomen** [fluentassertions/fluentassertions#2290]
Extension libraries have typically two needs that are currently not provided:

1. Being able to mark themselves as an extension library so that `CallerIdentifier` doesn't need to check for individual `CustomAssertion` attributes
2. Being able to inject additional capabilities, like custom implementations of `IEquivalencyStep` such as provided by `FluentAssertions.DataSets`.

I'm proposing to introduce an assembly-level attribute that FA will scan for before it executes any kind of assertion. This attribute will point to an initialization class/method that can be used to change FA defaults, e.g. using `AssertionOptions`. 

I'm not 100% sure yet, but I suspect this scanning could be triggered by the static constructor of `AssertionExtensions`

Is a prerequisite for finishing #2002

**Comment by jnyrup** [comment]
To change defaults from an extension library we could maybe use [module initializers](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/module-initializers)?

**Comment by dennisdoomen** [comment]
Yes, I was trying that. But those are not invoked until the assembly is loaded. And according to my tests, it isn't loaded until some code in a test directly uses some code from that assembly.
