### ISSUE TITLE
BeEquivalentTo on non-generic dictionary gives confusing error

### ISSUE THREAD

**Issue by kbilsted** [fluentassertions/fluentassertions#2298]
### Description

upgrading from v5 to version 6.12.0 I no longer am able to assert exception data

### Reproduction Steps

```csharp
 [Test]
public void exception()
{
    Func<Task> act = async () =>
    {
        var ex = new Exception("msg");
        ex.Data.Add("id", 22);
        ex.Data.Add("CustomerId", 33);
        throw ex;
    };
    
    act.Should()
        .ThrowAsync<Exception>()
        .WithMessage("msg")
        .Result.Which.Should().BeEquivalentTo(new Dictionary<object,object>()
        {
            {"id",22},
            {"CustomerId",33}
        });
}
```

### Expected behavior

assert

### Actual behavior

```
Expected act to be a dictionary or collection of key-value pairs that is keyed to type System.Object. It implements .

With configuration:
- Use declared types and members
- Compare enums by value
- Compare tuples by their properties
- Compare anonymous types by their properties
- Compare records by their members
- Include non-browsable members
- Match member by name (or throw)
- Be strict about the order of items in byte arrays
- Without automatic conversion.

   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(Comparands comparands, EquivalencyValidationContext context)
   at FluentAssertions.Primitives.ObjectAssertions`2.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs)
   at FluentAssertions.Primitives.ObjectAssertions`2.BeEquivalentTo[TExpectation](TExpectation expectation, String because, Object[] becauseArgs)
   at Alka.PermissionsService.Tests.AgreementRegistrationTests.exception() in C:\source\xxx.Tests\Tests.cs:line 
```

### Regression?

yes

### Known Workarounds
you can build this but its ugly and the assert requires to call this

```cs
public static Dictionary<string, object> Extract(this Exception e)
{
    var result = new Dictionary<string, object>();
    var ee = e.Data.GetEnumerator();
    while (ee.MoveNext())
    {
        result.Add(ee.Key.ToString(), ee.Value);
    }
    return result;
}
``` 

### Are you willing to help with a pull-request?

No

**Comment by dennisdoomen** [comment]
`Result` is of type `Exception` and you can't compare an exception with a dictionary. I can't imagine how that worked before.

**Comment by kbilsted** [comment]
You are correct. The example code is wrong and the error message is not really showing how wrong the example was. here is a non-working correct example

     [Test]
        public void exception()
        {
            Func<Task> act = async () =>
            {
                var ex = new Exception("msg");
                ex.Data.Add("id", 22);
                ex.Data.Add("CustomerId", 33);
                throw ex;
            };

            act.Should()
                .ThrowAsync<Exception>()
                .WithMessage("msg")
                .Result.Which.Data.Should().BeEquivalentTo(new Dictionary<object, object>()
                {
                    {"id",22},
                    {"CustomerId",33}
                });
        }


and the error which still is helpless (ie. only telling me ` It implements .` )

**Comment by kbilsted** [comment]
@IT-VBFK  it is the code path I am facing issues with. I have not tried all the other assert methods that may be relevant for this. I have not perused the source code to find the "optimal" set of assert methods to test for this bug report. Can you help out in this regard?

The return type is not task, since if I use the above `Extract` it works and it doesn't operate on `Task`.

**Comment by dennisdoomen** [comment]
You need to _await_ `ThrowAsync`

**Comment by kbilsted** [comment]
Many thanks for getting back.

when i try


        [Test]
        public async Task exception()
        {
            Func<Task> act = async () =>
            {
                var ex = new Exception("msg");
                ex.Data.Add("id", 22);
                ex.Data.Add("CustomerId", 33);
                throw ex;
            };

            var ex = await act.Should().ThrowAsync<Exception>();
            ex
            .WithMessage("msg")
            .Which.Data.Should().BeEquivalentTo(new Dictionary<object, object>()
            {
                    {"id",22},
                    {"CustomerId",33}
            });
        }


I get

Expected ex.WithMessage("msg").Which.Data to be a dictionary or collection of key-value pairs that is keyed to type System.Object. It implements .

With configuration:
- Use declared types and members
- Compare enums by value
- Compare tuples by their properties
- Compare anonymous types by their properties
- Compare records by their members
- Include non-browsable members
- Match member by name (or throw)
- Be strict about the order of items in byte arrays
- Without automatic conversion.

   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
   at FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(Comparands comparands, EquivalencyValidationContext context)
   at FluentAssertions.Primitives.ObjectAssertions`2.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs)
   at FluentAssertions.Primitives.ObjectAssertions`2.BeEquivalentTo[TExpectation](TExpectation expectation, String because, Object[] becauseArgs)
   at Alka.PermissionsService.Tests.AgreementDefinitionTests.exception() in C:\t0xsource\tfs\minsys\MS.NET\Solutions\Alka.PermissionsService\Alka.PermissionsService.Tests\AgreementDefinitionTests.cs:line 39
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()


perhaps rather than chasing a bug, you can enlighten me as what the 'canonical' way you see one should assert Exception data? Probably it worked in the v5. due to the implicit type conversion and that `Data` is not a Dictionary<object,object>` the type information is only `IDictionary` so it could use different implementations in future versions. It seems unfortunate, that my tests are dependent on the internal implementation of `Data` that may change in the future and break all my tests.

**Comment by jnyrup** [comment]
I haven't looked into the somewhat cryptic error message you get, but this should work for your case
```cs
ex
.WithMessage("msg")
.Which.Data.Should().BeEquivalentTo(new[]
{
    new{ Key = "id", Value = 22 },
    new{ Key = "CustomerId", Value = 33 }
});
```

**Comment by dennisdoomen** [comment]
I did look at this specific issue and managed to reproduce it. The `Data` property is of type `System.Collections.ListDictionaryInternal`, which does not implement any generic `IDictionary<T,T>` interfaces. So even though the error message could be improved, it's the expectation that's expecting something that isn't there.

**Comment by kbilsted** [comment]
Thanks for the feedback. I'm not sure u understand that you recommend that my tests should depend on the particular list implementation. The data field in the exception class uses an interface so they may substitute the implementation in the future. Would it be better to support implicit conversion of selected interfaces such as idictionary so ours tests do not break when internal implementation details change in .net? I think it would be great to make it easier to fluently test exception details, although I understand the change from fluentassertions v5 to v6

**Comment by jnyrup** [comment]
I agree that you shouldn't need to use a particular dictionary like type to assert equivalency.
It seems `GenericDictionaryEquivalencyStep` is a tad too aggressive in failing the entire assertion.
It doesn't give `DictionaryEquivalencyStep` a chance to prove equivalency.

We're currently working on v7, so for v6 you'll need to construct an expectation that implements `IDictionary` but not `IDictionary<,>`
So just like `ListDictionary` using e.g. `HashTable` also works.

**Comment by dennisdoomen** [comment]
Good point @jnyrup. I completely forgot we still support `IDictionary`.

**Comment by kbilsted** [comment]
many thanks

**Comment by jnyrup** [comment]
Another workaround.
You can also cast the generic dictionary to `IDictionary`.

**Comment by kbilsted** [comment]
Can we make this as an overload in v6 so people have less migration work going to v7?

**Comment by dennisdoomen** [comment]
> Can we make this as an overload in v6 so people have less migration work going to v7?

What do you mean? It's a non-critical bug, which we'll fix in v7.

**Comment by kbilsted** [comment]
I mean I just spent time upgrading Frome v5 to v6 so if possible I'd like not to spend additional time going fromnv6 to v7. 

It may be noncritical but we still waste time with all this back and forth between versions.

So I'm just saying it would be great if a solution could be introduced in v6 making v5 to v6 upgrading easier... and it means less work going from v6 to v7. But ultimately it is your call what experience you wish for your users.

Thanks again for all the quick replies.

**Comment by jnyrup** [comment]
> I mean I just spent time upgrading Frome v5 to v6 so if possible I'd like not to spend additional time going fromnv6 to v7.

We spent 17 months writing v7 :upside_down_face: 

We try to follow [semantic versioning](https://semver.org/) such that all minor and patch updates should just be bumping the nuget version.
So upgrading a major version will often include some work on the consumer side and even here we carefully consider if a change is justified to minimize the hassle of upgrading.

We both have a [changelog for v6](https://fluentassertions.com/releases/#600)  (as well as every other release) and made a [migration guide to v6](https://fluentassertions.com/upgradingtov6).
While the migration guide doesn't specifically mentions this case (as we do consider it a regression), the release notes mentions both dropping some support for non-generic collections and reworking equivalency for collection types.

We designed this library for extensibility, so until we release v7 with a proper fix for this bug, you can use the extension code below to use utilize method overload resolution to match `Dictionary<,>` to `IDictionary`.

```cs
var subject = new ListDictionary
{
	{ "id", 22 },
	{ "CustomerId", 33 }
};

var expected = new Dictionary<object, object>
{
	{ "id", 22 },
	{ "CustomerId", 33 }
};

subject.Should().BeEquivalentTo(expected);
```

```cs
using FluentAssertions;
using FluentAssertions.Primitives;
using System.Collections.Generic;
using System.Collections;
using FluentAssertions.Equivalency;

static class IDictionaryExtensions
{
	public static IDictionaryAssertions Should(this IDictionary obj) => new IDictionaryAssertions(obj);
}

class IDictionaryAssertions : ObjectAssertions<IDictionary, IDictionaryAssertions>
{
    public IDictionaryAssertions(IDictionary obj) : base(obj)
    {}
	
    /// <summary>
    /// Asserts that an object is equivalent to another object.
    /// </summary>
    /// <remarks>
    /// Objects are equivalent when both object graphs have equally named properties with the same value,
    /// irrespective of the type of those objects. Two properties are also equal if one type can be converted to another and the result is equal.
    /// The type of a collection property is ignored as long as the collection implements <see cref="IEnumerable{T}"/> and all
    /// items in the collection are structurally equal.
    /// Notice that actual behavior is determined by the global defaults managed by <see cref="AssertionOptions"/>.
    /// </remarks>
    /// <param name="expectation">The expected element.</param>
    /// <param name="because">
    /// A formatted phrase as is supported by <see cref="string.Format(string,object[])" /> explaining why the assertion
    /// is needed. If the phrase does not start with the word <i>because</i>, it is prepended automatically.
    /// </param>
    /// <param name="becauseArgs">
    /// Zero or more objects to format using the placeholders in <paramref name="because"/>.
    /// </param>
    public AndConstraint<IDictionaryAssertions> BeEquivalentTo(IDictionary expectation, string because = "",
        params object[] becauseArgs)
    {
        return BeEquivalentTo(expectation, config => config, because, becauseArgs);
    }
	
	/// <summary>
    /// Asserts that an object is equivalent to another object.
    /// </summary>
    /// <remarks>
    /// Objects are equivalent when both object graphs have equally named properties with the same value,
    /// irrespective of the type of those objects. Two properties are also equal if one type can be converted to another and the result is equal.
    /// The type of a collection property is ignored as long as the collection implements <see cref="IEnumerable{T}"/> and all
    /// items in the collection are structurally equal.
    /// </remarks>
    /// <param name="expectation">The expected element.</param>
    /// <param name="config">
    /// A reference to the <see cref="EquivalencyAssertionOptions{TSubject}"/> configuration object that can be used
    /// to influence the way the object graphs are compared. You can also provide an alternative instance of the
    /// <see cref="EquivalencyAssertionOptions{TSubject}"/> class. The global defaults are determined by the
    /// <see cref="AssertionOptions"/> class.
    /// </param>
    /// <param name="because">
    /// A formatted phrase as is supported by <see cref="string.Format(string,object[])" /> explaining why the assertion
    /// is needed. If the phrase does not start with the word <i>because</i>, it is prepended automatically.
    /// </param>
    /// <param name="becauseArgs">
    /// Zero or more objects to format using the placeholders in <paramref name="because"/>.
    /// </param>
    /// <exception cref="ArgumentNullException"><paramref name="config"/> is <see langword="null"/>.</exception>
    public AndConstraint<IDictionaryAssertions> BeEquivalentTo(IDictionary expectation,
        Func<EquivalencyAssertionOptions<IDictionary>, EquivalencyAssertionOptions<IDictionary>> config, string because = "",
        params object[] becauseArgs)
    {
		return base.BeEquivalentTo(expectation, config => config, because, becauseArgs);
    }
}
```
