### ISSUE TITLE
Drop support for NSpec3

### ISSUE THREAD

**Issue by dennisdoomen** [fluentassertions/fluentassertions#2316]
[NSpec](https://www.nuget.org/packages/nspec) hasn't been updated since December 2017, so I think we can safely remove it from v7

**Comment by jnyrup** [comment]
Let's drop it 🧹 
https://github.com/nspec/NSpec/issues/209

It seems we're the only ones using it 🙃 
![image](https://github.com/fluentassertions/fluentassertions/assets/919634/801176d2-6c9d-44f7-b164-e17175a03195)

[grep.app](https://grep.app/search?q=using%20NSpec&case=true&words=true) has four entries besides FA and they all seem quite dead.
