### ISSUE TITLE
[Docs]: Improve documentation for `ContainEquivalentOf`

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#2352]
### Background and motivation

#1795, #2260, #2283 and #2328 all thought that `subjectList.ContainEquivalentOf(expectedList)` tries to find a subset in `subjectList` that is equivalent to `expectedList`.
What `ContainEquivalentOf` does is trying to find an element within `subjectList` that is equivalent to `expectedList`.

Is there some xml-documentation or website docs/examples that are missing, incorrect or could be improved to avoid these confusions?

### Are you willing help with a pull-request?

No

**Comment by IT-VBFK** [comment]
According to the docs:
<img width="970" alt="image" src="https://github.com/fluentassertions/fluentassertions/assets/49762557/f4c92df2-026c-4bb0-92dd-c2b905da9e53">

Maybe we could add a link to this in the XML-docs or add an additional "warning" that this will not work with an expected collections, but a single item.
