### ISSUE TITLE
Spelling error in doc-comments

### ISSUE THREAD

**Issue by bkoelman** [fluentassertions/fluentassertions#2353]
### Description

Several `Subject` properties are documented as "Gets the object which value is being asserted." I believe this should be: "Gets the object _whose_ value is being asserted."

List of affected files: https://github.com/search?q=repo%3Afluentassertions%2Ffluentassertions%20%22gets%20the%20object%20which%20value%20is%20being%20asserted%22&type=code

### Reproduction Steps

-

### Expected behavior

-

### Actual behavior

-

### Are you willing to help with a pull-request?

No

**Comment by bkoelman** [comment]
https://langeek.co/en/grammar/course/447/which-vs-whose

**Comment by IT-VBFK** [comment]
Does `good first issue` mean that this should be tackled only by new contributors?

Maybe we should add a list of all (some?)  labels and their meaning in the CONTRIBUTING.md or add this as label description.

E.g. 
`good first issue`: This label marks issues which are reserved for new contributors (e.g. growing knowledge about the code-base). If you are familiar with the code-base: Please leave this for new contributors.

**Comment by 0liver** [comment]
@jnyrup I'd like to propose a replacement of `.Which` by `.Whose` in the public API as follows:

1. Introduce `.Whose` next to `.Which`, with the same semantics. Add an XML comment mentioning to prefer the former over the latter.
2. In the next major release, mark `.Which` as `[Deprecated]`. This will break people's builds, so it shouldn't be in a minor release.
3. In the 2nd major release from now, remove `.Which` completely.

What do you think?

**Comment by jnyrup** [comment]
@0liver Please keep issues focused, i.e. by not mixing doc changes and breaking API proposals.
For a discussion on Which vs Whose, use the existing #577.
