### ISSUE TITLE
Tests on macOS + VisualStudio cannot retrieve context variable name

### ISSUE THREAD

**Issue by IT-VBFK** [fluentassertions/fluentassertions#2368]
In my case (Visual Studio, macOS) a few assertions (or tests) fails, because it cannot extract the subject name and therefore it falls back to the default value.

e.g. This test (note: it has nothing to with what the test is about, this works fine)

```csharp
[Fact]
public void Mismatches_in_multiline_text_includes_the_line_number()
{
    var expectedIndex = 100 + (4 * Environment.NewLine.Length);

    var subject = """
    @startuml
    Alice -> Bob : Authentication Request
    Bob --> Alice : Authentication Response

    Alice -> Bob : Another authentication Request
    Alice <-- Bob : Another authentication Response
    @enduml
    """;

    var expected = """
    @startuml
    Alice -> Bob : Authentication Request
    Bob --> Alice : Authentication Response

    Alice -> Bob : Invalid authentication Request
    Alice <-- Bob : Another authentication Response
    @enduml
    """;

    // Act
    Action act = () => subject.Should().Be(expected);

    // Assert
    act.Should().Throw<XunitException>().WithMessage($"""
        Expected subject to be the same string, but they differ on line 5 and column 16 (index {expectedIndex}):
                     ↓ (actual)
          "…-> Bob : Another…"
          "…-> Bob : Invalid…"
                     ↑ (expected).
        """);
}
```

throws this failure on my mac (note the difference: string instead of subject):

```
Expected exception message to match the equivalent of "Expected subject to be the same string, but they differ on line 5 and column 16 (index 104):
             ↓ (actual)
  "…-> Bob : Another…"
  "…-> Bob : Invalid…"
             ↑ (expected).", but "Expected string to be the same string, but they differ on line 5 and column 16 (index 104):
             ↓ (actual)
  "…-> Bob : Another…"
  "…-> Bob : Invalid…"
             ↑ (expected)." does not.
```

_Originally posted by @IT-VBFK in https://github.com/fluentassertions/fluentassertions/issues/1854#issuecomment-1750946961_

**Comment by IT-VBFK** [comment]
It would be nice if someone with macOS + VisualStudio could verify this.

**Comment by dennisdoomen** [comment]
The only way we can address this if somebody with MacOS can reproduce this and provide a PR for this.

**Comment by dennisdoomen** [comment]
> I hardly believe that this fix will have much impact, does it?

Why, JetBrains Rider works on Mac. And Rider is superior to VS anyhow.

**Comment by IT-VBFK** [comment]
True :)

You never go back to VS if you tested Rider ;)

**Comment by jnyrup** [comment]
> Hmm.. since this note: https://learn.microsoft.com/en-us/visualstudio/mac/what-happened-to-vs-for-mac?view=vsmac-2022
> 
> I hardly believe that this fix will have much impact, does it?

In any case I'm curious to know why the IDE would make a difference here :suspect: 
I don't have a MacOS + VS setup at hand, so I won't be able to dig into this.

**Comment by dennisdoomen** [comment]
Yes, as I said. Unless somebody is going to dig into this, we have no choice then to close it.

**Comment by IT-VBFK** [comment]
> In any case I'm curious to know why the IDE would make a difference here :suspect: I don't have a MacOS + VS setup at hand, so I won't be able to dig into this.

It must have to do something with the IDE, because if I run `dotnet build && dotnet test` in terminal it does not fail any test.

**Comment by dennisdoomen** [comment]
The best way to debug this is to build a debug version of the Nuget package and use that in your IDE. Then you can debug the `CallerIdentifier` class.

**Comment by IT-VBFK** [comment]
You mean install the packed debug-version into a new project, do you?

**Comment by dennisdoomen** [comment]
Yes. By adding the locally build nuget package containing the debug version of FA and then trying to figure out where the `CallerIdentifier` is misbehaving.

**Comment by IT-VBFK** [comment]
Ohh.. I feel really dumb right now 🙈 

I'm so sorry to have bothered you. But the fail doesn't come from FA, but from test runner executing with net47, which is difficult an a mac.
If I run these tests with net6.0 all is working fine.

Sorry again 😢

**Comment by dennisdoomen** [comment]
I still don't get it. How could your test runner use .NET 4.7?

**Comment by IT-VBFK** [comment]
I have no clue 🤷‍♂️ 

This is what I can choose (german btw):
<img width="569" alt="image" src="https://github.com/fluentassertions/fluentassertions/assets/49762557/79dcb05b-309f-4a12-a768-6e080db1665e">
