### ISSUE TITLE
Methods are not guarded against being wrapped in an `AssertionScope`

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#2400]
### Description

When doing #2399 I found that these four methods in `TypeAssertions` are not guarded against being wrapped in an `AssertionScope`.

* `HaveExplicitProperty`
* `NotHaveExplicitProperty`
* `HaveExplicitMethod`
* `NotHaveExplicitMethod`

See how we call `Should().Implement()` and the make the next assertion without any guards.
https://github.com/fluentassertions/fluentassertions/blob/f4c3d56d5524996f6dc6bd02024fce88f55941d9/Src/FluentAssertions/Types/TypeAssertions.cs#L976-L984

### Reproduction Steps

```cs
var act = () =>
{
    using var _ = new AssertionScope();
    typeof(int).Should().HaveExplicitProperty(typeof(IExplicitInterface), "Foo");
};

act.Should().Throw<XunitException>()
    .WithMessage("Expected type System.Int32 to*implement IExplicitInterface.Foo, but it does not.");
```

### Expected behavior

pass

### Actual behavior

```
Expected exception message to match the equivalent of "Expected type System.Int32 to*implement IExplicitInterface.Foo, but it does not.", but "Expected type System.Int32 to implement interface FluentAssertions.Specs.Types.IExplicitInterface, but it does not.
Expected System.Int32 to explicitly implement FluentAssertions.Specs.Types.IExplicitInterface.Foo, but it does not.
" does not.
```

### Are you willing to help with a pull-request?

Yes, please assign this issue to me.

**Comment by IT-VBFK** [comment]
I am excited to know how we can guard for assertions scope after `Subject.Should().Implement(interfaceType, because, becauseArgs); `.

**Comment by jnyrup** [comment]
I don't have any pretty ideas.

My first shot, that would require the least changes, was to check `AssertionScope.Current.HasFailures()`, but that won't work if another assertion has already failed before calling `HaveExplicitProperty`.
```
using var _ = new AssertionScope();
true.Should().BeFalse();
typeof(int).Should().HaveExplicitProperty(typeof(IExplicitInterface), "Foo");
```

Also I noticed an inconsistency in the two failure messages:
```
Expected type System.Int32 to implement interface FluentAssertions.Specs.Types.IExplicitInterface, but it does not.
Expected System.Int32 to explicitly implement FluentAssertions.Specs.Types.IExplicitInterface.Foo, but it does not.
```

My best guess to either copy some implementation from `Implement` into the four listed methods or if feasible extract some parts into a shared method.

**Comment by IT-VBFK** [comment]
>  if feasible extract some parts into a shared method.

That could work I think:

```csharp
private bool SomeMethod(Type expected,[....])
{
    return ExecuteAssertion.ForCondition(...).FailWith(...);
}
```

**Comment by jnyrup** [comment]
> Do you mind if I give a try on this one?

Not at all, see where you can get it.

If `Implement()` and `HaveExplicitProperty` could have individual failure messages, that would be a bonus.

**Comment by IT-VBFK** [comment]
> Also I noticed an inconsistency in the two failure messages:
>
> Expected type System.Int32 to implement interface FluentAssertions.Specs.Types.IExplicitInterface, but it does not.
> Expected System.Int32 to explicitly implement FluentAssertions.Specs.Types.IExplicitInterface.Foo, but it does not.

Isn't this difference by design? Because the first failure tells about implementing the interface at all and the second about explicitly implementing a property/method?

So:
> If Implement() and HaveExplicitProperty could have individual failure messages, that would be a bonus.

would already kind of fulfill this?
