### ISSUE TITLE
Using which after BeOfType shows wrong information if assertions fails

### ISSUE THREAD

**Issue by comecme** [fluentassertions/fluentassertions#2407]
### Description

I'd expect a failure on an assertion after using `.Which` to report the property I am asserting if the assertions fails.

I must admit that the documentation doesn't tell me what to expect if the assertions fails, it just lists all kinds of assertions you can make, including `Which`. If it is a known limitation of FluentAssertions that is unable to tell me the name of the property on which the assertion fails, than please make that clear in the documentation.

### Reproduction Steps

```csharp
// Arrange
var ex = new Exception("Message");

// Assert
ex.Should().BeOfType<Exception>()
    .Which.Message.Should().Be("Other Message");
```

I know that for Exceptions, I'd better use `Should().Throw<Exception>().WithMessage`. But I am not actualy trying this on an Exception but on a custom type. The above code however shows the problem, using a type that is generally available.

### Expected behavior

Print out an error stating that `Message` was expected to be "Other Message"
```
Expected ex.Message to be "Other Message" with a length of 13, but "Message" has a length of 7, differs near "Mes" (index 0).
```

### Actual behavior

FluentAssertions prints out the following error, stating that `ex` itself was expected to be "Other Message":
```
Expected ex to be "Other Message" with a length of 13, but "Message" has a length of 7, differs near "Mes" (index 0).
```

### Known Workarounds

Split the assertion in to two assertions, althoug that just means you don't use the `Which` method after all.
```csharp
ex.Should().BeOfType<Exception>();
ex.Message.Should().Be("Other Message");
```

### Configuration

Fluent Assertions 6.12.0 on .NET Framework 4.8

### Other information

This example is one of the examples [on the website](https://fluentassertions.com/basicassertions/#:~:text=You%20can%20do%20that%20by%20chaining%20those%20assertions%20onto%20the%20Which%20property%20like%20this.).

### Are you willing to help with a pull-request?

No

**Comment by IT-VBFK** [comment]
#1502 ?

**Comment by comecme** [comment]
As @IT-VBFK suggested, this seems to be a duplicate of #1502
