### ISSUE TITLE
`private protected` members compared by default using `BeEquivalentTo`

### ISSUE THREAD

**Issue by erichiller** [fluentassertions/fluentassertions#2409]
### Description

`private protected` members are check against whereas `private`, `protected`, and `internal` members are all ignored when comparing two objects using `BeEquivalentTo`. I would have expected `private protected` which has a subset of the visibility of `protected` or `internal` to be ignore in the default checks as well.

### Reproduction Steps

```csharp
public class TestClass {
    [ Fact ]
    public void EquivalencyOfPrivateProtectedShouldMatchProtected( ) {
        Class1 class1 = new ();
        Class2 class2 = new ();
        Class3 class3 = new ();
        Class4 class4 = new ();
        class1.Should().BeEquivalentTo( class2 );
        class1.Should().BeEquivalentTo( class3 );
        class1.Should().BeEquivalentTo( class4 ); // <-- FAILS HERE ONLY
    }
}

class Class1 {
    public string Name = "Hello";
}

class Class2 {
    public    string Name             = "Hello";
    protected int    _protectedNumber = 2;
}

class Class3 {
    public   string Name             = "Hello";
    internal int    _protectedNumber = 2;
}

class Class4 {
    public            string Name             = "Hello";
    private protected int    _protectedNumber = 2;
}
```

### Expected behavior

By default I would have expected all of these tests to pass.

### Actual behavior

All tests pass except for the one where the differing field is `private protected`

### Configuration

.NET 7.0
Fluent Assertions 6.12

### Are you willing to help with a pull-request?

No

**Comment by jnyrup** [comment]
Thanks for reporting this, it's fixed on the develop branch which will become v7 at some point.

Until then, you can workaround this by excluding all members with the `private protected` getters.
```cs
using FluentAssertions;
using FluentAssertions.Common;
using FluentAssertions.Equivalency;

[Fact]
public void EquivalencyOfPrivateProtectedShouldMatchProtected()
{
    Class1 class1 = new();
    Class4 class4 = new();
    class1.Should().BeEquivalentTo(class4, opt => opt
        .Excluding(ctx => ctx.WhichGetterHas(CSharpAccessModifier.PrivateProtected)));
}
```

To configure this for all tests, such that you can use
```cs

[Fact]
public void EquivalencyOfPrivateProtectedShouldMatchProtected()
{
    Class1 class1 = new();
    Class4 class4 = new();
    class1.Should().BeEquivalentTo(class4);
}
```
Copy this snippet to a thread-safe initialization point as described in the [documentation](https://fluentassertions.com/extensibility/#thread-safety)
```cs
AssertionOptions.AssertEquivalencyUsing(options => options
    .Excluding(ctx => ctx.WhichGetterHas(CSharpAccessModifier.PrivateProtected)));
```
