### ISSUE TITLE
ThrowWithinAsync does not work with TaskCanceledException

### ISSUE THREAD

**Issue by Arithmomaniac** [fluentassertions/fluentassertions#2444]
### Description

`ThrowWithinAsync` does not work with `TaskCanceledException`, but only AFAICT on async/await methods.

See the reproduction steps, which endeavor to isolate the cause.

### Reproduction Steps

```csharp
await Invoking(async () => { await Task.Delay(1); throw new TaskCanceledException(); })
    .Should().ThrowAsync<TaskCanceledException>();
await Invoking(async () => { await Task.Delay(1); throw new InvalidOperationException(); })
    .Should().ThrowWithinAsync<InvalidOperationException>(TimeSpan.FromSeconds(1));
await Invoking(() => Task.FromException(new TaskCanceledException()) )
    .Should().ThrowWithinAsync<TaskCanceledException>(TimeSpan.FromSeconds(0.5));
await Invoking(async () => { await Task.Delay(1); throw new TaskCanceledException(); })
    .Should().ThrowWithinAsync<TaskCanceledException>(TimeSpan.FromSeconds(1));
```

### Expected behavior

Test passes; all four assertions work

### Actual behavior

Test fails with the following exception, which indicates only the last assertion failed:

```
  Message: 
    Expected a <System.Threading.Tasks.TaskCanceledException> to be thrown within 1s, but no exception was thrown.

  Stack Trace: 
    XUnit2TestFramework.Throw(String message)
    TestFrameworkProvider.Throw(String message)
    DefaultAssertionStrategy.HandleFailure(String message)
    AssertionScope.FailWith(Func`1 failReasonFunc)
    AssertionScope.FailWith(Func`1 failReasonFunc)
    AssertionScope.FailWith(String message)
    AsyncFunctionAssertions`2.AssertThrows[TException](Exception exception, TimeSpan timeSpan, String because, Object[] becauseArgs)
    AsyncFunctionAssertions`2.ThrowWithinAsync[TException](TimeSpan timeSpan, String because, Object[] becauseArgs)
    CollectionExtensionsTests.Foo() line 29
    --- End of stack trace from previous location --
```

### Configuration

xUnit.net VSTest Adapter v2.5.0.1+5ebf84cd75 (64-bit .NET 7.0.13)
FluentAssertions 6.12.0

### Are you willing to help with a pull-request?

No

**Comment by jnyrup** [comment]
Thanks for reporting this.

This is due to [Task.WhenAny](https://github.com/fluentassertions/fluentassertions/blob/43cdbb2e415b6e8f2d5a69b734d416a880c3595b/Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs#L287-L309) swallowing `OperationCancelledException` and returning a canceled exception instead of a faulted exception.

I have some ideas how to workaround this in Fluent Assertions.

**Comment by ITaluone** [comment]
For the record: it seems that the `Task.Delay(x)` does not have any effect on the outcome. 

```csharp
await Invoking(async () =>
{
    await Task.Delay(3000);
    throw new TaskCanceledException();
})
.Should().ThrowWithinAsync<TaskCanceledException>(TimeSpan.FromSeconds(1));
```

and
```csharp
await Invoking(async () =>
{
    await Task.Delay(0);
    throw new TaskCanceledException();
})
.Should().ThrowWithinAsync<TaskCanceledException>(TimeSpan.FromSeconds(5));
```

both fails with the same exception

**Comment by jnyrup** [comment]
> For the record: it seems that the Task.Delay(x) does not have any effect on the outcome.

That is only need to ensure the exception happens after a call to `await`, otherwise the exception is thrown before reaching https://github.com/fluentassertions/fluentassertions/blob/c34940ec65a317e67a388f27c0ff5eb71b01dc0b/Src/FluentAssertions/Specialized/AsyncFunctionAssertions.cs#L227
