### ISSUE TITLE
Types that contain an empty ArraySegment<>s cannot be checked with IsEquivalentTo.

### ISSUE THREAD

**Issue by ShaharPrishMSFT** [fluentassertions/fluentassertions#2446]
### Description

When a type (class/struct) contains an empty ArraySegment<> struct,, some methods fail to work with it.

Specifically, when trying to serialize a message, it will fail with an InvalidOperationException.

I have a pull request solving it: https://github.com/fluentassertions/fluentassertions/pull/2445

### Reproduction Steps

```csharp
class MyClass
{
    public ArraySegment<byte> ArraySegment { get; set; }
}
```

```csharp
// Arrange
var expected = new MyClass();
var actual = new MyClass();

// Act
Action act = () => actual.Should().BeEquivalentTo(expected);

// Assert
act.Should().NotThrow();
```

### Expected behavior

No crash when checking equivalency.

### Actual behavior

An InvalidOperationException is thrown.

### Configuration

	  <PackageReference Include="FluentAssertions" Version="6.12.0" />

### Are you willing to help with a pull-request?

Yes, please assign this issue to me.

**Comment by ITaluone** [comment]
Closed with #2511
