### ISSUE TITLE
Support .NET 8

### ISSUE THREAD

**Issue by vbreuss** [fluentassertions/fluentassertions#2465]
### Background and motivation

On Nov. 14th [.NET 8 ](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) was released. As this is a major version, I suggest that `fluentassertions` should also support .NET 8 as Target Framework.

### Are you willing help with a pull-request?

Yes, please assign this issue to me.

**Comment by ITaluone** [comment]
See discussion here: https://github.com/fluentassertions/fluentassertions/issues/2251

And somewhat here: https://github.com/fluentassertions/fluentassertions/issues/1779 (further down)

**Comment by vbreuss** [comment]
I don't think it is necessary to explicitely target .NET 8 in `fluentassertions.csproj`, but we should update the test suite to run on .NET 8 to make sure, that it can also be used in .NET 8.

**Comment by vbreuss** [comment]
While testing it locally I stumbled upon one issue:
.NET 8 introduced an own [`ITimer`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.itimer?view=net-8.0) interface. This results in a "[CS0104](https://learn.microsoft.com/de-de/dotnet/csharp/misc/cs0104)" warning: `'ITimer' is an ambiguous reference between 'FluentAssertions.Common.ITimer' and 'System.Threading.ITimer'`.

In the `FakeClock` class I added these lines to fix the issue, but I fear this could also affect all users:
```csharp
#if NET8_0_OR_GREATER
using ITimer = FluentAssertions.Common.ITimer;
#endif
```

**Comment by dennisdoomen** [comment]
Until we need to support specific features, we don't need to target .NET 8 for the main project. However, adding .NET 8 as a target for the tests is indeed useful. This probably also require bumping the SDK in the `global.json`.

Next to that, maybe this mean we should either rename our `ITimer` to something else, or adopt the new interface (and provide a polyfill of some sort, e.g. through [PolySharp](https://github.com/Sergio0694/PolySharp)).

**Comment by vbreuss** [comment]
> Next to that, maybe this mean we should either rename our `ITimer` to something else, or adopt the new interface (and provide a polyfill of some sort, e.g. through [PolySharp](https://github.com/Sergio0694/PolySharp)).

The two interfaces are not really compatible:
- Our [`ITimer`](https://github.com/fluentassertions/fluentassertions/blob/develop/Src/FluentAssertions/Common/ITimer.cs) consists of a single property `Elapsed`.
- The Microsoft [`ITimer`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.itimer?view=net-8.0) has a single method `bool Change (TimeSpan dueTime, TimeSpan period)`

**Comment by ITaluone** [comment]
> maybe this mean we should either rename our ITimer to something else

which would be a breaking change?

**Comment by dennisdoomen** [comment]
> which would be a breaking change?

Correct. Although that interface is only `public` because of technical constraints. It's not supposed to be used outside the library.

**Comment by ITaluone** [comment]
> It's not supposed to be used outside the library.

What's supposed and how it's used can differ 😉

**Comment by dennisdoomen** [comment]
> What's supposed and how it's used can differ

That was my point. Can we somehow make it `internal`? If not, I think we should rename it so that we can help our consumers by avoiding naming conflicts.

**Comment by vbreuss** [comment]
I had a look at the usage of the `ITimer`. The main use cases I found were:
- [`NotThrowAfter`](https://github.com/fluentassertions/fluentassertions/blob/develop/Src/FluentAssertions/Specialized/ActionAssertions.cs#L74)-Extensions
  It is used to check if the `waitTime` is already elapsed and the while loop should be terminated
- [`ExecutionTime`](https://github.com/fluentassertions/fluentassertions/blob/develop/Src/FluentAssertions/Specialized/ExecutionTime.cs#L50) class
  It is used to determine the execution time of the callback

In both cases, it does not use recurring events, so it is not the normal use case for a [Timer](https://learn.microsoft.com/en-us/dotnet/api/system.timers.timer). Also the default implementation uses a [`Stopwatch`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch) (see [`StopwatchTimer`](https://github.com/fluentassertions/fluentassertions/blob/develop/Src/FluentAssertions/Common/StopwatchTimer.cs)).

For me the naming is a bit misleading, so if we want to rename the `ITimer` class, I would rename it to `IStopwatch`.

**Comment by jnyrup** [comment]
> > which would be a breaking change?
> 
> Correct. Although that interface is only `public` because of technical constraints. It's not supposed to be used outside the library.


Isn't our `ITimer` well enough hidden under the `FluentAssertions.Common` namespace such that we don't have to change anything? :thinking:

**Comment by jnyrup** [comment]
My current vote is on doing nothing.
Every new type potentially clashes with other types, that's why we have namespaces.

Renaming to `IStopWatch` shifts the _potential_ conflict from being with .NET 8 BCL to e.g. [System.Reactive](https://github.com/dotnet/reactive/blob/main/Rx.NET/Source/src/System.Reactive/Concurrency/IStopwatch.cs).

**Comment by IT-VBFK** [comment]
Or rename it to something specific to this lib (which is weird if someone else uses it)?

Like `IFluentAssertionsStopwatch`

**Comment by dennisdoomen** [comment]
> Isn't our `ITimer` well enough hidden under the `FluentAssertions.Common` namespace such that we don't have to change anything

Yes and no. More types than I expected are under the `FluentAssertions.Common` namespace. For example, `Configuration`, `CSharpAccessModifier`, `DateTimeExtensions`, `IClock`, `IConfigurationStore`, `Services` and `ValueFormatterDetectionMode`

**Comment by Rubenisme** [comment]
@dennisdoomen I see you just released a new major version with .net6 support, while [.NET 6 has reached end of support](https://devblogs.microsoft.com/dotnet/dotnet-6-end-of-support/). 

Can we instead target an LTS version (8)? I'm not sure what .net8 will target now (probably `.netstandard2.0`?) I would suggest to remove the out-of-support versions.

P.S. I don't see a great reason to keep `.netstandard2.1` either, only for pretty old xamarin/mono applications, if they didn't update those by now, they likely will not update to a new major version of `FluentAssertions` either.

**Comment by dennisdoomen** [comment]
> AFAIK (and if I understand the nuget.org framework section correctly) everything up to .net8.0 can be computed by the sdk/runtime

Correct. If you have a unit testing project that targets .NET 8 or 9, it'll use the .NET 6 version of FA. There's no reason for us to target a newer version unless we specifically want to support a feature of a higher .NET version .

**Comment by dennisdoomen** [comment]
And for the record, both `main` and `develop` have their unit test projects multi-target, including .NET 8.0.

So I think we can close this.

**Comment by jnyrup** [comment]
>  I'm not sure what .net8/.net9 applications will target now (probably .netstandard2.0?)

No need to guess.

[Nuget Tools](https://nugettools.azurewebsites.net/6.12.1/get-nearest-framework?project=net8.0&package=net47%0D%0Anetstandard2.0%0D%0Anetstandard2.1%0D%0Anet6.0) points out that a .net8 project using Fluent Assertions 7.0.0 will pick the .net6 TFM.

And we can also verify this by just making a .net8 application, include Fluent Assertions 7.0.0 and see which dll is referenced.
![image](https://github.com/user-attachments/assets/06042b18-26ab-45b9-a0e9-17371df9a791)
