### ISSUE TITLE
IEnumerable gets evaluated multiple times when using BeEmpty()

### ISSUE THREAD

**Issue by Shidairyu** [fluentassertions/fluentassertions#2490]
### Description

There seems to be an issue with `BeEmpty()` when used with `IEnumerable`. The `IEnumerable` gets evaluated multiple times, leading to unexpected behavior.

### Reproduction Steps

```csharp
private bool a = false;

public IEnumerable<string> Get()
{
    if (a)
    {
        yield break;
    }

    a = true;
    yield return "123";
}

[TestMethod]
public void Execute()
{
    var result = Get();

    result.Should().BeEmpty();
}
```

### Expected behavior

I expect the test to fail, with the message: "Expected result to be empty, but found {"123"}."

### Actual behavior

Test fails, but with the message: "Expected result to be empty, but found {empty}."

### Known Workarounds

Converting the `IEnumerable` to a list before asserting solves the issue:
```csharp
[TestMethod]
public void Execute()
{
    var result = Get().ToList();

    result.Should().BeEmpty();
}
```

### Configuration

FluentAssertions version: 6.12.0
.NET version: 7.0

### Other information

The issue seems to arise from how Fluent Assertions handles the evaluation of `IEnumerable`. Ensuring the collection is evaluated only once before the emptiness check might resolve this issue.

### Are you willing to help with a pull-request?

No

**Comment by jnyrup** [comment]
A pitfall here is how to handle infinite enumerables.
For that case we cannot materialize the enumerable and on failure we likewise cannot include all items in the failure message.

We have had some discussions about this in #2000

**Comment by IT-VBFK** [comment]
What issues can possibly occur if we materializing every `IEnumerable<T>`?

**Comment by jnyrup** [comment]
> What issues can possibly occur if we materializing every `IEnumerable<T>`?

Try materializing this sequence
```cs
IEnumerable<int> GetFibonacciNumbers()
{
    int a = 0, b = 1;
    
    do 
    {
        yield return a;
        (a, b) = (b, a + b);
    }
    while(true);
}
```

On a slightly more serious note, #1691 reported that we tried to count the number of items in a infinite sequence.
The only viable solution I can think of, is what I started prototyping in https://github.com/jnyrup/fluentassertions/commits/issue2000_materializing_enumerable/ about a lazily materializing enumerable.

The two constraints are:
* enumerate sequences at most once, and
  * e.g. `[NotBeNull]` should not enumerate at all
* don't fetch more elements than necessary.
  * On sucess `[Not]BeEmpty` only need to fetch a single element to determine if the sequence is empty or not.
  * On failure `EnumerableFormatter` should probably decide how many elements to fetch from the sequence.

**Comment by louis-z** [comment]
I'd be willing to take a stab at it, if no one else has begun working on it.

I was thinking of doing something along the lines of @jnyrup's idea:

> - don't fetch more elements than necessary.
>   - On sucess `[Not]BeEmpty` only need to fetch a single element to determine if the sequence is empty or not.

**Comment by jnyrup** [comment]
@louis-z I haven't gotten around to work more on my prototype.
In any case It'd be great to have another set of eyes on this problem.

**Comment by louis-z** [comment]
I just submitted my first attempt, in which the error message has slightly changed. Is that a problem?
