### ISSUE TITLE
No overload of Equals to compare different types of collections using lambda

### ISSUE THREAD

**Issue by slogen** [fluentassertions/fluentassertions#256]
While trying to write some equivalence-assertions about related (but different) streams of data. I tried to apply the `.Equal` method mentioned in the documentation. However that code does not compile:

``` C#
public class InconsistentWithDocumentation
{
#if DOES_NOT_COMPILE___INCONSISTENT_WITH_DOCUMENTATION
    [Test]
    public void FluentAssertionOnGenericCollectionShouldBeAbleToUseEqual
    {
        new[] {1,2,3}.Should().Equal(new []{'b','c','d'}, (a,e) => e-'a' == a);
    }
    [Test]
    public void FluentAssertionOnCollectionShouldBeAbleToUseEqualWithPredicateAccordingToDocs()
    {
        ((IEnumerable)new[] { 1, 2, 3 }).Should().Equal(new[] { 1, 2, 3 }, (left,right) => left == right);
    }
#endif
    [Test]
    public void ExpectedBehavior()
    {
        new[] { 1, 2, 3 }.Zip(new[] { 'b', 'c', 'd' }, (a, e) => e - 'a' == a).ShouldAllBeEquivalentTo(new[] { true, true, true });
    }
}
```

Looking through the code I cannot find any overload of `Equal` that supplied the documented behavior. I am unfortunately not confident enough in the workings of fluentassertions to assert that this is in fact an inconsistency in the docs and even less so in updating the docs with the current best-practice for the use-case.

**Comment by dennisdoomen** [comment]
The two collections involved should be of the same type, which is in line with the documentation. It should be reasonably simple to add another overload though. I'll put that on the backlog, but feel free to provide me with a pull request to speed things up.

**Comment by Serg046** [comment]
The first example is now working, the second is not because the type should be generic which is quite obvious imo.

**Comment by Serg046** [comment]
The first example is now working, the second is not because the type should be generic which is quite obvious imo.

**Comment by dennisdoomen** [comment]
It would require an overload that takes two generic parameters. 

```
        public AndConstraint<TAssertions> Equal<TLeft, TRight>(
            IEnumerable<TExpected> expectation, Func<T, TLeft, TRight, bool> equalityComparison, string because = "", params object[] becauseArgs)
```

**Comment by dennisdoomen** [comment]
Since nobody looked at this or requested something similar for many years, I'm closing this
