### ISSUE TITLE
ComparingEnumsByName() seems not to work as expected

### ISSUE THREAD

**Issue by rizi** [fluentassertions/fluentassertions#2567]
### Description

I want to compare two objects, one object has a string property and one object has an enum property, therefore I want to compare the enum property **by name** and not by value, I think it's exactly the use-case that is described here: https://fluentassertions.com/objectgraphs/#enums

### Reproduction Steps
It makes no difference if I use a class or a record (it behaves equally).
```csharp
public enum State
{
    New,
    DataPending,
    Initialized   
}

public record Order(string Name, State State);

public record OrderDto(string Name, string State);
```

```csharp
// Arrange
OrderDto orderDto = new Order("Test", "DataPending");
Order order = new Order("Test", State.DataPending);


// Act && Assert
orderDto.Should().BeEquivalentTo(order, options => options.ComparingEnumsByName());
```

### Expected behavior

The test should be green because orderDto and order are equivalent (because the enum value should be compared by name)

### Actual behavior

The test is red with the following message:
Expected property orderDto.State to be equivalent to State.DataPending {value: 1}, but found "DataPending".

### Configuration

We are using FluentAssertions 6.12.0 and .Net 8.0.

### Are you willing to help with a pull-request?

Yes, please assign this issue to me.

**Comment by jnyrup** [comment]
> Note that even though an enum’s underlying value equals a numeric value or the enum’s name equals some string value, we do not consider those to be equivalent. In other words, enums are only considered to be equivalent to enums of the same or another type, but you can control whether they should equal by name or by value.

`ComparingEnumsByName` controls whether two (different) enums are compared by the _name_ of enum member or the _value_ of the enum member.
E.g. if `Foo.A` is considered equal to `Bar.A` or `Bar.B`, i.e. 
```cs
enum Foo { A = 13, B = 37}
enum Bar { A = 37, B = 13}
```

To compare two properties where one is an enum and the other a string, see #1670.

**Comment by rizi** [comment]
> > Note that even though an enum’s underlying value equals a numeric value or the enum’s name equals some string value, we do not consider those to be equivalent. In other words, enums are only considered to be equivalent to enums of the same or another type, but you can control whether they should equal by name or by value.
> 
> `ComparingEnumsByName` controls whether two (different) enums are compared by the _name_ of enum member or the _value_ of the enum member. E.g. if `Foo.A` is considered equal to `Bar.A` or `Bar.B`, i.e.
> 
> ```cs
> enum Foo { A = 13, B = 37}
> enum Bar { A = 37, B = 13}
> ```
> 
> To compare two properties where one is an enum and the other a string, see #1670.

ah thank you very much for the fast reply.
