### ISSUE TITLE
Add support for asserting NaN values

### ISSUE THREAD

**Issue by xp-development** [fluentassertions/fluentassertions#2579]
### Background and motivation

It would be nice if there is an extension method for double and float values to check NaN values.

`
double value = double.NaN;
value.Should().BeNaN( );
`

### Are you willing help with a pull-request?

No

**Comment by dennisdoomen** [comment]
@jnyrup seems to be a fair request and a good candidate for new contributors.

**Comment by jnyrup** [comment]
Even though we technically already support comparing against `NaN` using `Be`, I find this a nice little addition.
https://github.com/fluentassertions/fluentassertions/blob/daebdf3c107afe5293e17f453d8b5af1705a6c26/Tests/FluentAssertions.Specs/Numeric/NumericAssertionSpecs.Be.cs#L264-L272

Compared to using `Be`, `BeNaN` will make the test more resistant, i.e. doesn't have to be changed, if changing the subject type from `double` to `float`.

**Comment by lg2de** [comment]
> Compared to using `Be`, `BeNaN` will make the test more resistant, i.e. doesn't have to be changed, if changing the subject type from `double` to `float`.

Interesting question: Is double NaN different from double NaN?

**Comment by dennisdoomen** [comment]
> Interesting question: Is double NaN different from double NaN?

ChatGPT to the rescue: When comparing NaN to any other floating-point value, including itself, the result is always false. This means that a NaN is considered unequal to another NaN. This behavior is specified by the IEEE Standard for Floating-Point Arithmetic (IEEE 754), which is widely adopted by modern computer systems and programming languages.

**Comment by lg2de** [comment]
In this case we could not check for NaN at all, isn't it?

**Comment by dennisdoomen** [comment]
Yes, we can. There is a `float.IsNaN()` method.

**Comment by arocheleau** [comment]
Unless someone disagree, the extension methods

```
value.Should().BeNaN()
value.Should().NotBeNaN()
```

will be added for `float`, `double`, `float?` and `double?` values.  Internally, they will check using `float.IsNaN` and `double.IsNaN`.

**Comment by xp-development** [comment]
Double.IsInfinity support would be nice, too. 😁

**Comment by xp-development** [comment]
Thanks for adding the feature!
