### ISSUE TITLE
WithInnerException<T>() needs the type as a parameter

### ISSUE THREAD

**Issue by jjvdgeer** [fluentassertions/fluentassertions#2598]
### Description

I think this should compile:

```csharp
           Func<Task<int>> act = () => Task.FromResult(42);

           act.Should().ThrowAsync<InvalidOperationException>()
               .WithInnerException<ArgumentException>()
               .WithMessage("whatever");

```

but it does not. The WithInnerException method is defined like this:
```csharp
    public static async Task<ExceptionAssertions<Exception>> WithInnerException<TException>(
        this Task<ExceptionAssertions<TException>> task,
        Type innerException,
        string because = "",
        params object[] becauseArgs)
        where TException : Exception
    {
        return (await task).WithInnerException(innerException, because, becauseArgs);
    }
```

Shouldn't that be something like this? :

```csharp
    public static async Task<ExceptionAssertions<Exception>> WithInnerException<TException>(
        this Task<ExceptionAssertions<TException>> task,
        string because = "",
        params object[] becauseArgs)
        where TException : Exception
    {
        return (await task).WithInnerException(typeof(TException), because, becauseArgs);
    }
```

### Reproduction Steps

```csharp
           Func<Task<int>> act = () => Task.FromResult(42);

           act.Should().ThrowAsync<InvalidOperationException>()
               .WithInnerException<ArgumentException>()
               .WithMessage("whatever");
```

### Expected behavior

It compiles

### Actual behavior

There is no argument given that corresponds to the required parameter 'innerException'

### Are you willing to help with a pull-request?

No

**Comment by dennisdoomen** [comment]
I'm also surprised a bit, but I suspect it has something to do with a compiler limitation. One thing though. You need to `await` the call to `act.Should().ThrowAsync`

**Comment by jjvdgeer** [comment]
Thanks and a good point about the await. I didn't have that because I was migrating from version 5.x of FluentAssertions to version 6.x where the Throw<T>() no longer exists and I was struggling to get that working. Now I know! Thanks again!
