### ISSUE TITLE
FluetntAssertion doesn't work correctly for records

### ISSUE THREAD

**Issue by AlexeyRaga** [fluentassertions/fluentassertions#2603]
### Description

Let's have this data structure:

```csharp
public abstract record Foo
{
    public sealed record A(string Value) : Foo;
}
```

and this test:

```csharp
Foo a = new Foo.A("alexey");
Foo b = new Foo.A("raga");

a.Should().BeEquivalentTo(b);
```

It suddenly fails with 
```
No members were found for comparison. Please specify some members to include in the comparison ...
```

That's strange, but let's add an artificial member:
```csharp
public abstract record Foo
{
    public bool IsA => this is A;
    public sealed record A(string Value) : Foo;
}
```

and now this test **PASSES** as green!

### Reproduction Steps

```csharp
public abstract record Foo
{
    public bool IsA => this is A;
    public record A(string Value) : Foo;
}

public sealed class FooTests(ITestOutputHelper testOutputHelper)
{
    [Fact]
    public void Test()
    {
        Foo a = new Foo.A("alexey");
        Foo b = new Foo.A("raga");

        // This prints "false"
        testOutputHelper.WriteLine((a == b).ToString());

        // This doesn't fail the test
        a.Should().BeEquivalentTo(b);
    }
```

### Expected behavior

Values are compared correctly and the test only passes when they are equal

### Actual behavior

Test passes on values that are not equal

### Known Workarounds

Use `Assert.Equivalent` instead of `FluentAssertions`

### Configuration

.NET: `8.0`
FluentAssertions: `6.12.0`, `7.0.0-alpha.3`
XUnit: `2.7.0`

### Other information

The use case above is a minimised one, the real use case includes scenarios like:

```csharp
public abstract record Either<TLeft, TRight>
{
    private Either() {}

    public bool IsLeft => this is Left;
    public bool IsRight => this is Right;

    public sealed record Left(TLeft Value) : Either<TLeft, TRight>;
    public sealed record Right(TRight Value) : Either<TLeft, TRight>;
}
```

### Are you willing to help with a pull-request?

No

**Comment by dennisdoomen** [comment]
This is by design. Based on popular request, we [decided](https://fluentassertions.com/objectgraphs/#value-types) to have `BeEquivalentTo` treat records as normal types with members. So if the record doesn't have members, it'll complain about that.

**Comment by AlexeyRaga** [comment]
@dennisdoomen I see, thanks.

I still not understand though why only members of an abstract class are considered, and not members of a concrete value type, though...

**Comment by dennisdoomen** [comment]
> @dennisdoomen I see, thanks.
> 
> I still not understand though why only members of an abstract class are considered, and not members of a concrete value type, though...

But in the original example, there are no members. Just a nested record type. Or am I missing something?

**Comment by AlexeyRaga** [comment]
Or maybe I misunderstand :)

```csharp
public abstract record Foo
{
    public bool IsA => this is A;
    public record A(string Value) : Foo;
}

Foo a = new Foo.A("alexey");
Foo b = new Foo.A("raga");
```

These `a` and `b` are the values of the "nested" type `Foo.A`.  Sure, the variables are upcasted to an abstract `Foo`, but the values themselves are of type `Foo.A`.

But it looks like `BeEquivaluentTo` only considers members of the abstract class `Foo` (in this case `IsA`) and ignores the `Value` member of `Foo.A`.

**Comment by dennisdoomen** [comment]
That's because `Foo.A` and `Foo` are completely different types.

**Comment by AlexeyRaga** [comment]
`Foo` is a parent of `Foo.A`.

I nailed it down to this strange example:
```csharp
    [Fact]
    public void Test1()
    {
        Foo.A a = new Foo.A("alexey");
        Foo.A b = new Foo.A("raga");

        // This fails (correctly)!
        a.Should().BeEquivalentTo(b);

        var fooA = (Foo)a;
        var fooB = (Foo)b;

        // This passes (BUT I THINK IT SHOULD FAIL)!
        fooA.Should().BeEquivalentTo(fooB);

        var objA = (object)a;
        var objB = (object)b;

        // This fails (correctly)!
        objA.Should().BeEquivalentTo(objB);
    }
 ```

So, casting to an immediate parent makes the test pass. Despite the values being different. But casting it further to `object` makes the test fail again, as expected...

May be it is by design and I just don't get the reasoning...

**Comment by AlexeyRaga** [comment]
`opts.RespectingRuntimeTypes()` makes it work, but then casting to `object` works without it...

**Comment by dennisdoomen** [comment]
Foo.A a = new Foo.A("alexey");
        Foo.A b = new Foo.A("raga");

        // This fails (correctly)!
        a.Should().BeEquivalentTo(b);

Does the base-class `Foo` have any properties? And if so, are their values different? Otherwise, it should succeed.
