### ISSUE TITLE
FluentAssertions: using a NullorEqual string EqualityComparer still returns a type difference error

### ISSUE THREAD

**Issue by alelom** [fluentassertions/fluentassertions#2621]
### Description

I'm trying to use FluentAssertions to consider strings equal when they are null or empty, as it is attempted in a few old questions on StackOverflow<sup>1</sup>. In this case, I am attempting to use a custom EqualityComparer, as follows:

```cs
 [Test]
 public void StringNullOrEmpty()
 {
     Dictionary<string, object> dict1 = new();
     Dictionary<string, object> dict2 = new();
     dict1["Name"] = null;
     dict2["Name"] = "";

     dict1.Should().BeEquivalentTo(dict2, opt => opt.Using(new NullStringComparer()));
 }


 private class NullStringComparer : EqualityComparer<string>
 {
     public static IEqualityComparer<string> NullEqualsEmptyComparer { get; } = new NullStringComparer();

     public override bool Equals(string x, string y)
     {
         // equal if string.Equals(x, y)
         // or both StringIsNullOrEmpty
         return String.Equals(x, y)
             || (String.IsNullOrEmpty(x) && String.IsNullOrEmpty(y));
     }

     public override int GetHashCode(string obj)
     {
         if (String.IsNullOrEmpty(obj))
             return 0;
         else
             return obj.GetHashCode();
     }
 }

```

I do not understand the error I get, which is: 
```
Expected dict1[Name] to be of type System.String, but found <null>
```

Is this expected behaviour, am I missing something? It feels like I should not get any exception here.

______________

<sup>1</sup> All other SO questions I found on this topic are older and have attempts that do not make use of `EqualityComparer`. Since [this feature was added more recently than those questions](https://github.com/fluentassertions/fluentassertions/issues/1236), I would like to use it. Some example SO questions I found:
- https://stackoverflow.com/questions/65205342/fluent-assertions-null-and-empty-string-comparison
- https://stackoverflow.com/questions/24033905/how-can-i-compare-null-and-string-empty-or-in-fluent-assertions
- https://stackoverflow.com/questions/39084977/fluentassertions-how-make-shouldbeequivalentto-compare-empty-and-null-as-equal

### Reproduction Steps

See description.

### Expected behavior

No error should be found, the equality should succeed.

### Actual behavior

The error `Expected dict1[Name] to be of type System.String, but found <null>` is raised.

### Are you willing to help with a pull-request?

No

**Comment by jnyrup** [comment]
In v6.12 `EqualityComparerEquivalencyStep` needs as non-null subject.
https://github.com/fluentassertions/fluentassertions/blob/ead29b93ea1b9dda1b7fd80b4bc014a4f9a007f2/Src/FluentAssertions/Equivalency/Steps/EqualityComparerEquivalencyStep.cs#L26

In the next version (see #2489 ) it will need both non-null subject and expectation.
https://github.com/fluentassertions/fluentassertions/blob/7632b789cee6dc4a739d12131fff8b3b467a6bed/Src/FluentAssertions/Equivalency/Steps/EqualityComparerEquivalencyStep.cs#L24-L28

To handle when subject or expectation is null, you can implement an `IEquivalencyStep`.
This will also ensure that if subject and expectation are not deemed equivalent by this step, the regular `StringEqualityEquivalencyStep` will be used to compare strings.

```cs
[Test]
public void StringNullOrEmpty()
{
    Dictionary<string, object> dict1 = new();
    Dictionary<string, object> dict2 = new();
    dict1["Name"] = null;
    dict2["Name"] = "";

    dict1.Should().BeEquivalentTo(dict2, opt => opt.Using(new NullStringEquivalencyStep()));
}

private class NullStringEquivalencyStep : IEquivalencyStep
{
    public EquivalencyResult Handle(Comparands comparands, IEquivalencyValidationContext context, IEquivalencyValidator nestedValidator)
    {
        if (comparands.GetExpectedType(context.Options) == typeof(string)
            && string.IsNullOrEmpty(comparands.Subject as string)
            && string.IsNullOrEmpty(comparands.Expectation as string))
        {
            return EquivalencyResult.AssertionCompleted;
        }

        return EquivalencyResult.ContinueWithNext;
    }
}
```

**Comment by alelom** [comment]
I see. Thanks for the workaround with `IEquivalencyStep`. I find it a bit confusing that the implementation that leverages the comparer doesn't work out of the box, but I can see that in `EqualityComparerEquivalencyStep` this was likely required due to the fact that `null` objects don't retain the original type in C#. I wasn't clear on it, until I stumbled on this [blog post](https://blog.ploeh.dk/2015/11/13/null-has-no-type-but-maybe-has/) and the more in-depth [explanation of Eric Lippert](https://ericlippert.com/2013/07/25/what-is-the-type-of-the-null-literal/).
