### ISSUE TITLE
Name an assertion/property

### ISSUE THREAD

**Issue by mika76** [fluentassertions/fluentassertions#263]
As far as I can see, when a test is run the failed message returns the actual and expected values, but there is no name of the property shown.

So if I say 

```
5.Should().Be(10);
```

It returns "Message: Expected 10, but found 5", but if you have multiple assertions you have no idea which one failed.

Could you not add a named property to Should or a fluent method like .Named(string name) and then add the name to the output messages. I think this would work well and could look like:

```
5.Should("some number").Be(10);

5.Should().Named("some number").Be(10) 
```

would give "some number: Expected 10, but found 5"

**Comment by dennisdoomen** [comment]
Why not just use the `because` parameter?

**Comment by mika76** [comment]
Doesn't really look or sound right :smile:

**Comment by dennisdoomen** [comment]
Really? What about this?

    5.Should().Be(10, "because some number was set for some reason");

**Comment by mika76** [comment]
I was just teasing it

so
```
5.Should().Be(10, "because some number was set for some reason");
```
would return "Expected 10, but found 5 because  some number was set for some reason"

I still think if it was
```
5.Should().Named("Age").Be(10);
```
equals "Expect Age to be 10, but found 5" is more readable and understandable, plus less words in most cases. And adding because to that would be something like "Expected Age to be 10, but found 5 because age should not be taken for granted" is a wonderful way to see things

Also the name could be taken from MethodInfo or PropertyInfo and could be automatically populated.

**Comment by dennisdoomen** [comment]
I'm going to think about this a bit more. Maybe I can come up with a nice, fluent, syntax. Technically, if you wrap the call in an `AssertionScope`, you get just that.

**Comment by mika76** [comment]
Wow, I didn't even know about AssertionScopes. I will give that a try thanks. Seems a but wordy for what I wanted, but it just might work.

**Comment by dennisdoomen** [comment]
@mika76 And? Works for you?

**Comment by mika76** [comment]
Hi @dennisdoomen yes I ended up using AssertionScopes. They fit the bill, although they have the one difference in execution that all assertions executie and dont stop on first failure. It was ok in my case, although I still think the above syntax I suggested looks nice :smile: If you like, you can close this issue.

**Comment by dennisdoomen** [comment]
OK, I'll keep it open and ponder on it for a bit.

**Comment by krajek** [comment]
Although I recognize the possible usefulness of the idea, I think by now we have enough tools to help us identify the failed assertion.

- First of all, there is subject identification. As far as I understand it was not available three years ago.
- Secondly, there is the `because` parameter?
- Lastly, unit test runners automatically point you to the line that threw the exception.

@mika76 Would you agree that adding functionality you described would bring little gain in some very specific cases? In that case, you could close the issue.

**Comment by mika76** [comment]
@krajek it seems subject does exactly what I originally wanted. This is great! Will close.
