### ISSUE TITLE
[Feature]: Compile time warning/error for chaining Should() after a null conditional (?.)

### ISSUE THREAD

**Issue by Guitarnivore** [fluentassertions/fluentassertions#2655]
### Background and motivation

I ran into an issue where some of my tests were incorrectly passing when utilising the null conditional operator (`?.`) to access properties inside a model to verify with `Should()`.

Since the `?.` operator only runs methods chained to the end if the object is not null, then having `Should()` follow a conditional access means that it will never get run.

For example, the following test will pass since `Should()` never gets run against the null `Model` object.
```cs
public class Model
{
    public int Property => 2
}

...

public void Test()
{
    Model? m = null;
    // Should() will not run here and incorrectly cause the test to pass.
    m?.Property.Should().Be(1);
}
```

I propose that a compile time warning/error be implemented letting developers know that `Should()` will not be run against any null object with the null conditional operator. This will help increase understanding of how the `?.` operator works as well as help prevent any erroneous usage with Fluent improving correct test coverage.

### Are you willing help with a pull-request?

No

**Comment by ITaluone** [comment]
Why not just checking for not `null` before?

```csharp
Model? m = null;

m.Should().NotBeNull().And.Subject.As<Model>().Property.Should().Be(1);
```

**Comment by jnyrup** [comment]
This is detected by https://github.com/fluentassertions/fluentassertions.analyzers

![image](https://github.com/fluentassertions/fluentassertions/assets/919634/eaaa9105-9931-491c-b4e4-a4ae088a8259)

I would suggest using either of these
```cs
m.Property.Should().Be(1);
```

```cs
(m?.Property).Should().Be(1);
```

```cs
m.Should().NotBeNull();
m.Property.Should().Be(1);
```

**Comment by Guitarnivore** [comment]
I agree with all your suggestions, the Fluent Analyzers message is what I was looking for!

Thanks!
