### ISSUE TITLE
Equivalency assertion fails for nullable types when both values are null and an EqualityComparer for the non-nullable type is specified

### ISSUE THREAD

**Issue by scharnyw** [fluentassertions/fluentassertions#2678]
### Description

Not sure if this is already covered by #2595. If it is, please feel free to close this issue.

For equivalency assertions where there's a nullable type concerned, it should always compare equal if both sides are null. However, currently the assertion fails if both sides are null and there's an EqualityComparer specified for the non-nullable type (which arguably should have no impact on the nullable type comparison).

### Reproduction Steps

```csharp
var x = new MyClass();
var y = new MyClass();

x.Should().BeEquivalentTo(y, options => options.Using(new MyIntegerEqualityComparer()));

class MyClass
{
    public int? MyNullableInteger { get; init; }
}

class MyIntegerEqualityComparer : IEqualityComparer<int>
{
    public bool Equals(int x, int y)
    {
        return x == y;
    }

    public int GetHashCode(int obj)
    {
        return obj.GetHashCode();
    }
}
```

### Expected behavior

Assertion is successful.

### Actual behavior

Assertion fails with below exception.

`FluentAssertions.Execution.AssertionFailedException: 'Expected property x.MyNullableInteger to be of type System.Int32, but found <null>`

### Configuration

FluentAssertions 6.12.0
.NET 8.0

### Are you willing to help with a pull-request?

No

**Comment by ITaluone** [comment]
This test passes on latest develop
