### ISSUE TITLE
Support for xUnit.net v3

### ISSUE THREAD

**Issue by 0xced** [fluentassertions/fluentassertions#2709]
### Background and motivation

I just read [What’s New in xUnit.net v3](https://xunit.net/docs/getting-started/v3/whats-new) and figured this is relevant to FluentAssertions.

> A new `FailureCause` enum has been added, and is returned inside `ITestFailed` messages. It gives a best guess as to the cause of the test failure: assertion failure, exception thrown, or test timed out.
> 
> This best guess is based on two contracts added to v3 which can be implemented by third party assertion libraries. Throwing an exception which implements an interface named `IAssertionException` (in any namespace) will be reported as an assertion failure; similarly, throwing an exception which implements an interface named `ITestTimeoutException` (in any namespace) will be reported as a timed-out test.

This looks like an easy task to implement for FluentAssertions.

### Are you willing help with a pull-request?

Yes, please assign this issue to me.

**Comment by lg2de** [comment]
Xunit V3 is currently in version 0.2.0-pre.69.
I think it is too early to adopt it in FA.
This is currently the second attempt vor Xunit3. The first one was stopped after long development time.

**Comment by 0xced** [comment]
I have been following [Brad Wilson](https://mastodon.social/@bradwilson) on Mastodon lately and it really looks like v3 is happening. Also, see [this post from the xUnit.net account](https://dotnet.social/@xunit/112881458424002481):

> To answer what will be an inevitable question: "Does this mean no more v2 releases?"
> 
> The answer is: "Ideally, yes, but realistically, there may be bug fixes. As of today, v2 is the past, and v3 is the present."

Anyway, I just filed this issue as a reminder to look into it.

**Comment by dennisdoomen** [comment]
Do IDEs like Visual Studio and Rider work with the prerelease version?

**Comment by 0xced** [comment]
I haven't tried in Visual Studio (probably @bradwilson can answer this) but for Rider it [doesn't work yet](https://youtrack.jetbrains.com/issue/RSRP-497885). With the latest early access preview version (2024.2 EAP9) tests are discovered but running them is _inconclusive_ (i.e. crashes inside JetBrains.ReSharper.TestRunner).

**Comment by dennisdoomen** [comment]
Then we should wait until the official release is out. I don't use Visual Studio anymore.

**Comment by bradwilson** [comment]
The tracking item for Resharper/Rider is marked as complete, but afaik it hasn't shipped yet. Presumably in the next build.

https://youtrack.jetbrains.com/issue/RSRP-497885

**Comment by 0xced** [comment]
Although it's not mentioned in the [The Rider 2024.2 Release Candidate Is Now Available](https://blog.jetbrains.com/dotnet/2024/08/07/rider-2024-2-rc/) blog post, xUnit.net v3 support is available and working well in JetBrains Rider 2024.2 RC 1. 🎉

**Comment by bradwilson** [comment]
I have verified that it works with the current bits, and if you install our project templates, they're even there too. 😄 https://dotnet.social/@xunit/112927298642172250

![1aa58f3b3fb60cf0](https://github.com/user-attachments/assets/b7492694-078a-4d9a-ba80-5ed7e58efbab)

![0c34ad282be25e90](https://github.com/user-attachments/assets/5b185cbd-43fe-4c86-981f-00504f54d023)

**Comment by dennisdoomen** [comment]
That's great news @bradwilson

**Comment by bradwilson** [comment]
Apparently debugging isn't working yet, according to Simon Cropp: https://hachyderm.io/@simoncropp/112935177439183192

**Comment by bradwilson** [comment]
Actually, I take it back, Khalid and I are both able to use the debugger, so I'm not 100% sure what issue Simon ran into.
