### ISSUE TITLE
Lack of proper support for `decimal` in `InlineData`.

### ISSUE THREAD

**Issue by satma0745** [fluentassertions/fluentassertions#2713]
### Description

When a `[Theory]` test method accepts a decimal parameter, which value is provided by several `[InlineData(...)]` attributes, the following warnings are issued:
1. `xUnit1025: Theory method 'Test1' on test class 'UnitTest1' has InlineData duplicate(s). Remove redundant attribute(s) from the theory method.` (even though all decimal literals differ from each other).
2. `xUnit1012: Null should not be used for type parameter 'decimalInlineData' of type 'decimal'. Use a non-null value, or convert the parameter to a nullable type.` (even thought all decimal literals aren't null).

### Reproduction Steps

To reproduce this, You can just:
1. Create a new project from the `xunit` template using the `dotnet new xunit --name XunitDecimal --output .` command.
2. Upgrade all dependencies (including `xunit` ones).
3. Replace the contents of the `UnitTest1.cs` file with the following code snippet:

```csharp
namespace XunitDecimal;

public class UnitTest1
{
    [Theory]
    [InlineData(1m)]
    [InlineData(2m)]
    [InlineData(3m)]
    public void Test1(decimal decimalInlineData)
    {
        // ...
    }
}
```

### Expected behavior

Not receiving `xUnit1025` and `xUnit1012` warnings in this case.

### Actual behavior

`xUnit1025` and `xUnit1012` warnings are issued.

### Regression?

I'm not sure if this worked previously, but it doesn't work in both `2.7.0` and `2.9.0` versions of `xunit`.

### Known Workarounds

The best I can think of:
1. Turning off these warnings for method, class or an entire file.
2. Changing test method's parameter from `decimal` to `decimal?` to silence the `xUnit1012` warning, but it results in more warnings being issued in the actual test code.

### Configuration

.Net SDK version 8.0.303
Xunit versions 2.7.0 and 2.9.0

### Are you willing to help with a pull-request?

No

**Comment by satma0745** [comment]
I'm sorry - looks like the CLR itself doesn't allow using `System.Decimal` literals in attributes.
So these warnings (despite being misleading) aren't blocking me in this case: even if I hadn't these warnings, code wouldn't compile either way.

**Comment by dennisdoomen** [comment]
No worries.
