### ISSUE TITLE
[Feature]: New test framework support - TUnit

### ISSUE THREAD

**Issue by thomhurst** [fluentassertions/fluentassertions#2757]
### Background and motivation

I've been building a new testing framework, and in the Fluent assertions docs it says it will detect test frameworks and do some internal logic/mapping.

Would you be willing to support a new testing framework? And if so, what is required? I'd be willing to help out where possible but I've never looked at your codebase before so I may need some direction.

Can I also ask what the current mapping is for? Because if you throw exceptions normally my test frameworks would still fail your tests, so I'd be interested in how or what this would change.

My framework can be found at https://github.com/thomhurst/TUnit

Thanks very much :)

### Are you willing help with a pull-request?

Yes

**Comment by ITaluone** [comment]
I think a good start is the `ITestFramework` interface and its implementations. Further, you should have a look at `TestFrameworkProvicer` to understand that mapping.
