### ISSUE TITLE
[Feature]: Improve Documentation Navigation by Adding Section Highlighting for Better User 

### ISSUE THREAD

**Issue by sentemon** [fluentassertions/fluentassertions#2806]
### Background and motivation

Currently, in the documentation sidebar, all section titles and categories are displayed in a single color, making it challenging to identify the section that the user is currently viewing. Adding a color highlight or bold styling to the active section title would greatly improve navigation. This change would provide users with a visual cue to easily locate their current section, particularly when scrolling through longer lists of topics.

This enhancement would help users stay focused on relevant sections without losing track of where they are, resulting in a smoother and more intuitive user experience.

### Alternative Concerns

An alternative could be to use an icon or an underline next to the active section instead of color highlighting. However, using a distinct color or bold styling would likely be the most accessible and straightforward option.

### Are you willing help with a pull-request?

Yes, please assign this issue to me.

**Comment by dennisdoomen** [comment]
Sure, go ahead. Notice though that the website is build from the `master` branch.

**Comment by sentemon** [comment]
https://github.com/fluentassertions/fluentassertions/pull/2807
