### ISSUE TITLE
Better support for FluentAssertion within Expression<> trees

### ISSUE THREAD

**Issue by hugener** [fluentassertions/fluentassertions#2820]
### Discussed in https://github.com/fluentassertions/fluentassertions/discussions/2801

<div type='discussions-op-text'>

<sup>Originally posted by **hugener** November  2, 2024</sup>
Hi everyone
Not sure if anyone else uses this, but we have a serious use case, where we would like to use FluentAssertions within `Expression<>` trees.
Generally, it shouldn't be a problem, but the use of default values in method calls is not allowed inside Expression trees.

`GetTheTree(items => items.Should().Contain(x => x.FirstName == "Name"));`

Results in a CS0854: An expression tree may not contain a call or invocation that uses optional arguments.
It is due to the optional arguments in `Contain(..., string because = "", params object[] becauseArgs)`

I see two possible solutions that both have severe downsides:
1. Rather than relying on default values, use method overloads. This would require 2 extra method per supported assertion. Yikes, but probably the cleanest way to support Expression trees.
2. As a workaround we call the assertion like so:
`GetTheTree(items => items.Should()**._()**.Contain(x => x.FirstName == "Name"))`

After the `Should()`, we are using the `**_()**` to wrap the various `Assertion` types in our own class, where we can then place new versions of the different methods that do not use default values.

That's also not a nice solution and we would have to define all the overloads to use everything.

Does anyone know a better way around this?

</div>

**Comment by dennisdoomen** [comment]
This should remain a discusison, so closing the issue.
