### ISSUE TITLE
"Edit this page" link in docs leads to wrong branch and is thus not usable

### ISSUE THREAD

**Issue by rklec** [fluentassertions/fluentassertions#2846]
### Description

Apparently the branches were changed or renamed recently and the doc links ar e not updated yet to reflect this? "Edit this page" links linking to GitHub all point to the wrong branch.

### Reproduction Steps

1. Go to any docs page like https://fluentassertions.com/about/
2. Click on the grey "[Edit this page](https://github.com/fluentassertions/fluentassertions/edit/master/docs/_pages/about.md)" link. (or here)
3. It goes to https://github.com/fluentassertions/fluentassertions/edit/master/docs/_pages/about.md

### Expected behavior

It should maybe link to the `develop` branch aka https://github.com/fluentassertions/fluentassertions/edit/develop/docs/_pages/about.md?

### Actual behavior

This results in a 404 page on GitHub:
![grafik](https://github.com/user-attachments/assets/11c64abc-f493-410d-844a-2bedcc23fa0a)

Notably the "Go to default branch" button also does not help, as it throws away the file path, apparently, and lands on https://github.com/fluentassertions/fluentassertions?files=1 (also hardly useful)

### Regression?

Well worked before yeah

### Known Workarounds

Manually change URL, do _not_ click the GitHub button.

### Are you willing to help with a pull-request?

Yes, please assign this issue to me.

**Comment by rklec** [comment]
Hmm I see a commit that possibly could change it? https://github.com/fluentassertions/fluentassertions/commit/812d6f5ff102b575ef35fd8a1d87661021908f6f#diff-23490046866b96a63303a35dfa6634d7cc052a3da36803075e165349c05eace4 It uses `main` instead of `develop` but even that change does not seem to be deployed yet as you can see in my report above?

**Comment by ITaluone** [comment]
The commit which changed `master` to `main` isn't on `main` itself. And because the fluentassertions webpage is generated from `master/main` we have this situation.

**Comment by dennisdoomen** [comment]
Exactly. Fixing it now.

**Comment by dennisdoomen** [comment]
Is fixed
