### ISSUE TITLE
Breaking API changes from 7.0.0-alpha5 to 7.0.0

### ISSUE THREAD

**Issue by MeikelLP** [fluentassertions/fluentassertions#2864]
### Description

Dependabot raised FluentAssertions from `7.0.0-alpha5` to `7.0.0` (released yesterday): https://github.com/MeikelLP/quantum-core-x/pull/249

Sadly many tests are failing now because the API changed back (?) to the 6.x state

Please tell me if this is a dependency issue rather than FluentAssertion itself. I can reproduce this locally

The online documentation does not mention this option either: https://fluentassertions.com/strings/
However the docs source code (develop) does list this option: https://github.com/fluentassertions/fluentassertions/blob/30c29b2b4f5e93965bb9437729858cb7d65a5d29/docs/_pages/strings.md?plain=1#L103

### Reproduction Steps

```csharp
var input = "My\nString";
var expected = "My\r\nString;

// Assert
input.Should().Be(expected, o => o.IgnoringNewlineStyle());
```

### Expected behavior

API from 7.0.0-alpha5 exists?

### Actual behavior

Project cannot be build due to missing APIs

### Regression?

Maybe?

### Known Workarounds

-

### Are you willing to help with a pull-request?

Yes, please assign this issue to me.

**Comment by ITaluone** [comment]
See https://github.com/fluentassertions/fluentassertions/discussions/2862

**Comment by dennisdoomen** [comment]
See https://x.com/ddoomen/status/1863311674645856324

We had to make a hard choice.

**Comment by IT-VBFK** [comment]
Out of curiosity: What was the reason to release v7 now?
