### ISSUE TITLE
Not-null not inferred from Should() in v7

### ISSUE THREAD

**Issue by bart-vmware** [fluentassertions/fluentassertions#2867]
### Description

The change to annotate the first parameter on `Should` methods as non-nullable didn't make it in v7, despite its PR #2380 got merged in January 2024 and [this comment](https://github.com/fluentassertions/fluentassertions/pull/2380#issuecomment-2000261215) indicates it would ship in v7.

https://github.com/fluentassertions/fluentassertions/blob/7.0.0/Src/FluentAssertions/AssertionExtensions.cs#L282
https://github.com/fluentassertions/fluentassertions/blob/develop/Src/FluentAssertions/AssertionExtensions.cs#L285

Upon further investigation, it looks like nearly all changes moved to v8. Why was v7 released when it contains barely any changes? Would you consider backporting #2380 to v7?

### Reproduction Steps

1. Create a new .NET 8 console app
2. Add NuGet reference to FA v7
3. Paste the code below in `Program.cs`
    ```c#
    using FluentAssertions;

    string? result = GetValue();

    result.Should().NotBeNull();
    result.Length.Should().Be(1);

    static string? GetValue()
    {
        return null;
    }
    ```
4. Observe warning:
    ```
    CS8602: Dereference of a possibly null reference.
    ```
    ![image](https://github.com/user-attachments/assets/c7b6f894-16db-4672-a5ee-983db8d09913)
5. Additionally, Resharper does _not_ show the Should() method decorated with `[NotNull]`
    ![image](https://github.com/user-attachments/assets/1cb05fa7-f71b-41dc-a3ea-99ea3b5602fa)

### Expected behavior

Calling `Should()` to infer its argument is non-null when the method returns.

### Actual behavior

It is the same as earlier FA versions, which require the codebase to be sprinkled with `!` suppressions.

### Known Workarounds

none

### Are you willing to help with a pull-request?

No

**Comment by dennisdoomen** [comment]
See https://x.com/ddoomen/status/1863311674645856324

**Comment by bart-vmware** [comment]
Thanks, looking forward to v8!
