### ISSUE TITLE
Collection Assertion NotBeInAscendingOrder with lambda not available but documentation says it is

### ISSUE THREAD

**Issue by jesuissur** [fluentassertions/fluentassertions#296]
Hi

The documentation says there is an overload for NotBeInAscendingOrder with a lambda but I can't find this one into the 3.4.1 version.  The latest 4.0.0 version does not seem to have this overload neither.

I'm looking for
`collection.Should().NotBeInAscendingOrder(x => x.SomeProperty);`

but only found 
`collection.Should().NotBeAscendingInOrder()`

Thanks
Phil

**Comment by dennisdoomen** [comment]
You're right. It's not there. In fact, the methods that *are* there are misspelled. Seems I've been sloppy while accepting that pull request.
