### ISSUE TITLE
Support WithArgs assertion for .NET 4.5 EventHandlers

### ISSUE THREAD

**Issue by timbussmann** [fluentassertions/fluentassertions#30]
The restriction of EventHandler<TEventArgs> for TEventArgs to be of type EventArgs has fallen away with .NET 4.5 (see http://msdn.microsoft.com/en-us/library/db0etb8x(v=vs.110).aspx).

The WithArgs<TEventArgs>(..) assertion still requires TEventArgs to be of type EventArgs. This prevents us from making argument assertions for EventHandlers with TEventArgs other than EventArgs (e.g. EventHandler<string>).

**Comment by Tdue21** [comment]
This would make my life much simpler as well :)

**Comment by okobylianskyi** [comment]
I'm almost ready to provide PR for this issue, but I need to know the decision on @vossad01 question about repeated type parameters. My implementation currently sticks with second option. Should I rework it or it is enough just to assert that value was present among arguments of the same type?

**Comment by dennisdoomen** [comment]
You still want to wrap this up?

**Comment by dennisdoomen** [comment]
Nobody has been asking for this in three years, so we're going to close it.
