### ISSUE TITLE
Localize texts to other languages

### ISSUE THREAD

**Issue by ricardovsilva** [fluentassertions/fluentassertions#316]
I'm thinking about fork your repo and change texts from Assertions FailWith that today are hardcoded to resources files.
My idea about that is allow community translate these messages to any language without need to change the code. What do you think?

The steps will be:
- Fork repository
- Get all hardcoded text and put into en-us.resources file
- Create an static variable that will hold the language (default will be en-us)

So, for example, if I translate it to Brazilian Portuguese, users will only need to do something like:

``` csharp
[TestInitialize]
public void TestInitialize()
{
     FluentAssertions.Language = "pt-br";
}
```

So, when some assert fail. Instead of show:
**_Expected value to be {0} because {1} but found {2}_**

I'll get from resources, and text will be (in pt-br):
**_Esperado o valor {0} porque {1}, porém foi encontrado {2}_**

Use resources file is what I have in mind, any other ideas will be appreciated!

**Comment by dennisdoomen** [comment]
Wow. Never realized people coded in anything but English. I would accept a PR.

**Comment by ricardovsilva** [comment]
Hahaha, me neither. But it's a reality in a lot of companies here in Brazil. 
Also, (believe) there's a lot of developers that doesn't write tests and doesn't have a good English. 
So, if FluentAssertions show messages in Brazilian Portuguese, will be easier to convince more developers to give a try

**Comment by ricardovsilva** [comment]
I forked FluentAssertions but I'm having troubles to build. 
Is really necessary install Windows phone sdk or is there any way to bypass this?

**Comment by dennisdoomen** [comment]
Nope. You need everything :-(

**Comment by ricardovsilva** [comment]
Ok, I'll download and install everything at this weekend and start this PR.

**Comment by dennisdoomen** [comment]
:+1:

**Comment by Evangelink** [comment]
@dennisdoomen Do you have any preference regarding the naming of the resource keys?

**Comment by dennisdoomen** [comment]
Hi @Evangelink. No, not really. But maybe you can propose something that me and @jnyrup can look at?

**Comment by Evangelink** [comment]
@dennisdoomen Maybe you could close this issue as won't fix (at least for now)?

**Comment by splite** [comment]
Ok, the reason is, programmer may be fluent in engrish, but the QA guy / project manager looking at the test results log in a build server doesnt have to.

TBH i dont see the problem - just take your localizable string to satellite assembly and... Thats it, isnt it? You dont need list of supported language, everyone can create own translation, and the poor guy who spricht deutsch, parle français a trochu česky is happy :)

(see https://docs.microsoft.com/en-us/dotnet/framework/resources/creating-satellite-assemblies-for-desktop-apps )

**Comment by dennisdoomen** [comment]
We understand. But making everything localizable comes with a cost. You suddenly need to carefully track every piece of text and make them part of a contract between the core project and the satellite assemblies.

**Comment by dennisdoomen** [comment]
See also this https://github.com/fluentassertions/fluentassertions/pull/1089#issuecomment-510496201

**Comment by splite** [comment]
> See also this [#1089 (comment)](https://github.com/fluentassertions/fluentassertions/pull/1089#issuecomment-510496201)

Localized exceptions are bad, the exceptions are for programmers (if your app is interacting with user via exceptions*, you are doing something very wrong) and you didnt have to use unlocalize.com to know what to ask google.

But unit tests results (and FluentAssertions) is not only for us, programmers. Yes, they are not for users. They are for my QA guy who is reading unit tests log every morning with his coffee. (Well, he is reading only the red ones, but you know what i mean :) )

What i am trying to say, there IS value in localizable assertions / unit tests.

*: yes, i know Assert.xxx is throwing exception internally... :) But you are comunicating not with these exceptions, but with results.
