### ISSUE TITLE
assert equality without conversion of simple types

### ISSUE THREAD

**Issue by bitbonk** [fluentassertions/fluentassertions#317]
Currently Fluent Assertions doesn't seem to have a simple way to assert equivalency/equality that respects the actual runtime types and doesn't do any automatic conversions and that works for both collections and simple types.

The closet API for this would be `ShouldBeEquivalentTo` in combination with the `RespectingRuntimeTypes` option, but this will do automatic conversion of simple types and hence does not fail where it should.

I think Fluent Assertions should provide such a unified method just like xUnit.net does and this method should not be called "equivalent" but "equal" because it is much more an actual equality check than it is an equivalency check.

```
using System;
using System.Linq;
using FluentAssertions;
using Xunit;

public class ParserTests
{
    [Theory,
    InlineData(DataType.String, "foo", "foo"), // should pass
    InlineData(DataType.Integer, "42", 42),  // should pass
    InlineData(DataType.ByteArray, "1,2,3", new byte[] { 1, 2, 3 }),  // should pass
    InlineData(DataType.ByteArray, "1,2,3", new byte[] { 3, 2, 1 }),  // should fail
    InlineData(DataType.ByteArray, "1,2,3", new double[] { 1.0, 2.0, 3.0 }),  // should fail, but doesn't
    InlineData(DataType.Integer, "42", 42.0d)]  // should fail, but doesn't
    public void ShouldAllEqual(DataType datatype, string dataToParse, object expectedResult)
    {
        var result = Parser.Parse(datatype, dataToParse);

        result.ShouldBeEquivalentTo(expectedResult, o => o.RespectingRuntimeTypes());

        // this one works correctly but it is a pity that I need an if
        //if (result is IEnumerable && !(result is string))
        //{
        //    ((IEnumerable)result).Should().Equal(expectedResult as IEnumerable);
        //}
        //else
        //{
        //    result.Should().Be(expectedResult);
        //}

        // xUnit's Assert works correctly too
        //Assert.Equal(result, expectedResult);
    }
}


// Simplified SUT:

public enum DataType
{
    String,
    Integer,
    ByteArray
}

public static class Parser
{
    public static object Parse(DataType datatype, string dataToParse)
    {
        switch (datatype)
        {
            case DataType.Integer:
                return int.Parse(dataToParse);

            case DataType.ByteArray:
                return
                    dataToParse.Split(new[] { ',' }, StringSplitOptions.RemoveEmptyEntries)
                        .Select(byte.Parse)
                        .ToArray();

            default:
                return dataToParse;
        }
    }
}
```

**Comment by dennisdoomen** [comment]
So if I understand you correctly, if you could disable automatic conversion, `ShouldBeEquivalentTo` would do exactly what you want, right?

**Comment by bitbonk** [comment]
Yes, I think this is correct, at the end all test cases aove should fail and pass as described in the comment for each `InlineData`. It is just the naming of the API I am not sure about. `Should().Equal()` is probably a better match than `ShouldBeEquivalentTo()`

**Comment by dennisdoomen** [comment]
> Another thing I’ve changed is to disable auto-conversion of member values. This has been requested for many times, mostly because it confused so many people. For example, the conversion logic would allow you to treat a DateTime property and its string-representation as equivalent. This is no longer happening, but if you really want to, you can still opt-in this option using the WithAutoConversion and WithAutoConversionFor methods.

Since 5.0, we no longer enable auto-conversion automatically. Does this solve this issue?

**Comment by bitbonk** [comment]
Yes, that solved the issue perfectly.
