### ISSUE TITLE
Linq2Sql entity - default value formatter runs into SQL queries

### ISSUE THREAD

**Issue by drauch** [fluentassertions/fluentassertions#327]
For beginners it might not be obvious why a simple `myEntityCollection.Should().NotContain(entity)` executes SQL queries and (for bigger tables) takes forever due to the N+1 query problem.

The problem is that the `DefaultValueFormatter` tries to build an output string over many nesting levels of public properties in case `ToString()` is not overloaded (the default case for generated entites in Linq2Sql and afaik also for EntityFramework).

It would probably be best to always use `ToString()` and to enforce that the user explicitly must enable the `DefaultValueFormatter`'s Public-Property-Via-Reflection-ToString behavior.

What are your thoughts on this issue?

BR, D.R.

**Comment by drauch** [comment]
Also the current `HasDefaultToStringImplementation` doesn't look like it is a good idea -> ToString() is always called twice...

**Comment by dennisdoomen** [comment]
It's also a kind of double-edged sword. FA's ability to generate a nice dump of the objects involved in an assertion is one of its strongest features. 

But are you sure it's the formatter that is causing the queries? I would expect that the task of comparing the two objects would already do that.

**Comment by drauch** [comment]
No, `NotContain` uses by-reference comparison to determine whether an object is in a collection or not. It's the formatter which causes the N+1 query problem. Maybe `IQuerable<>` should have its own formatter which does not query the database?

**Comment by dennisdoomen** [comment]
So what should the formatter display for an `IQueryable<>`?

**Comment by drauch** [comment]
If possible the SQL statement, or just the information that it is an IQueryable<>? Everything's better than a database query (it should certainly not query the database at all in order to create a formatted output string).
