### ISSUE TITLE
Allow caller to control how keys and values of dictionaries are compared in ShouldAllBeEquivalentTo()

### ISSUE THREAD

**Issue by shift-evgeny** [fluentassertions/fluentassertions#341]
When comparing collections I can pass in my own comparer predicate (Func<T, TExpected, bool>):

`actualCollection.Should().Equal(expectedCollection, MyComparisonFunc)`

Please add the ability to do the same thing when comparing a dictionary, i.e.

`actualDictionary.ShouldAllBeEquivalentTo(expectedDictionary, MyKeyComparisonFunc, MyValueComparisonFunc)`

Passing in null should use the default comparer, so that if I want to override only the value comparison I can call

`actualDictionary.ShouldAllBeEquivalentTo(expectedDictionary, null, MyValueComparisonFunc)`

It would be even better if instead of bool the predicate could return a string with a message to be displayed to the user (explaining what's different about the objects), because this is often not obvious for large and complex object hierarchies. A null return value would mean the objects are equal.

**Comment by dennisdoomen** [comment]
Instead of extending the structural comparison API, wouldn't it be better to extend the dictionary assertions instead?

**Comment by shift-evgeny** [comment]
Oops! Yes, you're right. ```actualDictionary.Should().Equal()``` is the one that should be extended.

I think the reason I ended up using ShouldAllBeEquivalentTo() for dictionaries is that it gives a more useful error message when a key differs. The dictionary assertion just prints both dictionaries and I have to look for the difference myself. So it would be nice to fix this, too. Something like ```Actual dictionary did not contain 2 expected keys [1111, 2222], but contained 2 extra keys [1112, 2221]```

**Comment by dennisdoomen** [comment]
There's more then enough extension point to alter the behavior of you want to compare dictionaries, and there have been no similar requests.
