### ISSUE TITLE
Allow MonitorEvents to be reset

### ISSUE THREAD

**Issue by stuartbrownstanbury** [fluentassertions/fluentassertions#348]
If you need to check that multiple actions will trigger an event you need to create lots of small tests or recreate the unit under test and call .MonitorEvents() on it repeatedly. This request is for a way to clear out old events so that, for example, .ShouldRaisePropertyChangeFor() can be called over and over with the new "clear function" called in between.

**Comment by dennisdoomen** [comment]
In other words, a `Clear` method on the `EventRecorder` returned from `MonitorEvents`?

**Comment by stuartbrownstanbury** [comment]
Maybe a static method like monitor events. So you can do something like this:

`
[Test]
public void Test_Step()
{
    Step UUT = new Step();

    UUT.MonitorEvents();

    TerminationCondition TC1 = new TerminationCondition();
    TerminationCondition TC2 = new TerminationCondition();
    
    UUT.TerminationConditions.Add(TC1);
    UUT.ShouldRaisePropertyChangeFor(S => S.TerminationConditions);

    UUT.ClearEvents();
    UUT.TerminationConditions.Add(TC2);
    UUT.ShouldNotRaisePropertyChangeFor(S => S.TerminationConditions);
}
`

The new "ClearEvents" allows you to test that the event is raised for each insertion. Without it you can only say that the event was raised once. I need to check that it is raised twice (or more).

**Comment by somewhatabstract** [comment]
The concept in Jasmine, where the history of calls on spies is cleared uses the nomenclature `reset:

http://jasmine.github.io/2.4/introduction.html#section-38

However, I think `ResetEvents()` and `ClearEvents()` don't really describe what's actually being done. In jasmine, it's clear what's being reset because it is a method off of `calls`. To that end, I think either an extension like `ResetMonitoredEvents()` or a `Reset()` call off the `EventRecorder` makes sense.

**Comment by dennisdoomen** [comment]
That's pretty neat. I was thinking in the same direction. It will also work much better in parallel XUnit tests.

**Comment by somewhatabstract** [comment]
OK, so I'll see about adding both the `Dispose` pattern approach and the `Reset` call. I think that covers the use cases that people need.

**Comment by dennisdoomen** [comment]
This could also solve #477

**Comment by bitbonk** [comment]
@dennisdoomen How could that solve #477? Is it because now that you explicitly dispose you do not need to use WeakReferences anymore ?

**Comment by dennisdoomen** [comment]
Well, we should not use thread-static at all. Using an explicit `using` block would make it much more reliable.

**Comment by bitbonk** [comment]
It is just that I haven't understood how "Adding ability to reset event monitoring" could resolve the thread-static issue (I am just curious) from #477.

**Comment by dennisdoomen** [comment]
The title is a bit misleading, but the point of this issue is to change the implementation to solve all of the above problems.

**Comment by dennisdoomen** [comment]
Resolved by #625
