### ISSUE TITLE
SelectedMemberPath set inconsistently when filtering properties in ShouldAllBeEquivalentTo

### ISSUE THREAD

**Issue by jakubka** [fluentassertions/fluentassertions#351]
Hi,

I am experiencing strange behavior when it comes to excluding properties from comparison using predicate in Excluding method.

```c#
MyObject actual = new MyObject
{
	MyString = "identical string",
	Child = new MyChildObject
	{
		MyChildString = "identical string"
	}
};

MyObject expectation = new MyObject
{
	MyString = "different string",
	Child = new MyChildObject
	{
		MyChildString = "DIFFERENT STRING"
	}
};

IList<MyObject> actualList = new List<MyObject> {actual};
IList<MyObject> expectationList = new List<MyObject> {expectation};

actualList.ShouldAllBeEquivalentTo(expectationList,
	opt =>
		// INTERESTING STUFF HAPPENS HERE:
		opt
			.Excluding((ISubjectInfo s) => s.SelectedMemberPath == "Child.MyChildString") // no [0]
			.Excluding((ISubjectInfo s) => s.SelectedMemberPath == "[0].MyString") // suddenly, I need to specify index [0]
	);
```

Notice how `SelectedMemberPath` starts with index [0] when topmost property is compared, but with nested properties, the index doesn't need to be specified. I find this behavior confusing. Is it by design?

Thanks!

**Comment by VisionSuiteClients** [comment]
Thanks for reporting this. What version of FA are you using? Is this something that has changed for you?

**Comment by jakubka** [comment]
I am on FA 3.5.0 and I've also verified it on latest master.

I haven't used this feature before, so I have no idea whether it has changed or not.

**Comment by dennisdoomen** [comment]
Now that I think of it, it's by design. The `SelectedMemberPath` represents the dotted path from the root to the current property. So since your comparing two collections, it's *kind* of normal that you need to include this in the path. However, I do believe that it is kind of confusing.

**Comment by jakubka** [comment]
Yeah, but why is it needed to include index when comparing topmost property (`MyString` in the example above), but when comparing nested property (`Child.MyChildString`), the index is not part of the path. The inconsistency is what bothers me. :)

```
.Excluding((ISubjectInfo s) => s.SelectedMemberPath == "Child.MyChildString") // no [0]
.Excluding((ISubjectInfo s) => s.SelectedMemberPath == "[0].MyString") // suddenly, I need to specify index [0]

```

**Comment by dennisdoomen** [comment]
I agree with that. I understand why it is needed because I know how the internals work. Will fix it.

**Comment by jakubka** [comment]
:+1: Thank you

**Comment by dennisdoomen** [comment]
I think this is solved, so if it's not, please reopen.
