### ISSUE TITLE
Confusing result when comparing lists of different numeric types

### ISSUE THREAD

**Issue by baaronson** [fluentassertions/fluentassertions#355]
These results seem inconsistent:

```
1L.Should().Be(1);  // Passes
new[] {1L}.Should().ContainInOrder(1); // Fails
```

More confusingly, the output for the second line reads:

> Expected collection {1} to contain items {1} in order, but 1 (index 0) did not appear (in the right order).

Which is hard to understand. I'm not completely sure what the behaviour here should be, but it would be helpful if there was a different message for mismatching types versus unequal instances of the same type

**Comment by dennisdoomen** [comment]
Ah, so the failure is correct since FA would not try to convert numeric types for you. If you want that, use `ShouldBeAllEquivalenTo` instead. However, you can't see that from the message.

**Comment by dennisdoomen** [comment]
I've just checked this with 6.0 beta 2, and the second row succeeds now. And if I change the `1` into a `2`, like...
```
new[] { 1L }.Should().ContainInOrder(2);
```

...the response is

`Expected collection {1L} to contain items {2L} in order, but 2L (index 0) did not appear (in the right order).`
