### ISSUE TITLE
FluentAssertions doesn't work nicely with ASP.NET 5 projects

### ISSUE THREAD

**Issue by shederman** [fluentassertions/fluentassertions#358]
ASP.NET 5 doesn't build the DLL with dependencies anymore, so anything funny happens in FluentAssertions (like a ShouldThrow<> with the matching exception being thrown), and it fails hard with "FluentAssertions was configured to use xunit but the required test framework assembly could not be found".

**Comment by kevinkuszyk** [comment]
@shederman what versions of FA and AspNet Core are you using?

**Comment by sunsided** [comment]
@shederman FYI, I'm currently successfully using `xunit.runner.dnx` and `xunit.runner.aspnet` on both `1.0.0-rc2-16357` and `1.0.0-rc2-16549` (respectively) on `dnx451` and `dnx46` targets.

**Comment by shederman** [comment]
rc1-final.

**Comment by onovotny** [comment]
I don't think this is an issue with dotnet CLI. The output of test projects has all of the related dll's in it.

**Comment by dennisdoomen** [comment]
Is it possible that the XUnit assertion library isn't loaded yet at that point, as reported in #373 ?

**Comment by shederman** [comment]
No, I tried calling an Assert method before Should(), but it still gave the exception, so that's not it

**Comment by dennisdoomen** [comment]
If you put a breakpoint on the FA invocation and you inspect the modules loaded at that point, is the `xunit.assert` assembly loaded?

**Comment by shederman** [comment]
Yep

**Comment by dennisdoomen** [comment]
That's weird. Any change that you can debug this a bit? I can't reproduce it myself.

**Comment by dennisdoomen** [comment]
Does this problem still happen with 4.4.0? I've [changed](https://github.com/dennisdoomen/FluentAssertions/issues/373) the way the XUnit assembly is loaded.

**Comment by dennisdoomen** [comment]
Assume the problem is gone.
