### ISSUE TITLE
IEnumerable.Contains(IEnumerable) doesn't use type's Equals method

### ISSUE THREAD

**Issue by carlin-q-scott** [fluentassertions/fluentassertions#363]
I implemented `IEquatable<MyType>` on `MyType` and see that it's used by `IEnumerable<MyType>.Should().Contain(MyType)`. When I use `IEnumerable<MyType>.Should().Contain(IEnumerable<MyType>)` it doesn't use the  `IEquatable<MyType>` interface on `MyType`.

I overrode the base `Equals` method on `MyType` but it also not being called.

**Comment by dennisdoomen** [comment]
Can you tell me which class that `Contain` in your 2nd example is implemented? Maybe the overload resolution is confused. Notice that Fluent Assertion doesn't have any special `IEquatable<>` support.

**Comment by carlin-q-scott** [comment]
I can. The function signature is `FluentAssertions.Collections.CollectionAssertions<TSubject,TAssertions>.Contain(IEnumerable expected, string because, params Object[] reasonArgs)`.

Also, I am using a rather old version of FluentAssertions (v3.5) because the newer versions don't work with VS2013.

**Comment by dennisdoomen** [comment]
If you look at the [implementation](https://github.com/dennisdoomen/FluentAssertions/blob/master/Src/Core/Collections/CollectionAssertions.cs#L549) of that method, you see it is used the built-in `Except` method to find the missing items. .NET itself uses `Equals` to compare the objects. 

By the way, I use the latest version of FA on Visual Studio 2013 myself. What .NET Framework do you use?

**Comment by carlin-q-scott** [comment]
Except requires this: "To compare custom data types, implement the IEquatable<T> generic interface and provide your own GetHashCode and Equals methods for the type. The default equality comparer, Default, is used to compare values of types that implement IEquatable<T>. "
https://msdn.microsoft.com/library/bb300779(v=vs.100).aspx#Anchor_2

What does the singular contain assertion use instead?

I'm using .NET 4.5.

**Comment by dennisdoomen** [comment]
If you drill a bit deeper into that documentation, it tells you that the 'Default' compare will either use the `IEquatable` implementation or the overrides of `Equals`.

**Comment by carlin-q-scott** [comment]
Yeah, the default comparar will use those methods... and the GetHashCode method, as stated in my quote.

The [Enumerable.Contains method MSDN article](https://msdn.microsoft.com/en-us/library/bb352880%28v=vs.90%29.aspx) has this remark: 

> "If the type of source implements ICollection<T>, the Contains method in that implementation is invoked to obtain the result. Otherwise, this method determines whether source contains the specified element."

I remember one of my coworkers complaining about there being inconsistency in how ICollection's use the GetHashCode method, so maybe I just happened to use one that doesn't use GetHashCode while performing comparisons.

I think my issue issue is with the BCL, not FluentAssertion, but it sure would be nice if I could avoid doing something hacky like making a fake GetHashCode method as suggested in the article you linked to.

**Comment by dennisdoomen** [comment]
No further work needed.
