### ISSUE TITLE
CollectionAssertions.OnlyHaveUniqueItems to have predicate parameter

### ISSUE THREAD

**Issue by gordey4doronin** [fluentassertions/fluentassertions#365]
Hi,

Is it possible to implement additional `CollectionAssertions.OnlyHaveUniqueItems` method with `predicate` parameter?

I mean something similar to `CollectionAssertions.AndConstraint`:

``` cs
public AndConstraint<TAssertions> Equal(IEnumerable<T> expectation, Func<T, T, bool> predicate, string because = "", params object[] reasonArgs)
{
  this.AssertSubjectEquality<T>((IEnumerable) expectation, predicate, because, reasonArgs);
  return new AndConstraint<TAssertions>((TAssertions) this);
}
```

So having a possibility to assert collection uniqueness passing your own comparator-predicate.
What do you think?

**Comment by dennisdoomen** [comment]
Sure. Just send me a PR ;-)

**Comment by GDoronin** [comment]
Sure, I will :)
The question was if it's possible theoretically and if you can aim me?

**Comment by dennisdoomen** [comment]
Why wouldn't it be?

**Comment by GDoronin** [comment]
I don't know..
For some technical reasons or because of some kind of implementation details.
As it often happens in such matters.

If it's fine, nevermind then :)

**Comment by aateeque** [comment]
Or even a selector:
```
Func<T, TItemProp> selector = listOfEmployees => listOfEmployees.Id;
CollectionAssertions.OnlyHaveUniqueItems(selector, $"no two employees should have the same Id");
CollectionAssertions.Select(selector).Should().HaveCount(10, $"we only have 10 employees");
```

**Comment by dennisdoomen** [comment]
In this case, a selector is not enough because you need both values.
