### ISSUE TITLE
Support for collection.ShouldContainEquivalentOf

### ISSUE THREAD

**Issue by infosaurus** [fluentassertions/fluentassertions#367]
As far as I can tell, `Should().Contain()` uses `Equals()` to compare objects. It would be nice to be able to combine `Should().Contain()` and `Should().BeEquivalent()` and leverage structural equality instead.

We already have `ShouldAllBeEquivalentTo()`, this could be called `ShouldSomeBeEquivalentTo()` or `ShouldContainEquivalentOf()`.

Thanks for this awesome library !

**Comment by dennisdoomen** [comment]
Maybe by adding a `Should().ContainEquivalentOf` which internally leverages the structural equivalency API.

**Comment by RTodorov** [comment]
Hi guys,

Is there a workaround to achieve the same result with the current version?

Thank you!

**Comment by dennisdoomen** [comment]
You can build your own extension that passes each object in the collection to a call to ShouldBeEquivalenTo to compare each object with the one you like to find. At least one of those objects in the collection must match.

**Comment by danielmpetrov** [comment]
Issue #584 was a duplicate of this, and was closed in #693. Please close this one too.
