### ISSUE TITLE
Support Match() for non-reference types?

### ISSUE THREAD

**Issue by martincostello** [fluentassertions/fluentassertions#372]
I have an existing library I'm updating to use Fluent Assertions instead of the built-in xunit `Assert` class.

I have an xunit assert that looks like this, where the `UserId` property is of type `int?` which needs migrating:

``` csharp
Assert.True(project.Item.UserId == null || project.Item.UserId > 0);
```

There doesn't appear to be a way to do an equivalent with Fluent Assertions. I found the `Match<T>()` method, but this only works for reference types.

I'm currently doing this as a workaround:

``` csharp
if (project.Item.UserId.HasValue)
{
    project.Item.UserId.Should().BeGreaterThan(0);
}
```

but it would be much nicer to do something this:

``` csharp
project.Item.UserId.Should().Match((p) => p == null || p > 0);
```

**Comment by dennisdoomen** [comment]
You can just call `project.Item.UserId.Should().BeGreaterThan(0);` directly. It will throw the appropriate exception is the value is `null`.

**Comment by martincostello** [comment]
I don't want an exception if the value is ```null``` though, the value can be ```null``` _or_ it should be greater than zero.

**Comment by dennisdoomen** [comment]
My bad. Didn't look close enough. As a workaround, you *could* do something like `((object)project.Item.UserId).Should().Match(....`.

**Comment by martincostello** [comment]
I thought about that, but it's a bit ugly as you need two casts to make it work due to the use of the comparison operator meaning you need to cast it back to an ```int?``` in the predicate:

```csharp
((object)project.Item.UserId).Should().Match((p) => p == null || (int?)p > 0);
```

I guess ```Nullable<T>``` falls through the cracks a bit here as it was a reference type ```Match(...)``` would be available to use, and if it was just ```T``` then the other specialized classes would bring other useful methods into scope for use without the need for ```Match(...)``` like ```BeInRange(...)``` for ```int```.

**Comment by dennisdoomen** [comment]
I would have to try to see if I can introduce some kind of base-class like `ReferenceTypeAssertions` for value types.

**Comment by martincostello** [comment]
No problem, it's only one assertion in the particular code I've migrated, so there's no urgent need, but I figured it _might_ be a use case that it would be nice to have built-in support for.

**Comment by EvanSevy** [comment]
Any luck on this?

**Comment by dennisdoomen** [comment]
It's not particularly high on our radar. However, it would only require adding a `Match` method like [this](https://github.com/fluentassertions/fluentassertions/blob/6a8c42a82c358056e23e3d0bb11df986e4ea7487/Src/FluentAssertions/Primitives/ReferenceTypeAssertions.cs#L352) one on `NumericAssertions`. We would welcome a PR ;-)
