### ISSUE TITLE
ShouldAllBeEquivalentTo<T> a single object instead of IEnumerable

### ISSUE THREAD

**Issue by SaroTasciyan** [fluentassertions/fluentassertions#377]
An overload of _ShouldAllBeEquivalentTo_ method asserting all elements of given enumerable are equivalent to given object would be awsome.

``` C#
public static void ShouldAllBeEquivalentTo<T>(this IEnumerable<T> subject, T expectation, Func<EquivalencyAssertionOptions<T>, EquivalencyAssertionOptions<T>> config, string because = "", params object[] reasonArgs)
{
    // ..
}
```

I'm not aware of a better way using Fluent Assertions, this is how I currently implement the assertion using ShouldAllBeEquivalentTo;

``` C#
Model expectedModel = new Model { One = 1, Two = "2", Three = 3, Four = 4M };
IEnumerable<Model> expectedModels = Enumerable.Repeat(expectedModel, 2);

models.ShouldAllBeEquivalentTo(expectedModels);
```

**Comment by dennisdoomen** [comment]
Thanks for the suggestion, but IMO it's a pretty rare situation. Shouldn't be difficult to create your own extension method for that. Unless you submit a PR of course ;-)

**Comment by SaroTasciyan** [comment]
Hey @dennisdoomen. Thanks for reply. I ended up creating my own extension. I agree that it's a rare situation, I just been into one of those rares tho.

Planning to work for a PR in the following days.
