### ISSUE TITLE
Assertions instead of Boolean results in WithArgs(of T)

### ISSUE THREAD

**Issue by JueSte** [fluentassertions/fluentassertions#387]
I love the way string assertions are handled. 
But I have to do my string comparison manualy when i work with EventArgs.

``` c#
target.ShouldRaise("SomeEvent").WithArgs(Of SomeArgs)( x => x.SomeString = "expected");
```

I don't understand why we fallback to boolean results. Couldn't this be handled this way:

``` c#
target.ShouldRaise("SomeEvent").WithArgs(Of SomeArgs)( x => x.SomeString.Should.Be("expected"));
```

**Comment by c0bra** [comment]
:+1:  any answer?

**Comment by dennisdoomen** [comment]
I considered that at some point, but it breaks the fluentness of the API.
