### ISSUE TITLE
BeSameDateAs has not the opposite (NotBeSameDateAs)

### ISSUE THREAD

**Issue by ferpega** [fluentassertions/fluentassertions#397]
Hello,

I was looking for the opposite of `BeSameDateAs` but I have seen it doesn't exist.

I have forked the project to add this functionality for myself and pull request after that, but the project doesn't compile on my side.  Some of the Core or Portable libraries not present, IIRC.

Would be great somebody be able to implement that simple functionality or give me a clue to get the same behavior on some way.

Regards.

**Comment by dennisdoomen** [comment]
You need Visual Studio 2015 and the Windows 10 SDK. Then it'll compile.

**Comment by ferpega** [comment]
I will try it again.  I already have Visual Studio 2015 and Windows 10 SDK (doubt about this last).
Thanks.

**Comment by jnyrup** [comment]
I believe #414 closes this.
