### ISSUE TITLE
ShouldAllBeEquivalentTo fails to throw for object arrays

### ISSUE THREAD

**Issue by mmkal** [fluentassertions/fluentassertions#398]
ShouldAllBeEquivalentTo doesn't throw for object arrays containing multiple types even when they're clearly different. This is quite serious, as a test that should fail will pass, which could  easily hide bugs in product code.
Here's a simple repro:

```
var foo = new object[] { 1, 2, "aaa", 4 };
var bar = new object[] { 1, 2, "bbb", 4 };
foo.ShouldAllBeEquivalentTo(bar); // does not throw!
```

**Comment by dennisdoomen** [comment]
Actually, this behavior is by design. You're comparing two collections of type `object` and FA's default behavior is to include include the declared type's members. If you want to change that, pass the `IncludingAllRuntimeProperties` to the `options` parameter.
