### ISSUE TITLE
ShouldBeEquivalentTo does not fail on members that are in the expected but not in the actual

### ISSUE THREAD

**Issue by corvansteijn** [fluentassertions/fluentassertions#400]
When including all runtime properties, I want my spec to fail on missing members on my subject. I use a dynamic in my test with a property to check if that property exists on the actual. 
Unfortuantely this does not fail.

**Comment by dennisdoomen** [comment]
The approach I'll try to take is to treat the expectation as the truth rather than the source.

**Comment by dennisdoomen** [comment]
* [ ] Drop the difference between compile-time and run-time types
