### ISSUE TITLE
StringCollectionAssertions.Contain case-insensitive overload

### ISSUE THREAD

**Issue by MNF** [fluentassertions/fluentassertions#404]
It would be good to have `StringCollectionAssertions.Contain` case-insensitive overload.

The following example failed

```c#
IEnumerable<string> collection = new[] {"text1", "text2", "text3"};
collection.Should().Contain("Text3");//case mismatch
```

I've used my own extension method
    `collection.ContainsString("Text3").Should().BeTrue();`

```c#
public static bool ContainsString(this IEnumerable<string> collection, string toFind, bool ignoreCase = true, bool trimStrings = false)
{
    if (trimStrings)
    {
        collection = collection.Select(s => s.Trim());
        toFind = toFind.Trim();
    }
    
    return collection.Contains(toFind, StringComparer.Create(CultureInfo.InvariantCulture, ignoreCase));
}
```

I suggest to include similar extension to `StringCollectionAssertions`.

**Comment by dennisdoomen** [comment]
Thanks for suggesting. I do welcome pull requests ;-)

Alternatively, you could use the overload of `Contain` takes a Func<string, bool>

**Comment by jnyrup** [comment]
Two possible workarounds until this (hopefully) is better supported:
```c#
collection.Should().Contain(e => string.Equals(e, "Text3", StringComparison.OrdinalIgnoreCase));

collection.Should().ContainEquivalentOf("Text3", opt => opt
    .Using<string>(ctx => ctx.Subject.Should().BeEquivalentTo(ctx.Expectation))
    .WhenTypeIs<string>());
```

**Comment by Serg046** [comment]
Started to it and realized that it could overcomplicate API without a big need. I guess this should be convenient enough:
```csharp
collection.Should().ContainEquivalentOf("Text3", opt => opt.Using(StringComparer.InvariantCultureIgnoreCase));
```

**Comment by dennisdoomen** [comment]
Indeed, but that also requires the underlying `StringAssertions.Be` needs to support that.

**Comment by IT-VBFK** [comment]
Hello

Is this still a valid request? 
If so maybe we should clarify the needed API changes?

**Comment by dennisdoomen** [comment]
I prefer 1, but then using something like `opt.IgnoringCasing()` _and_ another option `opt.Using(StringComparer.InvariantCultureIgnoreCase)`

**Comment by lg2de** [comment]
In [#1956](https://github.com/fluentassertions/fluentassertions/issues/1956#issuecomment-1190650335) I started discussion about the concept for such API. Maybe we should really start to write a API design manual!?

**Comment by dennisdoomen** [comment]
Duplicate issue as described in #2064
