### ISSUE TITLE
[FluentAssertions.JSON] wrong assert message on Contain

### ISSUE THREAD

**Issue by fforjan** [fluentassertions/fluentassertions#405]
Unit test contains :
simModelViewModel.ItemStatus.Should().Contain("Name", new JValue("TestValue"));

But this is the error message when the name property is not  the expected one
![image](https://cloud.githubusercontent.com/assets/601810/15252493/0197836e-18e3-11e6-9884-fc831306bfb7.png)

the expected value in the message is wrong ?

**Comment by dennisdoomen** [comment]
Thanks for reporting this. What's the type of `simModelViewModel.ItemStatus`?

**Comment by fforjan** [comment]
Should have told you  :(
It's a JObject

**Comment by dennisdoomen** [comment]
That's weird. This doesn't even compile:

            var jobject = JObject.Parse("{\"name\":\"TestValue\"}");
            jobject.Should().Contain("name", new JValue("TestValue"));

Which version of FA are you using?

**Comment by fforjan** [comment]
Please find attach a simple project to reproduce the issue.

VS2015 Update  2 with patches from https://msdn.microsoft.com/en-us/library/mt695655.aspx up to 14.0.25130.0

[demoFluentJson.zip](https://github.com/dennisdoomen/FluentAssertions/files/266361/demoFluentJson.zip)

**Comment by dennisdoomen** [comment]
Ah, now I understand it. You're not referencing the `FluentAssertions.Json` namespace, which means that only the normal non-JSon assertions are in scope. And since `JObject` implements `IDictionary<K, V>`, that's what you're calling. Although I don't understand why it is giving a weird error.

**Comment by fforjan** [comment]
Ah yes...
because in my case, I already have other unit tests using fluent assertions.
I've started to do fluent assertions around JSON object just recently.

Are we saying we should not mix both json/non json in the same C# file ?
What's the recommended approach ?

**Comment by mkoertgen** [comment]
I think this can be resolved by disambiguating the extension methods for `JTokenAssertions` and `ObjectAssertions`, see #406
