### ISSUE TITLE
[FluentAssertions.JSON] Contain do not work well with JObject ?

### ISSUE THREAD

**Issue by fforjan** [fluentassertions/fluentassertions#406]
I've tried to do :
simModelViewModel.ItemStatus.Should().Contain("Graphics", JToken.Parse("{'X' : 100.0, 'Y':100.0, 'Height':100.0, 'Width':100.0, 'RotateAngle':100.0}"));

But in the end I had to do something like:
FluentAssertions.Json.JsonAssertionExtensions.Should(simModelViewModel.ItemStatus.Should().ContainKey("Graphics").WhichValue).BeEquivalentTo(JToken.Parse("{'X' : 100.0, 'Y':100.0, 'Height':100.0, 'Width':100.0, 'RotateAngle':100.0}"));

Also notice the conflicting issue between the BeEquivalentTo between the 2 namespaces...
(ItemStatus is a JObject)

**Comment by mkoertgen** [comment]
After using the JTokenAssertions myself for a while now, i also noticed that the current extension methods may often clash with JObject & JValue.

The current workaround is to help the compiler by explicitly casting to `JToken` like this

    ((JToken)simModelViewModel.ItemStatus).Should(...)

But this is not so nice either. A better solution would be to just add some explicit extension methods for `JObject` etc.

I'm on it.

**Comment by mkoertgen** [comment]
Hi @fforjan, this should be fixed with PR #434 and [FluentAssertions.Json/4.11.0](https://www.nuget.org/packages/FluentAssertions.Json/4.11.0). Please have a look. 

This resolved my issues. If this works for you too, we can close this issue and #405
