### ISSUE TITLE
Any way to adjust verbosity/tree depth of a failing assertion on a collection?

### ISSUE THREAD

**Issue by chrisstaley** [fluentassertions/fluentassertions#420]
Most of the time, when I have a failing assertion on a collection of objects, I'm only interested in the values of properties that are of primitive types, and not the values of properties that are objects (that also have properties that are objects, and on and on and on).  For example, I do a lot of testing with Entity Framework where the object graph can essentially be infinitely deep, since related objects have properties that point to each other.  The failure messages for those  tests often end up being hundreds of lines long for a collection with even a single object in it.

My question: Is there any way to configure the tree level depth that FluentAssertions will render in the failure message, or is there any plan/desire for such a feature?

**Comment by dennisdoomen** [comment]
No, nothing planned for that, but I'm open to pull requests. As a workaround, you could alter the formatters collection as described in the [extensibility section](https://github.com/dennisdoomen/FluentAssertions/wiki#extensibility-1) of the wiki
