### ISSUE TITLE
ExceptionAssertions.Where does not apply to InnerException

### ISSUE THREAD

**Issue by lukas-ais** [fluentassertions/fluentassertions#433]
Given is the following test code:

``` csharp
  [Fact]
  public void Test()
  {
    var innerException = new InvalidOperationException("InnerMessage");
    var exception = new ArgumentException("OuterMessage", innerException);
    exception.Invoking(e => { throw e; })
      .ShouldThrowExactly<ArgumentException>()
      .Where(e => e.Message == exception.Message)
      .WithInnerExceptionExactly<InvalidOperationException>()
      .Where(i => i.Message == innerException.Message);
  }
```

The test will fail because the last line does not match.

I assume, that this is not the intended use for the Where method.
But this looks fine for a fluent API.

How to check more details on inner exception than inner message (which is available using WithInnerMessage)? I would like to check other properties of a custom exception.

**Comment by dennisdoomen** [comment]
What does the `Where` return? The `InvalidOperationException` or the `ArgumentException`?

**Comment by lukas-ais** [comment]
Sorry for the strong delay.
I missed the response notification and then it when out of scope... :|

The problem is, that the `Where` method applies again to the `ArgumentException` instead of the `InvalidOperationException` which is expected according the fluent API.
Is there any other method available to check the details of the **inner exception**?

Here is the output of the test execution:

> FluentAssertions.Execution.AssertionFailedException : Expected exception where (i.Message == value([...schnipp...]Tests+<>c__DisplayClass1_0).innerException.Message), but the condition was not met by:
> 
> {System.ArgumentException with message "OuterMessage"
>      bei [...schnipp...]Tests.<>c.<Test>b__1_0(ArgumentException e) in [...schnipp...]Tests.cs:Zeile 37.
>      bei FluentAssertions.AssertionExtensions.<>c__DisplayClass10_0`1.<Invoking>b__0() in C:\projects\fluentassertions-vf06b\Src\Shared\AssertionExtensions.cs:Zeile 38.
>      bei FluentAssertions.Specialized.ActionAssertions.InvokeSubjectWithInterception() in C:\projects\fluentassertions-vf06b\Src\Core\Specialized\ActionAssertions.cs:Zeile 112.
> }

**Comment by dennisdoomen** [comment]
> This breaks the logic of When_asserting_with_an_aggregate_exception_type_the_asserts_should_occur_against_the_aggregate_exception
> 
> new AggregateException("Outer Message", new Exception("Inner Message"))
> 
>  act.Should().Throw<AggregateException>()
>                .WithMessage("Outer Message*")
>                 .WithInnerException<Exception>()
>                 .WithInnerMessage("Inner Message");
> With this change, the test above fails when switching from WithInnerException to WithInnerExceptionExactly, as WithInnerMessage now asserts on the Exception instead of AggregateException.

Maybe I can have `WithInnerException ` and `WithInnerExceptionExactly` return an object that allows the `Where` to apply its predicate on that `TInnerException`, but have it return an `ExceptionAssertions` on the original one? Will try to see if I can make that work.

**Comment by dennisdoomen** [comment]
@jnyrup 

Hmm, come to think of it, the current API is actually broken. It doesn't allow you to make a distinction between asserting that the parent exception has _two_ inner exceptions in contrast to an inner exception _within_ an inner exception. I suspect the latter is a more common scenario.  

If you agree, I think I'll have to introduce another breaking change by removing `WithInnerMessage`.

**Comment by jnyrup** [comment]
While it is a convenient API that most of the times saves you some key strokes, I find it ambiguous.

The following will not compile, as `Which` returns the outer exception.
```c#
Action act2 = () => throw new Exception("outer", new ArgumentNullException("paramName"));

act2.Should().Throw<Exception>()
    .WithInnerException<ArgumentNullException>()
        .Which.ParamName.Should().Be("paramName");
```

If you have an `AggregateException` `WithInnerMessage` only looks on the `InnerException` and not `InnerExceptions`.

```c#
var act = throw new AggregateException(
    new InvalidOperationException("You can't do this"),
    new NullReferenceException("Found a null")
 );

act.Should().Throw<AggregateException>()
                .WithInnerMessage("*You can't do this*")
                .WithInnerMessage("*Found a null*"); // fails
```

I searched for `return this;` in the code and `ExceptionAssertions` is the only Assertions class that returns `this`. 
Every else I guess this is solved by returning `AndWhich`?

**Comment by dennisdoomen** [comment]
Now it should be fixed.
