### ISSUE TITLE
Very unexpected omission: uint?.Should().Be(<value>) fails

### ISSUE THREAD

**Issue by diaconesq** [fluentassertions/fluentassertions#435]
```
            uint? u = 5;
            u.Should().Be(5);
```

Result: Expected object to be 5, but found 5.

It works fine for uint (not nullable) and int (both nullable and not nullable)

Used version: 3.2.2.0

**Comment by dennisdoomen** [comment]
Thanks for reporting this. Unfortunately, version 3.x is no longer supported. Is there a chance you can reproduce it with the current versions?

**Comment by diaconesq** [comment]
Just tried with 4.10. Same result.

**Comment by dennisdoomen** [comment]
Thanks for trying that. It's most definitely a bug.

**Comment by dennisdoomen** [comment]
After a bit of an investigation, I realized that FA doesn't properly support unsigned numeric types yet. It's going to be more than a simple fix to support that.

**Comment by jnyrup** [comment]
@dennisdoomen Do you recall why it wasn't a simple fix?
I tried adding overloads of `Should<T>()` for unsigned types and that seemed to work.

**Comment by dennisdoomen** [comment]
I think it had to do with the nullable assertion extensions, but I'm not sure.
