### ISSUE TITLE
Check for key value pair with out case

### ISSUE THREAD

**Issue by akshetty9** [fluentassertions/fluentassertions#439]
Is it possible to ignore the case when asserting a key value pair present in dictionary. Any option Contains() will do this?

**Comment by dennisdoomen** [comment]
Nope. Sorry. But I do accept pull requests ;-)

**Comment by akshetty9** [comment]
thank you. I will try :)

**Comment by dennisdoomen** [comment]
If this works for you, please close the issue.

**Comment by somewhatabstract** [comment]
This seems like an unusual one considering that the dictionary itself doesn't work that way unless a custom comparer is used. @dennisdoomen Does fluent assertions leverage the comparer of the dictionary when doing such comparisons or does it always do the same thing regardless of the dictionary comparer?

**Comment by dennisdoomen** [comment]
It relies on the `object.Equals` for most of the comparisons, so it should be possible to create such an enhancement.
