### ISSUE TITLE
Unexpected exception on entity collection order assertion failure

### ISSUE THREAD

**Issue by FilipFilipov** [fluentassertions/fluentassertions#447]
Stumbled on a weird bug when using the lambda overloads for `BeInAscendingOrder() / BeInDescendingOrder()` on a collection of entities, where I get a `The operation cannot be completed because the DbContext has been disposed` error only when the condition is not met. This happens with all the immediate nav properties included as well. And no, my comparer expression doesn't use a nav property, (it's a DateTime if that matters).

**Comment by dennisdoomen** [comment]
So is it possible that you're asserting code is outside the scope of the DbContext?

**Comment by FilipFilipov** [comment]
Yes, but I'm not touching anything that's not already loaded. And it works just fine when the collection order is as expected, I only get this when the assertion fails, so maybe the the code that generates the error message is responsible.

**Comment by dennisdoomen** [comment]
When the assertion fails, it will try to render a display-friendly version of that collection so it can show you what it expected and what it found. This may involve traversing the graph.

**Comment by FilipFilipov** [comment]
Ah, okay that explains it. I don't think showing the whole graph is particularly useful though. Can't it display it without the virtual properties that are not part of the comparison expression?

**Comment by dennisdoomen** [comment]
As a workaround, you could alter the formatters collection as described in the extensibility section of the wiki
