### ISSUE TITLE
ShouldBeEquivalentTo() .Using.When() with SelectedMemberInfo not working

### ISSUE THREAD

**Issue by jsmarsch** [fluentassertions/fluentassertions#449]
This is either a bug, or I'm doing something wrong.  
I'm using ShouldBeEquivalentTo to compare a large graph that I am getting from a REST service.

It's working great except for 1 business rule that I have to account for:
An object that can appear in the collection looks like this:
TheObject.AValue;
TheObject.AValueCode;

If AValueCode is non-null, then I expect AValue == AValueCode.  If AValueCode is null, then I AValue should equal Expected.AValue.

Here's what I have.  It looks as though the comparison in the .When() call is not working correctly because .When never appears to evaluate to true:

```
.Using<TheObject>(info => info.Subject.AValue.ShouldBeEquivalentTo(info.Subject.AValueCode?? info.Expected.AValue)
.When(subject => subject.RuntimeType == typeof(TheObject) && subject.SelectedMemberInfo.Name == "AValue";
```

I believe that the failure is on the  && subject.SelectedMemberInfo.Name because if I comment that part out, I get the correct comparison logic except that the rest of TheObject does not get validated, of course).

Bug, or am I just doing it wrong?

**Comment by dennisdoomen** [comment]
You've switched things around. Normally, `ShouldBeEquivalentTo` is a top-level method that you call on the root of your object graph. It takes an `options` parameter that you can use to tune its behavior.

**Comment by jsmarsch** [comment]
So I changed the ShouldBeEquivalentTo, but I'm still having the same problem.  I've published a "short but complete" project that demos the problem.  You can find it here: https://github.com/jsmarsch/FluentAssertionUsingProblem

Here's the gist of it though.  I think that this test should pass, but it fails:

```
        [Fact]
        public void FluentAssertionShouldPassWhenValueCodeIsUsed()
        {
            var expectedParent = new Parent(new Child {Name = "TestName", AValueCode = "100"});
            var simulatedResult = new Parent(new Child { Name = "TestName", AValueCode = "100", AValue = "100"});

            simulatedResult.ShouldBeEquivalentTo(
                expectedParent,
                options => options.Using<Child>(info => info.Subject.AValue.Should().Be(info.Expectation.AValueCode ?? info.Expectation.AValue))
                               .When(subject => subject.RuntimeType == typeof(Child) && subject.SelectedMemberInfo.Name == "AValue"));
        }

```
If you comment out the && subject.SelectedMemberInfo.Name == "AValue", then the test passes (but of course, then the assert only looks at the one propery, and my "real" child object has many other properties that should be compared in the default manner.

**Comment by jsmarsch** [comment]
One other question (and thank you for your help).

Is this a valid work-around?  I created an IEquivalencyStep (see below), and added it with a .Using().  It appears to do what I want, but I'm not very familiar with Fluent Assertions's internal workings, so(absolutely wicked tool, by the way!), so I'm not sure whether there is a better way or whether I loused something up 

don't miss my previous response though (above) -- I build a unit test above that repro's the problem I'm having.

```
        public bool Handle(IEquivalencyValidationContext context, IEquivalencyValidator parent, IEquivalencyAssertionOptions config)
        {
            Child subject = context.Subject.As<Child>();
            Child expected = context.Expectation.As<Child>();
            subject.ShouldBeEquivalentTo(context.Expectation, options => options.Excluding(info => info.SelectedMemberInfo.Name == "AValue"));
            subject.AValue.Should().Be(expected.AValueCode ?? expected.AValue);
            return true;
        }
```

**Comment by dennisdoomen** [comment]
Have you tried to debug the lambda in the `When` call to see if it is called at all?

**Comment by jsmarsch** [comment]
I think it's being interpreted as an expression, and not a delegate. When I
breakpointed the lambda, Visual Studio changed the breakpoint at runtime so
that it broke on the call to ShouldBeEquivalentTo()

**Comment by jnyrup** [comment]
@jsmarsch When `subject.SelectedMemberInfo.Name == "AValue"` is true then `subject.RuntimeType` is not referring to `Child`, but to `string`, i.e. the type of `AValue`. 
So when reaching the property `AValue`, you are not about to compare two `Child` instances, but rather two `string` instances.

While I don't think the `Using`+`When` API was designed with your type of comparison logic in mind, we can abuse it, even though it gets ugly.

```csharp
[Fact]
public void FluentAssertionShouldPassWhenValueCodeIsUsed()
{
    var expectedParent = new Parent(new Child { Name = "TestName", AValueCode = "100" });
    var simulatedResult = new Parent(new Child { Name = "TestName", AValueCode = "100", AValue = "100" });

    simulatedResult.Should().BeEquivalentTo(
        expectedParent,
        options => options.Using<Child>(info => UsingPredicate(info))
                            .WhenTypeIs<Child>());
}

private static void UsingPredicate(IAssertionContext<Child> info)
{
    info.Subject.Should()
        // Your specified business logic
        .Match<Child>(e => e.AValue == (info.Expectation.AValueCode ?? info.Expectation.AValue))
        .And
        // compare all other properties of `Child`, except `AValue` and `AValueCode`
        .BeEquivalentTo(info.Expectation,
            opt => opt.Excluding(e => e.AValue)
                        .Excluding(e => e.AValueCode));
}
```

**Comment by jnyrup** [comment]
@jsmarsch As you asked this question over two years ago, I assume this question is no longer relevant for you, or that my post answered your question.
If not, feel free to reopen.
