### ISSUE TITLE
Should().BeOfType<T>() does not support value types

### ISSUE THREAD

**Issue by RaYell** [fluentassertions/fluentassertions#459]
`Should.BeOfType<T>()` supports only reference types. If you try something like

```
var x = 1;
x.Should().BeOfType<int>();
```

the code will not compile as `BeOfType` is defined only for reference types.

The workaround is something like `x.GetType().Should.Be(typeof(int))` but I think it'd be easier to just allow value types to be used with this method.

**Comment by dennisdoomen** [comment]
Thanks for reporting this. It's funny nobody has noticed this over the course of the five years FA exists.

**Comment by ankurMalhotra** [comment]
Can I pick this up if no one else is working on it?

**Comment by dennisdoomen** [comment]
Sure. Go ahead.

**Comment by raghav710** [comment]
I think this issue can be closed. Can someone please do the honours :)
