### ISSUE TITLE
Support non-generic type parameter passing

### ISSUE THREAD

**Issue by RaYell** [fluentassertions/fluentassertions#460]
While generics are great in a lot of situations, sometime it would be useful to be able to pass the type parameter as a regular parameter rather than generic parameter.

As an example, I often have constructs like this

```c#
[Theory]
[MemberData(nameof(MyMemberTests))]
public void ShouldThrowExceptionForInvalidSelectors(Type exceptionType, Action selectorAction)
{
    Assert.Throws(exceptionType, selectorAction);
}
```

And I simply pass the expected exception type as parameter so I don't have to have duplicate code for similar cases (I usually use this construct for `ArgumentNullException` and `ArgumentException` checking).

Now, there's no way to use the fluent assertions with this construct as `ShouldThrow<T>` is a generic method. I could use reflection to invoke this method but that's just ugly.

I'd be great to have the overloads for generic methods that would accept the type as one of it's parameters. In this example something like:

```
ShouldThrow(
    this Action action, Type exceptionType, string because = "", params object[] becauseArgs)
```

**Comment by somewhatabstract** [comment]
This seems related to https://github.com/dennisdoomen/FluentAssertions/issues/478

Anyone picking this up can probably look at the work done there for inspiration.

**Comment by jnyrup** [comment]
With the current xunit, you can get the best of both worlds.
https://github.com/fluentassertions/fluentassertions/blob/97d737e89043cec5b3291aeb321fa1cb14f3c457/Tests/Shared.Specs/ExceptionAssertionSpecs.cs#L29-L36

**Comment by jehof** [comment]
I would like to work on this issue. Is it possible to assign me that issue?

**Comment by dennisdoomen** [comment]
Does anybody care about this?

**Comment by jnyrup** [comment]
For test frameworks that do no support generic parameters, and hence cannot use the workaround above, our suggestion to users in #1629 and https://stackoverflow.com/a/76611833 is
```cs
action.Should().Throw<Exception>().Which.Should().BeOfType(expectedType);
```
which I find quite verbose (read: as in contrast to concise and to the point).

A use case for the API is that since `typeof()` can used as an [attribute argument expression](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/attributes#223-attribute-specification), the invalid input to `Do` can be stitched directly on the test method.

```cs
[Theory]
[InlineData(-1, "title", typeof(ArgumentOutOfRangeException))]
[InlineData(0, null, typeof(ArgumentNullException))]
[InlineData(0, "", typeof(ArgumentException))]
public void Invalid_values(int value, string title, Type exception)
{
    Invoking(() => Do(value, title)).Should().Throw(exception);
}

private void Do(int value, string title)
{
    if (value < 0) throw new ArgumentOutOfRangeException(nameof(value));
    if (title is null) throw new ArgumentNullException(nameof(title));
    if (title is "") throw new ArgumentException("value must not be empty", nameof(title));

    // ...
}
```

I think this can have value, but it needs more work on what the method signatures should be for new `DelegateAssertions` and `AsyncFunctionAssertions` overloads and how it will work together with `ExceptionAssertions<TException>`.

**Comment by dennisdoomen** [comment]
Since there's no response, I'm going to close this issue.

**Comment by mycarrysun** [comment]
If anyone wants this here's an extension method I made:
```csharp
public static class AsyncFunctionAssertionExtensions
{
    public static async Task<AndConstraint<ObjectAssertions>> ThrowAsync<TTask, TAssertions>(
        this AsyncFunctionAssertions<TTask, TAssertions> assertions,
        Type exceptionType
    )
        where TTask : Task
        where TAssertions : AsyncFunctionAssertions<TTask, TAssertions>
    {
        return (await assertions.ThrowAsync<Exception>()).Which.Should().BeOfType(exceptionType);
    }
}```
