### ISSUE TITLE
Ground work for Fluent Assertions 5.0

### ISSUE THREAD

**Issue by dennisdoomen** [fluentassertions/fluentassertions#463]
**Ground Work**
- [x] Switch to XUnit (for Devices)?
- [x] Switch to Cake
- [x] Move JSON support to a separate repo to support different release cycles
- [x] Drops support for .NET 4.0, Silverlight, Windows 8.0/8.1, WPA and Windows Phone for Silverlight.
- [x] Redirect contributors to the master branch for bug-fixes.
- [x] Move to dedicated organization
- [x] Start logo contest
- [x] Cross-compiles .NET Standard 1.4 (so we can support XmlDocument and UWP), .NET Standard 1.6 (to support .NET Core)  and .NET Framework 4.5 (#558)

**Comment by dennisdoomen** [comment]
@onovotny any thoughts on this?

**Comment by onovotny** [comment]
LGTM :)

**Comment by dennisdoomen** [comment]
@onovotny will this allow you to get rid of FA.Xamarin?

**Comment by MannusEtten** [comment]
maybe also support for UWP?

**Comment by dennisdoomen** [comment]
> maybe also support for UWP?

Hmm, that would mean I have to target 1.4. @onovotny can you confirm?

**Comment by onovotny** [comment]
If you target 1.4, then that includes UWP.

**Comment by SaroTasciyan** [comment]
@dennisdoomen Regarding #257 planning to remove `ShouldBeEquivalentTo()` in v5 to prevent confusion?

**Comment by dennisdoomen** [comment]
I was planning to give them the same behavior.
