### ISSUE TITLE
Opt-in automatic conversion in ShouldBeEquivalentTo

### ISSUE THREAD

**Issue by lukefan6** [fluentassertions/fluentassertions#472]
Somehow in my project I need to see if the contents of two List< List< object >> are identical.
And I tried different should-be-equivalent assertions but the results are confusing:

```
var actual = new List<List<object>>
{
  new List<object> { 1, "401", 100, null }
};

var expected = new List<List<object>>
{
  new List<object> { 1, "401", "100", null }
};

actual.Should().BeEquivalentTo(actual); // FAIL
actual.ShouldBeEquivalentTo(actual); // PASS 
actual.ShouldAllBeEquivalentTo(actual); // PASS

actual.Should().BeEquivalentTo(expected); // FAIL
actual.ShouldBeEquivalentTo(expected); // PASS 
actual.ShouldAllBeEquivalentTo(expected); // PASS
```

As you can see the assertion results are all the same no matter they are identical or not.

Currently I'm using a workaround where I loop through each entry of the collection and use Should().Equal() to assert.

```
for (var index = 0; index < expected.Count; index++)
{
                var actualRow = actual[index];
                var expectedRow = expected[index];
                actualRow.Should().Equal(expectedRow, because: "row[{0}] should be identical", becauseArgs: index);
}
```

**Comment by dennisdoomen** [comment]
In this particular case, `actual.ShouldBeEquivalentTo(actual)` would be the correct assertion. In this particular case *equivalent* means, it'll try to convert the `100` to `"100"` for you. This can be confusing and will be removed in v5 (see #463). The same applies to the difference between `Should().BeEquivalentTo() and `ShouldBeEquivalentTo`.

**Comment by lukefan6** [comment]
@dennisdoomen what if I want the assertion to fail?
I mean, { 1, 100 } != { 1, "100" }
I want my unit test can catch that.
Is there any existing assertion that I can use?

Anyway, thanks for prompt reply

**Comment by dennisdoomen** [comment]
Unfortunately, you can't right now. You would need to remove the TryConversionEquivalencyStep from the global `AssertionOptions.EquivalencySteps` collection.

**Comment by lukefan6** [comment]
@dennisdoomen  I see, now I can achieve what I intended to assert following your suggestions
Thanks so much.

**Comment by dennisdoomen** [comment]
No problem. The fact that it is so confusing warrants changing this in a next major version.

**Comment by lukefan6** [comment]
Another question came up :p

Back to my original question, I'd like to perform assertions against two-dimensional collections.
The contents should be identical in order, even for inner collection.
Following snippet illustrates my expectation

```
		[TestMethod]
		public void Test()
		{
			var twoDimensionalArray1 = new object[][]
			{
				new object[] { 1, 2, 3 }
			};

			var twoDimensionalArray2 = new object[][]
			{
				new object[] { 1, 2, 3 }
			};

			var twoDimensionalArray3 = new object[][]
			{
				new object[] { 1, 3, 2 }
			};

			twoDimensionalArray1.Should().Equal(twoDimensionalArray2); // this fails :(
			twoDimensionalArray1.Should().NotEqual(twoDimensionalArray3); // this passes
		}
 
```

That is, I'd like to write a unit test where:

twoDimensionalArray1 == twoDimensionalArray2 
twoDimensionalArray1 != twoDimensionalArray3

If I read the wiki right, collection.Should().Equal() will compare elements in order.
However, it doesn't seem to apply for two-dimensional collections.  
Any existing assertion / configuration I can use?

**Comment by dennisdoomen** [comment]
Use `twoDimensionalArray1.ShouldBeEquivalentTo(twoDimensionalArray2, x => x.WithStrictOrdering`

**Comment by lukefan6** [comment]
Works like a charm, @dennisdoomen  thanks again.

**Comment by ulrichb** [comment]
@dennisdoomen Is your plan to make this "automatic conversion" opt-in (breaking change) or opt-out? I'm for opt-in because I found it very surprising that `ShouldBeEquivalentTo()` does not prove type equality _for scalar types_.

**Comment by dennisdoomen** [comment]
@ulrichb See #463. I'll make it opt-in (and thus a breaking change)

**Comment by ulrichb** [comment]
@dennisdoomen Thanks.
