### ISSUE TITLE
Problem with dynamic as argument

### ISSUE THREAD

**Issue by abenedykt** [fluentassertions/fluentassertions#473]
When a function gets a dynamic as argument I get an error event though it returns not dynamic result

Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Element „bool” does not contain a definition for „Should”.

```
  [Fact]
  public void PassingTest()
  {
      true.Should().BeTrue();
      false.Should().BeFalse();
      object arg = "aad";
      SomeMethod(arg).Should().BeTrue();

  }

  [Fact]
  public void FailingTest()
  {
      true.Should().BeTrue();
      false.Should().BeFalse();
      dynamic arg = "aad";
      SomeMethod(arg).Should().BeTrue();

  }

  private bool SomeMethod(dynamic arg)
  {
      return true;
  }
```

**Comment by dennisdoomen** [comment]
Are you still having this problem? It looks more like a compiler problem than a FA issue.

**Comment by dennisdoomen** [comment]
Or did you forget the `Using FluentAssertions` namespace declaration?

**Comment by abenedykt** [comment]
Just tried it again on VS2017 and .net 4.6 and packages.config like:

```
<packages>
  <package id="FluentAssertions" version="4.19.2" targetFramework="net46" />
  <package id="xunit" version="2.2.0" targetFramework="net46" />
  <package id="xunit.abstractions" version="2.0.1" targetFramework="net46" />
  <package id="xunit.assert" version="2.2.0" targetFramework="net46" />
  <package id="xunit.core" version="2.2.0" targetFramework="net46" />
  <package id="xunit.extensibility.core" version="2.2.0" targetFramework="net46" />
  <package id="xunit.extensibility.execution" version="2.2.0" targetFramework="net46" />
  <package id="xunit.runner.visualstudio" version="2.2.0" targetFramework="net46" developmentDependency="true" />
</packages>
```

and it still gives *: Element „bool” nie zawiera definicji „Should”.* on Failing Test

**Comment by dennisdoomen** [comment]
What about the namespace?

**Comment by abenedykt** [comment]
Didn't noticed your question. Sorry for that. Here is an example project and failing tests. Hope it helps. I would be happy to help you more if I can 

https://github.com/abenedykt/bug_example

**Comment by HajbokRobert** [comment]
That is how C# works, it's not a FluentAssertions bug. Passing dynamic as a method parameter makes the function return a dynamic(object) instead of a bool, because of the late binding of the compiler. It means you have to cast before using the extension method for a dynamic object, something like:

``` csharp
 ((bool)SomeMethod(arg)).Should().BeTrue()
```

See these for further reference:
https://stackoverflow.com/questions/7829518/dynamic-parameter-causes-compiler-to-think-method-return-is-dynamic
and
https://stackoverflow.com/questions/5311465/extension-method-and-dynamic-object

**Comment by abenedykt** [comment]
ok, so I guess we cannot do much about it at least for now.
