### ISSUE TITLE
To many overheads when executing many tests on same objects

### ISSUE THREAD

**Issue by IgorVyatkin** [fluentassertions/fluentassertions#475]
There are to many infrastructure (reflection and lambda compilation) overheads when we many times executing a test with different data, In our case we have the one NUnit test that receives about 20k complex data records (many level hierarchy with object, collection etc) from the test data provider.

I've checked execution pats with dotTrace and found that about 90% of execution time take infrastructure tasks such as reflection calls and lambdas compilations. It happens because every comparison prepares information about comparing objects from scratch.

As I understand some reflection and lambda caches should be added to avoid this issue.

**Comment by dennisdoomen** [comment]
Thanks for the report. I was waiting for this complaint for over 5 years ;-)

Are you using strict ordering during assertions/

**Comment by IgorVyatkin** [comment]
No, we're using FA in the following very simple way:
```
calculatedCompliancePeriods.ShouldAllBeEquivalentTo(
	requiredCompliancePeriods,
	config => config
		.IncludingAllRuntimeProperties()
		.Excluding(period => period.TermMonths)
		.Excluding(period => period.CodeOnlyExemption));
```

**Comment by IgorVyatkin** [comment]
Just for performance comparison ;) I've tried Compare-Net-Objects that uses the reflection cache and it works much faster (5-7 times) than FA but unfortunately has big problems with comparison of collections that contain object of different types.

**Comment by dennisdoomen** [comment]
> No, we're using FA in the following very simple way:

If you know that the order is relevant, you might want to use `UseStrictOrdering`. That will prevent FA from comparing every value with every other value.

**Comment by IgorVyatkin** [comment]
Sorry, I forgot to write that we cannot use the strict order in those tests.

**Comment by IgorVyatkin** [comment]
@dennisdoomen, Do we have any chance to see a fix for this problem in the near future? ;-)

**Comment by dennisdoomen** [comment]
Until the end of September I will probably not have much time for anything but bugs. But I do welcome pull requests.

**Comment by IgorVyatkin** [comment]
@dennisdoomen, I'll try to provide a PR that improves FA performance before end of week.

**Comment by somewhatabstract** [comment]
@IgorVyatkin How's that PR coming along? :smile:

**Comment by jnyrup** [comment]
@IgorVyatkin We did some performance improvements for 5.0.0, that delays the construction of the error message, so that it is only created if the test fail.
Maybe that eliminates the overhead you're experiencing?

If not, can you provide a working example that that have the bottleneck?

**Comment by jnyrup** [comment]
@IgorVyatkin [5.3.0](https://github.com/fluentassertions/fluentassertions/releases/tag/5.3.0) has been released, which includes optimizations specifically for `BeEquivalentTo`, see #817 .

If you have time to reevaluate the performance of Fluent Assertions on the aforementioned data, or provide the data, that would be very helpful. Thanks.

**Comment by jnyrup** [comment]
I'm gonna close this, as both 5.0.0 and 5.3.0 includes several performances improvements.
If you have a complete test case or other information to help debug performance issues, feel to re-open.

**Comment by pentp** [comment]
This is still a problem with 5.4.2 - about half of our test execution time is spent in `LambdaCompiler.Compile` (which is mostly called from `GenericEnumerableEquivalencyStep.Handle`, `GenericDictionaryEquivalencyStep.AssertSameLength`+`AssertDictionaryEquivalence`).

Why use `LambdaCompiler.Compile` at all if the result isn't cached and the only operation is to invoke a method dynamically? Simple reflection would be orders of magnitude faster.
And `AssertSameLength` could do a quick length check by casting directly to `ICollection`.
