### ISSUE TITLE
Event monitoring is not working properly for asyncronous tests

### ISSUE THREAD

**Issue by MichaWresche** [fluentassertions/fluentassertions#477]
Please consider the following test:

``` csharp
[TestMethod]
public async Task Test()
{
    var sut = new ViewModel();
    sut.MonitorEvents();
    await sut.DoSomethingAsync();
    sut.ShouldRaisePropertyChangeFor(vm => vm.BusyErrorText);
}
```

Sometimes, this test fails by an InvalidOperationException with description "Object <{0}> is not being monitored for events or has already been garbage collected. Use the MonitorEvents() extension method to start monitoring events."
The reason is the `ThreadStatic`-Attribute which is used for decorating the EventRecordersMap in the EventMonitor class.
Typically, UnitTests does not have a synchronization context so the code after await will be executed on any idle thread which is not the same thread as the thread that has been started the test. As a result, a new (empty) EventRecordersMap will be created and used when calling sut.ShouldRaisePropertyChangeFor(...).

**Comment by dennisdoomen** [comment]
Thanks for reporting.

**Comment by informatorius** [comment]
I don't know if it is the same issue but when 2 tasks fire events in a class under test then sometimes MonitorEvents is not catching both. So either in EventMonitor or EventRecordersMap there should be some locking.

**Comment by dennisdoomen** [comment]
@informatorius I believe it is the same problem. The current API doesn't simply not work with `async/await` code.

**Comment by informatorius** [comment]
I can reproduce the issue and can fix it with lock(object).
Should I make a pull request?

**Comment by dennisdoomen** [comment]
You can't really solve it like that. You might even cause deadlocks.

**Comment by informatorius** [comment]
My issue is with the MonitorEvents() method called from different threads and I get this exception:
`System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.

    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.CopyTo(KeyValuePair`2[] array, Int32 index)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at FluentAssertions.Events.EventRecordersMap.ForEach(Object eventSource, Action`1 action)
   at FluentAssertions.Events.EventRecordersMap.Add(Object eventSource, IEnumerable`1 recorders)
   at System.Threading.Tasks.Task.Execute()
`

I can fix it be using lock(object) at the MonitorEvents() method directly.

**Comment by dennisdoomen** [comment]
The problem is caused by the use of `[ThreadStatic]` which makes it unfit in multi-threaded situations. There's no workaround other than redesigning the API.

**Comment by informatorius** [comment]
OK then I may have a different issue and proceed in a new issue.
