### ISSUE TITLE
Add non-generic ReferenceTypeAssertions.BeAssignableTo

### ISSUE THREAD

**Issue by khodaie** [fluentassertions/fluentassertions#478]
The `ReferenceTypeAssertions.BeAssignableTo<T>` only supports definite types. Add the non generic `BeAssignableTo(Type type)` method to check to types in reflective programming.

**Comment by dennisdoomen** [comment]
Thanks for reporting. This is  your chance to become a contributor....;-)

**Comment by jnyrup** [comment]
Implemented in #483
