### ISSUE TITLE
Assertions should not call formatters unless they fail

### ISSUE THREAD

**Issue by shift-evgeny** [fluentassertions/fluentassertions#489]
I have a custom formatter that outputs all the values in an array. When I call `array.Should().Equal(otherArray)` this can take a very long time. Profiling shows that this is because FluentAssertions builds the entire "expected" message inside AssertionScope.WithExpectation before executing the assertion. It should do this only if the message is needed, i.e. if the assertion fails. That is, I want to see the contents of the whole array and I'm OK with waiting for that when the test fails, but it's useless when the test passes.

Another aspect to this is that if the formatter throws an exception the test fails, even though the assertion is true, which is clearly not the behaviour a user would expect.

**Comment by krajek** [comment]
@dennisdoomen I would like to tackle it, any objections?

**Comment by dennisdoomen** [comment]
Sure, but please base your branch on https://github.com/dennisdoomen/fluentassertions/tree/CallerContext, which I'm going to merge today or tomorrow (as part of #498).

**Comment by dennisdoomen** [comment]
My changes have been merged to the `release-5.0` branch, so no need to do anything special anymore.

**Comment by krajek** [comment]
@shift-evgeny mentioned `WithExpectation` method which is already using lazy calculation. It was implemented in the meantime in b444a390aeeaa08b6309782b97f97a3bae8c9bc1.

`FailWith`, just as `WithExpectation`, formats message only when the test failed.

The last missing piece `BecauseOf`, which eagerly formatted `reason`, is changed to lazy in PR #725.

It seems to me, that the PR will complete the topic.
