### ISSUE TITLE
ExceptionAssertion "WithMessageAndParameterName" 

### ISSUE THREAD

**Issue by KusumSitecore** [fluentassertions/fluentassertions#491]
Hi,
I am writing a extension method which can compare "Custom Error Message" with Exception Error Message.

Need your input on implementation on this.

```
    public static ExceptionAssertions<Exception> WithMessageForParameter(this ExceptionAssertions<Exception> exceptionAssertions, string parameterName,string errormessage)
    {
        //var nullParameterMessageFormatString = errormessage  + ".\r\nParameter name: {0}";
        exceptionAssertions.WithMessage(errormessage);
        return exceptionAssertions;
    }
```

regards
Kusum

**Comment by dennisdoomen** [comment]
I dont get what you are trying to do. Most of the parameters are not used in your code example.

**Comment by jnyrup** [comment]
Closing this due to no response.
Feel free to re-open, if you have additional information that clarifies the question.
