### ISSUE TITLE
ShouldBeEquivalentTo: exclude a property of all of a list items

### ISSUE THREAD

**Issue by drauch** [fluentassertions/fluentassertions#500]
Current state of the art:

> Maybe far-fetched, but you may even decide to exclude a member on a particular nested object by its index.

```cs
 orderDto.ShouldBeEquivalentTo(order, options => options.Excluding(o => o.Products[1].Status)); 
```
It would be nice to be able to exclude `Status` for all items in the list. One could use a special index instead for that, e.g., something along the lines of:

```cs
orderDto.ShouldBeEquivalentTo(order, options => options.Excluding(o => o.Products[Something.AllItems].Status));
```

This would be much better than the current workaround (using `PropertyPath`), as it is refactoring-safe.

Best regards,
D.R.

**Comment by dennisdoomen** [comment]
It's a nice idea, but probably a lot of work to get done.

**Comment by Jenan** [comment]
Hello,
I have tried to compare the lists but I can't find the property called `PropertyPath`.

I have used the version `4.19.4`.

How can I fix it? 
Thx.

**Comment by dennisdoomen** [comment]
It's on the `ISubjectInfo` object that is passed as part of the overload of `Including` and `Excluding` that take `Func<ISubjectInfo, bool>`

**Comment by Jenan** [comment]
I have tried this snippet for testing:
```
var clientDtos = new List<ClientDto>();
var clientDtosToCompare = new List<ClientDto>();

clientDtos.ShouldBeEquivalentTo(clientDtosToCompare, option => option.Excluding(x=> x.PropertyPath == "ClientName"));
```
But `PropertyPath` doesn't exist - can you please correct my code?

**Comment by jnyrup** [comment]
`PropertyPath` was removed from `ISubjectInfo` in [v4](https://github.com/fluentassertions/fluentassertions/releases/tag/4.0.0).

Use `SelectedMemberPath` instead
```csharp
clientDtos.ShouldBeEquivalentTo(clientDtosToCompare, option => option.Excluding(x => x.SelectedMemberPath.EndsWith("ClientName")));
```

**Comment by Jenan** [comment]
@jnyrup You are absolutely right, that works very well, thank you!

**Comment by davisnw** [comment]
The suggested workaround of just checking "SelectedMemberPath" is too broad.  Sometimes I have the same property name on different classes, but only want to exclude it on one of the classes.  This is problematic when dealing with collections.

It seems like I should be able to due something with the `IMemberInfo` `Excluding` overload, but I haven't yet had success, and the documentation on the FluentAssertions site is lacking in that regard - and there doesn't seem to be any general per-method api level documentation that I can find.  Since it takes an `Expression` I can't actually debug into it either (that's the trade-off, better failure messages versus debuggability).

E.g., this does not work:

     .Excluding((IMemberInfo memberinfo) => 
       memberinfo.CompileTimeType == typeof(PaymentMethodItem) 
       && memberinfo.SelectedMemberPath.EndsWith("CurrentDate")
     )

I suppose I can dig into the FluentAssertions source code if I have to, but that really shouldn't be necessary.

**Comment by davisnw** [comment]
Figured out what I needed to do.  To debug the `Excluding` clause, you can do something like the following:

        //...
             .Excluding((IMemberInfo memberInfo) => Debug(memberInfo))
        //...
        public bool Debug(IMemberInfo memberinfo)
        {
            return false;
        }

This allows you to set breakpoints in the `Debug` method.

For my case, I wanted to exclude a specific property of a specific type, which was accomplished by:

    .Excluding((IMemberInfo memberinfo) => 
          memberinfo.SelectedMemberInfo.DeclaringType == typeof(PaymentMethodItem)
          && memberinfo.SelectedMemberInfo.Name == "CurrentDate"
    )

**Comment by jnyrup** [comment]
@davisnw Can you provide a complete example?
Or just mention which *specific* overload of `BeEquivalentTo` you are using?

If you use a generic overload of `BeEquivalentTo`, i.e. one where the expectation is *not* something like  `params object[]` or `IEnumerable`, this works:

```c#
class Outer
{
    public int Value { get; set; }
    public Inner InnerMember { get; set; }
}

class Inner
{
    public int Value { get; set; }
}
```

Exluding the outer `Value`
```c#
var actual = new[]
{
    new Outer
    {
        Value = 1,
        InnerMember = new Inner
        {
            Value = 42
        }
    }
};

var expected = new[]
{
    new Outer
    {
        Value = 2,
        InnerMember = new Inner
        {
            Value = 42
        }
    }
};

actual.Should().BeEquivalentTo(expected, opt => opt.Excluding(e => e.Value));
```

Excluding the inner `Value`
```c#
var actual = new[]
{
    new Outer
    {
        Value = 42,
        InnerMember = new Inner
        {
            Value = 1
        }
    }
};

var expected = new[]
{
    new Outer
    {
        Value = 42,
        InnerMember = new Inner
        {
            Value = 2
        }
    }
};

actual.Should().BeEquivalentTo(expected, opt => opt.Excluding(e => e.InnerMember.Value));
```

**Comment by LuisMiguelFilipe** [comment]
I just ran into the same problem and I would to propose a solution.

In my object, `WizardSteps` is an array.
I used a private method `RemovingIndexes` (I could have used an extension method as well)
```
.Should().BeEquivalentTo(..., opt =>
  opt.Excluding(ctx => RemovingIndexes(ctx) == "WizardSteps.Element")

static string RemovingIndexes(IMemberInfo w)
{
    return Regex.Replace(w.SelectedMemberPath, @"\[\d+\]", "");
}
```

We could easily provide such functionality by:
1. create a new Method named `ExcludingRemovingIndexes` 
1. or add to `IMemberInfo` a new Property named `SelectedMemberPathWithoutIndexes`

**Comment by postb99** [comment]
I think the documentation should pinpoint the available feature, for simple cases.
It's really straighforward to ignore an additional member of the source object...
For nested objects, let's discuss...

`target.Should().BeEquivalentTo(source, options => options.Excluding(src => src.Title));`

**Comment by donotcodeit** [comment]
Additional suggestion that will not lose type checking, but only applicable if excluding is dependent on collection item `Type`:

```c#
class Item
{
    public int Id { get; set; }
    public string Value { get; set; }
}

class Foo
{
    public Item[] Items { get; set; }
}

public void Test()
{
    var expected = ...;
    var actual = ...;

    actual.Should().BeEquivalentTo(expected, options => options
        .Using<Item>(ctx => ctx.Subject.Id.Should().NotBe(0)) // Or even .Match(_ => true)
        .WhenTypeIs<Item>());
}
```

It would be great if something like this approach will be implemented, to make it less wordy, and also to make more strict selection based on certain properties instead of just `Type`:
```c#
public void Test()
{
    var expected = ...;
    var actual = ...;

    actual.Should().BeEquivalentTo(expected, options => options
        .ForCollection(x => x.Items, ctx => ctx.Subject.Id.Should().NotBe(0)));
}
```

**Comment by JayFad** [comment]
> `PropertyPath` was removed from `ISubjectInfo` in [v4](https://github.com/fluentassertions/fluentassertions/releases/tag/4.0.0).
> 
> Use `SelectedMemberPath` instead
> 
> ```cs
> clientDtos.ShouldBeEquivalentTo(clientDtosToCompare, option => option
>     .Excluding(x => x.SelectedMemberPath.EndsWith("ClientName")));
> ```

What's with the EndWith , I have properties that end up with the same suffix , but I need only one of the properties to be removed.

**Comment by dennisdoomen** [comment]
> What's with the EndWith , I have properties that end up with the same suffix , but I need only one of the properties to be removed

I don't understand the question

**Comment by JayFad** [comment]
> > What's with the EndWith , I have properties that end up with the same suffix , but I need only one of the properties to be removed
> 
> I don't understand the question

I have properties in the child collection, that has structure something like this : 

`public class ApparatusList
    {
        public string prop1{ get; set; }

       public string prop2{ get; set; }

        public List<OrderingDetail > OrderingDetails { get; set; }
     }`

and the OrderDetail is something like : 

    `public uint? MinPrice { get; set; }

        public uint? MaxPrice { get; set; }

        public uint? TotalPrice { get; set; }
`
If I only want to exclude property of OrderingDetail , TotalPrice , how to do that?

**Comment by dennisdoomen** [comment]
You can use a dotted path, like `x.SelectedMemberPath.EndsWith("OrderingDetails.TotalPrice")`

**Comment by cpeeyush** [comment]
Can also be done for a field.

```
actual.Should().BeEquivalentTo(expected, options => options.Excluding(x => x.Items).ExcludingFields());
```

**Comment by monet820** [comment]
This worked for me to Ignore one property.
  
  values.First().Should().BeEquivalentTo(items.First(), options => options.Excluding(x => x.Values));
  
  I first tried the values.First.ShouldBeEquivalentTo but that do not have the function options.

**Comment by dennisdoomen** [comment]
> orderDto.ShouldBeEquivalentTo(order, options => options.Excluding(o => o.Products[Something.AllItems].Status));

You can now do 

```
orderDto.Should().BeEquivalentTo(order,
    options => options
        .For(x => x.Products)
        .Exclude(x => x.Status));
```
