### ISSUE TITLE
AssertExpectationIsCollection null reference exception

### ISSUE THREAD

**Issue by miloszes** [fluentassertions/fluentassertions#522]
A method

GenericEnumerableEquivalencyStep->
private static bool AssertExpectationIsCollection(object expectation, object subject)

throws a null in case an expectation object is null and subject i an empty collection (ex. HashSet).

**Comment by dennisdoomen** [comment]
I just tried this:

```csharp
           var subject = new
            {
                Property = new HashSet<string>()
            };

            var expected = new
            {
                Property = (HashSet<string>)null
            };

            subject.ShouldBeEquivalentTo(expected);
```

But that throws the following (expected) message:

     Expected member Property to be <null>, but found {empty}.

Is this what you meant?

**Comment by dennisdoomen** [comment]
No response for more than 8 months, so will close this.
