### ISSUE TITLE
Missing NotBeDecoratedWith assertion for types

### ISSUE THREAD

**Issue by zkestenbaum** [fluentassertions/fluentassertions#527]
There does not appear to be any way to assert that a type is NOT decorated with a certain attribute. 

The wiki shows how to test for the presence of an attribute (see [https://github.com/dennisdoomen/fluentassertions/wiki#type-method-and-property-assertions](url)), but there is no way to test for the absence of an attribute. `NotBeDecoratedWith` already exists as a `MemberInfoAssertion `and a `PropertyInfoAssertion`, but not as a `TypeAssertion`.

Also see this related question on StackOverflow - [http://stackoverflow.com/questions/24070898/fluent-assertions-thatarenotdecoratedwith](url).

I would propose adding `NotBeDecoratedWith` and `ThatAreNotDecoratedWith` for types.

**Comment by dennisdoomen** [comment]
You're right. We forgot about that one. I would welcome a PR for that ;-)

**Comment by zkestenbaum** [comment]
Just submitted a pull request - my first one on GitHub, so I welcome any feedback.

**Comment by dennisdoomen** [comment]
Hi @zkestenbaum. Are you still going to finish your PR?

**Comment by zkestenbaum** [comment]
Yes, thanks for following up. Will finish this shortly.
