### ISSUE TITLE
Dictionary of DateTime comparison. Am I doing something wrong, or is this an issue?

### ISSUE THREAD

**Issue by msonme** [fluentassertions/fluentassertions#530]
Two dateTimes put in identical Dictionaries, just 1 millisecond difference...

var date1 = new DateTime(2017, 3, 1);
var date2 = date1.AddMilliseconds(1);

var myDict1 = new Dictionary<string, DateTime>() { { "dateField", date1 } };
var myDict2 = new Dictionary<string, DateTime>() { { "dateField", date2 } };

myDict1.ShouldAllBeEquivalentTo(myDict2, 
  options => options.Using< DateTime >
      (item =>   item.Subject.Should().BeCloseTo(item.Expectation, 1000))
   .WhenTypeIs< DateTime >());

Why does the BeCloseTo rule not work? The test fails (Also tried with <KeyValuePair<sting, DateTime>> as the generic type? Confused. Can anybody help. thanks so much!

**Comment by ben-m-lucas** [comment]
What's the failure that you're getting?  I just created a unit test using this code and the unit test passed.

**Comment by jnyrup** [comment]
Tried running this with v5.4.1
```csharp
// Arrange
var date1 = new DateTime(2017, 3, 1);
var date2 = date1.AddMilliseconds(1);

var myDict1 = new Dictionary<string, DateTime>() { { "dateField", date1 } };
var myDict2 = new Dictionary<string, DateTime>() { { "dateField", date2 } };

// Act / Assert
myDict1.Should().BeEquivalentTo(myDict2,
    options => options.Using<DateTime>(item => item.Subject.Should().BeCloseTo(item.Expectation, 1.Seconds()))
        .WhenTypeIs<DateTime>());
```

and got
> Expected pair[dateField] to be <2017-03-01 00:00:00.001>, but found <2017-03-01>

A description of what happens:
`AssertEquality` detects `GenericDictionaryEquivalencyStep` is able to handle `Dictionary<string, DateTime>`.

When `AssertEquality` tries to find an appropriate user handler for the `context` with two `DateTimes` as `Subject` and `Expectation` created by `CreateForDictionaryItem`, `AssertionRuleEquivalencyStepAdapter.CanHandle` returns `false` as `context.SelectedMemberInfo` is `null`.

If I force `CanHandle` to pass, the `if (predicate(context))` in `AssertionRule.AssertEquality` is able to handle the `context` and the assertion passes as expected.

I'm not sure of the logic behind 
```csharp
public bool CanHandle(IEquivalencyValidationContext context, IEquivalencyAssertionOptions config)
{
    return (context.SelectedMemberInfo != null);
}
```
