### ISSUE TITLE
Logo contest for FluentAssertions

### ISSUE THREAD

**Issue by SaroTasciyan** [fluentassertions/fluentassertions#533]
I wonder whether there's an official logo for _FluentAssertions_ or not? I know that the official web site recently renewed and following logo was introduced (I'm not quite sure if it's new):

![FluentAssertionsLogo](http://www.fluentassertions.com/images/logo.png)

However, I don't see it being used for _NuGet_. 
If there's no official logo and one is to be designed; Have you guys ever considered starting a logo contest as [WebAssembly](https://github.com/WebAssembly/design/issues/112) did?

**Comment by dennisdoomen** [comment]
Sounds like a great idea. As soon as I've moved the repo to the new organization, I'll post a message on twitter.

**Comment by IUsername** [comment]
![fluent_assertions](https://cloud.githubusercontent.com/assets/2133735/22858674/29bb0ed0-f081-11e6-9d72-be7f4ebfff08.png)

I have used Fluent Assertions for many years on numerous project. It is the least I can do to throw a design into the ring. Here are some alternative layouts of this design:

![fluent_assertions_alts](https://cloud.githubusercontent.com/assets/2133735/22858692/737278ba-f081-11e6-84cf-fb4ebd2d7d43.png)

**Comment by dennisdoomen** [comment]
@IUsername wow, simply wow!

**Comment by umuralpay** [comment]
![fluent2](https://cloud.githubusercontent.com/assets/747647/22872688/2c995c00-f1cc-11e6-93c6-7cfff24ee979.png)

Can be something retro, the word "fluent" gives me that mood.

**Comment by bitbonk** [comment]
When  choosing logo, we should also consider what it will look like as the icon for the nuget package, Especially in the nuget package manager of visual studio. This is the place where it will be seen most,

![light theme unselected](https://cloud.githubusercontent.com/assets/418030/23340962/bffd6518-fc3f-11e6-816a-d90a8b9d5e5a.PNG)
![light theme selected](https://cloud.githubusercontent.com/assets/418030/23340968/d3cf935e-fc3f-11e6-94fd-7e7eaccbfc40.PNG)
![dark theme unselected](https://cloud.githubusercontent.com/assets/418030/23340970/e38e0cc6-fc3f-11e6-829e-88cffdf57641.PNG)
![blue theme unselected](https://cloud.githubusercontent.com/assets/418030/23340976/f3ba532a-fc3f-11e6-9025-0ff577e0773f.PNG)
![blue theme selected](https://cloud.githubusercontent.com/assets/418030/23340982/02cd5970-fc40-11e6-8491-039fcabf6090.PNG)

**Comment by SaroTasciyan** [comment]
> When choosing a logo, we should also consider what it will look like as the icon for the nuget package

Definitely

**Comment by vossad01** [comment]
@IUsername I am not a designer, so this may be a very stupid question, but would there be any way (or merit) to work an "F" and an "A" (or otherwise include the name) into the small/square logo that you mocked up for the NuGet display?  I guess just for the sake of trying to tie the logo with the name.

**Comment by dennisdoomen** [comment]
It's safe to conclude that @IUsername's [proposal](https://github.com/fluentassertions/fluentassertions/issues/533#issuecomment-279187349) is going to be the official v5 logo. I absolutely love it and would be honored to be able to use it for v5.

**Comment by adamvoss** [comment]
@IUsername would you be able to provide the logo assets in vector form?

**Comment by IUsername** [comment]
@dennisdoomen Great! Glad you like it and I look forward to seeing it in use.

@adamvoss I have included an Illustrator and SVG format of the logo. If you need any other formats or modifications just let me know.

[fluent_assertions_final.zip](https://github.com/fluentassertions/fluentassertions/files/1046296/fluent_assertions_final.zip)

**Comment by adamvoss** [comment]
@IUsername How easy is it to provide the alternative layouts as well?

The main layout takes a bit more vertical space than is ideal for the current layout of the website.  I would still use it for the image on the [main page of the website](https://github.com/fluentassertions/fluentassertions/blob/master/docs/index.md) and stick it into README.md.

I am thinking the first alternative where the graphic and text are side-by-side would be best for the header; that or making the graphic part a bit smaller could work.  The one where the graphic has an extra white border seems pop in the dark theme for NuGet.

**Comment by IUsername** [comment]
@adamvoss No problem. I've attached a number of the alternative layouts.

[fluent_assertions_full_set.zip](https://github.com/fluentassertions/fluentassertions/files/1046412/fluent_assertions_full_set.zip)

**Comment by adamvoss** [comment]
![screen shot 2017-06-01 at 21 54 51-fullpage](https://cloud.githubusercontent.com/assets/965439/26709011/37a4a322-4715-11e7-86b5-7601c9355798.png)

@dennisdoomen @IUsername

**Comment by dennisdoomen** [comment]
The one in the header is beautiful. The one next to the installation section is weird though. 

Maybe those section headers should use that red/orange color of the logo.

**Comment by adamvoss** [comment]
The one within the page once had its place, but it is probably simplest just to remove it now.

**Comment by adamvoss** [comment]
This color seems somewhat sensitive to monitor calibration.

I do _not_ have nice monitors and on mine this is a very strong red/red-orange; almost like the sort you would use for marking corrections.  It seems best on white with plenty of space around it.  I wasn't going to say anything myself but I was partially questioning if the text color in the header needed to changed to be more friendly.

In response to on your comment, I opened up the screenshot on my phone (Galaxy S5) and see it really does look nice.

![image](https://cloud.githubusercontent.com/assets/965439/26712104/983ab48c-472a-11e7-93c3-8c480c190c05.png)

If people say the red looks good I'm happy to make the change.

**Comment by adamvoss** [comment]
![image](https://cloud.githubusercontent.com/assets/965439/26712523/d7d11c9c-472c-11e7-995e-aa9f377c19db.png)
?

**Comment by dennisdoomen** [comment]
Love it. 

>The nav links should probably be red then too?

Nah

**Comment by dennisdoomen** [comment]
@adamvoss are you still planning to apply this styling to the docs?

**Comment by dennisdoomen** [comment]
Since the contest itself has been completed with the awesome logo of @IUsername.

**Comment by adamvoss** [comment]
@dennisdoomen My work was merged into the the `develop` branch.  https://github.com/fluentassertions/fluentassertions/issues/533#issuecomment-305571836 indicated that the new logo would be for v5 so the work was done in `develop` and will become live when `develop` lands in master.

**Comment by dennisdoomen** [comment]
@IUsername are you willing to disclose some information about yourself? I'm working on a blog post for the final release of Fluent Assertions and I'd like to be able to name you with more than just _IUsername_

**Comment by IUsername** [comment]
That would be great. I updated my bio with some details. If you want more just let me know.

**Comment by dennisdoomen** [comment]
@IUsername check out https://www.fluentassertions.com

**Comment by IUsername** [comment]
@dennisdoomen Looks nice and thanks for the logo attribution tag in the corner.
