### ISSUE TITLE
Add ability to time an action

### ISSUE THREAD

**Issue by carlin-q-scott** [fluentassertions/fluentassertions#537]
I had a need to ensure a method took a certain amount of time which I know is a pretty unusual use case but here's [the code](https://gist.github.com/carlin-q-scott/705a69a336d84271455a80bdbb55141f) if you want to include it in the framework. It also supports fluent chaining which is lacking in the other action assertions and I can see why as it makes it difficult to know when to invoke the action.

**Comment by jnyrup** [comment]
We have improved this area for the upcoming 5.0.0 in #653 and added 
```csharp
BeCloseTo(TimeSpan expectedDuration, TimeSpan precision, string because = "", params object[] becauseArgs)
```

Here are two extracts from the tests of what this enables you to assert.

```csharp
subject.ExecutionTimeOf(s => s.Sleep(510)).Should().BeCloseTo(500.Milliseconds(), 50.Milliseconds());
someAction.ExecutionTime().Should().BeCloseTo(500.Milliseconds(), 50.Milliseconds());
```

**Comment by dennisdoomen** [comment]
@carlin-q-scott is that what you meant?

**Comment by jnyrup** [comment]
@sw-carlin seems you switched to a new GitHub profile?

**Comment by carlin-q-scott** [comment]
I use both profiles but I'm on my personal one way less frequently. Yes, the 5.0 release addressed my ask.
