### ISSUE TITLE
HaveDefaultConstructor throws InvalidOperationException if the type has both a default constructor and a static constructor

### ISSUE THREAD

**Issue by joshstrohminger** [fluentassertions/fluentassertions#540]
I've created an example of this occuring here: https://github.com/joshstrohminger/FluentAssertionsExample

When using `HaveDefaultConstructor` on a type that has a static constructor an `InvalidOperationException` is thrown with message "Sequence contains more than one matching element".
```stack
    at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       at FluentAssertions.Common.TypeExtensions.GetConstructor(Type type, IEnumerable`1 parameterTypes) in C:\Users\js1215\Documents\fluentassertionsjosh\Src\Core\Common\TypeExtensions.cs:line 345
       at FluentAssertions.Types.TypeAssertions.HaveConstructor(IEnumerable`1 parameterTypes, String because, Object[] becauseArgs) in C:\Users\js1215\Documents\fluentassertionsjosh\Src\Core\Types\TypeAssertions.cs:line 647
       at FluentAssertions.Types.TypeAssertions.HaveDefaultConstructor(String because, Object[] becauseArgs) in C:\Users\js1215\Documents\fluentassertionsjosh\Src\Core\Types\TypeAssertions.cs:line 666
```
This occurs because `TypeExtensions.GetConstructor` gets constructors using `AllMembersFlag` which includes `BindingFlags.Static` (see snippet below). It then calls `SingleOrDefault` on the `ConstructorInfo[]` and finds two constructors with no arguments:
1. _**ctor()**_ the default constructor we're looking for
2. _**cctor()**_ the static constructor we're not interested in, at least for this test

Both are no-arg constructors but when people say _DefaultConstructor_ I think they're usually referring to the _ctor_ and not the _cctor_.

The simpler fix would be to use `PublicMembersFlag` (which includes `BindingFlags.NonPublic` despite the name)
```c#
private const BindingFlags PublicMembersFlag =
    BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance;

private const BindingFlags AllMembersFlag =
    PublicMembersFlag | BindingFlags.NonPublic | BindingFlags.Static;
```
The only difference is that it doesn't include `BindingFlags.Static`. This fixes `HaveDefaultConstructor` for this scenario (not currently covered by a test case) but would prevent the use of `HaveConstructor` when checking for a static constructor (also not covered by a test case), but I think that's a good thing. I think there should be a newmethod `HaveStaticConstructor` which would call a new extension method `TypeExtensions.GetStaticConstructor` that would retrieve a no-arg constructor using `BindingFlag.Static | BindingFlag.NonPublic`. 

I plan on submitting a pull request to update the flags used and another to add the `HaveStaticConstructor` method unless people think otherwise.

**Comment by dennisdoomen** [comment]
Can this be closed now?

**Comment by joshstrohminger** [comment]
Yes. I'll submit a pull request for `HaveDefaultConstructor` once you're accepting them for more than just bugs.
