### ISSUE TITLE
Suggestion: Extract FluentValidations.com into its own fluentvalidations.github.io repo

### ISSUE THREAD

**Issue by SeanKilleen** [fluentassertions/fluentassertions#542]
Hi all,

I wanted to submit this for consideration; likely a low priority request. 

When authoring #541, I initially had trouble finding the web site because it's kept as an entirely separate gh-pages branch which is greatly diverged from master.

I'd suggest moving this into its own `fluentvalidations.github.io` repo, which is recognized as a user's repo by github page pages.

Once that's done, the web site could evolve independently and it would be easier for folks to submit PRs. 

If you'd like to create the repo under the org, I'd be happy to organize the move myself; you'd just have to update the CNAME pointers at the end. 

Thanks for your consideration!

**Comment by dennisdoomen** [comment]
Does that even work? It would become a repo that only contains the site content, correct?

**Comment by SeanKilleen** [comment]
Correct! It's how I'm running Sean Killeen.com, via seankilleen.github.io. since the org name is fluentassertions, it should work just fine.

**Comment by dennisdoomen** [comment]
Done!

**Comment by SeanKilleen** [comment]
@dennisdoomen nice! Congrats. :) I opened https://github.com/fluentassertions/fluentassertions.github.io/issues/1 to see if I could help with the site currently 404ing. Might just need time to propagate though.

Thanks for making this change; it'll make the site easier to find and update in the future!
