### ISSUE TITLE
ValueTuples don't work with Should().Be()

### ISSUE THREAD

**Issue by bradphelan** [fluentassertions/fluentassertions#544]
If you try

    (10,20,30).Should().Be((10,20,30))

then you get an error like 

> At least one object must implement IComparable.
>    at System.Collections.Comparer.Compare(Object a, Object b)
>    at System.ValueTuple`2.CompareTo(ValueTuple`2 other)

This doesn't seem quite right.

tag: c#7 vs2017

**Comment by dennisdoomen** [comment]
So does a tuple implement any form of value comparison?

**Comment by SaroTasciyan** [comment]
@bradphelan Couldn't reproduce it with .NET v4.6.2, FluentAssertions v4.19.2, System.ValueTuple v4.0.1.

@dennisdoomen `ValueTuple` implements `IComparable` and ends up in `ComparableAssertions` which seems fine. Reporting also seems fine (at least for primitives).

**Comment by dennisdoomen** [comment]
@SaroTasciyan did you try it with C# 7.0?

**Comment by SaroTasciyan** [comment]
@dennisdoomen yes I tried it with C# 7 (and VS2017). 
This syntax - comma separated values for defining `Tuple` - is a new feature of C# 7. As far as I know; in order to make it compile you need the `System.ValueTuple` nuget package. Otherwise, you can not use the syntax. However, you can still use the old school reference type `Tuple`.

Following tests are passing;
```c#
[Fact]
public void EqualValueTuplesShouldBe()
{
    (int, int, int) valueTuple = (10, 20, 30);

    valueTuple.Should().Be((10, 20, 30));
    (10, 20, 30).Should().Be((10, 20, 30));
}

[Fact]
public void UnequalValueTuplesShouldBe()
{
    void LocalFunction() => (1, 2, 3).Should().Be((2, 3, 4));

    ((Action)LocalFunction).ShouldThrow<Exception>()
        .WithMessage("Expected*(2, 3, 4)*found*(1, 2, 3)*");
}
```

Off-topic note; I couldn't use `ShouldThrow` extension without casting `LocalFunction` to `Action`

**Comment by SaroTasciyan** [comment]
@dennisdoomen Resharper was misleading me sorry, I'm a bit confused now. Local value tuple assertion ends up in `ComparableAssertions` and inline tuple assertion ends up in `ObjectAssertions` altho `(10, 20, 30).CompareTo((10, 20, 30))` still compiles. Wierd. All the assertions above are still fine.

I believe this requires a bit of investigation, at the moment I can not tell if (1, 4) is greater than (2, 3) or not.

**Comment by bradphelan** [comment]
Here is weird for you. It took me a bit to figure out the exact constellation to see the error but you will find the following quite strange and I'm not sure it has anything to do with fluentassertions.

![image](https://cloud.githubusercontent.com/assets/17650/23845425/525b5fbc-07c8-11e7-8672-08c611375ece.png)

```
    public class TupleTest
    {
        struct A
        {
            public int K;
        };

        [Fact]
        public void EqualValueTuplesShouldBeFails()
        {
            var a = new A();
            (A, int, int) valueTuple() => (a, 20, 30);

            valueTuple().Should().Be((a, 20, 30));
        }

        [Fact]
        public void EqualValueTuplesShouldBePasses()
        {
            var a = new A();

            (a,20,30).Should().Be((a, 20, 30));
        }
    }
```

**Comment by bradphelan** [comment]
This adds some more insight.

![image](https://cloud.githubusercontent.com/assets/17650/23846422/afb8771c-07cd-11e7-92b9-7fd66472f316.png)


```
    public class TupleTest
    {
        struct A
        {
            public int K;
        };

        [Fact]
        public void DirectComparisonThrowsException()
        {
            var a = new A();
            var v = global::System.Collections.Generic.Comparer<object>.Default;

            // This generates
            //  Expected object to be (Weingartner.Utils.Spec.TupleTest+A, 20, 31), but found (Weingartner.Utils.Spec.TupleTest+A, 20, 30).
            v.Compare((a, 20, 30), (a, 20, 30)).Should().Be(0);
        }


        [Fact]
        public void ComparisonThrowsException()
        {
            var a = new A();
            (A, int, int) valueTuple() => (a, 20, 30);

            // This generates
            //  Expected object to be (Weingartner.Utils.Spec.TupleTest+A, 20, 31), but found (Weingartner.Utils.Spec.TupleTest+A, 20, 30).
            valueTuple().Should().Be((a, 20, 30));
        }

        [Fact]
        public void ComparisonPasses()
        {
            var a = new A();

            // This passes
            (a, 20, 30).Should().Be((a, 20, 30));
        }

        [Fact]
        public void ComparisonFails()
        {
            var a = new A();

            // This fail with
            // Expected object to be (Weingartner.Utils.Spec.TupleTest+A, 20, 31), but found (Weingartner.Utils.Spec.TupleTest+A, 20, 30).
            (a, 20, 30).Should().Be((a, 20, 31));
        }
    }

```

**Comment by dennisdoomen** [comment]
Could be related to the problem mentioned in this thread https://github.com/fluentassertions/fluentassertions/releases/tag/5.0.0-beta.3

**Comment by dennisdoomen** [comment]
I've just tried your last examples on `release-5.0` and they all consistently fail until I have `A` implement `IComparable<A>`.

**Comment by dennisdoomen** [comment]
Not reproducable.

**Comment by bradphelan** [comment]
I can confirm the error no longer appears
