### ISSUE TITLE
When comparing dictionary objects of different items count, final result does not show which items are missing.

### ISSUE THREAD

**Issue by quldude** [fluentassertions/fluentassertions#557]
Lets say I have 2 dictionary objects: Dictionary<string, object> dictA, Dictionary<string, object> dictB. I'm doing the following when comparing them:

`dictB.ShouldBeEquivalentTo<T>(dictA);`

When the total items do not match, I just get a message " Expected member dictB to be a dictionary with 26 item(s), but found 23 item(s).". How can I make it show what items are missing between the two?

**Comment by raghav710** [comment]
If there is no way already to do this, I would like to take it up. Shall I ? :)

**Comment by dennisdoomen** [comment]
By all means, go ahead.

**Comment by raghav710** [comment]
Thanks :) 
I'd like to know in what format to display the missing keys.
Here are some options:
1. Exhaustive list 
  DictA has keys A, B, C, D which are missing in dictB
  DictB has keys X, Y, Z which are missing in dictA
2. trimmed list with ellipses
 Keys A, B, C.... are missing from dictB
 Keys Z, X, Y... are missing from dictA
3. Show only the missing keys with respect to the dictionary with lesser items
Eg; if dictB has 23 and dictA has 26 items only show the keys in dictA that are not in dictB

**Comment by raghav710** [comment]
I need some help getting the environment setup (this is my first PR to FA :) ). is there a document that will guide me through it?
running ./build.ps1 fails with "Error: Cake.Core.CakeException: MSBuild: Could not locate executable"

**Comment by dennisdoomen** [comment]
Yeah, you need to use the *master* branch right now. *develop* doesn't build yet since I'm working on a major new version.

**Comment by dennisdoomen** [comment]
I propose option 2.

**Comment by krajek** [comment]
I would like to implement that, which branch I should target?

**Comment by dennisdoomen** [comment]
Release-5.0
