### ISSUE TITLE
Suggested improvement: Reduce intellisense spam

### ISSUE THREAD

**Issue by faeriedust** [fluentassertions/fluentassertions#560]
Replace x.Should() with new Assert(x)

That way i don't have to see .Should() in my intellisense for every single variable.

I'm only typically testing one variable per test method, so I don't think i should see .Should, etc on every other variable's intellisense lol

I actually uninstalled because of this. Looked like really nice library otherwise though

**Comment by dennisdoomen** [comment]
Thank you for your comment. But the whole point of the library is to provide a fluent API on your test variables.

**Comment by dennisdoomen** [comment]
Thank you for your comment. But the whole point of the library is to provide a fluent API on your test variables.

**Comment by faeriedust** [comment]
You don't lose that though.. You can keep all the current fluent methods, just reduce the number
of/make more explicit the starting points.

The one challenge I can see is that the current .Should extension method assists in figuring out the generic type parameters implicitly..  So maybe it's not as simple I was thinking.. ~_~ I think there is a way though, I'll have a look later..

Simply reducing the number of these methods that show up for nontest variables would be very helpful though.  e.g .ShouldBeEquivalentTo can be .Should().BeEquivalentTo()

The fluent API off test variables is great.  My issue is just that there are far too many extension methods off the variables that are not under test.

Anyways, just my thought for you.  Good luck :)

**Comment by dennisdoomen** [comment]
I don't really see the issue, nor do I know how to fix this.
