### ISSUE TITLE
Improvement: Fail Message with parameterized Collection Should Contain

### ISSUE THREAD

**Issue by matthiaslischka** [fluentassertions/fluentassertions#564]
Hi

Wrote myself an extension method to keep code clean
```c#
public static AndWhichConstraint<GenericCollectionAssertions<ValidationFailure>, ValidationFailure> ShouldContainErrorMessage(this ValidationException validationException, string errorMessage)
{
    return validationException.Errors.Should().Contain(e => e.ErrorMessage == errorMessage);
}
```
But when the Assertion fails it displays
`Collection {BlaFooBar} should have an item matching (e.ErrorMessage == value`

It would be great if it could replace "value" with the actual errorMessage that is used. Actually, I'm not sure why it does not work out-of-the-box. Maybe I'm supposed to write it in an other way. sry if that's the case.

BR,
Matthias

**Comment by dennisdoomen** [comment]
I suspect it happens because it compiles to an expression that relies on an external parameter. The only thing I can think of right now is to wrap that code is a `using (var scope = new AssertionScope())`, extract the validation error yourself using `Discard` and then throw a custom exception using `Execute.Assertion.FailWith`.

**Comment by matthiaslischka** [comment]
Thx for your input. :)
I ended up with this solution which unfortunately changes the result to a `StringCollectionAssertions` typed `AndWhichConstraint`  - just a small flaw I gladly take for getting a good error description again:
```c#
public static AndWhichConstraint<StringCollectionAssertions, string> ShouldContainErrorMessage(this ValidationException validationException, string errorMessage)
{
    validationException.Should().NotBeNull();
    return validationException.Errors.Select(e => e.ErrorMessage).Should().Contain(errorMessage);
}

```
I probably will look into this when I find time. Not offended if someone fixes that before I find the time to do so. :)

BR Matthias

**Comment by dennisdoomen** [comment]
OK, so we can close it.
