### ISSUE TITLE
Assertion hangs trying to format unfinished Task

### ISSUE THREAD

**Issue by ezsilmar** [fluentassertions/fluentassertions#566]
This test hangs:

```c#
using System.Threading.Tasks;
using FluentAssertions;
using NUnit.Framework;

namespace FooBarTests
{
    [TestFixture]
    internal class Foo_Tests
    {
        [Test]
        public void Test_foo()
        {
            var foo = new Foo();
            foo.Should().BeNull();
        }

        private class Foo
        {
            public Task<int> Bar => Task.Delay(100000).ContinueWith(_ => 42);
        }
    }
}
```

The reason is a formatter which tries to display a string representation of `Foo` instance. It traverses all public properties recursively and stops trying to get `foo.Bar.Result` or some other Task property which requires waiting.

Possible fix is a special treatment of Task instances during formatting, for instance `IsCompleted` property can be checked.

**Comment by dennisdoomen** [comment]
Another nice catch. It would mean FA needs to understand properties of type `Task?`. Why would `Foo` have a public property like that?

**Comment by ezsilmar** [comment]
In my case Foo is used as a synchronization object in complex async code. It has a `TaskCompletionSource` inside, and a public property to wait for "completion" event.

**Comment by dennisdoomen** [comment]
Hmm, that does make sense. Will be a bit hard to fix that in 4.19.x since not all frameworks support `Task<T>`. Need to investigate.

**Comment by dennisdoomen** [comment]
For the time being, you can create a custom formatter. See this blog post http://www.continuousimprover.com/2016/05/the-definitive-guide-to-extending.html

**Comment by ezsilmar** [comment]
Thank you for the link, will try it. As for `Task<T>`, it hangs on non-generic version too.

**Comment by ezsilmar** [comment]
A simple fix I used:

```c#
internal class TaskValueFormatter : FluentAssertions.Formatting.IValueFormatter
{
    public bool CanHandle(object value)
    {
        return value is Task;
    }

    public string ToString(object value, bool useLineBreaks, IList<object> processedObjects = null, int nestedPropertyLevel = 0)
    {
        var task = value as Task;
        return task.Status.ToString();
    }
}
```

Initialization:

```c#
public class MyTestBase
{
    private static readonly TaskValueFormatter taskValueFormatter = new TaskValueFormatter();

    static MyTestBase()
    {
        FluentAssertions.Formatting.Formatter.AddFormatter(taskValueFormatter);
    }
}
```
