### ISSUE TITLE
Upgrade to support .NET 4.7

### ISSUE THREAD

**Issue by vincentw56** [fluentassertions/fluentassertions#567]
Please upgrade to support .NET 4.7.

**Comment by dennisdoomen** [comment]
The upcoming v5 will allow this.

**Comment by dennisdoomen** [comment]
BTW, what prevents you from using FA 4.19 in a .NET 4.7 project?

**Comment by vincentw56** [comment]
Actually, since I've opened this, I haven't had any issues using it in 4.7. I forgot I still had this open.

**Comment by dennisdoomen** [comment]
No problem. Thanks for letting me know.
