### ISSUE TITLE
Support local functions in C# 7

### ISSUE THREAD

**Issue by pipedreambomb** [fluentassertions/fluentassertions#580]
Unless I'm missing something obvious, FluentAssertions doesn't support local functions in C#7. I don't know if this is just impossible, but I didn't see it in the issue tracker so I'm raising it.

For example, I'd like to write code like this:
   ```
[Test]
public void Fluent_AAA_throws()
{
    // Arrange
     var sut = new SystemUnderTest();
  
    // Act
    void Act() => sut.Whatever(null);

    // Assert
     Act.ShouldThrow<ArgumentNullException>();
}
```

Thanks for all your great work, etc. George

**Comment by adamvoss** [comment]
You can do this:

```c#
[Test]
public void Fluent_AAA_throws()
{
 // Arrange
  var sut = new SystemUnderTest();

 // Act
 void Act() => sut.Whatever(null);

 // Assert
  ((Action)Act).ShouldThrow<ArgumentNullException>();
}
```

Beyond that, there is nothing FA could do to support this (besides a compiler extension).  `Act` above is a method not an object.  Your attempt to call `ShouldThrow` on it is the same as trying to call `Fluent_AAA_throws.ToString()`.  To make this work the C# language would need to be modified to have an implicit conversion from methods to `Func<...>/Action` object when a method name is followed by a `.`.

**Comment by dennisdoomen** [comment]
I agree with @adamvoss. A local function is not an `Action`, nor does it support extension methods.

**Comment by jmyersmsft** [comment]
Users who find this issue via web searches and want to use local functions like this while keeping more of the fluent style could do something like
```cs
private static Action Invoking(Action action) => action;

[Test]
public void Fluent_AAA_throws()
{
 // Arrange
  var sut = new SystemUnderTest();

 // Act
 void Act() => sut.Whatever(null);

 // Assert
 Invoking(Act).ShouldThrow<ArgumentNullException>();
}
```

Looks prettier than the cast at least. FA could provide such an `Invoking` method that users could use with `using static`, but I don't think it's likely users would even discover such a thing, so probably not worth it.
