### ISSUE TITLE
Add test projects for all supported test frameworks

### ISSUE THREAD

**Issue by dennisdoomen** [fluentassertions/fluentassertions#587]
In addition to the MSTestV2 and XUNit.Specs projects, we need projects for all supported frameworks so we know for sure FA will raise the right exception type for that framework.

**Comment by jnyrup** [comment]
Some notes:
* Next version of Cake will have [support for MSpec](https://github.com/cake-build/cake/pull/1873)
* There is an NSpec plugin for Cake, but it references an old version of Cake. I've opened an [issue](https://github.com/app-iron/Cake.NSpec/issues/4)

**Comment by dennisdoomen** [comment]
We don't need to use Cake's plug-in model, right? I mean, when we were still using PSake, we would just invoke whatever .exe we needed to run. In fact, this is one of the things I dislike about Cake. The plug-in model introduces too much magic (and thus, too much coupling).

**Comment by jnyrup** [comment]
I tried to complete MbUnit too, but I wasn't satisfied (at all).
I could not find any MbUnit-v2 packages on NuGet

I could only find unofficial builds of v3 on NuGet:
* https://www.nuget.org/packages/mbunit/
* https://www.nuget.org/packages/Gallio_MbUnit/
* https://www.nuget.org/packages/GallioBundle/

In MbUnit-v2 you could apparently create a [self-contained test runner](https://matt.berther.io/2005/10/18/a-test-runner-for-mbunit/), but for v3 it seems you should run it through Gallio, but then Gallio exceptions are thrown.

Note:
MbUnit-v3 had its latest release/commit 5.5 years ago and the issue tracker is mainly about people trying to get it to work on VS2015 but switching to [nx]unit.

**Comment by dennisdoomen** [comment]
We can decide to just skip that one...
