### ISSUE TITLE
Use the caller context / stackframe to preset the context

### ISSUE THREAD

**Issue by dennisdoomen** [fluentassertions/fluentassertions#588]
* [x] Fix all unit tests
* [x] Rebase on the release branch and fix the remaining unit tests
* [x] Fix Xunit runner incompatibilities
* [x] Allow extensions to also participate gracefully in the caller context logic.

**Comment by tavisca-pushkar** [comment]
@dennisdoomen Is this related to #498 ?

**Comment by dennisdoomen** [comment]
@tavisca-pushkar yes, it is.

**Comment by dennisdoomen** [comment]
Documentation will be updated separately. 

An important change is that this only works correctly if the unit tests are build without optimization and inlining (i.o.w. debug builds).
