### ISSUE TITLE
 Add new logo to the Nuget package, repo and website

### ISSUE THREAD

**Issue by dennisdoomen** [fluentassertions/fluentassertions#591]
#533

**Comment by adamvoss** [comment]
See PRs #574, #575, #576 

Note: unless something changed since I last looked, the NuGet package will need to be done by @dennisdoomen because that is configured via the NuGet website.

**Comment by dennisdoomen** [comment]
> Note: unless something changed since I last looked, the NuGet package will need to be done by @dennisdoomen because that is configured via the NuGet website.

Needs to be done using the `iconUrl` attribute of the package. See https://docs.microsoft.com/en-us/nuget/schema/nuspec

**Comment by dennisdoomen** [comment]
Added a new logo to the repo and updated the .nuspec.
