### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by dennisdoomen** [fluentassertions/fluentassertions#592]
Update the docs with all the breaking changes, plus all the new APIs added by contributors.
  
* [x] Review the docs
* [x] Add a section on caller identification and the need for debug builds
* [x] Add some short introduction of FA to the main website page
* [x] Update website examples
* [x] New event monitoring API
* [x] Add extensibility section as separate page based on the blog post
* [x] Verify all API changes from the list below

**Comment by jnyrup** [comment]
I'm working on this.

**Comment by dennisdoomen** [comment]
Is this now done?

**Comment by jnyrup** [comment]
No - but I haven't been working on this issue for the past month.

I intentionally didn't touch the `IValueFormatter`, `BeEquivalentTo` and `Monitor` parts as they seemed to be WIP and I wasn't very familiar with those parts of the code.

For the remaining `TypeAssertions`, would it be fine with you that I don't create complete examples, but just list them?

**Comment by dennisdoomen** [comment]
Sure. I'll do a review myself of the whole document after I finally finish #588
