### ISSUE TITLE
Replacing HaveCount(predicate)

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#615]
Currently there are two ways to assert something about the number of elements in a collection.
* `HaveCount(int)` for asserting an exact count,
* `HaveCount(countPredicate)` for everything else.

I think FA should include methods for the five missing comparison operators:
* `NotHaveCount(int)`
* `HaveCountGreaterThan(int)`
* `HaveCountGreaterOrEqualTo(int)`
* `HaveCountLessThan(int)`
* `HaveCountLessOrEqualTo(int)`

Maybe I'm missing out on something, but with the five methods added the predicate overload becomes superfluous.

So If we:
* Provide the five methods,
* and these cover all use cases, 
* and we accept a breaking change
then we can remove `HaveCount(predicate)`.

**Comment by dennisdoomen** [comment]
On the other hand, with the predicate you can cover all of them. And even with those five specific overloads, you still can't predict all possible usages of the predicate.

**Comment by jnyrup** [comment]
Forget about my proposal to remove `HaveCount(predicate)`.
I just came to think of possible usages that requires it such as `HaveCount(IsEven)` or `HaveCount(IsPowerOf2)`.

How do you think about having the five methods included?
I guess these covers the most common predicates - at least all my usages of HaveCount(predicate).

**Comment by dennisdoomen** [comment]
Sure, those five do make sense (but are not a high priority for me right now)
