### ISSUE TITLE
AssertionScope.Succeeded returns false even if the assertion succeeds

### ISSUE THREAD

**Issue by aptester** [fluentassertions/fluentassertions#617]
Consider the following snippet of code:
string hello = "Hello";
using (var scope = new AssertionScope())
{
      hello.Should().Be("Hello");
      bool succeeded = scope.Succeeded;
}

On executing the above code, the value of the succeeded variable comes back as false. As per me, it should be true. I can send out a PR, if this is a valid issue.

**Comment by dennisdoomen** [comment]
Technically, you're right. However, that particular assertion is not using the `ForCondition`, hence it is not affecting the `Succeeded` flag. Moreoever, it's primarily used for chaining multiple conditions in a single fluent API call *within* assertion extensions. I'm pretty sure there are more existing assertions that don't properly use the `AssertionScope`. Not sure if it's useful to fix this.

**Comment by aptester** [comment]
Ok, I was trying to use the Succeeded property to determine whether nested AssertionScopes passed or failed so that I could make the parent AssertionScope fail.. if any of the child scopes failed. A simple example of what I was trying to accomplish: 
[Fact]
public void Test2()
{
    bool passed = true;
    using (var scope = new AssertionScope("Parent"))
    {
        using (var nestedScope = new AssertionScope("Child 1"))
        {
            1.Should().Be(2);
            if (passed)
            {
                passed = AssertionScope.Current.Succeeded;
            }
        }
        using (var nestedScope = new AssertionScope("Child 2"))
        {
            "Two".Should().Be("2");
            if (passed)
            {
                passed = AssertionScope.Current.Succeeded;
            }
        }
        scope.ForCondition(passed == true).FailWith("Parent Scope verification has errors");
    }
}

How would you suggest I go about it?

**Comment by aptester** [comment]
@dennisdoomen did you get a chance to look at the above code snippet?

**Comment by dennisdoomen** [comment]
Not yet. Just came back from holiday.

**Comment by aptester** [comment]
@dennisdoomen hoping you can suggest an alternate method to fail the parent AssertionScope if any of the nested AssertionScope fails.

**Comment by dennisdoomen** [comment]
I'm still not sure what you're trying to accomplish. The `AssertionScope` is intended to run multiple assertions and get the failures in a one go. 

That `Succeeded` property was introduced to build more complicated assertions such as:

```
            Execute.Assertion
                .BecauseOf(because, becauseArgs)
                .WithExpectation("Expected type to be {0}{reason}, ", expectedType.FullName)
                .Given(() => Subject.Cast<object>())
                .ForCondition(subject => subject.All(x => x != null))
                .FailWith("but found a null element.")
                .Then
                .ForCondition(subject => subject.All(x => expectedType == x.GetType()))
                .FailWith("but found {0}.", subject => $"[{string.Join(", ", subject.Select(x => x.GetType().FullName))}]");
```

**Comment by aptester** [comment]
Dennis, thanks for the example for the use of the Succeeded property. Let me try and state my problem a little more clearly. I have a bunch of assertion scopes which work as expected. I was trying to nest these AssertionScopes under a 'parent' AssertionScope and get this parent assertionScope to fail if one or several 'child' AssertionScope objects failed. A kind of AssertionScope failure chaining..

**Comment by dennisdoomen** [comment]
That part I understood, but what I don't understand is _why_. What are you really trying to accomplish?

**Comment by jnyrup** [comment]
Closed due to inactivity, please re-open if you have more to add.
