### ISSUE TITLE
Object not being monitored error but MonitorEvents called

### ISSUE THREAD

**Issue by thnk2wn** [fluentassertions/fluentassertions#628]
I'm calling MonitorEvents but it's acting like it hasn't been called or as if the command was disposed (neither of which are the case). Not sure if I'm doing something wrong or if this is an issue. Version 5.0.0-beta0001

![monitorevents](https://user-images.githubusercontent.com/120529/29795056-7c1686a4-8bff-11e7-85bb-d6bfb0e239cc.png)

Message: System.InvalidOperationException : Object <GalaSoft.MvvmLight.Command.RelayCommand> is not being monitored for events or has already been garbage collected. Use the MonitorEvents() extension method to start monitoring events.

    vm.SendNowCommand.MonitorEvents();

    // Act.
    await vm.DeleteOrderItemCommand.ExecuteAsync(vmItemToDelete);

    // Assert.
    vm.SendNowCommand.ShouldRaise("CanExecuteChanged");

It also happens with this code, even on version 4.19.4 stable:

        vm.MonitorEvents();

        // Act.
        await vm.DeleteOrderItemCommand.ExecuteAsync(vmItemToDelete);

        // Assert.
        vm.ShouldRaisePropertyChangeFor(x => x.IsOrderEmpty);

**Comment by thnk2wn** [comment]
Actually it appeared the ShouldRaisePropertyChangedFor was working before installing the pre-release (to get ShouldRaise("Eventname") to work) but now it also gives me the same error in this version doing the same thing:

        vm.MonitorEvents();

        // Act.
        await vm.DeleteOrderItemCommand.ExecuteAsync(vmItemToDelete);

        // Assert.
        vm.ShouldRaisePropertyChangeFor(x => x.IsOrderEmpty);

**Comment by thnk2wn** [comment]
Not sure if it matters but this is in a UWP unit test app targeting platform version 10.0.15063.0 and using x64, xunit 2.3.0-beta3-build3705.

**Comment by dennisdoomen** [comment]
This still hasn't changed yet in beta 1. I'm [working on this](https://github.com/fluentassertions/fluentassertions/pull/625) as we speak.

**Comment by dennisdoomen** [comment]
Resolved by #625
