### ISSUE TITLE
Fluent Assertions for ASP.NET Core

### ISSUE THREAD

**Issue by piotrpMSFT** [fluentassertions/fluentassertions#629]
@dennisdoomen we're building up a few FA's that target ASP.NET Core types. I don't think these make sense in the core FA package as it would unnecessarily grow the dependencies of that package. Is there a story for shipping assertions that target non-core types?

**Comment by dennisdoomen** [comment]
What are you proposing? A separate package under the FA org?

**Comment by kevinkuszyk** [comment]
@piotrpMSFT I maintain the Fluent Assertions for MVC Core package over at [kevinkuszyk/FluentAssertions.AspNetCore.Mvc](https://github.com/kevinkuszyk/FluentAssertions.AspNetCore.Mvc).  If you'd like to add your assertions, feel free to open a PR.

> What are you proposing? A separate package under the FA org?

@dennisdoomen are you considering bringing some of the community extensions into the FA org?  If so, I have a few we could transfer in.  I'd be happy to stay on as a maintainer of them.

**Comment by piotrpMSFT** [comment]
@dennisdoomen @kevinkuszyk this is exactly in line with what I was thinking. As much as possible, I'd like to see new assertions added to the main package. However, when those assertions will require expanding the dependency graph of that package then they should likely be packaged separately. I think the FA community would benefit from a central directory of such extensions, as well as some level of curation [naming conventions, implementation patterns, test thoroughness, documentation, etc] that we've come to expect from the central package.

I think it's up to @dennisdoomen to decide how he'd like to see such packages be developed. I think that separate packages under the FA org make a lot of sense, though I'd love for their docs, etc. to be unified with the core package docs. Having the packages shipped from a common NuGet account would also be nice.

@kevinkuszyk cool project! let's see where this goes and how we can collaborate.

**Comment by dennisdoomen** [comment]
Then let's do that! 

PS. I try to model my packages these days based on https://www.slideshare.net/dennisdoomen/build-libraries-not-frameworks. This is also why my other OSS project has so many packages: https://github.com/liquidprojections/

**Comment by kevinkuszyk** [comment]
@dennisdoomen I'll open a new issue to track moving the community extensions into FA org, so we can keep this on focused on ASP.NET Core support.

**Comment by dennisdoomen** [comment]
So do we need to keep this one open?

**Comment by kevinkuszyk** [comment]
@dennisdoomen fine with me to close.
