### ISSUE TITLE
ShouldBeEquivalentTo() succeeds even though objects have different values

### ISSUE THREAD

**Issue by udlose** [fluentassertions/fluentassertions#631]
I'm using 4.19.4 (though this happened with 4.19.3). I have 2 HttpResponse messages that I'm comparing.  The object graphs are identical. There is only 1 bool property in the Content.Value's object that differs.  

This passes (it should fail):
`actual.ShouldBeEquivalentTo(expected);`

This fails (as expected):
`actual.Should().Be(expected);`

[actualOutput.txt](https://github.com/fluentassertions/fluentassertions/files/1271605/actualOutput.txt)
[expectedOutput.txt](https://github.com/fluentassertions/fluentassertions/files/1271604/expectedOutput.txt)

I've attached the json representation of the objects.

**Comment by dennisdoomen** [comment]
What's the compile-time type of `actual`?

**Comment by udlose** [comment]
@dennisdoomen - 'actual' is a return value from an awaited Task<HttpResponseMessage> - thus HttpResponseMessage. Expected is a defined HttpResponseMessage.

Here is some of the code:
```
        internal static readonly JsonMediaTypeFormatter Formatter = new JsonMediaTypeFormatter
        {
            SerializerSettings = new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                NullValueHandling = NullValueHandling.Ignore
            }
        };
...
            var actual = await cfcPolicy.ExecuteAsync((context, token) => funcToCauseRetry(), pollyContext, new CancellationToken(), false);  //using App-vNext/Polly

            var testRequest = BuildRequestMessage();
            var expected = new HttpResponseMessage(HttpStatusCode.PartialContent)
            {
                Content = new ObjectContent<FooResponse>(BuildDefaultFooResponse(), Formatter),
                RequestMessage = testRequest
            };

        private HttpRequestMessage BuildRequestMessage()
        {
            return new HttpRequestMessage(HttpMethod.Get, "http://foo")
            {
                Content = new ObjectContent<FooRequest>(_request, Formatter),
            };
        }

```

**Comment by dennisdoomen** [comment]
Then this is expected (although not immediatelly clear). 

`Should().Be()` will do a simple comparison using the object's `Equals` implementation. I suspect `HttpRequestMessage`'s default implementation will just do a reference comparison, which will fail. 

`ShouldBeEquivalentTo` will try to do a deep comparison. But by default, it will only look at the compile-time properties of the object. I suspect that all of these are equal, even though the underlying raw body is not.

**Comment by udlose** [comment]
@dennisdoomen - am I missing something?  When are the properties not compared?  In the example I provided, the object graph is well-defined at compile time.  There is only 1 bool property that is different.  Therefoere, I would expect ShouldBeEquivalentTo to fail.

**Comment by dennisdoomen** [comment]
`HttpResponseMessage.Content` is of type `HttpContent`, which does not expose the body in any way, nor overrides `Object.Equals`.

**Comment by udlose** [comment]
Here is a simplified version that seems to prove there is an issue (unless I have a fundamental misunderstanding of FluentAssertions).  Please clarify if I do - and how I can accomplish this kind of comparison.

```
        internal static readonly JsonMediaTypeFormatter Formatter = new JsonMediaTypeFormatter
        {
            SerializerSettings = new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver(),
                NullValueHandling = NullValueHandling.Ignore
            }
        };

        [Test]
        public void SomeTest()
        {
            //arrange
            HttpResponseMessage message1 = new HttpResponseMessage(HttpStatusCode.PartialContent)
            {
                Content = new ObjectContent<string>("foo", Formatter),
                RequestMessage = new HttpRequestMessage(HttpMethod.Get, "http://foo")
            };
            HttpResponseMessage message2 = new HttpResponseMessage(HttpStatusCode.PartialContent)
            {
                Content = new ObjectContent<string>("foo2", Formatter),
                RequestMessage = new HttpRequestMessage(HttpMethod.Get, "http://foo")
            };

            //assert
            message1.ShouldBeEquivalentTo(message2);  //passes - should fail
            message1.Content.ShouldBeEquivalentTo(message2.Content); //passes - should fail
        }
```

**Comment by dennisdoomen** [comment]
It will indeed try to recursively compare the `Content` and `RequestMessage` properties. However, the `Content` property is of type `HttpContent` which does not expose its body as a property, nor does it override `Equals` to provide some kind of value equality. So FA has no way to determine whether two instances of `HttpContext` are semantically equivalent, other than attempting a simple `Equals` call. 

Alternatively, you can use the FluentAssertion.Json package to compare the two Json strings.

**Comment by udlose** [comment]
sigh. I guess it's an edge case then.  Can I suggest to throw an exception noting that the user is trying to compare objects - some of whose parts cannot be compared for equivalency?  I'd rather have an "in your face" warning about this rather than it silently doing nothing under the covers and appearing as if they are equal.  That is scary.

**Comment by dennisdoomen** [comment]
Ah, because by default, it will look at the declared type only. If you want it to look at the run-time type, use `RespectingRuntimeTypes`.

**Comment by udlose** [comment]
@dennisdoomen - cool. That works.  Certainly, not an obvious solution IMO.  I incorrectly assumed it was the default behavior to examine runtime-types

1. In the future, what should be the "warning signs" that I will need to use this option to get this desired  behavior?
2. When would I not want to look at the runtime-type?  I feel like maybe I should add this everywhere just so I don't get "silently passing" tests that are actually missing equivalency assertions based on runtime types.

**Comment by dennisdoomen** [comment]
1. When it _does_ fail, it'll show the settings and conventions it used. But that wouldn't help you in your specific case. Maybe the documentation should be a bit more clearer. 

2. That's a matter of taste. From the many prior discussions with users, I got the impression that they would expect the declared type to be leading. You could obviously override the defaults through `AssertionOptions.AssertEquivalencyUsing`.

**Comment by dennisdoomen** [comment]
Point 1 has been explained in https://github.com/fluentassertions/fluentassertions/blob/release-5.0/docs/documentation.md#compile-time-types-vs-run-time-types
Point 2 has been documented here https://github.com/fluentassertions/fluentassertions/blob/release-5.0/docs/documentation.md#diagnostics
