### ISSUE TITLE
failing ShouldAllBeEquivalentTo() shows broken exception text if string with curly braces are involved

### ISSUE THREAD

**Issue by bitbonk** [fluentassertions/fluentassertions#634]
The following failing test ...

        [Fact]
        public void Test()
        {
            new[]
            {
                new { Name = "{one}" },
                new { Name = "{two}" }
                
            }.ShouldAllBeEquivalentTo(new[]
            {
                new { Name = "{one}" },
                new { Name = "{zwei}" },
            });
        }

... yields the following exception message:

>Xunit.Sdk.XunitException occurred
>  HResult=0x80131500
>  Message=Expected item[1].Name to be "" with a length of 6, but "" has a length of 5.
>  Expected item[1].Name to be "", but "" differs near "two" (index 1).

Note that the message does not should the expected and actual strings correctly. They are empty. The message should have been:

>Xunit.Sdk.XunitException occurred
>  HResult=0x80131500
>  Message=Expected item[1].Name to be "{zwei}" with a length of 6, but {two}"" has a length of 5.
>  Expected item[1].Name to be "{zwei}", but "{two}" differs near "two" (index 1).

**Comment by dennisdoomen** [comment]
Which version?

**Comment by bitbonk** [comment]
4.15.0
