### ISSUE TITLE
Misspelling 'NotApproximatelly' in new API

### ISSUE THREAD

**Issue by bkoelman** [fluentassertions/fluentassertions#640]
Noticed a spelling error in an added API in the [release notes of 5.0.0 beta1](https://github.com/fluentassertions/fluentassertions/releases/tag/5.0.0-beta.1):

```NotApproximatelly```

should be:

```NotApproximately```

**Comment by dennisdoomen** [comment]
You with your sharp eyes.... 😜

**Comment by bkoelman** [comment]
Oh, now I see the issue was only in the text of release notes. The actual code was already correct. Sorry for bringing this up.

**Comment by dennisdoomen** [comment]
No, not at all. I've updated the release notes.
