### ISSUE TITLE
Type assertion fails if nulls are compared

### ISSUE THREAD

**Issue by psmolinsky** [fluentassertions/fluentassertions#671]
This code passes:
`((string)null).Should().Be(null);`

But this code fails:
`((Type)null).Should().Be(null);`

The error is funny: _Expected type to be \<null\>, but found \<null\>._
Please fix it - make the second code snippet to pass too.

**Comment by jnyrup** [comment]
For null checks I recommend using the designated `BeNull()` or `NotBeNull()`.

If both the actual and expected types just happens to be null, I agree it should not fail.

**Comment by psmolinsky** [comment]
Thanks for suggestion. I've run into this issue because my test was parameterized. The code looke like this:
`foo.BarType.Should().Be(expectedBarType)`.

**Comment by psmolinsky** [comment]
Perfect, thanks for quick fix.
