### ISSUE TITLE
Compare XDocuments?

### ISSUE THREAD

**Issue by drauch** [fluentassertions/fluentassertions#679]
How to properly assert `XDocument` with FluentAssertions?

I tried:

    resultDoc.Should().Be(expectedDoc);

However, I run into a very weird error output:

> Expected XML document to be <node xmlns=\"http://sample.io/nodes/v1\">...</node>, but found <node xmlns=\"http://sample.io/nodes/v1\">...</node>

Both strings look absolutely equal, I don't know what's wrong :(

Also I had to exclude them from the original assertion which used `ShouldBeEquivalentTo` and move it into its own assertion - is there a trick that XDocuments work in the context of `ShouldBeEquivalentTo`?

**Comment by shatl** [comment]
Try https://github.com/xmlunit/xmlunit.net

**Comment by drauch** [comment]
Thanks, I'm using it now instead of fluent assertions. Recommended 👍

**Comment by drauch** [comment]
One more question though: is there a way to "hook" XmlUnit comparison into Fluent assertions for all XDocument properties? Maybe there is a way to register a user-provided comparer for certain data types?

**Comment by dennisdoomen** [comment]
@drauch You can create your own extension of course. I've blogged [extensively](http://www.continuousimprover.com/2016/05/the-definitive-guide-to-extending.html) about this.

**Comment by dennisdoomen** [comment]
The internals of `ShouldBeEquivalentTo` (or `Should().BeEquivalentTo()` as it is now called in 5.0) are heavily extendable. Check out the `StructuralEqualityEquivalencyStep` in https://github.com/fluentassertions/fluentassertions/blob/release-5.0/Src/FluentAssertions/Equivalency/StructuralEqualityEquivalencyStep.cs

**Comment by 0xced** [comment]
Note to future readers: as of FluentAssertions 5.5.3 (maybe even earlier versions), asserting `XDocument` equivalency is straightforward:

```csharp
// Arrange
XDocument expectedDocument = XDocument.Load(...);
// Act
XDocument document = _systemUnderTest.CreateDocument();
// Assert
document.Should().BeEquivalentTo(expectedDocument);
```

**Comment by dennisdoomen** [comment]
That would mean that it would compare the properties. Not sure if that gives you the right information.

**Comment by 0xced** [comment]
Not sure what you mean by _it would compare the properties_. I looked at [XDocumentAssertions](https://github.com/fluentassertions/fluentassertions/blob/5.5.3/Src/FluentAssertions/Xml/XDocumentAssertions.cs#L104-L122) implementation and it uses [XmlReaderValidator](https://github.com/fluentassertions/fluentassertions/blob/5.5.3/Src/FluentAssertions/Xml/XmlReaderValidator.cs) which from what I understand compares all elements, attributes and the structure of the XML documents. I tested on two actual XML documents, trying to change/remove elements/attributes and the assertion fails with excellent error messages when the documents are not equivalent.

**Comment by drauch** [comment]
@0xced: "compare the properties" means, that the type does not have to be the same one. You can even have an anonymous type on the rigthhand side of the comparison.
