### ISSUE TITLE
Nuget doesn't display FluentAssertions (.Net core 2.0, VS 2017)

### ISSUE THREAD

**Issue by dhtek** [fluentassertions/fluentassertions#680]
Hello,

I just created a new xunit test project .NET core 2.0 on vs 2017 15.3.5 and can't find FluentAssertions in nuget package.

Can anybody help me ?

Thanks.

**Comment by jnyrup** [comment]
I tried to replicate your case, but I couldn't make it fail.
After creating the test project I went to "Manage NuGet packages" and searched for "FluentAssertions" and installed it.

What is the "package source" set to? 
See the upper right corner of the picture.
![image](https://user-images.githubusercontent.com/919634/31682090-606a96b0-b379-11e7-8af1-376a0defcd4c.png)

**Comment by dhtek** [comment]
It's ok 👍
I wrote "Fluent Assertion" instead of "FluentAssertions"...

**Comment by dennisdoomen** [comment]
Great. Case closed ;-)
