### ISSUE TITLE
ShouldBeEquivalentTo should not compare internals by default

### ISSUE THREAD

**Issue by TheRealNing** [fluentassertions/fluentassertions#683]
I was recently surprised to find a unit test failing because ShouldBeEquivalentTo was matching on an internal property of the subject. I was even more surprised when it continued to fail when I converted the property to an internal field.
Surely it is counter to good practice to test internals? Pragmatically, it is occasionally necessary, so it would be nice to be able to have the option to include internals. But not by default surely?
The question has been asked on StackOverflow (https://stackoverflow.com/questions/41933186/why-does-fluentassertions-shouldbeequivalentto-validate-internals) but has not received an answer.

FluentAssertions is fabulous by the way - it is my go-to assertion framework and I recommend it to everyone.

**Comment by dennisdoomen** [comment]
I've tried to trace it back to more than 6 years ago, but apparently it has always been like that. In a way, `internal` properties are conceptually _public_. If you would really design them as not being part of the your API, make them _private_. Another reason of running into that is that you're testing scope is a bit on the small side. Why would you make some properties public and others internal? Again, this is just an presumption by me, and you may have good reasons to do so. You can always exclude that `internal` property though.

**Comment by dennisdoomen** [comment]
So? Does that satisfy your question?

**Comment by TheRealNing** [comment]
I don't agree that `internal` properties are conceptually `public`; the naming makes the concept very clear.

There were good reasons for the specific scope and, being on a core base class, excluding them would have meant a lot of tests would be affected. In the end an extension method turned out to be neater and so the problem went away.

From a practical point of view, changing something that has been around for 6 years seems likely to displease more people than it pleases and I'm satisfied with the response.

Apologies for taking so long to close the issue. Thanks for considering this and providing your excellent framework.
