### ISSUE TITLE
link to fluentassertions.bestpractices

### ISSUE THREAD

**Issue by Meir017** [fluentassertions/fluentassertions#684]
I was wondering if it would be possible to add a link to [fluentassertions.bestpractices](https://github.com/Meir017/fluentassertions.bestpractices) and perhaps also move my project into the FA organization.

It currently supports the best-practices docs for collections and dictionaries

**Comment by dennisdoomen** [comment]
Sure. Although I recommend renaming your repo a bit. It now sounds like it contains a couple of best practices, but it is more than that.

**Comment by Meir017** [comment]
I was thinking of `fluentassertions.analyzers`

**Comment by dennisdoomen** [comment]
Yeah, sounds like a better name

**Comment by Meir017** [comment]
@dennisdoomen anything else before we can transfer this repository into the FA organization?

**Comment by dennisdoomen** [comment]
Nope. I've sent you an invite to become a member of FluentAssertions. Just push your repo to that location.

**Comment by Meir017** [comment]
done! 💯

**Comment by dennisdoomen** [comment]
Made you admin

**Comment by dennisdoomen** [comment]
So that closes the issue, right?

**Comment by Meir017** [comment]
Yes
