### ISSUE TITLE
Request: Add "HavePrivateSetter" and "HaveInternalSetter"

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [fluentassertions/fluentassertions#688]
I'm currently writing unit tests for a framework which exposes some read-only properties to the outside consumer of the framework. Internally these properties need to be set either via the constructor (private setter) or via an internal call (internal setter).

I'm currently testing with something along the lines of:

```

typeof(MyType).GetProperty(nameof(MyType.MyPrivateSetterPropery)).GetSetMethod()
                .Should().BeNull("because it should only be set by the constructor");
```

For internal setters its a bit more effort even.

Would it be possible to add methods to the framework to support things along the lines of:

```

typeof(MyType).GetProperty(nameof(MyType.MyInternalSetterPropery))
                .Should().HaveInternalSetter("because it should only be set internally");
```

**Comment by dennisdoomen** [comment]
Something like this? https://github.com/fluentassertions/fluentassertions/blob/release-5.0/Tests/Shared.Specs/TypeAssertionSpecs.cs#L1374

**Comment by MJLHThomassen-Eurocom** [comment]
Ah yes, wonderfull. Too bad the docs aren't up to date yet but I'm sure that will come. I've been using version 5.0.0 which also has some syntactic changes (to get the entire api more unified as i noticed, which is great) which have not been documented yet.

Thanks!

**Comment by dennisdoomen** [comment]
Yep, work in progress: #592
