### ISSUE TITLE
The example is confusing

### ISSUE THREAD

**Issue by mrtylerzhou** [fluentassertions/fluentassertions#692]
I tried
theString = "This is a String";
theString.Should().BeEquivalentTo("THIS IS A STRING");
The test success,**BeEquivalentTo** should be exactly the same.but obviously,the uppercase string is not exactly the same as theString variable

**Comment by jnyrup** [comment]
Equivalency is weaker than Equality. 
Somewhat like how approximate works with numerics. 

For assertion equality you should use `Should().Be()`.

I'm a bit unsure what you're asking for?
I think the examples with `Be()` and `EquivalentTo` exemplifies the difference between equivalency and equality.

**Comment by dennisdoomen** [comment]
So what do you think `BeEquivalentTo` should be doing?

**Comment by mrtylerzhou** [comment]
I have no problem with what BeEquivalentTo functions.But the explaination is confusion.When I hover over the method in visual studio,it explains that Assert a string is **exactly the same** as another string...I think excatly the same is not proper here,Because it is just approximate the same as another

**Comment by mrtylerzhou** [comment]
@dennisdoomen @jnyrup

**Comment by dennisdoomen** [comment]
It should say this: https://github.com/dennisdoomen/fluentassertions/blob/efd98babb37b2c1c3141c232595c09ca77480a8e/Src/FluentAssertions/Primitives/StringAssertions.cs#L80

**Comment by dennisdoomen** [comment]
So? Is this still an issue?

**Comment by mrtylerzhou** [comment]
Hello sir,thank you for your patient.Maybe I have understanding problems.I can not understand why **BeEquivalentTo** functions as approximate equal but the method explaination is **Asserts that a string is exactly the same as another string** .I regard **exactly the same** as total same,without any difference.If so,why the explaination should't be "Assert that a string looks like another string"

**Comment by dennisdoomen** [comment]
Where did you see the text _Asserts that a string is exactly the same as another string_?

**Comment by mrtylerzhou** [comment]
In the Method comments,just like **Be** method's comment.I'm so sorry that I did not read it carefully,It also have another line:w**ith the exception of casting.**.This line makes it different from the Be Method.Now I can understand it
