### ISSUE TITLE
FluentAssertions.5.0.0-beta0004 missing .NET 4.5 binaries

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [fluentassertions/fluentassertions#693]
As far as I can tell from the release notes, only support for .NET 4.0 was dropped in version 5.0.0, not support for .NET version 4.5. The nuget package for FluentAssertions.5.0.0-beta0004 only contains a net451 folder with those binaries.

Is support for 4.5 also dropped?

**Comment by dennisdoomen** [comment]
If you mean 4.5.0? If so, Microsoft does not support it all since Jan 2016. The only supported version is 4.5.2.

**Comment by MJLHThomassen-Eurocom** [comment]
We recently decided to start using FluentAssertions (and wanted to start using v5 since that was the latest one), but a collegue of mine just notified me that there are still some projects we have build with .NET 4.5. I did not know it wasn't support by MS anymore. If not then I understand why 4.5 is not supported by FluentAssertions either and I will notify my collegue about this.

**Comment by dennisdoomen** [comment]
Regardless, I'll check if I really need anything from 4.5.1. If not, I'll retarget 4.5.0 instead.

For reference purposes, see https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/

**Comment by MJLHThomassen-Eurocom** [comment]
Thanks. Yeah i also read that blog post. Good to know!

**Comment by MJLHThomassen-Eurocom** [comment]
Thanks!

**Comment by MJLHThomassen-Eurocom** [comment]
I just updated our .net 4.5 project to use Fluent Assertions 5.0.0 this week. Team is happy, thanks!
