### ISSUE TITLE
How to assert "one of enumeration matches"?

### ISSUE THREAD

**Issue by drauch** [fluentassertions/fluentassertions#704]
I have a collection of messages and I want to check that ONE OF those messages contains an ID and a special error code number. How to assert that?

    myCollection.Should().???
    // looking for something like:
    .Should().OneOf(x => x.Message.Contains(Id) && x.Message.Contains(ErrorCode) );

Any ideas? :-)

**Comment by jnyrup** [comment]
If you want to check that `myCollection` has *exactly* one match, you can use `ContainSingle`.
e.g.
`myCollection.Should().ContainSingle(x => x.Message.Contains(Id) && x.Message.Contains(ErrorCode));`
