### ISSUE TITLE
BeDecoratedWith should be able to specify wether or not the attribute should be inherited

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [fluentassertions/fluentassertions#706]
type.BeDecoratedWith() currently only checks for direct implementation. It should also be possible to check if the type, or any of its parent types, are decorated. This could be easily achieved since the build-in .NET method Type.GetCustomAttributes already has an overload that accepts a boolean wether or not to take inherited attributes into account.

Version 5.0.0-beta0004

**Comment by jnyrup** [comment]
I we expose the `bool inherit` to our API, I think we should be consistent and expose it everywhere.
That means both `[Not]BeDecoratedWith` and `ThatAre[Not]DecoratedWith`.

For `[Not]BeDecoratedWith` it would be a breaking change if we changed the API from 
```csharp
BeDecoratedWith<TAttribute>(
            Expression<Func<TAttribute, bool>> isMatchingAttributePredicate,
            string because = "", params object[] becauseArgs)
```

to e.g.

```csharp
BeDecoratedWith<TAttribute>(
            Expression<Func<TAttribute, bool>> isMatchingAttributePredicate,
            bool inherit = false,
            string because = "", params object[] becauseArgs)
```

This also has the implication that if you provide a `because` string, you need to provide `inherit`.
I'm not sure how well that fits into the fluent style API.

Have you done any thoughts of how this should change the API?

**Comment by dennisdoomen** [comment]
Or change the default behavior... 

Either way, we can still introduce breaking changes for 5.0.

**Comment by MJLHThomassen-Eurocom** [comment]
I've poked around in the code a bit yesterday but im not really familliar with the layout of the project so its a bit hard for me to see what would be the wisest thing to do here.

I agree that if we implement it here it should be implemented everywhere. I also agree with the fact that you should not have to specify the inherit property if you specify a because.

I was thinking about something along the lines of: typeof(MyType).Should().BeDecoratedWith<MyAttribute>().Or.InheritAttribute<MyAttribute>();

But introducing something like Or (which would be usefull in other cases I've encountered but thats not a discussion for here) would be a major refactoring/adding of code and logic so its probably not the best idea.

**Comment by jnyrup** [comment]
I would find it awkward if the default behaviour was `inherit = true`, as the default for `GetCustomAttributes` is `inherit = false`.

How about something like:
```csharp
ThatAreDecoratedWith(bool inherit = false);
ThatAreNotDecoratedWith(bool inherit = false);

BeDecoratedWith(string because = "", params object[] becauseArgs)
BeDecoratedWith(bool inherit, string because = "", params object[] becauseArgs)

NoBeDecoratedWith(string because = "", params object[] becauseArgs)
NotBeDecoratedWith(bool inherit, string because = "", params object[] becauseArgs)
```

**Comment by MJLHThomassen-Eurocom** [comment]
@jnyrup The default behavior should indeed reflect the GetCustomAttributes method. "BeDecoratedWith" also implies the decoration is ON that type and not on a parent type (since then it would be decorated on the parent).

As far as naming goes, I'm not really coming up with something. If you want it analogous to `Throw` and `ThrowExactly` i'd say: `BeDecoratedWith' and `BeDecoratedOrHaveParentThatIsDecoratedWith' or `BeDecoratedWithOrInherit' but both are kinda long...

**Comment by dennisdoomen** [comment]
I like `BeDecoratedWithOrInherit`

**Comment by dennisdoomen** [comment]
Is anybody working on this?

**Comment by MJLHThomassen-Eurocom** [comment]
@dennisdoomen I had a short look at it but I'm afraid my knowledge of the code layout is too limited to just go adding stuff in places i 'think' it belongs. Perhaps I will have a more extensive look should I have some spare time at the end of my current Sprint.

**Comment by dennisdoomen** [comment]
I understand. The beauty of a PR is that it allows code reviews and such. You could even ask for a preliminary review.

**Comment by MJLHThomassen-Eurocom** [comment]
I just decided that this would probably be forgotten if i didnt do it right away so here goes: #727
