### ISSUE TITLE
Bug when comparing collection to empty collection

### ISSUE THREAD

**Issue by tadams1138** [fluentassertions/fluentassertions#718]
```C#
[Fact]
public void EmptyCollectionComparison()
{
    var collection1 = new[] { 1, 2, 3 };
    var collection2 = new int[] { };
    collection1.Should().Equal(collection2);
}
```

Fails with the following message:

`Expected collection to be equal to {empty}, but found empty collection.`

I think "but found empty collection" should read "but found {1, 2, 3}" or something that at least indicates that collection1 was not in fact empty.

I'm using version (4.19.4).

**Comment by dennisdoomen** [comment]
Reproducable on 5.0 beta 4 as well.
