### ISSUE TITLE
Redundant BindingFlags

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#744]
From `TypeExtensions.cs`

```csharp
private const BindingFlags PublicMembersFlag =
BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance;

private const BindingFlags AllMembersFlag =
PublicMembersFlag | BindingFlags.NonPublic | BindingFlags.Static;
```

Note how `BindingFlags.NonPublic` is included in both constants.

Is that just redundant?

**Comment by dennisdoomen** [comment]
No, that can be removed.

**Comment by jnyrup** [comment]
Come again?

**Comment by dennisdoomen** [comment]
I mean the duplicate `BindingFlags.NonPublic`

**Comment by jnyrup** [comment]
I just wondered since 

```csharp
private static IEnumerable<PropertyInfo> GetPublicProperties(Type type)
{
    return type.GetProperties(PublicMembersFlag);
}
```

uses `PublicMembersFlag`, which includes `BindingFlags.NonPublic`, and hence `GetPublicProperties` will also return private properties.

**Comment by dennisdoomen** [comment]
Sure. Just remove it.
