### ISSUE TITLE
Generic EventMonitoring: no way to tell RaisePropertyChangeFor which Property to look for

### ISSUE THREAD

**Issue by jensbrand** [fluentassertions/fluentassertions#753]
In the documentation:

```
POCOClass subject = EmitViewModelFromPOCOClass();

using (var monitor = subject.Monitor<INotifyPropertyChanged>())
{
    // POCO class doesn't have INotifyPropertyChanged implemented
    subject.Should().RaisePropertyChangeFor(x => x.SomeProperty);
}
```

This dosn't work because subject.Should() dosn't expose RaisePropertyChangeFor. Monitor.Should() does but than, x is of type INotifyPropertyChange and does not expose the Property toc check.

**Comment by dennisdoomen** [comment]
You should remove the `INotifyPropertyChanged`. See https://github.com/fluentassertions/fluentassertions/blob/master/Tests/Shared.Specs/EventAssertionSpecs.cs#L459

**Comment by jensbrand** [comment]
Yes, I know this option and it works perfectly. But I think, the documentation is not correct because subject.Should() dosn't has the RaisePropertyChangeFor() method.

**Comment by dennisdoomen** [comment]
OK, I'll check the docs. Thanks for reporting it.

**Comment by dennisdoomen** [comment]
The docs were indeed wrong and completely unnecessary. You don't need to call `Monitor<INotifyPropertyChanged>()` to use `Should().RaisePropertyChangeFor`.
