### ISSUE TITLE
When installing the package in .net 4.7 it forces me to install ValueTuple

### ISSUE THREAD

**Issue by m3zercat** [fluentassertions/fluentassertions#757]

**Comment by dennisdoomen** [comment]
Shouldn't hurt, considering https://github.com/dotnet/announcements/issues/25

**Comment by m3zercat** [comment]
Ah. I hadn't seen that. Just remembered a while back it causing me annoying issues and so I've been avoiding it ever since.

**Comment by dennisdoomen** [comment]
I probably have to change the .nuspec so that that version no longer has the dependency.
