### ISSUE TITLE
New WithMessage isn't matching substrings without explicit ComparisonMode.Substring

### ISSUE THREAD

**Issue by mikecousins** [fluentassertions/fluentassertions#77]
Just updated our FluentAssertions and removed the ComparisonMode.Substring from our test. Our test now looks like this:

``` C#
        [Test]
        public void TesttemplatingExceptions()
        {
            const string template = @"@modal.value1";
            Action action = () => { new SingleTemplateRazorService(template, typeof(ModelForCsv)); };
            action.ShouldThrow<Exception>().WithMessage("The name 'modal' does not exist in the current context");
        }
```

We now get the following result even though it's clearly a substring:

```
Expected exception message to match the equivalent of 
"The name 'modal' does not exist in the current context", but 
"Compile Error Num:     CS0103\r\nError Text:\n The name 'modal' does not exist in the current context\r\nError location - line [25] column [7]\n\nProcessed Template:\n\r\n24            public override void Execute() {{\r˜25    Write(modal.value1);\r26    \r\n\r\n" does not.
```

**Comment by Terebi42** [comment]
The main page for FA is giving an example with the comparison mode property. Might want to update it, it took me 15 min of googling to find this issue, and figure out why the documented example wasn't working. 

http://www.fluentassertions.com/

.ShouldThrow<RuleViolationException>()
                    .WithMessage("change the unit of an existing ingredient", ComparisonMode.Substring)
                    .And.Violations.Should().Contain(BusinessRule.CannotChangeIngredientQuanity);

**Comment by dennisdoomen** [comment]
Good point!

**Comment by JosKrause** [comment]
2 years later...

**Comment by JeffRausch** [comment]
@dennisdoomen 
Example on https://fluentassertions.com/examples/ still shows ComparisonMode being used.

**Comment by dennisdoomen** [comment]
> Example on https://fluentassertions.com/examples/ still shows ComparisonMode being used.

Fixed it. Thanks for reporting.
