### ISSUE TITLE
Should().BeEquivalentTo

### ISSUE THREAD

**Issue by snekbaev** [fluentassertions/fluentassertions#771]
Hi,

thought you might give some insight about why comparison doesn't work.

```
var l1 = new List<UserEntity>()
{
	new UserEntity
	{
		FirstName = "Name"			
	}
};

var l2 = new List<UserEntity>()
{
	new UserEntity
	{
		FirstName = "Name"
	}
};

l1.Should().BeEquivalentTo(l2, options => options.Including(x => x.FirstName));
```
where `UserEntity` is an LLBLGen ORM entity and has other properties/fields/methods. However, validation throws `AssertionFailedException`. When I replace it with a regular class like:
```
public class WorksWithThis
{
	public string FirstName {get;set;}
}
```
No exception. I also tried in LinqPad:
```
(new UserEntity().FirstName == new UserEntity().FirstName).Dump();
(l1[0].FirstName == l2[0].FirstName).Dump();
```
both return `true`.

P.S.: using 5.1.1

**Comment by dennisdoomen** [comment]
Thanks for reporting this. What is the _exact_ output of the failure exception? 

If I'm not mistaking, this scenario is the same as is being testing by https://github.com/fluentassertions/fluentassertions/blob/master/Tests/Shared.Specs/CollectionEquivalencySpecs.cs#L704. 

BTW, you can compare your object with an anonymous type. That usually makes your tests a bit easier to read.

**Comment by snekbaev** [comment]
Thank you for a quick response!

I replaced the `UserEntity` with `FavoriteEntity` and compared `EntityId` Guid field to make the exception message shorter: [fvGHIssue.txt](https://github.com/fluentassertions/fluentassertions/files/1733553/fvGHIssue.txt)

P.S.: yeah, as a workaround I ended up having anonymous type comparison with a todo to undo :) One thing I ran into and wasn't sure whether it was by design (probably is given that I can see why it could make sense):
```
var l1Items = l1.Select(x => new {x.EntityId, S = "random value passing by"}).ToList();
var l2Items = l2.Select(x => new {x.EntityId}).ToList();
	
l1Items.Should().BeEquivalentTo(l2Items);
```
doesn't throw an exception. And it just felt that by using the `.Including` I could have a slightly stricter way to ensuring no one messes up with the anonymous types creation :)

**Comment by dennisdoomen** [comment]
Wait, now I see the problem. Does that object override `Equals`? Because it looks like it is comparing the entity by value, not by it's properties. You can verify that by using the `ComparingByMembers` option.

**Comment by snekbaev** [comment]
Something like:

```
(l1[0].Equals(l2[0])).Dump(); // False

(l1[0].EntityId.Equals(l2[0].EntityId)).Dump(); // True

l1.Should().BeEquivalentTo(l2, options => options.Including(x => x.EntityId).ComparingByMembers<Guid>()); // AssertionFailedException
```
?

**Comment by dennisdoomen** [comment]
No:

```csharp
l1.Should().BeEquivalentTo(l2, options => options.Including(x => x.FirstName).ComparingByMembers<UserEntity>());
```

**Comment by snekbaev** [comment]
I think following can replicate the issue:

```
var guid = Guid.NewGuid();

	var l1 = new List<WorksWithThis>()
	{
		new WorksWithThis
		{
			EntityId = guid
		}
	};

	var l2 = new List<WorksWithThis>()
	{
		new WorksWithThis
		{
			EntityId = guid
		}
	};
```

```
l1.Should().BeEquivalentTo(l2, options => options.Including(x => x.EntityId).ComparingByMembers<Guid>()); // AssertionFailedException
```

```
public class WorksWithThis : EntityBase2
{
	public Guid EntityId { get; set; }

	protected override Dictionary<string, string> CustomPropertiesOfType => throw new NotImplementedException();

	protected override Dictionary<string, Dictionary<string, string>> FieldsCustomPropertiesOfType => throw new NotImplementedException();

	protected override List<IEntityRelation> GetAllRelations()
	{
		throw new NotImplementedException();
	}

	protected override List<IEntity2> GetDependentRelatedEntities()
	{
		throw new NotImplementedException();
	}

	protected override List<IEntity2> GetDependingRelatedEntities()
	{
		throw new NotImplementedException();
	}

	protected override List<IEntityCollection2> GetMemberEntityCollections()
	{
		throw new NotImplementedException();
	}

	protected override Dictionary<string, object> GetRelatedData()
	{
		throw new NotImplementedException();
	}

	protected override RelationCollection GetRelationsForFieldOfType(string fieldName)
	{
		throw new NotImplementedException();
	}

	protected override void SetRelatedEntity(IEntityCore relatedEntity, string fieldName)
	{
		throw new NotImplementedException();
	}

	protected override void UnsetRelatedEntity(IEntityCore relatedEntity, string fieldName, bool signalRelatedEntityManyToOne)
	{
		throw new NotImplementedException();
	}
}
```

You will need FluentAssertions Nuget and LLBLGen support classes Nuget: https://www.nuget.org/packages/SD.LLBLGen.Pro.ORMSupportClasses

**Comment by snekbaev** [comment]
```
l1.Should().BeEquivalentTo(l2, options => options.Including(x => x.FirstName).ComparingByMembers<UserEntity>());
```

let's try...

**Comment by dennisdoomen** [comment]
This is by design. I tried to make this behavior more consistent and predictable. From http://www.continuousimprover.com/2018/02/fluent-assertions-50-best-unit-test.html:

> Similarly to auto-conversion, I've considerably simplified the way Fluent Assertions determines whether or not an object has value semantics. Before this release, it used a static IsValueType lambda and some awkwardly unclear heuristics. As of now, any type that overrides Object.Equals is treated as having value semantics. Why? Well, the entire purpose of that method (and its sibling GetHashCode) is to allow you to add value semantics to a reference type. Why wouldn't I comply to that .NET design principle? However, I also acknowledge the fact that not everybody will follow this principal faithfully, so you can override this using the ComparingMyMembers and ComparingByValue. Don't worry, I have some upgrading tips at the bottom of this post. Oh, and don't forget you can also set these and options globally using AssertionOptions.AssertEquivalencyUsing

**Comment by snekbaev** [comment]
alright, thank you! :)
