### ISSUE TITLE
Targets that are IComparable and IEnumerable don't work

### ISSUE THREAD

**Issue by bradphelan** [fluentassertions/fluentassertions#775]
![image](https://user-images.githubusercontent.com/17650/36413412-94d1d5e6-161e-11e8-9e19-478d49ee8d30.png)

Specifically classes like Lst<T> from LanguageExt

https://louthy.github.io/language-ext/LanguageExt.Core/LanguageExt/Lst_A.htm

which is an immutable list, both comparable and enumerable

Is there a solution to this?

**Comment by dennisdoomen** [comment]
What's the type of that `Children` property?

**Comment by bradphelan** [comment]
Lst<T>  as in the link

**Comment by bradphelan** [comment]
The workaround for the moment for me is to provide

```
    public static class LanguageExtExtensions
    {
        [Pure]
        public static GenericCollectionAssertions<T> ShouldAsEnumerable<T>( this IEnumerable<T> lst ) => lst.Should();

        [Pure]
        public static ComparableTypeAssertions<T> ShouldAsComparable<T>(this IComparable<T> lst ) => lst.Should();
    }
```

**Comment by dennisdoomen** [comment]
This is not something we can fix unfortunately. It's a compiler limitation. The only workaround I can think of is to first cast the result.
