### ISSUE TITLE
Tests running locally but not on AppVeyor?

### ISSUE THREAD

**Issue by kevinkuszyk** [fluentassertions/fluentassertions#776]
I have a PR open on the MVC extensions project to upgrade to FA 5 (fluentassertions/fluentassertions.mvc#34).  We have an odd error when tests run locally but not on AppVeyor.

@dennisdoomen have you seen a case like this before, and any idea on what might be wrong?

This is my console output locally: 

![image](https://user-images.githubusercontent.com/2734580/36473032-506c41a2-16eb-11e8-98c1-d6a72e77c2cf.png)

And the same on branch on AppVeyor:
https://ci.appveyor.com/project/kevinkuszyk/fluentassertions-mvc/build/45

Any tips would be much appreciated.

/cc @rikrak

**Comment by dennisdoomen** [comment]
The caller identitifcation only works on .NET Standard 2.0 and .NET 4.5 _and_ when you debug info available.

**Comment by kevinkuszyk** [comment]
Bingo, thanks @dennisdoomen it blows up here now when I make a release build.

@rikrak does that give you enough info to finished off the FA 5 upgrade?

**Comment by dennisdoomen** [comment]
I even documented that http://fluentassertions.com/documentation.html#subject-identification

**Comment by rikrak** [comment]
@kevinkuszyk I shall take a look.  Thanks for the tip @dennisdoomen :-)

**Comment by kevinkuszyk** [comment]
Note to self: RTFM!
