### ISSUE TITLE
Question: Nullable Immutable Arrays

### ISSUE THREAD

**Issue by Mike-EEE** [fluentassertions/fluentassertions#777]
First off, amazing project. :)  We are using it for [ExtendedXmlSerializer](https://github.com/wojtpl2/ExtendedXmlSerializer).

Secondly, finally ran into my first problem here after many (many!) times of "just working".

I have the following class:

```
class Subject
{
	public Subject(ImmutableArray<int>? test)
	{
		Test = test;
	}

	public ImmutableArray<int>? Test { get; }
}
```

But when I do this:
```
new Subject(ImmutableArray.Create(1, 2, 3))
    .ShouldBeEquivalentTo(new Subject(ImmutableArray.Create(1, 2, 3)));
```

I get the following failure: `Expected member Test to be {1, 2, 3}, but found {1, 2, 3}.`

Looks like it has to do with being a nullable value type.  If I make it non-nullable it works as expected.  Any suggestions on what I could be doing wrong?  Thank you in advance for any assistance!

**Comment by Mike-EEE** [comment]
Hey lucky #777... I'll take that. 😎

**Comment by dennisdoomen** [comment]
Thanks for nice words. If possible, I recommend using v5. It has much better semantics for value types.

**Comment by Mike-EEE** [comment]
OK cool.  I did try to upgrade but we're using a lot of `ShouldBeEquivalentTo` which appears to be moved in the latest version (no doubt due to your suggestion above).  I'll fix this bug I am working on and then give that a shot.  If I have any further questions I'll reopen this issue.  Thank you for your quick reply!

**Comment by Mike-EEE** [comment]
Ah ok... I installed v5.1.2 but unfortunately I get the same failure.  I am using `Should().BeEquivalentTo`.  Please let me know if there's another consideration here.

**Comment by Mike-EEE** [comment]
OK great, thanks for sharing that, @dennisdoomen.  For starters, can you please share the source of that?  Is that from a blog?  I would like to subscribe to it to make sure I get updates and not have to be a hassle on your issues board. 😄 

Secondly, the issue isn't value types per-se, but in this case a _nullable_ value type.  If I change my `Test` property from a `ImmutableArray<int>?` to a `ImmutableArray<int>` it works just fine (and so did 4.x).  So I am curious here on what the magic option setting I need to apply to make this work in this case.  I did try the above suggestions but did not have any success.

Thirdly (and finally!), we are making use of an [equality comparer](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/bf84ca748afdc985734bb494cf6527eca655b96f/src/ExtendedXmlSerializer/ContentModel/Conversion/TypePartsEqualityComparer.cs#L31) as this tends to keep POCOs "plain" while also allowing for easier integration with other components if they happen to need it.  Ideally, it would be valuable to utilize this for the comparison, but it does not appear that the `IEqualityComparer` interface is utilized/available anywhere in FluentAssertions.  If it is I would greatly appreciate a pointer on where!

**Comment by eNeRGy164** [comment]
Source: http://www.continuousimprover.com/2018/02/fluent-assertions-50-best-unit-test.html

**Comment by Mike-EEE** [comment]
Cooool, thanks @eNeRGy164 ... subscribed. 🤓

**Comment by Mike-EEE** [comment]
Ah ok... what I am suggesting here is to have the ability to pass in an `IEqualityComparer` to the `BeEquivalentTo` method.

If it helps, [here is an example](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/test/ExtendedXmlSerializer.Tests/ContentModel/Reflection/TypePartsParserTests.cs#L59-L66) of what we're having to do now.

Ideally, it would be nice to do something like this instead:

```
var sut = TypePartsParser.Default;
sut.Get("testing:int^3,4,2").Should().BeEquivalentTo(
	new TypeParts("int", "testing", dimensions: ImmutableArray.Create(3, 4, 2)),
	TypePartsEqualityComparer.Default
);
```

**Comment by dennisdoomen** [comment]
> If I change my Test property from a ImmutableArray? to a ImmutableArray it works just fine

I found the problem. Nullable properties referring to types implementing `IEnumerable` are not detected as such, after which FA will fall back on value semantics. And `ImmutableArray` implements `Equals` by comparing the underlying arrays by reference.

**Comment by Mike-EEE** [comment]
Woohoo!  Awesome!  Thank you @dennisdoomen !
