### ISSUE TITLE
Nullable DateTime properties cause exception when comparing collections with different member ordering

### ISSUE THREAD

**Issue by FilipFilipov** [fluentassertions/fluentassertions#778]
It's entirely possible this affect more general cases, but that's the only one I've run across.

```
var obj1 = new { date = (DateTime?) null, num = 0 };
var obj2 = new { date = (DateTime?) DateTime.Now, num = 1 };

// Passes
new[] { obj1, obj2 }.Should().BeEquivalentTo(new[] { obj1, obj2 });

// Passes
new[] { obj1, obj2 }.Should().BeEquivalentTo(new[] { obj2, obj1 }, opt => opt.Excluding(o => o.date));

 // NullReferenceException
new[] { obj1, obj2 }.Should().BeEquivalentTo(new[] { obj2, obj1 });
```

**Comment by jnyrup** [comment]
Which version of Fluent Assertions are you using?

I just tried with v5.1.2 and all cases passes for me.

**Comment by FilipFilipov** [comment]
I'm using the NuGet package of 5.1.2 for framework 4.6

**Comment by jnyrup** [comment]
Can you check if:
* replacing `DateTime.Now` with `DateTime.UtcNow` or,
* setting `CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;`

solves the problem?

**Comment by FilipFilipov** [comment]
I now remember that I created  a custom global configuration way back when I first started using the library. You can reproduce the bug if you add this

```
AssertionOptions.AssertEquivalencyUsing(options => options.Using<DateTime>(ctx => ctx.Subject.Should().BeCloseTo(ctx.Expectation, 1000)).WhenTypeIs<DateTime>());
```

I did this to compare DateTimes fetched from the SQLServer, as they lose more precision when saved than the default margin for error will allow. I don't recall that causing problems before version 5.0 though.

**Comment by FilipFilipov** [comment]
It seems I can work around the issue by specifying a second rule for the nullable DateTime

```
.Using<DateTime>(ctx => ctx.Subject.Should().BeCloseTo(ctx.Expectation, 100)).WhenTypeIs<DateTime>()
.Using<DateTime?>(ctx =>
{
  if (ctx.Expectation.HasValue)
  {
    ctx.Subject.Should().BeCloseTo(ctx.Expectation.Value, 100);
  }
  else
  {
    ctx.Subject.Should().BeNull();
  }
}).WhenTypeIs<DateTime?>()
```

Still it'd be nice if it figured that out on its own.
