### ISSUE TITLE
Question: .NET Standard 1.4 vs .NET Standard 1.3

### ISSUE THREAD

**Issue by Athari** [fluentassertions/fluentassertions#779]
What is the reason to prefer .NET Standard 1.4 over 1.3? I couldn't find any info on their [supported platforms](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) being different or [any relevant APIs](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard1.4.md) being added in 1.4. [XmlDocument](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmldocument) mentioned in #463 seems to be available only in .NET Standard 2.0. I'm confused.

I'm trying to port my library to .NET Standard and 1.3 seemed like a reasonable version, based on available APIs and NuGet dependencies. To my surprise, FluentAssertions turned out to be the only exception, so I'm trying to understand why.

I'm new to this .NET Standard thing, so maybe I'm missing something obvious.

**Comment by dennisdoomen** [comment]
Now I'm in doubt as well. Just checked the history and apparently I did it to support XmlDocument (see #463), but it seems I was wrong about that.

**Comment by dennisdoomen** [comment]
Just tried to retarget it and everything seems to work, so it looks I can fix this.

**Comment by dennisdoomen** [comment]
Will be part of 5.2.0 in the coming days.
