### ISSUE TITLE
MethodImplAttribute doesn't work with BeDecoratedWith

### ISSUE THREAD

**Issue by melchiork** [fluentassertions/fluentassertions#781]
Version: 5.1.2

When a method is decorated with `MethodImplAttribute` the assertion `Should().BeDecoratedWith<MethodImplAttribute>()` will not detect that and therefore produce a false negative. It's because `GetCustomAttributes` method that is used behind the scenes will not get this attribute as per [docs](https://msdn.microsoft.com/en-US/library/system.runtime.compilerservices.methodimplattribute(v=vs.110).aspx). The `GetMethodImplementationFlags` method has to be used.
I can implement a patch for this, but I'm unsure which of two approaches would be better:
1. [breaking] add capacity of finding the Implementation Flags to current `BeDecoratedWith` method
2. [non-braking] add a new assertion like `BeDecoratedWithImplementationFlags`

**Comment by dennisdoomen** [comment]
Why would (1) be breaking?

**Comment by melchiork** [comment]
Example "reconstruction" of `MethodImplAttribute`

```
private static int ImplementationOptionsMask = 
Enum.GetValues(typeof(MethodImplOptions)).Cast<int>().Sum(x => x);

                private static Attribute GetMethodImplAttribute(MemberInfo memberInfo)
        {
#if NETSTANDARD1_3
            return null;
#else
            var methodInfo = memberInfo.MemberType == MemberTypes.Method
                ? memberInfo as MethodInfo
                : null;

            var implementationAttributes = methodInfo.GetMethodImplementationFlags();

            var methodImplementationOptionsWithoutNotMatchingImplementationAttributes =
                (int)implementationAttributes & ImplementationOptionsMask;

            var implementationOptions =
                (MethodImplOptions)(short)
                methodImplementationOptionsWithoutNotMatchingImplementationAttributes;

            if (implementationOptions != 0)
            {
                return new MethodImplAttribute(implementationOptions);
            }

            return null;
#endif
        }
```

**Comment by jnyrup** [comment]
The other type assertions take a C# perspective rather than a CLR perspective.
Seen from that point of view, I'm not against `[Not]BeDecoratedWith` getting capabilities to detect `MethodImplAttribute`.

If it is at any help for the person who might implement this, `MethodImplAttribute` is marked with `Inherited = false`. So overriden methods won't inherit this attribute.

**Comment by jnyrup** [comment]
Thanks for another contribution @melchiork .
They are very appreciated.
