### ISSUE TITLE
[question] [discussion] [support needed] Asserting log created with log4j has entry

### ISSUE THREAD

**Issue by hellboy81** [fluentassertions/fluentassertions#782]
I have unit test written in C# which should test my own code both in C# which also calls external application (SOAP UI) and also my code in this AUT (Groovy)

The only way to verify Groovy code is logging. The logging framework in SoapUI is based on `log4j`

What is the best way to make assertions indirectly using log files?

**Comment by dennisdoomen** [comment]
This question is not really related to this project. Please post this on StackOverflow instead.
