### ISSUE TITLE
Maintain more specific types when chaining assertions 

### ISSUE THREAD

**Issue by ofirgeller** [fluentassertions/fluentassertions#784]
For example if I am asserting something on Type A that derives from object, and I use `.And` to chain more assertions I lose the type of the original object that is now only known to be an "object".

The thing that made me think of this is the usage of the `BeOfType<T>` assertion. I would be much more comfortable to have the subject typed as T after this assertion in the chain. so you can write something like.

`actual.Should().BeOfType<Car>().And.Subject.Speed.Should().Be(80);`

**Comment by dennisdoomen** [comment]
You need to use `Which` like this:

`actual.Should().BeOfType<Car>().Which.Subject.Speed.Should().Be(80);`

**Comment by ofirgeller** [comment]
Thank you, I did not know that and it does serve well for my main use case. but other assertions are still losing the specific type no?

**Comment by dennisdoomen** [comment]
Most assertions that have the notion of a `T` return an object that exposes a typed `Which`

**Comment by dennisdoomen** [comment]
Does this answer your question?

**Comment by ofirgeller** [comment]
Yes it does, thank you.
