### ISSUE TITLE
Add Using<TActual, TExpected, TCommon>

### ISSUE THREAD

**Issue by michal-ciechan** [fluentassertions/fluentassertions#791]
I have been thinking of implementing a 

    .Using<TActual, TExpected, TCommon>(
        Func<TActual, TCommon> actualSelector, 
        Func<TExpected, TCommon> expectedSelector
    ) 

with potentially an overload to accept 

`Action<TCommon, TCommon> comparer` 

as the final argument

**Comment by dennisdoomen** [comment]
Is this related to #535?

**Comment by michal-ciechan** [comment]
Yes, will close this, and take a look at the other issue.
