### ISSUE TITLE
Is updating to System.ValueTuple 4.4 in the roadmap?

### ISSUE THREAD

**Issue by jon-tindel** [fluentassertions/fluentassertions#792]
Is it currently envisioned to update to System.ValueTuple 4.4?

**Comment by dennisdoomen** [comment]
Are you missing something?

**Comment by jon-tindel** [comment]
Ah, good question. No, I'm just running into an assembly compatibility issue. A project I'm working on requires the later version of System.ValueTuple (4.4), and our lead architect doesn't want to get into multiple assembly versions.

**Comment by dennisdoomen** [comment]
The entire point of relying on the lowest minor version is that you can take any higher version. That's the idea behind semantic versioning.

**Comment by jon-tindel** [comment]
Are you sure FA isn't requiring the older version?
When I run a test that relies on ValueTuple, I get "Could not load file or assembly 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)".
All the System.ValueTuple.dll assemblies on my computer are assembly version 4.0.2.0.

**Comment by dennisdoomen** [comment]
Which framework are you targeting and from which folder inside the nuget package is it referencing FA?

**Comment by jon-tindel** [comment]
Targeting .net framework 4.6.1.
Referencing from C:\L\packages\unittests\FluentAssertions\lib\net45\FluentAssertions.dll (am I answering the right question?)

**Comment by dennisdoomen** [comment]
Hmm, which version of FA are you using?

**Comment by jon-tindel** [comment]
FA: Runtime Version: v4.0.30319. Version: 5.1.2.0.

**Comment by dennisdoomen** [comment]
See https://stackoverflow.com/questions/38382971/predefined-type-system-valuetuple´2´-is-not-defined-or-imported

You're not supposed to have that assembly referenced unless you use .NET 4.7 or higher. So can you try to remove that reference add the nuget package isntead?

**Comment by jon-tindel** [comment]
I'm not sure what assembly you're referring to. System.ValueTuple 4.4 is necessary for us and is supported by .net 4.6.1. If you're referring to the FA assembly, I can't think of a different place. The other options are net47, netstandard1.4, netstandard1.6, and netstandard2.0. All of this is being added through nuget. It is only FA that is the issue because it references System.ValueTuple 4.3. We are able to use System.ValueTuple effectively in other parts of our application. We have also verified that only System.ValueTuple 4.4 (4.0.2.x) libraries are on the machine.

**Comment by dennisdoomen** [comment]
That's the problem. You should be referring to System.ValueType 4.4, not 4.0.2.x. It should come from a local Nuget package, not from a different folder.

**Comment by jon-tindel** [comment]
I'm sorry. I think you're mistaken. The build version 4.0.2.x is the one that comes from the package version 4.4. We are using it to great effect elsewhere in our application. It is only FA which is looking for the previous dll version. Unfortunately, we will not be able to use FA if this can't be corrected.

All of our package management is being done via nuget through paket and we have no control over the individual references.

Thanks for your assistance!

**Comment by jnyrup** [comment]
Can you provide a minimal example that shows your problem?

When using NuGet 4.0.0, a .NET Framework 4.6.1 project will choose the FA dll for net45.
http://nugettoolsdev.azurewebsites.net/4.0.0/get-nearest-framework?project=net461&package=netstandard1.3%0D%0Anetstandard1.6%0D%0Anetstandard2.0%0D%0Anet45%0D%0Anet47

The FA dll targeting .net 4.5 is not requiring *exactly* `System.ValueTuple` 4.3, but *at least* 4.3.
https://github.com/fluentassertions/fluentassertions/blob/master/Src/FluentAssertions/FluentAssertions.csproj#L42

This means consumers of FA are free to reference `4.3`, `4.4`, `4.5.0-preview1-26216-02` or any future version in their unit test projects.
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-version
https://docs.microsoft.com/en-us/nuget/reference/package-versioning#version-ranges-and-wildcards

In fact our own tests project for .NET Framework 4.5 references `System.ValueTuple` 4.4
https://github.com/fluentassertions/fluentassertions/blob/master/Tests/Net45.Specs/Net45.Specs.csproj#L16

**Comment by dennisdoomen** [comment]
Check out the official package using the NuGet Package Explorer. 4.4.0 has a dedicated .NET 4.6.1 package, which version is 4.7.something. 

![image](https://user-images.githubusercontent.com/572734/37076320-6da3067a-21d6-11e8-9f9e-928009d08f89.png)

**Comment by jon-tindel** [comment]
Interestingly, when our paket guy checked it out with NuGet Package Explorer, we see different values.
![nuget package explorer](https://user-images.githubusercontent.com/22062745/37160789-e2ee1c92-22a5-11e8-9fa5-8c73d56d2634.jpg)

**Comment by jon-tindel** [comment]
I'll try to create a minimal example. Thanks for the advice, @jnyrup.
And thanks for your responses, @dennisdoomen.
I've been a fan of FA for years and would be disappointed if I can't get it integrated into the latest project I'm working on to the satisfaction of the team lead.

**Comment by jnyrup** [comment]
Here's what I see using Nuget Package Explorer 4.1.38 and the v3 nuget feed.

![image](https://user-images.githubusercontent.com/919634/37161569-5653fa42-22f3-11e8-8b5d-ed67486d5c25.png)

**Comment by dennisdoomen** [comment]
Alright. It seems I was using an older version of the Nuget Package Explorer. Now I see the same thing. Apparently package 4.3.0 has a strong name referring to 4.0.1.0. I think it is safe to upgrade to System.ValueTyple 4.4.0.

**Comment by jon-tindel** [comment]
Thanks guys
