### ISSUE TITLE
Why using RespectingDeclaredTypes as the default in the options for BeEquivalentTo

### ISSUE THREAD

**Issue by ursenzler** [fluentassertions/fluentassertions#797]
While upgrade to V5 of FluentAssertions we struggle a bit with the new and shiny `BeEquivalentTo`.

We compare a lot of objects containing `IEnumerables<IFoo>` with different classes implementing `IFoo`.

The result with the default behaviour is that only the properties of `IFoo` are compared and not the additional properties of the classes implementing `IFoo`.

We can get the correct result by specifying options with `IncludingAllRuntimeProperties`.

What we wonder is, shouldn't this be the default behaviour (least surprisingly to the user and safest)?

**Comment by dennisdoomen** [comment]
The current behavior was the intention all along. But because the _expectation_ wasn't driving the comparison, it wasn't that apparent. You can also specify a global option you know?

**Comment by ursenzler** [comment]
I set the options globally with Fody ModuleInit: https://github.com/Fody/ModuleInit .

Thanks.
