### ISSUE TITLE
Contain(IEnumerable<T>, params T[]) lacks because parameter

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [fluentassertions/fluentassertions#806]
The method

```cs
public AndConstraint<TAssertions> Contain(IEnumerable<T> expectedItemsList, params T[] additionalExpectedItems);
```
in the class `SelfReferencingCollectionAssertions<T, TAssertions>` lacks a `string because` parameter. Probably because `additionalExpectedItems` is a `params`.

Suggestions:

1. Refactor to:

```cs
public AndConstraint<TAssertions> Contain(IEnumerable<T> expectedItemsList, IEnumerable<T>additionalExpectedItems, string because = "", params object[] becauseArgs);
```

Pro's:
- Same signature as other methods

Cons:
- Breaking change

2. Add:

```cs
public AndConstraint<TAssertions> Contain(IEnumerable<T> expectedItemsList, string because ="", params T[] additionalExpectedItems);
```

Pro's:
- Non-breaking change

Cons:
- No `params object[] becauseArgs`
- Still does not match other method signatures

**Comment by dennisdoomen** [comment]
That's because there's already a `params` parameter. If you really need the `because`, use the overload that takes an `IEnumerable`.

**Comment by MJLHThomassen-Eurocom** [comment]
> That's because there's already a params parameter. If you really need the because, use the overload that takes an IEnumerable.

Which overload is that? I am already using the overload that accepts an `IEnumerable`, as far as I can see from the interface these are the options:

```
public AndWhichConstraint<TAssertions, T> Contain(Expression<Func<T, bool>> predicate, string because = "", params object[] becauseArgs);
public AndConstraint<TAssertions> Contain(IEnumerable<T> expectedItemsList, params T[] additionalExpectedItems);
public AndWhichConstraint<TAssertions, T> Contain(T expected, string because = "", params object[] becauseArgs);
```

from `SelfReferencingCollectionAssertions`

and 

```
public AndConstraint<TAssertions> Contain(IEnumerable expected, string because = "", params object[] becauseArgs);
```
from `CollectionAssertions`

I don't require the because args per-se, its fine as it is, I was just wondering why the `additionalExpectedItems` parameter is a `params T[]` instead of an `IEnumerable<T>`, causing this single method to break convention with the rest of the library.

**Comment by jnyrup** [comment]
As of #1529 this is now handled by `GenericCollectionAssertion.Contain(IEnumerable<T>)` as `Contain(IEnumerable<T> expectedItemsList, params T[] additionalExpectedItems)` has been removed.
