### ISSUE TITLE
Use BeEquivalentTo to compere subclass as base class with other subclass

### ISSUE THREAD

**Issue by wojtpl2** [fluentassertions/fluentassertions#807]
I have:
```C#
    public class ClassOne
    {
        public int ValOne { get; set; } = 1;
    }

    public class InheritsFromClassOne : ClassOne
    {
        public string StringVal { get; set; }
    }
```
then I create instances:
```C#
var actual = new InheritsFromClassOne() { ValOne = 1, StringVal = "A" };
var expected = new InheritsFromClassOne() { ValOne = 1, StringVal = "B" };
```
And then I compere this class I get exception XunitException with message
`Expected member StringVal to be \"B\", but \"A\" differs near \"A\" (index 0).*` And it is correct behavior.

But if I change type of expected object to base class, like this:
```C#
var actual = new InheritsFromClassOne() { ValOne = 1, StringVal = "A" };
ClassOne expected = new InheritsFromClassOne() { ValOne = 1, StringVal = "B" };
```
I do not get any exception.

**Comment by dennisdoomen** [comment]
The object you pass in as the _expectation_ determines what is compared. In your second example, you pass in an instance of `ClassOne` as the expectation. That one doesn't expose the `StringVal` property. See also http://fluentassertions.com/documentation.html#compile-time-types-vs-run-time-types

**Comment by wojtpl2** [comment]
Thanks! I didn't know about it. In this way there is no problem. 
I did:
```C#
Action act = () => actual.Should().BeEquivalentTo(expected, o=>o.RespectingRuntimeTypes());
```
And FlentAssertions work great!
