### ISSUE TITLE
What is your recommendation about where to specify global configuration

### ISSUE THREAD

**Issue by ursenzler** [fluentassertions/fluentassertions#808]
With `AssertionOptions.AssertEquivalencyUsing(options => options.IncludingAllRuntimeProperties());` I can specify my global configuration. But where to define it best?

Some static constructor of some random type?

Any advice?

**Comment by dennisdoomen** [comment]
This is something I'm struggling myself with as well.

**Comment by jnyrup** [comment]
If your unit testing frameworks support global setups, I would put it there.
E.g for `MSTest`

```
[TestClass]
class GlobalTestInitializer
{
    [AssemblyInitialize]
    public static void InitializeTestAssembly(TestContext context)
    {
        AssertionOptions.AssertEquivalencyUsing(options => options.IncludingAllRuntimeProperties());
    }
}
```

**Comment by ursenzler** [comment]
xUnit does not provide global setup, but I'll try it with Fody ModuleInitializer...

**Comment by ursenzler** [comment]
I use Fody ModuleInitilizer for this now: https://github.com/Fody/ModuleInit

**Comment by dennisdoomen** [comment]
I guess we need some feature based on some kind of interface and then use reflection to find the implementation.

**Comment by ursenzler** [comment]
But when do you want to execute this code?

**Comment by chwarr** [comment]
Perhaps a completely different approach: could we come up with a way to scope `AssertionOptions`? Then, in xUnit, you could do something like this:

```
public class FooTests : IDisposable
{
    private readonly ScopedOptions _scopedOptions;

    public FooTests()
    {
        _scopedOptions = new ScopedOptions();
        _scopedOptions.IncludingAllRuntimeProperties();
    }

    public void Dispose()
    {
        _scopedOptions.Dispose();
    }

    [Fact]
    public void Given_What_Expectation()
    {
        var expected = ...;
        var actual = ...;
        expected.Should().BeEquivalentTo(actual);
    }
}
```

If this is already possible with something like `AssertionScope`, I could not see how to glue things together. Pointers here would be welcome.

**Comment by dennisdoomen** [comment]
The problem with that approach is that it would need to keep that scope associated with that test. Without hooking into a specific technique a test framework may provide (if any), you'll need to resort on thread-static stuff. But since a lot of people using `async/await`, you can't make any assumptions about the thread something is running on anymore. In .NET 4.6, `AsyncLocal` was introduced, which could work, but then we have to find another way for people targeting .NET 4.5. In FA 5.0, I spend a great deal of time trying to get rid of any thread-static stuff. So I'm a bit on the brink here on how to approach this. Maybe @jnyrup has some opinions about that as well.

**Comment by jnyrup** [comment]
My gut feeling is that this should be handled by the unit test framework and not by FA.

* xUnit.net : https://xunit.github.io/docs/shared-context.html
* MSTest : https://www.meziantou.net/2018/02/12/mstest-v2-test-lifecycle-attributes
* NUnit : https://github.com/nunit/docs/wiki/SetUp-and-TearDown

**Comment by chwarr** [comment]
I hadn't considered async methods. Agreed they'd complicate stuff. I don't have a better proposal either. Thanks for the details.

**Comment by philippdolder** [comment]
Might be a bit late to the party, but I think we now got a solution that works for us (we're using xUnit.net).
From my understanding shared context in xUnit.net doesn't work, since the `AssertionOptions` is static, i.e. one shared instance per AppDomain, i.e. broader lifetime than any xUnit shared contexts.

``` c#
public static class GlobalFluentAssertionsConfiguration
{
    private static readonly object Lock = new object();
    private static bool alreadyLoaded = false;

    public static void Configure()
    {
        lock (Lock)
        {
            if (alreadyLoaded)
            {
                return;
            }

            alreadyLoaded = true;

            AssertionOptions.AssertEquivalencyUsing(
                options => <do your thing>);
        }
    }
}
```

we're calling this method from the static ctor of every test that requires the special assertions. Without the check `alreadyLoaded` we started to have `System.InvalidOperationException : Collection was modified; enumeration operation may not execute.` caused by `BeEquivalentTo()`.

**Comment by dennisdoomen** [comment]
@philippdolder thanks for sharing this.

**Comment by philippdolder** [comment]
@dennisdoomen I guess I was a bit overly excited. Unfortunately we still sometimes get
`System.InvalidOperationException : Collection was modified; enumeration operation may not execute.`
🤔 I'm running out of ideas now. Do you have an explanation what might cause this exception now, that I'm (quite) sure we only setup the global assertion options once?

Stacktrace is
```
System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
  Stack Trace:
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at FluentAssertions.Equivalency.SelfReferenceEquivalencyAssertionOptions`1..ctor(IEquivalencyAssertionOptions defaults)
   at FluentAssertions.Equivalency.EquivalencyAssertionOptions`1..ctor(IEquivalencyAssertionOptions defaults)
   at FluentAssertions.AssertionOptions.CloneDefaults[T]()
   at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, Func`2 config, String because, Object[] becauseArgs)
   at FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo[TExpectation](TExpectation expectation, String because, Object[] becauseArgs)
```

**Comment by philippdolder** [comment]
after some more investigation we think it might be the following that's happening.

Test 1 (without a call to `Configure`) is doing `CloneDefaults`
Test 2 is executing the call to `Configure` at the same time on a different thread which modifies the collection the `CloneDefaults` is iterating through. Which is of course not allowed.

Seems the assertion options cloning / modifying is not thread-safe.

@dennisdoomen does that sound reasonable?

**Comment by dennisdoomen** [comment]
Yep. That would be my first thought as well. I would welcome a PR or at least a separate issue.
