### ISSUE TITLE
The repo and NuGet descriptions are mismatched 

### ISSUE THREAD

**Issue by melchiork** [fluentassertions/fluentassertions#812]
The repo description states 

> that target .NET Framework 4.5, .NET Standard 1.4, 1.6 and 2.0. 

when NuGet one states 

> Targets .NET Framework 4.5, .NET Standard 1.3, 1.6 and 2.0.

I think NuGet description to be correct. Also the is no mention of 4.7. Can this be addressed?

**Comment by dennisdoomen** [comment]
You're right. Fixed that. The Nuget package has evolved beyond the repo ;-)
