### ISSUE TITLE
LineBreaks in formatting

### ISSUE THREAD

**Issue by j-maly** [fluentassertions/fluentassertions#815]
I've noticed the useLineBreaks parameter in formatters. 
How can i write an assertion that tells formatters to use line breaks? I couldn't find this in the docs, is there something like 
 
x.Shlould().BeEquivalentTo(y, ??? f => f.UseLineBreaks())

**Comment by dennisdoomen** [comment]
Well, I wouldn't verify it like that. I would only assert on the actual output of an assertion that fails with the correct failure message

**Comment by j-maly** [comment]
Maybe I am not making myself clear, I am just interested on making the output more readable. 

This assertion: 

var a = new [] {"a", "b", "c", "d"}
var b = new [] {"b", "c", "d", "e"}

a.Should().BeEquivalentTo(b);

Prints something like:
Expected collection {"a", "b", "c", "d"} to be equivalent to "b", "c", "d", "e"}...

But it is not very readable when the objects in the collection are complex and have long ToString outputs.
So I was hoping I can get it formatted like 
Expected collection 
{
"a", 
"b", 
"c", 
"d"
} 
to be equivalent to 
{
"b", 
"c", 
"d",
"e"
}
...

**Comment by dennisdoomen** [comment]
The you need to override the formatter that handles collections.

**Comment by j-maly** [comment]
This page 
http://fluentassertions.com/extensibility/#rendering-objects-with-beauty
says the formatter should look at the value of context.UseLineBreaks. 
I don't know how the user can set the value of context.UseLineBreaks.

**Comment by dennisdoomen** [comment]
This is something that the assertion code uses internally. The `AssertionScope.UsingLineBreaks` can be used to instruct that the next failure message should use line breaks.

**Comment by j-maly** [comment]
Aha, ok... well maybe this could be a feature :)

**Comment by dennisdoomen** [comment]
How would that change the API?

**Comment by dennisdoomen** [comment]
Can I close this topic @j-maly? Or do you have more questions?

**Comment by jnyrup** [comment]
Closed due to inactivity, please re-open if you have more to add.
