### ISSUE TITLE
IComparable<T> tests aren't rigorous enough

### ISSUE THREAD

**Issue by jmagaram** [fluentassertions/fluentassertions#816]
Check out this terrible implementation of IComparable. My test passes even though my implementation of IComparable is flawed. When I'm trying to assert that a<b (and neither is null) shouldn't FluentAssertions validate that `a.CompareTo(b)` and `b.CompareTo(a)` also return values with opposite signs? And if I'm testing that a<=b then FluentAssertions should check that a<b too. Otherwise each comparison test becomes very verbose because I need to manually specify all the implied mathematical implications.
 
    public class MyClass : IComparable<MyClass>
    {
        public int CompareTo(MyClass other) => -1;
    }

    [TestMethod]
    public void CompareTest()
    {
        var a = new MyClass();
        var b = new MyClass();
        a.Should().BeLessThan(b);
        b.Should().BeLessThan(a);
    }

To properly implement IComparable you might also want to do a strongly typed version of it, override the comparison operators, etc. I think it would be better if I could write a test like `a.IsLessThan(b).IsLessThan(c).IsEqualTo(c).Assert(Option.CheckStaticOperators);` and it would check all relevant comparisons, make sure the IEquatable<T> is implemented too, use reflection to check that equality operators are implemented, that GetHashCode is same if values are the same, that types are sealed for IEquatable<T>, etc. Lastly, I couldn't figure out how to write an assertion to check if two values are equal meaning the Compare method returns 0 RATHER than having you do that magic to check if two object instances are equivalent.

**Comment by dennisdoomen** [comment]
Thanks for the feedback. What you are suggestion sounds like you are using FA to verify the correct behavior of an individual `IComparable` implementation. In that case, my personal opinion is to make that explicitly clear by defining separate test cases for each scenario. The support that FA offers for `IComparable` is just to be able to _use_ implementations of `IComparable`. In fact, in my own projects, we rarely test that small anymore. We general see this as an implementation detail that is covered by the code that uses it. 

W.r.t. to comparing two objects for equality, if the subject implements `IComparable`, `Should().Be()` does exactly [that](https://github.com/fluentassertions/fluentassertions/blob/9792f618f1cd4c9d880b570dae6e554bd345af61/Src/FluentAssertions/Numeric/NumericAssertions.cs#L45).

**Comment by jmagaram** [comment]
OK I get it.
