### ISSUE TITLE
Add version of StringAssertions.Contain that allows specifying the number of times a substring should occur.

### ISSUE THREAD

**Issue by basbossink** [fluentassertions/fluentassertions#818]
Currently StringAssertions has no easy way of asserting that a substring should occur a particular number of times within a string. Imagine the syntax could be something like

    actual.Shoud().Contain("Fred", Twice, "Fred is important");

or

    actual.Should().Contain("Fred").Twice("Fred is important");

or

    actual.Should().Contain("Fred", 2, "Fred is important");

**Comment by jnyrup** [comment]
How about the `Match` assertion?

This asserts that `actual` has at least two *distinct* `Fred`s in it.
```csharp
actual.Should().Match("*Fred*Fred*", "Fred is important");
```

I emphasize distinct because I feel it could be difficult to get such an API right.
E.g. does `aaa` contain `aa` one or two times?

Would `actual.Should().Contain(expectedSubstring, k)` mean that `actual` should contain `expectedSubstring` *exactly* `k` times or *at least* `k` times?

Just for the record a very unreadable way to assert that `actual` contains exactly two distinct `Fred`s.
```csharp
actual.Should().MatchRegex("^(?:(?!Fred).)*Fred(?:(?!Fred).)*Fred(?:(?!Fred).)*$", "Fred is important");
```

**Comment by basbossink** [comment]
Thanks for the explanation, in this case the `Match` assertion is a good alternative. The second suggestion is imho a little bit more readable. In my example I would expect `Twice` to mean exactly two times. I could also image something like:

    actual.Should().Contain("Fred").AtLeast.Twice("Fred is important");
    actual.Should().Contain("Fred").AtMost.Twice("Fred is important");
    actual.Should().Contain("Fred").Exactly.Twice("Fred is important"); //which would be equivalent to:
    actual.Should().Contain("Fred").Twice("Fred is important");

Given that my request can by implemented using the `Match`, I would treat this request as a _light suggestion_ and handle it as you see fit. Thanks for your efforts.

**Comment by dennisdoomen** [comment]
It could work, provided that `Fred` does indeed exists in that `actual`. The successive checks would just apply additional checks. But then we should also add those extensions to all related assertions.

**Comment by mkolumb** [comment]
Hi,

I would like to do this.
But I think we should do it using the following api
`actual.Should().ContainExactly("Fred", 2, "Fred is important");`

API proposed above is more readable, but I think it will be a breaking change.

**Comment by mkolumb** [comment]
Of course I can implement other similar methods like e.g. `ContainAtLeast` if proposed API will be accepted.

**Comment by dennisdoomen** [comment]
I personally prefer the proposal of @basbossink

**Comment by jnyrup** [comment]
We could do something similar to FakeItEasy's [assertion syntax](https://fakeiteasy.readthedocs.io/en/stable/assertion/):

```c#
actual.Should().Contain("Fred", 4, Times.Exactly);
actual.Should().Contain("Fred", 4, Times.OrLess);
actual.Should().Contain("Fred", 4, Times.OrMore);
```

I'm still interested in the discussion about whether "aaa" contains "aa" two or three times.

**Comment by mkolumb** [comment]
Good point.
I think that "aaa" contains "aa" only once.
Imagine you have 3 apples.
If you want to give someone 2 apples, you can do it only once.

**Comment by mkolumb** [comment]
I have one more proposal

```
actual.Should().Contain("Fred", AtLeast.Twice, "Fred is important");
actual.Should().Contain("Fred", AtLeast.Times(2), "Fred is important");
actual.Should().Contain("Fred", MoreThan.Twice, "Fred is important");
actual.Should().Contain("Fred", MoreThan.Times(2), "Fred is important");
actual.Should().Contain("Fred", Exactly.Twice, "Fred is important");
actual.Should().Contain("Fred", Exactly.Times(2), "Fred is important");
```

**Comment by dennisdoomen** [comment]
I still prefer the more fluent proposal of @basbossink

**Comment by mkolumb** [comment]
I understand.
If I should implement this version, the problem of current `Contain `method still exists.
How I should solve this?
And the second issue is mentioned by @jnyrup 

> whether "aaa" contains "aa" once or twice

**Comment by mkolumb** [comment]
In case of `Contain` method problem I see 2 solutions:
1. Assumption that `Contain` should throw **always**  if expected string wouldn't be found (leave as it is)
2. Replace the current `Contain` by something like that `actual.Should().Contain("Fred").Any`

Personally, I think that FluentAssertions should be careful when introducing breaking changes.
So my suggestion is to implement 1 version.

I have almost completed the feature, but I would like to adjust the API to final version before sending PR.

**Comment by mkolumb** [comment]
Hi guys, I created the pull request #962
