### ISSUE TITLE
collection.BeEquivalentTo(1, 2, 3) is order-dependant

### ISSUE THREAD

**Issue by Gerboa** [fluentassertions/fluentassertions#822]
`BeEquivalentTo(params object[] expectations)` is order-dependant but the versions that take `IEnumerable` are not.

**Comment by jnyrup** [comment]
@Gerboa Can you provide an example that show the described behaviour?

**Comment by Gerboa** [comment]
Sorry for the delay (on holiday), I've not been able to reproduce the problem; it's working **perfectly** now.

Apologies for the red herring.

**Comment by dennisdoomen** [comment]
No problem. Thanks for taking the time to report this.
