### ISSUE TITLE
BeEquivalent doesn't handle member of base type correct

### ISSUE THREAD

**Issue by MartinDemberger** [fluentassertions/fluentassertions#826]
When I have a member with a base type and the subclasses have differences this isn't recognized correct.

I expect the following two tests to fail:

        public class Owner
        {
            public BaseClass Member { get; set; }
        }

        public class BaseClass
        {
            public string Name { get; set; }
        }

        public class SubClass1 : BaseClass
        {
            public string Value { get; set; }
        }

        public class SubClass2 : BaseClass
        {
            public int Value { get; set; }
        }

        [Fact]
        [Trait(TestConstants.Category, TestConstants.UnitTest)]
        public void Test()
        {
            var owner0 = new Owner()
            {
                Member = new SubClass1() { Name = "Name",  Value = "test"},
            };
            var owner1 = new Owner()
            {
                Member = new SubClass2() { Name = "Name", Value = 14},
            };

            owner0.Should().BeEquivalentTo(owner1);
        }

        [Fact]
        [Trait(TestConstants.Category, TestConstants.UnitTest)]
        public void Test2()
        {
            var owner0 = new Owner()
            {
                Member = new SubClass1() { Name = "Name", Value = "test" },
            };
            var owner1 = new Owner()
            {
                Member = new SubClass1() { Name = "Name", Value = "other" },
            };

            owner0.Should().BeEquivalentTo(owner1);
        }

**Comment by dennisdoomen** [comment]
Nope. Your subject-under-test is of type `Owner` and you compare it with an `Owner`, so FA assumes that's what you intended. You can use `IncludingAllRuntimeProperties` to fix that. Also make sure you check out the documentation at https://fluentassertions.com/documentation/#object-graph-comparison
