### ISSUE TITLE
Migrating from v4.x to v5.x - anything important to consider?

### ISSUE THREAD

**Issue by drauch** [fluentassertions/fluentassertions#830]
We want to upgrade all our projects from 4.x to 5.x. Are there any pitfalls? Important things to consider? Incompatibilities we need to know of? Tips & tricks for migrating?

I have only found this article https://www.continuousimprover.com/2018/02/fluent-assertions-50-best-unit-test.html but I was hoping for something more substantial.

Best regards,
D.R.

**Comment by dennisdoomen** [comment]
Check the last paragraph called _Upgrading tips_ and the comment. They might ease the burden.

**Comment by jnyrup** [comment]
@drauch I hope you've found what you needed to prepare and upgrade to 5.x.
If not, feel free to reopen.
