### ISSUE TITLE
Controlling comparison options on sub-components of an object graph

### ISSUE THREAD

**Issue by Tragedian** [fluentassertions/fluentassertions#834]
I use Fluent Assertions primarily for its ability to perform value-based comparison over object graphs. This is very useful when building systems which are primarily concerned with data-flow.

Whilst the `options.Include` and `options.Exclude` methods are able to trivially set up comparison rules for the top-level object of the graph, it can be a lot trickier to set them up for child nodes of the graph, particularly when collections are involved. I often wind up with syntax like:

```
actual.Should().BeEquivalentTo(
    expected,
    options => options
        .Exclude(o => o.Id)
        .Exclude(o => o.SelectedMemberInfo.DeclaringType == typeof(ChildType)
            && o.SelectedMemberInfo.Name = nameof(ChildType.Identifier))
```

This doesn't produce very readable code or readable output in the printed options:

```
- Exclude member actual.Id
- Exclude member when ((member.SelectedMemberInfo.DeclaringType == SomeNamespace.ChildType) AndAlso (member.SelectedMemberInfo.Name == "Identifier"))
```

Is there a way to do this more easily? If not, I'd love to add a syntax like:

```
    options => options.ForType<ChildType>(childOptions => childOptions.Exclude(o => o.Id))
```

**Comment by jnyrup** [comment]
Fluent Assertions supports creating and attaching custom implementations of `IEquivalencyStep`, which are used when trying to determine if two objects are equivalent.
* The feature is explained in the [document](https://fluentassertions.com/extensibility/), the [tests](https://github.com/fluentassertions/fluentassertions/blob/master/Tests/Shared.Specs/ExtensibilityRelatedEquivalencySpecs.cs) has some simple examples and the [source](https://github.com/fluentassertions/fluentassertions/tree/master/Src/FluentAssertions/Equivalency) has the real world implementations.

**Comment by dennisdoomen** [comment]
@Tragedian does this answer your question?

**Comment by Tragedian** [comment]
I think I can use `IMemberSelectionRule` to achieve what I want, but I'm not clear on exactly how I would improve the test output.
