### ISSUE TITLE
AssertionScope does not work with GenericCollectionAssertions

### ISSUE THREAD

**Issue by flabordec** [fluentassertions/fluentassertions#835]
I would expect the following code to create two assertions, but it only creates one: 

```
using (new AssertionScope())
{
    var values = new Dictionary<string, int>();
    values.Should().ContainKey("hi");
    values.Should().ContainKey("bye");
}
```

It seems to be widespread for most collection assertions: 

```
using (new AssertionScope())
{
    int[] a = new[] {1, 2, 3};
    int[] b = new[] {1, 2};
    int[] c = new[] {3, 4};
    a.Should().BeEquivalentTo(b);
    b.Should().BeEquivalentTo(c);
}
```

I'm using FluentAssertions 5.3.

**Comment by dennisdoomen** [comment]
The entire point of `AssertionScope` is to collect all assertion failures and throw them as one exception.

**Comment by flabordec** [comment]
Exactly, so if it were working correctly, then the result would be two assertions captured: 

```
Xunit.Sdk.XunitException
Expected values {empty} to contain key "hi".
Expected values {empty} to contain key "bye".
```

But instead only the first exception is captured: 

```
Xunit.Sdk.XunitException
Expected values {empty} to contain key "hi".
```

**Comment by flabordec** [comment]
Note that this is some specific problem with the `GenericDictionaryAssertions<K,V>` class and with other collection assertions, like the array one. 

The following code: 
```
using (new AssertionScope())
{
    var values = new Dictionary<string, int>();
    true.Should().BeFalse();
    values.Should().ContainKey("hi");
    values.Should().ContainKey("bye");
}
```

Will correctly capture the first assertion, and then bail after the second one: 

```
Xunit.Sdk.XunitException
Expected boolean to be false, but found True.
Expected values {empty} to contain key "hi".
```

**Comment by jnyrup** [comment]
@flabordec Thanks for reporting this.
There is a bug in `ContainKey` where it tries to use the key even if it didn't exist, which caused a `KeyNotFoundException` and messing with the `AssertionScope`.

Just to be sure, you're only having problems with `Using(new AssertionScope)` when using `ContainKey` right?

**Comment by flabordec** [comment]
Yes, and I found the same behavior at least with `BeEquivalentTo` as well, for example: 

```
using (new AssertionScope())
{
    int[] a = new[] {1, 2, 3};
    int[] b = new[] {1, 2};
    int[] c = new[] {3, 4};
    a.Should().BeEquivalentTo(b);
    b.Should().BeEquivalentTo(c);
}
```

Only shows:

```
Xunit.Sdk.XunitException
Expected a to be a collection with 2 item(s), but {1, 2, 3}"
"contains 1 item(s) more than"
"{1, 2}.
Expected item[0] to be 3, but found 1.
Expected item[1] to be 4, but found 2.
```

But I would expect it to show:

```
Xunit.Sdk.XunitException
Expected a to be a collection with 2 item(s), but {1, 2, 3}"
"contains 1 item(s) more than"
"{1, 2}.
Expected item[0] to be 3, but found 1.
Expected item[1] to be 4, but found 2.

Xunit.Sdk.XunitException
Expected item[0] to be 3, but found 1.
Expected item[1] to be 4, but found 2.
```

**Comment by jnyrup** [comment]
Fluent Assertions gives different failure messages on `BeEquivalentTo` when the collections have same/different number of items.

```csharp
using (new AssertionScope())
{
    int[] a = new[] { 1 };
    int[] b = new[] { 2 };
    int[] c = new[] { 3 };
    a.Should().BeEquivalentTo(b);
    b.Should().BeEquivalentTo(c);
}
```

outputs:
```
Expected item[0] to be 2, but found 1.
Expected item[0] to be 3, but found 2.
```

and
```csharp
using (new AssertionScope())
{
    int[] a = new[] { 1 };
    int[] b = new[] { 2, 3 };
    int[] c = new[] { 4, 5, 6 };
    a.Should().BeEquivalentTo(b);
    b.Should().BeEquivalentTo(c);
}
```

outputs:
```
Expected a to be a collection with 2 item(s), but {1}"
"contains 1 item(s) less than"
"{2, 3}.
Expected b to be a collection with 3 item(s), but {2, 3}"
"contains 1 item(s) less than"
"{4, 5, 6}.
```

So in your example `a` and `b` have a *different* number of items, while `b` and `c` have the *same* number of items.
`a.Should().BeEquivalentTo(b);` gives 
```
Expected a to be a collection with 2 item(s), but {1, 2, 3}"
"contains 1 item(s) more than"
"{1, 2}.
```

and `b.Should().BeEquivalentTo(c);` gives:
```
Expected item[0] to be 3, but found 1.
Expected item[1] to be 4, but found 2.
```

**Comment by flabordec** [comment]
Oh, I get it, I was expecting the messages to be separated by a new line or something but I understand that one now 😆
