### ISSUE TITLE
Equivalency strategy

### ISSUE THREAD

**Issue by mkhalast** [fluentassertions/fluentassertions#849]
It would be good to have a possibility to define custom strategy for equivalency rules and be able to operate with runtime types instead of manually registering a list of entities with ComparingByMembers<T> or ComparingByValue<T> at compile-time

**Comment by dennisdoomen** [comment]
Did you read https://fluentassertions.com/extensibility/?

**Comment by mkhalast** [comment]
yes, i have read it, thank you, but EquivalencyStep is an actual comparison and not just equivalency strategy. How do I decorate existing comparison than?

**Comment by dennisdoomen** [comment]
Does this answer your question?

**Comment by jnyrup** [comment]
Closed due to inactivity, please re-open if you have more to add.
