### ISSUE TITLE
AllBeEquivalentTo not working with Generic Lists

### ISSUE THREAD

**Issue by markdemich** [fluentassertions/fluentassertions#855]
### Description

Comparing two identical generic lists using AllBeEquivalentTo failing.

### Complete minimal example reproducing the issue
``` csharp
     class Dto
    {
        public string Name { get; set; }
        public string Value { get; set; }
    }
        [TestMethod]
        public void TestBug()
        {
            var list1 = new List<Dto>
            {
                new Dto() {Name = "ABC", Value = "123"}
            };

            var list2 = new List<Dto>
            {
                new Dto() {Name = "ABC", Value = "123"}
            };

            list1.Should().AllBeEquivalentTo(list2);

        }

```
NOTE: This is fails if I do this.
```csharp
list1.Should().AllBeEquivalentTo(list1);
````
### Expected behavior:
I believe this should pass.

### Actual behavior:
Fails with a message that looks like this.
```
Expected item[0] to be {Tdx.Puf.Conversion.Tests.Dto
   {
      Name = "ABC"
      Value = "123"
   }}, but found 

Tdx.Puf.Conversion.Tests.Dto
{
   Name = "ABC"
   Value = "123"
}.

With configuration:
- Use declared types and members
- Compare enums by value
- Include all non-private properties
- Include all non-private fields
- Match member by name (or throw)
- Try conversion of all members. 
- Try conversion of all members. 
- Be strict about the order of items in byte arrays

```
### Versions

* Fluent Assertions 5.3.2.0
* .Net 4.7.1

**Comment by dennisdoomen** [comment]
Thanks for reporting this and the great explanation. What you are asking FA to is to compare each item in the first list with the entire list. Instead, you should be using `list1.Should().BeEquivalentTo(list1);`. This was one of the (documented) breaking changes in version 5.

**Comment by jnyrup** [comment]
Strictly speaking, it's also in the error message.
It expected `item[0]` to be equivalento to `{ Dto{...} }`, but found `Dto{...}`. 
The outer curly braces is our way to format collections.
So it failed to compare `item[0]`, which is a `Dto`, to `{ Dto{...} }` which is a list of `Dto`'s.

**Comment by markdemich** [comment]
The reason I was using AllBeEquivalentTo was because on my real test case BeEquivalentTo was actually passing for cases where they shouldn't be.  I thought I replicated with my example above, but I just tried changing it to BeEquivalentTo and it passed.  I then changed Value to 1234 in one of the objects and it did indeed break, so my test is not exactly replicating my issue.  I'm going to post my code snippet that's NOT failing, but it should.  Maybe you can spot the problem.  I appreciate your help.

```csharp
        [TestMethod]
        public void GetContentList_SimpleText_ReturnsOneParagraph()
        {
            var expectedContentList = new List<BlockContentItem>()
            {
                new TextBlock
                {
                    InlineContents = new InlineContents(new List<InlineContentItem>()
                    {
                        new TextContentItem()
                        {
                            Text = "ABCBAD"
                        }
                    })
                }
            };
            var testContentList = new List<BlockContentItem>()
            {
                new TextBlock
                {
                    InlineContents = new InlineContents(new List<InlineContentItem>()
                    {
                        new TextContentItem()
                        {
                            Text = "ABC"
                        }
                    })
                }
            };
            testContentList.Should().BeEquivalentTo(expectedContentList ,options => options.WithTracing());
        }
```
This is PASSing but it should not be.  This is a slightly simplified example compared to where I found the initial problem so I'm hoping you can spot an issue.  If you need anymore details, please let me know.

**Comment by jnyrup** [comment]
You're using `List<BlockContentItem>` and `List<InlineContentItem>` and insert `TextBlock`s, and `TextContentItem`s.
Per default `BeEquivalentTo` will use the compile-time types, so it will only compare the properties declared on `BlockContentItem` and InlineContentItem`.

To use the run-time types use [`RespectingRuntimeTypes()`](https://fluentassertions.com/documentation/#compile-time-types-vs-run-time-types).

**Comment by markdemich** [comment]
That did the trick. Thanks so much for the quick reply.  I'm going to close this.
