### ISSUE TITLE
fluentassertions website tips

### ISSUE THREAD

**Issue by Meir017** [fluentassertions/fluentassertions#866]
I'm working on the `fluentassertions.analyzers` project and I would like to have the ability to reference the actual website to show the improvement

Right not each test case is rendered in the following html
```html
<table class="code-table">
    ...
</table>
```
![image](https://user-images.githubusercontent.com/9786571/41727486-20d12b06-757d-11e8-8192-1c6caf9d24d5.png)

would it be possible to add an `id` attribute to each `table` element?

I'm not sure how the html is generated 😕

**Comment by jnyrup** [comment]
The html is generated by [Jekyll](https://jekyllrb.com/) from this [template](
https://github.com/fluentassertions/fluentassertions/blob/master/docs/_includes/assertion-comparison.html) written in [Liquid](https://shopify.github.io/liquid/).

From the [Liquid documentation](https://help.shopify.com/themes/liquid/objects/for-loops#forloop-index) it seems easy by using the `forloop.index`

Something like `id="example{{forloop.index}}"`.

**Comment by Meir017** [comment]
Looks to me I would need to add an `id` to each of test cases in the `tips` directory, am I right?

**Comment by jnyrup** [comment]
That is not necessary.
Are you working on it? 
Otherwise I almost got it working.

**Comment by Meir017** [comment]
I didn't start working on it yet, I'd be happy to see your solution 👏

**Comment by dennisdoomen** [comment]
Now #867 is merged, can we close this?
