### ISSUE TITLE
Collections.HaveElementAt object is doing reference equals and not checking for IEquatable

### ISSUE THREAD

**Issue by ericnewton76** [fluentassertions/fluentassertions#874]
### Description

(Collections).HaveElementAt is using System.Object.Equals for equality check, and not checking for IEquatable and invoking that if available.  Maybe there's a more appropriate method?

### Complete minimal example reproducing the issue

```csharp
[Test]
public void MyLibrary_Testing()
{
  // Arrange
  var testobj = new TestObject { Index = 0 };
  var testobjCollection = new TestObject[] { testobj };

  // Act
  var result = testobjCollection;

  // Assert
  result.Should().HaveElementAt(0, new TestObj { Index=0 }); //this doesnt work
  result.Should().HaveElementAt(0, testobjCollection[0]); //this works since references are equal
}
public class TestObject : IEquatable<TestObject>
{
  public int Index { get;set; }
  public bool Equals(TestObject other)
  {
    if(other==null) return false;
    if(this.Index != other.Index) return false;
    return true;
  }
}
```

### Expected behavior:

HaveElementAt looks at collection index 0, checks equality by invoking IEquatable since interface was present on TestObject.

### Actual behavior:

Output from test:
```text
Message: Expected 

RESTQueryTests.QueryableExtensions_AddPaging_Tests+TestObject
{
   Index = 0
} at index 0, but found 

RESTQueryTests.QueryableExtensions_AddPaging_Tests+TestObject
{
   Index = 0
}.
```

Clearly basically the same object from IEquatable standpoint, but two different objects from ReferenceEquals standpoint.

### Versions

* Which version of Fluent Assertions are you using? 5.4.1
* Which .NET runtime and version are you targeting? Net Framework 4.5.2

**Comment by ericnewton76** [comment]
In the process of generating commit here to review actual test, will update this message when finished.

**Comment by ericnewton76** [comment]
ObjectAssertions.Be doesnt seem to check for IEquatable either
```c#
		[Test]
		public void TestObject_Equals()
		{
			//arrange
			var testobj1 = new TestObject { Index = 0 };

			//act
			var testobj2 = new TestObject { Index = 0 };

			//assert
			testobj2.Should().NotBeSameAs(testobj1);
			testobj2.Should().Be(testobj1); //fails
		}

		class TestObject : IEquatable<TestObject>
		{
			public int Index { get; set; }

			public bool Equals(TestObject other)
			{
				if(other == null) return false;
				if(this.Index != other.Index) return false;
				return true;
			}
		}
```

https://github.com/ericnewton76/RESTQuery/blob/1d2dbdc3f57d621e6fc64ccf833c76bd3e82d1b5/src/RESTQueryTests/QueryableExtensions_AddPaging_Tests.cs#L103

**Comment by dennisdoomen** [comment]
Are you saying that your object implements `IEquatable`, but does not override `Equals`?

**Comment by ericnewton76** [comment]
Yes, just figured that out when I added `override Equals` to TestObj:

https://github.com/ericnewton76/RESTQuery/commit/b562191fe28e0712df3f65d5d9f4d5c0bccdc756
