### ISSUE TITLE
Add equivalent to xUnit's Assert.Collection

### ISSUE THREAD

**Issue by nzkeith** [fluentassertions/fluentassertions#882]
### Description

xUnit has this:

```csharp
Assert.Collection(things,
    thing =>
    {
        thing.Id.Should().Be(guid1);
        thing.Name.Should().Be("Thing1");
        thing.Attributes.Should().NotBeNull();
        thing.FullName.Should().MatchRegex("^Thing1 [^ ]+$");
    },
    thing =>
    {
        thing.Id.Should().Be(guid2);
        thing.Name.Should().Be("Thing2");
        thing.Attributes.Should().NotBeNull();
        thing.FullName.Should().MatchRegex("^Thing2 [^ ]+$");
    });
```

In some situations I find this style more expressive and/or succinct than the FluentAssertions methods that assert collection equality or equivalence.

Assert.Collection signature:

```csharp
/// <summary>
/// Verifies that a collection contains exactly a given number of elements, which meet
/// the criteria provided by the element inspectors.
/// </summary>
/// <typeparam name="T">The type of the object to be verified</typeparam>
/// <param name="collection">The collection to be inspected</param>
/// <param name="elementInspectors">The element inspectors, which inspect each element in turn. The
/// total number of element inspectors must exactly match the number of elements in the collection.</param>
public static void Collection<T>(IEnumerable<T> collection, params Action<T>[] elementInspectors)
```

### Proposed API

Per https://fluentassertions.slack.com/archives/C039Y2H7U/p1527880297000421

```csharp
things.Should().SatisfyRespectively(thing => { ... }, thing => { ... });
```

**Comment by nzkeith** [comment]
Related to #118

**Comment by nzkeith** [comment]
Original question on StackOverflow: https://stackoverflow.com/questions/50471950/fluentassertions-equivalent-to-xunit-assert-collection

**Comment by vanashimko** [comment]
@nzkeith, @dennisdoomen is there a place for `because` and `becauseArgs` in proposed API? Given that `becauseArgs` is `params`, we can't have both `inspectors` and `becauseArgs` as params...

(just was looking for something to pick up and found this one)

**Comment by jnyrup** [comment]
@vanashimko Good observation.
One should definitely be able to specify `because` and `becauseArgs` to be consistent with (most of ) the existing API.

**Comment by dennisdoomen** [comment]
Hmm, not sure how to accomplish that.

**Comment by jnyrup** [comment]
@dennisdoomen Take an `IEnumerable<Action<T>>` instead?

**Comment by vanashimko** [comment]
@jnyrup @dennisdoomen 
Can it be two overloads: one with `IEnumerable<Action<T>> inspectors` with because and args, and another one with `params Action<T>[] inspectors` without custom because?

**Comment by jnyrup** [comment]
On the surface having these two overloads looks good as they both work on `Action<T>`:
* `(params Action<T>[] inspectors)`
* `(IEnumerable<Action<T>> inspectors, string because, params string[] becauseArgs)`

We already do that approach for several assertions: `ContainKeys`, `NotContainKeys`, `ContainValues`, `NotContainValues`, and more.

For some context/related issues, where `params` has caused issues.
* `params object[]` overload for `BeEquivalentTo`, #1036
* Not having `because` and `becauseArgs` parameters #806

**Comment by vanashimko** [comment]
Thanks @jnyrup! After some playing around with message formatting I came up with the following:

Given:
```csharp
var customers = new Customer[]
{
    new Customer { Age = 21, Name = "John" },
    new Customer { Age = 22, Name = "Jane" }
};
customers.Should().SatisfyRespectively(
    thing =>
    {
        thing.Age.Should().Be(22);
        thing.Name.Should().Be("Jane");
    },
    thing =>
    {
        thing.Age.Should().Be(21);
        thing.Name.Should().Be("John");
    });
```
Fails with:
```
Expected customers to satisfy all inspectors, but some inspectors are not satisfied:
    At index 0:
        Expected customer.Age to be 22, but found 21
        Expected customer.Name to be "Jane", but "John" differs near "ohn" (index 1)
    At index 1:
        Expected customer.Age to be 21, but found 22
        Expected customer.Name to be "John", but "Jane" differs near "ane" (index 1)
```

Note, that there are no separators except line breaks. It allows to have nested `SatisfyRespectively` without any special hacking on fail messages. The only "hacking" required to be done is adding tab(s) at the beginning of each line.

Any concerns?

**Comment by jnyrup** [comment]
Contributed in #1043
