### ISSUE TITLE
Adding to Should().BeEquivalentTo() options.WithTracing() changes outcome of the test

### ISSUE THREAD

**Issue by sinapis** [fluentassertions/fluentassertions#903]
### Description

I got an error message which I think should not have happened, since the only difference is the order of the item and by default order shouldn't break equivalence. So I tried adding options.WithTracing() to understand what's going on, but then the test passes. This is the output without WithTracing():

> Message: Expected item[0] to be 
> 
> Deal.DealComputer+Deal
> {
>    Items = {Deal.DealComputer+SingleItem
>       {
>          Name = "Croissant"
>          Price = 12
>          Tags = {Pastry}
>       }, Deal.DealComputer+SingleItem
>       {
>          Name = "Cappuccino"
>          Price = 11
>          Tags = {HotDrink}
>       }}
>    Name = "Coffee + Pastry"
>    Price = 19
>    Tags = {HotDrink, Pastry}
> }, but found 
> 
> Deal.DealComputer+Deal
> {
>    Items = {Deal.DealComputer+SingleItem
>       {
>          Name = "Cappuccino"
>          Price = 11
>          Tags = {HotDrink}
>       }, Deal.DealComputer+SingleItem
>       {
>          Name = "Croissant"
>          Price = 12
>          Tags = {Pastry}
>       }}
>    Name = "Coffee + Pastry"
>    Price = 19
>    Tags = {HotDrink, Pastry}
> }.
> 
> With configuration:
> - Use declared types and members
> - Compare enums by value
> - Include all non-private properties
> - Include all non-private fields
> - Match member by name (or throw)
> - Without automatic conversion.
> - Without automatic conversion.
> - Be strict about the order of items in byte arrays

### Complete minimal example reproducing the issue

```csharp

public enum Tag
    {
        HotDrink,
        Pastry,
        Breakfast
    }

public interface Dish
        {
            string Name { get; set; }
            int Price { get; set; }
            IEnumerable<Tag> Tags { get; set; }
        }

        public class SingleItem : Dish, IEquatable<SingleItem>
        {
            public string Name { get; set; }
            public int Price { get; set; }
            public IEnumerable<Tag> Tags { get; set; }

            public override bool Equals(object obj)
                => Equals(obj as SingleItem);

            public bool Equals(SingleItem other) 
                => !(other is null) &&
                   Name == other.Name &&
                   Price == other.Price &&
                   Tags.SequenceEqual(other.Tags);

            public override int GetHashCode() 
                => HashCode.Combine(Name, Price, Tags);

            public static bool operator ==(SingleItem item1, SingleItem item2)
            {
                if (item1 is null)
                {
                    return item2 is null;
                }

                return item1.Equals(item2);
            }

            public static bool operator !=(SingleItem item1, SingleItem item2)
                => !(item1 == item2);
        }

        public class Deal : Dish, IEquatable<Deal>
        {
            public string Name { get; set; }
            public int Price { get; set; }
            public IEnumerable<Tag> Tags { get; set; }
            public IEnumerable<SingleItem> Items { get; set; }

            public override bool Equals(object obj) => Equals(obj as Deal);

            public bool Equals(Deal other)
            {
                return !(other is null) &&
                       Name == other.Name &&
                       Price == other.Price &&
                       Tags.SequenceEqual(other.Tags) &&
                       Items.SequenceEqual(other.Items);
            }

            public override int GetHashCode() => HashCode.Combine(Name, Price, Tags, Items);

            public static bool operator ==(Deal deal1, Deal deal2)
            {
                if (deal1 is null)
                {
                    return deal2 is null;
                }

                return deal1.Equals(deal2);
            }

            public static bool operator !=(Deal deal1, Deal deal2) => !(deal1 == deal2);
        }

        readonly SingleItem cappuccino = new SingleItem { Name = "Cappuccino", Price = 11, Tags = new[] { Tag.HotDrink }};
        readonly SingleItem croissant = new SingleItem { Name = "Croissant", Price = 12, Tags = new[] { Tag.Pastry } };
        readonly SingleItem tea = new SingleItem { Name = "Tea", Price = 8, Tags = new[] { Tag.HotDrink } };
        readonly SingleItem datesPastry = new SingleItem { Name = "Dates Pastry", Price = 10, Tags = new[] { Tag.Pastry } };
        readonly Deal CoffeeAndPastryDeal = new Deal { Name = "Coffee + Pastry", Price = 19, Tags = new [] { Tag.HotDrink, Tag.Pastry } };

        [Fact]
        public void FourItemsSingleDeal()
{
            var items = new[] {
                tea,
                datesPastry,
                cappuccino,
                croissant,
            };

            var deals = new[] { CoffeeAndPastryDeal };

            var completedDeal1 = CoffeeAndPastryDeal.DeepClone();
            completedDeal1.Items = new[] { croissant, cappuccino };
            var expected = new Dish[]
            {
                completedDeal1,
                tea,
                datesPastry
            };

            var completedDeal2 = CoffeeAndPastryDeal.DeepClone();
            completedDeal2.Items = new[] { cappuccino, croissant };

            var actual =
                new Dish[]
            {
                completedDeal2,
                tea,
                datesPastry
            };

            actual.Should().BeEquivalentTo(expected, o => o.WithTracing()); // passes
            actual.Should().BeEquivalentTo(); //fails
}
```

### Expected behavior:

I expect options.WithTracing() to not affect the outcome of tests

### Actual behavior:

options.WithTracing() affects the outcome of tests

### Versions

* Which version of Fluent Assertions are you using? 5.4.1
* Which .NET runtime and version are you targeting? .net core 2.1
* For deep cloning I'm using nuget DeepCloner 0.10.2

**Comment by jnyrup** [comment]
Three things are happening here, none of which are related to `WithTracing()`.

1. `actual.Should().BeEquivalentTo();` should be `actual.Should().BeEquivalentTo(expected);`
2. Fluent Assertions will use your overload of `bool Equals(object)` if available, and `Deal.Equals(object)` specifies that the order of items matters, as you use `Items.SequenceEquals(other.Items)`.
3. By default Fluent Assertions [uses the compile time types](https://fluentassertions.com/documentation/#compile-time-types-vs-run-time-types).
In your case that means that `actual` and `expected` are compared by the members defined in `Dish` and not the additional defined in `Deal`.

Your test case was not quite minimal, so it took me some time to figure out.
When debugging an issue, try to remove the noise.
Copy the problematic code into a fresh project/solution and remove all irrelevant code.
That makes it easier to spot the error.

```c#
public interface Dish
{
    string Name { get; set; }
}

public class SingleItem : Dish
{
    public string Name { get; set; }
}

public class Deal : Dish, IEquatable<Deal>
{
    public string Name { get; set; }
    public IEnumerable<SingleItem> Items { get; set; }

    public override bool Equals(object obj) => Equals(obj as Deal);

    public bool Equals(Deal other)
    {
        return !(other is null) &&
                Name == other.Name
                && Items.SequenceEqual(other.Items);
    }

    public override int GetHashCode() => HashCode.Combine(Name, Items);
}

[Fact]
public void FourItemsSingleDeal()
{
    var cappuccino = new SingleItem { Name = "Cappuccino" };
    var croissant = new SingleItem { Name = "Croissant" };

    var completedDeal1 = new Deal
    {
        Items = new SingleItem[] { croissant, cappuccino }
    };

    var completedDeal2 = new Deal
    {
        Items = new SingleItem[] { cappuccino, croissant }
    };

    completedDeal1.Should().BeEquivalentTo(completedDeal2, opt => opt.WithTracing()); // fails
    completedDeal1.Should().BeEquivalentTo(completedDeal2); // fails
}
```

**Comment by sinapis** [comment]
First, thank you for taking the time to look into my issue!
Second - Sorry, you are right. I had a typo there where I missed "expected". 

However, I'm still seeing the same behavior with the test I pasted here (after adding "expected") - when running 
`completedDeal1.Should().BeEquivalentTo(completedDeal2, opt => opt.WithTracing());  `
it passes while 
`completedDeal1.Should().BeEquivalentTo(completedDeal2);`
fails.

Can you explain what's going on?

**Comment by jnyrup** [comment]
Have a look at my second bullet point. 
`Deal.Equals` uses `SequenceEquals`, hence the order of items in `Items` matters to you.
 Fluent Assertions will not try to guess how to compare objects when you have explicitly specified how to compare them.

**Comment by sinapis** [comment]
Thank you for pointing this out.
I understood that point, but I do not understand why would the test pass when I add WithTracing().
The test should have failed always, since the order is incorrect in both cases.

**Comment by jnyrup** [comment]
That sounds like my third bullet point about compile time vs runtime types.
Here's the console application I ended up with when I was debugging your example.
There was no change in results when using `WithTracing()`.

[ConsoleApp47.zip](https://github.com/fluentassertions/fluentassertions/files/2321871/ConsoleApp47.zip)

```c#
using FluentAssertions;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConsoleApp47
{
    class Program
    {
        public static void Main() => new Program().FourItemsSingleDeal();

        public interface Dish
        {
            string Name { get; set; }
        }

        public class SingleItem : Dish
        {
            public string Name { get; set; }
        }

        public class Deal : Dish, IEquatable<Deal>
        {
            public string Name { get; set; }
            public IEnumerable<SingleItem> Items { get; set; }

            public override bool Equals(object obj) => Equals(obj as Deal);

            public bool Equals(Deal other)
            {
                return !(other is null) &&
                        Name == other.Name
                        && Items.SequenceEqual(other.Items);
            }

            public override int GetHashCode() => HashCode.Combine(Name, Items);
        }

        public void FourItemsSingleDeal()
        {
            var cappuccino = new SingleItem { Name = "Cappuccino" };
            var croissant = new SingleItem { Name = "Croissant" };

            var completedDeal1 = new Deal { Items = new SingleItem[] { croissant, cappuccino } };
            var completedDeal2 = new Deal { Items = new SingleItem[] { cappuccino, croissant } };

            completedDeal1.Should().BeEquivalentTo(completedDeal2, opt => opt.WithTracing()); // fails
            completedDeal1.Should().BeEquivalentTo(completedDeal2); // fails

            completedDeal1.As<Dish>().Should().BeEquivalentTo(completedDeal2.As<Dish>(), opt => opt.WithTracing()); // passes
            completedDeal1.As<Dish>().Should().BeEquivalentTo(completedDeal2.As<Dish>()); // passes

            completedDeal1.As<Dish>().Should().BeEquivalentTo(completedDeal2.As<Dish>(), opt => opt.WithTracing().RespectingRuntimeTypes()); // fails
            completedDeal1.As<Dish>().Should().BeEquivalentTo(completedDeal2.As<Dish>(), opt => opt.RespectingRuntimeTypes()); // fails

            var expected = new Deal[] { completedDeal1 };
            var actual = new Deal[] { completedDeal2 };

            actual.Should().BeEquivalentTo(expected, o => o.WithTracing()); // fails
            actual.Should().BeEquivalentTo(expected); // fails

            actual.Cast<Dish>().Should().BeEquivalentTo(expected.Cast<Dish>(), opt => opt.WithTracing()); // passes
            actual.Cast<Dish>().Should().BeEquivalentTo(expected.Cast<Dish>()); // passes

            actual.Cast<Dish>().Should().BeEquivalentTo(expected.Cast<Dish>(), opt => opt.WithTracing().RespectingRuntimeTypes()); // fails
            actual.Cast<Dish>().Should().BeEquivalentTo(expected.Cast<Dish>(), opt => opt.RespectingRuntimeTypes()); // fails
        }
    }
}
```

**Comment by sinapis** [comment]
Since your console application does not reproduces the issue, I do not think it can answer my question.

Attached is a minimal repro (well, as minimal as I could make it). 
[Test.zip](https://github.com/fluentassertions/fluentassertions/files/2321901/Test.zip)

Can you please execute and let me know if you can see the problem on you machine?

**Comment by jnyrup** [comment]
I see a difference in your example and without having looked at the internals of `WithTracing()` so far, I agree it looks suspicious.

But *please* make a minimal example. 
* You didn't even remove the unused variables.
* Is the dependency on DeepCloner really necessary to reproduce the issue?
* I could e.g. remove the `Price` and tag property.

**Comment by sinapis** [comment]
yes, deep clone is needed for repro.
I shaved off some more. only one property left on Dish. And Deal also have items.

Please let me know if now it's good enough.
[Test.zip](https://github.com/fluentassertions/fluentassertions/files/2322753/Test.zip)

**Comment by jnyrup** [comment]
After shaving of the last noise I found the cause.

`actual.Should().BeEquivalentTo(expected, o => o.WithTracing())` resolves to the generic overload of `BeEquivalentTo`
uses 

```c#
BeEquivalentTo<TExpectation>(
    IEnumerable<TExpectation> expectation,
    Func<EquivalencyAssertionOptions<TExpectation>, EquivalencyAssertionOptions<TExpectation>> config, 
    string because = "", 
    params object[] becauseArgs)
```

while `actual.Should().BeEquivalentTo(expected)` is resolved to a non-generic overload of `BeEquivalentTo`
```c#
BeEquivalentTo(params object[] expectations)
```

The first one passes not because of `o => o.WithTracing()`, using `o => o` gives the same result, but because it sees that `expected` is of type `Dish[]` and `Dict` only defines `Name`.

The second fails as expected because the overload is non-generic and it uses the runtime types of `expected`.

This is indeed confusion behavior.
Until we hopefully land a fix, you can workaround it by declarting `expected` as `List<Dish>` instead of `Dish[]`.


Btw, `DeepCloner` was not necessary to reproduce the issue, here's what I would regard a minimal example.
```c#
[Fact]
public void TwoItemsSingleDeal()
{
    var cappuccino = new SingleItem { Name = "Cappuccino" };
    var croissant = new SingleItem { Name = "Croissant" };

    var completedDeal1 = new Deal
    {
        Items = new[] { croissant, cappuccino }
    };

    var completedDeal2 = new Deal
    {
        Items = new[] { cappuccino, croissant }
    };

    var expected = new Dish[] { completedDeal1 };

    var actual = new Dish[] { completedDeal2 };

    actual.Should().BeEquivalentTo(expected, o => o.WithTracing()); // passes
    actual.Should().BeEquivalentTo(expected, o => o); // passes
    actual.Should().BeEquivalentTo(expected.ToList()); // passes
    actual.Should().BeEquivalentTo(expected); // fails
}
```

**Comment by jnyrup** [comment]
@sinapis The fixes I could come up with to solve your problem potentially breaks other peoples code.
We won't break code without bumping the major version and I don't imagine that will happen anytime soon.
For now you'll have to use a workaround if you want to avoid that `BeEquivalentTo` resolves to the non-generic overload.
