### ISSUE TITLE
Equivalency of enums

### ISSUE THREAD

**Issue by Robelind** [fluentassertions/fluentassertions#905]
```csharp
enum Color { Red, Green, Blue };

IEnumerable<Color> a = new[] { Color.Red, Color.Green, Color.Blue };
IEnumerable<Color> b = new[] { Color.Red, Color.Blue, Color.Green };

a.Should().BeEquivalentTo(b);
```

### Expected behavior:
Test should fail.

### Actual behavior:
Test doesn't fail

### Versions
* Fluent Assertions 5.1.2
* .NET framework 4.6.1

**Comment by jnyrup** [comment]
This is [intended behavior](https://fluentassertions.com/documentation/#ordering) for `BeEquivalentTo`.
In general to take the order into account, you can use:
```c#
a.Should().BeEquivalentTo(b, opt => opt.WithStrictOrdering());
```

In your particular example you can also use `Equal`
```c#
a.Should().Equal(b);
```
