### ISSUE TITLE
Allow pattern matching in `SelfReferencingCollectionAssertions.Contain()`

### ISSUE THREAD

**Issue by Balfa** [fluentassertions/fluentassertions#912]
### Description

When casting items in a collection, I can either do `new object[] {"hi", "bye"}.Any(x => x is string s && s.Length > 2 && s.StartsWith("b")).Should().BeTrue();`, which misses out on the benefits of Fluent Assertions' rich error messaging, or I can do `new object[] {"hi", "bye"}.Should().Contain(x => x is string && ((string)x).Length > 2 && ((string)x).StartsWith("b"));`, which misses out on C#7's pattern matching, which makes things a little nicer and cleaner.

### Complete minimal example reproducing the issue

```csharp
new object[] {"hi", "bye"}.Should().Contain(x =>
  x is string && ((string)x).Length > 2 && ((string)x).StartsWith("b"));
new object[] {"hi", "bye"}.Should().Contain(x =>
  x is string s && s.Length > 2 && s.StartsWith("b"));
```

### Expected behavior:

Both lines build and pass the test

### Actual behavior:

A compile time error is encountered on the second line:
Error	CS8122	An expression tree may not contain an 'is' pattern-matching operator.

### Versions

* Fluent Assertions 5.4.1
* .NET framework 4.6.1

### Additional Information

I see that `Contain()` takes an `Expression<Func<T, bool>>`, whereas `.Any()` takes just a `Func<TSource, bool>`. I'm familiar with the basic purpose of an Expression Tree, but have never used them.
I'm fine if this change would be too expensive to be worthwhile, and this issue is just closed, but if so, could I get a quick two sentence explanation for my own learning why Expression Trees are required? 😃 

Thanks for the awesome tool! 😁

**Comment by jnyrup** [comment]
We use an `Expression<Func<T, bool>>` instead of a plain `Func<T, bool>` to give more descriptive failure messages by including [`predicate.Body`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.lambdaexpression.body?view=netstandard-2.0#System_Linq_Expressions_LambdaExpression_Body).

Source: https://github.com/fluentassertions/fluentassertions/blob/master/Src/FluentAssertions/Collections/SelfReferencingCollectionAssertions.cs#L462

**Comment by krajek** [comment]
@Balfa could we close this issue? 
There is no practical solution, at least for now. If you would resign from `Expression` then we would lose descriptive failure message anyways. In fact, it is the c# compiler that limit's the functionality, not FluentAssertions. 
Nonetheless, you raised an interesting question, thanks.

**Comment by Balfa** [comment]
Yes, that makes sense. Thanks.

**Comment by weitzhandler** [comment]
I just bumped into the same scenario, and interestingly, also using Moq.
The workaround that worked for me is:

```c#
x as string != null && !string.IsNullOrWhiteSpace((string)x);
```

Would be happy to hear about better options.
