### ISSUE TITLE
Assert that a large enumerable contains only the very same item n times?

### ISSUE THREAD

**Issue by drauch** [fluentassertions/fluentassertions#914]
I have a collection of 100K sample numbers. In one test case I want to assert that all of them are of the same value. I tried:

    values.Should().AllBeEquivalentTo(5);

This takes quite some time (around five seconds). Which is WAY to long. Is this a bug in the implementation? Why is it taking so long? I think it's the wrong function, but I couldn't find a `.AllBe(5)` for which I was looking for originally.

My workaround now is `values.Distinct().Should().BeEquivalentTo(new[]{5});` but I don't like it because it doesn't express my intent.

Ideas on how to do that properly?

**Comment by dennisdoomen** [comment]
It's a performance bug. The current implementation is using a very naive approach.

**Comment by krajek** [comment]
@dennisdoomen Are you going to fix it or can I jump in?

**Comment by dennisdoomen** [comment]
By all means, jump in

**Comment by krajek** [comment]
@drauch I have just tried to reproduce the problem with following test.
```
[Fact] public void When_some_subject_items_are_not_equivalent_to_expectation_for_huge_table_execution_time_should_still_be_short()
{
	//-----------------------------------------------------------------------------------------------------------
	// Arrange
	//-----------------------------------------------------------------------------------------------------------
	const int N = 1000000;
	var subject = new List<int>(N) {1};
	for (int i = 1; i < N; i++)
	{
		subject.Add(2);
	}

	//-----------------------------------------------------------------------------------------------------------
	// Act
	//-----------------------------------------------------------------------------------------------------------
	Action action = () =>
	{
		try { subject.Should().AllBeEquivalentTo(1); }
		catch (Exception)
		{
			// ignored, we only care about execution time
		}
	};

	////-----------------------------------------------------------------------------------------------------------
	//// Assert
	////-----------------------------------------------------------------------------------------------------------
	action.ExecutionTime().Should().BeLessThan(150.Milliseconds());
}
```
On my machine it always passes, even for more elements than 100K. Could you provide [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve)?

**Comment by drauch** [comment]
Thanks!

**Comment by drauch** [comment]
Are you going to release this soon? :)

**Comment by jnyrup** [comment]
Yes, we're fixing up the last things to get 5.5.0 ready.
https://github.com/fluentassertions/fluentassertions/milestone/12

So stay tuned, we're also eager to get out a new release.
