### ISSUE TITLE
BeEquivalentTo with WithStrictOrdering produces messy failure message

### ISSUE THREAD

**Issue by shuebner** [fluentassertions/fluentassertions#918]
### Description

Comparing collections with option "WithStrictOrdering" produces messy failure messages.

### Complete minimal example reproducing the issue
```csharp
new[] { 1, 2, 3 }.Should().BeEquivalentTo(new[] { 1, 3, 2 }, opts => opts.WithStrictOrdering());
```

### Expected behavior:

Clear failure message about the difference between the lists.

### Actual behavior:

Confusing and malformatted message with wrong statements:

Expected item[1] to be a collection with 3 item(s)Expected item[1] to be 3, but found 2.
Expected item[2] to be a collection with 3 item(s)Expected item[2] to be 2, but found 3.

### Versions

FluentAssertions 5.4.2.0
.NET Framework 4.6.1

**Comment by dennisdoomen** [comment]
> I also found it as part of #920. It is already fixed there.

That would surprise me. I'm still fixing it by changing the way assertion scopes get chained.
