### ISSUE TITLE
double?.Should().BeApproximately is looking for a float?

### ISSUE THREAD

**Issue by ravensorb** [fluentassertions/fluentassertions#922]
I am using 5.4.2 and trying to work with both double and double? type data elements

```
double? d1 = 1.0123;
double expected = 1.01;

d1.Should().BeApproximately(expected, 1.0); <-- this extension doesn't exist
d1.Value.Should().BeApproximately(expected, 1.0) <-- complains that "expected" should be float
```

Shouldn't both work?

**Comment by krajek** [comment]
Hi @ravensorb 
I failed to reproduce your problem. Following code works for me for `5.4.2`. No compile-time nor runtime errors occurred.

```
using FluentAssertions;
namespace FluentAssertionAsCodeSuggestion
{
    class Program
    {
       static void Main()
       {
           double? d1 = 1.0123;
           double expected = 1.01;

           d1.Should().BeApproximately(expected, 1.0);
           d1.Value.Should().BeApproximately(expected, 1.0);
       }
    }
}
```

Could you please prepare [minimal, complete and verifiable example](https://stackoverflow.com/help/mcve)?

**Comment by ravensorb** [comment]
Which version of .NET were you compiling against?

**Comment by ravensorb** [comment]
Here is a screenshot

![Screenshot](https://i.imgur.com/mPIBM6g.png)

And it is from the tests located here: 
https://github.com/Invisionware/Invisionware.Net/tree/master/tests/Invisionware.Net.GeoCoding.Google.Tests

And they are being compiled against .NE 4.7.1 referencing a .NET Standard 2.0 project

**Comment by krajek** [comment]
Thanks, you did not provide MVCE program, but I was able to analyze source code on github. It turns out that the problem occurs when both `subject` and `expected` are `double?`.
MCVE program is following:
```
using FluentAssertions;
namespace DoubleNullableFAProblem
{
    class Program
    {
        static void Main()
        {
            double? d1 = 1.0123;
            double? expected = 1.01;

            d1.Should().BeApproximately(expected, 1.0);
            d1.Value.Should().BeApproximately(expected, 1.0);
        }
    }
}
```

**Comment by jnyrup** [comment]
So your question is whether two new overloads of `BeApproximately` taking a nullable `expectation` should exist, namely

```c#
double actual = ... ;
double? expected = ... ;
actual.Should().BeApproximately(expected, precision);
```

and

```c#
double? actual = ... ;
double? expected = ... ;
actual.Should().BeApproximately(expected, precision);
```

I can't think of an example where the first overload makes much sense as the `actual` value will never be `null`.

On the other hand, the second overload could be nice to have when doing equivalency comparisons.
E.g.

```c#
var actual = new { B = (double?)1 };

var expected = new { B = (double?)2 };

actual.Should().BeEquivalentTo(expected,
    opt => opt.Using<double?>(ctx => ctx.Subject.Should().BeApproximately(ctx.Expectation, 1))
    .WhenTypeIs<double?>());
```

Of course, if any of these overloads are added, they should also be added for `float` and `decimal`.
