### ISSUE TITLE
Does FluentAssertions need a dependency on System.Configuration.ConfigurationManager >=4.4.0 for .NETCoreApp v2.0?

### ISSUE THREAD

**Issue by KarlZ** [fluentassertions/fluentassertions#924]
### Description

I get a NuGet error when trying to restore on the build machine. It says, "Package System.Configuration.ConfigurationManager 4.4.0 is not compatible with netcoreapp2.0 (.NETCoreApp,Version=v2.0). Package System.Configuration.ConfigurationManager 4.4.0 supports: - net461 (.NETFramework,Version=v4.6.1) - netstandard2.0 (.NETStandard,Version=v2.0) One or more packages are incompatible with .NETCoreApp,Version=v2.0.)"
This package is listed as a dependency for FluentAssertions.

### Complete minimal example reproducing the issue

More details here [https://stackoverflow.com/questions/52499907/does-fluentassertions-support-test-projects-that-are-net-core-2-0]

### Expected behavior:

NuGet restore to work on the build machine.

### Actual behavior:

(see Description)

### Versions

* Which version of Fluent Assertions are you using? 5.4.2
* Which .NET runtime and version are you targeting? .NET Core 2.0.

**Comment by dennisdoomen** [comment]
What version of Nuget are you using?

**Comment by KarlZ** [comment]
Detected NuGet version 4.1.0.2450 / 4.1.0

**Comment by dennisdoomen** [comment]
I think you need at least 4.4.

**Comment by KarlZ** [comment]
That did the trick! Thanks so much. I added a task in the pipeline called NuGet Tool Installer and set it to use NuGet 4.4.0 and the very next step, "restore" worked fine.

**Comment by dennisdoomen** [comment]
Great to hear. The NuGet ecosystem can be quite confusing sometimes.
