### ISSUE TITLE
BeEquivalentTo + Excluding  does not work with structs and classes overriding Equals

### ISSUE THREAD

**Issue by Kikimora** [fluentassertions/fluentassertions#937]
FluentAssertions 5.4.2, .net 2.1

`tt1.Should().BeEquivalentTo(tt2, o => o.Excluding(x => x.Field1));` does not work for `struct`. See test case below that demonstrate it works for class with fields but does not work for structs with fields.

```csharp
        public class FF
        {
            public string Field1;
            public string Field2;
        }
        
        public struct SS
        {
            public string Field1;
            public string Field2;
        }

        [Test]
        public void FFT()
        {
            var tt1 = new FF() {Field1 = "1", Field2 = "Same"};
            var tt2 = new FF() {Field1 = "2", Field2 = "Same"};
            tt1.Should().BeEquivalentTo(tt2, o => o.Excluding(x => x.Field1));
        }
        
        [Test]
        public void SST()
        {
            var tt1 = new SS() {Field1 = "1", Field2 = "Same"};
            var tt2 = new SS() {Field1 = "2", Field2 = "Same"};
            tt1.Should().BeEquivalentTo(tt2, o => o.Excluding(x => x.Field1));
        }
```

**Comment by Kikimora** [comment]
I guess this happens because FluentAssertions compares structs as other value types using Equals and ignores `o => o.Excluding(x => x.Field1)` configuration.

**Comment by dennisdoomen** [comment]
Your assumption is correct. You should be able to change that using the `ComparingByMembers` option.

**Comment by Kikimora** [comment]
I find this quite counterintuitive, I think `ComparingByMembers` should be on by default for structures.

**Comment by dennisdoomen** [comment]
I disagree. See https://www.continuousimprover.com/2018/02/fluent-assertions-50-best-unit-test.html#redefining-equivalency

**Comment by Kikimora** [comment]
You making sound point, that types which override `Equals` should be compared with `Equals`. This unfortunately comes with inconsistency, since suddenly `o => o.Excluding(x => x.Field1)` does not work for structs for no apparent reason. Either exception should be thrown or assertions can switch to `ComparingByMembers` automatically when user request `Excluding` or similar option. I think that would make a better API and user experience.

**Comment by dennisdoomen** [comment]
Hmm, I see your point. I need to think about that.

**Comment by Kikimora** [comment]
I was hit by same issue second time today, this time with classes overriding equals :(

**Comment by bacar** [comment]
+1 to this. The statement as coded does not appear to be meaningful for the given types and indicates a programming error - it should ideally fail compilation or at worst fail at runtime with an obvious error, if automatically switching to `ComparingByMembers` is not desirable.

**Comment by dmytro-gokun** [comment]
@dennisdoomen  I has been bitten by this today. It's really not very intuitive behavior. Also, it's error prone. As soon as i change my "class" to a "struct" (or vice versa) part of my unit tests start to fail.

IMO, it would make much more sense to add ComparingByMembers() automaticaly if "actual" value is a "struct".

**Comment by dennisdoomen** [comment]
> As soon as i change my "class" to a "struct" (or vice versa) part of my unit tests start to fail.

Are you referring to the `Excluding` problem mentioned in this issue? Or about something else?

**Comment by dmytro-gokun** [comment]
@dennisdoomen Well, my problem was a bit different, but i think the root cause is the same. Here's some code:

```
class C
{
     public double X { get;set; }
}

struct S
{
     public C C { get;set; }
}

var expected = new S { C = new C { X = 0} };
var actual = new S { C = new C { X = 0} };
actual.Should().BeEquivalentTo(expected); // Does not work
actual.Should().BeEquivalentTo(expected, o => o.ComparingByMembers<S>()); // Works
```

**Comment by dennisdoomen** [comment]
Yeah, this is by design. A `struct` is a value type and thus has value semantics, and FA honors that. And indeed, nothing to do with the current issue.

**Comment by dennisdoomen** [comment]
I've investigated options to implement this, but I've concluded that this is going to need a major overhaul of the way `ISelectionRule` works. Those are not tightly coupled to a specific type, so evaluating whether some rules apply to a value type will mean that FA must run all of them against a value type, just to see if specific properties were selected.
