### ISSUE TITLE
NotThrow with wait time

### ISSUE THREAD

**Issue by frederik-h** [fluentassertions/fluentassertions#940]
As far as I know, fliuentassertions contains no equivalent to NUnit's [DelayedConstraints](https://github.com/nunit/docs/wiki/DelayedConstraint) which allows to specifiy that a condition should be satisfied after a certain wait time.
I am using an overload of ActionAssertions.NotThrow which takes additional waitTime and pollingInterval parameters to achieve a similar effect. That is, it repeatedly executes the Action every pollingInterval milliseconds, catching any exceptions, until the Action either stops throwing exceptions or the waitTime has passed. In the latter case, it fails with an exception.

I was wondering if there is some interest to include this functionality in fluentassertions?

**Comment by dennisdoomen** [comment]
Could you give us an example of what this would look like?

**Comment by frederik-h** [comment]
@dennisdoomen Sure. Let's consider the following artificial example:

```         var watch = Stopwatch.StartNew();
            Action throwForSomeTime = delegate {
                    if(watch.ElapsedMilliseconds < 1000)
                            throw new Exception("Not yet done.");
            };

            throwForSomeTime.Should().NotThrow(1100, 50);
            Console.WriteLine("Action stopped throwing as expected.");
```

Here the assertion would succeed and return after about 1000ms since the Action stops throwing an exception after 1000ms. The second argument of NotThrow is the polling interval, i.e. the Action will be executed every 50ms until it succeeds or the maximum wait time of 1100ms is exceeded.

If we change the Action to throw for, say, 1200ms, the assertion would fail with 
an exception:  `Unhandled Exception: FluentAssertions.Execution.AssertionFailedException: Did not expect any exception after 1100 milliseconds, but found System.Exception with message "Not yet done."
`

If you have tests which have to wait, for instance, for some network service to become available, the easiest thing to do is to insert a sleep into your code. This is not ideal since your tests will always have to wait for a fixed time, even if your service becomes available much more quickly. Implementing the polling in each test is quite cumbersome.

**Comment by frederik-h** [comment]
Sure, it has to be decided what should be used to achieve the delay in the implementation. I currently use `Task.Delay` for this. Another question is what would be the best name for the method? Should it be an overload of `NotThrow` or would `NotThrowAfter` be clearer?

**Comment by dennisdoomen** [comment]
I like `Should().NotThrowAfter`

**Comment by eajhnsn1** [comment]
I am also struggling to test some asynchronous code.  Along the lines of NotThrowAfter, would it be possible to do something like the following, to gain delayed assertions?:

Should().Eventually(timeout).AllOtherAssertions().

**Comment by frederik-h** [comment]
@eajhnsn1 It should be possible to implement a variant of `Should().NotThrowAfter` which works for `Func<Task>`, although that is not part of the current proposal. Would that help?

**Comment by eajhnsn1** [comment]
What I have in mind wouldn't involve any exceptions.  The code being tested is performing some other wait, which should completed after no more than X time has passed.  

Having never looked into the internals of FluentAssertions, I don't even know if the following makes sense, but is what I would want Should().Eventual(timeout).AllOtherAssertions() to do:

- Periodically run AllOtherAssertions
  - If they pass, good
  - If they fail, sleep for some period of time and retry AllOtherAssertions
  - if the accumulated wait time surpass the timeout, fail the test

**Comment by frederik-h** [comment]
> What I have in mind wouldn't involve any exceptions. The code being tested is performing some other wait, which should completed after no more than X time has passed.
> ... sense, but is what I would want Should().Eventual(timeout).AllOtherAssertions() to do: ...

What you describe sounds like `NotThrowAfter` (for synchronous code). To see this, it is necessary to understand that a failing assertion raises an exception. This means you could implement the described behavior by writing something like `(() => AllOtherAssertions()).Should().NotThrowAfter(timeout, pollInterval)`.

**Comment by frederik-h** [comment]
@eajhnsn1 `NotThrowAfter` has been included in the latest release of Fluent Assertions. You can give it a try and see if it does what you need.

**Comment by skarllot** [comment]
Should include `ThrowBefore` too

**Comment by mazharenko** [comment]
If someone is interested in a way to delay any other assertions, which I was eager to get for end-to-end tests, they might like the following approach:
```cs
Action throwForSomeTime = delegate {
      if(watch.ElapsedMilliseconds < 1000)
              throw new Exception("Not yet done.");
};

foreach (var _ in EventualAssertions.Attempts(1400, 50))
{
    throwForSomeTime.Should().NotThrow();
}
```

`EventualAssertions.Attempts` returns an `IEnumerable` which returns an `IEnumerator` which:
1. Wraps an `AssertionScope`
2. On each new trivial element checks the scope
3. If there are errors in the scope, discards them, waits a specified time and returns another trivial element
4. If there are no errors in the scope, returns nothing

So, any failed assertion among those in the `foreach` body will cause another attempt, if the time budget has not expired.

Its appropriate `MoveNext` method can look like the following (aux types, declarations omitted):
```cs
    public bool MoveNext()
    {
        stopwatch.Start();
        
        switch (state)
        {
            case State.Initial:
                Current = new Attempt();
                state = State.Waiting;
                return true;
            case State.Waiting:
                if (assertionScope is null || !assertionScope.HasFailures())
                    return false;
                if (stopwatch.Elapsed > timeBudget)
                {
                    assertionScope.Discard();
                    assertionScope.Dispose();
                    assertionScope = null;
                    state = State.LastTry;
                    Current = new Attempt();
                    return true;
                }
                assertionScope.Discard();
                
                Thread.Sleep(delay);
                
                Current = new Attempt();
                return true;
            case State.LastTry:
                return false;
            default:
                throw new InvalidEnumArgumentException();
        }
    }
```

The complete example is in the [gist](https://gist.github.com/mazharenko/e4c470cd7a69bcb533b13046968af5b5), a bit more including async and docs &ndash; in my [repo](https://github.com/mazharenko/FluentAssertions.Extensions).
