### ISSUE TITLE
Using Fluentassertions in .net vb

### ISSUE THREAD

**Issue by Mexanikus2006** [fluentassertions/fluentassertions#983]
### Description

I have some issues with using Fluentassertions in .net visual basic.

Can anyone send me links, documentation or examples how to use it to compare objects excluding some members ( in statements like this resultObject.Should.BeEquivalentTo(expectedObject) ) ?

Function override shows this form 
![image](https://user-images.githubusercontent.com/45478716/49273811-9b6e5500-f48f-11e8-9dfd-375abf5e2e7d.png)

### 
```vb.net
Class A
    Property MemberToCompare As Integer
    Property MemToAvoid As DateTime
End Class

// Assert
        Dim Result As New A
        Dim Expected As New A
        With Result
            .MemberToCompare = 5
            .MemberToAvoid = New DateTime(2015, 3, 19, 14, 47, 35)
        End With
        With Expected
            .MemberToCompare = 5
            .MemberToAvoid = New DateTime(2011, 1, 1, 15, 1, 1)
        End With

        result.Should.BeEquivalentTo(Expected)
```
### Expected behavior:
I want to compare these objects excluding MemberToAvoid and get OK

### Actual behavior:
I get error

### Versions
FluentAssertions    version=5.4.2
.NET framework 4.7.02053

**Comment by jnyrup** [comment]
From the [documentation](https://fluentassertions.com/documentation/#selecting-members) in the section about "Object graph comparison":
```c#
orderDto.Should().BeEquivalentTo(order, options => 
    options.Excluding(o => o.Customer.Name));
```

**Comment by Mexanikus2006** [comment]
Thank you Jonas for Reply, but this is not case for visual basic .net. 
I have read the documentation and cannot find how to write it in my case.

**Comment by jnyrup** [comment]
The documentation is written with C# examples, so in Visual Basic the same code can be written as
```vb
Result.Should().BeEquivalentTo(Expected,
    Function(opt) (opt.Excluding(Function(o) (o.MemberToAvoid))))
```

**Comment by jnyrup** [comment]
Closing for now.
Feel free to re-open if my answer didn't solve your problem.
If your problem is not about an issue in Fluent Assertion, but *how* to use Fluent Assertions in VB.net StackOverflow might be a better/quicker resource to use.
