### ISSUE TITLE
BeEquivalent() is not working when Excluding members from an FSharp Record

### ISSUE THREAD

**Issue by erlis** [fluentassertions/fluentassertions#988]
### Description

Using Should().BeEquivalent() fails when excluding members that are define in an FSharp record

### Complete minimal example reproducing the issue

define a record in Fsharp and use it in a Should().BeEquivalent() excluding one of the fields, make everything the same except the field you are excluding and it fails when it should pass. 

Excluding is not working for Fsharp records.

**Comment by jnyrup** [comment]
Hi @erlis 

From your sparse issue description I have very little clue on what went wrong.
You didn't post a *complete minimal example*, that means actual code I can copy/paste into e.g. Visual Studio and run, so I'll have to guess what problem you're having.

I haven't done F# before, but I tried reproducing your issue

```fs
open FluentAssertions
open FluentAssertions.Equivalency

type A = { includeMe: int; excludeMe: int }

[<EntryPoint>]
let main argv =
    let actual = { includeMe = 42; excludeMe = 1}
    let expected = { includeMe = 42; excludeMe = 2}

    let config (opt : EquivalencyAssertionOptions<A>) : EquivalencyAssertionOptions<A> = 
        opt.Excluding(fun (o : A) -> o.excludeMe :> obj)

    actual.Should().BeEquivalentTo(expected, config, "")

    0
```

and got this error
```
Expected object to be {includeMe = 42;
 excludeMe = 2;}, but found {includeMe = 42;
 excludeMe = 1;}.

With configuration:
- Use declared types and members
- Compare enums by value
- Exclude member root.excludeMe
- Match member by name (or throw)
- Without automatic conversion.
- Be strict about the order of items in byte arrays

```

Now we need *your* help.
1. Is that the same error that you're experiencing?
2. If not, please post:
  a) An example like mine above, that shows your problem
  b) The error you're experiencing.

**Comment by jnyrup** [comment]
As record types overrides `Equals(object)` Fluent Assertions per default does not perform a structural equivalency check.
To do this, and thereby respecting the `Excluding`, use [`ComparingByMembers()`](https://fluentassertions.com/documentation/#value-types):
```f#
type MyRecord = { includeMe: int; excludeMe: int }

let actual = { includeMe = 42; excludeMe = 1}
let expected = { includeMe = 42; excludeMe = 2}

let config (opt : EquivalencyAssertionOptions<MyRecord>) : EquivalencyAssertionOptions<MyRecord> = 
    opt.Excluding(fun (o : MyRecord) -> o.excludeMe :> obj)
       .ComparingByMembers()

actual.Should().BeEquivalentTo(expected, config, "")
```

**Comment by erlis** [comment]
Hi Jonas, 

To test this you don't have to code in FSharp, you can do your test in C# as usual, just declare the Record in FSharp and you will have the result you are posting. This is what I'm doing, I'm defining some value types in Fsharp and coding in C#.  

I'll give it a try to the ComparingByMembers. I was not aware of it. I always though that Should().BeEquivalentTo() was doing exactly that.... Comparing by members. Can you explain in what scenario .BeEquivalentTo() won't be comparing by members? 

Thanks for the response! 
Erlis

**Comment by jnyrup** [comment]
The function that determines the default comparison strategy is `HasValueSemantics()`
https://github.com/fluentassertions/fluentassertions/blob/1b796f84f62cb54a237b8f4f81968ca5d892ae4d/Src/FluentAssertions/Common/TypeExtensions.cs#L415-L419

That behavior can be overridden with either `ComparingByMembers()` or `ComparingByValue()`.

**Comment by maradik** [comment]
How can I globally setup the strategy to using ComparingByMembers for all reference types (ignore condition type.OverridesEquals())?

**Comment by dennisdoomen** [comment]
```
AssertionOptions.AssertEquivalencyUsing(options => options
    .ComparingByValue<DirectoryInfo`());
```

See also https://fluentassertions.com/documentation/

**Comment by jnyrup** [comment]
@erlis I'm glad you found a solution.
Yes, Fluent Assertions also compares `internal` when using `BeEquivalentTo`.
