### ISSUE TITLE
Assertions for Func<Task<T>>

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions#990]
Currently both `Func<Task>` and `Func<Task<T>>` are handled by `AsyncFunctionAssertions` which has a `Subject` of type `Func<Task>` and hence ignores the return value for `Func<Task<T>>`.

If we split `AsyncFunctionAssertions` into:
* `AsyncFunctionAssertions` for `Func<Task<T>>`, and
* `AsyncActionAssertions` for `Func<Task>`

That should enable us to return the result of `Task<T>` for further assertions, similar to what was implement ed for `Func<T>` in #951, such as:

```c#
// Arrange/Act
Func<Task<int>> func = () => Task.FromResult(42);

// Assert
func.Should().NotThrow().Which.Should().Be(42);
(await func.Should().NotThrowAsync()).Which.Should().Be(42);
```

This was inspired by this [question](https://stackoverflow.com/questions/54092547/chceck-return-value-in-fluentassertion-exception-syntax)

**Comment by dennisdoomen** [comment]
Yeah, sounds like a good idea.

**Comment by lg2de** [comment]
I would like to combine this extension with an additional feature:
```c#
func.Should().Complete(TimeSpan.FromMilliseconds(100));
```

The test would fail if the Task does not complete within specified time span.

What do you think about such feature?

**Comment by dennisdoomen** [comment]
That's a nice idea, and a very useful one as well.

**Comment by lg2de** [comment]
While thinking about the implementation I would like to check whether my "Complete" extension should be based on `Func<Task<T>>` or maybe better on `Task<T>`.
The latter would result into easier usage:
```c#
this.myServer.OpenAsync().Should().Complete(TimeSpan.FromMilliseconds(100));
```

In this case my changes would not touch anymore the refactoring mentioned by @jnyrup.

**Comment by jnyrup** [comment]
@lg2de I would prefer if you opened a new issue with an API proposal describing the purpose of the functions and their function signatures.
