### ISSUE TITLE
Extensions for HttpResponseMessage

### ISSUE THREAD

**Issue by balanikas** [fluentassertions/fluentassertions#994]
### Extensions for HttpResonseMessage to be used in rest api tests

I have written a few custom extensions that can be used in integration tests targeting rest apis.
They are meant to be used in typically these scenarios:

```csharp
var model= new RestModel();
PostResource(model);
HttpResonseMessage response = GetResource();

//assert
response.Should().Be200();
response.Should().HaveBody(model);
```

Since testing rest apis is quite common, I would like to contribute those into fluentassertions in some forms. 
However, i am not sure if this repository is the best place, or if they should be compiled into 
a separate library with a dependency on the core fluentassertions package. Unfortunately i don't have the time to maintain a github project on my own.

Here are some examples, that you will hopefully find useful.

```csharp
_httpResponseMessage.Should().Be200(); // there is support for even more common status codes
```

```csharp
_httpResponseMessage.Should().HaveBody(restModel); 
```

```csharp
_httpResponseMessage.Should().HaveBodyExcluding(_restModel, x => x.PropertyToExclude); 
```

```csharp
_httpResponseMessage.Should().HaveBodyIncluding(_restModel, x => x.PropertyToInclude); 
```
```csharp
_httpResponseMessage.Should().HaveBodyWithProperty<RestModel>(x => x.MyProperty, expectedValue);
```

```csharp
_httpResponseMessage.Should().ContainText("\"MyProperty\":5");
```

```csharp
_httpResponseMessage.Should().NotContainText("\"MyProperty\":5");
```

This targets the full .net framework, and tested on net461
I am using FluentAssertions 5.4.2

**Comment by balanikas** [comment]
Thanks for feedback, and I agree with your reasoning.
I created this separate package instead, https://www.nuget.org/packages/FluentAssertions.Http/1.0.0-beta1

Can I close this issue now? Or should I leave it?

**Comment by dennisdoomen** [comment]
No, it can be closed.

**Comment by dennisdoomen** [comment]
If you link me to an announcement tweet of some kind, let me know. I'll retweet.

**Comment by balanikas** [comment]
Thanks @dennisdoomen I will let it mature a bit and then let you know
