### ISSUE TITLE
ShouldBeEquivalentTo gives false positive for values not implementing IConvertible

### ISSUE THREAD

**Issue by nvirth** [fluentassertions/fluentassertions#995]
### Description

`ShouldBeEquivalentTo` gives false positive for values not implementing `IConvertible`

### Complete minimal example reproducing the issue

Please check code below:

```csharp
[TestFixture]
public class TestsClass
{
    [Test]
    public void TheTest()
    {
        var result = new TestClass() {Value = new MyNotConvertibleClass()};
        var expected = new TestClass() {Value = new string[0]};

        result.ShouldBeEquivalentTo(expected); // [1]
    }
}

class TestClass
{
    public object Value { get; set; }
}

class MyNotConvertibleClass
{
}
```

Here, at `// [1]`, the assertion does not fail, the test succeeds.

### Expected behavior:

Assertion should fail at `// [1]`, because Value properties have different values

### Actual behavior:

Assertions does not fail

### Versions

`<package id="FluentAssertions" version="4.0.0" targetFramework="net46" />`

### Additional Information

I can see a handled exception at `// [1]` within the function call: `System.InvalidCastException: Object must implement IConvertible.`
Thus I think comparison of Value properties is skipped.

**Comment by jnyrup** [comment]
Is it possible for you to upgrade to Fluent Assertions 5.x.x?
From version 4 to 5 we reworked `ShouldBeEquivalentTo` a *lot* to work more as expected.
For more information, see https://www.continuousimprover.com/2018/02/fluent-assertions-50-best-unit-test.html#moving-towards-a-unified-api

**Comment by nvirth** [comment]
Thank you for the information!
We will schedule an upgrade.
Until that, I'm closing this issue now; if still reproducible after the upgrade, I will reopen it.
