### ISSUE TITLE
Subset assertion for complex object collection

### ISSUE THREAD

**Issue by pooventhan** [fluentassertions/fluentassertions#996]
Hi,

I'm trying to verify if a collection is a subset of another.

```csharp
var expectedList = new List<ApiResponse>
{
	new ApiResponse { Id = "5678", Length = 5 },
	new ApiResponse { Id = "1234", Length = 3 }
};

var actualList = new List<ApiResponse>
{
	new ApiResponse { Id = "1234", Length = 3 },
	new ApiResponse { Id = "5678", Length = 5 },
	new ApiResponse { Id = "9119", Length = 7 }
};

expectedList.Should().BeSubsetOf(actualList); // Throws exception
actualList.Should().Contain(expectedList); // Throws exception
```
Both assertions above does not produce expected outcomes. 

However, if the collections are made up of simple type, both assertions above produce expected outcomes.
```csharp
var expectedList = new List<string> { "5678", "1234" };
var actualList = new List<string> { "1234", "5678", "9119" };

expectedList.Should().BeSubsetOf(actualList); // Succeeds
actualList.Should().Contain(expectedList); // Succeeds
```
**Versions**
- FluentAssertions: 5.6.0
- .NET Core 2.1

Is there any configuration required to assert collection of complex objects?
Appreciate if anyone could help to shed some light.

Thanks in advance!

**Comment by dennisdoomen** [comment]
That's because those APIs use the object's `Equals` implementation. Your `ApiResponse` probably doesn't. So unless you're willing to "pollute" your classes with an `Equals` implementation, there's no such API. The closests to that is `Should().BeEquivalentTo` which does compare entire object graphs. See https://fluentassertions.com/documentation/#object-graph-comparison

**Comment by pooventhan** [comment]
Hi @dennisdoomen,

Thanks for the clarification. I've worked around this without overriding the `Equals` implementation. 

```csharp
foreach (var item in expectedList)
{
   actualList.Should().ContainEquivalentOf(item);
}
```

**Comment by dennisdoomen** [comment]
If you do it like that, you don't need to override `Equals`. `ContainEquivalentTo` will do a structural comparison of the properties of each object.

**Comment by adrianiftode** [comment]
Is there an overload for ```actualList.Should().ContainEquivalentOf(expectedList);```

**Comment by InspiringCode** [comment]
> Is there an overload for `actualList.Should().ContainEquivalentOf(expectedList);`

I also would have needed this feature quite often... Is there any workaround?
