### ISSUE TITLE
Ordering assertions in CollectionAssertions should use IComparer, not IComparer<object>

### ISSUE THREAD

**Issue by m-ringler** [fluentassertions/fluentassertions#998]
### Description
The ordering assertions in `CollectionAssertions` expect an `IComparer<object>`, although the declared type of the items in the collection does not need to be object. This makes it hard to use standard comparers such as `StringComparer` and comparers derived from `Comparer<T>`.

### Complete minimal example reproducing the issue

The following does not compile:

```cs
string[] actual = { "a", "b", "c" };
actual.Should().BeInAscendingOrder(StringComparer.CurrentCultureIgnoreCase);
```

### Expected behavior:

* You should be able to use a comparer that implements `IComparer<T>` for a generic collection with items of type `T`.
* You should be able to use a comparer that implements `IComparer` for a non-generic collection.

### Actual behavior:

Does not compile.

### Versions

* Which version of Fluent Assertions are you using? v5.6.0
* Which .NET runtime and version are you targeting? .NET framework 4.6.1

**Comment by dennisdoomen** [comment]
We could add an overload that takes an `IComparer`, but I'm not sure if this will cause a compiler ambiguity when you provide a type that implements both `IComparer` and `ICompare<T>`.

**Comment by m-ringler** [comment]
If you have an ambiguity between overloads with `IComparer` and `IComparer<T>` (or `IComparer<object>` if you want to keep that for backwards compatibility) you can always disambiguate by casting the actual comparer object to the desired interface:
`actual.Should().BeInAscendingOrder((IComparer)myComparer); `

If one overload is a generic method (`GenericCollectionAssertions.BeInAscendingOrder<T>(...)`), and the other is not (`CollectionAssertions.BeInAscendingOrder(...)`) you can also disambiguate by adding the type argument to the method call:
`actual.Should().BeInAscendingOrder<string>(StringComparer.CurrentCultureIgnoreCase);`

**Comment by dennisdoomen** [comment]
True, but technically that would be a breaking change.

**Comment by m-ringler** [comment]
It should be possible to add something like `BeInAscendingOrder<T>(IComparer<T>)` to `GenericCollectionAssertions<T>` without compiler errors. There would be no ambiguity because overload resolution prefers the method in the derived class to the base class method (see section Inheritance in http://www.csharpindepth.com/Articles/General/Overloading.aspx and code example below).

It would still be a breaking change, however, for the unlikely cases where a comparer explicitly implements both `IComparer<object>`and e. g. `IComparer<string>` and those implementations differ. In such a case, the `IComparer<string>` implementation would be used instead of the `IComparer<object>` implementation.

The following program compiles and prints `IComparer<String>`.
```
using System;
using System.Collections;
using System.Collections.Generic;

namespace myApp
{
    public class Program
    {
        static void Main(string[] args)
        {
            args.Should().BeInAscendingOrder(new SomeComparer());
        }
    }

    public static class Extensions
    {
        public static GenericCollectionAssertions<T> Should<T>(this IEnumerable<T> collection)
        {
            return new GenericCollectionAssertions<T>();
        }
    }

    public class SomeComparer : IComparer, IComparer<string>, IComparer<object>
    {
        public int Compare(object x, object y)
        {
            throw new NotImplementedException();
        }

        public int Compare(string x, string y)
        {
            throw new NotImplementedException();
        }
    }

    public class CollectionAssertions
    {
        public void BeInAscendingOrder(IComparer<object> comparer)
        {
            Console.WriteLine("IComparer<object>");
        }
    }

    public class GenericCollectionAssertions<T> : CollectionAssertions
    {
        public void BeInAscendingOrder(IComparer<T> comparer)
        {
            Console.WriteLine("IComparer<" + typeof(T).Name + ">");
        }
    }
}
```

**Comment by m-ringler** [comment]
An overload with `Comparison<T>` would avoid the breaking change entirely and also address the problem. For then we could write
`actual.Should().BeInAscendingOrder(StringComparer.CurrentCultureIgnoreCase.Compare);`
with the downside that that's not very obvious.

**Comment by jnyrup** [comment]
`GenericCollectionAssertions` already has three overloads of `BeInAscendingOrder`.
One that takes an [`Expression<Func<T, TSelector>> propertyExpression`](https://github.com/fluentassertions/fluentassertions/blob/a144189242ec4bf796041c3292072aca67951938/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs#L126) allowing you to write
```c#
actualPersons.Should().BeInAscendingOrder(p => p.Age)
```

one overload that takes an [`IComparer<T>`](https://github.com/fluentassertions/fluentassertions/blob/a144189242ec4bf796041c3292072aca67951938/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs#L146) allowing you to write
```c#
new[] { 42, 43 }.Should().BeInAscendingOrder(Comparer<int>.Default)
```

and lastly one that takes [both](https://github.com/fluentassertions/fluentassertions/blob/a144189242ec4bf796041c3292072aca67951938/Src/FluentAssertions/Collections/GenericCollectionAssertions.cs#L169).

From the first post, the problem seems to be that `StringCollectionsAssertions` doesn't have those overloads but only offers those from `CollectionAssertions`.

**Comment by m-ringler** [comment]
Ah ok, sorry. I had assumed that what you get from stringArray.Should() was an instance of `GenericCollectionAssertions<string>` or a subclass. Then it's really just an issue with string collections.

**Comment by jnyrup** [comment]
No worries, I've been confused about that before as well. 

For some future major release I hope we can overhaul the collection assertions more.
